### ISSUE TITLE
Chrome WebDriver does not support capture screenshot

### ISSUE THREAD

**Issue by desertblade** [robotframework/SeleniumLibrary#1]
Install Chrome webdriver from http://code.google.com/p/chromium/downloads/list

Use the Capture Page Screenshot keyword

Error in RF Log:
KEYWORD: Selenium2Library.Capture Page Screenshot
Documentation:  Takes a screenshot of the current page and embeds it into the log.
Start / End / Elapsed:  20111103 05:01:45.742 / 20111103 05:01:45.760 / 00:00:00.018
05:01:45.760    FAIL    AttributeError: 'WebDriver' object has no attribute '_execute'
05:01:45.760    WARN    Keyword 'Capture Page Screenshot' could not be run on failure: AttributeError: 'WebDriver' object has no attribute '_execute'

This is also an issue when you have the Capture Page Screenshot on fail

**Comment by rtomac** [comment]
Hi desertblade,

Thanks for logging this issue. I hope to take a look at this in the next 24 hours.

Ryan

**Comment by SteveElliott** [comment]
Did anything happen in that 24Hrs?  ;)

I am trying to run robotframework-2.6.3 with robotframework-selenium2library-0.5.2 & chromedriver_linux64_17.0.963.0 all under Fedora 16 xfce.

Capture Page Screenshot fails with 
Open Browser <url> chrome

but succeeds with
Open Browser <url> ff

Steve

**Comment by adwu73** [comment]
you can find the fix in issue 7

**Comment by SteveElliott** [comment]
Thanks for that response.

I had followed down that chain and posted my results at
https://github.com/hali4ka/robotframework-selenium2library/commit/cfb5e594aa
5b74a04053c97efc439d3ddd752387

Regards

Steve

-----Original Message-----
From: adwu73
[mailto:reply+i-2134390-93d838215947d500668e01c597ff14e832f41be1-1302906@rep
ly.github.com] 
Sent: Thursday, 5 January 2012 1:25 PM
To: SteveElliott
Subject: Re: [robotframework-selenium2library] Chrome WebDriver does not
support capture screenshot (#1)

you can find the fix in issue 7

---

Reply to this email directly or view it on GitHub:
https://github.com/rtomac/robotframework-selenium2library/issues/1#issuecomm
ent-3364745
