### ISSUE TITLE
It's time to bring Start Server back

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#100]
In latest webdriver version, a IEDriverServer.exe can be started seperately, and you have to register a call back to kill the process if the test fail. It seems that  we can bring Start Server keyword back to allow the configuration of the IEDriverServer.exe and also register the call back. Here is the example java code:

```
System.setProperty("webdriver.ie.driver",
            "C:\\IEDriver\\IEDriverServer.exe");

    try {
        service = new InternetExplorerDriverService.Builder()
                .usingAnyFreePort()
                .withLogFile(new File("C:\\IEDriver\\iedriver.log"))
                .withLogLevel(InternetExplorerDriverLogLevel.INFO).build();
        service.start();
    } catch (IOException e) {
        throw Throwables.propagate(e);
    }

    Runtime.getRuntime().addShutdownHook(new Thread() {
        @Override
        public void run() {
            service.stop();
        }
    });
```

**Comment by ombre42** [comment]
With the keyword _Create Webdriver_ that will be in 1.5, you will be able to pass parameters to the ie webdriver's init. This will allow you to set the log level of IEDriverServer, specify exe location, and more. The webdriver init has all the parameters for the service and creates a service instance so there is no need to construct your own service.See the [docstring for Create Webdriver](https://github.com/rtomac/robotframework-selenium2library/blob/8c8247f6742e4ab6302eee82749ea14ec5b12920/src/Selenium2Library/keywords/_browsermanagement.py#L151) for an example of starting IEDriverServer with specific parameters.

Stopping the server is taken care of by Close All Browsers or Close Browser, so use one of them as a teardown or inside a user teardown keyword.
