### ISSUE TITLE
Improve exception raised by the library

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1000]
In most of the cases we raise `ValueError` or `AssertionError`. The exceptions where improved in 3.0.0 release, in commits: 4e481994, 51e2c2d1, cb40630a and dc875cfe, but it would be good to take closer look on the exceptions the library raises. It would be best to unify the exceptions that we raise and make them more useful also the be used in the programmatic way. One example of where the exception could be improved in explained in #997

**Comment by pekkaklarck** [comment]
My opinion about exception is as follows:

1. We should use the standard [ValueError](https://docs.python.org/2/library/exceptions.html#exceptions.ValueError) if a user provides an argument that has invalid value. If it's of invalid type altogether, we can use [TypeError](https://docs.python.org/2/library/exceptions.html#exceptions.TypeError). This is the same logic Python uses. We shouldn't try to validate all arguments, though, so in practice there could be, for example, [AttributeError](https://docs.python.org/2/library/exceptions.html#exceptions.AttributeError) if a user gives `int` and we use it like `arg.upper()`.

2. We should use [AssertionError](https://docs.python.org/2/library/exceptions.html#exceptions.AssertionError) with *all* keywords validating something when the validation fails. Such keywords may raise other exceptions too, for example, if arguments are invalid.

3. If there's an error situation trying to do something, we can use our own exceptions like `ElementNotFound`. If there's no good exception, [RuntimeError](https://docs.python.org/2/library/exceptions.html#exceptions.RuntimeError) is OK, but I'd like to reduce its usage.

4. With *Wait* keywords I'm not 100% sure what to do. My current thinking is that they should raise `AssertionError` like *Should* keywords do, like they also do nowadays, and like Robot's *Wait* keywords do. I can see there's a semantic difference between *Wait* and *Should* keywords, but I'm not sure is it big enough to warrant different exceptions. I think all *Wait* keywords should use the same exception type, though.

**Comment by aaltat** [comment]
Most likely I don't have time to do this in the near future. Closing
