### ISSUE TITLE
Can not call methods which uses @keyword decorated methods to change the keyword name from the library instance when extending library

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1001]
When doing this: 
```
from SeleniumLibrary import SeleniumLibrary


lib = SeleniumLibrary()
print lib.keywords.get('get_webelements')
```
the print should not display `False`, instead it should return the method. Now the `print lib.keywords.get('Get WebElements')` return the method, which is hard to use in Python side. 

This needs fixing in the https://github.com/robotframework/PythonLibCore/issues/2 side

**Comment by pekkaklarck** [comment]
This was a regression during 3.0 development so it doesn't really belong to final 3.0 scope.
