### ISSUE TITLE
Document how to extend the library

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#1007]
The new architecture in SL 3.0 (#771) is likely to break lot of external libraries using SL internally somehow. Explicitly exposing and documenting the public API (#882) helps, but we should still document different approaches how to interact with the library and how to safely extend it. Examples are going to be very valuable.

**Comment by pekkaklarck** [comment]
If you are a maintainer of a library that is broken due to the changes in SL 3.0, please report your problems here, on robotframework-users mailing list, or on Slack.

https://groups.google.com/group/robotframework-users
https://robotframework-slack-invite.herokuapp.com/

**Comment by aaltat** [comment]
There are many libraries which already extend the Selenium2Library in one way or other. It would be good to have links to point to other projects which go nicely together with SL. Like in #638

1) How to extend the library by providing PR with GitHub. This is mostly done in CONTRIBUTING.rst but should provide link to the right place.
2) How to extend the library with inheritance
3) How to get the library instance from Robot Framework
4) How to to extend the library without creating a new library to Robot Framework side.

Put the extending documentation in to the ./docs/extending/ folder.

**Comment by aaltat** [comment]
The #1029  provides initial commit how the extending can be done.

**Comment by aaltat** [comment]
This is done in #1029
