### ISSUE TITLE
'Select Radio Button' fails to change value in IE and doesn't report failure

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#101]
pretty self explanatory, but the command works fine in firefox and chrome

**Comment by Softworks-Consultancy** [comment]
does it work with "regular" selenium i.e. without robot framework?

Also what version of IE?

**Comment by know1nos** [comment]
I have not tried it without robotframework, relatively new to selenium and robotframework alike.  I am currently using IE9.

**Comment by emanlove** [comment]
@know1nos: I recently had an [issue](http://code.google.com/p/selenium/issues/detail?id=4375) for which I needed to test selenium without robotframework.  Here are the steps I took (sorry but they are written for Linux. at least the unittest script is not OS dependent) ...

Setup a python virtual environment to isolate my test environment

```
~$ mkdir se-bug 
~$ cd se-bug
~/se-bug$ virtualenv -p /usr/bin/python2.6 --no-site-packages clean-python26-env
```

Activate the virtual enviroment and install selenium; in this case I specify selenium version 2.25.0 (the version I was having problem with)

```
~/se-bug$ source clean-python26-env/bin/activate
(clean-python26-env) ~/se-bug$ easy_install selenium==2.25.0
```

create a test file ~/se-bug/testExeJS.py

```
import unittest
from selenium import webdriver

class ExecuteJavascriptTestCase(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox()

    def test_exe_javascript(self):
        driver = self.driver
        driver.get("http://www.google.com")
        driver.execute_script("return [ document.location ];")
        print('Finished')

    def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()
```

and run unittest

```
(clean-python26-env) ~/se-bug$ python testExeJS.py
```

In my case I was having issue with Firefox and the 'execute_script' selenium command.  You should be able to create a similar test for the issue you are having.

Also if you provide more of the error output or traceback we might be able to help more.

**Comment by know1nos** [comment]
Thank you, I will go about trying that soon.

As for the error output there is NONE, half the time the command simply does not change the value but reports that there was no error... I don't know if that helps narrow the problem down but I appreciate any and all responses.

**Comment by emanlove** [comment]
There has been some submitted patches (#92) to address the issues of return values and error reporting with the select keywords.  I don't think this patch addresses your specific issue but it's a start. I've added a task (#104) for me to review the return value for all keywords within the library.

Note also I have some [changes](https://github.com/rtomac/robotframework-selenium2library/pull/68) to the select keywords and @schminitz has some performance [patches](https://github.com/emanlove/robotframework-selenium2library/pull/1) which should improve the functionality and speed of the select keywords.

**Comment by emanlove** [comment]
I've retried this under IE9, Selenium 2.37.2 and it works for me. If this is still an issue please reopen this ticket.
