### ISSUE TITLE
Add option to start browser headless in Open Browser keyword

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1014]
Add support for Firefox and Chrome to start with headless mode in `Open Browser` keyword. The headless is quite common need within the user base of the SeleniunLibrary. The headless can be done, by using the `Create WebDirver` keyword but the code in the Robot Framework data is quite horrible. With the Selenium 3.8.0 it is easy to modify the `Open Browser` to support headless mode with Firefox and Chrome.

**Comment by aaltat** [comment]
Done in #1011

**Comment by rsensha** [comment]
I am facing the below error message while running a test script.
(The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Please help as I am stuck with this for few days now.
I am using  Robot framework, SeleniumLibrary, Chrome version 74

**Comment by aaltat** [comment]
Issue tracker is reserved for bugs and enhancement requests, for support: https://github.com/robotframework/SeleniumLibrary#support
