### ISSUE TITLE
Selenium2Library much slower than SeleniumLibrary

### ISSUE THREAD

**Issue by schminitz** [robotframework/SeleniumLibrary#102]
I am using selenium 2.25 and updated my SeleniumLibrary to Selenium2Library, but now tests are **much** slower.

Im am using firefox 13.0.1 on ubuntu 11.10

This logs are pretty explicits I think

```
SeleniumLibrary:
================

KEYWORD: SeleniumLibrary.Select From List name=${prefix}_jour, ${day} Expand All
Documentation:     

Selects `*values` from list identified by `locator`
Start / End / Elapsed:     20120830 15:54:52.805 / 20120830 15:54:52.917 / 00:00:00.112
15:54:52.917     INFO     Selecting values '23' from list 'name=envoi_jour'.



Selenium2Library:
=================

KEYWORD: Selenium2Library.Select From List name=envoi_jour, 4 Expand All
Documentation:    

Selects `*items` from list identified by `locator`
Start / End / Elapsed:     20120830 15:44:44.062 / 20120830 15:44:46.418 / 00:00:02.356
15:44:44.065     INFO     Selecting option(s) '4' from list 'name=envoi_jour'.



Random keyword doing less than 1 second to execute in Selenium2Library: (So its not a 'speed' attribute or something like that the problem no?)
=======================================================================

KEYWORD: Selenium2Library.Input Text name=snun_cde, BLIIII Expand All
Documentation:   

Types the given `text` into text field identified by `locator`.
Start / End / Elapsed:   20120830 15:44:37.490 / 20120830 15:44:38.043 / 00:00:00.553
15:44:37.490   INFO   Typing text 'BLIIII' into text field 'name=snun_cde'
```

**Comment by j1z0** [comment]
Hi Schminitz,

Thanks for the report.  When using standard locators i.e. name Selenium2Library may fall back to using xPath for location.  Can you try explicitly using as css or id selector and see if the results improve.  If not it is possible to share the offending html code and we can have a look.

Cheers,
Jeremy

**Comment by schminitz** [comment]
Hi,

I just tested with id selector and it changes nothing.

The problem might be with how we are trying to get the values of each select element. Like emanlove explains it here:
https://groups.google.com/forum/#!msg/robotframework-users/K_KQJadtuqw/vWsfLu7BNuwJ

I will check that way

Thanx

**Comment by j1z0** [comment]
Ahh I see. I thought Ed had already made the change to select. Let me speak to him and see when we can try to get this fixed for you. Please be patient though as we are both quite busy with other projects but one is us will get to it soon. 

Cheers,
Jeremy

**Comment by schminitz** [comment]
Actually i already began working on it, normally i will commit changes monday. We will see if I did the good way.

Cheers

**Comment by emanlove** [comment]
'Select' keywords were updated under Selenium2Library version 1.1 and performance should be improved.
