### ISSUE TITLE
Selenium2Library import changed to SeleniumLibrary triggers some warnings

### ISSUE THREAD

**Issue by chaussen** [robotframework/SeleniumLibrary#1022]
OS: Win10 Pro build 15063
python: 2.7.13
robot:
robotframework==3.0.2
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.0.1

got warning when running tests
`C:\Python27\lib\site-packages\SeleniumLibrary\utils\seleniumversion.py:19: ImportWarning: Not importing directory 'C:\Python27\selenium': missing __init__.py`

but the tests can pass.

`%PYTHONPATH%` is empty

`%PATH%` is messy. related to robot are probably C:\Python27\ and C:\Python27\Scripts

**Comment by aaltat** [comment]
For some reason, the `C:\Python27\` is in your module search path. Are you any chance running tests from `C:\Python27\`? When starting Robot Framework execution, are you using `--pythonpath` option and does it point to the `C:\Python27\`?

**Comment by chaussen** [comment]
no. my command is run from sublime text:

`["python","-W","once", "-m", "robot.run","-d","outputs", "-T", "--include", "complete", "--debugfile", "debug.log","$file_path"]`

the `-W` is used ignore the requests warnings.

**Comment by aaltat** [comment]
Ah, Sublime has it's own settings for resolving modules. Are you using some plugin or a build system?

**Comment by aaltat** [comment]
And could you run the same test from Windows command line.

**Comment by aaltat** [comment]
This was discussed in slack channel and the warning is OK. Therefore closing this issue.
