### ISSUE TITLE
Focus keyword does not work on chrome

### ISSUE THREAD

**Issue by lyqingme** [robotframework/SeleniumLibrary#1028]
(Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86)
    @keyword
    def find_element_focus(self, locator):
        element = self.find_element(locator)
        self.driver.switch_to_active_element()
        self.driver.execute_script("return arguments[0].scrollIntoView();", element)  

the keyword ‘find_element_focus’ can work

**Comment by aaltat** [comment]
SeleniumLibrary doesn't have keyword `Find Element Focus` keyword, so the above code is from your own library. Also I don't quite understand what is the problem that you are trying to solve, could you explain your problem with more details?

**Comment by lyqingme** [comment]
My problem is that the focus keyword in SeleniumLibrary has no effect in my environment, and Find Element Focus is my custom keyword that works in this way.

**Comment by aaltat** [comment]
Do you get an error, if yes, what error you get(use --loglevel trace option to run the test)? Where do you know that `Set Focus To Element` keyword does not work? Would it be possible to see an example that demonstrates the problem and also we can run?

**Comment by lyqingme** [comment]
error trace：
20180103 11:05:19.912 : TRACE : Arguments: [ "Xpath=//div[@class='innebox']//div[1]//div[2]//div//div" ]
20180103 11:05:19.913 :  INFO : Clicking element 'Xpath=//div[@class='innebox']//div[1]//div[2]//div//div'.
20180103 11:05:19.913 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/elements {"using": "xpath", "sessionId": "9ed01561704eae9690d724b97eebb499", "value": "//div[@class='innebox']//div[1]//div[2]//div//div"}
20180103 11:05:19.931 : DEBUG : Finished Request
20180103 11:05:19.931 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/element/0.6506079561739881-28/click {"sessionId": "9ed01561704eae9690d724b97eebb499", "id": "0.6506079561739881-28"}
20180103 11:05:20.116 : DEBUG : Finished Request
20180103 11:05:20.118 : TRACE : Return: None
20180103 11:05:20.123 : TRACE : Arguments: [ '2s' ]
20180103 11:05:22.123 :  INFO : Slept 2 seconds
20180103 11:05:22.123 : TRACE : Return: None
20180103 11:05:22.125 : TRACE : Arguments: [ "Xpath=//div[@class='innebox']//div[1]//div[3]//div//div" ]
20180103 11:05:22.125 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/elements {"using": "xpath", "sessionId": "9ed01561704eae9690d724b97eebb499", "value": "//div[@class='innebox']//div[1]//div[3]//div//div"}
20180103 11:05:22.147 : DEBUG : Finished Request
20180103 11:05:22.148 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/execute {"sessionId": "9ed01561704eae9690d724b97eebb499", "args": [{"element-6066-11e4-a52e-4f735466cecf": "0.6506079561739881-30", "ELEMENT": "0.6506079561739881-30"}], "script": "arguments[0].focus();"}
20180103 11:05:22.164 : DEBUG : Finished Request
20180103 11:05:22.164 : TRACE : Return: None
20180103 11:05:22.165 : TRACE : Arguments: [ "Xpath=//div[@class='innebox']//div[1]//div[3]//div//div" ]
20180103 11:05:22.165 :  INFO : Clicking element 'Xpath=//div[@class='innebox']//div[1]//div[3]//div//div'.
20180103 11:05:22.166 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/elements {"using": "xpath", "sessionId": "9ed01561704eae9690d724b97eebb499", "value": "//div[@class='innebox']//div[1]//div[3]//div//div"}
20180103 11:05:22.181 : DEBUG : Finished Request
20180103 11:05:22.182 : DEBUG : POST http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/element/0.6506079561739881-30/click {"sessionId": "9ed01561704eae9690d724b97eebb499", "id": "0.6506079561739881-30"}
20180103 11:05:22.250 : DEBUG : Finished Request
20180103 11:05:22.251 : TRACE : Arguments: [  ]
20180103 11:05:22.252 : DEBUG : GET http://127.0.0.1:49182/session/9ed01561704eae9690d724b97eebb499/screenshot {"sessionId": "9ed01561704eae9690d724b97eebb499"}
20180103 11:05:22.616 : DEBUG : Finished Request
20180103 11:05:22.617 :  INFO : </td></tr><tr><td colspan="3"><a href="selenium-screenshot-12.png"><img src="selenium-screenshot-12.png" width="800px"></a>
20180103 11:05:22.618 : TRACE : Return: 'C:\\project\\smartclass-web-autotest\\TestResult\\selenium-screenshot-12.png'
20180103 11:05:22.687 :  FAIL : 
WebDriverException: Message: unknown error: Element <div data-v-044bdd4a="" class="select">...</div> is not clickable at point (421, 692). Other element would receive the click: <div data-v-044bdd4a="" class="bottom_bar">...</div>
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86)

20180103 11:05:22.687 : DEBUG : 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\SeleniumLibrary\__init__.py", line 360, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\keywords\element.py", line 410, in click_element
    self.find_element(locator).click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by lyqingme** [comment]
A list of operations I want. The current situation is that the first two elements are clicked, the third element is not in the current page display area, the third element clicks wrong. I did Focus before clicking the element, but it does not work for now.

**Comment by aaltat** [comment]
But your problem is not with the focus keyword. It's with the Click Element keyword and the exception gives you clear reason why the click fails:
```
WebDriverException: Message: unknown error: Element

...
is not clickable at point (421, 692). Other element would receive the click:
...

(Session info: chrome=63.0.3239.84)
(Driver info: chromedriver=2.33.506120 (
```
There are many reasons why the test might have stopped working for you, but based on the error message it doesn't have anything with the Focus keyword or the SeleniumLibrary. The Focus keyword does not ensure that element is visible and can be clicked, the keyword only moves the cursor to the element. Most likely you have to poll that page is fully loaded, before you try to click on the element. But because this is not a problem with the SeleniumLibrary, I am closing the issue.
