### ISSUE TITLE
getting error as firefox not installed in selenium

### ISSUE THREAD

**Issue by priya391** [robotframework/SeleniumLibrary#1030]
#_firefox_ version 57
installed geckoriver of version 19
OS appears to be: WIN10
Build info: version: '3.8.1', 
os.name: 'Windows 10', java.version: '9.0.1'

getting below error:
Exception in thread "main" org.openqa.selenium.WebDriverException: Cannot find firefox binary in PATH. Make sure firefox is installed. 
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.FirefoxBinary.<init>
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at org.openqa.selenium.firefox.FirefoxOptions.getBinary
	at org.openqa.selenium.firefox.FirefoxDriver.toExecutor
	at org.openqa.selenium.firefox.FirefoxDriver.<init>
	at org.openqa.selenium.firefox.FirefoxDriver.<init>

**Comment by aaltat** [comment]
Selenium is really picky on the supported installation location. In practice browsers must be installed in the default location and if it's not installed in the default location, then the location must be provided. Based on the error it looks like Selenium does not find the Firefox installation. One should be able to fix this by installing the Firefox in the default location in your OS.

By the way, are you using the Java version of the Selenium2Library? If you are, then the Java version is hosted here: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java

**Comment by aaltat** [comment]
Is this still a problem or can the issue be closed?

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by priya391** [comment]
No ...The issue has been closed...

On Jan 25, 2018 2:29 AM, "Tatu Aalto" <notifications@github.com> wrote:

Is this still a problem or can the issue be closed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/robotframework/SeleniumLibrary/issues/1030#issuecomment-360271384>,
or mute the thread
