### ISSUE TITLE
Remove deprecated browser attribute from the library public API. 

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1036]
When doing SeleniumLibrary 3.0 we did change the `self.browser` to `self.driver` in the library public API in one of the beta or alpha releases. But for early adopters we wanted to support backwards comparability for some time. Now the `self.browser` attribute is removed from the public API.

**Comment by pekkaklarck** [comment]
`self.browser` was only added during SL 3.0 development and then later renamed to `self.driver`, right? In that case removing it is absolutely fine. With old attributes from S2L 1.8 and older we probably should wait a bit more unless they start to cause too much trouble.

**Comment by aaltat** [comment]
@pekkaklarck your memory server well and you are correct. I should have removed the `self.browser` already in 3.0 final release but I did forget. I also agree that we should wait little bit longer on 1.8 attribute removals.
