### ISSUE TITLE
Fix SeleniumLibrary demo project to use SeleniumLibrary instead of the Selenium2Library

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1041]
Demo project is here: https://bitbucket.org/robotframework/webdemo

Fix the imports and recreate the report and logs.

**Comment by pekkaklarck** [comment]
Yeah, I started moving the demo to use SL instead of S2L earlier but SL3 wasn't yet released so didn't change the test data. Should definitely do that now.

**Comment by aaltat** [comment]
Do you know that is there something else that should be fixed also?

**Comment by pekkaklarck** [comment]
Don't remember. Luckily there's not that much content.

**Comment by aaltat** [comment]
Discussed with Pekka and decided to move the project from Bitbucket to GitHub. Will enable the GitHub pages and put report and log in there.
