### ISSUE TITLE
Add Message attribute to the Page Title Should Be function

### ISSUE THREAD

**Issue by rubygeek** [robotframework/SeleniumLibrary#1042]
Many tests allow you to pass a message on failure, this function is lacking that. Though you can do something similar in other ways, it should be part of the function

One solution might be:
```
${title}=     Get Title
Should Be Equal   My Homepage    ${title}     Page didn't go to the right location
```

But better if we could do 

```
Page Title Should Be  My Homepage  message=Page didn't go to the right location
```

**Comment by aaltat** [comment]
Having a new argument sounds good idea.

**Comment by aaltat** [comment]
Done is #1044
