### ISSUE TITLE
Test fails with "ValueError: need more than 1 value to unpack" on "Open Browser" when comma in test name

### ISSUE THREAD

**Issue by djay** [robotframework/SeleniumLibrary#1049]
Not really sure how this happens yet but most likely something is using TEST_NAME env variable and this isn't made safe?

**Comment by aaltat** [comment]
Could you show an example that demonstrates the problem. Also could you run your test `--loglevel trace` and send the full stack trace?

Please remember that this is a public website, so remember to hide sensitive information.

**Comment by djay** [comment]
Looks like its not a bug SeleniumLibrary. Sorry for the noise

```
*** Settings ***
Documentation     Simple example using SeleniumLibrary.
Library           SeleniumLibrary

***Test Cases***
Test a comma, in a test
     open browser    http://www.google.com   chrome
```

Seems to work fine. Will try to work out where the error is being introduced.

**Comment by aaltat** [comment]
Thanks for the information, I hope that you are able to solve the problem.
