### ISSUE TITLE
MAC - WebDriverException: Message: 'chromedriver' executable needs to be in PATH

### ISSUE THREAD

**Issue by robotTester** [robotframework/SeleniumLibrary#1051]
WebDriverException: Message: 'chromedriver' executable needs to be in PATH

Working fine on safari

**Comment by aaltat** [comment]
Please do as the error message says, put the ChromeDriver to the PATH. More details in here: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#browser-drivers

**Comment by robotTester** [comment]
I have put it in path but still it shows

Here is my echo $PATH result:
/usr/local/bin/chromedriver:/Library/Frameworks/Python.framework/Versions/2.7/bin/chromedriver

**Comment by aaltat** [comment]
The error comes from the Selenium side, which in practice tries to start the `chromedriver` executable by using the Python subprocess module. And now it throws an error, because the `chromedriver` executable can not be found by operating system. Please consult your operating system manual pages how the set PATH for the user that is running the test.

**Comment by robotTester** [comment]
I have consulted many pages about how to set PATH but its confusing foe MAC as you can set path using .bash_profile and /etc/paths .
But I have tried putting chromedriver paths in both ways.
Also we should give the path till the .exe file or the folder where it resides .
Thanks

**Comment by aaltat** [comment]
I don't have a Mac so I don't know how to help you more than provide random links to similar problems: https://stackoverflow.com/questions/43528944/python-browser-with-mac-error-chromedriver-executable-needs-to-be-in-path

That brew install did look really neat thing.

But this is not a problem in the SeleniumLibrary, but an support issue and therefore I am closing the issue. You will get better support by asking from the slack or from the user group mailing list. Most likely there is a person, who have had a same problem with a Mac and is able to help you better.

Official support channels are listed here: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
