### ISSUE TITLE
Create new keyword "Element Text Should Not Be"

### ISSUE THREAD

**Issue by mariosimao** [robotframework/SeleniumLibrary#1065]
I need to check if some part of the page has a text or is empty. For me there should be 2 logical ways to do that:

| Element Text Should Not Be | ${EMPTY} |
|---------------------------:|----------|

| Element Text Should Not Be Empty |
|---------------------------------:|

I think both keywords should exist in this Library

**Comment by aaltat** [comment]
The `Element Text Should Not Be Empty` is not general enough to qualify as a keyword. But having a counterpart, but a negative one for `Element Text Should Be` might be possible. But have you considered that there are possibility to check the element text in other ways too. Example:
```
| ${text] = | Get Text | xpath://path/to/element | 
| Should Not Contain | ${text} | None |
```
Please remember that Selenium will return [Python None](https://docs.python.org/2/library/constants.html#None) when element does not have text and also when element is not visible (even the element has text).  Therefore the number of false positive may be quite high. And in all UI tests, proving that something is not there, is actually quite complicated problem.  

But I am not against writing a new keyword `Element Text Should Not Be`, would you be willing to provide PR for such keyword?

**Comment by mariosimao** [comment]
What do you mean with PR?

**Comment by aaltat** [comment]
PR stands for Pull Request: https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst#pull-requests

**Comment by rubygeek** [comment]
I will take this and create a PR if @mariosimao  does not want to.

**Comment by mariosimao** [comment]
@rubygeek could you? I'm a little busy in the past weeks plus zero experience with this situations. Maybe I could learn with your PR... :)

**Comment by rubygeek** [comment]
@mariosimao  of course

**Comment by aaltat** [comment]
This was done in #1074
