### ISSUE TITLE
Click does nothing for a dynamic element within a frame

### ISSUE THREAD

**Issue by srigney** [robotframework/SeleniumLibrary#1071]
## Meta -
OS:  
Windows 10
Selenium Version:  
3.0.1, RobotFramework 3.0, Python 2.7
Browser:  
Internet Explorer
Browser Version:  
11.248.16299.0

## Expected Behavior -
Should be able to click on a dynamically enabled element within a frame.
## Actual Behavior -
The click action shows as successful in the logs, but nothing actually happens. 
## Steps to reproduce -
Below are screen shots 
App/Frame undr test
![2018-03-01_0837](https://user-images.githubusercontent.com/20686626/36869380-788ed2f6-1d50-11e8-854d-57d203499ba2.png)

DOM
![2018-03-01_0832](https://user-images.githubusercontent.com/20686626/36869406-8eaf89ea-1d50-11e8-9ace-1cb18e4a31b2.png)

RobotFramework Log
![2018-03-01_1212](https://user-images.githubusercontent.com/20686626/36869424-9dcf3ede-1d50-11e8-8948-d8d02b6c69a6.png)

Code snippet
![2018-03-01_1236](https://user-images.githubusercontent.com/20686626/36869440-a9ebfbb2-1d50-11e8-8938-6c2aef45cbc2.png)

**Comment by drobota** [comment]
I would rather say that link does not have any event handler. Try to click a button or parent element instead. Also please check it in pure python or in  javascript console.

**Comment by aaltat** [comment]
Your problem is quite typical one. With modern interactive web applications, it is not enough to wait that element is visible or enabled. I example wait that JQuery does not anymore run. By the DOM snippet, it looks like you are using Angular as a base for your web application. There is separate libraries, which is based on the SeleniumLibrary, that helps to deal with Angular web applications. Example this one has a support for SeleniumLibrary 3.X in the repository: https://github.com/Selenium2Library/robotframework-angularjs I think the SeleniumLibrary 3.X compatible code is in this branch: https://github.com/Selenium2Library/robotframework-angularjs/tree/seleniumlibrary-v3.x but if that does not work, please ask the @emanlove where that code might be.

**Comment by srigney** [comment]
You are correct that we are using Angular. I will take a look at the RF-Angular library you mentioned and update with my results.

**Comment by srigney** [comment]
I tried using both  https://github.com/Selenium2Library/robotframework-angularjs/tree/seleniumlibrary-v3.x  and https://github.com/rickypc/robotframework-extendedselenium2library but both result in import errors that seem to be related to the new version of Selenium(3.0). I don't want to downgrade the version of Selenium in order to use these packages since I'm not convinced either of these will resolve my issue.

I even added in explicit waits for up to a minute in order to disprove the notion that it is an issue with JQuery still running. The element is found, I wait a full minute and am still unable to click on the element.

**Comment by aaltat** [comment]
Then I would try what you @drobota did suggest. Some web applications are really picky where the click happens. Also it might be that event which Selenium triggers is not listened by your web application. This is an issue that you have to discuss with your development.

Please note that SeleniumLibrary and Selenium are quite independent and one can update and downgrade quite freely one without affecting the other. But I understand your reluctance to downgrade the SeleniumLibrary.

One other notable thing to remind is that if your xpath points in to multiple elements, SeleniumLibrary will silently select the first element and perform the action with the first element. So please check that the xpath points only to one and correct element.

**Comment by srigney** [comment]
Thanks for the feedback. I can assure you that I verified that this is the only element with the identifier I have given. I even tried a 'get element count' and got a count of one. I have tried setting focus to the element and sending the enter key, 

I will try clicking a parent element, but there isn't much in the modal.

**Comment by aaltat** [comment]
Then it strongly looks that event which Selenium triggers is not listened by your web application. This is an issue that you have to discuss with your development.

**Comment by aaltat** [comment]
Did you get the problem sorted out with your development?

**Comment by srigney** [comment]
I am should be meeting with the developer in the next day or two. I will post an update after that.

**Comment by aaltat** [comment]
Sure, no problems.

**Comment by aaltat** [comment]
Did you get the problem sorted out with your development?

**Comment by aaltat** [comment]
Closing due inactivity. 

If you still think that this is a problem with the SeleniumLibrary, please explain why you think so and we can reconsider reopening the issue.

**Comment by srigney** [comment]
I worked with the developer and we couldn't get it working as is so the modul was removed from the iFrame and put in an IonicModal and this resolved the issue.
