### ISSUE TITLE
Opera webdriver missing binary

### ISSUE THREAD

**Issue by buscseik** [robotframework/SeleniumLibrary#1072]
Hi All,

I have tried to execute the following simple robot test:

    *** Settings ***
    Library				SeleniumLibrary
    
    *** Test Cases ***
    Verify Opera
    	Open Browser	https://google.com	opera

And I receive the following error:

    WebDriverException: Message: unknown error: cannot find Opera binary
      (Driver info: OperaDriver=2.33 (3c26e9df3b0e313077a02a7d6ecab2264700bf10),platform=Windows NT 10.0.16299 x86_64)

I have seen few topic around this problem, but all suggested fix is: to define the binary location at opera_option.binary_location. That was a proposed solution if I use Python to interact with selenium. (see details on link below.)
Is there a way to define this option on RobotFramework level, or is there any workaround for this?

See more info: [Opera driver issue](https://github.com/operasoftware/operachromiumdriver/issues/31)

Opera version: 51.0.2830.40 
Opera driver version: 2.33

**Comment by aaltat** [comment]
The best option is to create your own keyword to open Opera browser. Extending the library is explained in here: https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/EXTENDING_SELENIUMLIBRARY.rst

**Comment by aaltat** [comment]
Is this still a problem?

**Comment by buscseik** [comment]
Yes, I still have this problem. This should work out of the box as selenium library accept opera as option.
So this is a bug.

**Comment by pekkaklarck** [comment]
Does this work if Opera is in PATH?

**Comment by buscseik** [comment]
No, PATH does not help.
I found some info, and seems the bug is: the selenium wrapper library does handle "\\" in path as escape character.

**Comment by aaltat** [comment]
I do not understand what you mean by that? Could you show an example?

**Comment by pekkaklarck** [comment]
So the underlying bug is in OperaDriver? In that case I don't think it makes sense to add a special argument to Open Browser, but in general being able to configure opened browser better would be handy. At the moment this ought to be doable with Create Webdriver keyword.

**Comment by buscseik** [comment]
I tried to load from python and following error pop up.
It seems the path being handled incorrectly. The "\51" in the path being replaced by ")"
"\51." is in line 5
")" is in line 23

    Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from selenium import webdriver
    >>> options = webdriver.ChromeOptions()
    >>> options.binary_location = "c:\Program Files\Opera\51.0.2830.40\opera.exe"
    >>> driver = webdriver.Opera(options=options)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python36\lib\site-packages\selenium\webdriver\opera\webdriver.py", line 78, in __init__
        service_log_path=service_log_path)
      File "C:\Python36\lib\site-packages\selenium\webdriver\opera\webdriver.py", line 57, in __init__
        service_log_path=service_log_path)
      File "C:\Python36\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
        desired_capabilities=desired_capabilities)
      File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 154, in __init__
        self.start_session(desired_capabilities, browser_profile)
      File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 243, in start_session
        response = self.execute(Command.NEW_SESSION, parameters)
      File "C:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 312, in execute
        self.error_handler.check_response(response)
      File "C:\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
        raise exception_class(message, screen, stacktrace)
    selenium.common.exceptions.WebDriverException: Message: unknown error: no Opera binary at c:\Program Files\Opera).0.2830.40\opera.exe
      (Driver info: OperaDriver=2.32 (cfa164127aab5f93e5e47d9dcf8407380eb42c50),platform=Windows NT 10.0.16299 x86_64)
    As you can see the "\51." in the path has been miss interpreted into ")" in the defined path

**Comment by aaltat** [comment]
The `\` is an escape character in Python and also in RF. If you want write literal `\` you need to do `\\`

**Comment by buscseik** [comment]
You have right, above example is not relevant on the this bug.

Anyhow I tried a workaround:

    *** Settings ***
    Library									Selenium2Library
    
    *** Test Cases ***
    Verify Opera
            ${options}=						Evaluate			sys.modules['selenium.webdriver'].ChromeOptions()		sys
            ${options.binary_location} =	Set Variable		C:/Program Files/Opera/51.0.2830.40/opera.exe
            Create Webdriver				Opera				options=${options}


This was working, and also this confirm the issue is related to opera binary location.

**Comment by aaltat** [comment]
Good that you got the problem sorted out.

Currently the `Open Browser` keyword is not designed for this type of usage. And for more complex usage, there is the `Create WebDriver` keyword. I agree that enhancing the `Open Browser` keyword is good idea, but for that we have a separate issue #701. I am closing this as a duplicate.
