### ISSUE TITLE
Create `Element Attribute Should Be   locator   attribute   value`

### ISSUE THREAD

**Issue by rubygeek** [robotframework/SeleniumLibrary#1073]
I and my team often test element attributes to see if they are a certain values (ie to make sure the homepage link is href "/"). It would be handy to have this in one function so we don't have to use two lines to verify (Get Element Attribute and  Should Be Equal As Strings).

I would be happy to write a PR if it seems good to others.

**Comment by aaltat** [comment]
As a workaround one can always use xpath: `//*[@attribute="value"]`, but I guess, this could be good addition. Are you wanting something like this: 
```
| Element Attribute Should Be | locator | attribute | value |
```

**Comment by rubygeek** [comment]
Yes exactly

**Comment by brian-mathews** [comment]
I will do this ticket, my co-worker @rubygeek will help me as this will be my first contribution

**Comment by aaltat** [comment]
Great to hear.

**Comment by aaltat** [comment]
There is a #1087 to address this issue.

**Comment by aaltat** [comment]
The #1087 is merged to master and therefore closing the issue.
