### ISSUE TITLE
IE operate fail when IE window is not active window

### ISSUE THREAD

**Issue by wingking** [robotframework/SeleniumLibrary#108]
selenium2library 1.0.1 
1  open a notebook.exe when running scripts,the operation to ie will fail .
if add autoitlibrary keyword :win activate ,it pass.
2  The script opens two IE browser, and need to switch between them, it fails even using "switch browser".

win xp ,IE8
the FF10 work fine.

**Comment by emanlove** [comment]
> selenium2library 1.0.1
> 1 open a notebook.exe when running scripts,the operation to ie will fail .
> if add autoitlibrary keyword :win activate ,it pass.
> 2 The script opens two IE browser, and need to switch between them, it 
> fails even using "switch browser".
> 
> win xp ,IE8
> the FF10 work fine.

I'm not sure I fully understand you problem but there is a known issue 
with the 'Select Window' keyword within the Selenium2Library where IE 
fails switching between two windows. See

   https://github.com/rtomac/robotframework-selenium2library/issues/10

There is a fix within the repository

https://github.com/rtomac/robotframework-selenium2library/commit/4b36772fcc546dadb3a6c82f8f2f014240588576

that will appear in the next release.  If you need this fix sooner you 
could implement the change in your local code.

Ed

**Comment by ombre42** [comment]
You are reporting on an issue that appears to be with Selenium not Selenium2Library. Check [this page](http://code.google.com/p/selenium/wiki/InternetExplorerDriver) out for some info on the challenges with the IE driver, including foreground issues. Remember Selenium2Library is a thin wrapper around Selenium.

**Comment by emanlove** [comment]
@wingking Version 1.1 (released 6 Nov. 2012) Selenium2Library has a change which might fix the issue you are seeing. As @ombre42 noted this might be an upstream issue within Selenium and not Selenium2Library.  The latest [Selenium2Library Developer's Documentation has a tutorial section](https://github.com/rtomac/robotframework-selenium2library/blob/master/BUILD.rst#testing-third-party-packages) on how to discern selenium issues from Selenium2Library issues as well as documentation on how to easily test for bugs within selenium only. You might also try upgrading to a newer version of selenium. If you are still experiencing this issue please reopen this ticket.
