### ISSUE TITLE
How scroll element into view

### ISSUE THREAD

**Issue by antho03** [robotframework/SeleniumLibrary#1082]
Hi guys, 

I regularly have the following error " couldn't scroll into view"
I know KW in ExtendedSelenium2libray but it's it is not compatible with the latest version of selenium2library

Other solution is to use Execute javascript | document.getElementById('myId')[0].scrollIntoView()
But how use that for HTML <select>< option > value or index ? 

Maybe there is a solution with a keyword?

Thx a lot guys

**Comment by aaltat** [comment]
Unfortunately no-one has seen implement enough to implement this as a keyword in SeleniumLibrary. There is actually already an existing issue #763 and therefore I am closing this one.
