### ISSUE TITLE
close all browsers doesn't work

### ISSUE THREAD

**Issue by wingking** [robotframework/SeleniumLibrary#109]
```
Open Browser    http://10.10.0.18    ie
Open Browser    http://10.10.0.16    ie
Close All Browsers
```

only close the first ie.
and raise : WindowsError: [Error 5]

xp sp3, ie8, se2 v1.0.1
the FF is fine.

the below code also fail:
    Open Browser    http://10.10.0.18    ie  a
    Open Browser    http://10.10.0.16    ie  b
    Switch Browser a
    Close Browser
    Switch Browser b
    Close Browser

**Comment by j1z0** [comment]
I don't believe webdriver for IE even supports multiple browsers.  You might want to verify with the selenium team if multiple browser in IE is even supported. 

Cheers,
Jeremy

**Comment by elizaleong** [comment]
I do not know about multiple browser support for IE, but please see Issue #111 about catching WindowsError with selenium itself.

**Comment by adwu73** [comment]
this is a selenium bug, http://code.google.com/p/selenium/issues/detail?id=4310

**Comment by rtomac** [comment]
Agreed, this is a Selenium bug (that has been fixed in source but not yet made part of a release). Hopefully we'll see a point release from Selenium team soon.
