### ISSUE TITLE
Add message to Location Should Be keyword

### ISSUE THREAD

**Issue by rubygeek** [robotframework/SeleniumLibrary#1090]
The keyword `Location Should Be` and `Location Should Contain` would be more useful to show a custom error message like many of the other keywords that take a `message` attribute.

http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Location%20Should%20Be
http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Location%20Should%20Contain
I would be happy to work on this or assist one of my teammates on this task.

**Comment by aaltat** [comment]
This is a good enhancement. Are you able to provide a pull request?

**Comment by rubygeek** [comment]
Yes we will, thanks!

**Comment by aaltat** [comment]
This is done #1091 Closing the issue.
