### ISSUE TITLE
Future Improvement: Deprecate error param and use message 

### ISSUE THREAD

**Issue by rubygeek** [robotframework/SeleniumLibrary#1095]
10 of the functions in Selenium Library use the keyword name `error` while the majority use `message` to set a custom error message.

The following functions use `error`:

* Wait For Condition
* Wait Until Element Contains
* Wait Until Element Does Not Contain
* Wait Until Element Is Enabled
* Wait Until Element Is Not Visible
* Wait Until Element Is Visible
* Wait Until Page Contains
* Wait Until Page Contains Element
* Wait Until Page Does Not Contain
* Wait Until Page Does Not Contain Element

Not high priority, but something to just keep in mind. I will update the contributing document to say to use the `message` attribute for future work on the library. Some of these keywords are probably fairly popular so care must be taken to not break backwards capability.

**Comment by aaltat** [comment]
Although this could be fixed, it will cause big backwards incompatibly and I don't think it's worth of the effort. Therefore closing this issue.
