### ISSUE TITLE
Headless Firefox and Chrome not working over selenium grid

### ISSUE THREAD

**Issue by amalsgit** [robotframework/SeleniumLibrary#1098]
I was trying to run headless firefox with custom firefox profile over a selenium grid, But the browser does not open is headless mode.  It opens in the GUI mode

Launch Firefox Grid
    Set Download Directory
    ${profile path}=  set_firefox_profile  ${DOWNLOAD_DIR}
    log  ${profile path}
    ${dict}    Create Dictionary    seleniumProtocol=WebDriver  maxInstances=5  environment=firefox
    Open Browser  about:blank  headlessfirefox  None  http://192.168.99.100:4444/wd/hub    desired_capabilities=${dict}  ff_profile_dir=${profile path}
    Maximize Browser Window

The firefox profile was created like this:
`def set_firefox_profile(download_dir):
    fp = FirefoxProfile()
    fp.set_preference("browser.download.folderList", 2)
    fp.set_preference("browser.download.manager.showWhenStarting", False)
    fp.set_preference("browser.download.dir", download_dir)
    fp.set_preference("browser.manager.closeWhenDone", True)
    fp.set_preference("browser.download.manager.showAlertOnComplete", False)
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "text/plan")
    fp.update_preferences()
    return fp.path`

I have 3.11.0 version of selenium and 3.1.1 version of SeleniumLibrary in my environment

**Comment by aaltat** [comment]
By looking the code, this is a valid problem and also affects Chrome. Should not be difficult to fix.

**Comment by aaltat** [comment]
@amalsgit this should be now fixed in the master. Would it be possible you to give it a try?
