### ISSUE TITLE
Capture Page Screenshot doesn't work with PageObjectPattern

### ISSUE THREAD

**Issue by yurii-levchenko-chegg** [robotframework/SeleniumLibrary#1099]
I have python page file SignInPage.py:
|||||||||
class SignInPage(Page):
    def login(self):
       self.s2l.go_to('....')
       self.s2l.element_should_be_visible('css=body.qwerty')
|||||||||

.robot file:
|||||||||
Library  SignInPage

* Test cases *
Name
    Login
|||||||||

actually css=body.qwerty is not visible and doesn't exist at all.

Test fails, but "Capture Page Screenshot" keyword never executing.

Bug?

**Comment by yurii-levchenko-chegg** [comment]
Works fine when I'm trying to call "element_should_be_visible  css=body.qwerty" in .robot file directly. Test fails and Capture Page Screenshot works as expected.

**Comment by aaltat** [comment]
When method raises an exception, the `run on failure` is only applied when method is executed as keyword. This is by design and in my opinion should not be changed. Why you want to be changed?

**Comment by yurii-levchenko-chegg** [comment]
I'm using Page Object Pattern (or something similar to that), all common functionality (bundle of keywords) I keep in my custom keywords (example, keywords "Sign up", "Sign in" etc), each of them contains some basic keywords, like "Open Browser", "Go To", "Element Should Be Visible" etc.
I don't want copy all keywords from "Sign up", "Sign in" in each test case. But at the same time I want see screenshot in my CI if test fails in "Sign up", "Sign in" place.

P.S I don't want define keywords in .robot files, in Python only, because I have additional logic here, like Python decorators, classes extending etc.

**Comment by yurii-levchenko-chegg** [comment]
> This is by design and in my opinion should not be changed

Worked fine in 1.8.0 version

**Comment by aaltat** [comment]
I fully agree that building keywords in Python is the best and the only way to go. What I don't understand and would like to understand: when you call a method from SeleniumLibrary in your library and it raises an exception, why you would like to `run on failure` to be applied automatically?

This indeed has changed between 1.8.0 and 3.0.0 release. But in the 1.8.0, if the method was a public, it was also a keyword and therefore it also used to `run on failure`. Starting from 3.0.0 onwards, we have methods which are public, but are not keywords: https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/EXTENDING_SELENIUMLIBRARY.rst#methods-or-attributes-which-are-not-keywords-but-are-available-in-the-public-api Therefore it would be hard to remember which public methods have and which doesn't have the ` run on failure` applied. But the biggest reason is that when I did build logic in my own libraries, using Selenium2Library method, it did have to suppress `run on failure` and I did have to remember to restore it when keyword execution was done. In my opinion, current implementation eases the usage of the SeleniumLibrary from a API point of view, but it looks like you have a different opinion. Could you explain why you think differently?

**Comment by yurii-levchenko-chegg** [comment]
In my case, there are no difference if that is public or private keywords, because I use Page Object. RF also in my case just tool for running tests: simple to write tests (.robot files) and they look nice, simple to run tests, rich functionality (one of them was screenshots).
RF on 95% is framework for FE tests. I don't write tests for checking some math operations e.g (without browser windows). So, 99% keywords potentially related to browser window.
If I will have keyword like "Generate random int and compare it with 72" then better to give user possibility to add tag @non_browser_keyword to avoid auto triggering "run on failure", this in more rare keyword than other possible.

**Comment by pekkaklarck** [comment]
FWIW, I don't think it's a good idea that running a SeleniumLibrary method in Python automatically would trigger the run-on-failure functionality. Especially if SL is not used in combination with Robot, it could have really strange side-effects. In other words, I think the current behavior is better than the old one. 

This kind of backwards-incompatible change should have obviously been mentioned in SL 3.0 release notes, but I guess nobody, including users testing the preview releases, noticed it. If there would have been complaints then, we could have considered this, but now I'd say that ship has sailed.

Those who want the old behavior have at least these possibilities:

1. Instead of using SeleniumLibrary methods directly, use them via the `run_keyword` method that Robot nowadays uses when it's calling SL keywords. For example, instead of using `sl.title_should_be('Expected')`, you can use `sl.run_keyword('title_should_be', ['Expected'])`. For more details about the `run_keyword` method study Robot's [dynamic library API](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dynamic-library-api).

2. Implement the functionality yourself. You can decorate your own keywords or SeleniumLibrary methods with a decorator that does it automatically like in Selenium2Library 1.8.

3. Construct your library using the dynamic API and implement the run-on-failure functionality in `run_keyword` similarly as SL 3 and newer.

**Comment by aaltat** [comment]
My question is not bout how you use your library keywords or where you call them. The question is about when you build the library keywords, on top of the SeleniumLibrary, why you want the `run on failure` be applied automatically? When I did build my library keyword, I did have other methods than just SeleniumLibrary methods and I did have some custom logic in those libraries which where not based on SeleniumLibrary. Example when I have a login, it is not just about entering the user name/password and pressing the login button. Login could involve example changing the user default password and/or creating a secret question(s) for the user. In pseudo code it could look like this: 
```
def login(self, username, passowrd):
    if not self.browser:
        self.sl.open_browser(self.url, "chrome")
    self._login()
    if self._password_change_visible():
        self._change_password()
    if self._secret_question_visible():
        self._set_secret_question()
   self.sl.location_should_hontain("home")
```
In that code, only the parts that are prefixed with `self.sl` are coming directly from SeleniumLibrary. So if those parts fail, the logs will have the  SL `run on failure` run but other parts not. Also SL parts may fail intentionally, so it will be flooding logs with  `run on failure` on those cases is not good idea in my mind. There I did build my own `run on failure` logic to my library keywords and if keyword fails, then keyword will trigger the run on failure and the run on failure is not triggered multiple times by different parts of lithe methods or libraries.

**Comment by yurii-levchenko-chegg** [comment]
> Implement the functionality yourself. You can decorate your own keywords or SeleniumLibrary methods with a decorator that does it automatically like in Selenium2Library 1.8.

Do you mean wrap methods with "from robot.api.deco import keyword"? Did not help for me.

> def __init__(self, timeout=30.0, implicit_wait=30.0, run_on_failure='Capture Page Screenshot',
                 screenshot_root_directory=None):
        SeleniumLibrary.__init__(self, timeout=timeout, implicit_wait=implicit_wait, run_on_failure=run_on_failure, screenshot_root_directory=screenshot_root_directory)

this is what I have currently. 'Capture Page Screenshot' keyword is also in my custom class, here I'm trying to use 'scrot' tool if it is installed (wrapped to try: except:)

**Comment by emanlove** [comment]
@yurii-levchenko-chegg I have a suggestion which may help you but first wanted to share a word of caution. Having done something similar both @pekkaklarck's and @aaltat's suggestions are well worth taking the time to understand. (In particular having written my own Pekka's \#3 solution above is one I, too, should re-examine. Having started on my library about four years ago the code has need to be modified as the, then, Selenium2Library was changed. (I was even the maintainer of S2L at the time [laughing]). As I read you have listened so that being said..

**Comment by emanlove** [comment]
@yurii-levchenko-chegg Take a look at the [robotframework-angularjs library](https://github.com/Selenium2Library/robotframework-angularjs/blob/master/AngularJSLibrary/__init__.py). I am overriding the find functionality so to be able to check the Angular queue. The purpose being to deal with timing errors. Thus it sounds similar to what you are doing. My cautionary note taken there might be something here and if you have questions feel free to ask.  Good luck!

**Comment by yurii-levchenko-chegg** [comment]
Thanks everybody for help, I will try all variants.

**Comment by rotoclabs** [comment]
We recently adopted the newer SeleniumLibrary and ran into this bummer. Capturing screenshots on failure for calls made to SeleniumLibrary keyword methods, within our custom page objects was an extremely used feature, no looks like that's gone ? Troubleshooting test failures involving UI had been real pain, and this feature used to get that job done with least of the efforts. We could even see the transition of a UI in our case like (representational only)

```
Wait Until Keyword Succeeds
...              5 minutes    15 seconds
...              mylib.myapp.pages.TemperatureAlarm.All Are Triggered
```

Internally, it would have been checking multiple elements for an aggregate criteria.

```
def  all_are_triggered:
    self._sl.element_should_be_visible("id:coolant_indicator")
    self._sl.element_should_be_visible("id:oil_indicator")
```

**Comment by aaltat** [comment]
There has been lot of changes between 1.8 and 3.x release. Also this has changed and now the `run on failure` functionality is only applied when SeleniumLibrary method is run as keyword. If SeleniumLibrary method is called from from Python side directly, then `run on failure` is not applied. This has changed between the releases and we are not going to change it back.

This means that if you want your library have `run on failure` functionality, you need to implement it. The good side is that the `run on failure` is simple and it's easy to you to implement, example as a decorator in your library.
