### ISSUE TITLE
Capture Page Screenshot doesn't capture full page with iedriver

### ISSUE THREAD

**Issue by wingking** [robotframework/SeleniumLibrary#110]
my pc is 1440  \* 900,
open browser and Capture Page Screenshot.
it capture full page.
click a button,open a child page, only 760\* 640
Capture Page Screenshot, and the size of caputre pic is 760\* 640
so father page is show to,and the child page only show part(appear scroll,).

xp sp3
se2 v1.0.1

**Comment by j1z0** [comment]
Capture page screen shot is implemented by webdriver itself not s2l.  Thus can you raise this issue on the webdriver list itself?

Cheers,
Jeremy

**Comment by Gurud** [comment]
I am also facing problem of   [warn] Capture Page Screenshot .. while run the test script with Selenium2library with robotframework. so if any one have correct solution on this please post it soon.

As per above comment its the problem with webdriver lib so its open issue ? please clear me , I m stuck here to used of Selenium2Library.

Thanks,
Gaurav

**Comment by emanlove** [comment]
@Gurud If you are still experiencing a problem please open a new ticket and provide more information.
