### ISSUE TITLE
Checkbox Should Not Be Selected keywork can not find element by locator

### ISSUE THREAD

**Issue by arvor87** [robotframework/SeleniumLibrary#1111]
Checkbox Should Not Be Selected keywork can not find element bu locators like id= or name=

Error message: "Checkbox with locator 'id=some_checkbox_id' not found"

Other keywords can interact with thic locator

**Comment by aaltat** [comment]
Could you run the test with `--loglevel trace` set from command line and post the full stack trace? Also would it be possible to see relevant parts of the DOM where your check box is?

**Comment by ombre42** [comment]
That keyword will only work if the element is an _input_ element and the type is _checkbox_.
I suspect you have a div or something else masquerading as a checkbox. Inspecting the DOM in dev tools can confirm if the element has tag input and type checkbox.

**Comment by arvor87** [comment]
You are right! This checkbox is an input element but with type=button. I can not guess why.
So this issue can be closed.
