### ISSUE TITLE
Get Locations will make NoSuchWindowException

### ISSUE THREAD

**Issue by virtualnode** [robotframework/SeleniumLibrary#1113]
After I  clicked a  link which may activate a download window (new window) , NoSuchWindowException was found. 

NoSuchWindowException: Message: no such window

**Comment by HelioGuilherme66** [comment]
That is not a browser window (controlled by webdriver), but an operating system. To control that window you have to use other libraries (usually Image Recognition ones, like SikuliLibrary, ImageHorizon). People often avoid getting that pop-up window, by forcing the downloads to a specific folder.

It does not look like an Issue on our SeleniumLibrary, and is preferable to ask for solutions on our communication channels.

**Comment by ombre42** [comment]
I remember getting this in IE a long long time ago. If I put in a delay after a new tab/window opens, the exception wasn't thrown. So I just worked around the issue.

Can you provide a traceback for when this occured? What version too of SL/selenium/browser?

**Comment by aaltat** [comment]
Is still a problem. If it is, could you describe your problem better and answer to the questions?

**Comment by aaltat** [comment]
Closing due inactivity.
