### ISSUE TITLE
I am running my test(robot framework) on remote server, I am trying to capture the the screenshot where it is failing

### ISSUE THREAD

**Issue by mishraja** [robotframework/SeleniumLibrary#1120]
I am running my test(robot framework) on remote server, I am trying to capture the the screenshot where it is failing.

When check log to verify did it worked fine i seen black screen. attached below. I there any solution to resolve this issue 

![image](https://user-images.githubusercontent.com/39285775/40037615-d62b1b7a-582b-11e8-86b0-cc0a6afd8348.png)

**Comment by aaltat** [comment]
Your `Take Screenshot` keyword comes from the `Screenshot` library and it is not part of the SeleniumLibrary. Therefore I am closing this issue. 

This also feels like a support request more than a bug report or a enhancement request. More details about support, please read: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Comment by emanlove** [comment]
I agree with @aaltat that this is better suited for one of the [Robot Framework support channels](http://robotframework.org/#support). I will note that your problem, I believe, is related to you running the Jenkins Slave on a Windows machine and under a specific user who might not, under the setup, have access or permissions to the screen buffer. Thus getting black screenshots. I suggest you search on running Jenkins slaves under windows and user permissions with the screen buffer. Then I would come back to one of the suggested support channels and we can talk more there.
