### ISSUE TITLE
Got "no browser is open" with chrome.

### ISSUE THREAD

**Issue by lifeislearning** [robotframework/SeleniumLibrary#1121]
Hello, I'm looking a help to solve "no browser is open" issue.

My version is Robot Framework 3.0.4 (Python 3.6.5 on win32).
I had set environment variable in my WIN 10 and downloaded the chromedriver to my google folder, but It's still not work. Please help me to resolve it.

I did another study and found a way, but it confused me if it's my environment setting issue.

I followed someone's suggestion to add an new Library, and it worked to open Chrome.
However,  If I only had Selenium2Library, it will get "no browser is open"

Here is new Library.
```
from selenium import webdriver

drivers = {
    "chrome": webdriver.Chrome,
    "firefox": webdriver.Firefox
}

class SeleniumKeywords:

    ROBOT_LIBRARY_SCOPE = 'GLOBAL'

    def __init__(self):
        self.driver = None

    def open_browser(self, browser="chrome"):
        driver_class = drivers[browser]
        self.driver = driver_class()

    def go_to(self, url):
        self.driver.get(url)

```

**Comment by aaltat** [comment]
Would you be able to run the test cases with `--loglevel trace` set from the command line and post the full stack trace in here. Also could you show an simplified example how you use the `Open Browser` keyword. Also could you tell the Selenium, ChromeDriver and Chrome version you are using?

**Comment by lifeislearning** [comment]
Sorry, I'm quite new, I don't know how to parsing the parameter since I got error for parsing loglevel trace.

Chrome version:  66.0.3359.181 
ChromeDriver:    2.38.552522
Selenium:             3.12.0

`
C:\Users\user\AppData\Local\Programs\Python\Python36>
C:\Users\user\AppData\Local\Programs\Python\Python36>pybot demo.txt --loglevel trace
[ ERROR ] Error in file 'C:\Users\user\AppData\Local\Programs\Python\Python36\demo.txt': Non-existing setting 'Suite'.
[ ERROR ] Parsing '--loglevel' failed: Data source does not exist.

Try --help for usage information.

C:\Users\user\AppData\Local\Programs\Python\Python36>
`
`
C:\Users\user\AppData\Local\Programs\Python\Python36>pybot demo.txt
[ ERROR ] Error in file 'C:\Users\user\AppData\Local\Programs\Python\Python36\demo.txt': Non-existing setting 'Suite'.
[ ERROR ] Error in file 'C:\Users\user\AppData\Local\Programs\Python\Python36\demo.txt': Non-existing setting 'Suite'.
==============================================================================
Demo
==============================================================================
Google devops and find code                                           | FAIL |
No browser is open.
------------------------------------------------------------------------------
Demo                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\user\AppData\Local\Programs\Python\Python36\output.xml
Log:     C:\Users\user\AppData\Local\Programs\Python\Python36\log.html
Report:  C:\Users\user\AppData\Local\Programs\Python\Python36\report.html
`

Here is what I did.

`*** Settings ***

Library    Selenium2Library

Suite  Setup     Go to homepage
Suite  Teardown  Close All Browsers

*** Variables ***
${HOMEPAGE}   http://www.google.com  
${BROWSER}      chrome

*** Test Cases ***	
Google devops and find code
	Google and check results    devops    www.google.com

*** Keywords ***
  
Google and check results
	[Arguments]    ${searchkey}    ${result}
	Input Text     id=lst-ib       ${searchkey}
    Click Button   id=sfdiv
    Wait Until Page Contains       ${result}
	
Go to homepage
   Open  Browser   ${HOMEPAGE}     ${BROWSER}
  `

**Comment by aaltat** [comment]
Robot is picky for the argument order, please run: `pybot --loglevel trace demo.txt`

**Comment by aaltat** [comment]
Also please use three back ticks when you want to post code or something similar. Example \`\`\` text here \`\`\`

**Comment by lifeislearning** [comment]
Thanks, 
It looks no further debug message dump, any other way change debug level?

```
C:\Users\user\AppData\Local\Programs\Python\Python36>pybot --loglevel trace demo.txt
[ ERROR ] Error in file 'C:\Users\user\AppData\Local\Programs\Python\Python36\demo.txt': Non-existing setting 'Suite'.
[ ERROR ] Error in file 'C:\Users\user\AppData\Local\Programs\Python\Python36\demo.txt': Non-existing setting 'Suite'.
==============================================================================
Demo
==============================================================================
Google devops and find code                                           | FAIL |
No browser is open.
------------------------------------------------------------------------------
Demo                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\user\AppData\Local\Programs\Python\Python36\output.xml
Log:     C:\Users\user\AppData\Local\Programs\Python\Python36\log.html
Report:  C:\Users\user\AppData\Local\Programs\Python\Python36\report.html

C:\Users\user\AppData\Local\Programs\Python\Python36>
```

**Comment by aaltat** [comment]
And when you open the log.html, could you post the full stack trace too?

**Comment by lifeislearning** [comment]
Here is log message from log.html

```


Documentation:	
Takes screenshot of the current page and embeds it into log file.

Start / End / Elapsed:	20180516 15:59:56.282 / 20180516 15:59:56.282 / 00:00:00.000
15:59:56.282	TRACE	Arguments: [  ]	
15:59:56.282	INFO	Cannot capture screenshot because no browser is open.	
15:59:56.282	TRACE	Return: None	
15:59:56.282	TRACE	Arguments: [ 'id=lst-ib' | 'devops' ]	
15:59:56.282	INFO	Typing text 'devops' into text field 'id=lst-ib'.	
15:59:56.282	FAIL	No browser is open.	
15:59:56.282	DEBUG	Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\__init__.py", line 360, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\base\robotlibcore.py", line 102, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\keywords\formelement.py", line 248, in input_text
    self._input_text_into_text_field(locator, text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\keywords\formelement.py", line 418, in _input_text_into_text_field
    element = self.find_element(locator)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\base\context.py", line 62, in find_element
    return self.element_finder.find(locator, tag, True, required, parent)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\locators\elementfinder.py", line 73, in find
    parent=parent or self.driver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\base\context.py", line 32, in driver
    return self.ctx.driver
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\SeleniumLibrary\__init__.py", line 403, in driver
    raise NoOpenBrowser('No browser is open.')	
15:59:56.282	TRACE	Arguments: [ ${searchkey}='devops' | ${result}='www.google.com' ]
```

**Comment by aaltat** [comment]
There is a problem in your test. You call `Input Text` keyword before call the `Open Browser` keyword.

**Comment by aaltat** [comment]
Because this looks like a problem in the test case and not with the SeleniumLibrary I am closing this issue. If you feel differently, please send an update.

**Comment by lifeislearning** [comment]
Thanks, you are right.
But I think it may not work with  "Suite  Setup      Go to  homepage",  I just modified the keywords to add open browser and make '#' at "Sutie Setup",  it can open Chrome successfully.

Thanks for your helpful hint.

```
*** Settings ***

Library    Selenium2Library
#Library    SeleniumKeywords

#Suite  Setup      Go to  homepage
#Suite  Teardown   Close All Browsers

*** Variables ***
${HOMEPAGE}   http://www.google.com  
${BROWSER}    Chrome


*** Test Cases ***	

OPEN BROWSER
	Example

Google devops and find code
	Google and check results    devops    www.google.com
	
*** Keywords ***
Example
    Open Browser   ${HOMEPAGE}   ${BROWSER}

Google and check results
	[Arguments]    ${searchkey}    ${result}
	Input Text     id=lst-ib       ${searchkey}
    Click Button   id=sfdiv
    Wait Until Page Contains       ${result}
	
	
#Go to homepage
#   Open  Browser   ${HOMEPAGE}     ${BROWSER}

   
```

**Comment by aaltat** [comment]
It will work also in the suite setup, but there is an formatting error in the settings table (which can be seen also in the console output, in the previous post). You have two or more spaces, between Suite and Setup words. If you put only one, then it should be fixed.

**Comment by Bhavik124** [comment]
![image](https://user-images.githubusercontent.com/59410887/83936046-2181ff00-a7dd-11ea-87f5-8c17f1d827c6.png)
See Also I am getting same error

**Comment by aaltat** [comment]
There is a problem in your test. You must call `Open Browser` or `Create WebDriver` keyword before calling other SeleniumLibrary keywords.

**Comment by Pallaviayalureddy** [comment]
Hi sir I m new to Robot framework , getting "cannot capture screenshot because no browser is open.
20200614 18:29:31.336 :  FAIL : No browser is open.". i m working on desktop application after validating some rules getting IE browser report opening directly after that getting above error not able to proceed further please help me out

**Comment by aaltat** [comment]
@Pallaviayalureddy for better help you, please ask in one of the community support channels https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
