### ISSUE TITLE
find_element duplicate definition

### ISSUE THREAD

**Issue by johanno** [robotframework/SeleniumLibrary#1124]
I've got an weird error, that is_text_present in context.ContextAware object
 ```python
def is_text_present(self, text):   
            locator = "xpath://*[contains(., %s)]" % escape_xpath_value(text)
            return self.find_element(locator, required=False) is not None
```

TypeError: find_element() got an unexpected keyword argument 'required'

by debugging i found out, that some how it uses the find_element method in `Selenium/__init__.py`
instead of the method with the same name in the same class.

possible solution could be:
```python
def find_element(self, locator, parent=None, **kwargs):
           return self._element_finder.find(locator, parent=parent, **kwargs)
```

in `SeleniumLibrary/__init__.py`

why is this method restricted anyway?

**Comment by pekkaklarck** [comment]
Could you clarify how did you get this error? Did you use SL normally or do you use it from Python somehow? Also, you could try fixing the formatting in the description. You can edit the comment and then click the `Styling with Markdown is supported` link below the text area for syntax help.

**Comment by johanno** [comment]
for testing purpose i run it in python.
```python
if __name__ == '__main__':
    m = MIB3ExtendedLibrary(2, run_on_failure="Nothing")
    options = webdriver.ChromeOptions()
    debug = {'debuggerAddress' : 'localhost:9222'}
    options._experimental_options = debug
    m.open_browser("http://10.2.36.211:8080", "Chrome")
    m.select_window(m.list_windows()[0])
    m.maximize_browser_window()

    m.wait_until_page_does_not_contain("sdf")

class MIB3ExtendedLibrary(ExtendedSelenium2Library):
     def __init__(self, implicit_wait=15.0, **kwargs):
            ExtendedSelenium2Library.__init__(self, implicit_wait, **kwargs)
...
```

but i get the error also if i run it with robot framework.

**Comment by pekkaklarck** [comment]
I don't think ExtendedSelenium2Library is compatible with latest Selenium(2)Library versions. Can you test with the normal SeleniumLibrary instead?

**Comment by johanno** [comment]
well i'm actually trying to update the extended2Library to python3.
And using the normal seleniumLibrary works, so the bug is somewhere in the extended2library

**Comment by pekkaklarck** [comment]
The problem is most likely caused by big architecture changes Selenium(2)Library v3.0.0. The ways how to nowadays extend the library is documented here:
https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/EXTENDING_SELENIUMLIBRARY.rst

Is there some specific functionality in the ExtendedSeleniumLibrary that you need and the normal SeleniumLibrary isn't adequate? Could that functionality possibly be added to SL itself?

**Comment by aaltat** [comment]
When SL 3.0 was released, it changed quite many things internally. Like now we use dynamic library API, instead of the static one. But as good side, we now actually have an API which is safe to use for extending the library. Also we would like to get feedback what is working and what improvements one might need.

**Comment by aaltat** [comment]
Did forgot to say that we have also documentation: 
https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/EXTENDING_SELENIUMLIBRARY.rst

**Comment by pekkaklarck** [comment]
Yeah, it would be good to make ExtendedSelenium2Library compatible with the latest SeleniumLibrary versions to make sure extending SL works well. It would, however, be even better to move useful functionality from ES2L to SL.

**Comment by johanno** [comment]
> Is there some specific functionality in the ExtendedSeleniumLibrary that you need and the normal 
> SeleniumLibrary isn't adequate? Could that functionality possibly be added to SL itself?

the extended library provides `Wait Until Element Contains (Not) Attribute` , `Is Element Visible`, `Scroll Element Into View`, `Element Attribute Should (Not) Contain` .
Well the last time i compared the Selenium library with the extended i thougth there were much more keywords we use.

**Comment by pekkaklarck** [comment]
These look fine additions to me and some may have already been added. Please submit individual issues about kws you need and they can then be discussed separately.
