### ISSUE TITLE
How i set desired capabilities attribute in Open Browser Keyword 

### ISSUE THREAD

**Issue by wangbixing** [robotframework/SeleniumLibrary#1125]
open browser url chrome ${None} ${False} {'popups':'1'}

**Comment by ombre42** [comment]
I am using Selenium server. This is what I am doing to stop Selenium from disabling the pop-up blocker:

```
    # allow popup-blocking using desiredCapabilities
    ${options}    Evaluate    sys.modules['selenium.webdriver.chrome.options'].Options()    sys, selenium.webdriver.chrome.options
    ${excluded}    Create List    disable-popup-blocking
    Call Method    ${options}    add_experimental_option    excludeSwitches    ${excluded}
    ${caps}    Call Method    ${options}    to_capabilities
    Open Browser    ${starting_url}    browser=chrome    remote_url=http://server:4444/wd/hub
    ...    desired_capabilities=${caps}
```

**Comment by aaltat** [comment]
Ugh

From the Open Browser keyword documentation: Desired capabilities can be
given either as a Python dictionary or as a string in format
key1:value1,key2:value2.

Please note that starting from release 3.1 onwards, desired capabilities is
also accepted for local browser too.

-Tatu
Send from my mobile

**Comment by aaltat** [comment]
Is this still a problem?

**Comment by aaltat** [comment]
Closing due inactivity.
