### ISSUE TITLE
New Keyword 'Is Element Visible'

### ISSUE THREAD

**Issue by johanno** [robotframework/SeleniumLibrary#1127]
Copied from ExtendedSelenium2Library:
```python
@keyword
    def is_element_visible(self, locator):
        """Returns element visibility identified by ``locator``.

        Arguments:
        - ``locator``: The locator to find requested element. Key attributes for
                       arbitrary elements are ``id`` and ``name``. See `introduction` for
                       details about locating elements.

        Examples:
        | Is Element Visible | css=div.class |
        """
        return self.is_visible(locator)
```

**Comment by aaltat** [comment]
There is already this keyword: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Element%20Should%20Be%20Visible are these the same or is there something different?

**Comment by johanno** [comment]
Should, raises an Error.
Is Element Visible returns false instead.

**Comment by pekkaklarck** [comment]
It's easy to add this kind of `Is` keywords, but for consistency reasons they should be added for all/most `Should` keywords and I'm not sure is that worth the effort. You can already now use `Run Keyword And Return Status` to turn any failure into `False`:

    ${is visible} =    Run Keyword And Return Status    Element Should Be Visible    id:example

It might be possible to add some generic way to configure all SL library's `Should` keywords to return status instead of failing by utilizing the dynamic API that SL nowadays uses. I could work something like this:

    ${is visible} =    Element Should Be Visible    id:example    return_status=True

**Comment by joaonc** [comment]
The `return_status` option is awesome.  Would give us the same functionality w/o adding a ton of new keywords (for the `Page Should Contain ...` keywords as well)

**Comment by bartkl** [comment]
But wouldn't pretty much always want to temporarily disable taking screenshots on error in the case of using these keywords with boolean result values? Adding a `return_status` would not take care of that, so I'd say you'd still have to go through a lot of hassle to get what you want.

**Comment by MichielYKamp** [comment]
> Adding a `return_status` would not take care of that

Can it be done that if this parameter 'return_status' is set to true, that internally this keyword calls
 `${kw on fail}=  Register keyword to run on failure  NONE` beforehand  and `Register keyword to run on failure  ${kw on fail}` afterwards

**Comment by sebastianciupinski** [comment]
I think this is more generic problem: https://github.com/robotframework/robotframework/issues/3171

On one hand, adding return_status=True would be simple and would not increase amount of keywords, but on the other hand this causes particular keyword is doing different things in fact, depending on given argument...

Also, choosing such approach does not fit into RF philosophy which from my understanding is that keyword should describe it's exact purpose. I mean user who would like to find out what keyword should be used for checking if two variables are equal will search for `Are Equals As Numbers` not for `Should Be Equal As Numbers`.

One option to handle that problem might be using some decorator for keywords containing **Should** or **Should Not**, but this still requires developer attention to decorate keyword. Another approach might be extending BuiltIn library with dynamic library API to examine all loaded libraries, look for members of library class, filter them by "should" and "should" not and return new keywords like `Is Sometging`, `Are Somethinf`, `Does Something`. I think inspect module may be useful here. This does not looks like so complicated for processing libraries created with Static API, but may not be so easy for libraries using Dynamic API

**Comment by aaltat** [comment]
The Selenium testability plugin provides many solutions to this problem. Therefore closing this issue.
