### ISSUE TITLE
Get Text of selenium2library not working consistently

### ISSUE THREAD

**Issue by sivassrr** [robotframework/SeleniumLibrary#1130]
Get Text some time it works, And some time it doesnt.

Is there any known issue there?

**Comment by HelioGuilherme66** [comment]
@sivassrr Did you search about this? Do you have an example of your problem?
Please see [submitting-issues](https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst#submitting-issues)

**Comment by aaltat** [comment]
With these details it's hard to say anything concrete about your issue. Generally speaking, Selenium will return Python None when the element does not have a text and also then when element is invisible (also in case when element contains text, but when it's invisible). 

To give a better answer, we would need to know your problem more deeply.  Would it possible to you to create an example that demonstrates the problem and we all can run? Also providing used SL, Selenium, browser driver and browser versions are useful.

**Comment by aaltat** [comment]
Is this still a problem and are you waiting us to do something? If yes, then what it might be?

**Comment by aaltat** [comment]
Closing due inactivity.
