### ISSUE TITLE
Close Windows Issue with Firefox

### ISSUE THREAD

**Issue by houesmalek** [robotframework/SeleniumLibrary#1133]
Hello everyone,

I'm using robotframework with RIDE on its version 1.5.2.1. 
I've created a function that closes all open Windows using a **for loop** and the function **Close Window** Inside. It works perfectly, but when everything is closed Firefox  displays a popup saying **_"Firefox has stopped working_**" 
Any idea why is that happening plz?

Thank you in advance

**Comment by aaltat** [comment]
Is there a reason why you don't use this keyword: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Close%20All%20Browsers

**Comment by houesmalek** [comment]
Yes because it's not supported on RIDE, it always fails with this message "WebDriverException: Message: quit" and doesn't close anything

**Comment by HelioGuilherme66** [comment]
Try to update "geckodriver" and "chromedriver". That message is from Selenium (RIDE and SeleniumLibrary have nothing to do with it).

**Comment by aaltat** [comment]
Let's clarify some terms.
RIDE: is an IDE or editor for Robot Framework test data.
Robot Framework: is a generic test automation framework. Robot Framework does not directly interact with application under test.
SeleniumLibrary: is a web testing library for Robot Framework that utilizes the Selenium tool internally. 
Selenium: is an umbrella project encapsulating a variety of tools and libraries enabling web browser automation.
Geckodriver: Proxy for using W3C WebDriver-compatible clients to interact with Gecko-based browsers. Made by Mozilla.

Now the error you are seeing comes from Selenium side, most likely from the geckodriver. After you did upgrade Selenium, geckodriver and Firefox, is this still a problem?

**Comment by aaltat** [comment]
Closing due inactivity.
