### ISSUE TITLE
Question: Testing Web Components (Shadow DOM)

### ISSUE THREAD

**Issue by Georgegriff** [robotframework/SeleniumLibrary#1134]
We are making heavy use of Web Components in our applications now, which make use of Shadow DOM. I've done a bit of reading around but couldn't find any official statements/advice on how to handle the issue of not being able to easily target keywords at elements in the shadow dom. Would be great to get some thoughts

**Comment by aaltat** [comment]
Last time I did check, Selenium doesn't offer support for shadow DOM. Therefore SeleniumLibrary does not have the support either. I don't have experience with shadow DOM, but with Google I did find example this one: https://stackoverflow.com/questions/36139212/shadow-dom-support-for-selenium

**Comment by aaltat** [comment]
Because this is more a support question, I am closing this issue.
