### ISSUE TITLE
Element Should Contain fails with TypeError if the element is not found

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#114]
Execute: Element Should Contain    id=doesNotExist    Expected Text

Expected:  fails with error similar to other keywords such as 
ValueError: Element 'id=doesNotExist' not found.
or
ValueError: Element locator 'id=doesNotExist' did not match any elements.

Actual: fails with TypeError: argument of type 'NoneType' is not iterable

If pull request #53 to add element_should_not_contain keyword were accepted, it would have the same issue at this moment

**Comment by emanlove** [comment]
'Get Text' and 'Element Should Contain' now throws exception if element is not found. See #127.

**Comment by ombre42** [comment]
Now fails with
ValueError: Element locator '<locator>' did not match any elements.
in 1.1
