### ISSUE TITLE
Drop support for Selenium 2 and increase the required Selenium 3.4 version.

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1142]
The Selenium 2.53.6 is two years old. The main reason to support Selenium 2.53.6 is the compatibility with older (I think it was Firefox 42 and older). Although Selenium 3 is a drop in replacement for Selenium 2, the changes (starting from Selenium 3.7.0 onward) in Selenium API are causing the project to create some Selenium specific code, specially in the browser creation. Dropping the older version of Selenium could ease the maintenance of the project and avoid mistakes like: #1098 

Raise the minimum required Selenium 3 version to 3,4.

**Comment by HelioGuilherme66** [comment]
I totally agree.

**Comment by jjwong** [comment]
Drop support. If folks need older browser support, they can stick with the older version of the library using requirements.txt or pipenv.

**Comment by antonpaa** [comment]
I think this makes sense. For the time being, the last version to support Selenium 2.53.6 could be labeled somewhere if that can be done conveniently.

**Comment by Cronax42** [comment]
Fully agree.

**Comment by zilahir** [comment]
agree!

**Comment by aaltat** [comment]
The Selenium 2.53.6 is removed from Travis. Need to think should we test with some other version of Selenium 3 than the latest.

**Comment by aaltat** [comment]
Now and then there are changes in way how Selenium logs stuff. We have test which checks that keywords logs correct information and it would come hard to support many versions of Selenium when Selenium logging changes. Therefore different Selenium version are not tested in Travis.

Consider adding note to release documentation.

**Comment by aaltat** [comment]
The https://github.com/robotframework/SeleniumLibrary/commit/b6c8f3b636855a9f21b64679d4582ca6a04a4fd4 updates the requirement.txt for Selenium to 3.4.0.

**Comment by aaltat** [comment]
Update also https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#versions

**Comment by aaltat** [comment]
Closed via #1203
