### ISSUE TITLE
Speed up and optimize Jython with Travis

### ISSUE THREAD

**Issue by mihaiparvu** [robotframework/SeleniumLibrary#1145]
Check this [commit](https://github.com/mihaiparvu/SSHLibrary/commit/293ad27e2053e1a56a2bf3016cb05659133f91b5) for an improved integration of Jython with Travis-CI. The main change is using the official Jython installer instead of building it from source code each time. Also, the average job duration is about 2-3 minutes lower.

**Comment by aaltat** [comment]
Cool and thanks for the tip. If it works for SSHLibrary it should also work for us too. I will proudly copy your implementation, just like the last time :-)
