### ISSUE TITLE
Get Text succeeds and returns None if the element is not found instead of failing

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#115]
Execute: ${text}    Get Text    id=doesNotExist

Expected: fails with error similar to other keywords such as 
ValueError: Element 'id=doesNotExist' not found.
or
ValueError: Element locator 'id=doesNotExist' did not match any elements.

Actual: keyword succeeds and ${text} is assigned a value of None

This appears to be the same root cause as Issue #114 - _ElementKeywords._get_text() returns None if the element is not found instead of raising an exception

**Comment by emanlove** [comment]
'Get Text' and 'Element Should Contain' now throws exception if element is not found. See #127.

**Comment by ombre42** [comment]
This was fixed in 1.1. The error as implemented looks like this:
ValueError: Element locator 'id=doesNotExist' did not match any elements.
