### ISSUE TITLE
Choose File: file does not exist on the local file system

### ISSUE THREAD

**Issue by houesmalek** [robotframework/SeleniumLibrary#1160]
Hello,

I want to upload a file using `Choose file`. The file is located on my project's repository. 
When I run, I've got this error **file ".."does not exist on the local file system**. However, using `Get File `with the same file in the arguments is able to find the file.

Any idea??

**Comment by aaltat** [comment]
The error comes from the operating system side and it says that operating system can not find the file. That being said, it's possible that you have encountered an bug, would you be able to demonstrate your problem with the example?

**Comment by houesmalek** [comment]
Yes sure, here is my example
```
    ${Windows}=    List Windows
    Select Window    ${Windows[1]}
    Wait Until Page Contains    Sélectionner le fichier    timeout=3    error=timeOut!
    Choose File    //input[@name="urlFichier"]    ${nomFichier}
    sleep    1
    Click Element    //input[@value="Télécharger"]
    sleep    1
```

**Comment by aaltat** [comment]
Sorry, I unclear. I did mean an example that I can also run and it demonstrates the problem.

**Comment by houesmalek** [comment]
No problem

```
Open Browser    http://www.convertcsv.com/csv-to-pdf.htm    browser=firefox    ff_profile_dir=${FFProfileWeb}
    sleep    2
    Choose File    id=f1    exp.csv
```

[exp.txt](https://github.com/robotframework/SeleniumLibrary/files/2245454/exp.txt)


You can change the extension of the attached file to csv (it's not supported for upload here)

**Comment by aaltat** [comment]
Now I remember. `Choose File` must contain path to the file. SeleniumLibrary does not do anything in the background to discover the file. The `Get File` does little bit discovery, in the background, to find the path to the file. In short, this should work: 
```
*** Settings ***
Library    SeleniumLibrary

*** Test Cases ***
Test title
    Open Browser    http://www.convertcsv.com/csv-to-pdf.htm    Chrome
    Sleep    2
    Choose File    id=f1    ${CURDIR}/exp.csv
```
Although it could be useful to do `| Choose File | id=f1 | exp.csv | ` instead of  `| Choose File | id=f1 | ${CURDIR}/exp.csv | `. Would you be willing to provide a PR for it?

**Comment by houesmalek** [comment]
Thank you so much for your help. This works perfectly with the example we've made (but still not working on my project, I will try to figure out what's going on or will be back here).
However, what do you mean with "provide a PR for it" , I didn't get your point.

**Comment by aaltat** [comment]
PR means pull request. A way to contribute code for a project: https://help.github.com/articles/about-pull-requests/

**Comment by houesmalek** [comment]
Yes I would love to, but I don't know on which branch I should suggest my PR?

**Comment by pekkaklarck** [comment]
I think SeLib cannot automatically consider `x.txt` to be `${CURDIR}/x.txt` because it cannot know on which directory the file containing the keyword is. It could consider it to be `${EXECDIR}/x.txt`, and it's possible it already does that. Probably best to document the behavior and have example with `${CURDIR}`.

**Comment by aaltat** [comment]
Ah, is `${CURDIR}` always dynamically created and we can not use [Get Variable Value](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Get%20Variable%20Value) inside of the library? In that case, it is impossible to know, inside of the SeleniumLibrary, what `${CURDIR}` ìs. 

Currently it does not default to anything, but relies on [os.path.isfile](https://github.com/robotframework/SeleniumLibrary/blob/021ded5b901f9c94685546b76a55bb6b64104d81/src/SeleniumLibrary/keywords/formelement.py#L205)  to heck does `file_path` exist. The documentation already has an example with `${CURDIR}`, so I think documentation update is not needed. I guess we could try to check with `${EXECDIR}/x.txt` if [os.path.isfile](https://github.com/robotframework/SeleniumLibrary/blob/021ded5b901f9c94685546b76a55bb6b64104d81/src/SeleniumLibrary/keywords/formelement.py#L205) is `False`, but I not sure is that useful in real life.

**Comment by pekkaklarck** [comment]
`${CURDIR}` is replaced already when test data is parsed. We got robotframework/robotframework#596 about making it a normal variable, but that's not a simple task.

If you use `os.path.isfile` or other such functions with a non-absolute path, it is considered to be relative to the current working directory. Robot sets `${EXECDIR}` based on the cwd when test execution starts, but libraries or other code can use [os.chdir](https://docs.python.org/3/library/os.html#os.chdir) to change it.

Perhaps a note could be added that possible relative paths are considered to be relative to the current working directory. Don't think it makes sense to mention `${EXECDIR}`.

**Comment by aaltat** [comment]
Or the doc could be enhanced to explicitly to say that argument must be path to file, absolute or relative. Now it is little bit on implicitly said, except in the example. @houesmalek would you be interested to enhance the documentation?

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by rkefi84** [comment]
Hi guys,
I am getting this file not found error on choose file in both cases with ${CURDIR} or ${EXECDIR}
The Get File keyword finds the file in both cases

Both steps in my test 
`Get File    ${CURDIR}${/}people.csv`
`Upload 84 users csv file ${CURDIR}${/}people.csv`

Error in log :

`InvalidArgumentException: Message: invalid argument: File not found : file /Users/rkefi/Documents/Work/unified-admin-e2e/Tests/E2E/people.csv`

<img width="1361" alt="Screen Shot 2021-08-03 at 9 38 10 AM" src="https://user-images.githubusercontent.com/55718411/128025344-184d9a20-4cda-486a-abdb-e5c13e19473f.png">

**Comment by JohnMath3w** [comment]
Same issue as above, zip file exists on the system but after upload attempt, the error message says 
`InvalidArgumentException: Message: File not found`
