### ISSUE TITLE
Get File UTF-8 problem

### ISSUE THREAD

**Issue by houesmalek** [robotframework/SeleniumLibrary#1162]
Hello everyone, 

I'm trying to get a file so that I can use its content in my tests. The files in entrance are written in french ( contain special caracters "à, é, è...") and to recognize them I'm using UTF-8 encoding. But robot Framework still don't recognize these caracters and fails with this error: **UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0** 

Here is an example you can try 
```
test
    ${content}=    Get File    file.txt    encoding=UTF-8    encoding_errors=strict
    Log    ${content}
```
Anyone have any idea plz?

[file.txt](https://github.com/robotframework/SeleniumLibrary/files/2249640/file.txt)

**Comment by aaltat** [comment]
This is wrong issue tracker for that kind of problems and therefore I am closing this issue.

**Comment by HelioGuilherme66** [comment]
@houesmalek Although this is already closed, I observed that your file is not UTF-8 but CP1252. So you just have to correct your test.

**Comment by houesmalek** [comment]
@HelioGuilherme66 Thank you!
