### ISSUE TITLE
Problem with encoding character on keyword Click Link

### ISSUE THREAD

**Issue by sgaunet** [robotframework/SeleniumLibrary#1165]
This  test case doesn't work :  

```
*** Settings ***
Library           SeleniumLibrary

*** Variables ***
${URL}            https://www.linternaute.fr/dictionnaire/fr/definition/requete/
${Browser}        ff

*** Test Cases ***

Exemple
	Open Browser    ${URL}    ${Browser}
	Click Link	13 synonymes de requête
	Page Should Contain	requête
	Close Browser
```

The line "Page Should Contain	requête " is working fine whereas the line "Click Link	13 synonymes de requête" is giving this error : 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 20: ordinal not in range(128)

The file is encoded in UTF-8.

Platform : windows 10 64 bit with python 2.7.15 and robot 3.0.4 (and the last version of seleniumlibrary)

Thanks

**Comment by pekkaklarck** [comment]
Could you run tests with `--loglevel debug` and paste the traceback you get here so that we can see where exactly the code breaks?

**Comment by sgaunet** [comment]
[log.zip](https://github.com/robotframework/SeleniumLibrary/files/2269538/log.zip)

Thanks for watching

**Comment by aaltat** [comment]
This is most likely duplicate of #1084 and that bug is fixed in the master code line. Could you install from GitHub directly: https://github.com/robotframework/SeleniumLibrary#installation and give it a try is it fixed.

**Comment by sgaunet** [comment]
Perfect, that's working. Thank you very much.
