### ISSUE TITLE
No more proxy option with recent update

### ISSUE THREAD

**Issue by aluneau** [robotframework/SeleniumLibrary#1166]
Hi, 
I use RobotFramework for 2 month ago. During this week I think a python package that SeleniumLibrary or robot framework need is not anymore compatible with the "http_proxy" environnement variable.
Is there a way to use proxy in order to contact a Selenium Grid (maybe a line of code to add in tests) ?
All I found on proxy is to use proxy on firefox or chrome but I can't find the information to use proxy in order to  contact the grid.

Thanks by advance

**Comment by aaltat** [comment]
I don't quite understand what is problem and what is thing that you want to do, but is not for some reason working.

**Comment by aluneau** [comment]
Ok I will reexplain.
I have a grid selenium and I need to pass throught a proxy to use it. 
(RobotFramework will need to use a proxy in order to proceed requests).
To do that I set my environnement variable
http_proxy
HTTP_PROXY
https_proxy
HTTPS_PROXY
It was working correctly until this days. It looks like RobotFramework does not use proxy anymore since I' updated pip packages.
I'm pretty sure that it's a proxy problem because the answer (bad gateway) (in wireshark) is the same as when i'm not using proxy.

I would like to know if there is an other solution to use proxy in RobotFramework.
My colleague do exactly the same except he did not update his packages and it is still working.

**Comment by aaltat** [comment]
Well, there are actually quite a lot different Python pagages and OS related things which could affect the to the problem. Could you pinpoint the exact SeleniumLibrary version which causes the problem. First install the version that did work and then upgrade one version up and try again. And continue to install new versions until you find the version where the problem starts. Then report the version where the proxy works and where it doesn't. Example it works on SeleniumLibrary 3.1.0 but does not work in SeleniumLibrary 3.1.1.

In this way we can look at the changes between version and perhaps find the reason for the bug.

**Comment by aaltat** [comment]
Also if you did update Selenium, they have swapped some internal dependencies, which may also affect: https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES

**Comment by aluneau** [comment]
Thanks a lot for your answer.
It is exactly the problem.
I swap selenium 3.14 for 3.13 and it is working.
It seems that urllib3 does'nt care about proxy. It will be a problem for the future for me.

Thanks again !

**Comment by pekkaklarck** [comment]
Is it really so that urllib3 doesn't support the (de-facto) standard environment variables `http_proxy/https_proxy/no_proxy`? That would be strange but I assume they'd have a good reason for that. Selenium losing this support as a consequence of switching from urllib2 to urllib3 would, in my opinion, be a bug in Selenium and should be reported in their tracker.

**Comment by aluneau** [comment]
Yes it is strange.
I found the documentation for proxy and it seem that proxy have to be specified in the code (http://urllib3.readthedocs.io/en/latest/advanced-usage.html#proxies)

I've opened an issue on selenium github: https://github.com/SeleniumHQ/selenium/issues/6264

Thanks for your help.

**Comment by aaltat** [comment]
I strongly agree with @pekkaklarck and it would be best to report the problem to the Selenium issue tracker.

**Comment by aaltat** [comment]
In any case, this looks like a Selenium problem and not a SeleniumLibrary issue and therefore I am closing this issue.
