### ISSUE TITLE
Evolution : take account client certificate

### ISSUE THREAD

**Issue by astrowalker2013** [robotframework/SeleniumLibrary#1167]
Is it possible to developped for SeleniumLibrary a feature to take accunt certificate client. 
like p12 certificate

**Comment by aaltat** [comment]
How that would be implemented by using Selenium and Python?

**Comment by aaltat** [comment]
I did looked into this issue and finding solution that would require browser or operating system specific code seems impossible to do. At least code would be very browser and Selenium version specific. Therefore I am deciding against the proposal and closing this issue.
