### ISSUE TITLE
Find by CSS path not working with Robot

### ISSUE THREAD

**Issue by msslavanya** [robotframework/SeleniumLibrary#1168]
Hi All,
I tried this with python3.7  and found working for clicking a particular content in css

DiagSearchPath = driver.find_element_by_css_selector("#gwt-uid-101>span")
DiagSearchPath.click()

However when I tried this in Robot framework as below, same was not working throwing an error ValueError: did not match any elements

upgradeXpath="css:#gwt-uid-101>span"

Click Element       ${upgradeXpath}

**Comment by aaltat** [comment]
The locator must be without the quotes: `css:#gwt-uid-101>span` and not `"css:#gwt-uid-101>span"`. 

If that was not the problem, please run the test with `--loglevel trace` and send the full stack trace, including the log messages from keyword.

**Comment by msslavanya** [comment]
Thanks.

I dont know how, but changing the variable with = did a magic it works.

upgradeXpath="css=#gwt-uid-101>span"

**Comment by msslavanya** [comment]
Issue solved

**Comment by pekkaklarck** [comment]
If `css=locator` works but `css:locator` doesn't, you are most likely using either Selenium2Library < 3.0 or a *very* old SeleniumLibrary version. The support for `:` is new in SL 3.0 (and S2L 3.0 which in practice is the same thing).
