### ISSUE TITLE
Add tests to setup.py

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#117]
We should consider adding a unittest testrunner to setup.py. Then one could easily run the tests by typing at the command line

```
python setup.py test
```

For more information see ["test"](http://packages.python.org/distribute/setuptools.html#test-build-package-and-run-a-unittest-suite) section of setup.py documentation.

**Comment by just-be-dev** [comment]
Is this really necessary? What are the benefits it provides over how we currently run tests?

**Comment by emanlove** [comment]
The idea is to move the test directory into the distribution so users have the tests along side the source. I am not sure if this is this ticket or another so please leave this one open. Thanks.

**Comment by aaltat** [comment]
I do not quite understand why we could like to do this. If someone could share some light why this would be useful, I am happy to hear it. But in mean time I am closing the issue.
