### ISSUE TITLE
Equivalent KeywordGroup class in SeleniumLibrary

### ISSUE THREAD

**Issue by deepakaravind** [robotframework/SeleniumLibrary#1170]
In Selenium2Library we had a keywordgroup module, however could not find the same in SeleniumLibrary?  Is there an equivalent module available in SeleniumLibrary or any similar one.  This statement works fine in Selenium2Library "from Selenium2Library.keywords.keywordgroup import KeywordGroup" but not in SeleniumLibrary
https://github.com/carbonblack/robotframework-selenium2library/blob/master/src/Selenium2Library/keywords/keywordgroup.py

**Comment by aaltat** [comment]
The SeleniumLibrary architecture was charged during the 3.0 and lot of internal was charged, deleted or created. One of the deleted objects was the keyword group and moving to use Robot Framework dynamic library API. Could you tell what you want to do and perhaps we can point you to right direction?

**Comment by deepakaravind** [comment]
Thanks for the response @aaltat We decided to re-implement the KeywordGroup that we had implemented in the past.  Please go ahead and close the issue.  Thanks.

**Comment by aaltat** [comment]
Good that you did found a solution. SeleniumLibrary uses now days https://github.com/robotframework/PythonLibCore for fulfilling the Dynamic API needs, like the keyword discovery. It gives more flexibility for the library building. For further, it might be worth while to investigate.
