### ISSUE TITLE
Robotframework-3.0.2-angularjs_Validation issue

### ISSUE THREAD

**Issue by asief44** [robotframework/SeleniumLibrary#1174]
Hi All,
My application is angular js based, and unable to locate elements due to angular js calls.
Tried installing robotframework-angularjs via pip and installation was successful, but after adding angularjs library into eclipse(RED), some validating error pop-up is occurred.
**Below is the error message.**
Validating has encountered a problem.
An internal error occurred while "validating" .
\AngularJSLibrary\0273c5.lipspec(The system cannot find the file specified)

**Config details:**
 Robotframework - 3.0.2
robotframework-angularjs - 0.0.8
robotframework-selenium2library - 3.0.0
robotframework-seleniumlibrary - 3.1.1
robotframework-extendedselenium2library - 0.9.1

Kindly help on this issue.

Thanks in Advance!

**Comment by aaltat** [comment]
You are reporting this issue to wrong project and you are actually looking this project: https://github.com/Selenium2Library/robotframework-angularjs

But because this is not SeleniumLibrary issue, I am closing this issue.
