### ISSUE TITLE
Check Selenium2Library setup.py installation issues 

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#118]
Been reported that you need Python 2.7 and disutils on both Linux and MacOSX in order to have buildout install selenium2library **_plus**_ it's dependencies. Need to very easy_install and pip but our installer should install dependencies for Python 2.6 and 2.7.

**Comment by aaltat** [comment]
I haven not heard complaints about this for a long time, in Mac or any other platform. There has been some installation problems, but they all have been for Python 3. I think we close the issue.
