### ISSUE TITLE
Waiting too long in keywords from other Library will raise error: ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by louislewatcn** [robotframework/SeleniumLibrary#1196]
I am using SeleniumLibrary and SikuliLibrary to test html5 games, start browser and click play games by images

I don't know whether it is by design or not, but i have troubles dealing with built-in keyword "Sleep" and keywords which will wait long time from other libs.
I know there are many keywords SeleniumLibrary provides to deal with wait such as "Wait Until Page Contains".
But sometimes, the keywords from other Library such as "robotframework-SikuliLibrary"."Wait Until Screen Contain", which is used to verify an image exists on screen within a period of time.
After this keyword runs, the selenium socket will be closed like the situation where I used Sleep 10

Is there any setting that may avoid this: Sleep will stop the selenium local socket?

Below is the sleep example and its log.
![robot](https://user-images.githubusercontent.com/23356201/45343894-c950a580-b5d4-11e8-9111-a914d0bf7c55.PNG)
![log](https://user-images.githubusercontent.com/23356201/45343902-cf468680-b5d4-11e8-847b-e98bb30a1259.PNG)

This one is working with sikuli keywords
I covered the Windows button for 15 seconds and then uncover it to let the waiting time reach 15 seconds
![sikulitest](https://user-images.githubusercontent.com/23356201/45350112-a5e22680-b5e5-11e8-80d5-6ab046f55ccf.PNG)
![silulifail](https://user-images.githubusercontent.com/23356201/45350119-a975ad80-b5e5-11e8-87d3-660ddbbed813.PNG)
Windows Button to click in test
![windowskey](https://user-images.githubusercontent.com/23356201/45350164-bf836e00-b5e5-11e8-8b9f-f5af3d53f446.png)

**Comment by aaltat** [comment]
Interesting problem, for some reason Selenium can not anymore communicate to the Geckodriver. Can you reproduce the problem with Chrome or perhaps without SikuliLibrary? Also have you checked that the Selenium, Geckodriver and Firefox are compatible with each other?

**Comment by louislewatcn** [comment]
I can not reproduce it using other browsers,
I have used the latest version of Geckodriver and  Selenium 3.12.0 and the latest version of firefox
Maybe the issue are caused as you said, I will try with the different drivers and  Seleniums

**Comment by louislewatcn** [comment]
Yeah, i have used a previous version of Geckodriver, it worked.
Thanks for your advice. It ended my 2 day debugging.
I guess this is the bug related the latest version of Geckodriver.
So the issue can be closed
