### ISSUE TITLE
Drag and drop across iframe bounds is problematic

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#120]
The drag events are all bound within the toolbar iframe.  Example need - "We have a scenario here where we are grabbing a drag source in an iframe and dropping on a drag target in the parent window. I can 'Select Frame' to get the drag target, and Unselect Frame to return to the main window, but the Drag and Drop keyword doesn't appear to allow for that kind of context switching."

**Comment by emanlove** [comment]
One solution is to drag and drop by offset. Having an source element and target element you should be able to get positions of each, using "Get Horizontal Position" and "Get Vertical Position" keywords. From there determine offset. **_Remember**_ though the click keywords uses the center of the element so you might also need size of element to properly calculate offset.

**Comment by emanlove** [comment]
There is also a 'Mouse Down' keyword as well as a 'Mouse Up' keyword that might be used in conjunction to deal with the stated scenario.

**Comment by aaltat** [comment]
Ed, is this still an issue or could we close this one? The frames are getting quite rare in these days, although there is one part in our application where frames are still being used.

**Comment by emanlove** [comment]
I haven't tried in a while nor needed to try it. In the effort to close old issues let me say...

If anyone feels that this is still valid issue or this becomes an issue again, please send an update, reopen the ticket or create a new one.
