### ISSUE TITLE
Add example to Get Element Attribute keyword how to solve the removed deprecated functionality

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1204]
To avoid further questions add example to Get Element Attribute keyword how to solve the removed deprecated functionality. This will help users to them self overcome the problem.

**Comment by pekkaklarck** [comment]
In my opinion the kw doesn't need an example of the old usage. The issue removing the functionality getting such example ought to be enough.

**Comment by aaltat** [comment]
Agreed and done. Closing this issue.
