### ISSUE TITLE
error when element not found with unicode string in locator

### ISSUE THREAD

**Issue by bachng2017** [robotframework/SeleniumLibrary#1211]
os: centos 6.10
python: 2.7
robotframework-seleniumlibrary  3.1.1
selenium                        3.14.1

We had problem when an element with unicode xpath not found. Is this a known issue ?

```
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/SeleniumLibrary/keywords/element.py", line 34, in get_webelement
    return self.find_element(locator)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/SeleniumLibrary/base/context.py", line 62, in find_element
    return self.element_finder.find(locator, tag, True, required, parent)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/SeleniumLibrary/locators/elementfinder.py", line 76, in find
    .format(element_type, locator))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 39-44: ordinal not in range(128)
```

**Comment by aaltat** [comment]
This is most likely fixed in SeleniumLibrary 3.2.0 release: https://github.com/robotframework/SeleniumLibrary/issues/1084 Please update your SeleniumLibrary and retest.

**Comment by bachng2017** [comment]
thanks a lot for your prompt response. Yes, I could confirm that the problem is fixed with 3.2.0. 
```
ElementNotFound: Element with locator '//div[@class="submenu" and contains(.,"\u30dd\u30ea\u30b7\u30fc\u7ba1\u7406")]' not found.
```
the only minor thing is the msg is not displayed as a unicode. But it is not big issue for me

**Comment by pekkaklarck** [comment]
Could you test how the error looks with Python 3? I highly recommend Python 3 in general, but especially when working with non-ASCII strings.

**Comment by bachng2017** [comment]
it looks good with Python3
```
SeleniumLibrary.errors.ElementNotFound: Element with locator '//div[@class="submenu" and contains(.,"ポリシー管理")]' not found.
```
but we still have support Python2.7 for a while.

**Comment by aaltat** [comment]
It's somewhat inconvenient that error is not available in clear text in Python 2. If you think that would be an important fix, please submit separate issue for it.

But because the original issue is actually fixed, I am closing this issue.

**Comment by bachng2017** [comment]
Ok thanks alot
