### ISSUE TITLE
Chrome is not a supported Browser

### ISSUE THREAD

**Issue by Anil-KumarE** [robotframework/SeleniumLibrary#1225]
I am running a simple basic test to launch the browser through Robot framework and my test fails in the open browser step. I am not sure what changes went in that is causing this trouble:

*** Settings ***
Documentation
Library     SeleniumLibrary
Resource    ../Resources/CommonAuth/LoginPage.robot

*** Variables ***
${Browser}  =   chrome
${URL}      =   http://www.google.com

*** Test Cases ***
Login to the CS Home page
    open browser    ${URL}  ${Browser}
    #   LoginPage.Navigate to
    LoginPage.Verify page Loaded
    LoginPage.Enter User Credentials

Error:
Login to the CS Home page                                             | FAIL |
ValueError: =chrome is not a supported browser.

**Comment by drobota** [comment]
It seems that the browser is `=chrome`. I can say it for sure If you provide some logs. Please, check for extra spaces in the variables section.

**Comment by Anil-KumarE** [comment]
Gotch thanks space in between ${Browser} and = is making = the first character input.
