### ISSUE TITLE
"Open Browser" & "Go TO" fails to launch URL having window authentication

### ISSUE THREAD

**Issue by SivaArunBalaji** [robotframework/SeleniumLibrary#1228]
Hi Team,
We are unable to launch windows authenticated URL in latest chrome version >V.66 using the compatible driver > v.42&v.43.

**Comment by aaltat** [comment]
I do not understand what is the problem. Could you show an simplified example which demonstrates the problem? Would it be possible also us to run the example? Are there errors, if yes please share the error with us (use `--loglevel trace` when running the test.) If there are popup's or dialogues, please share them too.

**Comment by SivaArunBalaji** [comment]
We are automating web application, where the login credential should be entered through windows authentication. 

Robot Code:
*** Settings ***
Library           Selenium2Library

*** Test Cases ***
TestWindows_Authentication
    Open Browser    https://the-internet.herokuapp.com/basic_auth    gc
    log    Testing Windows Authentication
    [Teardown]    Close All Browsers

Version Details(32 Bit):
robotframework==2.8.4
robotframework-selenium2library==1.7.1
Python 2.7.2
Chrome Version : 68.0.3440.106
Driver Version : 2.42

We have tried other options mentioned in the below link
https://seleniumjava.com/2017/04/30/how-to-deal-with-windows-authentication-popups/

It is not working. Kindly advise

**Comment by aaltat** [comment]
Ah this is a basic authentication, last time I've tested using format: `http://user:pass@host`.

But because this is a support issue, I am closing the issue. For further support, please see: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
