### ISSUE TITLE
Support Appium For MAC to find native mac element issue

### ISSUE THREAD

**Issue by qifeiLiu** [robotframework/SeleniumLibrary#1231]
# Prerequisites
**Use Python Selenium Library**:
`WindowPath = "/AXApplication[@AXTitle='Citrix Workspace']/AXWindow[@AXTitle='Citrix Workspace' and @AXIdentifier='_NS:14' and @AXSubrole='AXStandardWindow']"`
`SheetPath = WindowPath + "/AXSheet[@AXIdentifier='_NS:51']"`
`CancelButton_path = SheetPath + "/AXButton[@AXIdentifier='_NS:12']"`
`desiredCapabilities = {'platform':'Mac', 'commandDelay':50, 'loopDelay':1000, 'implicitTimeout':utilities.defaultImplicitTimeout_sec * 1000, 'mouseMoveSpeed':50, "screenShotOnError":1}`
`driver = webdriver.Remote( command_executor='http://xx.xx.xx.xx:4622/wd/hub', desired_capabilities=desiredCapabilities)`
`driver.get("Citrix WorkSpace")`
`button_Cancel = driver.find_element_by_xpath(CancelButton_path)`

The last step **find_element_by_xpath**  works with no error

# For issues
**Use Robot SeleniumLibrary**
*** Settings ***
Library    SeleniumLibrary
Library    SeleniumLibraryExtendForMAC    
Library           Collections
Variables         ../WSH RF Variable/env_MAC.py

*** Keywords ***
Open MAC APP
    [Arguments]    ${AppName}
     ${dc}    Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.IPAD   sys,selenium.webdriver
     Collections.Set To Dictionary    ${dc}    version    ${1.0}
     Collections.Set To Dictionary    ${dc}    browserName    ${EMPTY}
     Collections.Set To Dictionary    ${dc}    commandDelay    ${50}
     Collections.Set To Dictionary    ${dc}    loopDelay       ${20000}
     Collections.Set To Dictionary    ${dc}    mouseMoveSpeed   ${50} 
     Collections.Set To Dictionary    ${dc}    screenShotOnError   ${1}
     #${experimental_options}    BuiltIn.Create Dictionary        @{defaultCookies}
     #Collections.Set To Dictionary    ${dc}    cookies    @{defaultCookies}
     BuiltIn.Set Global Variable    ${DESIRED_CAPABILITIES}    ${dc}   
     #SeleniumLibrary.Add Cookie    name    value
     Create Webdriver    Remote     command_executor=${appiumServer}  desired_capabilities=${DESIRED_CAPABILITIES}
     BuiltIn.Run Keyword And Ignore Error    SeleniumLibrary.Go To    ${AppName}

*** Test Cases ***
MAC Casting
    BuiltIn.Log    ${CancelButton_path}    
    Open MAC APP    Citrix Workspace
    #AppiumLibrary.Click Button  xpath:${CancelButton_path}
    **Get Webelement    xpath:${CancelButton_path}**

## Error messages and additional information
Starting test: WSH-RF.ROBOT-TC.06 MAC.MAC.MAC Casting
20181102 01:27:26.887 : INFO : /AXApplication[@AXTitle='Citrix Workspace']/AXWindow[@AXTitle='Citrix Workspace' and @AXIdentifier='_NS:14' and @AXSubrole='AXStandardWindow']/AXSheet[@AXIdentifier='_NS:51']/AXButton[@AXIdentifier='_NS:12']
20181102 01:27:26.889 : INFO : ${dc} = {'platform': 'MAC', 'browserName': 'iPad', 'version': ''}
20181102 01:27:26.896 : INFO : ${DESIRED_CAPABILITIES} = {u'screenShotOnError': 1, u'loopDelay': 20000, 'platform': 'MAC', 'browserName': '', 'version': 1.0, u'commandDelay': 50, u'mouseMoveSpeed': 50}
20181102 01:27:26.897 : INFO : Creating an instance of the Remote WebDriver.
20181102 01:27:27.089 : INFO : Opening url 'Citrix Workspace'
20181102 01:27:28.028 : FAIL : NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

Ending test: WSH-RF.ROBOT-TC.06 MAC.MAC.MAC Casting

The AXPATH  locator could not be located.

## Environment
Test  native mac element
Appium For MAC : https://github.com/appium/appium-for-mac#installation
Operating System: macOS High Sierra version 10.13.6
Libraries
- Robot Framework: Version: 3.0.4
- Selenium: Version 3.14.0
- SeleniumLibrary: Version 3.2.0
- Interpreter: Python27

**Comment by aaltat** [comment]
Because there is an error, run the Robot Framework test with `--loglevel trace` set from command line, copy paste the full error message from the log.html in https://gist.github.com/ and send the link.

**Comment by qifeiLiu** [comment]
@aaltat the log.html link here:https://gist.github.com/qifeiLiu/6622cd045f1db3de1f8cd660d5065675

**Comment by aaltat** [comment]
The `Get WebElement` keyword is an asset type of keyword and it doesn't wait. Usually this type of problems are solved by waiting, example by http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Page%20Contains%20Element

But because this is more of an support issue and not a bug report, I am therefore closing the issue.  For support please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
