### ISSUE TITLE
Can't import seleniumlibrary on ride

### ISSUE THREAD

**Issue by kachunni** [robotframework/SeleniumLibrary#1237]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by kachunni** [comment]
I have installed Selenium2 and Selenium libraries with Robot framework and Ride and have configured corresponding Path variables.
When import Selenium2Library or seleniumlibrary , the library name was red,
Got below log messages from Ride log. Could anybody let me what's wrong? Thank you!
20181119 23:01:10.393 [INFO]: Found Robot Framework version 3.0.4 from 'C:\Python27\lib\site-packages\robot'.

20181119 23:01:10.397 [INFO]: Started RIDE 1.5.2.1 using python version 2.7.15 with wx version 2.8.12.1 in win32.

20181119 23:01:40.197 [WARN]: Importing test library "selenium2library" failed

Traceback (most recent call last):
Importing test library 'selenium2library' failed: ImportError: No module named selenium2library
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\WINDOWS\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\setuptools-39.2.0-py2.7.egg
  C:\Python27\lib\site-packages\pip-10.0.1-py2.7.egg
  C:\Python27\lib\site-packages\setuptools_scm-3.1.0-py2.7.egg
  C:\Python27\lib\site-packages\kitchen-1.2.5-py2.7.egg
  C:\Python27\lib\site-packages\pytest_runner-4.2-py2.7.egg
  C:\Python27\lib\site-packages\decorator-4.3.0-py2.7.egg
  C:\Python27\lib\site-packages\pygments-2.2.0-py2.7.egg
  C:\Python27\lib\site-packages\six-1.11.0-py2.7.egg
  C:\Python27\lib\site-packages\natsort-5.4.1-py2.7.egg
  C:\Python27\lib\site-packages\appium_python_client-0.30-py2.7.egg
  C:\Python27\lib\site-packages\urllib3-1.24.1-py2.7.egg
  C:\Python27\lib\site-packages\robotremoteserver-1.1-py2.7.egg
  C:\Python27\lib\site-packages\robotframework_pabot-0.45-py2.7.egg
  C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.4.6-py2.7.egg
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Python27\lib\site-packages\robotide\spec
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by aaltat** [comment]
Library imports are case sensitive. You are importing library with all letters written in lower case, but it must be `Selenium2Library`. 

Because I don't see a problem with the SeleniumLibrary and this definitely is a support request, I am closing the issue.

**Comment by kachunni** [comment]
> Library imports are case sensitive. You are importing library with all letters written in lower case, but it must be `Selenium2Library`.
> 
> Because I don't see a problem with the SeleniumLibrary and this definitely is a support request, I am closing the issue.

20181120 11:46:04.492 [WARN]: Importing test library "Selenium2Library" failed

Traceback (most recent call last):
Importing test library 'Selenium2Library' failed: ImportError: No module named Selenium2Library
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\WINDOWS\SYSTEM32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\setuptools-39.2.0-py2.7.egg
  C:\Python27\lib\site-packages\setuptools_scm-3.1.0-py2.7.egg
  C:\Python27\lib\site-packages\kitchen-1.2.5-py2.7.egg
  C:\Python27\lib\site-packages\pytest_runner-4.2-py2.7.egg
  C:\Python27\lib\site-packages\decorator-4.3.0-py2.7.egg
  C:\Python27\lib\site-packages\pygments-2.2.0-py2.7.egg
  C:\Python27\lib\site-packages\six-1.11.0-py2.7.egg
  C:\Python27\lib\site-packages\natsort-5.4.1-py2.7.egg
  C:\Python27\lib\site-packages\appium_python_client-0.30-py2.7.egg
  C:\Python27\lib\site-packages\urllib3-1.24.1-py2.7.egg
  C:\Python27\lib\site-packages\robotremoteserver-1.1-py2.7.egg
  C:\Python27\lib\site-packages\robotframework_pabot-0.45-py2.7.egg
  C:\Python27\lib\site-packages\robotframework_appiumlibrary-1.4.6-py2.7.egg
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Python27\lib\site-packages\robotide\spec
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by aaltat** [comment]
For more support please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Comment by kachunni** [comment]
> For more support please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

got it sorted ! thank you very much!!
