### ISSUE TITLE
Need to swipe the web page using coordinates

### ISSUE THREAD

**Issue by osandadeshan** [robotframework/SeleniumLibrary#1246]
# Feature requests

1. I need to swipe the web page using source coordinates and destination coordinates.
2. Using Java and Selenium I can use this code
```
        TouchAction action = new TouchAction(driver);

        int startY = element1.getLocation().getY() + (element1.getSize().getHeight() / 2);
        int startX = element1.getLocation().getX() + (element1.getSize().getWidth() / 2);

        int endX = element2.getLocation().getX() + (element2.getSize().getWidth() / 2);
        int endY = element2.getLocation().getY() + (element2.getSize().getHeight() / 2);

        action.press(startX, startY).waitAction(2000).moveTo(endX, endY).release().perform();
```
3. I need to do this using Robot framework

**Comment by aaltat** [comment]
So in practice you want keyword that looks like something like this
```
| Swipe From Element To Element | start_locator | end_locator | pause | message |
```
With that keyword, it should move mouse to the element indicated by `start_locator`, press mouse key down. Pause for `pause` seconds. Move mouse to the element indicated by `end_locator`. And finally release the mouse button. I guess that is useful, specially when testing mobile views. But for normal web app it feels lot of like drag and drop, what is the difference?  

In terms of Selenium API methods, one should look at these methods: https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.action_chains.ActionChains.click_and_hold https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.action_chains.ActionChains.move_to_element https://selenium-python.readthedocs.io/api.html#selenium.webdriver.common.action_chains.ActionChains.pause

**Comment by osandadeshan** [comment]
Actually in some web application has scrollable views inside the web page. There I need to click on elements which will be visible only after scrolling.

**Comment by aaltat** [comment]
Then would this be better: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Scroll%20Element%20Into%20View

**Comment by pekkaklarck** [comment]
Isn't swiping a mobile thing only? I got a feeling that trying to emulate it with click/hold/move is not at all the same thing. Does Selenium have built-in support for swiping or is it something that Appium and others provide? If Selenium supports swiping, exposing that functionality via SeleniumLibrary makes sense, but otherwise I'd say it's better to use other tools.

**Comment by osandadeshan** [comment]
@pekkaklarck 
Yes selenium supports that function.

**Comment by aaltat** [comment]
Hmmm, I did not see such thing, could you share a links?

**Comment by osandadeshan** [comment]
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html

**Comment by osandadeshan** [comment]
I have tried with this keyword. But still it won't scroll.

`Execute Javascript    document.getElementsByClassName('slimScrollDiv').scrollTop = document.getElementById('announcement-menu-item-link').offsetTop;`

**Comment by aaltat** [comment]
Here is the Python version of touch action: https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.common.touch_actions I tried few touch actions with Chrome (not in mobile view) and any they did not work in normal (not mobile view) mode. But are testing mobile views or do you just want to scroll?

**Comment by aaltat** [comment]
Is this still a problem or can the issue be closed?

**Comment by aaltat** [comment]
Closing due inactivity.
