### ISSUE TITLE
Cleanup: Delete branch `feature/ISSUE-763`

### ISSUE THREAD

**Issue by joaonc** [robotframework/SeleniumLibrary#1249]
The branch [feature/ISSUE-763](https://github.com/robotframework/SeleniumLibrary/tree/feature/ISSUE-763) is lingering around while the issue has been resolved and the keyword added in SeleniumLibrary 3.2.0 in PR #1083 

Branch should just be deleted.

**Comment by aaltat** [comment]
Done.
