### ISSUE TITLE
ff_profile_dir does nothing

### ISSUE THREAD

**Issue by jimpriest** [robotframework/SeleniumLibrary#1253]
I'm trying to use a new Firefox profile so I can control download directory location.

I've created Firefox profile and set directory.

In my Robot test I define the ff_profile_dir:

```
   Open Browser
    ...  url=${START_URL}
    ...  browser=${BROWSER}
    ...  ff_profile_dir=C:/Users/mydir/AppData/Local/Mozilla/Firefox/Profiles/robot
```

Run test - the file is downloaded but not in the correct directory defined in the profile.   

## Environment

- Windows 10
- geckodriver 0.23.0
- robotframework==3.0.4
- robotframework-seleniumlibrary==3.2.0
- selenium==3.141.0
- ~~Firefox Developer Edition 64~~
- Firefox 63.0.3

**Comment by jimpriest** [comment]
I also tried this by creating my own create_profile keyword and calling it - I can see the temp profile get created but again - Robot doesn't seem to use ff_profile_dir...

```   
${profile_path}  Create Profile
Open Browser
...  url=${START_URL}
...  browser=${BROWSER}
...  ff_profile_dir=${profile_path}
```

```
def create_profile():
    fp=webdriver.FirefoxProfile()
    fp.set_preference("browser.download.folderList",1)
    fp.set_preference("browser.download.manager.showWhenStarting",False)
    # fp.set_preference("browser.download.dir",path)
    fp.set_preference("browser.download.dir","C:\\downloads")
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "image/png")
    fp.update_preferences()
    return fp.path
```

**Comment by aaltat** [comment]
I am not able to reproduce the problem. When I do this: 
```
| Open Browser | https://github.com/robotframework/SeleniumLibrary/issues/1253 | ff | ff_profile_dir=/home/username/.mozilla/firefox/nfgn0cqg.default | 
```
And when test is run test, I can see that my profile is used and I am logged in GitHub. When running the test case with `--loglevel trace` I can see that the send profile is much bigger than the default profile. 

I am using: 
selenium==3.141.0
robotframework-seleniumlibrary==3.2.0
geckodriver 0.23.0
Firefox 63.0.3

I would try the official release of Firefox and I would check what the `geckodriver.log` contains.

**Comment by bjneuhaus** [comment]
@jimpriest  you might check if it works for you when using the [Firefox-ESR version](https://www.mozilla.org/en-US/firefox/organizations/) version.

**Comment by jimpriest** [comment]
@novacasa   Thanks! I'm going to purge my two Firefox installs this morning and then start from scratch. The ESR version looks ideal. 

@aaltat  Thanks for confirming things work!  Will examine geckodriver.log once I get things setup again.

**Comment by bjneuhaus** [comment]
@jimpriest  yw. I also had issues on that but the esr version was fine so I guess I had some version dependency issues - I'll look in that laterwhen I have time in general.
I'd prefer to just install an extension directly instead of using a complete profile like I do with chrome but I didn't get it run in FF so... the workaround rules the world ..

**Comment by jimpriest** [comment]
Still no luck.  Trying Firefox 63.0.3.  I tried to both pass in a hard coded path to the profile 

```
    Open Browser
    ...  url=${START_URL}
    ...  browser=${BROWSER}
    ...  ff_profile_dir=C:\\Users\\myhome\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\robot
```

As well as use my create_profile keyword.  

```
def create_profile():
    fp=webdriver.FirefoxProfile()
    fp.set_preference("browser.download.folderList",1)
    fp.set_preference("browser.download.manager.showWhenStarting",False)
    
    # pass in path as an arg
    # def create_profile(path):
    # fp.set_preference("browser.download.dir",path)
    
    fp.set_preference("browser.download.dir","C:\\Downloads")
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "image/png")
    fp.update_preferences()
    return fp.path
```

Test runs but no download.   Looking in geckodriver.log I see:

1544108375160	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\39231\\AppData\\Local\\Temp\\rust_mozprofile.wgvPvEezUvyd"

Going to try ESR version next.

**Comment by jimpriest** [comment]
Same issue with 60.3.0esr.

I even set the default profile to my new robot profile, opened it and set the download directory.

**Comment by aaltat** [comment]
Hmm, I did try in Linux, perhaps the problem is a Windows OS specific.

**Comment by jimpriest** [comment]
Doing the --loglevel trace I can see the giant string sent for the profile but it doesn't appear there is anything useful there unless there is some way to unravel that blob.

My create_profile returns a valid path with a profile containing a user.js file which has my correct download path...  

c:\users\myuser\appdata\local\temp\tmpqcw4xj
user_pref("browser.download.dir", "C:/Users/myuser/Downloads/robot_downloads");

**Comment by jimpriest** [comment]
If I can do anything to help troubleshoot please let me know.  I'd rather not switch to Chrome as that is opening another can of worms :)

**Comment by aaltat** [comment]
I did modify your code and I did get the automatic download working with this code: 
```
from selenium import webdriver


def create_profile():
    fp = webdriver.FirefoxProfile()
    fp.set_preference("browser.download.folderList", 2)
    fp.set_preference("browser.download.manager.showWhenStarting", False)
    fp.set_preference("browser.download.dir", "D:\\tmp\\foobar")
    fp.set_preference("browser.helperApps.neverAsk.saveToDisk", "text/csv,application/java-archive, application/x-msexcel,application/excel,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/x-excel,application/vnd.ms-excel,image/png,image/jpeg,text/html,text/plain,application/msword,application/xml,application/vnd.microsoft.portable-executable")
    fp.update_preferences()
    return fp.path
```
And by running this test:
```
*** Settings ***
Library           SeleniumLibrary
Library           ./foo.py

*** Test Cases ***
Test 1
    ${ff} =    Create Profile
    Open Browser    https://www.seleniumhq.org/download/    ff    ff_profile_dir=${ff}
    Sleep    3
    Click Element    //p[text()='Download version ']/a
   # Keyword where which pols the correct file is present.  
```
There are two differences in the `create_profile` method: 
1) `fp.set_preference("browser.download.folderList", 1)`  -> `fp.set_preference("browser.download.folderList", 2)`
2) The MIME types are wider than in your example

The MIME types are based on this [blog post](http://makeseleniumeasy.com/2018/08/26/how-to-change-default-download-directory-for-firefox-browser-in-selenium-webdriver/). But because SeleniumLibrary and also Firefox seems to be working correctly, I am closing the issue.

**Comment by jimpriest** [comment]
IT WORKS!   I could have sworn I tried browser.download.folderList = 2 but that may have been before I reinstalled my browsers.

Thank you so much!

**Comment by Mohit3095** [comment]
I am facing a similar problem.
When i run the below test case:
Open Browser	    https://www.google.com	    browser=ff	    ff_profile_dir=C:/Users/userid/AppData/Roaming/Mozilla/Firefox/Profiles/Selenium

It opens firefox but it doesn't load the Selenium profile, instead it creates a temporary file and opens that.
**Environment:**

    Windows 10
    geckodriver 0.22.0
    robotframework==3.1.1
    robotframework-seleniumlibrary==3.0.1
    selenium==3.141.0
    Firefox : 66.0.3
     Python 2.7.10

Here is the profile when i look it in Firefox -> Help-> Troubleshooting Information

![image](https://user-images.githubusercontent.com/20072937/57405204-751db580-71a3-11e9-8467-c0bbe9f91bc0.png)

**Comment by jimpriest** [comment]
Are you creating the [profile as seen above](https://github.com/robotframework/SeleniumLibrary/issues/1253#issuecomment-445015582)? 

FWIW - I got this working but Firefox was always a bit of a pain I found and with Chrome becoming more and more popular I switched over and have had less issues.

**Comment by bjneuhaus** [comment]
Is userid a variable? Do you use minimum 2 spaces between keyword and argument?
Is the profilepath existing? I would also recommend to use proper path concat to avoid os specific path issues with / \ paths. 
Put it in a variable, Check before if exists, then use it as an argument.
Makes it even better due to you can override it on execution from outside.

 Open Browser  https://www.google.com	browser=ff  ff_profile_dir=C:/Users/userid/AppData/Roaming/Mozilla/Firefox/Profiles/Selenium

**Comment by Mohit3095** [comment]
Replying to both the comments : 
@jimpriest  
Not exactly, i created a Selenium profile manually using firefox Manager and i use that profile to run automation which is free of all plugins. 

And then using the Open Browser Keyword specified above i provide the path of the Selenium profile i created manually. 

I tried the same thing in chrome, even that is also not opening the default ff_profile_dir i provide.

Also if i run this chunk of code , it does open the right profile i need 

from selenium import webdriver 
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

options = Options()
options.add_argument("-profile")
options.add_argument("C:\\Users\\userid\\AppData\\Roaming\\Mozilla\\Firefox\\Default")
firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
driver = webdriver.Firefox(capabilities=firefox_capabilities, firefox_options=options)

@bjneuhaus  
it's my account name on my machine, not a variable, did not specify the name.
I have minimum 2 spaces between the keyword and argument. 
Profile path exists

**Comment by aaltat** [comment]
There has been quite a lot of changes since SeleniumLibrary 3.0.1, in the SeleniumLibrary and in Selenium side. Could you try to reproduce the problem with SeleniumLibrary 3.3.1 ?

**Comment by Mohit3095** [comment]
I installed the SeleniumLibrary 3.3.1 and ran the below test case:

Browser testing
    Open Browser    https://www.google.com    browser=ff    ff_profile_dir=C:/Users/userid/AppData/Roaming/Mozilla/Firefox/Profiles/Selenium 

But it still opens a temporary firefox profile instead of the one named Selenium.

Here is the env:
robotframework-selenium2library (3.0.0)
robotframework-seleniumlibrary (3.3.1)
selenium (3.141.0)

**Comment by Mohit3095** [comment]
I think I found the issue.
I had opened the Selenium profile in firefox browser manually that i was working on. Since that profile was already in use,  the same profile coudln't be opened twice using Selenium and RobotFramework.

**Comment by bjneuhaus** [comment]
I copy such folder to a temporary testfolder with a randomized path element or testid as index name so you can also do some testing without damaging your original one :)
Might check if a process with FF is already runnig on the sytem in Testuite setup + Close All Browsers.
Thanks for the feedback.

**Comment by Mohit3095** [comment]
sure @bjneuhaus , thank you for this check.
And i had one general question, manually if we try to a browser twice with the same profile name, it works but via selenium it doesn't . May sound a simple question but i haven't been able to get an answer on it by googling.
