### ISSUE TITLE
'Mouse Down' and 'Mouse Up' Bug

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#126]
The 'Mouse Down' and 'Mouse Up' buttons do not work unless you mouse is actually hovering over the firefox window.  This has been true in FF 14 and 15 but I have not observed this behavior in chrome or ie7, ie8, or ie9.

**Comment by srib4ufrnd** [comment]
For "mouser over" keyword as well I am facing an issue. I raised it as seperate issue for tracking. 
https://github.com/rtomac/robotframework-selenium2library/issues/131

**Comment by know1nos** [comment]
I've also noticed that it works properly if i remote into a virtual machine instead of using my local machine... not sure why

**Comment by know1nos** [comment]
i should add that the bug occurs on 6/6 local windows 7 machines and fails on all versions of firefox between 16 and 13, but does not occur on any of the virtual machines i am using which are also running windows 7

**Comment by emanlove** [comment]
This issue appears to be upstream within Selenium/WebDriver and not within Selenium2Library. Thus I am closing this issue. If you feel I am mistaken please reopen this ticket.
