### ISSUE TITLE
How to ignore ssl warning on Headless Chrome

### ISSUE THREAD

**Issue by zied-eb** [robotframework/SeleniumLibrary#1272]
My issue started when the tested web application was moved to HTTPS.
Since I am getting the "Not secure" Chrome warning, my tests are failing at the first checkpoint (a blank page is displayed on the generated error screenshot).

My question is: How to ignore the ssl warning screen?

1. I see that it is possible by using desired capability argument from [Open Browser](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Open%20Browser) Keyword, but it is not well documented.
2. After searching on internet, I see that there some keywords that could be used like (Evaluate, call...)  along with Open Browser, but again there is no clear documentation on this matter.

## Steps to reproduce the issue
Open Browser   |                     ${WELCOME_PAGE}      |           ${BROWSER}
Set Window Size      |               1920                   |         1080
Set Login Credentials      |         ${USERNAME_GOOD}      |          ${PASSWORD_GOOD}
Wait Until Element Is Visible  |     ${WEBELMT_LOGO}      |           ${WAIT_FOR_PAGE}

## Expected behavior and actual behavior

When I follow those steps, I see blanc screen (according to error screenshots)

I was expecting the warning displayed (So I will handle it by Selenium), or a way to ignore the warning

## Environment

Browser: Chromium latest (headless)
Browser driver: chromium-chromedriver latest
Operating System: Docker container based on Alpine 
Libraries
- Robot Framework: 3.0.4
- SeleniumLibrary: 3.2.0
- Interpreter: Python 2.7

## Proposal
1. Describe how to do this on the Documentation
2. add an argument for HTTPS handling (or use a current one)

**Comment by aaltat** [comment]
The  easiest way would be have valid certificate on your system. Have you looked at this one: https://stackoverflow.com/questions/24507078/how-to-deal-with-certificates-using-selenium

I understand your need, but we are not going to document and duplicate everything what is possible on the Selenium side. Also what you want to do is already possible in many ways, one can use the Create Webdriver keyword or create custom library keyword to open the browser as one please. 

Also this feels like a support requests than an issue or an enhancement requests. Therefore I am closing the issue.
