### ISSUE TITLE
TextFields with "onChange" js-event needs to be filled twice to values be available

### ISSUE THREAD

**Issue by Hi-Fi** [robotframework/SeleniumLibrary#129]
Environment: Wicket-based form, which validates text inputs
Problem: When "Input text" is ran first time, it empties the field (and value attribute), and causes event to fire (at this case submitting the form). When (in same command from Robot Framework) command tries to add text, it can't find element anymore. 

Workaround is to make Input text first inside "Run keyword and ignore error", but this just seems quite stupid way (plus it generates extra screenshot/page source in log).

Second time the event isn't fired, which causes need for following action to be performed twice (first launches the event, and second time puts the correct value to dropdown's selected).

**Comment by Hi-Fi** [comment]
For some reason Selenium's "clear" fires onChange event, and prevents running the Keyword 'til end. 

Workaround in Selenium2library is to find the element again after clear.

**Comment by j1z0** [comment]
when you clear an element the onChange event will occur.  That is correct.  This doesn't prevent the next statement from happening unless you application specifically handles onChange and then changes the focus or something of the element.

However I'm not sure your particular use case is best handled in Selenium2Library as for the vast majority of people onChange event doesn't shift focus / submit form or whatever.

I think Juho you may have better luck wrapping Selenium2Library and creating your own custom library on top of it so you can handle the specific logic of your application.

Cheers,
Jeremy

**Comment by Hi-Fi** [comment]
I actually have my own version of library in use. Just thought that this might be a thing that someone else will also struggle with, if using Wicket and filtering with onChange making form submit.

**Comment by aaltat** [comment]
There has not been activity for this issue for few years and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by Hi-Fi** [comment]
I'll try to create a test page and check this. At least code looks like same than that time.

**Comment by aaltat** [comment]
Could you also share information how did you handle the problem in your own library?

**Comment by Hi-Fi** [comment]
Created test page: http://fiddle.jshell.net/xsxd0p57/1/show/

Normally onChange() is launched only when I move out from field (by clicking something/pressing tab/filling other field). But if I put test 2 times to one field, onChange() prints empty result.

RF test case:

```
*** Settings ***
Library           Selenium2Library

*** Test Cases ***
OnChange Test
    Open Browser    http://fiddle.jshell.net/xsxd0p57/1/show/light/    ${BROWSER}
    Wait Until Page Contains Element    xpath=//iframe[contains(@src,'xsxd0p57')]    10s
    Select Frame    xpath=//iframe[contains(@src,'xsxd0p57')]
    Log Source
    Wait Until Page Contains Element    xpath=//input[@name='test']    10s
    Input Text    xpath=//input[@name='test']    Testing
    Input Text    xpath=//input[@name='test']    Testing2
    Capture Page Screenshot
```

This test results:
![selenium-screenshot-1](https://cloud.githubusercontent.com/assets/1499780/10991418/c8e85280-8465-11e5-912a-b25956231c68.png)

Same thing happens with Java version, so might be Selenium issue instead of libraries.

**Comment by BT-astauder** [comment]
This is also blocking us when testing a existing app that fires always one onchanges to much.
Does anybody know if this comes from selenium or robotframework?

**Comment by aaltat** [comment]
By looking the code, the keyword is really thin wrapper on top of the selenium. Also because it happens also with Java version, I would strongly suspect that it is an selenium or your application problem.

But there are workarounds for the problem and most likely the best solution for you is to build your own keyword to handle these kinds of situations.

**Comment by HelioGuilherme66** [comment]
I have just tested modified test and it passes with Chrome (with Firefox does not open the iFrame):

```
*** Settings ***
Library           Selenium2Library

*** Test Cases ***
OnChange Test
    Open Browser    http://fiddle.jshell.net/xsxd0p57/1/show/light/    ${BROWSER}
    Wait Until Page Contains Element    xpath=//iframe[contains(@src,'xsxd0p57')]    10s
    Select Frame    xpath=//iframe[contains(@src,'xsxd0p57')]
    Log Source
    Wait Until Page Contains Element    xpath=//input[@name='test']    10s
    Input Text    xpath=//input[@name='test']    Testing
    Input Text    xpath=//input[@name='test2']    Testing2
    Click Element    xpath=//body
    Capture Page Screenshot
    Close All Browsers
```

**Comment by BT-astauder** [comment]
@HelioGuilherme66 yes it passes because the fields are already empty. So to empty it it is no change and the empty log is not triggered. But you are also no longer testing for this bug.

**Comment by aaltat** [comment]
The way code works is the default way with selenium to clear the field. This is more a problem with the selenium than S2L and therefore closing the issue.
