### ISSUE TITLE
Close All Browsers fails with BadStatusLine error

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#1290]
## Steps to reproduce the issue
I'm using the Close All Browsers keyword in the Suite Teardown and it fails with BadStatusLine error.

## Error messages and additional information
![capturescreenshoterror](https://user-images.githubusercontent.com/13623153/51102463-6b7cd600-17df-11e9-8267-22d4d4a9a69e.PNG)
![closebrowserserror](https://user-images.githubusercontent.com/13623153/51102467-6e77c680-17df-11e9-89c2-911208d852be.PNG)

## Expected behavior and actual behavior
 - Expected behaviour: Close All Browsers closes all of the browser instances and the suite teardown finishes succesfully
 - Actual behaviour : Close All Browsers closes the browsers instances, but the suite teardown fails
## Environment

Browser: Google Chrome Version 71.0.3578.98
Browser driver: chromedriver 2.45.615291
Operating System: Windows 10
Libraries
- Robot Framework: 3.1.1
- Selenium: 3.141.0
- SeleniumLibrary: 3.3.1
- Interpreter: Python 2.7.12

**Comment by aaltat** [comment]
[Bad status line](https://docs.python.org/2/library/httplib.html#httplib.BadStatusLine) means that the ChromeDriver responded to the Selenium something which it did not understand. There is [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API between the Selenium and ChromeDriver (or any browser driver that matter). Now the ChromeDriver is responding, on the http level, something what the Python http library is not able understand. Based on the screen captures, it looks like the Selenium session has already died, for a reason which can not be seen from the logs. 

Would you be able to create a simplified example, which I can also run and demonstrates the problem?

**Comment by ghost** [comment]
@aaltat Here is a simple example, the same error occurs running this.

https://gist.github.com/bioneyez/a49035364b4a46e4abfacf3f6990d2e4

**Comment by aaltat** [comment]
I will give it try, I can not promise anything at this week, because of [RoboCon](https://robocon.io/), but after that should be possible.

**Comment by ghost** [comment]
Its okay, thanks for the help.

**Comment by aaltat** [comment]
I can not reproduce the problem. I tried in Linux and Windows 10. I use:
* Chrome 71.0.3578.98
* ChromeDriver 2.45.615279
* robotframework-seleniumlibrary==3.3.1
* selenium==3.141.0
For me the Chrome opens, goes to: google.com and closes without errors.

**Comment by ghost** [comment]
Unfortunately I was expecting this result. Running the simple example gives this output for me.
![simplexample1](https://user-images.githubusercontent.com/13623153/51519882-790b0f00-1e22-11e9-89ed-d740e3b15697.PNG)
![simplexample2](https://user-images.githubusercontent.com/13623153/51519887-7ad4d280-1e22-11e9-8e48-29ccafca6162.PNG)
![simplexample3](https://user-images.githubusercontent.com/13623153/51519888-7c9e9600-1e22-11e9-8560-fc7cebaab9ba.PNG)

I dont know any of this information helps but we are behind company proxy. I tried reinstalling everything except Chrome.

**Comment by aaltat** [comment]
I do not have any good ideas, because I can not reproduce the problem, but here are few random ideas. 
* Reboot windows. Sometimes the chromedriver is left hanging in the background and Selenium starts behaving badly. Usually looking the process list and manually killing the chromedriver process will help. But sometimes reboot is needed.
* Create similar code in Python, run it and see does it produce same error. Do you need help for this? 
* Try with a different browser, Firefox is usually pretty good and see the result. 
* Try `Open Browser` keyword. 

I do not know what information that will bring but hopefully something useful.

**Comment by ghost** [comment]
- I tried rebooting and killing stucked chromedriver processes as well.
- I wrote this python code https://gist.github.com/bioneyez/34cfa8290b80ed2dbfd3e277dc3e5898 which fails as well. Here is the output https://gist.github.com/bioneyez/45fa305a0dda2d2b97511223b8e8872d
- I tried it with IE and Open Browser the result is 
![ieerror1](https://user-images.githubusercontent.com/13623153/51531314-5e925f00-1e3d-11e9-8f33-9572d220e0f7.PNG)
![ieerror2](https://user-images.githubusercontent.com/13623153/51531317-5fc38c00-1e3d-11e9-8a33-740a8080b1b5.PNG)

Since the Python code generated the same issue, I'm sure that Robot and SeleniumLibrary is not the root of the problem.

**Comment by aaltat** [comment]
Hmmm, it might be good idea to enable the ChromeDriver and Chrome logging in to a file, see details here: http://chromedriver.chromium.org/logging

**Comment by aaltat** [comment]
Also because you can produce the error with Selenium only, it might be good to ask from the Selenium side too: https://github.com/SeleniumHQ/selenium/issues

**Comment by ghost** [comment]
This is the log I got
[qc1.log](https://github.com/robotframework/SeleniumLibrary/files/2782568/qc1.log)

**Comment by aaltat** [comment]
I do not know how to help you more, I would ask from the Selenium side. They do not care about Robot Framework and SeleniumLibrary (When debugging problems), but if you show them you Python code and related logs, they should get interested.

**Comment by ghost** [comment]
Okay, thanks for all the help.

**Comment by aaltat** [comment]
If you decide to open issue to the Selenium side, could post the issue also in here? I would like to know also the solution to the problem.

**Comment by ghost** [comment]
Sure.  https://github.com/SeleniumHQ/selenium/issues/6870

**Comment by rnth** [comment]
Using selenium 3.3.1 instead of 3.141 fixes the issue. Something wrong between python and selenium 3.141 connections !!

**Comment by aaltat** [comment]
The Selenium API, for closing browser is identical in Selenium 3.3.1 and 3.141. This is a Selenium problem and can not fixed SeleniumLibrary project.

**Comment by aaltat** [comment]
Closing this issue because the problem is in the Selenium side.
