### ISSUE TITLE
Investigate html 5 different input types

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1291]
The HTML 5 different [input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_input_types), like `date` are supported by the library but are untested. It would be good to write test for the input types supported by the library.

The `Input Text` will always clear the input field and in the same time it would be good to find out can the clearing be done for all input types.

**Comment by aaltat** [comment]
This was investigated in RoboCon sprints and new html 5 some input types have problems with `Input Text` keyword because they can not be cleared. I see two options

1. Make clear configurable. 
2. Build detection when clearing can not be done and do not try to clear elements when it is not possible. 

I would prefer the 1 option.

**Comment by pekkaklarck** [comment]
In my opinion 1 alone is bad usability, but being able to disable clearing could be useful  as well. I'd prefer doing both.

**Comment by pekkaklarck** [comment]
Don't we know which input types cannot be cleared? If yes, it ought to be easy not to do that in those cases. That could be the default behavior, but a separate option could be added to force/disable clearing. Could be `clear=None` that can then be turned to `True/False` if needed.

**Comment by aaltat** [comment]
Based on the input from RoboCon different browsers do behave unexpectedly, so therefore it is was not clear. But I can do some more digging with the different input types and see what input types do not support clear.

**Comment by pekkaklarck** [comment]
If not clearing certain elements causes a problem with some browser, then that's obviously not a good idea. Having an option to force/disable clearing would nevertheless be a good idea.

**Comment by aaltat** [comment]
Lets do option 1 at least, with a configurable `clear` argument.

If some consensus is found, among browser vendors, could make it automatic. But it should work like this:
- When `clear=None` then do the automatic detection of clearing. User leaves the SeleniumLibrary to decide is the `input`element cleared or not. 
- When `clear=True` (or any [boolean](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Boolean%20arguments) True value) clearing will be always done and no automatic detection. 
- When `clear=False` clearing will not be done and no automatic detection.

**Comment by pekkaklarck** [comment]
If there are tests for various input types, it ought to be easy to see which shouldn't be cleared.

**Comment by aaltat** [comment]
I did write test for each new html 5 input type, see #1327 . All the new input types did work with `Input Text` keyword with Chrome and Firefox without any errors. Although in some tests the `value` attribute does is not properly filled. 

But because `Input Text` keyword does not fail (although it always calls Selenium `clear` method), the automatic clearing detection is not needed. But I wonder should we make configurable does the `Input Text` keyword call the Selenium [clear](https://selenium-python.readthedocs.io/api.html?highlight=clear#selenium.webdriver.remote.webelement.WebElement.clear) method?

**Comment by aaltat** [comment]
Well this issue is already quite cluttered and the original goal is already done. Therefore I am going to close this issue and open a new one for making the clearing configurable.

**Comment by pekkaklarck** [comment]
When you @aaltat wrote

> But because there is not errors, the automatic clearing is not needed. 

did you mean there's no need to call the `clear()` method at all or that it was always OK to call it?

And when you wrote

> Although in some tests the value attribute does is not properly filled.

why was that? Was it related to clearing, was the data invalid, or what? Related to that, it would be good to have some tests (don't know are there already) for typing invalid values into these dedicated fields (e.g. something like "Hello world!" to a date field).

**Comment by aaltat** [comment]
It is always OK to call Selenium `clear`, the `Input Text` keyword does not fail.

I did try with different kinds of input values, the problematic ones are: `color`, `datetime-local` `month` and `range`. Based on the testing, they seem to be really picky about the format of the text (like those date related things) or the Selenium `send_keys` is not triggering the correct event in the browser (true on `color` and `range`). 

Also I try invalid values for the different input elements. Browsers seems to just ignore wrong input, errors are not presented or wrong value is not visible in the element, also the keyword does not fail. Also different browser seems to validation in different ways and accept different kind of values, this true with dates type of input elements (I hate dates and it's different formats.)

**Comment by pekkaklarck** [comment]
OK. It would be nice to do input validation to make sure values are actually accepted but I'm not sure is it worth the effort. Definitely not part of this issue anyway.
