### ISSUE TITLE
run keyword if ${name1} = ${name2}

### ISSUE THREAD

**Issue by Anil-KumarE** [robotframework/SeleniumLibrary#1294]
I am trying to match text in between two elements and move into next step if those two match using the For loop and Run keyword If

Find a File
    ${xpath}=    set variable    //div[@id='wrapper2']//div[@id='content']//form[@id='theform']//div[@class='messageblock']//div
    ${count}=    get matching xpath count    ${xpath}
    ${names}=    create list
    : FOR    ${i}    IN RANGE    1    ${count} + 1
    \    ${name}=    Sel.get text    xpath=(${xpath})[${i}]
    \    append to list    ${names}    ${name}
    \    run keyword if    ${name}==${FROM_SENDER_EMAIL}    Get the Element   exit for loop

Get the Element
    ${Element_Name}=    ${name}

Seeing the following  error: Evaluating expression 'Remote==' failed: SyntaxError: unexpected EOF while parsing (<string>, line 1)

can i get some help here ...

**Comment by aaltat** [comment]
Could you build a simple example which I can run and demonstrate the problem.

**Comment by Anil-KumarE** [comment]
updated the issue it didnt post correctly initially

**Comment by Anil-KumarE** [comment]
- <div id="wrapper2" class="round">
	<div id="content" class="round">
		<form id="theform">
			<label class='SectionTitle'  >New files</label>
			<br />
			<div class = 'rightcontent'>
				<div class='messageblock'>
					<div class='messagesubjectlabel'>
						<a href='HyperLink 1' target='_blank' title='Download all files'>Test File</a>
					</div>
					<div class='messageinfoblock'>
						From: email id 1
						<div class="dropdownTrigger dropdownArrow"  data-dropdown="#dropdown-99841f00-49d6-4dac-9395-af353c440e0e-waiting">
						</div>
					</div>
				</div>
			</div>					
			<label class='SectionTitle'  >Incomplete uploads</label>
			<br />
			<div class = 'rightcontent'>
				<div class='messageblock'>
					<div class='messagesubjectlabel'>
						<a href='Hyperlink 2' target='_blank' title='Upload all files'>Test Rest</a>
					</div>
					<div class='messageinfoblock'>
						To: email id 2
						<div class="dropdownTrigger dropdownArrow"  
						data-dropdown="#dropdown-57ce262b-6290-44d6-ae1f-1d8da4a93c7d-resumableUploads">
						</div>
					</div>
				</div>
			</div>					
          </form>        
        </div>
</div>
[demo code.txt](https://github.com/robotframework/SeleniumLibrary/files/2779792/demo.code.txt)

**Comment by Anil-KumarE** [comment]
i have attached the sample code please let me know if it is not accessible.

**Comment by aaltat** [comment]
There is something wrong with the URL or with file content, for me it opens a XML file. Could you provide a correct file?

**Comment by Anil-KumarE** [comment]
```
<div id="wrapper2" class="round">
	<div id="content" class="round">
		<form id="theform">
			<label class='SectionTitle'  >New files</label>
			<br />
			<div class = 'rightcontent'>
				<div class='messageblock'>
					<div class='messagesubjectlabel'>
						<a href='HyperLink 1' target='_blank' title='Download all files'>Test File</a>
					</div>
					<div class='messageinfoblock'>
						From: email id 1
						<div class="dropdownTrigger dropdownArrow"  data-dropdown="#dropdown-99841f00-49d6-4dac-9395-af353c440e0e-waiting">
						</div>
					</div>
				</div>
			</div>					
			<label class='SectionTitle'  >Incomplete uploads</label>
			<br />
			<div class = 'rightcontent'>
				<div class='messageblock'>
					<div class='messagesubjectlabel'>
						<a href='Hyperlink 2' target='_blank' title='Upload all files'>Test Rest</a>
					</div>
					<div class='messageinfoblock'>
						To: email id 2
						<div class="dropdownTrigger dropdownArrow"  
						data-dropdown="#dropdown-57ce262b-6290-44d6-ae1f-1d8da4a93c7d-resumableUploads">
						</div>
					</div>
				</div>
			</div>					
          </form>        
        </div>
</div>
```

**Comment by aaltat** [comment]
Yes, that is not a Robot Framework test case which can be run by me.

**Comment by Anil-KumarE** [comment]
*** Variables ***
${FROM_MESSAGE_BLOCK}    //*[@id="theform"]/div/div/div[2]
${FROM_SENDER_EMAIL}    ${EMPTY}
${File_Subject}    //a[contains(text(),'Test File')]
${name}     ${EMPTY}

*** Keywords ***
Find a File
    #    @{texts}    get all texts    css=.name
    #    log many    ${texts}
    ${xpath}=    set variable    //div[@id='wrapper2']//div[@id='content']//form[@id='theform']//div[@class='messageblock']//div
    ${count}=    get matching xpath count    ${xpath}
    ${names}=    create list
    : FOR    ${i}    IN RANGE    1    ${count} + 1
    \    ${name}=    Sel.get text    xpath=(${xpath})[${i}]
    \    append to list    ${names}    ${name}
    \    run keyword if    ${name}==${FROM_SENDER_EMAIL}    Get the Element   exit for loop

Get the Element
    ${Element_Name}=    ${name}

*** Test Cases ***
Forwarding a Single File
                  Find a File


This is the complete code, the above comment is the piece of HTML code where i am trying to complete the Email ID from this page to what I pass in so that i can go inside and do the next steps

**Comment by aaltat** [comment]
And how do I run that test?

**Comment by aaltat** [comment]
Closing due inactivity.
