### ISSUE TITLE
No keyword with name 'NOTHING' found.

### ISSUE THREAD

**Issue by storenth** [robotframework/SeleniumLibrary#1299]
**Prerequisites**
I want disable of taking Screenshot when something failed! 

**Steps to reproduce the issue**
1. Clone the WebDemo or use your failed test cases
2. Look at http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Register%20Keyword%20To%20Run%20On%20Failure about NOTHING keyword
3. Disable _Run-on-failure functionality_ by changing resource.robot, add the KEYWORD:
```
...
*** Keywords ***
Register Keyword To Run On Failure
    NOTHING
...
```
4. Try run test case with:
```
...
*** Test Cases ***
Valid Login
    [Setup] Register Keyword To Run On Failure
...
```

CLI Error message:

`No keyword with the name 'NOTHING' found.`

**Expected behavior**:
When test case fails, no screenshot was taken.

**Actual behavior**:
Test failed with:
```
[17:22:08] storenth@storenth-MacBookAir:~/Documents/robot_demo/WebDemo$ pip3 list | grep robot
robotframework (3.1.1)
robotframework-seleniumlibrary (3.3.1)
[17:22:52] storenth@storenth-MacBookAir:~/Documents/robot_demo/WebDemo$ robot login_tests/gherkin_login.robot 
==============================================================================
Gherkin Login :: A test suite with a single Gherkin style test.               
==============================================================================
Valid Login                                                           | FAIL |
Setup failed:
**No keyword with name 'NOTHING' found.**
------------------------------------------------------------------------------
Gherkin Login :: A test suite with a single Gherkin style test.       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/storenth/Documents/robot_demo/WebDemo/output.xml
Log:     /home/storenth/Documents/robot_demo/WebDemo/log.html
Report:  /home/storenth/Documents/robot_demo/WebDemo/report.html
```
**Environment**:
robotframework (3.1.1)
robotframework-seleniumlibrary (3.3.1)
https://github.com/robotframework/WebDemo#running-demo

**Comment by aaltat** [comment]
From your example, it's not clear where the error actually happens. But if your test cases contains only those lines which you demonstrated in the snippets, then Robot Framework is correct to complain that it keyword `NOTHING` is not found. Please see the `Register Keyword To Run On Failure` keyword documentation  http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Register%20Keyword%20To%20Run%20On%20Failure how to use keyword correctly.

**Comment by storenth** [comment]
> From your example, it's not clear where the error actually happens. But if your test cases contains only those lines which you demonstrated in the snippets, then Robot Framework is correct to complain that it keyword `NOTHING` is not found. Please see the `Register Keyword To Run On Failure` keyword documentation http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Register%20Keyword%20To%20Run%20On%20Failure how to use keyword correctly.

Just clone the https://github.com/robotframework/WebDemo#running-demo and follow steps with 2 (TWO) code insertions

**Comment by aaltat** [comment]
See the Register Keyword To Run On Failure keyword documentation http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Register%20Keyword%20To%20Run%20On%20Failure how to use keyword correctly.

**Comment by aaltat** [comment]
Because this looks like an error using the `Register Keyword TO Run On Failure` keyword I am closing this issue. If you feel different, please send update and express why you feel differently.

**Comment by ombre42** [comment]
```
*** Keywords ***
Register Keyword To Run On Failure
    NOTHING
```
Couple of things wrong here. First this is creating a keyword that masks the SeleniumLibrary keyword. You should choose a different name. The other is that you are putting the argument on its own line. Robot thinks you are trying to call a keyword named NOTHING.

Your setup keyword should look more like:
```
*** Keywords ***
Setup On Failure
    Register Keyword To Run On Failure    NOTHING
```

**Comment by storenth** [comment]
> ```
> *** Keywords ***
> Register Keyword To Run On Failure
>     NOTHING
> ```
> Couple of things wrong here. First this is creating a keyword that masks the SeleniumLibrary keyword. You should choose a different name. The other is that you are putting the argument on its own line. Robot thinks you are trying to call a keyword named NOTHING.
> 
> Your setup keyword should look more like:
> 
> ```
> *** Keywords ***
> Setup On Failure
>     Register Keyword To Run On Failure    NOTHING
> ```

thanks a lot!
