### ISSUE TITLE
Add support event_firing_webdriver

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1303]
Selenium has an listener API which is called [event_firing_webdriver](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.event_firing_webdriver.html#module-selenium.webdriver.support.event_firing_webdriver). It allows many interesting features and could be useful example in https://github.com/Omenia/robotframework-seleniumtestability project. 

To implement this, three things are required from the SeleniumLibrary project
- Add argument, in library import, which takes in the `event_listener` class.
- Wrapping driver with [EventFiringWebDriver](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.event_firing_webdriver.html#selenium.webdriver.support.event_firing_webdriver.EventFiringWebDriver) and `event_listener` class.
- Wrapping WebElements with [EventFiringWebElement](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.event_firing_webdriver.html#selenium.webdriver.support.event_firing_webdriver.EventFiringWebElement) and `event_listener` class.

When #1292 is done, the functionality to import classes from string should be reused to import the  `event_listener` class. SeleniumLibrary will not perform checks on the `event_listener` class, although it must implement the [Selenium abstract_event_listener](https://seleniumhq.github.io/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.abstract_event_listener.html#module-selenium.webdriver.support.abstract_event_listener). 

In practice import should look like this: 
```
| Library | SeleniumLibrary | event_listener=MySeleniumEventListener |
```
Arguments could be supported, if underlying Selenium allows it, in similar way as in plugins. 

If `event_listener` is not defined or defaults to `False` wrapping drivers and WebElements should not be done.

**Comment by sebastianciupinski** [comment]
@aaltat - are there any plans for importing more than one event firing listeners?

**Comment by aaltat** [comment]
I do not know does Selenium support multiple listeners. But for time being what is your use case for supporting multiple listeners?
