### ISSUE TITLE
No way to pass profile preferences

### ISSUE THREAD

**Issue by bubenkoff** [robotframework/SeleniumLibrary#132]
To pin the language of the browser, i want something like this:
profile.setPreference( "intl.accept_languages", "no,en-us,en" );
please add special argument for profile preferences

**Comment by aaltat** [comment]
One can specify the language with Create Webdriver keyword, See example from here: https://groups.google.com/d/msg/robotframework-users/r3rxgSv1Cs0/rzzc1fmwEQAJ

Closing issue because this is now possible. Please open new issue if you feel that issue is still relevant
