### ISSUE TITLE
 	How to use regular expressions in Robot Framework?

### ISSUE THREAD

**Issue by shrutishrivastava** [robotframework/SeleniumLibrary#133]
I am using Robot Framework to create my testcases. I am using ride as a graphical user interface. I want to use regular expression in Robot Framework. Please share how to do it. It would be really beneficial if you can explain with the help of an example.

**Comment by zmlpjuran** [comment]
You do not write what you want to achieve with regular expression. Locate an element or just match the string? See String Library - Get Lines Matching Regexp keyword whether it suits for you: http://robotframework.googlecode.com/hg/doc/libraries/String.html?r=2.8.3#Get%20Lines%20Matching%20Regexp

**Comment by ombre42** [comment]
@zmlpjuran Thanks for helping.
@shrutishrivastava If you require further assistance, please use the [Robot Framework User Group](https://groups.google.com/forum/#!forum/robotframework-users).

**Comment by ohuohuo** [comment]
link is broken.

**Comment by aaltat** [comment]
Ugh

Closed issues are not kept up to date. What are you looking for?

-Tatu
Send from my mobile
