### ISSUE TITLE
Open Browser keyword could take in Selenium browser specific options

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1331]
Selenium has been enhanced to support browser specific options for Firefox, Chrome, IE, Edge and Opera for some time ago. Since SeleniumLibrary has raised the minimum required [Selenium version to 3.8.1](https://github.com/robotframework/SeleniumLibrary/issues/1305), the Selenium options API has been stable. Example for [Chrome WebDriver](https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.webdriver) there is [Chrome WebDriver Options](https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.chrome.options). Similar system exist for all the browsers mentioned in above.

Taking in the browser specific options in the [Open Browser](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Open%20Browser) keyword should not be hard. Example the keyword signature could look like this: 
```
| Open Browser | url | browser | alias | remote_url | desired_capabilities | ff_profile_dir | options |
```
The Selenium options is an Python class instance and not a dictionary. Each browser specofic options object has different set of methods and attributes. 

It was decided to enhance the `Open Browser` keyword to take in Selenium options by using `options` argument. The `options` argument should support two different formats: string and Python object which is Selenium options instance. Example of a string format: 
```
| Open Browser | url | browser | options=method('arg'); attr = 'value'; method('foo', True) |
```

This enhancement proposal is one step forward to unify the `Open Browser` and `Create WebDriver` keywords. See #701

**Comment by aaltat** [comment]
Usage cases for this enhancement is example a support Chrome [mobile emulation](http://chromedriver.chromium.org/mobile-emulation) or setting Firefox geckodirver `–log LEVEL`

**Comment by pekkaklarck** [comment]
Separate kws to create and modify options is a good general solution but also pretty annoying to use.

Would it be possible to specify options as a dict and then construct the actual option instance based on it? That would be a lot easier to use, especially if SL would allow passing the dict as a literal. Real option objects should obviously be supported as well , but special kws to construct them wouldn't be needed.

**Comment by aaltat** [comment]
It definitely would be possible, the only downside I see that if user wants to return a property value or method return value. Example it is possible to get default desired capabilities or convert options as capabilities and so on.

**Comment by pekkaklarck** [comment]
You cannot just create e.g. ChromeOptions with all info you want but instead need to create an instance and call various setters? Horrible API! Anyway, SL could go through the passed dict and call setters according. Not sure could this be done on generic manner or would all arguments need to be handled separately.

If it turns out separate kws for creating and modifying options are needed, I'd check could the existing `BuiltIn.Call Method` be used for the latter purpose.

Do all options need to be specified before WebDriver instances are created or can they still be modified after that? Would assume everything needs to be set before actually opening a browser.

**Comment by aaltat** [comment]
Yes, options needs to passed when the WebDriver is created.

But in any case, using a dictionary sounds better idea than my ones. Need to try out how it looks like, when I am with real PC and not with mobile.

**Comment by pekkaklarck** [comment]
With dicts supporting literals is convenient especially in simple cases. `ast.literal_eval` makes that easy. Or upgrading to RF 3.1 and using automatic type conversion.

**Comment by aaltat** [comment]
Did do some thinking and I think it should be a list of dictionaries. Because single setter can be called multiple times, example like: 
```
PROXY = "66.97.38.58:80"
url = "http://whatsmyip.org"
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--proxy-server=%s' % PROXY)
driver = webdriver.Chrome(chrome_options=chrome_options)
```
So it could be something like this:
```
[
    {'add_argument': ['--headless']},
    {'add_argument': ['--no-sandbox']},
    {'add_argument': ['--disable-dev-shm-usage']},
    {'add_argument': [f'--proxy-server={PROXY}']}, 
    {'add_argument': ['--disable-dev-shm-usage']}
]
```
And the if the above list of dictionaries is in `${add_argument}` variable, then usage could be something like this (Unfortunately dictionary value must be list, because the setter can have more than one argument, like in [add_experimental_option](https://selenium-python.readthedocs.io/api.html#selenium.webdriver.chrome.options.Options.add_experimental_option ). Using string syntax with some sort of separator might be also possible.) : 
```
| ${options} = Set Selenium Options | Chrome | ${add_argument} |
```
And  then `${options}` variable contains similar instance as in `chrome_options` the above Python code. The problem is creating list of dictionaries is hard in plain Robot Framework data. 
```
| ${add_argument} | Create List |
| ${list1} = | Create List | --headless |
| ${dict1} = | Create Dictionary | add_argument | ${list1} |
| Append To List | ${add_argument} | ${dict1} |
```
And that is the only the one option. It can be eased somewhat with the `FOR` loop syntax. But it still quite hard: 
```
| ${add_argument} | Create List |
| FOR | ${opt} | IN | --headless | --no-sandbox | --disable-dev-shm-usage | --proxy-server=66.97.38.58:80 | --disable-dev-shm-usage |
| | ${list} = | Create List | ${opt} |
| | ${dict} = | Create Dictionary | add_argument | ${list} |
| | Append To List | ${add_argument} | ${dict} |
| END |
```

But I agree with you and I am starting to hate the Selenium options interface even more. One is just passing command line arguments to the `ChromeDriver`.

**Comment by aaltat** [comment]
Also when reading Selenium code, I did notice that example Edge has options support. Need to add it to the first comment.

**Comment by aaltat** [comment]
There was an idea in the slack that instead of the having separate keyword for creating the SeleniumLibrary options, we could pass the the dictionary/string/option object directly to the `Open Browser` keyword. That sounds like a great idea.

**Comment by aaltat** [comment]
I was thinking the idea. I think it would be good to call the argument as `selenium_options`. The string presentation is pretty simple to define, methods (or attributes are separated by comma and method argument(s) are separated by colon. Example like this: `method_or_argument:arg1,method_or_argument:arg2,method_2:arg1:arg2`

Internally it converts it a list of dictionaries and call the method or attribute with the defined argument(s)

**Comment by aaltat** [comment]
The proposed string format `method_or_argument:arg1,method_or_argument:arg2,method_2:arg1:arg2` was not a good solution. Instead It was proposed to use `method('arg'); attr = 'value'; method('foo', True)`

I agree that the later format is better. Although there is some more work to write it and also parsing is not trivial the benefits are greater than those two downsides.

1. It is clear for the reader is user calling an attribute or a method.
2. There is a clear separation between Python booleans (Like True), numbers (although I haven't found an example where number would be needed) and strings.
3. This replaces the hard to make and read [{...}, {...}] format.
4. Documentation will hopefully be less confusing, because there is only one format to explain.
5. External objects should be supported, but that is trivial.
