### ISSUE TITLE
Enhance Open Browser keywords to support Selenium service_log_path argument

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1333]
On Selenium side Firefox, Chrome, IE and Opera support service_log_path argument. It allows to push driver logs to a file. This is useful in cases where there is errors example when starting new browser. In such case, the stack from Selenium side is not useful at all, but sometimes the driver logs returns something useful. It would be good to support `service_log_path` argument in open browser keyword. Example like this: 
```
| Open Browser | url | browser | service_log_path=${OUTPUTDIR}/driver.log |
```
This enhancement proposal is one step forward to unify the Open Browser and Create WebDriver keywords. See #701

**Comment by aaltat** [comment]
When `Open Browser` keyword is called multiple times, overwrite or appending to a same file are not very good options. Instead keyword should do same as `Capture Page Screenshot` and it's indexing counter. Instead this should be supported
`service_log_path=driver-{index}.log` and index would grow each time keyword gets called.

**Comment by pekkaklarck** [comment]
`service_log_path` isn't that clear name but using same name as underlying Selenium obviously has its benefits. Otherwise something like `driver_log` would be better.

**Comment by aaltat** [comment]
Does not work with Firefox browser. Needs fixing.
