### ISSUE TITLE
How do i do continuous integration with robot framework?

### ISSUE THREAD

**Issue by shrutishrivastava** [robotframework/SeleniumLibrary#134]
i am pretty new to the Robot Framework. I have robot framework installed on my local machine. I am able to create testscripts. Now i want to use a CI tool with Robot Framework. How do i do that? Please help.

**Comment by marekjs** [comment]
Use Jenkins. (http://jenkins-ci.org/)
There is Robot Famework plugin for Jenkins.

**Comment by ombre42** [comment]
There is even a [Robot Framework plugin for Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Robot+Framework+Plugin).
For more help, use the [Robot Framework user group](https://groups.google.com/forum/#!forum/robotframework-users).
