### ISSUE TITLE
'Select Window', 'Get Window Titles', "Get Window Names', and 'Get Window Identifiers' 

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#135]
None of these keywords work for me across 6 different machines.  They all simply hang, there is never a success or failure reported.  If the test execution is not stopped manually, python begins to become unresponsive after several minutes.  I have not been able to produce a log file with an error code so I honestly have no idea where the problem is occurring.  Please help

**Comment by emanlove** [comment]
This sounds very much like #10 which is really an issue with selenium version 2.25.0 (see http://code.google.com/p/selenium/issues/detail?id=4375). We have a [work-around](https://github.com/rtomac/robotframework-selenium2library/commit/0bf17bc8bcec8d6f17704e74d5a7341a43dc8d7a) implemented within Selenium2Library code which has not yet been released. It is a very simple change which you can implement in your code while we work to get 1.1 out the door. See

https://github.com/rtomac/robotframework-selenium2library/commit/0bf17bc8bcec8d6f17704e74d5a7341a43dc8d7a

**Comment by know1nos** [comment]
that worked great, thank you.  Any idea when 1.1 will be released?

**Comment by ksanand** [comment]
I tried the fix and got rid of the hanging problem. But seeing "Undefined" values for the window identifiers.  This is what I tired..
.......

Check Help  [Arguments]  ${link_str}
    Click On Links  ${link_str}
    Selenium2Library.Click Image  /images/help.gif
    @{handles}=  Selenium2Library.Get Window Identifiers
    :FOR  ${h}  IN @{handles}
    \  Switch To Window  $h
    \  ${title}=  Selenium2Library.Find Elements By Tag Name  title
........

Same result in Chrome and Firefox.  However Get Window Titles worked.

**Comment by ombre42** [comment]
Window identifiers (the id attribute) are not a built-in attribute as far
as I can tell, but it is popular due to the prevalence of jQuery. Windows
don't have ids unless the creator of the window specifically gives it one.

**Comment by ombre42** [comment]
From what I can tell this issue was fixed. Feel free to re-open if I am mistaken.

**Comment by Muddesir** [comment]
I am facing the same issue using :   

Error in RIDE:
20161231 12:51:17.692 :  FAIL : 
NoSuchWindowException: Message: Unable to get browser

20161231 12:51:17.694 :  WARN : 
Keyword 'Capture Page Screenshot' could not be run on failure: NoSuchWindowException: Message: Unable to get browser

20161231 12:51:17.908 :  FAIL : 
NoSuchWindowException: Message: Unable to get browser

Ending test:   CommandCenterExample.VAG Command

![version](https://cloud.githubusercontent.com/assets/24763195/21577162/e28f9178-cf76-11e6-8138-d148325b0e39.PNG)

**Comment by aaltat** [comment]
Most likely it is not same problem. Could you open a new issue and run the test with `--loglevel trace`. Also could you tell which browser version you are using.
