### ISSUE TITLE
Not able to install selenium2library to work with robotframework

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [robotframework/SeleniumLibrary#1351]
Hi, I am getting the below error while downloading selenium2library. I tried with both python 2 and python 3 and get the same error:
Could not find a version that satisfies the requirement selenium2library (from versions: )
No matching distribution found for selenium2library.

Please provide me the solution.

**Comment by aaltat** [comment]
Could you show the command that you did give? Also seeing the full console output is useful too.

Please note that Selenium2Library is deprecated and all future development happens in SeleniumLibrary. Therefore it would be best to switch using SeleniumLibrary instead of the Selenium2Library.

**Comment by Ishrat-Manzoor** [comment]
![image](https://user-images.githubusercontent.com/24873115/54863121-8bde8900-4d6a-11e9-8132-c26ffe2697bb.png)

Still if i try to add seleniumlibrary or selenium2library in ride, it turns red

**Comment by aaltat** [comment]
There is not error in the console output and output says that everything is installed.

Can you run simple test case from command line and see does it work?

**Comment by Ishrat-Manzoor** [comment]
Actually i have both python 2 and 3 installed, i have set python 3 in environment variables and did whole robotframework installation on it. But while opening ride, it is showing python 27, so i am not able to import selenium library.
![image](https://user-images.githubusercontent.com/24873115/54863294-e7aa1180-4d6c-11e9-894b-973f761d087c.png)
what needs to be done now? 

![2019-03-23](https://user-images.githubusercontent.com/24873115/54863316-1e802780-4d6d-11e9-9f9e-edc393f9c57e.png)

**Comment by aaltat** [comment]
RIDE problem is not my problem. RIDE issues must be reported to the RIDE project issue tracker.

From the first screen capture I can see that, you have installed Selenium2Library to Python 3. Can you run simple test case, with Python 3 and from command line and see does it work?

**Comment by aaltat** [comment]
Because you opened a new issue, I am assuming that this is not anymore an problem. Therefore I am going to close this issue.
