### ISSUE TITLE
I can't import selenium2library or seleniumlibrary in Ride 

### ISSUE THREAD

**Issue by Ishrat-Manzoor** [robotframework/SeleniumLibrary#1359]
![image](https://user-images.githubusercontent.com/24873115/54918340-fc7cd580-4f23-11e9-892b-9b8291a7c9dc.png)
![image](https://user-images.githubusercontent.com/24873115/54918373-13bbc300-4f24-11e9-9399-cdba3322150f.png)

**Comment by aaltat** [comment]
1) For the RIDE, I don't provide support, you need to contact for the RIDE project https://github.com/robotframework/RIDE and look in to their project how support works. 
But if you can provide example, which proves same error in pure Robot Framework data and command line example, then I am interested.

2) As in Robot Framework, also in Python you need to import (other than built-in methods and statements) method or classes you are going to use. In your above example:
```
>>> import SeleniumLibrary
>>> SeleniumLibrary.SeleniumLibrary()
```
Should fix your example.

For more details about Python import system, please refer to the Python documentation https://docs.python.org/3/reference/import.html

**Comment by aaltat** [comment]
I am assuming that this is not anymore valid and therefore I am closing this issue.
