### ISSUE TITLE
Scroll Element Into View does not always scroll element into view

### ISSUE THREAD

**Issue by mytzenka** [robotframework/SeleniumLibrary#1369]
In this screen you can see a set or radio buttons, highlighted in red
![image](https://user-images.githubusercontent.com/39919027/56208321-2de34f80-6051-11e9-8eea-91e8154031e7.png)
When these buttons are in view (top screenshot) I can click on them fine.
However if they are not visible, because they are below the banner (bottom screenshot, highlighted in blue) I can't click on them because then I get an error like:
"Element is not clickable at point (111, 700). Other element would receive the click"

I tried to solve this by using keyword `scroll element into view`. However in this case it doesn't work. The keyword reports `PASSED` but the element is not scrolled into view and I still get the error.

My suspicion is that the problem is that the radio button I want to click is still behind the banner highlighted in blue, even after `scroll element into view` passes.

How do get this element to actually scroll into view?

**Comment by aaltat** [comment]
Interesting problem, the keyword relies purely on Selenium API. Does this problem happen with Chrome and have you tried other browsers? Also is your Selenium, browser driver and browser compatible with each other, example Chrome is pretty strict on the matter now days.

**Comment by bjanzen** [comment]
When I run into this, I write a Keyword with a little python and use ActionChains to get the location and just click there anyway, and in all my cases so far, it works.  e.g. ActionChains(driver).move_to_element(x).click().perform()

**Comment by aaltat** [comment]
Is this still a problem? If this is still a problem, could you answer to the questions in my previous post?

**Comment by mytzenka** [comment]
> Is this still a problem? If this is still a problem, could you answer to the questions in my previous post?

Yes this is still a problem and our drivers are up to date.
We haven't been able to test on another browser yet. Our application doesn't work correctly in Internet Explorer. The only other option we can try is Edge. Will let you know how that goes.

**Comment by mytzenka** [comment]
This also doesn't work correcly in Edge.
We do have a workaround, but it would be nice if the keyword 'scroll into view' would actually scroll into view, if at all possible.
But like you said, this is probably an issue in Selenium itself and not SeleniumLibrary?

**Comment by aaltat** [comment]
The keyword implementation is in here: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L668 It uses Selenium API to scroll element in to view. To report the issue to the Selenium project, Python script (using only Selenium API) and example webpage should be provided to the Selenium project issue tracker.

Is your website publicly available? If it's not, are those, elements in the blue rectangular elements that do not scroll, like a always visible menu bar?

**Comment by mytzenka** [comment]
> Is your website publicly available? If it's not, are those, elements in the blue rectangular elements that do not scroll, like a always visible menu bar?

Indeed this website is not publicly available. Yes, the blue rectangle is fixed so the element that I want to have in view is scrolling behind it.

**Comment by aaltat** [comment]
I can reproduce the problem, my test page is based on this: https://www.w3schools.com/css/tryit.asp?filename=trycss_navbar_horizontal_black_fixed2 
The `Scroll Element Into View` keyword only scrolls the element to the edge of the browser window. If there is those floating type of elements, Selenium does not scroll the element enough to be in view. I can produce the problem also in pure Selenium code. Also problem can be reproduced with many browsers, like Chrome and Firefox. I feel that the problem in lies in the Selenium or in the  browser driver implementation side. I raised an issue the Selenium issue tracker: https://github.com/SeleniumHQ/selenium/issues/7159

**Comment by aaltat** [comment]
Selenium project responded. They say that it's  based in each browser vendors implementation, which again is based on the WebDriver specification. I agree with you that the WebDriver specification is not perfect, but I am not going to drive this forward anymore in the external projects. 

Also in the SeleniumLibrary project, I am not going to change the implementation, because I can not see an easy solution which would be universally compatible. But that doesn't not prevent you or other providing a PR which would solve the problem.

**Comment by mytzenka** [comment]
> I am not going to drive this forward anymore in the external projects.
Also in the SeleniumLibrary project, I am not going to change the implementation, because I can not see an easy solution which would be universally compatible

I understand that of course. I will have to think about what I want to do about this.
Thanks a lot for your help so far!

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by avimehenwal** [comment]
> When I run into this, I write a Keyword with a little python and use ActionChains to get the location and just click there anyway, and in all my cases so far, it works. e.g. ActionChains(driver).move_to_element(x).click().perform()

Hey @bjanzen  , would it be possible to share a snippet/ gist? on how to do it!
I am also trying todo something similar and my python skills are not that good

**Comment by aaltat** [comment]
Have you looked at the Selenium testability plugin, it should have a keyword for this which works on JavaScript.

**Comment by avimehenwal** [comment]
> The keyword implementation is in here: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L668 It uses Selenium API to scroll element in to view. To report the issue to the Selenium project, Python script (using only Selenium API) and example webpage should be provided to the Selenium project issue tracker.
> 
> Is your website publicly available? If it's not, are those, elements in the blue rectangular elements that do not scroll, like a always visible menu bar?

Updated link > https://github.com/robotframework/SeleniumLibrary/blob/4fc4088a90ddac0511746d1693bd684ccd635c37/src/SeleniumLibrary/keywords/element.py#L684
