### ISSUE TITLE
'Element Should Contain' looks for exact string matches

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#138]
'Element Should Contain' looks for exact string matches when it should be looking for the string to contain the substring instead

**Comment by ombre42** [comment]
Can you provide a page and test to reproduce this? It appears to match substrings, but it is case-sensitive. It also appears to work with unicode characters.
This passes:
    Open Browser    http://code.google.com/p/robotframework/
    Element Should Contain    xpath=id('mt')/a    roject

**Comment by ombre42** [comment]
Submitter did not respond and no one else is reporting this issue
