### ISSUE TITLE
Increment required selenium version to 2.12

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#140]
With the change to using Selenium's Select class we need to increment the minimum selenium version required by Selenium2Library to 'selenium >= 2.12' whuich is the Selenium version which introduced this support code.

**Comment by rtomac** [comment]
This should happen _along with_ the 1.1 release, correct Ed?

**Comment by emanlove** [comment]
Yeah, it should. Making the change now and should be merged in shortly.

**Comment by rtomac** [comment]
Great, thanks.

**Comment by emanlove** [comment]
Done.
