### ISSUE TITLE
Drop Python 3.4 support in SeleniumLibrary 4.1

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1409]
Python 3.4 is [end of life](https://www.python.org/dev/peps/pep-0429/) and we should remove support for it. Mainly this mean that we update Travis to test with Python 3.5. Inform community also about the decision.

**Comment by hugovk** [comment]
Please see PR https://github.com/robotframework/SeleniumLibrary/pull/1466.
