### ISSUE TITLE
Add better documentation support for plugins

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1430]
Currently only plugin keywords are [documented](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#generating-keyword-documentation) It would be useful feature to append plugin documentation also from plugins class level to the SeleniumLibrary documentation.

**Comment by aaltat** [comment]
Add `Installed plugins` in the table of contents. Add also the same chapter in the class level documentation and by default add text: ` No installed plugins.`

If plugins are installed, remove the last line and add plugin class name as level two heading and append the class documentation in to the SeleniumLibrary documentation. Do same for each plugin. Something like this: 
```
= Installed Plugins =
== MyPlugin ==

Documentation goes here

== AnotherPlugin ==

Another doc here
```

For plugins adding documentation from `__init__` is not supported in this release. But that can be later changed, if there is a need.

**Comment by pekkaklarck** [comment]
I'd do that slightly differently. I don't like the `Installed Plugins` top level section too much in general and especially don't like showing it when no plugins are installed. Instead I'd make separate top-level section for each plugin so that the header is in format `Plugin: My Cool Plugin`. I'd also inject them to the TOC to make  all plugins immediately visible.

**Comment by aaltat** [comment]
So it should look something like this in the ToC:
```
    - `Locating elements`
    - `Browser and Window`
    - `Timeouts, waits and delays`
    - `Run-on-failure functionality`
    - `Boolean arguments`
    - `EventFiringWebDriver`
    - `Thread support`
    - `Plugins`
    - `Plugin: My Cool Plugin`
    - `Plugin: Other Plugin`
    - `Importing`
    - `Shortcuts`
    - `Keywords`
```
And would append plugin docs, like this in the end:
```
...
documentation for further details.

Plugin API is new SeleniumLibrary 4.0

= Plugin: My Cool Plugin =

Documentation goes here

= Plugin: Other Plugin =

Another doc here
```

**Comment by pekkaklarck** [comment]
Yeah. Would uust move that "Plugins" sections to be the last so that installed plugins are after that. Installed plugins could also be its subsections, but having them on top level and on TOC feels a bit better for me.

**Comment by aaltat** [comment]
Updated the example in above. But feels much better plan, also it better reflects that plugin discovery is done as last (actually keywords are discover as last, but close enough).

**Comment by aaltat** [comment]
I had hard time to decide what would be best way to get `__intro__` doc from the plugins. 
1) Save each plugin doc in class instance
2) Recreate plugin instances when `def get_keyword_documentation(self, name):` is called
3) Save plugin instances in a list and yield docs 

I did went with [solution three](https://github.com/robotframework/SeleniumLibrary/pull/1433/files#diff-40c471e982a520769c6721ee04a812cdR470) but I am not sure was it a best solution or would some other solution be better. Any ideas?

**Comment by pekkaklarck** [comment]
Storing references to plugins looks good to me. SL already has access to library components, though, but I'm not sure is there any easy way to check which of them are plugins. If there is, then that could work.

The logic to attaching plugin docs to original docs could probably be simplified a bit. There could be, for example, a marker in the original toc that's replaced with plugin toc entries, and actual plugin docs could be just added to the end with `+`. That marker should then obviously be removed if there are now plugins. Regardless the approach, doc constructing logic should be moved to a helper method.

**Comment by aaltat** [comment]
Yes, marker could simply the code. Thanks for the pointer.

**Comment by pekkaklarck** [comment]
Even better ideas:
- Generate the whole toc automatically. First add plugin docs and then parse the doc to find headers. Add marker like `%TOC%` to the doc and replace it with the generated toc.

- Submit an issue to Libdoc to support generating toc automatically.

**Comment by aaltat** [comment]
Later idea is great :-) Maintaining toc is somewhat extra work which should be automated. Well, I most likely have time to spend on this later, so let's see what comes out.

**Comment by pekkaklarck** [comment]
We can add toc generation to Libdoc in RF 3.2. Not sure can SL 4 have it as a dependency for plugin writers when we don't have even an alpha out yet, though. Perhaps it could first be implemented in SL and then ported to Libdoc?

**Comment by aaltat** [comment]
Not a bad idea. I can put it in a separate module so that it's easier to port.

**Comment by pekkaklarck** [comment]
Helper method is probably enough. Experimenting with the design/functionality is more important than code.

**Comment by aaltat** [comment]
Well, made the automatic [toc generation](https://github.com/robotframework/SeleniumLibrary/pull/1433/files#diff-40c471e982a520769c6721ee04a812cdR499). I ended up with a solution which uses regex. I think this is better than the first attempt.
