### ISSUE TITLE
"Table Header Should Contain" might get <th> elements from footer

### ISSUE THREAD

**Issue by php-coder** [robotframework/SeleniumLibrary#1437]
`Table Header Should Contain` keyword is looking for `<th>` elements everywhere in a table:

https://github.com/robotframework/SeleniumLibrary/blob/44a41f0a8ce719c928cd9d7fe7b33b3998006ee3/src/SeleniumLibrary/keywords/tableelement.py#L199-L200

Given that [`<th>` tag can be enclosed within `<tfoot>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/tfoot), it doesn't seem right to treat it as a header.

It seems like a bug.

**Comment by aaltat** [comment]
Interesting, would it possible to get static HTML page and simple test case that demonstrates the problem?

**Comment by php-coder** [comment]
Thank you for the fast reply!
Yes, sure I'll prepare test cases on weekend.

**Comment by aaltat** [comment]
Would you have an update to the case?

**Comment by php-coder** [comment]
I'm sorry I wasn't able to find time for that :-( Ok, probably, I won't provide it then.

**Comment by aaltat** [comment]
I do not have time investigate this in the near future. Therefore I am closing this issue. If you @php-coder want to return in the issue, please reopen the issue.
