### ISSUE TITLE
Submit Form keyword doesn't submit the form

### ISSUE THREAD

**Issue by finspin** [robotframework/SeleniumLibrary#144]
Selenium2Library 1.1.0
Robot Framework 2.7.5 (Python 2.7.3 on linux2)
Browser: Firefox 16.0.2

When I run keyword 'Submit Form   id=ingr-form' where ingr-form is the id of the form element, RF reports the keyword as passed but the form is not submitted.

When I instead use keyword 'Click Button        name=ingrForm' to submit the form, the form is successfully submitted.

Here is the form's HTML code:

``` html
<form id="ingr-form" method="post" action="/">
    <p>
        <label for="id_ingr-name">Name:</label> <input type="text" maxlength="30" name="ingr-name" id="id_ingr-name">
    </p>
    <p>
        <label for="id_ingr-category">Category:</label> 
        <select id="id_ingr-category" name="ingr-category">
            <option selected="selected" value="">---------</option>
            <option value="1">Value 1</option>
            <option value="2">Value 2</option>
        </select></p>
    <input type="submit" value="Save" name="ingrForm">
</form>
```

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closing due inactivity.
