### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1444]
Things to do:

- [x] Start support branch from latest release version and configure Travis to run it.
- [x] Clean CI so that it runs only with Python 3
- [x] Update Travis image to bionic
- [x] Clean unit tests that skip tests with Jython
- [x] Read code and see can something be improved. At least remove all PY2 and PY3 imports.
- [x] Take a peek in the acceptance test and is there something because of Python 2

By bye Python 2, it was a fun ride and welcome the new king Python 3: https://www.python.org/doc/sunset-python-2/

**Comment by hugovk** [comment]
Please see PR https://github.com/robotframework/SeleniumLibrary/pull/1466.

**Comment by aaltat** [comment]
In the Selenium side, there is some discussion about dropping Python 2 https://github.com/SeleniumHQ/selenium/issues/7462

**Comment by aaltat** [comment]
Clean up also documentation, [atest/README.rst](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/README.rst) and run.py files from Python 2 examples.

**Comment by aaltat** [comment]
#1589 only partially fixes the issue, reopening.

**Comment by aaltat** [comment]
Python 2 support is dropped at SL 5.0

**Comment by aaltat** [comment]
Only partial fix

**Comment by aaltat** [comment]
Done in above PR. Closing. 

Bye bye Python 2.
