### ISSUE TITLE
Select from list doesn't select correct item

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#145]
tried using two different options, including value... will not select the proper item.... have not seen anything like this before on any of my other webpage testing.  When trying to select via the list value it appears to simply select a country at random.  I have also noted that the input text keywords have not been completing the text input.  Is there some setting that may need to be changed on my end to ensure that the keywords complete their execution before moving on to the next one?  I am remoting into my office today, that is the only difference i can think of, though I don't believe that should be causing these issues.  Any input would be appreciated.

**Comment by emanlove** [comment]
@know1nos Can you provide some more information?

**Comment by know1nos** [comment]
Has not been occurring with 1.1 update

**Comment by emanlove** [comment]
Reopen this ticket if it reappears.
