### ISSUE TITLE
Failed to import SeleniumLibrary

### ISSUE THREAD

**Issue by ShuratCode** [robotframework/SeleniumLibrary#1453]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

I installed the SeleniumLibrary for robot framework but when I am trying to import the library I got this message:

('FAILED', u'SeleniumLibrary', DataError(u'Importing test library \'SeleniumLibrary\' failed: ImportError: cannot import name is_string\nTraceback (most recent call last):\n  File "c:\\python27\\lib\\site-packages\\robotide\\lib\\robot\\utils\\importer.py", line 153, in _import\n    return __import__(name, fromlist=fromlist)\n  File "c:\\python27\\lib\\site-packages\\SeleniumLibrary\\__init__.py", line 25, in <module>\n    from SeleniumLibrary.base import DynamicCore, LibraryComponent\n  File "c:\\python27\\lib\\site-packages\\SeleniumLibrary\\base\\__init__.py", line 17, in <module>\n    from .context import ContextAware\n  File "c:\\python27\\lib\\site-packages\\SeleniumLibrary\\base\\context.py", line 17, in <module>\n    from SeleniumLibrary.utils import escape_xpath_value\n  File "c:\\python27\\lib\\site-packages\\SeleniumLibrary\\utils\\__init__.py", line 20, in <module>\n    from .types import is_falsy, is_noney, is_string, is_truthy, PY3\n  File "c:\\python27\\lib\\site-packages\\SeleniumLibrary\\utils\\types.py", line 22, in <module>\n    from robot.utils import is_string\nPYTHONPATH:\n  c:\\python27\\lib\\site-packages\\robot\\libraries\n  c:\\python27\\lib\\site-packages\n  C:\\Python27\\Scripts\n  C:\\WINDOWS\\SYSTEM32\\python27.zip\n  c:\\python27\\DLLs\n  c:\\python27\\lib\n  c:\\python27\\lib\\plat-win\n  c:\\python27\\lib\\lib-tk\n  c:\\python27\n  c:\\python27\\lib\\site-packages\\win32\n  c:\\python27\\lib\\site-packages\\win32\\lib\n  c:\\python27\\lib\\site-packages\\Pythonwin\n  c:\\python27\\lib\\site-packages\\wx-2.8-msw-unicode\n  c:\\python27\\lib\\site-packages\\robotide\\spec\n  c:\\python27\\lib\\site-packages\\robotide\\lib\n  c:\\python27\\lib\\site-packages\\robotide\\contrib\\testrunner\\../../lib\n  .\n  C:\\WINDOWS\\system32\n  c:\\python27\\lib\\site-packages\\robotide\\contrib\\testrunner\\../../lib',))

**Comment by HelioGuilherme66** [comment]
@genius8901 You did not fill the Issue template info. This should be a rejected Issue.

Your problem is with RIDE version. If you run your test from command window, those errors should not appear.

**Comment by ShuratCode** [comment]
Thank you
