### ISSUE TITLE
Alternate method for ._current_browser() in seleniumLibrary  

### ISSUE THREAD

**Issue by Anandh1924** [robotframework/SeleniumLibrary#1456]
AttributeError: 'Selenium2Library' object has no attribute '_current_browser' , Can I know how to pass current running browser instance to custom key.

**Comment by aaltat** [comment]
Most of the Selenium2Library private API was deprecated in the SeleniumLibrary 3.0 and it was removed in SeleniumLibrary 4.0. In the SeleniumLibrary 3.0 release a [public API](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#public-api) was created and currently active browser can be found from `driver` attribute.

**Comment by Anandh1924** [comment]
Thanks below is code in custom class

def get_bv_prepare():
        from selenium.webdriver.common.action_chains import ActionChains
        selenium2lib = BuiltIn().get_library_instance('Selenium2Library')
        driver = selenium2lib._current_browser()
can i know how to get current active browser from driver attribute .

**Comment by aaltat** [comment]
Change ` driver = selenium2lib._current_browser()` to ` driver = selenium2lib.driver`.

**Comment by Anandh1924** [comment]
Thanks

**Comment by aaltat** [comment]
The SeleniumLibrary 4.0 has many new features for people that are extending library, example the plugin API would be good to read https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#plugins

**Comment by aaltat** [comment]
Darn that comment reopen button are too close.
