### ISSUE TITLE
Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name 'PY3' from 'robot.utils'

### ISSUE THREAD

**Issue by collonville-tom** [robotframework/SeleniumLibrary#1457]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

```
pyrf -m robot tests.robot 
[ ERROR ] Error in file '/home/xxxxxxxx/dev/xxxx-git/xxxx-rf/tests.robot': Importing test library 'SeleniumLibrary' failed: ImportError: cannot import name 'PY3' from 'robot.utils' (/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/robot/utils/__init__.py)
Traceback (most recent call last):
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/robot/utils/importer.py", line 145, in _import
    return __import__(name, fromlist=fromlist)
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/SeleniumLibrary/__init__.py", line 25, in <module>
    from SeleniumLibrary.base import DynamicCore, LibraryComponent
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/SeleniumLibrary/base/__init__.py", line 17, in <module>
    from .context import ContextAware
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/SeleniumLibrary/base/context.py", line 17, in <module>
    from SeleniumLibrary.utils import escape_xpath_value
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/SeleniumLibrary/utils/__init__.py", line 20, in <module>
    from .types import is_falsy, is_noney, is_string, is_truthy, PY3
  File "/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/SeleniumLibrary/utils/types.py", line 23, in <module>
    from robot.utils import PY3
PYTHONPATH:
  /home/xxxxxxxx/dev/xxxx-git/xxxx-rf
  /usr/lib/python37.zip
  /usr/lib/python3.7
  /usr/lib/python3.7/lib-dynload
  /home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages
==============================================================================
Tests :: Example using the space separated plain text format.                 
==============================================================================
My Test :: Example test                                               | PASS | (basic RF test)
------------------------------------------------------------------------------
Another Test                                                          | PASS | (idem)
------------------------------------------------------------------------------
Valid Login                                                           | FAIL | (Selenium test)
No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.
------------------------------------------------------------------------------
Tests :: Example using the space separated plain text format.         | FAIL |
3 critical tests, 2 passed, 1 failed
3 tests total, 2 passed, 1 failed
```

## Expected behavior and actual behavior

When I run test.robot exemple i have a stack trace that PY3 package not found following a merge into the commit 2f48d14315f90189 realized in 5 Dec 2018 

I have that following stack trace

I was expecting that the .robot script works like the  3.3.1

## Environment

Python 3.7.3

$piprf list
Package                        Version  
------------------------------ ---------
appdirs                        1.4.3    
beautifulsoup4                 4.8.0    
certifi                        2019.9.11
chardet                        3.0.4    
future                         0.17.1   
idna                           2.8      
pip                            19.2.3   
pkg-resources                  0.0.0    
py                             1.8.0    
requests                       2.22.0   
robotframework                 3.1.2    
robotframework-imaplibrary     0.3.0    
robotframework-python3         2.9      
robotframework-seleniumlibrary 4.0.0    
selenium                       3.141.0  
setuptools                     39.0.1   
six                            1.12.0   
soupsieve                      1.9.3    
tqdm                           4.36.1   
urllib3                        1.25.6   
webdrivermanager               0.7.4    
wheel                          0.33.6   

Browser: Chrome / firefox

**Comment by aaltat** [comment]
Hmmm, I have locally the same version, also the CI runs with same version and it works without a problem. I would assume that the interpreter you use to run the test has older Robot Framework version installed.

**Comment by collonville-tom** [comment]
it's a fresh reinstall of robotframework package with its  library that we need.
i test it from scratch on a standalone installation in a virtenv environemnt and it fail. and to verify it i run also it in a docker file and i have the same error. 

you think that the python version is too old? it's 3.7.3 just under the last 3.7.4, and i prefer use the LTS version.

i install python/robotframework/selinium from apt-get update && apt-get upgrade before the apt-get install python3.7 && etc...

From what package/library the PY3 package come from?

**Comment by aaltat** [comment]
SeleniumLibrary imports [PY3 here](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/utils/types.py). And `robot.utils` import is the [init](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/__init__.py#L55) and it is defined in [platform](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/platform.py#L30).  It is not about your Python version, it is about the version of Robot Framework you have installed in the interpreter you are using to run your test.  `PY3` has been in Robot Framework since Robot Framework 3.0 release, but it was not in the [2.9 release](https://github.com/robotframework/robotframework/blob/2.9.2/src/robot/utils/platform.py). 

If you look at your Robot Framework installation, in `/home/xxxxxxxx/dev/tools/py-rf/lib/python3.7/site-packages/robot/utils/__init__.py` based on the first post, it does not contain line which would import [PY3](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/__init__.py#L56). But it would be nice to what version Robot Framework you are using, and it should be in `https://github.com/robotframework/robotframework/blob/master/src/robot/version.py`.

**Comment by aaltat** [comment]
Because this is turning more of a support requests for debugging environment issue, I am closing this issue. If you need more support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
