### ISSUE TITLE
Ctrl+B shortcuts key does not work python3 

### ISSUE THREAD

**Issue by mecanda12** [robotframework/SeleniumLibrary#1458]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment]
It's impossible to help you with only at the information in the title. You should actually read the the prefilled text and answer to the questions in the text.

**Comment by mecanda12** [comment]
Ctrl+B shortcuts key does not work python 3 with robot-framework-selenium library 4.0.0.
Mostly CTRL+B used to see the custom code or keyword to explore. It is used to work in previous version 3.3.1 but not in current version.

**Comment by aaltat** [comment]
I don't understand at all what you are trying to say.

Please provide context in your explanation. What you are trying to do, where you are trying to do it, tests examples, error message. Remember that I don't see your screen on know anything about your environment. Explain the problem as for a blind person.

**Comment by mecanda12** [comment]
![image](https://user-images.githubusercontent.com/32083604/65725598-10df8d80-e081-11e9-8e2b-3a7dd9e90485.png)

**Comment by mecanda12** [comment]
I upload the picture above.  write any keyword from robot-framework-selenium library 4.0.0.
example:  open browser --> bring the cursor on top --> press CTRL+B 
expected : It will take you to actual python code, but it is not working in current version and used to work in previous version.  

I attached another screen short here. what is expected result. 


![image](https://user-images.githubusercontent.com/32083604/65725870-9feca580-e081-11e9-97ed-ae811e760481.png)

**Comment by humbienri** [comment]
I am confused.  Crtl+B would be an IDE thing, not a SeleniumLibrary thing.  It might be that you are using PyCharm? Or RED, or Visual Studio Code, whatever IDE you are working with.  But it's not a RobotFramework thing/setting at all.

**Comment by mecanda12** [comment]
But how come work in 3.3.1 version if PyCharm issue? It is same version of Pycharm,

**Comment by humbienri** [comment]
It might be that your "Intellibot" or "Intellibot Patched for SeleniumLibrary" plugin is no longer useful for the "dynamic" nature of SeleniumLibrary.  I've had lot of trouble with those plugins for RobotFramework b/c they are outdated.

**Comment by mecanda12** [comment]
How can I run robot framework without plugin? What do you recommend how to use selenium in robot?

**Comment by humbienri** [comment]
Well, you could try running it from the commandline. Proven way to do it!

There are other plugins available for PyCharm to make it "point & click" easy to run a single test case or a suite/whole file of test cases.  Just go to Plugins and do a search for "robot".  I think that depending on what version of PyCharm you are using, you might have better plugins available to install.  But these are for executing RF tests/test suites.

To actually develop/implement the test cases, I think there was one that I remember seeing authored by a "Valerio" person.  I don't use it 'cause I have an older version of PyCharm but I also don't use PyCharm much for RF tests. A lot of people seem to like using RIDE for authoring RF tests.

**Comment by mecanda12** [comment]
Ride does not work anymore.

**Comment by aaltat** [comment]
SeleniumLibrary has not changed the library API between 3.0 and 4.0 releases. You need to consult your IDE or IDE plugin project what is wrong in their side. SeleniumLibrary project does not provide support for various IDE or IDE plugins. Therefore I am closing this issue.

**Comment by mecanda12** [comment]
Thanks for explanation. I do have little concern if library API did not change why CTRL + B not work new version? End of the day same version of API and same robot framework and same IDE + Plugin. 
If I install Old version  CTRL + B function work. Do not you think this is version issue?

**Comment by aaltat** [comment]
I don't have any idea how the plugin you are using is parsing keywords out of libraries. The only thing that is guaranteed by the SeleniumLibrary that it obeys the Robot Framework [dynamic library API](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dynamic-library-api). Therefore project does not test are IDE or IDE plugins compatible with the dynamic library API, it's something that IDE projects should care about.

But your question is actually quite important, because Robot Framework ecosystem is missing good support for different IDE. But that is not this project goal, although we share the worry. If you want better IDE support, please example contribute language server project.

**Comment by mecanda12** [comment]
Thanks for above information. May I know how did you test selenium library with robot framework? What kind Plugin you use? 

I can explain how I use robot framework with selenium. Step are given below 👍 
1. pycharm community latest version 
2. Python 3 latest version 
3. open pycharm and set up project with python interpreter 
4. Install plugin " IntelliBot @SeleniumLibrary Patched" 
5. install selenium 3.141 and robot framework selenium library 3.3.1 
6. write any keyword from selenium library example " click element"
7. bring the cursor on keyword, you will notice keyword get highlight. Press CTRL + B. You will notice actual python code will show. 

Note : if all above step get 100% success then please update to latest version selenium and robot framework selenium library. Please follow 6 & 7 step again. Hope you will see the difference between both version :)
Thanks

**Comment by aaltat** [comment]
I use PyCharm but I don't use Robot Framework specific plugins. 

For testing project uses Travis as a CI, for more details see https://github.com/robotframework/SeleniumLibrary/blob/master/atest/README.rst

As I said before, this project is not going to test against IDE or other editors. Raise an issue in your IDE project issue tracker.
