### ISSUE TITLE
Update Open Browser keyword documentation to better demonstrate how to use Selenium options

### ISSUE THREAD

**Issue by JonKoser** [robotframework/SeleniumLibrary#1461]
Selenium options is quite complicated system and it seems that Open Browser keyword documentation could be enhanced to better demonstrate how Selenium options can be used. Use real example with Chromium based app.

**Comment by JonKoser** [comment]
Re-opening issue as discussed in PR#1460 (now closed) comments. 

`Open Browser` by itself actually works quite well for Chromium-based apps. However, the documentation for that usecase could be significantly improved. Providing examples of how to use options to pass a binary location and remote debugging port would be quite helpful.

**Comment by JonKoser** [comment]
Re-opening issue as discussed in PR#1460 (now closed) comments. 

`Open Browser` by itself actually works quite well for Chromium-based apps. However, the documentation for that usecase could be significantly improved. Providing examples of how to use options to pass a binary location and remote debugging port would be quite helpful.

**Comment by aaltat** [comment]
Done in #1471
