### ISSUE TITLE
Open Browser keyword and Selenium options with Windows path needs double escaping

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1473]
If there is a need to do add windows path by using `Open Browser` keywords `options` argument, then windows path needs double escaping. Example: 
```
| Open Browser | url | firefox | options=add_argument("-profile"); add_argument("C:\\\\path\\to\\\\profile")
```
This is both untested and not documented. Write few tests and improve the documentation.

**Comment by pekkaklarck** [comment]
This is a bit unfortunate. Is the reason that the code is eval'ed at some point? If the issue cannot be fixed, mentioning the raw-string syntax like `r'c:\\foo\\bar'` might be a good idea.

**Comment by aaltat** [comment]
Yes, eval is in here https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py#L432 It's done to ensure that string `True` in the argument is converted to Python `True`. And raw string is good idea too.

**Comment by pekkaklarck** [comment]
SL could also replace `\` with `\\` before that. Would need to very carefully think are there possible downsides with that, though.

**Comment by aaltat** [comment]
Replacing automatically `\` with `\\` feels little bit too magical. I think testing, documenting and providing example about raw strings is more suitable solution.
