### ISSUE TITLE
Can driver specify a custom path?

### ISSUE THREAD

**Issue by ligaopan** [robotframework/SeleniumLibrary#1487]
When using java development, you can specify the path of the driver, such as:
System.setProperty("webdriver.chrome.driver", "D:\\chromedriver.exe" );
//Open chrome
         WebDriver driver = new ChromeDriver();

Is there a similar method for seleniumlibrary?
This function is very practical, if not, it is recommended to add it, thank you

**Comment by aaltat** [comment]
I did not test but something like this could work
```
| Open Browser | Chrome | URL | options=binary_location = '/path/to/chrome' |
```

**Comment by aaltat** [comment]
Because this looks like a support case than a bug report or feature request, I am closing this issue. For more support, please see https://github.com/robotframework/SeleniumLibrary#support
