### ISSUE TITLE
Fix Press Keys to support multiple key pressing 

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1489]
There is an issue with [Press Keys](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Press%20Keys) and it does not support multiple keys with Chrome. This is because keyword internally uses [send_keys_to_element](https://seleniumhq.github.io/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html?highlight=send_keys_to_element#selenium.webdriver.common.action_chains.ActionChains.send_keys_to_element). The Selenium `send_keys_to_element` API clicks element first and then sends keys to the driver. This causes input fields in Chrome to clear after each click. Fix `Press Keys` to support again sending multiple keys

**Comment by chenrui333** [comment]
@aaltat I would imagine this will affect `seleniumlibrary` upgrade, right?

**Comment by aaltat** [comment]
I don't quite follow, how it affects in your case?

**Comment by chenrui333** [comment]
We recently upgraded to seleniumlibrary 4.0.0, and also trying to do syntax change, `Press Key` -> `Press Keys`. 

But some of the tests failed. That is reason why I got directed into this issue.

**Comment by aaltat** [comment]
Pressing single key sequence should work fine in the 4.0 release. Example `| Press Keys | locator | CTRL+c |` should work fine. But sending multiple keys and specially to a input element can fail. Example `| Press Keys | xpath://input | AA | BB |` may fail.

**Comment by chenrui333** [comment]
Cool, I will double check on this tomorrow. Thanks!

**Comment by IhorHrankov** [comment]
@aaltat @chenrui333 we are using 'Press Key' to clear some of the custom fields `    ${text}=  Get Element Attribute  ${field}    value
    ${character count}=  get length  ${text}
    :FOR    ${index}    IN RANGE    ${character count}
    \    Press Key    ${field}    \\8` so I believe it works as sending multiple keys in our case

**Comment by chenrui333** [comment]
Cool, thanks for clarifying, @IgorGrankov !

**Comment by aaltat** [comment]
There are two keywords, `Press Key` and `Press Keys`. 

If you want to delete text from the field, then `Input Text` does it automatically. But sometimes input elements contain some strange custom implementation and do not listen events send by the Selenium. In that case, example this should work:
```
| Press Keys | //input | CTRL+a | | DELETE |
```
Should work fine.
