### ISSUE TITLE
Raise minimum required Robot Framework to 3.1

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1494]
To get better support for Python 3, raise minimum supported Robot Framework to 3.1. This will allow support for Python type annotations and allows Robot Framework to detect the type of the argument correctly and [convert argument to correct type](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#specifying-argument-types-using-function-annotations). When type is converted correctly by Robot Framework, SL can remove all code that explicitly handles the conversio, example this type of code: 
```
if is_falsy(argument):
    code here
```

Also #1021 is automatically then done.

**Comment by pekkaklarck** [comment]
I'm actually not sure about #1021. At least RF doesn't automatically convert non-typed arguments to strings. I also think it doesn't convert arguments to strings even if they'd be explicitly typed to be strings. That feature could be implemented but earliest in RF 3.2.
