### ISSUE TITLE
Document running Selinium2Library / Robot Framework under Jenkins CI Server

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#150]
Both myself, @emanlove, and @finspin ran into the issue of needing xvfb to run our Selenium2Library tests under Firefox and Linux which is not that intuitive at first.  We should add some documentation on how to setup under a CI server.

**Comment by jamescw** [comment]
Would love to know how to set this up in Jenkins

**Comment by j1z0** [comment]
There is a robot framework plugin for Jenkins that displays the RF results. Just install the plugin. Run your rf scripts from Jenkins using pybot and then point the post build RF task to your rf results. I you need more details let me know and I can post something. 

Cheers,
Jeremy

**Comment by jamescw** [comment]
Was installing xvfb straight forward enough or did you have todo anything special?

Thanks for getting back to me,
James

**Comment by j1z0** [comment]
No nothing special again there is a plugin for xfvb alternatively u can use phantomjs or sauce labs and then u don't need xfvb. 

Cheers,
Jeremy

**Comment by jamescw** [comment]
Thanks for all your help.

James

**Comment by aaltat** [comment]
There are plenty of blog post available how to setup xvfb with selenium. Also there is Robot Framework library for xvfb: https://github.com/drobota/robotframework-xvfb I think this can be closed.
