### ISSUE TITLE
Drop Robot Framework 3.0.x support

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1513]
Release of Robot Framework 3.2 is getting near and it introduces backwards incompatible changes. Therefore drop Robot Framework 3.0 support and take RF 3.2 in use in test data.

**Comment by pekkaklarck** [comment]
Need to add type information support to PythonLibCore and SL can can benefit from automatic type conversion.

**Comment by aaltat** [comment]
Yes, we need to discuss about it. I am not sure how to proceed with that one.
