### ISSUE TITLE
javascript error?

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#152]
I've been seeing javascript errors occurring in google chrome testing, usually ssociated with the select from list method.  Has anyone else seen this error?

**Comment by know1nos** [comment]
I might add performing the tests manually can not replicate these errors...

**Comment by know1nos** [comment]
![Javascript Error.PNG](https://f.cloud.github.com/assets/2244307/3700/3240ac54-42de-11e2-9beb-93a2c2b39ab6.PNG)

**Comment by emanlove** [comment]
@know1nos I'm not sure I understand what you mean by "performing the tests manually can not replicate these errors"? Could you gave an example/code of how you run the tests differently between manual and otherwise?

**Comment by know1nos** [comment]
What I meant was we cannot replicate the issue with a human user.  The issue does appear when we are using a chrome instance started with the chrome driver, so I believe the issue is not with the selenium2library specifically. I believe this issue can be deleted.

**Comment by emanlove** [comment]
As per @know1nos "I believe this issue can be deleted."
