### ISSUE TITLE
Unpredictable URLError: <urlopen error timed out>

### ISSUE THREAD

**Issue by bubenkoff** [robotframework/SeleniumLibrary#153]
Most likely it's not an issue in this library, but in selenium directly, but please advise.
I have occasional subj  errors during the tests runing. It waits for socket opened to webdriver, when all ok with the test itself, browser is working ok too, just that socket if frozen.
I tried to change defaulttimeout in sockets, but in result that  did nothing - no timeout but freeze is still there, it just waits for nothing

**Comment by emanlove** [comment]
This does sound like a selenium issue. If you discover a problem with Selenium2Library please reopen this ticket.

**Comment by bubenkoff** [comment]
yes, i solved this issue via monkey patching selenium to add more time for socket. An issue is created on the selenium project also.
