### ISSUE TITLE
Open Browser keyword options argument does not support parsing complex structures.

### ISSUE THREAD

**Issue by jsellers180** [robotframework/SeleniumLibrary#1530]
I'm attempting to launch chromedriver in a mobile view using the new [mobile emulation flag](http://chromedriver.chromium.org/mobile-emulation). When I attempt to use it as an option for the open browser keyword, I am getting an error stating that too many args are passed. 
```
*** Test Case ***
open browser in mobile view
     ${mobileDev}=  Create dictionary  deviceName  Galaxy S5
     open browser  www.google.com  browser=chrome 
 options=add_experimental_option("mobileEmulation", ${mobileDev})

```

Error returned
`TypeError: add_experimental_option() takes exactly 3 arguments (4 given)`

**Comment by aaltat** [comment]
This is true and by design. When I did build the feature, I did not think that there would be need for complex Python data structures. But when now looking at the matter, that design decision was not the best one. This is not the first time when I hear about this type of problem and we could try to change the design.

To workaround the problem, you need to take a look at the `Create WebDriver` keyword.

**Comment by HelioGuilherme66** [comment]
In use the following code and it works:
```
*** Keywords ***
Chrome Mobile Go To URL
    [Arguments]    ${url}    ${mobile}=Galaxy S5
    [Documentation]    Starts a Chrome Browser in Mobile Emulation with specified device model
    ${options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys
    Create webDriver    Chrome    chrome_options=${options}
    &{mobile_emulation}=    Create Dictionary    deviceName=${mobile}
    Call Method    ${options}    add_experimental_option    mobileEmulation    ${mobile_emulation}
    Create Webdriver    Chrome    chrome_options=${options}
    GoTo    ${url}
```

**Comment by jsellers180** [comment]
@HelioGuilherme66 @aaltat  thanks! I'll implement the workaround for now but it would be cool to have the open browser keyword support the complex types.

**Comment by aaltat** [comment]
@jsellers180 This should be now fixed in the master branch, but is not yet released. Would it be possible you to install from the source: `pip install git+https://github.com/robotframework/SeleniumLibrary.git`, give it a try and provide feedback does it solve the problem you where having.

**Comment by Mamta1413** [comment]
Hi HelioGuilherme66,

How can we handle Certificate issue in chrome's mobile view. Can you pls guide.

**Comment by jsellers180** [comment]
@aaltat Unfortunately I don't have access to the codebase for the project I raised the issue for as I was laid off due to covid-19.
