### ISSUE TITLE
Expose Selenium Command Executor URL as a Keyword

### ISSUE THREAD

**Issue by osonwanne** [robotframework/SeleniumLibrary#1531]
I am trying to pass "**command executor URL**", along with session ID of an existing Selenium WebDriver Ie() session to another test case in .py file. I can currently assign the session ID by using Keyword "Get Session Id". Could there be a keyword (that is not "Get Location" which uses the base url of application under test) but localhost IP address with the port number that shows in logs in RIDE?

`driver = Remote(command_executor=url, desired_capabilities={})`

using "Get Location"  I receive the following error:
c:\users\XXXXXX\python\python37-32\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

**Comment by aaltat** [comment]
It seems that you are trying to solve a problem, but you asking this as solution to the problem. Could you explain the problem and then we might be able to solve the problem better.

**Comment by osonwanne** [comment]
@aaltat 

I am trying to use the existing Selenium WebDriver session in IE from one robot test case to another that is a .py file  (exported from Selenium IDE in pytest) and continue the test instead of opening a new instance of an IE Browser session when the .py file is called as a Robot test case. In order not to open an new session of the browser, the .py file test case requires you to pass session id, and command executor url, I am unable to get command executor URL from a Robot Keyword in Selenium Library.

---

Settings:
Library           test_inputAccount.py


Keywords:
Input Account
    [Arguments]    ${account}
    ${session_id}=    Get Session Id
    ${seLib}=                   get_library_instance                      SeleniumLibrary
    ${session_url}=    ${seLib}    object.driver.command_executor._url #**This doesn't work**
    test_inputAccount    ${session_url}    ${session_id}    ${account}


In **test_inputAccount.py:**

class test_inputAccount():

	def test_inputAccount(self, url, session_id, account):  	
		# # Test name: InputAccount
		self.driver = Remote(command_executor=url, desired_capabilities={})
		self.driver.session_id = session_id

**Comment by aaltat** [comment]
Instead of that, would it be easier to share the WebDriver instance?

**Comment by osonwanne** [comment]
@aaltat 

I can already use BuiltIn to get library instance, which is an object reference. I just need a way to get the "command executor url" 

    ${session_url}=    get_library_instance    SeleniumLibrary

INFO : ${session_url} = <SeleniumLibrary.SeleniumLibrary object at 0x0466F250>

**Comment by aaltat** [comment]
You don't see why you want to do it so hard way. SeleniumLibrary active WebDriver instance is in the `driver` attribute. Example something like this could work:
```
sl = BuildIn().get_library_instance("SeleniumLibrary")
driver = sl.driver
# Your code here
```

**Comment by osonwanne** [comment]
I was able to solve it by calling a .py file

Library           remote_url.py

    ${session_url}=    remote_url

**remote_url.py**:

`from robot.libraries.BuiltIn import BuiltIn

class remote_url():

	def remote_url(self):
	    seLib = BuiltIn().get_library_instance('SeleniumLibrary')

	    # the driver is instantiated in the SeleniumLibrary, but not provided publicly, thus accessing it through this py code 
	    remote_url = seLib.driver.command_executor._url  # for local instance, this is a value in the form 'http://localhost:57856'
	   	# session_id = seLib.driver.session_id

	    return remote_url`

**Comment by aaltat** [comment]
I still don't understand why you want to create new WebDriver instance, when accessing the current one is available. But I guess this solves your problem and I will close the issue. If think otherwise, please comment to the issue.

**Comment by osonwanne** [comment]
I'm accessing the current one created by Selenium in Robot in an external
Python file that was recorded/exported. Re-using existing browser instance
to continue test cases.

**Comment by aaltat** [comment]
Yes, but if you can access the instance, you don't need to recreate the instance in your own Python library. Just get the SeleniumLibrary instance and get the active WebDriver (by using the above code) and you are done.
