### ISSUE TITLE
Wait Until Page Contains add option Limit

### ISSUE THREAD

**Issue by IlfirinPL** [robotframework/SeleniumLibrary#1543]
# Feature requests

It would extend to keyword  Wait Until Page Contains allow to add option Limit that works the same as in keywords Page Should Contain Element.

Currently to use this feature its require to use WUKS with this keyword
|Wait Until Keyword Succeeds | ${Timeout} | ${iteration} | Page Should Contain Element | ${locator} | limit=4|

Its less clear code then
| Wait Until Page Contains | ${Timeout} | ${locator} | limit=4|

**Comment by aaltat** [comment]
I agree, `Wait Until Page Contains` should also have `limit`argument and it can be generally usefully feature to have. 

@IlfirinPL would you be interested to to do PR?

**Comment by IlfirinPL** [comment]
@aaltat Yes will try

**Comment by IlfirinPL** [comment]
I have also added support of "limit" to Wait Until Page Not Contains, since its similar functionality
