### ISSUE TITLE
Overriding Create Driver to add functionality to the driver -- Question

### ISSUE THREAD

**Issue by teaglebuilt** [robotframework/SeleniumLibrary#1553]
# Question

I am attempting to extend seleniumlib and overwrite the driver creation to add my own proxy functionality.   After reading through the code. I understand that Create Webdriver will create the driver and register it in the WebDriverCache. I am wondering how and when the WebDriverCreator class and methods are used.  In my plugin, I was going to override methods in that class.

But I decided to override create_webdriver so i can register the driver in the cache and its also where the driver is wrapped by event firing. 

 My question is, from the Create Webdriver keyword, is WebDriver Creator class used / called ?

**Comment by aaltat** [comment]
Create WebDriver does not use methods from `WebDriverCreator` class, instead it resolves internally Selenium methods to call. `WebDriverCreator` is only used by `Open Browser` keyword.
