### ISSUE TITLE
Small error in 'Get Cookie' keyword documentation

### ISSUE THREAD

**Issue by Brownies** [robotframework/SeleniumLibrary#1555]
The documentation for 4.3.0 has an example
|  |  |  |
| --- | --- | --- |
| Add Cookie | foo | bar |
| ${cookie} = | Get Cookie | foo |
| Should Be Equal | ${cookie.name} | **bar** |
| Should Be Equal | ${cookie.value} | **foo** |

The values for ${cookie.name} and ${cookie.value} are swapped with each other. So it should be
|  |  |  |
| --- | --- | --- |
| Should Be Equal | ${cookie.name} | **foo** |
| Should Be Equal | ${cookie.value} | **bar** |

**Comment by jaypee1602** [comment]
changed this in my pull request, but forgot to link this issue to my commit

**Comment by aaltat** [comment]
Good catch, there is a bug in the documentation.

**Comment by aaltat** [comment]
Thank you for spotting the bug and fixing it.

Fixed in #1556
