### ISSUE TITLE
"Wait Until Location Is" error message reads "Location did not is <url> in <wait time>"

### ISSUE THREAD

**Issue by testventure** [robotframework/SeleniumLibrary#1559]
Steps to reproduce the issue:
Give "Wait Until Location Is" a parameter that will fail.

Observed: Location did not is (url) in (wait time)
Expected: Something like:
- Location did not become (url) in (wait time)
- Location did not change to (url) in (wait time)

**Comment by aaltat** [comment]
Good catch, the error message definitely needs improving. Would you like to make a PR to fix it?

**Comment by testventure** [comment]
Sure I'm willing to do that.

**Comment by aaltat** [comment]
Fixed in #1560
