### ISSUE TITLE
Choose File not working on Safari

### ISSUE THREAD

**Issue by monpriya** [robotframework/SeleniumLibrary#1569]
# For issues
## Steps to reproduce the issue
I run robot framework with seleniumLibrary, and I using keyword Choose File for upload.

It's working on Chrome, Edge But not working on Safari

```
Choose File   <locator>    <file_path>
```

## Error messages and additional information

The error I got is:
``` 
InvalidArgumentException: Message: One or more files could not be selected. 
```
Log TRACE

![file](https://user-images.githubusercontent.com/22930044/79413923-7ec6b480-7fd3-11ea-978f-72689ba2dc6d.png)

## Expected behavior and actual behavior

I was expecting Choose File working on Safari

## Environment

Browser: Safari Version 13.1 (14609.1.20.111.8)
Operating System: MacOS Mojave (10.14.6)
Libraries
- Robot Framework: 3.1.2
- SeleniumLibrary: 4.3.0
- python: 3.7.4

**Comment by aaltat** [comment]
Hmmm, exception is raised by the underlying Selenium. It's trying to say that browser or browser driver does not understand what Selenium is trying to send. Usually it means that Selenium, Browser driver or/and Browser are not compatible with each other. I would suggest to look at Apple documentation what are the supported versions for your combination. Somewhere might be good place to start https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari

**Comment by aaltat** [comment]
Because this looks configuration issue in the Safari side, I am closing this issue. If you think this is a SeleniumLibrary issue, please state so.
