### ISSUE TITLE
Selenium 4 has deprecated all find_element_by_* methods, therefore move using find_element(By.*)

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1575]
Selenium 4 has deprecated all find_element_by_* methods, therefore move using find_element(By.*). Refactor [elementfinder](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/locators/elementfinder.py) to use `find_element(By.*)` methods. Change should be backward compatible and invisible for users.

**Comment by andreagubellini** [comment]
Hi, 

I would like to help with this issue.

Any work has been done yet?

Cheers

**Comment by aaltat** [comment]
It's not started and contributions are always welcomed. Is everything clear or do you want to discuss something before starting the work?

**Comment by andreagubellini** [comment]
Yep, I believe everything is clear.  Just one question: is elementfinder the only class impacted by this?

**Comment by aaltat** [comment]
It should be the only place. All should go through elementfinder and if it's not it can be changed.

**Comment by badari412** [comment]
I don't see any PRs linked to this, so please let me know if it's still waiting for a contributor. If yes, I would like to work on this.

**Comment by aaltat** [comment]
I have not seen anything, please start looking in to the issue.

**Comment by badari412** [comment]
Thanks, will do!

**Comment by aaltat** [comment]
Done in #1626
