### ISSUE TITLE
Element should be focused while inputing the text until it completes while parallel testing the focus go out of the devx-tagbox and cannot complete typing hence the result doesnot come

### ISSUE THREAD

**Issue by sushmapothamsetti** [robotframework/SeleniumLibrary#1583]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment]
I don't understand what you are trying to say, please clarify your issue.

**Comment by sushmapothamsetti** [comment]
Hi,During parallel testing some of the elements get cleared out when we focus out of the input textbox while typing.(For example tagbox incase of angular).So i cannot type completly. For example i am typing 'Beauty and the beast'.After i type beauty the focus has went away so 'beauty got cleared off automatically.Now when i am back in focus since beauty has cleared off i can only type "and the beast".Sometimes my whole text box will be cleared.So,i want to completely focus on the element while inputting the text(typing) during parallel testing .I tried Element should be focused.Not sure how to combine the keywords  Input text and element should be focused.Kindly help.

**Comment by aaltat** [comment]
SeleniumLibrary or underlying Selenium does not change the focus in your application. It's your application that changes something (it might not be focus) so that characters gets lost. I would bet that there is JavaScript running which causes some troubles.

But this is more of an support case and because this issue tracker is reserved for enhancements or bugs, I am closing this issue. For more support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
