### ISSUE TITLE
webdriver can't find js element after using remote library

### ISSUE THREAD

**Issue by wingking** [robotframework/SeleniumLibrary#159]
C:\Documents and Settings\Administrator>pybot --version
Robot Framework 2.7.5 (Python 2.7.2 on win32)
win xp , ie8
selenium2libary 1.0.0

RF is on PC A, 
setp 1 : open browser to url1
step 2 : do somethong on PC B
step 3 : click a elemnt on the page of step 1
it can't find the element(it is generated by javascript)
if the element is not generated by js,it clicks.

if i delete step 2, it clicks the js element.

**Comment by emanlove** [comment]
This does sound like a selenium issue. If you discover a problem with Selenium2Library please reopen this ticket.
