### ISSUE TITLE
Importing 'SeleniumLibrary' failed with syntaxError: invalid syntax (StringIO.py)

### ISSUE THREAD

**Issue by TimKoomen** [robotframework/SeleniumLibrary#1593]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Robotframework 3.2.1, Python 3.8.2, Seleniumlibrary 4.4.0, Windows10, browser drivers up-to-date.
In Pycharm, Settings, Python Interpreter, updates all libs (May 5)
7 or 8 days ago it still worked (~April 27-28)

## Error messages and additional information
[ ERROR ] Error in file 'I:\development\robot-scripts\first-script\Resources\Common.robot' on line 2: Importing test library 'SeleniumLibrary' failed: SyntaxError: inva
lid syntax (StringIO.py, line 40)
Traceback (most recent call last):
  File "i:\python\lib\site-packages\SeleniumLibrary\__init__.py", line 28, in <module>
    from SeleniumLibrary.keywords import (AlertKeywords,
  File "i:\python\lib\site-packages\SeleniumLibrary\keywords\__init__.py", line 17, in <module>
    from .alert import AlertKeywords
  File "i:\python\lib\site-packages\SeleniumLibrary\keywords\alert.py", line 18, in <module>
    from selenium.webdriver.support import expected_conditions as EC
  File "i:\python\lib\site-packages\selenium\webdriver\__init__.py", line 18, in <module>
    from .firefox.webdriver import WebDriver as Firefox  # noqa
  File "i:\python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 29, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "i:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 26, in <module>
    from .webelement import WebElement
  File "i:\python\lib\site-packages\selenium\webdriver\remote\webelement.py", line 37, in <module>
    from StringIO import StringIO as IOStream
PYTHONPATH:
  I:\Python\Scripts\robot.exe
  i:\python\python38.zip
  i:\python\DLLs
  i:\python\lib
  i:\python
  i:\python\lib\site-packages

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment]
Exception is raised in the Selenium side, please report problem in their side https://github.com/SeleniumHQ/selenium

Closing issue because this is not SeleniumLibrary issue.
