### ISSUE TITLE
Need a keyword/Existing Keyword 'Input Text' with param hide_text_in_log=True

### ISSUE THREAD

**Issue by saiteja99498** [robotframework/SeleniumLibrary#1609]
If I want to enter (secret) text using '[Input Text](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Input%20Text)' keyword and share the log to other they might see the text I entered in the log file. 

We can achieve this by using the keyword 'Input Password' but the Keyword named that it should be used only with the password (I want to enter a secret text but it is not a password at all)

For this i'm requesting to add a parameter to Input text keyword  "hide_text_in_log= False" and it false by default

**Comment by Snooz82** [comment]
But this is absolutely what `Input Password` is.

You could also just:
```
${org_level}=    Set Log Level    None
Input Text    id:text     mysecret text
Set Log Level    ${org_level}
```

I do not see any need for a new keyword that would exactly do what `Input Password` already does but with another name...

**Comment by aaltat** [comment]
As @Snooz82 said, `Input Password` does what you want. If you have a reason why that is not good enough or have other reason why `Input Text` should be enhanced in this category, please let's us know and we will consider reopening the issue. But for now I am going to close the issue.
