### ISSUE TITLE
Choose File not working when running against a remote machine.

### ISSUE THREAD

**Issue by djl197** [robotframework/SeleniumLibrary#1617]
# Summary
My issue is very similar to #1551 

My code currently uses library version 3.3 and this works as expected.  
However when I upgrade to version 4.3 I get this error (much like #1551).

```

12:32:10.084	DEBUG	Page contains element //div[@id='import_license_dialog']/*//input[@type='file']	
12:32:10.084	INFO	Sending /tmp/license_to_import to browser.	
12:32:10.084	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/7191f3c4a5518c37b417031f7e3f8080/elements {"using": "xpath", "value": "//div[@id='import_license_dialog']/*//input[@type='file']", "sessionId": "7191f3c4a5518c37b417031f7e3f8080"}	
12:32:10.107	DEBUG	Finished Request	
12:32:10.107	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/7191f3c4a5518c37b417031f7e3f8080/element/0.06728975866412834-4/value {"text": "/tmp/license_to_import", "value": ["/", "t", "m", "p", "/", "l", "i", "c", "e", "n", "s", "e", "_", "t", "o", "_", "i", "m", "p", "o", "r", "t"], "id": "0.06728975866412834-4", "sessionId": "7191f3c4a5518c37b417031f7e3f8080"}	
12:32:10.143	DEBUG	Finished Request	
12:32:10.186	FAIL	InvalidArgumentException: Message: invalid argument: File not found : /tmp/license_to_import
  (Session info: chrome=72.0.3626.121)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-164-generic x86_64)
12:32:10.186	DEBUG	Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.6/site-packages/MkLibrary/keywords.py", line 177, in import_license_file
    selenium_lib.import_license()
  File "/home/jenkins/.local/lib/python3.6/site-packages/MkLibrary/keywords.py", line 95, in import_license
    self.get_sl().choose_file(choose_file_locator, '/tmp/license_to_import')
  File "/usr/local/lib/python3.6/dist-packages/SeleniumLibrary/keywords/formelement.py", line 216, in choose_file
    self.find_element(locator).send_keys(file_path)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)	
12:26:06.031	TRACE	Arguments: [  ]
```

# For issues
## Steps to reproduce the issue
I try to upload the file as part of Setup Teardown in  a Robot Framework test.

## Error messages and additional information
See above for the error trace.

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: 3.1.2
- Selenium: 3.141
- SeleniumLibrary: 4.3.0

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment]
Based on the logs message and looking at the code, I would assume that you do not have local file `/tmp/license_to_import` (Local here means the environment where the Robot Framework test is running.) From the log, it can be seen that it does not send it as a file, but instead Selenium send the file as a path:
```
12:32:10.107	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/7191f3c4a5518c37b417031f7e3f8080/element/0.06728975866412834-4/value {"text": "/tmp/license_to_import", "value": ["/", "t", "m", "p", "/", "l", "i", "c", "e", "n", "s", "e", "_", "t", "o", "_", "i", "m", "p", "o", "r", "t"], "id": "0.06728975866412834-4", "sessionId": "7191f3c4a5518c37b417031f7e3f8080"}	
```
If it would be transferred as a file, then the file content would be transferred as a base64 string (If I remember correctly the Selenium implementation.) Cloud you make sure that file exist the local file system. 

If the local file exist, would it be possible to get example which also I can run and demonstrates the problem?

**Comment by djl197** [comment]
I ran the same Robot Framework test with the older version 3,3 used and I can see an additional entry in the debug:
```

16:40:49.358	DEBUG	Page contains element //div[@id='import_license_dialog']/*//input[@type='file']	
16:40:49.358	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/1b294c9c371e82e5a3047084ac666495/elements {"using": "xpath", "value": "//div[@id='import_license_dialog']/*//input[@type='file']", "sessionId": "1b294c9c371e82e5a3047084ac666495"}	
16:40:49.374	DEBUG	Finished Request	
16:40:49.383	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/1b294c9c371e82e5a3047084ac666495/file {"file": "<file contents>", "id": "0.6216670674952012-4", "sessionId": "1b294c9c371e82e5a3047084ac666495"}	
16:40:49.449	DEBUG	Finished Request
16:40:49.450	DEBUG	POST http://<ipaddr>:24444/wd/hub/session/1b294c9c371e82e5a3047084ac666495/element/0.6216670674952012-4/value {"text": "/tmp/1b294c9c371e82e5a3047084ac666495/upload7282340463753300514file/license_to_import", "value": ["/", "t", "m", "p", "/", "1", "b", "2", "9", "4", "c", "9", "c", "3", "7", "1", "e", "8", "2", "e", "5", "a", "3", "0", "4", "7", "0", "8", "4", "a", "c", "6", "6", "6", "4", "9", "5", "/", "u", "p", "l", "o", "a", "d", "7", "2", "8", "2", "3", "4", "0", "4", "6", "3", "7", "5", "3", "3", "0", "0", "5", "1", "4", "f", "i", "l", "e", "/", "l", "i", "c", "e", "n", "s", "e", "_", "t", "o", "_", "i", "m", "p", "o", "r", "t"], "id": "0.6216670674952012-4", "sessionId": "1b294c9c371e82e5a3047084ac666495"}	
16:40:49.478	DEBUG	Finished Request	
16:40:49.479	DEBUG	Pre wait until page contains element //div[@id='import_license_dialog']/*//button[@type='submit']
```
Here I can see that it has sent the file, and then updated the filename to a modified path which is present.
I am adding more debug to see how I can help more - we have a custom Key Word that then calls choose_file python method.  Are we missing some code that was implicit in 3.3 and now needs to be explicit in 4.4?

**Comment by djl197** [comment]
I have an educated guess at the problem.  Between 3.3 and 4.x the following code was added:
```
    def choose_file(self):
        try:
            sl = self._get_sl()
        except Exception:
            sl = None
        if sl and sl._running_keyword == 'choose_file':
            return True
        return False
```

The problem is are not using the Keyword Choose File but calling the python method choose_file from our own Keyword (Import License File).  Therefore I think the choose_file is returning False when it should be true.

If my understanding is correct - does this mean that we cant have a custom keyword that calls choose_file?

**Comment by aaltat** [comment]
The public API should be the same, but internally it has changed a lot. Motivation to change is explained in #1398 and the actual change #1417 Therefore it is possible that something has changed between the versions or you run in to some case, which is not covered by [the tests](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/acceptance/keywords/choose_file.robot#L25).

**Comment by aaltat** [comment]
> I have an educated guess at the problem. Between 3.3 and 4.x the following code was added:

That should not affect unless you use the library without RF being running. But are you doing so?

**Comment by djl197** [comment]
I am not sure I fully understand?  We are using RobotFramework running on one node, and then using a remote session to actually run the tests.  This is the docker-selenium node from elgalu.  
We have written our own keywords in python and we call some of the functions directly (for example choose_file rather than via the Robot Keyword of 'Choose File'
I can see why the logic was changed and understand.  I presume instead of calling
```
choose_file(locator, file_path)
```
I could call (have i got the syntax correct):
```
run_keyword(choose_file, locator, file_path)
```
Which would use the Public API and thus probably work?

**Comment by aaltat** [comment]
I was unclear in my question. But is the SeleniumLibrary running in the same Python process where the Robot Framework is running? Or are you running SeleniumLibrary in some other way?

**Comment by aaltat** [comment]
Another option is that you have not imported SeleniumLibrary only in the Python side and not in the Robot Framework data side.

**Comment by djl197** [comment]
In my Robot test (Suite Setup/Teardown) I have the following:
```
Library    SeleniumLibrary
Library    BuiltIn
Library    OurCustomLibrary
...
```
It is all running in the same process.  In our Setup function it calls a custom Keyword implemented in OurCustomLibrary.  That keyword (Import License File) - Clicks a few elements in the Product GUI and then calls choose_file directly with the xpath selector string and the filename.  
I cant see how the _running_keyword would ever be anything other than our Custom Keyword (i.e import_license_file) - and if that is the case I think the logic would not work in LocalFileSelector as it would not have a _running_keyword of choose_file.
But I could be missin g something as I am debugging this (I did not write it :-) )

**Comment by aaltat** [comment]
I can reproduce the problem and fix is pretty easy to do also. Just need to move the location where detection of choose file is done.

**Comment by aaltat** [comment]
The issue should be fixed in the master branch. I ma going to push out 4.5.0 release candidate 2 soon and I will let you test it out.

Thank you for being persistent on the issue and not giving up.

**Comment by djl197** [comment]
Thankyou for the support - great job - once RC2 is available I will integrate and test :-)

**Comment by aaltat** [comment]
RC2 is already out https://pypi.org/project/robotframework-seleniumlibrary/4.5.0rc2/

**Comment by djl197** [comment]
Fixed 👍  Proved in our setup - great job, thankyou
