### ISSUE TITLE
proxy support missing for IE

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#162]
Hello, I'm using robotframework_selenium2library-1.1.0-py2.7.egg from RobotFramework and need to open the browser with proxy settings.
I'm trying to do 
Open | Internet Explorer Browser | http://www.whatismyip.com/ | None | None | httpProxy:http://127.0.0.1:9666 
but it seems to work.

Is there any way to do this?

Trace:
23:51:39.334    INFO    Opening browser 'Internet Explorer' to base url 'http://www.whatismyip.com/' through remote server at 'None'
23:51:39.340    WARN    Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
23:51:39.342    FAIL    ValueError: too many values to unpack

**Comment by ombre42** [comment]
Please read issue https://github.com/rtomac/robotframework-selenium2library/issues/32#issuecomment-3928892. You have to use the standalone webdriver server and you are not specifying a remote url in your keyword.

**Comment by ombre42** [comment]
Here is a way to do it as of 1.5. I noticed that the proxy settings are not always restored after the teardown. This is an issue with Selenium and not Selenium2Libary.

```
IE Proxy
    ${proxy}=    Set Variable    localhost:8888
    ${caps}=    Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.INTERNETEXPLORER.copy()    sys, selenium.webdriver
    ${proxy dict}=    Create Dictionary    proxyType    MANUAL    httpProxy    ${proxy}    ftpProxy
    ...    ${proxy}    sslProxy    ${proxy}
    Set To Dictionary    ${caps}    proxy    ${proxy dict}
    Log Dictionary    ${caps}
    Create Webdriver    Ie    capabilities=${caps}
    ${s2l}=    Get Library Instance    Selenium2Library
    Log Dictionary    ${s2l._current_browser().capabilities}    # log actual capabilities
    Go To    http://www.yahoo.com/
    [Teardown]    Close All Browsers
```
