### ISSUE TITLE
How to locate the next Xpath element with the same id

### ISSUE THREAD

**Issue by colleenantonio** [robotframework/SeleniumLibrary#1620]
I was trying to locate the next Xpath with the same id of "undefined_0.... 1..... 2"

**Tried this syntax:**
Click Element    //*[@id="undefined_0"][1]     # Added index [1] to get the next label = "All" since it displays 4 of 4 results 

**The BE/ html looks like this:**
See attached zip file: [html_code.zip](https://github.com/robotframework/SeleniumLibrary/files/4957326/html_code.zip)

**Message Log: Error**
 FAIL : ElementNotInteractableException: Message: element not interactable

**Expected behavior**
It should locate the next element of the same Xpath location (should I really have to add the index at the end of the Xpath?)

**Comment by aaltat** [comment]
This is a support request, but this issue tracker is reserved for bugs and enhancement request. Therefore I am going to close this issue. For getting more help, see https://github.com/robotframework/SeleniumLibrary#support
