### ISSUE TITLE
Not able to find Open Browser Keyword in SeleniumLibrary

### ISSUE THREAD

**Issue by Kalyan-Nk** [robotframework/SeleniumLibrary#1621]
I am trying to write a simple webLogin Testcase in Roboframework, Below preconditions are done.

1. Installed all the necessary packages
2. Installed required SSH/SeleniumLibrary and Mozilla geckodriver
3. Imported SSH and Selenium Library, however i couldnt see any "Open Browser" keyword in SeleniumLibrary
Could anyone help me with this.

Requirement already up-to-date:

urllib3 in c:\program files\python36\lib\site-packages (from selenium>=3.141.0->robotframework-seleniumlibrary)
Installing collected packages:
<img width="960" alt="Test" src="https://user-images.githubusercontent.com/68810989/88808291-52285880-d1d0-11ea-9f5e-af324b84e29a.PNG">
<img width="960" alt="Test" src="https://user-images.githubusercontent.com/68810989/88808678-cf53cd80-d1d0-11ea-974b-df1596b3ba5d.PNG">

>

**Comment by aaltat** [comment]
I don't have any idea why that IDE does not work like it should. But this is a problem with IDE and not with the SeleniumLibrary, because keyword exists and works with  Robot Framework. Please raise an issue to IDE/plugin project. 

Because this is not SeleniumLibrary problem, I am closing issue.

**Comment by HelioGuilherme66** [comment]
There is no problem with SeleniumLibrary. That is a RIDE problem.

You should install the current Beta version of RIDE to have that problem solved:

```
pip install -U --pre robotframework-ride

```

**Comment by Kalyan-Nk** [comment]
Thanks HelioGuilherme66, i installed latest RIDE beta version and i can use the keyword.

**Comment by Kalyan-Nk** [comment]
> I don't have any idea why that IDE does not work like it should. But this is a problem with IDE and not with the SeleniumLibrary, because keyword exists and works with Robot Framework. Please raise an issue to IDE/plugin project.
> 
> Because this is not SeleniumLibrary problem, I am closing issue.

Thanks for your time.

**Comment by hppsmokey** [comment]
Hi Kalyan,

Try using Zoomba.GUILibrary. It has Open Browser keyword and it pretty much
inherits all the keywords from Selenium Library.

Thanks
Ram L
