### ISSUE TITLE
I want to use event_firing_webdriver when import SeleniumLibrary，but something went wrong

### ISSUE THREAD

**Issue by lijiahao10086** [robotframework/SeleniumLibrary#1622]
**error log:**
Traceback (most recent call last):
Initializing test library 'SeleniumLibrary' with arguments [ event_firing_webdriver=MyListener ] failed: DataError: Importing test Selenium lister class 'MyListener' failed.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 167, in _get_instance
    return libcode(*self.positional_args, **dict(self.named_args))
  File "C:\Python27\lib\site-packages\SeleniumLibrary\__init__.py", line 460, in __init__
    self.event_firing_webdriver = self._parse_listener(event_firing_webdriver)
  File "C:\Python27\lib\site-packages\SeleniumLibrary\__init__.py", line 608, in _parse_listener
    raise DataError(message)
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 87, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 24, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 54, in TestLibrary
    lib.create_handlers()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 100, in create_handlers
    self._create_handlers(self.get_instance())
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 159, in get_instance
    self._libinst = self._get_instance(self._libcode)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 169, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 314, in _raise_creating_instance_failed
    % (self.name, args_text, msg, details))

**when I choose .py file ,error log：**

Traceback (most recent call last):
Initializing test library 'SeleniumLibrary' with arguments [ event_firing_webdriver=./MyListener.py ] failed: DataError: Importing test library './MyListener.py' failed: ImportError: Import by filename is not supported.
Traceback (most recent call last):
  None

**Version information：**
Package                        Version
------------------------------ -----------
bcrypt                         3.1.7
cffi                           1.14.1
cryptography                   3.0
enum34                         1.1.10
ipaddress                      1.0.23
numpy                          1.16.6
paramiko                       2.7.1
Pillow                         6.2.2
pip                            20.2.1
pycparser                      2.20
Pygments                       2.5.2
PyNaCl                         1.4.0
PyPubSub                       3.3.0
pywin32                        228
robotframework                 3.1.2
robotframework-pythonlibcore   2.1.0
robotframework-ride            1.7.4.2
robotframework-seleniumlibrary 4.5.0
robotframework-sshlibrary      3.4.0
scp                            0.13.2
selenium                       3.141.0
setuptools                     41.2.0
six                            1.15.0
urllib3                        1.25.10
win-inet-pton                  1.1.0
wxPython                       4.0.7.post2

**Comment by ghost** [comment]
Interesting, you have two problems: 1) Import with module search path 2) Import with path

The both importing ways use the same import mechanics as Robot Framework uses internally. 

1) Mode search path
This error is caused that you plugin is not found from the module search path. Because SeleniumLibrary uses same import mechanics as RF, please see RF user guide how to adjust your module search path: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#module-search-path

2) Import with path
This is interesting, because SeleniumLibrary has an [acceptance test](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/acceptance/2-event_firing_webdriver/event_firing_webdriver.robot#L2) which says that it is possible. 

But both of the errors are coming RIDE. If you do simple test and run it from the command line (by not using RIDE anywhere in the test creation), do you still get the same errors?

**Comment by lijiahao10086** [comment]
hi，I run it by the command line，success!

1）
I put module in C:\Python27\Lib\site-packages,it's RF search path

2)Import with path
exactly，I using RIDE import file，emmm，Import selenium library error，the wrong log has been put in

But,I run it by the command line，it works amazing

Thank you very much for your reply. It's my pleasure，hhhhh

**Comment by lijiahao10086** [comment]
emmm，I think it's a bug in RIDE，do you think so？

sorry，my english is not well, please understand ~~

**Comment by aaltat** [comment]
Because it works from command line, I would assume that this is a problem with RIDE. Please raise an issue to RIDE issue tracker. And I am closing this issue, because it's not problem with SeleniumLibrary.
