### ISSUE TITLE
cannot install Selenium2Library properly

### ISSUE THREAD

**Issue by DJoeri** [robotframework/SeleniumLibrary#163]
Win7 64 bit
i installed the package both with pip and easy_install, and both have the same result.
on the cmd line in a DOS window, in Python, i'm able to import Selenium2Library without errors,
but when i try to run an ant script from within Eclipse , starting  org.robotframework.RobotFramework via a java task (which obliges me to set my classpath myself within the ant-script),
i have the below issue.
I could already get rid of the error "cannot find module decorator" (allthough also installed via easy_install) by copying the decorator directory into my project, and adding this project directory in my ant java classpath.
However, the below error i cannot get rid of because i don't understand the problem.

When i go the keywordgroup file in Eclipse, i get the warning "assignment to reserved build in symbol dict.

 [java] [ ERROR ] Error in file 'C:...txt' in table 'Settings': Importing test library 'Selenium2Library' failed: TypeError: Error when calling the metaclass bases
     [java]     'module' object is not callable
     [java] Traceback (most recent call last):
     [java]   File "**pyclasspath**/Selenium2Library/**init**.py", line 2, in <module>
     [java]   File "**pyclasspath**/Selenium2Library/keywords/**init**.py", line 2, in <module>
     [java]   File "**pyclasspath**/Selenium2Library/keywords/_runonfailure.py", line 6, in <module>
     [java]   File "__pyclasspath__/Selenium2Library/keywords/keywordgroup.py", line 24, in **new**

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
