### ISSUE TITLE
Add support for xpath starting with ((//

### ISSUE THREAD

**Issue by lynhbn** [robotframework/SeleniumLibrary#1652]
Currently, we are only treating `//` and `(//` as xpath expression

Please help to add support also for `((//`

For example, my xpath having union operator:
```((//label[contains(.,"ABC")]/input[@type="checkbox"]|//label[contains(.,"ABC")]/preceding-sibling::*[@type="checkbox"]))[1]```

It's still a vaid xpath expression, but unable to be detected in SeleniumLibrary

Thank you

**Comment by aaltat** [comment]
xpath is very complex language and we automatically detect only a [small fraction](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/locators/elementfinder.py#L303) of the xpath syntax, although it is the most common fraction. You can avoid the problem by defining strategy for the xpath, example in your case: `xpath:((//label[contains(.,"ABC")]/input[@type="checkbox"]|//label[contains(.,"ABC")]/preceding-sibling::*[@type="checkbox"]))[1]`. 

Although technically the doing what you request is not hard, I have fear that this change could be backwards incompatible. The point is that could the change mess someone default locator syntax?

**Comment by pekkaklarck** [comment]
I would expect it to be safe to automatically detect a locator is an xpath if there's any number of `(`s before `//`. The current check is

```python
if locator.startswith(('//', '(//')):
   ...
```
but it could be changed to

```python
if re.match(r'\(*//', locator):
   ...
```

**Comment by lynhbn** [comment]
I should go for @pekkaklarck 's solution. It's quite decent.

Adding prefix `xpath:` sometimes causes a little bit cumbersome, for example when I need to do something like `execute_javascript(f"document.evaluate('{my_xpath}', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.select()")` , I need to remove this prefix again before executing the JS snippet

**Comment by aaltat** [comment]
Interested of making a PR to implement your need?
