### ISSUE TITLE
Can seleniumLibrary / selenium2Library be used to automate desktop application ( in windows and mac OS )

### ISSUE THREAD

**Issue by MoniRaj1** [robotframework/SeleniumLibrary#1661]
Desktop application - Electron based application
OS support requirement - Windows and mac

**Comment by MoniRaj1** [comment]
Desktop application - Electron based application 
OS support requirement - Windows and mac

**Comment by aaltat** [comment]
Never done and therefore can not answer. Most likely you will get better answers in [community forums](https://github.com/robotframework/SeleniumLibrary#id12). 

But because this is support request, I am closing this issue. Issue tracker is reserved for bug reports or enhancement request.
