### ISSUE TITLE
RIDE Cannot Find Switch Window Keyword

### ISSUE THREAD

**Issue by MummanaSubramanya** [robotframework/SeleniumLibrary#1668]
I was using select window in 4.3.0 and I read in 4.5.0 we need to use Switch Window but Ride is unable find the keyword. Please find the screenshot. 
<img width="1158" alt="Screenshot 2020-10-02 at 8 34 50 AM" src="https://user-images.githubusercontent.com/25982124/94894871-877c4b80-048a-11eb-8acb-64f000c027c4.png">

## Steps to reproduce the issue
1) Upgraded from 4.3.0 to 4.5.0 

## Error messages and additional information
 No error message

## Expected behavior and actual behavior
Expected: Switch Window keyword should be able use via RIDE
actual: Cannot find Switch Window

## Environment

Browser: Chrome
Browser driver: chromedriver
Operating System: Win10
Libraries
- Robot Framework: 3.2.2
- Selenium: NA
- SeleniumLibrary: 4.5
- Interpreter: Name and version

**Comment by aaltat** [comment]
This is a RIDE problem, which I think is fixed in some RIDE pre release, please consult RIDE project.
