### ISSUE TITLE
Drag and drop doesn't work on Linux with firefox

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#1678]
I can see that drag and drop keyword doesn't work using last relase of seleniumLibrary on Red Hat 7.8 with Firefox

Please find the robot framework test suite.
*** Settings ***
| Documentation | IO Instrumentation workspace tests
| Library       | SeleniumLibrary
| Library       | BuiltIn
Library  OperatingSystem
| Default Tags  | IOI   |  details
| Resource      | ${CURDIR}/keywords.txt
| Variables     | ${CURDIR}/variables.py

*** Test Cases ***
workspace-add-chart
|       | [Documentation] | add a chart - scale 100
|       | Access to details page
|       | Run Keyword And Continue On Failure | Wait Until Page Contains Element | id:operations-button
|       | Sleep | 5s
|       |  Execute Javascript  | document.getElementById("scale-100").classList.remove('hidden')
|       | Run Keyword And Continue On Failure | Wait Until Page Contains Element | id:scale-100
|       | Drag And Drop | id:operations-button | id:scale-100
|       | Run Keyword And Continue On Failure | Wait Until Page Contains Element | css:.myChart

## Error messages and additional information

 robot test-workspace.txt
==============================================================================
Test-Workspace :: IO Instrumentation workspace tests
==============================================================================
workspace-add-chart :: add a chart - scale 100                        | FAIL |
Element 'css:.myChart' did not appear in 5 seconds.
------------------------------------------------------------------------------
Test-Workspace :: IO Instrumentation workspace tests                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================

## Environment

Browser: firefox
Browser driver: firefox quantum 68.8.0esr 64 bits
Operating System: Name and version (Linux, Red Hat 7.8
Libraries
- Robot Framework: Robot Framework 3.2.2 (Python 3.6.8 on linux)

acco (2.5)
appdirs (1.4.3)
beautifulsoup4 (4.9.3)
certifi (2020.6.20)
chardet (3.0.4)
ClusterShell (1.8.3)
colorama (0.4.3)
configparser (5.0.0)
crayons (0.4.0)
distlib (0.3.0)
filelock (3.0.12)
flash-sbbreport (2.0)
flash-sbbtool (2.0)
flash-utils (2.0)
idna (2.10)
importlib-metadata (1.6.0)
importlib-resources (1.4.0)
Jinja2 (2.8.1)
jsonschema (2.5.1)
lxml (4.5.2)
MarkupSafe (0.23)
numpy (1.19.2)
Pillow (7.2.0)
pip (9.0.3)
PyYAML (3.12)
requests (2.24.0)
robotframework (3.2.2)
robotframework-pythonlibcore (2.1.0)
robotframework-selenium2library (3.0.0)
robotframework-seleniumlibrary (4.5.0)
selenium (3.141.0)
setuptools (39.2.0)
six (1.14.0)
soupsieve (2.0.1)
tqdm (4.50.1)
urllib3 (1.25.10)
virtualenv (20.0.17)
webdriver-manager (3.2.2)
webdrivermanager (0.9.0)
zipp (3.1.0)

**Comment by aaltat** [comment]
Yes, this is pretty common problem with Selenium and browsers versions. Selenium is really picky when it work correctly with drag and drop and it causes numerous problems in various places. Because the Keyword in [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L743-L746) relies purely on Selenium implementation. there is not much we could fix in SL side. 

To fix your problem, you could try [Selenium testability](https://pypi.org/project/robotframework-seleniumtestability/) it has better drag and drop support. Also it is possible that some application/browsers needs to perform the drag in drop by using other Selenium action chains, but for that you need to implement your own custom keyword.

**Comment by ghost** [comment]
Ok thanks for your quick answer. I tried using Selenium testability without success; I will try another way

Best regards
