### ISSUE TITLE
Get Webelements not returning text for all elements in list dropdown

### ISSUE THREAD

**Issue by mverma-va** [robotframework/SeleniumLibrary#1681]
I have a list of 20 items (only few visible) and trying to find element by text of item, but "Get Text" not returning text after 14th item.
robotframework version: 3.2.2
robotframework-seleniumlibrary version: 4.5.0

![image](https://user-images.githubusercontent.com/4573058/102253629-92654a80-3ed5-11eb-8170-58c297ff2c2f.png)
![image](https://user-images.githubusercontent.com/4573058/102253816-d2c4c880-3ed5-11eb-8f34-95773eef10b7.png)

Get Row Index of Element
    [Arguments]  ${rows_locator}  ${element_text}
    @{row_list}=  Get WebElements    ${rows_locator}
    sleep  1s
    ${len}=  get length  ${row_list}
    log  ${len}
    FOR  ${index}  ${element}  IN ENUMERATE  @{row_list}
        ${found_text}=  Get Text  ${element}
        log  ${found_text}
        log  ${index}
        run keyword if  $element_text in $found_text    exit for loop
    END
    ${index} =    Set Variable    ${index+1}
    ${index}=    convert to string  ${index}
    Return From Keyword    ${index}

**Comment by aaltat** [comment]
Yes, this is how Selenium works. If element is not visible text is not returned. There is nothing we can fix in the SeleniumLibrary side and therefore I am going to close the issue.

**Comment by mverma-va** [comment]
@aaltat  thanks for responding but still have one doubt, I am able to get all 20 elements returned by Get Webelements though, how is that possible (only 12 are visible), as Get Text is not working for not visible elements (as you said). 

What would be an ideal workaround here?
