### ISSUE TITLE
"Close Browser" keyword not working in IE,GC.i am using selenium2Library.Please help me in resolving it.

### ISSUE THREAD

**Issue by sunita1jangra** [robotframework/SeleniumLibrary#1682]
"Close Browser" keyword not working in IE,FF.i am using selenium2Library.Please help me in resolving it.

C:\Users\Hp>pip freeze
certifi==2020.12.5
chardet==4.0.0
idna==2.10
numpy==1.19.5
Pillow==8.1.0
psutil==5.8.0
Pygments==2.7.4
Pypubsub==4.0.3
pywin32==300
requests==2.25.1
robotframework==3.2.2
robotframework-pythonlibcore==2.2.1
robotframework-requests==0.8.0
robotframework-ride==2.0b1
robotframework-selenium2library==3.0.0
robotframeworklexer==1.1
selenium==3.141.0
six==1.15.0
urllib3==1.26.2
wxPython==4.1.1

C:\Users\Hp>

**Comment by aaltat** [comment]
You are missing a dependency Selenium2Library, Selenium2Library also needs SeleniumLibary. So 
 `pip install robotframework-seleniumlibrary` Also you should migrate to SeleniumLibrary, because Selenium2Library is deprecated.

**Comment by sunita1jangra** [comment]
thanks @aaltat , with SeleniumLibrary it is working.
