### ISSUE TITLE
Register Keyword to Run on Failure Bug or Doc fix

### ISSUE THREAD

**Issue by neiljhowell** [robotframework/SeleniumLibrary#1686]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Register Keyword to Run on Failure  no longer works with NONE:

*** Settings ***
Library                 SeleniumLibrary

*** Variables ***
${browser}              chrome

*** Keywords ***
Test Case Setup
    [Arguments]                 ${url}=https://github.com/      ${browser}=${browser}
    Open Browser                ${url}                          browser=${browser}
    Maximize Browser Window
    Set Selenium Speed          0.2s

*** Test Cases ***
NONE test for Selenium 5.0.0
    [Teardown]                  Close All Browsers
    Register Keyword To Run On Failure  NONE
    Test Case Setup             https://www.quackit.com/html/codes/html_popup_window_code.cfm
    Select Frame                //iframe[@name='result1notfound']

Python None test for Selenium 5.0.0
    [Teardown]                  Close All Browsers
    Register Keyword To Run On Failure  None
    Test Case Setup             https://www.quackit.com/html/codes/html_popup_window_code.cfm
    Select Frame                //iframe[@name='result1notfound']

NOTHING test for Selenium 5.0.0
    [Teardown]                  Close All Browsers
    Register Keyword To Run On Failure  NOTHING
    Test Case Setup             https://www.quackit.com/html/codes/html_popup_window_code.cfm
    Select Frame                //iframe[@name='result1notfound']

## Error messages and additional information

==============================================================================
NONE test for Selenium 5.0.0                                          [ WARN ] Keyword 'NONE' could not be run on failure: No keyword with name 'NONE' found.
| FAIL |
Element with locator '//iframe[@name='result1notfound']' not found.
------------------------------------------------------------------------------
Python None test for Selenium 5.0.0                                   [ WARN ] Keyword 'None' could not be run on failure: No keyword with name 'None' found.
| FAIL |
Element with locator '//iframe[@name='result1notfound']' not found.
------------------------------------------------------------------------------
NOTHING test for Selenium 5.0.0                                       | FAIL |
Element with locator '//iframe[@name='result1notfound']' not found.
------------------------------------------------------------------------------
NONEtest                                                              | FAIL |
3 critical tests, 0 passed, 3 failed
3 tests total, 0 passed, 3 failed
==============================================================================
Output:  c:\Robot_Output\output.xml
Log:     c:\Robot_Output\log.html
Report:  c:\Robot_Output\report.html

Process finished with exit code 3

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...
No WARN flags and same behavior regardless if NONE, None, or NOTHING is used. This only started happening after upgrading from 4.5.0 to 5.0.0

## Environment

Browser: Chrome Version 88.0.4324.182
Browser driver: Chromedriver Version 88.0.4324.182
Operating System: Windows 10
Libraries
- Robot Framework: Version 3.2.2
- Selenium: Version 3.141.0
- SeleniumLibrary: 5.0.0
- Interpreter: PyCharm 2020.3

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment]
In SeleniumLibrary 5.0 release, we did move to use [typehints](https://docs.python.org/3/library/typing.html) and gave the argument conversion to Robot Framework. Robot Framework is more strict on the how the arguments are converted and conversion are explained in the [user guide](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-conversions). I see that we have at least bug in the keyword documentation, in the [run on failure](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Run-on-failure%20functionality) docs. Have you seen other places where the documentation is not correct?

**Comment by aaltat** [comment]
Page Should Contain should be also looked with this issue.

**Comment by aaltat** [comment]
I looked trough the code, this is a bug in SeleniumLibrary side and there is hole in the acceptance tests too.
