### ISSUE TITLE
Support Edge/Linux config

### ISSUE THREAD

**Issue by remontees** [robotframework/SeleniumLibrary#1697]
# Feature requests

[As MsEdgeDriver is now available for Linux OS](https://developer.microsoft.com/fr-fr/microsoft-edge/tools/webdriver/), it would be great if the Edge/Linux configuration was taken into account in addition to Edge/Windows configuration.

Thanks a lot,

Best regards

**Comment by zahed3795** [comment]
How can I add Desired Capabilities in MsEdge Driver?

${chrome_options} =     Evaluate  sys.modules['selenium.webdriver'].DesiredCapabilities.INTERNETEXPLORER    sys,    selenium.webdriver
    Call Method    ${edge_options}    add_argument    --no-sandbox
    ${options}=     Call Method     ${edge_options}    to_capabilities
    Open Browser    ${url}      edge      desired_capabilities=${options}

I am getting an error that "add_argument is not a function", but same working properly with chrome driver.

Thanks a lot,

**Comment by emanlove** [comment]
AFAIK, this as been working for a while. If someone sees otherwise fell free to raise a new issue.
