### ISSUE TITLE
Https connection causing SSL_ERROR

### ISSUE THREAD

**Issue by antomelvin** [robotframework/SeleniumLibrary#1699]
Hello, I am using the selenium library and it seems like there is a error due to the SSL Certificate (img attached).  I added the following line in my code:

**Open Browser  about:blank  headlesschrome  options=add_argument("--no-sandbox");add_argument("--ignore-certificate-errors");add_argument("--ignore-ssl-errors");add_argument("--disable-popup-blocking")**       
![image](https://user-images.githubusercontent.com/38493350/110657206-ede76180-81c0-11eb-9cec-e8fa1ffc271f.png)
  

 I still seem to be getting the error.  The URL is called from another page object.  The tests worked fine with http and they recently introduced https to our project and that's when the tests started to fail. After reading about it, I figured you could add these arguments to circumvent the SSL issue but it still doesn't seem to work.

**Comment by HelioGuilherme66** [comment]
I cannot reproduce with this setup:
```
Windows 10
Python 3.9.1
Chrome  89.0.4389.82
ChromeDriver 89.0.4389.23

C:\>pip show robotframework-seleniumlibrary
Name: robotframework-seleniumlibrary
Version: 4.5.0
Summary: Web testing library for Robot Framework
Home-page: https://github.com/robotframework/SeleniumLibrary
Author: Tatu Aalto
Author-email: aalto.tatu@gmail.com
License: Apache License 2.0
Location: c:\users\helio\appdata\roaming\python\python39\site-packages
Requires: robotframework, selenium, robotframework-pythonlibcore
Required-by: rpaframework, robotframework-seleniumtestability

C:\>pip show robotframework
Name: robotframework
Version: 4.0b3
Summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
Home-page: http://robotframework.org
Author: Pekka Klärck
Author-email: peke@eliga.fi
License: Apache License 2.0
Location: c:\users\helio\appdata\roaming\python\python39\site-packages
Requires:
Required-by: rpaframework, robotframework-seleniumlibrary, robotframework-screencaplibrary, robotframework-sapguilibrary, robotframework-requests
```
Test File:
```robot
*** Settings ***
Suite Teardown    Close All Browsers
Library           SeleniumLibrary

*** Test Cases ***
Tries to Open Browser
    Open Browser    about:blank    headlesschrome    options=add_argument("--no-sandbox");add_argument("--ignore-certificate-errors");add_argument("--ignore-ssl-errors");add_argument("--disable-popup-blocking")

```

**Comment by antomelvin** [comment]
CommonSetup.txt

```
*** Settings ***
Library  SeleniumLibrary

*** Variables ***

*** Keywords ***
#Test cases to setup the browser
Begin Web Test
    Open Browser  about:blank  headlesschrome  options=add_argument("--no-sandbox");add_argument("--ignore-certificate-errors");add_argument("--allow-insecure-localhost");add_argument("--ignore-ssl-errors");add_argument("--disable-popup-blocking")
    # Maximize Browser Windo


End Web Test
    Close Browser
```

LandingPage.txt

```
*** Settings ***
Library  SeleniumLibrary

*** Variables ***


*** Keywords ***
#Only tests if the UI can be loaded
Load
    Go To  https://localhost:1128/WebUI/

Verify Page Loaded
    Wait Until Page Contains UI Login`
```

**The site is run locally on my machine.
The site uses a self-signed certificate**

**Comment by HelioGuilherme66** [comment]
@antomelvin You did not show us the system or environment versions.
You now provide another test file that does not have relation with your reported error.
We cannot reproduce errors, when the sites or app under test is not public.

Self signed certificates are known to be limited. You probably have to fake a valid URL on your hosts file. For example to access,
https://myfake.domain.net/
`127.0.0.1    myfake.domain.net`

**Comment by aaltat** [comment]
I guess we can close this issue?

**Comment by antomelvin** [comment]
Hello, I figured out the problem. The site when redirected changed it's port number (this is how the site enforces HTTPS), this is why the selenium library was not able to make the handshake. Changing the URL fixed the issue. 
Thanks again for you time!
Yes I will close this issue.
