### ISSUE TITLE
Safari

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#170]
Has anyone looked into using Safari webdriver testing with RIDE?  I was looking at http://code.google.com/p/selenium/wiki/SafariDriver and it sounds like it has begun to be integrated into the selenium package, though I am unclear in how I should implement this functionality.  Any ideas or insight?

**Comment by emanlove** [comment]
Please ask this question within the [robotframework-users group](http://groups.google.com/group/robotframework-users).

**Comment by zmlpjuran** [comment]
See issue #243
