### ISSUE TITLE
Handle alert having an issue with chrome browser(89.0.4389.82)

### ISSUE THREAD

**Issue by sasikumar-sekar** [robotframework/SeleniumLibrary#1701]
Trying to automate zoom meeting application with robot framework selenium2library.

Got stuck with handling alert.

Code:

*** Settings ***
Library    Selenium2Library
Variables    configuration.yaml

*** Test Cases ***

Testcase1 - SeleniumTestCase For Zooms
    Create Webdriver    Chrome    executable_path=/Users/sasik/Documents/chromedriver/chromedriver
    Go To    https://zoom.us/join
    Wait Until Element Is Visible    xpath=//*[@id="join-confno"]
    ${present}=  Run Keyword And Return Status    Element Should Be Visible   xpath=//*[@id="join-confno"]
    Run Keyword If    ${present}    Input Text    xpath=//*[@id="join-confno"]    text=XXX XXX XXXX
    Run Keyword If    ${present}    Click Element    xpath=//*[@id="btnSubmit"]
    Sleep  5
    **Handle Alert     DISMISS**
    Sleep  10
    ${res} =    Get Locations
    Log    ${res}
    ${res} =    Get Window Handles
    Log    ${res}
    Wait Until Element Is Visible    xpath=//div[contains(@role, 'button') and contains(text(),'Launch Meeting')]
    Click Element    xpath=//div[contains(@role, 'button') and contains(text(),'Launch Meeting')]
    Wait Until Element Is Visible    xpath=//*[contains(text(),'Join from Your Browser')]
    Click Link    xpath=//*[contains(text(),'Join from Your Browser')]
    Page Should Contain    Join a Meeting
    Wait Until Element Is Visible    xpath=//*[@id="inputname"]
    Run Keyword If    ${present}    Input Text    xpath=//*[@id="inputname"]    text=sasik
    Click Element    xpath=//div[contains(@role, 'button') and contains(text(),'Launch Meeting')]

**Comment by aaltat** [comment]
Selenium2Library is not supported anymore, migrate to SeleniumLibrary. If you can reproduce the issue with latest SeleniumLibrary, we can reopen the issue.
