### ISSUE TITLE
Wrong number of arguments Error for Open Browser

### ISSUE THREAD

**Issue by tusharkr18** [robotframework/SeleniumLibrary#1707]
Hello,

I am transitioning from Selenium2Library to SeleniumLibrary. While running the test I am getting below error
java.lang.IllegalArgumentException: wrong number of arguments

Steps
1- Created Maven Project
2- Added Dependency for robotframework, seleniumlibrary and robotframework-maven-plugin
3- Wrote Simple Test case to Open Browser

*** Settings ***
Library    SeleniumLibrary   
Default Tags    contactpage-smoke     

*** Test Cases ***
Test_Case_01
	[Documentation]    Test Case to Validate the Google Page

	[Tags]    smoke-p2
    Open Browser  ${url}  chrome 
    
*** Variables ***
${url}    www.google.com    #Path    

4- While running the test, getting error message- wrong number of arguments
## Environment

Browser: Chrome 89
Browser driver: chrome 89
Operating System: Mac 10
Libraries
- Robot Framework: Version 3.2.2
- Selenium: Version 3.141.0
- SeleniumLibrary: Version 5.1.1
- Interpreter: Name and version Java version: 15.0.2  

Attaching the Trace Logs as well
[trace.txt](https://github.com/robotframework/SeleniumLibrary/files/6175701/trace.txt)

**Comment by aaltat** [comment]
I am not familiar with Maven, but what is the intrepeter  the project is using? Python 3.6+ or Jython? If it's Jython or Python 2, that is not anymore supported by this project.  If it's Python 3.6+, then you would need to find out the exception from Python side.

But if you are using Jython, then you might be better off with https://github.com/MarketSquare/robotframework-seleniumlibrary-java

**Comment by tusharkr18** [comment]
Hello Aaltat,
Thanks for responding. I have checked and seems like Java Error. 
This error comes when trying to execute via maven command. If I run the robot . command or either from Eclipse (without Maven Configuration) I am not getting the error.

I have noticed one more error/warning for which it was mentioned to be corrected in Jython 2.7.2 ticket- https://github.com/OpenRefine/OpenRefine/issues/1741

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.io.StreamIO (file:/Users/deebasanober/.m2/repository/org/robotframework/robotframework/3.2.2/robotframework-3.2.2.jar) to field java.io.FilterOutputStream.out
WARNING: Please consider reporting this to the maintainers of org.python.core.io.StreamIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
==============================================================================

**Comment by aaltat** [comment]
It looks like you are using Jython, but Jython is not supported anymore by this project. Instead you should look https://github.com/MarketSquare/robotframework-seleniumlibrary-java or move to Python 3.6+ side. 

Because you are using not supported interpreter, I am going to close this issue.
