### ISSUE TITLE
How can I wirte a script to start and stop VNC in selenium script 

### ISSUE THREAD

**Issue by sskhan** [robotframework/SeleniumLibrary#171]
Hi I am writing selenium script with Robot Framework. Right now I am first starting the vnc server and then launch the test case. Is there any way that I can automate the start and stop of VNC along with test case

**Comment by peritus** [comment]
This is probably not in the scope of this library. Good starting point is probably https://code.google.com/p/robotframework/wiki/OperatingSystemLibrary
