### ISSUE TITLE
Execute JavaScript has wrong type definition

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#1711]
Execute JavaScript does not work if there is a test like this:
```
    ${body_webelement}  Get WebElement  css:body
    ${tag_name}  Execute Javascript
    ...  return arguments[0].tagName;
    ...  ARGUMENTS
    ...  ${body_webelement}
   ```

**Comment by rasjani** [comment]
@aaltat This could probably be closed already or is there something that still needs to be addressed ?

**Comment by aaltat** [comment]
Yes, I though GitHub does autoclosing, but in this case not.
