### ISSUE TITLE
Built in Capture Screenshot does not use it's own version

### ISSUE THREAD

**Issue by Harm10** [robotframework/SeleniumLibrary#1715]
I executed SeleniumLibrary.Open Browser in RIDE which gave an error. Part of the error handling is apparently to Capture a screenshot (I have not coded that) but this in turn gives an error when other packages are installed that have the same command (like RPA.Browser).
I can only resolve this by inactivating RPA.Browser.
If this action is built in why does Selenium not use it's own command?

**Comment by aaltat** [comment]
This is because conflict in the keyword names and because SeleniumLibrary uses Robot Framework BuiltIn.Run Keyword keyword to run the keyword. In this case Robot Framework does the choice based on the library search order. But there is a easy fix, prefix the default keyword with `SeleniumLibrary`

**Comment by aaltat** [comment]
With second tough, fix is not that easy, because library name is not always `SeleniumLibrary`, because it can be changed with `WITH NAME` syntax in library import.

**Comment by aaltat** [comment]
Had a second idea, if run on failure keyword is `capture page screenshot` (case insensitive) then we run it as method and not as keyword trough Robot Framework.  This is somewhat backwards incompatible for two reasons:
1) The log.html shows little bit different. If the `capture page screenshot` is used the screenshot is embedded in the same log message where the failure happens. This actually looks better in the log and might be easier to understand.
2) Using the library search order does not anymore work when deciding which keyword to run, when keyword name is `capture page screenshot`. In other keywords will still work.

**Comment by Harm10** [comment]
Just to be sure: this will be fixed in a next version?

**Comment by aaltat** [comment]
That is the plan. You can already try this one by installing from the source, by running: `pip install git+https://github.com/robotframework/SeleniumLibrary.git`

**Comment by Harm10** [comment]
I'd rather wait on the official next release. When is it planned?

**Comment by aaltat** [comment]
Well, usually there is no clear deadline, @rasjani do you have an idea?

**Comment by Harm10** [comment]
@aaltat @rasjani Any response?

**Comment by Harm10** [comment]
Another try: @aaltat @rasjani Any response?
