### ISSUE TITLE
Selenium Open Browser inside Network Interface Namespace fails

### ISSUE THREAD

**Issue by triblex** [robotframework/SeleniumLibrary#1724]
## Steps to reproduce the issue
I've created a network interface namespace with:
```
    sudo ip netns add net-$name
    sudo ip link set dev $interface netns net-$name
    sudo ip netns exec net-$name ip link set dev $interface up
    sudo ip netns exec net-$name ip address add 192.168.0.1/24 dev $interface
```
Then i create a simple test that just opens a browser with seleniumLibrary in robotframework:

```
*** Settings ***
Documentation   Test browser access in netns

Library   OperatingSystem
Library   SeleniumLibrary

Force Tags  test_123

*** Test Cases ***
Test Browser In Netns
    Open Browser    192.168.0.100  browser=ff
    Close Browser
```
I run the test script inside the netns.

## Error messages and additional information

```
WebDriverException: Message: Service geckodriver unexpectedly exited. Status code was: 69 
  
Traceback (most recent call last):
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/__init__.py", line 492, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/mci/.local/lib/python3.8/site-packages/robotlibcore.py", line 103, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 293, in open_browser
    return self._make_new_browser(
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 324, in _make_new_browser
    driver = self._make_driver(
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 716, in _make_driver
    driver = self._webdriver_creator.create_driver(
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py", line 83, in create_driver
    return creation_method(
  File "/home/mci/.local/lib/python3.8/site-packages/SeleniumLibrary/keywords/webdrivertools/webdrivertools.py", line 199, in create_firefox
    return webdriver.Firefox(
  File "/home/mci/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/mci/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/mci/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
```
## Expected behavior and actual behavior

- When i just run the test script inside the netns (as normal user) with `robot --loglevel trace tests/01__netns_browser.robot`, i see the above error.
- Running this outside the netns works just fine. Firefox opens and goes the the webpage provided to the `Open Browser` keyword.
- Running anything else than browser depending tests works just fine. - I'm also running api tests that go through without problems using the same ipaddress as the browser needs to use.
- Running the `OperatingSystem` keyword `Run  firefox 192.168.0.100` instead of the `Open Browser` keyword opens the browser and goes the the webpage without problem, so it seems to be a strictly Selenium based problem?

I was of course expecting the selenium tests to run as outside the netns just like the other tests.

## Environment

Browser: Mozilla Firefox 87.0
Browser driver: GeckoDriver 0.29.0
Operating System: Linux, Ubuntu 20.04
Libraries
- Robot Framework: 4.0 (Python 3.8.5 on linux)
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.1
- Editor: Visual Studio Code 1.55.2

**Comment by aaltat** [comment]
Most likely this is problem in underlying Selenium or Geckodriver. To test it, put this in a `.py` file
```
from selenium import webdriver

#This example requires Selenium WebDriver 3.13 or newer
with webdriver.Firefox() as driver:
    driver.get("192.168.0.100")

```
And run with the Python where you have RF and SeleniumLibrary installed.

**Comment by rasjani** [comment]
It would be helpful to also get the geckodriver.log from failed run. 

I havent had any exposure to netns and have no idea how it's usage is typically done  but so this is just brainstorming  - does netns require some special handling regarding on how applications end up using it ? Reason why im asking is that if you "just" use `Open Browser` keyword, geckodriver will bind itself into random port on 127.0.0.1/localhost ..  Maybe this can cause issues with python Selenium communicating with geckodriver or geckodriver having issues either binding into network device or communicating with internet  and/or Selenium .. 

If its anyway related to above, experimenting with creating a webdriver w/ `Create Webdriver`  and passing service_args with --host flag could be helpful.

**Comment by triblex** [comment]
I missed that when creating the namespace, the loopback was not automatically added and up'ed. \
Once i added that with `ip netns exec net-$name ip link set dev lo up` there was no issues with selenium. So yes @rasjani your brainstorm reply had the answer, as geckodriver was trying to bind itself to a port on 127.0.0.1 but was not able to as lo was never up.

The only logs from GeckoDriver was `geckodriver: error: Cannot assign requested address (os error 99)`, so this was a bit frustrating to debug. Good news is that selenium was not at fault. Thanks for the quick replies!
