### ISSUE TITLE
Provide support for waiting for a value in a textarea element

### ISSUE THREAD

**Issue by nathanhannig** [robotframework/SeleniumLibrary#1726]
# Feature request

While evaluating RobotFramework + SeleniumLibrary I found a use case where
the value of a textarea is changed and I would like to wait until the value matches some expected text.

Generally, you would expect Wait Until Element Contains would fill this scenario. But issue #167 showcases that textareas behave a little differently.

I believe that textareas would need their own Wait Until keyword to handle the .value property they contain.

**Comment by nathanhannig** [comment]
I think the following should be added to match Textarea support to Element support

Wait Until Textarea Contains - wait_until_textarea_contains
Wait Until Textarea Does Not Contains - wait_until_textarea_does_not_contain
Wait Until Textarea Value Is - wait_until_textarea_value_is
Wait Until Textarea Value Is Not - wait_until_textarea_value_is_not

Textarea Should Not Contain - textarea_should_not_contain
Textarea Value Should Not Be - textarea_value_should_not_be

**Comment by nathanhannig** [comment]
I will work on a PR for this

Wait Until Textarea Contains - wait_until_textarea_contains
Wait Until Textarea Does Not Contains - wait_until_textarea_does_not_contain
Wait Until Textarea Value Is - wait_until_textarea_value_is
Wait Until Textarea Value Is Not - wait_until_textarea_value_is_not

**Comment by emanlove** [comment]
This can be accomplished with existing Wait For Expected Condition keyword. Closing this issue as such.
