### ISSUE TITLE
I use  keysord : Select Window  and occur error information :No keyword with name 'Select Window' found.

### ISSUE THREAD

**Issue by ZZHHogan** [robotframework/SeleniumLibrary#1729]
# For issues

I use  keysord : Select Window  and occur error information :No keyword with name 'Select Window' found.
and my code is :
    Open Browser .....
    .... ....
    ${titles}    Get Window titles
    ${title2}    Get From List    ${titles}
    ${title1}    Get From List    ${titles}
    Select Window    title=${title2}
    Sleep 2
    Select Window    title=${title1}

## Error messages and additional information

Error messages :
      FAIL : No keyword with name 'Select Window' found.

## Environment

Browser: Chrome 90.0
Browser driver: chromedriver
Operating System: win10
Libraries
- Robot Framework: 4.0.1
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.3 （and I had used Selenium2Library ,too.And finally using SeleniumLibrary）
- Interpreter: python 3.7

 And  can you tell me how I can fix this problem ? I hope to select window in browser smoothly，Thanks！

**Comment by aaltat** [comment]
Keyword is removed, use https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Switch%20Window
