### ISSUE TITLE
How to verify text node in shadow root with robot framework keyword

### ISSUE THREAD

**Issue by totmania** [robotframework/SeleniumLibrary#1730]
I want to verify text node "20 Meters" in shadow root with robot framework keyword so this is html tag

     `<div class="styles__RadiusUnitLabel-sc-1jm4361-1 enqpSw">20 Meters</div>``

I try keyword with this

`Wait until element is visible   dom:document.getElementById("react-root").shadowRoot.querySelector('div[class*="styles__RadiusUnitLabel"]').innerText`

and get this error from robot framwork 

**`AttributeError: 'str' object has no attribute 'is_displayed'`**

How should to verify text node for this problem ?

This is picture for more information
[https://drive.google.com/file/d/1IeucYx7XLpFnGfhzOgi-7Z31qwhMXiUZ/view?usp=sharing](url)
[https://drive.google.com/file/d/1iz74qOZoEZA1KQ5ibiOUsHLEyJFiLh9q/view?usp=sharing](url)

**Comment by aaltat** [comment]
Your query returns a text, but it should return a WebElement and therefore keyword fails. If you return innerText attribute keyword will most likely work. 

Because this is a support request and this issue tracker is reserved only for bugs and enhancements, I will close the issue.

**Comment by totmania** [comment]
> Your query returns a text, but it should return a WebElement and therefore keyword fails. If you return innerText attribute keyword will most likely work.
> 
> Because this is a support request and this issue tracker is reserved only for bugs and enhancements, I will close the issue.

Can you tell me which keyword that I should to use for this
