### ISSUE TITLE
Download file in headless mode

### ISSUE THREAD

**Issue by saimadao** [robotframework/SeleniumLibrary#1731]
download in headless mode need to set download path manually.
I have added below code into browsermanagement.py and it works fine

    @keyword
    def set_headless_download_path(self, path):
        """Set headless browser download path.

        Create by LMY, unofficial
        """
        params = {'behavior': 'allow', 'downloadPath': path}
        self.driver.execute_cdp_cmd('Page.setDownloadBehavior', params)

**Comment by aaltat** [comment]
This is more of support question to Selenium or browser side. This issue tracker is reserved to bugs and feature requests and therefore issue will be closed. You could ask your question from the community: https://github.com/robotframework/SeleniumLibrary#community

**Comment by saimadao** [comment]
OK. 
However, this issue has been submit in selenium git project in 2018, but unfortunately, still no official solution for this issue.
And the following are the issue tracker in selenium project
https://github.com/seleniumhq/selenium/issues/5159
https://github.com/Codeception/Codeception/issues/5518
