### ISSUE TITLE
Selenium for Webview2

### ISSUE THREAD

**Issue by Bhavnasewani** [robotframework/SeleniumLibrary#1732]
Hi Team,

I have an application that is developed using Webview2 .NET component. Basically, we have a desktop container for our Angular based app. 
This is run using the Microsoft edge (chromium). 
I want to use Selenium and edge drivers in Robot Framework for automation testing of this application.

When I referred the documentation around webview2, I saw that we need to communicate to the driver that we are driving our web application using Webview2. Please check the link below:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

I want to similar testing using robot framework so was wondering how could we communicate to the edge driver and run tests

Any help on this would be appreciated
Let me know if any further information is required from my end

**Comment by Bhavnasewani** [comment]
Can selenium library be upgraded to have the options for setting edge options similar to the below code:

    ${options}=   Get Edge Options 
    ${options.use_chromium}=    Set Variable   True
    ${options.use_webview}=    Set Variable   True
    ${options.binary_location}=    Set Variable   ${WebView_APP}  #new one as we need to communicate edge we are using 
                                                                                                        webview2 application
    # Open Browser with options
    Open Browser    ${MyWebsite}     Edge   options=${options}

**Comment by Bhavnasewani** [comment]
@aaltat Could you please check on this request, Appreciate your help in advance!

**Comment by aaltat** [comment]
This issue tracker is reserved for bugs and enhancement request. For this type of problem solving cases, it is better turn on https://github.com/robotframework/SeleniumLibrary#community  

Closing issue.
