### ISSUE TITLE
Choose File: file does not exist on the local file system

### ISSUE THREAD

**Issue by rkefi84** [robotframework/SeleniumLibrary#1737]
Hi guys,
I am getting this file not found error on choose file in both cases with ${CURDIR} or ${EXECDIR}
The Get File keyword finds the file in both cases

Robot Framework: Version 4.0.1
SeleniumLibrary: Version 5.1.3

Both steps in my test 
`Get File    ${CURDIR}${/}people.csv`
`Upload 84 users csv file ${CURDIR}${/}people.csv`

Error in log :

`InvalidArgumentException: Message: invalid argument: File not found : file /Users/rkefi/Documents/Work/unified-admin-e2e/Tests/E2E/people.csv`

<img width="1361" alt="Screen Shot 2021-08-03 at 9 38 10 AM" src="https://user-images.githubusercontent.com/55718411/128025344-184d9a20-4cda-486a-abdb-e5c13e19473f.png">

**Comment by aaltat** [comment]
Interesting, could you run test with `--loglevel trace` set from command line and post the stack trace.  Also could  you show how you open the browser?

**Comment by rkefi84** [comment]
Well maybe you gave me a hint.
Today morning i changed the open browser keyword to replace it with create webdriver and then go to url
I will try now the same with Open Browser and i will enabled the trace loglevel too

**Comment by rkefi84** [comment]
This is how i open the browser now
`${chromedriver_path}=   chromedriversync.Get Chromedriver Path`
    `Create Webdriver    Chrome   executable_path=${chromedriver_path}`
    `Go to  ${goToAdminBaseUrl}/${accountKey}`
    `#open browser        ${goToAdminBaseUrl}/${accountKey}     ${browser}        remote_url=${RemoteURL} ` `desired_capabilities=${capabilities}`

**Comment by rkefi84** [comment]
@aaltat So i get the same error with Open Browser too
Here is the screenshot with the trace level enabled
<img width="539" alt="Screen Shot 2021-08-03 at 12 03 09 PM" src="https://user-images.githubusercontent.com/55718411/128048541-8ff178ec-93cc-4e5e-b88d-6d10e19cc1d2.png">
<img width="1656" alt="Screen Shot 2021-08-03 at 12 03 31 PM" src="https://user-images.githubusercontent.com/55718411/128048556-3e12d907-e585-4e25-b054-ddab6bececbc.png">

**Comment by aaltat** [comment]
Based on the screenshot you file path is incorrect. The `${file}` variable contains `file /Users/...` but the it should contain `/Users/...`

**Comment by rkefi84** [comment]
But i am not setting that anywhere
I have this `${CURDIR}/people.csv`
I dont know from where it come
Question i am running inside a python virtual env, could it be that the issue?

**Comment by rkefi84** [comment]
My script looks like this
`@{csvContent}=      read_csv_file_to_list  ${CURDIR}${/}people.csv`
    `${userUploadedEmailList}=      Create List`
    `Navigate to ${peopleAppIcon} application`
    `Navigate to the users page`
    `Users page renders properly with all the elements`
    `Click add new user button`
    `New user wizards renders properly and displays the first step`
    `Check single product in the licenses table`
    `Click Element       ${step1NextButton}`
    `New user wizard second step renders properly`
    `Get File    ${CURDIR}${/}people.csv`
    `Upload 84 users csv file ${CURDIR}/people.csv`
    
    This is how the test looks like
    If you see at the beining i am calling a keyword from the CSVLibrary with the same file path and its able to empty the file and then fill it with data

**Comment by rkefi84** [comment]
I think i found from where that file comes from its the word in the keyword just before the path
Indentation issue looks like :D let me fix and test again

**Comment by rkefi84** [comment]
It passed!

**Comment by rkefi84** [comment]
Many thanks for your help!
