### ISSUE TITLE
Suggestion for clarifying documentation around Timeouts

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#1738]
Dave Martin and I were discussing some wording and understanding about timeouts. He has the following suggestions for some clarifying sentences to the documentation to make clear (changes in **bold**).

> SeleniumLibrary contains various keywords that have an optional timeout argument that specifies how long these keywords should wait for certain events or actions. These keywords include, for example, Wait ... keywords and keywords related to alerts. Additionally Execute Async Javascript. Although it does not have timeout, argument, uses a timeout to define how long asynchronous JavaScript can run.
> 
> The default timeout these keywords use can be set globally either by using the Set Selenium Timeout keyword or with the timeout argument when importing the library. **If no default timeout is set globally, the default is 5 seconds. If None is specified for the timeout argument in the keywords, the default is used.** See time format below for supported timeout syntax.
> 

I am temporarily recording/storing his suggestion here as to not lose it out of Slack. I'll submit a pull request sometime in the future.

**Comment by aaltat** [comment]
I like it, how about PR?

**Comment by emanlove** [comment]
Working on one now .. need to review Contributing docs to see what I need to do to submit a "complete" pull request.
