### ISSUE TITLE
SeleniumLibrary modules not loaded correctly. Ride: 1.7.4.1, Python: 3.6.4, robot-selenium: 4.5.0 does not load the methods after "U" alphabet

### ISSUE THREAD

**Issue by AparnaaMariappan** [robotframework/SeleniumLibrary#1742]
**## Steps to reproduce the issue
1. Launch RIDE
2. Create a test case
3. Open browser
4. click some element
5. give "wait until page contains element"

Expected Result:
SeleniumLibrary.waituntilpagecontains keyword should be displayed in BLUE

Actual Result:
The keywords upto SeleniumLibrary.Unselect is only loaded or displayed. The "wait" keywords are not loaded.

Test data:
I used RIDE version 1.7.4.2, Python version: 3.6.4, robotframework-seleniumlibrary version: 4.5.0.

I degraded the robotframework-seleniumlibrary version and it worked.**

I couldn't attach screenshot as it is blocked by my organization. Thanks

**Comment by aaltat** [comment]
Ride has some development/beta versions that support Robot Framework dynamic library API and SeleniumLibrary is one of the dynamic library API users. This is most likely a bug with RIDE and not with SeleniumLibrary and therefore I am going to close this issue.

**Comment by HelioGuilherme66** [comment]
@AparnaaMariappan You should go to the RIDE project page and see how to install the development version from`master` .
It is a work in progress for some RF features, but at least the documentation is working.
