### ISSUE TITLE
SessionNotCreatedException: Message: session not created from timeout: Timed out receiving message from renderer: 600.000   (Session info: chrome=93.0.4577.63)

### ISSUE THREAD

**Issue by elveera0491** [robotframework/SeleniumLibrary#1743]
SessionNotCreatedException: Message: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=93.0.4577.63)

Seem to be getting this error for a while now while running our robotframework based test scripts using selenium: 3.141.0. When I go into the VM and check for the package everything seems to be up to date. Our Jenkins jobs keep failing because of the above. Any pointers on why this occurs and how to resolve will be very helpful.

**Comment by aaltat** [comment]
Please see https://github.com/robotframework/SeleniumLibrary#community for how reach community in this type of problems. I am closing this issue.
