### ISSUE TITLE
Selenium can't find elements with IE driver 3.150.2

### ISSUE THREAD

**Issue by oferdan** [robotframework/SeleniumLibrary#1745]
Hi,

I'm facing issues while running tests with IE driver 3.150.2. - Selenium can't find any elements.
Browser is opened with "Open browser" KW. There are no synchronization issues (element not clickable etc.)
When I'm using 3.149 it is fine, same with 3.150.1 
(But I want to use the latest version, because when using the latest libraries with older drivers there are tmp files left in %USERPROFILE%\AppData\Local\Temp or 3.150x driver is getting stuck sometimes on initial webdriver page.)

Browser: IE 20H2
Browser driver: IE driver (3.150.2 - x86)
Operating System: Windows 10 Enterprise build 19042.1237
Libraries
- Robot Framework: 4.1.1
- Selenium: 3.141
- SeleniumLibrary: 5.1.3
- Interpreter: Python 3.7

Anybody else is having this issue?

Thanks for investigation

**Comment by aaltat** [comment]
This type of support request are answered faster in the community channels: https://github.com/robotframework/SeleniumLibrary#community

Also because this is not feature request or bug report, I am going to close the issue.
