### ISSUE TITLE
Press Keys causes two key ups for selenium special keys

### ISSUE THREAD

**Issue by MrBIN89** [robotframework/SeleniumLibrary#1748]
## Steps to reproduce the issue
`Press Keys` keyword execution with special selenium keys, for example `Press Keys css:locator BACKSPACE`, brings two _key_up_ events unexpectedly. That causes two letters removal instead of one in my case.
![изображение](https://user-images.githubusercontent.com/47885244/136017353-f3676809-63df-4e08-83d5-180343cf20be.png)

Though in case the selenium key code is used there is no event duplicates, works like a charm
![изображение](https://user-images.githubusercontent.com/47885244/136019241-e5abcd5b-78f8-4a8c-8ac4-0d9318fc116e.png)

## Expected behavior and actual behavior

I was expecting that the `Press Keys` should work consistently for both scenarios, send key_down and key_up for once only:
1. `Press Keys    css:locator    BACKSPACE`
2. `Press Keys    css:locator    \ue003`

## Environment

Browser: Chrome 90.0.4430.72
Browser driver: ChromeDriver 90.0.4430.24
Operating System: Windows 10
Libraries
- Robot Framework: 4.0.3
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.3
- Interpreter: Python 3.6

**Comment by MrBIN89** [comment]
PS: W3C chromedriver mode is set to False in the example above.

**Comment by emanlove** [comment]
Retesting with latest versions (Robot Framework v7.1.1, Selenium v4.26.1, SeleniumLibrary 6.6.1) this is not seen. I see in the screenshots above where there are two selenium webdriver calls to the keys endpoint. The current implementation for press keys and the underlying action chains acts differently and sends a single call to the actions endpoint with a key down and key up.

Anyone experiencing similar issues should upgrade to the latest versions of the library and selenium to resolve. Closing this issue as such.
