### ISSUE TITLE
Why not pin the Browser library instead of this one at the top of Robot Frameworks pinned Github repos?

### ISSUE THREAD

**Issue by wlad** [robotframework/SeleniumLibrary#1751]
It seems this project is not maintained any more(?). Last updates were months ago. I think the reason is that recently all the contribution goes into the [Browser](https://github.com/MarketSquare/robotframework-browser) library(?) So why not pin the Browser library at the top instead (or in addition to SeleniumLibrary)?

If the Browser library is meant to replace SeleniumLibrary in the long term, may be there should be a note about this in the README otherwise new users could get a bad impression of Robot Framework when they stumble over an 'outdated' library pinned at the top.

![grafik](https://user-images.githubusercontent.com/64201310/141703759-1cab3ec8-2225-4afd-8174-2f776dbf4ee6.png)

**Comment by pekkaklarck** [comment]
First of all, this library is still maintained. The reason Browser isn't pinned on the organization front page is that it is developed in a different organization.
