### ISSUE TITLE
Keywords which uses action chains are having a default 250ms timeout which cannot be overriden.

### ISSUE THREAD

**Issue by johnpp143** [robotframework/SeleniumLibrary#1768]
## The issue
Keywords that uses action chains like drag and drop and other mouse actions are using a default delay of 250ms. This causes these actions to be significantly slower.
In older chrome versions w3c actions were not default and hence these action chain class was not used.
In newer chrome versions these are used, but the keywords dont give an option to override this default timeout.
This becomes an issue for example when, we are doing multiple drag and drop in a page, each action takes about 500ms.
## Error messages and additional information
![image](https://user-images.githubusercontent.com/35929471/150853592-23fb2d15-fbdd-4fbc-84d3-636c1706adaa.png)
![image](https://user-images.githubusercontent.com/35929471/150853712-d132d6e7-ee03-42e8-b720-e76690b67f93.png)

## Expected behavior and actual behavior
Ability to override the default action chain duration for a faster running script

Current behaviour has no option to override 250ms default delay.

## Environment
Browser: Chrome 95
Browser driver: Chromedriver
Operating System: WIndows10
Libraries
- Robot Framework: 4.0.0
- Selenium: 4.1.0
- SeleniumLibrary: 5.1.3
- Interpreter: Python

**Comment by emanlove** [comment]
@johnpp143 If you have a pull request that would be helpful.
