### ISSUE TITLE
Plugin initialization randomly fails

### ISSUE THREAD

**Issue by dhilipsiva** [robotframework/SeleniumLibrary#1769]
This Plugin loading fails randomly and I am not able to establish a pattern why it is failing. Maybe I am doing something fundementally wrong with my plugin code. By any chance, is there something wrong that I doing with my plugin code?

## Steps to reproduce the issue

I have a plugin `MyPlugin.py` as like so:
```py
from SeleniumLibrary import SeleniumLibrary
from SeleniumLibrary.base import keyword
from SeleniumLibrary.keywords.browsermanagement import BrowserManagementKeywords


class MyPlugin(BrowserManagementKeywords):
    def __init__(self, ctx):
        BrowserManagementKeywords.__init__(self, ctx)
        # Some other init things

    @keyword
    def custom_open_browser(self, url: str, alias: str):
        # Do some Custom logic and the open_browser
        return self.open_browser(url=url, alias=alias, browser="chrome")
```

And this is what my robot scripts looks like:

```robot
*** Settings ***
Library           SeleniumLibrary    plugins=${CURDIR}/MyPlugin.py

*** Test Cases ***

Scenario: Custom Open Browser
    # Following Keyword is implemented in MyPlugin.py
    Custom Open Browser    https://example.com/    example
```

## Error messages and additional information

```
Error in file '/tmp/tmpagw8aw6l/tests/MyTest.robot' on line 2: Initializing library 'SeleniumLibrary' with arguments [ plugins=/tmp/tmpagw8aw6l/tests/MyPlugin.py ] failed: AttributeError: 'NoneType' object has no attribute 'info' 

Traceback (most recent call last): 

File "/usr/local/lib/python3.9/site-packages/SeleniumLibrary/__init__.py", line 484, 
    in __init__ plugin_libs = self._parse_plugins(plugins) 
File "/usr/local/lib/python3.9/site-packages/SeleniumLibrary/__init__.py", line 605, 
    in _parse_plugins plugin = importer.import_class_or_module(parsed_plugin.module) 
File "/usr/local/lib/python3.9/site-packages/robot/utils/importer.py", line 93, 
    in import_class_or_module imported, source = self._import_class_or_module(name_or_path) 
File "/usr/local/lib/python3.9/site-packages/robot/utils/importer.py", line 104, 
    in _import_class_or_module return importer.import_(name) 
File "/usr/local/lib/python3.9/site-packages/robot/utils/importer.py", line 265, 
    in import_ self._remove_wrong_module_from_sys_modules(path) 
File "/usr/local/lib/python3.9/site-packages/robot/utils/importer.py", line 283, 
    in _remove_wrong_module_from_sys_modules self._logger.info("Removed module '%s' from sys.modules to import "
```

## Expected behavior and actual behavior

I expect it to open a browser 

## Environment

Browser: chrome
Browser driver: chromedriver
Operating System: Ubuntu 20.04

Libraries:
robotframework = "^4.1.1"
robotframework-seleniumlibrary = "^6.0.0"

**Comment by emanlove** [comment]
My initial review there is nothing that I see that stands out as failing or "incorrect". A couple suggestions for next steps in debugging .. I might try a try, catch on the full plugin init to see if you can catch any thrown errors. And I might try using the [logging capabilities](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#librarycomponent) to see if I could output some more useful information.

Anything under the more init items that may be timing or network related? Also I would just do a sanity check on the machine that is running to verify the chrome and chromedriver aren't doing something silly. (You mentioned it works sometimes so this may be useless but its one of those things that I do often with a quick from selenium import webdriver;driver=webdriver.Chrome() for myself to level base my thinking and understanding and state of system).

**Comment by emanlove** [comment]
Also the latest version of the core is 4.1.3. With the dot release of .3 I would probably update that from ending .1 to the latest. I haven't checked the release notes but those point release are generally bug fixes so useful to try out.

**Comment by rasjani** [comment]
Didn't check but one scenario where this can happen is if there are multiple test suites with different parameters - something similar to this can happen. Afaik, RF does not reinit the already existing library and thus stuff like this can happen.

**Comment by dhilipsiva** [comment]
Thanks for all your input! :smile: 
I have refactored my plugin into a stand-alone library. And I am using `BuiltIn().get_library_instance("SeleniumLibrary")` to reference the SL instance. This seemed to have fixed the Issue. Will close this ticket.

**Comment by aaltat** [comment]
The deeper analysis is hard without knowing your plugin code and looking at your test data. My gut feeling says that rasjani is correct and you have multiple imports in your code and because of RF fuzzy logic in imports, something does not work as expected. 

The other option is that you plugin has something which cause loading plugin to fail, perhaps `__init__` does something which has delay or something.
