### ISSUE TITLE
Add Chrome Options keyword

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#1770]
# Feature requests
It may be nice to have a keyword for adding Chrome/Chromium Options instead of the current method of 

```robotframework
    ${options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys, selenium.webdriver
    Call Method    ${options}   add_argument    --window-size\=1920,1080
    Call Method    ${options}   add_experimental_option  useAutomationExtension  ${False}
    Create Webdriver  Chrome  chrome_options=${options}    executable_path=${driver_path}
 ```

**Comment by aaltat** [comment]
It is already possible with `Open Browser` keyword, see `options` argument.

**Comment by emanlove** [comment]
I should have read the current documentation before submitting!

I was thinking about clarifying by making readable the "Python object which is an instance of the Selenium options class" format which is what the string format is doing.
