### ISSUE TITLE
Add option to "highlight" elements during runtime.

### ISSUE THREAD

**Issue by Mordenak** [robotframework/SeleniumLibrary#178]
I was wondering if anyone's considered adding an option to "highlight" elements in the browser during runtime.

My thought would be something similar to QTP (for those who have used it) where it just highlights the element with a blue border when interacting with it.

I'm not sure what all would be involved, or what the implementation would look like, I'm just throwing out the idea.

Thanks,

**Comment by aaltat** [comment]
Closing issue due inactivity
