### ISSUE TITLE
Provides documentation for calling the seleniumLibrary using Python code 

### ISSUE THREAD

**Issue by Eatkarus** [robotframework/SeleniumLibrary#1781]
# Feature requests
Hiiiii!
I want to use Python to call the seleniumLibrary to build the test project, and I want to maintain it as code. But I searched in all the search engines, can find very few cases.
 I wonder if RobotFramework can support this feature? Looking forward to your reply, thank you!

**Comment by aaltat** [comment]
Did you see https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst

**Comment by emanlove** [comment]
Closing out this ticket as the extending documentation outlines calling SeleniumLibrary through Python. If there are any changes or improvements you see please recommend or submit a pull request.
