### ISSUE TITLE
Executing RobotFramework test cases from putty?

### ISSUE THREAD

**Issue by PriyaAn** [robotframework/SeleniumLibrary#179]
The test cases are kept in linux machine and i am trying to execute them from Windows machine using putty.But i am getting the an exception:

UL1                                                                   | FAIL |
WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: no display specified\n'

Kindly help me in resolving the issue,if possible?

**Comment by HelioGuilherme66** [comment]
I would use SSHLibrary to get the files from the Linux machine. (You can
even package them in a Zip file and unzip in windows),

If you really need to have Linux graphical windows you need to have putty
to forward X11, and a X11 windows server like XMing. This looks like a very
complicated setup.

Are the tests specific for Windows?

Helio

**Comment by PriyaAn** [comment]
Actually i want to execute the test cases on another machine(Linux) but from putty.The browser should be launched on the linux machine but the command for execution is being send from putty.
As of now if i execute from putty i am getting the above exception.

**Comment by HelioGuilherme66** [comment]
To troubleshoot that,
make sure that the graphical environment is working in the Linux machine,
this is run the tests from a local console. If that is working, then is
putty not correctly set.

There is a DISPLAY environment variable to tell Linux where windows should
be presented.

My guess is that roboframework is loosing context. (I do not even know if
it is possible to do what you want, but I'm not expert).

**Comment by rsq647** [comment]
you may try 'xvfb-run'

**Comment by just-be-dev** [comment]
It's probably because the linux box didn't have an active display and thus couldn't activate the webdriver. One method to get around this would be to test using the phantomjs webdriver which is headless. Otherwise you'll need to investigate X11 forwarding over an SSH tunnel.
