### ISSUE TITLE
Extending selenium2Library

### ISSUE THREAD

**Issue by anhvutnu** [robotframework/SeleniumLibrary#180]
Hi all,

I'm trying to extending slenium2Library by writing a class that extends KeywordGroup. The problem that I have is I don't quite understand the technique how to get the current browser in the cache by calling self._current_browser().

**Comment by ombre42** [comment]
What you need is get a reference to the current instance of Selenium2Library.

``` python
from robot.libraries.BuiltIn import BuiltIn
from Selenium2Library.keywords.keywordgroup import KeywordGroup

def _get_s2l():
    return BuiltIn().get_library_instance('Selenium2Library')


class Selenium2LibraryExt(KeywordGroup):

    def _run_on_failure(self):
        # required for on failure in this class to work - call Selenium2Library's on failure
        _get_s2l()._run_on_failure()

    def do_something(self):
        s2l = _get_s2l()
        webdriver = s2l._current_browser()
        ...
```

The other way is to extend Selenium2Library and import your library instead of Selenium2Library. Then self will refer to the correct instance.

**Comment by anhvutnu** [comment]
Thank you ! This is awesome.

**Comment by emanlove** [comment]
For more information on the method @ombre42 is suggesting see the section entitled ["Extending existing test libraries"](http://robotframework.googlecode.com/hg/doc/userguide/RobotFrameworkUserGuide.html#extending-existing-test-libraries) within the Robot Framework User's Guide.
