### ISSUE TITLE
Any estimated time of complete for the Selenium Library?

### ISSUE THREAD

**Issue by everlighting** [robotframework/SeleniumLibrary#1800]
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by emanlove** [comment]
@everlighting If I may, using GitHub issues and just the subject line is not the best method for asking questions on various robot framework libraries. Some better methods for reaching out to the larger community include,

Slack - https://rf-invite.herokuapp.com/
Forum - https://forum.robotframework.org/
Mailing List - https://groups.google.com/g/robotframework-users

or even a fairly active community on LinkedIn - https://www.linkedin.com/groups/3710899/

I'll note that maintainers of the SeleniumLibrary, Jani and myself have our own usual spots we frequently listen and answer on. I prefer communicating over Slack and Jani has preferred the forum although he has been active on Slack recently as well.  I do understand that for some they have various restrictions on access to our various community channels like Slack or Google groups/email list. If your only access is with Github I understand. But I would prefer, if not, that you use another method to reach out with questions and support. And if you do use Github it would be best to delete out our issue template and add a few more words about what you are asking. Also if your primary language is something other than English and you prefer communicating in another language please do so. We can try our best recognizing that we are a world wide community and the gifts and talents people bring really enrich and enhance that community.

Jani and I have been discussing some issues lately and working on the next release. We were going to get together hopefully this week to finalize planning on this work. Personally I would like to get out the next release by the end of this month; which I think is doable. If you have any particular needs please ask. Also if you meant something else by your question please correct me and I will try to answer better what you were asking. Have a great day and take care!

**Comment by emanlove** [comment]
The 6.1.0 release was made May 3, 2023. The next release is schedule for June 30, 2023.
