### ISSUE TITLE
Firefox webdriver seems broken?

### ISSUE THREAD

**Issue by madworx** [robotframework/SeleniumLibrary#1801]
# Prerequisites

✅  I have searched for similar issues in open tickets and cannot find a duplicate.
✅  The issue still exists against the latest released version of SeleniumLibrary.
✅  This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
✅  You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
✅  Remember that this is a public forum, so remember to remove all sensitive information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

```
git clone git@github.com:madworx/docker-robotframework-selenium-xvfb-firefox-chrome.git
cd docker-robotframework-selenium-xvfb-firefox-chrome
make
docker run --rm -it -v $(pwd):/robot madworx/robotframework-selenium-xvfb-firefox-chrome -L TRACE -v BROWSER:firefox -d out-firefox .
cat out-firefox/geckodriver-*.log
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

USAGE:
    geckodriver [FLAGS] [OPTIONS]

For more information try --help

```

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

```
cat out-firefox/geckodriver-*.log
geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context

USAGE:
    geckodriver [FLAGS] [OPTIONS]

For more information try --help
```

## Expected behavior and actual behavior

I expected it to work.

I get error that --websocket-port is deprecated/not in use.

## Environment

Browser: Firefox 105
Browser driver: geckodriver 0.29.0
Operating System: Debian bookworm
Libraries
- Robot Framework: 5.0.1
- Selenium: robotframework-seleniumlibrary 6.0.0
- SeleniumLibrary: robotframework-seleniumlibrary 6.0.0
- Interpreter: Python 3.10.7

**Comment by emanlove** [comment]
Searching on that error message .. "geckodriver: error: Found argument '--websocket-port' which wasn't expected, or isn't valid in this context" .. I see references to a mismatch between the geckodriver and the Firefox browser. I see you've noted geckodriver version 0.29.0 but not the Firefox version. Do you have the Firefox version?

**Comment by madworx** [comment]
@emanlove : It's up there :) Browser: Firefox 105

**Comment by emanlove** [comment]
Sorry .. completely missed that somehow .. not sure how as I read the geckodriver version. From what I have read I suspect it is a driver / browser mismatch. Or at least that would be the first thing I would check. If you can manually log into the docker instance I would suggest investigating down that path. To me if that is the case this is a webdrivermanager issues versus a seleniumlibrary one.

**Comment by madworx** [comment]
Indeed; It seems that I relied on "webdrivermanager" pip package, which seems to have become abandonware. Using the latest geckodriver doesn't cause any errors.

I'm closing this since it's not really a bug in SeleniumLibrary.

**Comment by emanlove** [comment]
So I didn't mention that I recently joined as co-maintainer of the webdrivermanger project alongside of Jani (@rasjani). Jani originally wrote this package starting back in May 2018. As we transitioned into maintaining SeleniumLibrary again we decide to bring in webdrivermanager into the Robot Framework community organization - marketsquare. Jani did feel that this code need to be revisited and updated but neither of us had time to focus on it. I will note someone else created a similar project [webdriver-manager that is up on PyPI](https://pypi.org/project/webdriver-manager/). I have not taken a deep look at this other project but from a quick glance they are approaching it a bit differently. There seems to work with the browsers within the selenium code versus the marketsquare webdrivermanger which is an external tool for managing.

We would welcome any co-collaborators or pull requests if you are interested.

**Comment by madworx** [comment]
I believe the approach that the current `webdrivermanager` is doing is the correct one; However, I don't see the model working unless we'd have proper automated processed in place to:

a) Track all new releases.
b) Validate browser releases against webdrivers versions.
c) Automating PRs against tested working combinations.

In such a scenario maintainers would get a notification when there's a new validated-working combination that should be merged, and the only work effort would be to simply merge that PR into HEAD.

I've created such frameworks in the past - if you have a look at `https://github.com/madworx/docker-qemu`, `.travis.yml` and `travis-functions.sh` (they're currently not in a working state due to Travis CI shutting down general availability for open source building, but I believe they serve as an indicator of what I'm describing above)

**Comment by madworx** [comment]
There are a few issues that needs to be addressed if we want to do something better with this:

* Is it possible to download "older" versions of e.g. Chrome? (My current builds just pulls "`google-chrome-stable_current_amd64.deb`".
* I suppose the same goes for FIrefox?
* ... the same regarding webdrivers?
