### ISSUE TITLE
RemoteDriverServerException was removed from Selenium

### ISSUE THREAD

**Issue by dotlambda** [robotframework/SeleniumLibrary#1804]
https://github.com/SeleniumHQ/selenium/commit/5fba3a2b2d24a02356def84ffc5618bda73cc09f breaks `utest/test/keywords/test_webdrivercache.py`

**Comment by emanlove** [comment]
Thanks for the notice @dotlambda. Reviewing that test suite now and trying to understand what it is testing and the mechanics of how it is testing.

**Comment by emanlove** [comment]
Fixed within #1806
