### ISSUE TITLE
Input text field accepting more than its maximum length - iOS Devices

### ISSUE THREAD

**Issue by pchant35** [robotframework/SeleniumLibrary#1805]
Device : Mobile Phones
OS : iOS
Selenium Version : 5.1.1
Browser : Safari

Hi,

I'm experiencing an issue with the “Input Text” method on a textfield where the input field accepts more than its maximum length.
In html code, maxlength attribute of an input node (textfield) is set to 10 but during executions the input field is accepting more than 10 chars. This issue is seen on iOS Devices (Mobile phones) whereas it is working fine on other device (Mobile Android and desktop navigators). I'm using seleniumLibrary with robotframework.

This is the piece of code:
```
SeleniumLibrary.Input text    ${element}    elevenchars
${readtext}    SeleniumLibrary.Get Value    ${selector}   # get 11 chars
```

Is there a way to handle the max length such that only 10 characters are entered and restricts the further characters in automation.

Thanks and Regards,

**Comment by emanlove** [comment]
This sounds like you have discovered a bug with the application under test. It is also possible that the method selenium is inputting text is not the same way a user is entering text. This is less likely but again is application specific. Any broad change to limit the number of characters inputted would seem counter to the purpose and usage of the library. I'm open to counter arguments to that but I'll be honest this would be a high bar for this specific change.
