### ISSUE TITLE
IntelliBot @SeleniumLibrary Patched not working

### ISSUE THREAD

**Issue by isgandarov1994** [robotframework/SeleniumLibrary#1839]
I am getting this error 
1 - related to IntelliBot @SeleniumLibrary Patched 
2- And also there is no suggestion in my .robot file when typing keywords. Does anyone have a solution or suggestion. What should I use instead? Thanks in advance

Env: mac
PyCharm 2022.2.5 (Community Edition)
Python 3.10.5
selenium 4.10.0
robotframework 6.1
robotframework-seleniumlibrary 6.1.0

![](https://user-images.githubusercontent.com/54127314/245693035-a729f668-f2d3-4b3b-bf13-86ba1b945678.png)

**Comment by emanlove** [comment]
That plug-in was last updated over five years ago and looks as if it is no longer being maintained. I recommend you use a different plug-in possibly the [Robot Framework Language Server (by RoboCorp) plug-in](https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server) instead.

**Comment by isgandarov1994** [comment]
Thanks
