### ISSUE TITLE
Possible bug with Page should contain element keyword?

### ISSUE THREAD

**Issue by anhvutnu** [robotframework/SeleniumLibrary#184]
Hello all,

I have a xpath of following form:

xpath=//select[@id='${id}']/option[@selected=''][text()= ${expectedValue}]

I tested this xpath with Firepath and it worked as I wanted . 

I was trying call "Page Should Contain Element" with this xpath to verify if a form is pre-populated with expected value, but the keyword always returned saying it could not find the element. I'm using IE webdriver by the way.

Is it a bug with this keyword or Am i using this keyword wrong?

Thanks,

**Comment by ombre42** [comment]
Is there a reason you are not using List Selection Should Be?
Keeping things simple, I would do this:
List Selection Should Be    id=${id}    ${expectedValue}
Page Should Contain Element is pretty basic. If there were a bug here it would most likely be in Selenium. Have you run it in debug mode and looked at the XPath being sent to {:sessionid}}/elements and put that into Firebug?

**Comment by emanlove** [comment]
@anhvutnu What is the value of ${expectedValue}? My guess is the problem lies with the issue of string representation of  ${expectedValue} and the need for quotes within you xpath.

You might try @ombre42 suggestion of using List Selection Should Be...

**Comment by anhvutnu** [comment]
Thanks for the quick reply guys.

I will try @ombre42 suggestion and let you guys know if it works out for me.

@emanlove : I tried both quoted (text()='${expectedValue}') and without quoted still the keyword couldn't find the element.

**Comment by emanlove** [comment]
@anhvutnu Do you have any [special characters](http://stackoverflow.com/questions/247135/using-xpath-to-search-text-containing) within the expected value?

**Comment by anhvutnu** [comment]
the string I tested with was 0005

**Comment by anhvutnu** [comment]
Ok...List Selection Should Be worked like a charm ....

Thanks,
