### ISSUE TITLE
Missing "Options" setup in EDGE browser for remote url execution

### ISSUE THREAD

**Issue by ap0087105** [robotframework/SeleniumLibrary#1844]
We are using SeleniumLibrary version : 6.1.0 for scripting. 

Have below set of robot instruction : 

    ${downloadPath}=    Get Variable Value    Download Path 
    ${prefs}=    Create Dictionary    download.default_directory=${downloadPath}
    Open Browser    browser=${browser}    options=headless=${headless};add_experimental_option("prefs", ${prefs})    remote_url=${remoteUrl}    desired_capabilities=${desired_capabilities}
    
	
Here we setting up default downloads path in options. we are using EDGE browser to test the scripts. This works fine on local machine which is Windows machine. We tried to execute same TC on Remote Server, and its Linux instance. Same code is not working there, and what we found implementation for edge browser in Python38\Lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py
	
	if remote_url:
            defaul_caps = webdriver.DesiredCapabilities.EDGE.copy()
            desired_capabilities = self._remote_capabilities_resolver(
                desired_capabilities, defaul_caps
            )
            return self._remote(desired_capabilities, remote_url)

	where in return self._remote(desired_capabilities, remote_url) line options=options is missing. Can you check ?

**Comment by emanlove** [comment]
Made an initial pass through the code and it does appear that Edge, along with Safari, are missing options when using the remote url.

**Comment by ap0087105** [comment]
How soon these changes can be available in selenium library @emanlove? any thoughts.

**Comment by emanlove** [comment]
@ap0087105 I went ahead and made a release for this issue. Right now I have just released a release candidate, so in order to  install you just run


```
   pip install --pre --upgrade robotframework-seleniumlibrary
```
or use
```
   pip install robotframework-seleniumlibrary==6.1.2rc1
```

I was going to let this be used dfor about a week and then will release a final 6.1.2 release next week.

**Comment by ap0087105** [comment]
Thanks for quick resolution!!

**Comment by emanlove** [comment]
Just made final 6.1.2 release.
