### ISSUE TITLE
ProtocolError: ('Connection aborted.', Connection Reset Error('An existing connection was forcibly closed by remote host',None,10054,None)) 

### ISSUE THREAD

**Issue by achincholkar** [robotframework/SeleniumLibrary#1871]
# Prerequisites

- Similar issues https://github.com/robotframework/SeleniumLibrary/issues/1802. But the solution is not helpful.

# Steps to reproduce issue:
- This issue is reproducible when the new pop-up window is opened and it closes with a click of a button.
- Go to the URL and click on a button that opens a new pop-up. This pop-up has a save and cancel button.
- Click on cancel button which closes that pop-up.
- Try to do any action on the base page it will throw a protocol issue.

## Expected behavior and actual behavior
Expected behavior: Automation should continue to execute when the pop-up is closed using the cancel button.
Actual result: The selenium library hangs on clicking on the cancel button and we cannot perform any other action after that.

When I follow those steps, I see...

## Environment

Browser: Google Chrome and version 112 
Browser driver: Chrome-driver version 112.0.5615.49
Operating System: Windows 10

Libraries
- Robot Framework: 6.1
- Selenium: 4.12.0
- SeleniumLibrary: 6.1.1
- Interpreter: Python 3.11.5

**Comment by emanlove** [comment]
Try upgrading Selenium to the latest v4.15.2. There was a very nasty issue where within some of the JavaScript code that comes with Selenium was overriding a common function name `_` and causing issues similar to what you describe within the steps to reproduce above. This selenium issue appeared in 4.12.0 and was fixed in 4.13.0.

**Comment by emanlove** [comment]
You might also update to the just released SeleniumLibrary v6.2.0 which has some fixes for compatibility with latest Selenium versions.

Going to close this issue as the above should resolve you issue. If you have more issue feel free to reopen or create a new issue.

**Comment by achincholkar** [comment]
Hello @emanlove, we tried the suggested solution but it is not working as of now. Is there anything else we need to do to resolve this?
