### ISSUE TITLE
Input string Text while just show last character in input box when using Input Text keyword

### ISSUE THREAD

**Issue by wisdom2018** [robotframework/SeleniumLibrary#1873]
# For issues
Input "TR4097RE6" into input text while just show 6 character

## Expected behavior and actual behavior
show all string "TR4097RE6"

## Environment

Browser: Chrome
Browser driver: Chrome Driver Version 120.0.6099.71
Operating System: MacOS
Libraries
- Robot Framework: robotframework-requests==0.9.3
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  
- webdriver-manager==4.0.1

**Comment by emanlove** [comment]
This is likely due to the application under test and the field you are entering data into. Might I suggest you try `Press Keys` instead to enter data into that field.

**Comment by emanlove** [comment]
Closed due to lack of activity.
