### ISSUE TITLE
Add examples to 'Wait for Condition' keyword

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#188]
A [request](https://groups.google.com/forum/?fromgroups=#!topic/robotframework-devel/RVYqOHdbaZE) was made for better documentation and an example of the 'Wait For Condition' keyword works.

**Comment by roman-shayda** [comment]
return window.document.querySelector('your_CSS_locator').style.visibility != "visible"

**Comment by pekkaklarck** [comment]
This could/should be done as part of #925. Closing this issue.
