### ISSUE TITLE
Wrong Type Hint on some keywords. (`locator: Union[WebElement, None, str]`)

### ISSUE THREAD

**Issue by Snooz82** [robotframework/SeleniumLibrary#1880]
Some keywords like `Capture Element Screenshot` do have a type hint, that allows `WebElement`, `None` and `str`.
But the None is actually wrong.
There are some keywords that actually would work with `${None}` as a locator, but this one and others actually does not work and raises the error `TypeError: expected string or bytes-like object, got 'NoneType'`

Fix would be to just remove the None.

**Comment by emanlove** [comment]
René do you have a list of keywords you discovered that this affects?

**Comment by Snooz82** [comment]
Not at directly.
I remembered that it was more than one. 
search for those which has `None` as type hint, but no default.

**Comment by Snooz82** [comment]
A quick search results in the following you should check.
- [Get Table Cell](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Get%20Table%20Cell)
- [Table Column Should Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Table%20Column%20Should%20Contain)
- [Table Footer Should Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Table%20Footer%20Should%20Contain)
- [Table Header Should Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Table%20Header%20Should%20Contain)
- [Table Row Should Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Table%20Row%20Should%20Contain)
- [Table Should Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Table%20Should%20Contain)
- [Wait Until Element Contains](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Element%20Contains)
- [Wait Until Element Does Not Contain](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Element%20Does%20Not%20Contain)
- [Wait Until Element Is Enabled](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Element%20Is%20Enabled)
- [Wait Until Element Is Not Visible](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Element%20Is%20Not%20Visible)
- [Wait Until Element Is Visible](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Element%20Is%20Visible)
- [Wait Until Page Contains Element](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Page%20Contains%20Element)
- [Wait Until Page Does Not Contain Element](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Wait%20Until%20Page%20Does%20Not%20Contain%20Element)
- [Capture Element Screenshot](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Capture%20Element%20Screenshot)


But there may be more.
All those have `None` as type hint for `locator` but no None as default.

**Comment by emanlove** [comment]
Danke schön René. I'll take a look
