### ISSUE TITLE
(🎁) Support python 3.12

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/SeleniumLibrary#1906]
https://github.com/robotframework/SeleniumLibrary/blob/b0a848db40a3db4b7a8935fa79d90835b82c19a1/setup.py#L44

**Comment by emanlove** [comment]
Fixed in #1916

**Comment by emanlove** [comment]
@KotlinIsland  We have made a release adding Python 3.12 support ([PyPI](https://pypi.org/project/robotframework-seleniumlibrary/), [release notes](https://github.com/robotframework/SeleniumLibrary/releases/tag/v6.6.1))

**Comment by KotlinIsland** [comment]
lovely
