### ISSUE TITLE
Add Get Selenium Session Id -keyword

### ISSUE THREAD

**Issue by datakurre** [robotframework/SeleniumLibrary#191]
Selenium session id is required for sending test status information back to Sauce Labs, but it's currently not exposed through keywords. Because I want to use the released S2L, I need to monkey patch it to get the id:

https://github.com/plone/plone.app.robotframework/blob/master/src/plone/app/robotframework/saucelabs.py#L16

Would it be OK to add a such keyword? I could also provide pull request later myself.

**Comment by j1z0** [comment]
would be great if you could provide a path Asko.  I would incorporate it.

Cheers,
Jeremy

**Comment by datakurre** [comment]
Thanks. I'll prepare a pull request for this later and close this issue when the pull is there (need to write documentation for the keyword).

**Comment by ombre42** [comment]
I think this keyword is a good idea, however I would like to point out that monkey patching is not needed in this scenario. I used code like this to get the IP of the node when using Grid.:

```
from robot.libraries.BuiltIn import BuiltIn

def do_something():
    session_id = BuiltIn().get_library_instance('Selenium2Library')._current_browser().session_id
   ...
```

**Comment by datakurre** [comment]
@ombre42 Thanks. I was unaware of that possibility.

(I will still try to make a pull request later.)
