### ISSUE TITLE
WebDriver options: `platform_name`, `browser_version`

### ISSUE THREAD

**Issue by IncandescentChrysalis** [robotframework/SeleniumLibrary#1914]
# Steps to reproduce the issue
Since `v6.1.3` SeleniumLibrary has [dropped the `desired_capabilities` ability](https://github.com/robotframework/SeleniumLibrary/blob/master/docs/SeleniumLibrary-6.1.3.rst#id2).

As a result, `options` needs to be used to do the same.
However, I have been unable to choose the target OS leveraging the [`platform_name` common option of WebDriver](https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.options.html#selenium.webdriver.common.options.BaseOptions.platform_name).
Excerpt of the method leveraging `Open Browser`
```
    [Arguments]  ${url}
    &{BrowserStack capabilities}  Create Dictionary
    ...  local=true  timezone=Paris  idleTimeout=7200  networkLogs=true
    ...  os=${BROWSER.os}  osVersion=${BROWSER.os_version}
    ...  resolution=${RESOLUTION}  sessionName=${SUITE NAME}
    Open Browser  ${url}  remote_url=${REMOTE_URL}  options=set_capability("bstack:options", ${BrowserStack capabilities}); platform_name=${BROWSER.os}; browser_version=${BROWSER.browser_version}
```

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

# Error messages and additional information

```
ValueError: Unable to parse option: "platform_name=Windows"
```
# Expected behavior and actual behavior
Maybe I am not doing what is expected.
How to properly drive the:
* OS type
* browser version

?

# Environment
Browser driver: `8.9` ([Latest BrowserStackLocal](https://www.browserstack.com/docs/app-accessibility/local-testing/set-up-local-testing#Linux))
Operating System: Debian 12 Bookworm
Libraries
- Robot Framework: `4.1.3`
- Selenium: `4.23.1`
- SeleniumLibrary: `6.5.0`
- Interpreter: ?

**Comment by emanlove** [comment]
The value for platform_name and browser_name needs to be quoted, as in

```
Open Browser  ${url}  remote_url=${REMOTE_URL}  options=platform_name="${BROWSER.os}"; browser_version="${BROWSER.browser_version}"
```

The library is essentially converting that string into Python code and thus the syntax should reflect that and be valid.

**Comment by IncandescentChrysalis** [comment]
That did the trick!
Thanks a lot
