### ISSUE TITLE
Add keyword to access Selenium's getCSSValue functionality

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#192]
[Request made](https://groups.google.com/forum/?hl=en&fromgroups=#!topic/robotframework-users/1kIXsmyQIk0) on robotframework-users mailing list.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

Also send update the discussion referred by Ed.

**Comment by surfline-jherndon** [comment]
Is there a solution or workaround for this? My element does not contain a style attribute. At render time it reads the css file for its style.  id=test_element@background-color   does not work.

**Comment by aaltat** [comment]
No there hasn't been any progress on the matter. Would you like to do something with the matter?

**Comment by Yi-Dun** [comment]
I have the same problem with element does not contain style attribute. 
But after googling, I found some workaroud with Javascript and it works in RF.
Following is the example for returning the background color by xpath from an element.

```
${background_color}=  Execute Javascript  return window.getComputedStyle(document._getElementsByXPath("your_xpath")[0]).getPropertyValue('background-color');
log  ${background_color}
```

**Comment by aaltat** [comment]
There is work done in PR #775 but it is not yet ready. It is missing some test before it can go to the master. 

And it seems that there is duplicate issues raised, #774. I am closing this one.
