### ISSUE TITLE
Open Browser keyword not working when proxy server is enabled.

### ISSUE THREAD

**Issue by srib4ufrnd** [robotframework/SeleniumLibrary#197]
"Open browser" keyword is failing when proxy server is enabled.

when i disabled Proxy server option , atleast a browser windows is getting opened but i am not able to visit the google web page (because of no proxy)

but when I enabled Proxy server Option in Windows -> Internet Options
with proxy server x.x.x.x and port yy
i am able to open the google page manually from the browser, but when i tried it from selenium library with the same google page link, browser windows itself is not getting opened.

OpenBrowser window is getting failed without lanching any browser window.

what is the problem when i enabled proxy server?

below i mentioned all the steps i tried.....................................

i installed selenium library successfully.

I wrote a simple ROBOT test case as below
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
OpenGoogleLink
    Open Browser    http://google.com    gc
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I ran test case using RIDE by selectin Pybot with -L TRACE

I got the below error:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# command: pybot.bat -L TRACE --argumentfile c:\users\sreedhar.r\appdata\local\temp\RIDEmn2cnz.d\argfile.txt --listener C:\Python27\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:58015 D:\Official\ROBOT_Prerequisites\SeleniumWEbTest\webProxyDemo\webproxytest.txt
# Webproxytest                                                                                                                       

OpenGoogleLink                                                                                                             | FAIL |
## URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>

Webproxytest                                                                                                               | FAIL |
1 critical test, 0 passed, 1 failed
#1 test total, 0 passed, 1 failed

Output:  c:\users\sreedhar.r\appdata\local\temp\RIDEmn2cnz.d\output.xml

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Log:     c:\users\sreedhar.r\appdata\local\temp\RIDEmn2cnz.d\log.html
Report:  c:\users\sreedhar.r\appdata\local\temp\RIDEmn2cnz.d\report.html

test finished 05/03/13 16:21:51
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I got the belwo error Trace:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting test: Webproxytest.OpenGoogleLink
20130503 16:21:48.382 : TRACE : Arguments: [ u'http://google.com' | u'gc' ]
20130503 16:21:48.382 :  INFO : Opening browser 'gc' to base url 'http://google.com'
20130503 16:21:48.889 : DEBUG : POST http://127.0.0.1:58210/session {"sessionId": null, "desiredCapabilities": {"platform": "ANY", "browserName": "chrome", "version": "", "javascriptEnabled": true, "chromeOptions": {"args": [], "extensions": []}}}
20130503 16:21:49.925 : DEBUG : DELETE http://127.0.0.1:58210/session/None {"sessionId": null}
20130503 16:21:50.940 : TRACE : Arguments: [  ]
20130503 16:21:50.942 :  FAIL : No browser is open
20130503 16:21:50.942 : DEBUG : 
Traceback (most recent call last):
  File "<string>", line 2, in capture_page_screenshot
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_screenshot.py", line 28, in capture_page_screenshot
    if hasattr(self._current_browser(), 'get_screenshot_as_file'):
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_browsermanagement.py", line 390, in _current_browser
    raise RuntimeError('No browser is open')
20130503 16:21:50.943 :  WARN : Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
20130503 16:21:50.947 :  FAIL : URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
20130503 16:21:50.947 : DEBUG : 
Traceback (most recent call last):
  File "<string>", line 2, in open_browser
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_browsermanagement.py", line 106, in open_browser
    browser = self._make_browser(browser_name,desired_capabilities,ff_profile_dir,remote_url)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_browsermanagement.py", line 404, in _make_browser
    browser = getattr(self,creation_func)(remote , desired_capabilities , profile_dir)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_browsermanagement.py", line 433, in _make_chrome
    webdriver.DesiredCapabilities.CHROME, remote, desired_capabilities)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_browsermanagement.py", line 456, in _generic_make_browser
    browser = webdriver_type()
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 66, in __init__
    self.quit()
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in quit
    self.service.stop()
  File "C:\Python27\lib\site-packages\selenium\webdriver\chrome\service.py", line 97, in stop
    url_request.urlopen("http://127.0.0.1:%d/shutdown" % self.port)
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 406, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 438, in error
    result = self._call_chain(_args)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "C:\Python27\lib\urllib2.py", line 625, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Python27\lib\urllib2.py", line 400, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 418, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1177, in do_open
    raise URLError(err)
Ending test:   Webproxytest.OpenGoogleLink
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Setting I have:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Os i am using: Windows 7 Enterprise Service Pack 1
Chrome browser: Version 26.0.1410.64 m
Selenium Chrome driver installed: chromedriver2_win32_0.8
RIDE version: RIDE 1.1 running on Python 2.7.3. 
ROBOT Framework version:  Robot Framework 2.7.6 (Python 2.7.3 on win32)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by srib4ufrnd** [comment]
could any please let me know the solution for this problem?

is this really a configuration problem or a bug in the selenium library?

the only answer i need to know is why selenium is not working when proxy server is configured in my  system?

if i am supposed to do any specific configuration in selenium library please do let me know,

**Comment by ombre42** [comment]
The problem is communication between the client code of Selenium and the server is being redirected to the proxy.
One way to tell urllib2 not to use a proxy when the communication is local is to set the environmental variable no_proxy. There are several ways to do this
1) As a keyword call to a bundled library:
OperatingSystem.Set Environment Variable    no_proxy    127.0.0.1
2) In some Python code used by the test data:
import os
os.environ['no_proxy'] = '127.0.0.1'
3) in the shell/script prior to lanuching RF:
set no_proxy=127.0.0.1
export if *nix...

Whatever way its done, it has to happen before Open Browser.
