### ISSUE TITLE
How to handle the error screenshots in finial report when use rebot tool

### ISSUE THREAD

**Issue by luislu** [robotframework/SeleniumLibrary#199]
pybot --name T1 --outputdir T1\Results --output T1.xml T1.txt
pybot --name T2 --outputdir T2\Results --output T2.xml T2.txt
rebot --outputdir T3\Results --output T3.xml T2\Results\T2.xml T1\Results\ T1.xml

I use rebot tool to combines the results of several test suites.The timeout error screenshots for T1 and T2 are named the same(selenium-screenshot-1.png). So the final report can't display well or display the same.We have no chance to give the filename to screenshots during the test case execution once some steps timeout.

**Comment by j1z0** [comment]
your going to want to post this on the robot framework issue tracker, as this is upstream of S2L, i.e. we can't do anything about it here.

You might want to try reposting the issue here:

https://code.google.com/p/robotframework/issues/list

**Comment by ombre42** [comment]
It is not true that you do not have a chance to change the filename. The code snippet here demonstrates how to make the filenames unique by changing the keyword that runs when a test fails. This is not a perfect solution, but I hope it helps:

```
[Setup]    Register Keyword To Run On Failure    Selenium On Failure

*** Keywords ***
Selenium On Failure
    ${time}    Evaluate    str(time.time())    time
    Capture Page Screenshot    ${SUITE_NAME}_SCREENSHOT_${time}.png
```

**Comment by ombre42** [comment]
#268 is a similar issue with a clear change request where this is a howto that has been answered, so closing this.
