### ISSUE TITLE
'Click Element' does not handle implicit_wait well

### ISSUE THREAD

**Issue by frankbp** [robotframework/SeleniumLibrary#203]
We set the implicit wait to 10 seconds but seems keyword 'Click Element' only wait for 1 second.
![clickelement](https://f.cloud.github.com/assets/1422799/583347/6e93c5a6-c8e9-11e2-831c-422b5204aa46.png)
![implicitwait](https://f.cloud.github.com/assets/1422799/583355/de95039c-c8e9-11e2-98ce-334458c828cb.png)

**Comment by ombre42** [comment]
Implicit wait is only designed to handle waiting for the element to exist, not to wait until it is visible or enabled. See the [Selenium documentation](http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#implicit-waits) on that. In this scenario it is best to explicitly wait for the element to be visible. A [keyword for doing that](https://github.com/rtomac/robotframework-selenium2library/issues/174) has been implemented but has not been merged yet :(

Here is a keyword that extends S2L to provide this functionality that I have been using in the mean time:

```
from robot.libraries.BuiltIn import BuiltIn


class Selenium2LibraryExt(object):    

    def wait_until_element_visible(self, locator, timeout=None, error=None):
        """Waits until element specified with `locator` is visible on current page.

        Fails if `timeout` expires before the element is visible. See
        `introduction` for more information about `timeout` and its
        default value.

        `error` can be used to override the default error message.

        See also `Wait Until Page Contains`, `Wait For Condition` and
        BuiltIn keyword `Wait Until Keyword Succeeds`.
        """
        lib = BuiltIn().get_library_instance('Selenium2Library')
        if not error:
            error = "Element '%s' not visible in <TIMEOUT>" % locator
        try:
            lib._wait_until(timeout, error, lib._is_visible, locator)
        except:  # since this keyword is outside the library, it is not decorated for run on failure
            lib._run_on_failure()
            raise
```

**Comment by emanlove** [comment]
Merged.  Bumped this up to 1.3 release for which I just merged in the 
last scheduled issue.  We will see how the build goes 
http://robot.radiaatto.ri.fi/job/Selenium2Library/ and then should be 
able to cut the 1.3 (May) release.  

Ed

**Comment by frankbp** [comment]
Hi,

Thanks all for your great information and looking forward to the next
release of Selenium2Library.

Best regards,
Xie Lieping, Frank

On Fri, May 31, 2013 at 9:42 AM, Ed Manlove notifications@github.comwrote:

> Kevin Ormbrek wrote:
> 
> > Implicit wait is only designed to handle waiting for the element to
> > exist, not to wait until it is visible or enabled. See the Selenium
> > documentation
> > <
> > http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp#implicit-waits>
> > on that. In this scenario it is best to explicitly wait for the
> > element to be visible. A keyword for doing that
> > https://github.com/rtomac/robotframework-selenium2library/issues/174
> > has been implemented but has not been merged yet :(
> 
> Merged. Bumped this up to 1.3 release for which I just merged in the
> last scheduled issue. We will see how the build goes
> http://robot.radiaatto.ri.fi/job/Selenium2Library/ and then should be
> able to cut the 1.3 (May) release. In the mean time ... - Ed
> 
> > Here is a keyword that extends S2L to provide this functionality that
> > I have been using in the mean time:
> > 
> > |from robot.libraries.BuiltIn import BuiltIn
> > 
> > class Selenium2LibraryExt(object):
> > 
> > def wait_until_element_visible(self, locator, timeout=None, error=None):
> > """Waits until element specified with `locator` is visible on current
> > page.
> > 
> > Fails if `timeout` expires before the element is visible. See
> > `introduction` for more information about `timeout` and its
> > default value.
> > 
> > `error` can be used to override the default error message.
> > 
> > See also `Wait Until Page Contains`, `Wait For Condition` and
> > BuiltIn keyword `Wait Until Keyword Succeeds`.
> > """
> > lib = BuiltIn().get_library_instance('Selenium2Library')
> > if not error:
> > error = "Element '%s' not visible in<TIMEOUT>" % locator
> > try:
> > lib._wait_until(timeout, error, lib._is_visible, locator)
> > except: # since this keyword is outside the library, it is not decorated
> > for run on failure
> > lib._run_on_failure()
> > raise
> > |
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/rtomac/robotframework-selenium2library/issues/203#issuecomment-18678253
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rtomac/robotframework-selenium2library/issues/203#issuecomment-18718995
> .

## 

Best regards,
Xie Lieping, Frank
