### ISSUE TITLE
"Select Window" KW not completely switching

### ISSUE THREAD

**Issue by Jenissi** [robotframework/SeleniumLibrary#205]
Hi, 

I'm experiencing some pretty odd behaviour when using the select window keyword.  The thing is it is not consistently happening, I'd say around 70% of the time.

When I switch to a window, I can click around, but the minute i try to input text, it says it entered the text successfully, but it actually didn't.  Upon looking at it more closely, although I can click around etc, when I try to click on the textbox and type something I cannot even click on the textbox.  Another interesting thing is, when I do a ctrl-a, to select everything, it does the select all in the previous window that I switched from, not on the current window that selenium is clicking on.

Anybody else experience anything like this?
Thanks,
Mike

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closing due inactivity.
