### ISSUE TITLE
Open Browser cause error 503 Service Unavailable

### ISSUE THREAD

**Issue by atthaboon** [robotframework/SeleniumLibrary#207]
After install i can't user robotframeowk open browser

Open Browser | http://www.google.com |  chrome

I got this error:
HTTPError: HTTP Error 503: Service Unavailable
and no browser open

**Comment by ombre42** [comment]
This sounds like it could be a proxy issue. By default, Selenium traffic, which is local for local webdrivers, will obey system proxy settings. To bypass the proxy for local traffic, you can set the environmental variable no_proxy to 127.0.0.1,localhost prior to calling Open Browser. You can do this wherever you feel is best - in a setup (the Operating System library has a Set Environment Variable keyword), a variables file, on the command line prior to running tests, etc.

**Comment by aaltat** [comment]
Closed @ombre42 did ask for closing.
