### ISSUE TITLE
How to specify Profiles?

### ISSUE THREAD

**Issue by cookie314** [robotframework/SeleniumLibrary#208]
Hi, guys;
I want to use a specify profile on a remote machine, so I start the server on remote machine like this:
java -jar selenium-server-standalone-2.33.0.jar -firefoxProfileTemplate C:\AdminProfiles
Then I execute the case on local
Open Browser  http://www.google.com   firefox   remote_url=http://IP:4444/hub/wd
It did start the firefox and go to google, but not the right profile. So, how can I fix this?
Besides, I tried -profileLocation, didnot work either.
Thanks.

**Comment by ombre42** [comment]
This type of question is better asked in the user forums for Selenium, Robot Framework or others.
You could use nfs, mapped network drives, rsync, robocopy, sync with a SCM, and other solutions.
Closing this as it cannot be handled in this project.
