### ISSUE TITLE
Can't install selenium2library

### ISSUE THREAD

**Issue by dkoudrin** [robotframework/SeleniumLibrary#218]
I'm trying to install selenium2library with pip, it fails:

Downloading/unpacking robotframework-selenium2library
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement robotframework-selen
ium2library
No distributions at all found for robotframework-selenium2library
Storing complete log in C:\Users\Dmitri\pip\pip.log

Any good reason for this?

P.S. I successfully used pip to install robotframework and ride, so not sure why this is not working.

**Comment by Softworks-Consultancy** [comment]
perhaps your not connected to the internet or something is blocked?  I just tried it, works fine from my end.... whats in your pip.log file?

**Comment by dkoudrin** [comment]
Yep, got it now thanks. That server was actually down with a 'Major Outage' for a period of time, now all is well :)
