### ISSUE TITLE
Can't work with newest chromedriver.

### ISSUE THREAD

**Issue by wlnpu** [robotframework/SeleniumLibrary#220]
I download the newest chromedirver and replace the old one.
A lot of keyworkds will hang up. I try to use selenium library directly, it works fine.

**Comment by emanlove** [comment]
@wlnpu Do you recall which versions of ChromeDriver you were switching from and to when these hang ups occurred? Are you still having issues?

**Comment by wlnpu** [comment]
I remember I switched from 0.8 to the first 2.x version. I don't have any issue till now. I think it might be a chromedriver issue not the issue in selenium2library.

Thanks

**Comment by ombre42** [comment]
Has your situation improved with a newer version of chromedriver?

**Comment by wlnpu** [comment]
Yes, now I have used seleniume2Library and chromedhriver for a long time. No more issue yet.

Thanks,
Rocky

在2014年08月30 02时40分，"Kevin Ormbrek"notifications@github.com写道：

Has your situation improved with a newer version of chromedriver?

**Comment by ombre42** [comment]
Thank you for responding @wlnpu
