### ISSUE TITLE
Robot Framework-How to print results in excel from RIDE

### ISSUE THREAD

**Issue by praduman** [robotframework/SeleniumLibrary#221]
Hi,
I want to publish results in an Excel sheet after execution. Please tell me that how can I achieve it from RIDE.

**Comment by emanlove** [comment]
@praduman: Please note that this issue list is for Selenium2Library, a add-on library that focuses solely on Selenium2/WebDriver. Your question applies to Excel and RIDE, neither of which has anything to do with this Selenium library. Please address these questions to the mailing list for Robot Framework, robotframework-users@googlegroups.com.

**Comment by ombre42** [comment]
@emanlove - Hey Ed. I recommend adding a section to the readme like [this](https://github.com/ombre42/robotframework-sudslibrary#getting-help).

**Comment by emanlove** [comment]
@ombre42 - Great idea and I agree. Will do.
