### ISSUE TITLE
'Select from list' is very slow

### ISSUE THREAD

**Issue by douglaswaugh** [robotframework/SeleniumLibrary#222]
It seems to be taking our tests over five seconds for values to be selected from dropdown lists.  I tried to select using the specific 'id=' locator as suggested in https://github.com/rtomac/robotframework-selenium2library/issues/54 but it didn't make any difference compared with just using the id implicitly.

Is this normal/what everybody else experiences?

**Comment by douglaswaugh** [comment]
Actually it looks as though the answer to this is to use the 'Select from list by label' keyword.  It's cut the time to select a value in a dropdown to sub 0.5 seconds.  I understood that the documentation was telling me 'Select from list' is slow but I didn't understand what 'by value/by label/by index' meant at first.  All sorted now though.

**Comment by ombre42** [comment]
Closing per your comment. The documentation mentions that other keywords are faster.
