### ISSUE TITLE
Document using Chromedriver with Selenium2Library

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#224]
As the Chrome browser requires a separate download, ChromeDriver, is would be nice to fully document how to run, the demo for example, using the Chrome browser. (i.e. when the Chrome WebDriver documentation says PATH lets say what PATH that means and give an explicit example...)

**Comment by emanlove** [comment]
PATH means system path and not python path (as far as I can tell).  One can test the installation of ChromeDriver by typing at the command line

```
$ chromedriver
```

which for my system reported an error

```
chromedriver: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by chromedriver)
chromedriver: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by chromedriver)
```

that was not reported when trying to get ChromeDriver to work

```
# python
Python 2.6.6 (r266:84292, Mar 25 2011, 19:24:58) 
[GCC 4.5.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> driver = webdriver.Chrome('/home/individual/sandbox/virtual-python26-env/bin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/individual/sandbox/virtual-python26-env/lib/python2.6/site-packages/selenium-2.33.0-py2.6.egg/selenium/webdriver/chrome/webdriver.py", line 59, in __init__
    self.service.start()
  File "/home/individual/sandbox/virtual-python26-env/lib/python2.6/site-packages/selenium-2.33.0-py2.6.egg/selenium/webdriver/chrome/service.py", line 68, in start
    and read up at http://code.google.com/p/selenium/wiki/ChromeDriver")
selenium.common.exceptions.WebDriverException: Message: 'ChromeDriver executable needs to be available in the path.                 Please download from http://code.google.com/p/selenium/downloads/list                and read up at http://code.google.com/p/selenium/wiki/ChromeDriver' 
>>> 
```

which all leads me to this issue of documenting how to both install the necessary parts for the ChromeDriver and troubleshooting instructions verify one's install is working and hints on fixing issues.

**Comment by aaltat** [comment]
For me the raised exception is quite good and clear. Perhaps pointing to the correct documentation in the selenium side would be enough

**Comment by aaltat** [comment]
This is now days documented in the README: https://github.com/robotframework/SeleniumLibrary/commit/87b3bae99ce8737aa238d808cb284288476e150d

**Comment by pekkaklarck** [comment]
Should this be explained also in keyword docs?

**Comment by aaltat** [comment]
Well in keyword doc it says: 

For information about installation, support, and more please visit the [project page](https://github.com/robotframework/SeleniumLibrary).

Which should be sufficient.
