### ISSUE TITLE
How to Configure Robot Framework using Eclipse and PyDev?

### ISSUE THREAD

**Issue by N1t1nA** [robotframework/SeleniumLibrary#229]
I am using the following:-

Eclipse 
Eclipse Standard/SDK
Version: Kepler Release
Build id: 20130614-0229

Installed PyDev for Eclipse 

Installed RobotFramework EclipseIDE

Installed Python 2.7.5

Under site-packages
configured SeleniumLibrary
configured robot

Please let me know how to Start further  and Create Test Suite and write Robot Tests

**Comment by ombre42** [comment]
This is an issue tracker for Selenium2Library.
If you need help with SeleniumLibrary or Robot Framework usage, please post to the [user group for Robot Framework](http://groups.google.com/group/robotframework-users)

**Comment by cloverluo** [comment]
Hi N1t1nA, 
I have the same question that  how to Start further and Create Test Suite and write Robot Tests, and the content assist function is not working in eclipse for the keyword of robot.
Could you help me ,thanks.

**Comment by emanlove** [comment]
As Kevin noted:

This is an issue tracker for Selenium2Library.
If you need help with SeleniumLibrary or Robot Framework usage, please post to the [user group for Robot Framework](http://groups.google.com/group/robotframework-users).

I will also note this is a really old thread so ii is best to ask within the [user group](http://groups.google.com/group/robotframework-users).
