### ISSUE TITLE
Get Element Attribute bug?

### ISSUE THREAD

**Issue by dmllc** [robotframework/SeleniumLibrary#230]
When I use the Get Element Attribute to get the action attribute value of the following html code, the domain is not being returned:

HTML:
form name="learnmore" id="learnmore" action="https://uat.example.com/go/dispatcher/signup?option=A" method="post"

RF:
${SIGNUP_URL} =    Get Element Attribute    xpath=//form[@id='learnmore']@action
log    ${SIGNUP_URL}

LOG:
20130828 11:35:21.674 :  INFO : ${SIGNUP_URL} = https://uat/go/dispatcher/signup?option=A

**Comment by emanlove** [comment]
Which browser are you using and what version of that browser? Also which version of selenium?

**Comment by emanlove** [comment]
Here is some test code you can use to rule out or determine if the underlying selenium is the issue

Create test html, sample.html, (the form code was lifted from W3 HTML 4 spec)

```
<html>
<body>
  <form name="learnmore" id="learnmore" action="https://uat.example.com/go/dispatcher/signup?option=A" method="post">
 <P>
    <LABEL for="firstname">First name: </LABEL>
              <INPUT type="text" id="firstname"><BR>
    <LABEL for="lastname">Last name: </LABEL>
              <INPUT type="text" id="lastname"><BR>
    <LABEL for="email">email: </LABEL>
              <INPUT type="text" id="email"><BR>
    <INPUT type="radio" name="sex" value="Male"> Male<BR>
    <INPUT type="radio" name="sex" value="Female"> Female<BR>
    <INPUT type="submit" value="Send"> <INPUT type="reset">
    </P>
 </FORM>
</body>
</html>
```

Create test code, test-attr.py

```
import unittest
from selenium import webdriver

class GetAttributeTestCase(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox()

    def test_get_attribute(self):
        driver = self.driver
        driver.get("file:///home/emanlove/se-test-attr/sample.html")
        el = driver.find_element_by_xpath("//form[@id='learnmore']")
        action = el.get_attribute("action")
        print("Action String: %s" % action)
        self.assertEqual(action, u"https://uat.example.com/go/dispatcher/signup?option=A")

    def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()
```

Create test environment and run test code

```
$ mkdir se-test-attr
$ cd se-test-attr/
~/se-test-attr $ virtualenv -p /usr/bin/python2.6 --no-site-packages clean-python26-env
(clean-python26-env) ~/se-test-attr $ source clean-python26-env/bin/activate
(clean-python26-env) ~/se-test-attr $ easy_install selenium
(clean-python26-env) ~/se-test-attr $ python test-attr.py 
```

If you are using a selenium other than the last (2.25.0 in my recent test) or want to check out other versions just change the easy_install line to 

```
(clean-python26-env) ~/se-test-attr $ easy_install selenium==2.21.0
```

here testing against selenium version 2.21.0

**Comment by dmllc** [comment]
Firefox ver 22. selenium-2.16.1. i will upgrade selenium server and retest.

**Comment by dmllc** [comment]
fyi ... updated to selenium 2.35.0 and still get the same result.

**Comment by dmllc** [comment]
turns out to be a user error. sorry.
