### ISSUE TITLE
Select from list is not working as expected

### ISSUE THREAD

**Issue by cchukka** [robotframework/SeleniumLibrary#234]
I am running into an issue with select_from_list method. I am able to select the item from the dropdownlist but the corresponding onchange event is not working, where the page does not refresh as expected, nothing happens when the item is selected. the onchange event uses actionevent which is deprecated in IE9 but should still work. Issue is seen only in Ie9 standard mode and works in Ie9 compatibility mode and Ie8. 
Configuration:
Browser Ie9 standard mode
IE driver 235
selenium 2.35
robotframework-selenium2library=1.3

Preview of manual selection of dropdown list

![snapshotsample](https://f.cloud.github.com/assets/5382621/1080865/4c7b1002-156d-11e3-9e60-000208b53aba.png)

Preview of webdriver selection of dropdown

![doesnotwork](https://f.cloud.github.com/assets/5382621/1080884/8b19faf8-156d-11e3-8c42-17de7bc2a06f.png)

The second line " <br>This line only seen when manual selection of dropdown in IE9 standards mode because of attachEvent problem."does not show up when selecting the item.

**Comment by ombre42** [comment]
It looks like you have [worked this out with the Selenium team](https://code.google.com/p/selenium/issues/detail?id=4788) and have a workaround.
To fire an onChange event using Selenium2Library,  use [Simulate](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Simulate) with event=change.
