### ISSUE TITLE
Is there any way to send Ctrl+A keystroke?

### ISSUE THREAD

**Issue by rodion-goritskov** [robotframework/SeleniumLibrary#235]
Can't find is it possible to send Ctrl+A keystroke to the browser. In WebDriver I can do it with element.send_keys(Keys.CONTROL, 'a').

Is it possible using RobotFramework with Selenium2library?

**Comment by ombre42** [comment]
Technically it is possible with the current version, but this is not a recommendation for general usage:

```
    ${control}=    Evaluate    selenium.webdriver.common.keys.Keys.CONTROL    selenium
    ${s2l}=    Get Library Instance    Selenium2Library
    ${elem}=    Call Method    ${s2l}    _element_find    xpath=//input    ${True}    ${True}
    Call Method    ${elem}    send_keys    ${control}    a
```

Your use case needs to be accommodated through more conventional/user-friendly means.

**Comment by rodion-goritskov** [comment]
Thank you very much for your answer!
