### ISSUE TITLE
Issues with click element when site is using floating headers or footers

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#236]
We've been noticing that using the click element keyword will click on button on the floating header as opposed to the desired element.  I believe it is because the element is scrolled into view but selenium does no check if there is another element with a higher Z index on top of it.  We've been using Execute Javascript    document.getElementById('INSERT_ELEMENT_ID_HERE').click() to get around it but thought i'd mention it here.

**Comment by ombre42** [comment]
I understand your pain, but this sounds like an issue with Selenium itself. There are [instructions](https://github.com/rtomac/robotframework-selenium2library/blob/master/BUILD.rst#testing-third-party-packages) for testing whether you are encountering an issue with Selenium2Library or Selenium itself. If it is a Selenium issue, we cannot fix it, and you should report it [upstream](https://code.google.com/p/selenium/issues/list). If you have a page with a floating div that you can hide via Click Element I would consider doing that prior to interacting with the element you are trying to interact with.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by know1nos** [comment]
I haven't used the product in about two years, you can delete the issue and any others I created

Ben
