### ISSUE TITLE
Installation on a Linux environment gives "No module named _md5"

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#238]
. As we do not have pip nor easy_install on our linux servers, I have to use the python-method. When issuing the installation command, I get

[root@clab347node04 robotframework-selenium2library-master]# /opt/robot/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from ez_setup import use_setuptools
  File "src/ez_setup.py", line 67, in <module>
    except ImportError: from md5 import md5
  File "/opt/robot/python-2.5.5/lib/python2.5/md5.py", line 6, in <module>
    from hashlib import md5
  File "/opt/robot/python-2.5.5/lib/python2.5/hashlib.py", line 133, in <module>
    md5 = __get_builtin_constructor('md5')
  File "/opt/robot/python-2.5.5/lib/python2.5/hashlib.py", line 60, in __get_builtin_constructor
    import _md5
ImportError: No module named _md5

What goes wrong?

Thanks!

**Comment by HelioGuilherme66** [comment]
Not sure if is this, but you called python using absolute path:
/opt/robot/bin/python setup.py install
(python should be found from $PATH)
And then we can see:
/opt/robot/python-2.5.5/lib/python2.5

I think that is a very old python version. It should be 2.7.2 (or so).

Before installing robotframework-selenium2library is your robotframework install working?

**Comment by ombre42** [comment]
Although Selenium2Library has put some effort into being compatible with Python 2.5, Selenium itself is not. Please use 2.6 or 2.7.
There are a few posts on StackOverflow about your problem. Your error seems to happen when using a version of Python that was compiled without optional modules that should be provided later.
