### ISSUE TITLE
Add "Download File" keyword

### ISSUE THREAD

**Issue by daluu** [robotframework/SeleniumLibrary#24]
Mirroring an issue request from SeleniumLibrary for RF. There may be more requests of this nature in the future. And WebDriver may have some native solution in the future or not, so thus implementation may differ from SeleniumLibrary's request.

References:

RF user group request:
http://groups.google.com/group/robotframework-users/browse_thread/thread/4ad246ac0742ba3b

SeleniumLibrary issue 129
http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=129

Selenium / WebDriver issue 95
http://code.google.com/p/selenium/issues/detail?id=95

**Comment by tisto** [comment]
+1

**Comment by just-be-dev** [comment]
Is there any desire for this still?

**Comment by ombre42** [comment]
I would love this feature. The Selenium project has been sitting on this for seven years. If it was an easy solution, I'm sure they would have implemented it. Until Selenium implements, I'm not sure what the point of keeping this open is.

**Comment by just-be-dev** [comment]
I'll work on something next week. I have some ideas.

**Comment by just-be-dev** [comment]
I was thinking we could pull in a library like pycurl that can essential download a Web page or resource given a specified url. It would add a dependency but kinda achieve the basic functionality that we're seeking.

**Comment by just-be-dev** [comment]
This isn't a feature I can support through selenium, but could be easily added to RF simply using a library like pycurl.
