### ISSUE TITLE
The browser appears to have exited before we could connect. The output was: Error: cannot open display: :94

### ISSUE THREAD

**Issue by gjingqa** [robotframework/SeleniumLibrary#240]
Robot framework 2.8.1
Selenium  2.35.0
Selenium2Library  1.3.0
RIDE 1.1
Firefox 23
Jenkins
vnc-plugin
vncserver
user: jenkins

when one test case fail and the browser cannot be closed as expected, all the test cases after this case cannot be run and fail, the jenkins console show the following error:

---

RegressionTest.Shoppingcart positive.Checkout With MasterPass
.....
Several failures occurred:

1) Wallet not found!

2) URLError: <urlopen error [Errno 111] Connection refused>

3) WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: cannot open display: :94\n'
......
Register
egister :: 1. Go to registration page                                [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: URLError: <urlopen error [Errno 111] Connection refused>
| FAIL |
WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: cannot open display: :94\n'

---

but this issue never occurs when running on GUI desktop (ride.py). When one test case fail and browser will be left there, then another browser will handle next text case.

**Comment by gjingqa** [comment]
I'm using data-driven test method, means I put the keyword into template field. So, one test contains several test data, in this case, should I put "close all browser" at keyword teardown field to ensure browser will be closed in case of one test data fail?

**Comment by HelioGuilherme66** [comment]
Here are "my thoughts" about this.
- Firefox must use some user profile, and not the default one. Any security certificate question would prevent webdriver to proceed (you must add exception before using Selenium2Library).
- About the Wallet not found. If there is a master password the Wallet will pop up, and Robot does not care about that. I recommend to not use master password (or Wallet, which I think is a GNU/Linux program).
- I have used Jenkins directely to the machine set as slave in Windows, to have proper GUI interactions it needed to be run from startup and not as a service.
- Closing All Browsers in test Teardown might be a good solution (there was a bug that prevented Webdriver to load in new runs, but it was fixed).

(I believe that there are new versions for RIDE and Selenium2Library)

**Comment by gjingqa** [comment]
Hello Helio,

I'm so excited to get your reply!

I did meet the security certificate and added exception before.

The defined error message 'Wallet not found' is caused by my fault, I missed a original wallet picture for comparison. Here, I use image recognition to match what I want. 

Another mistake is caused by using 'Wait until page contains Element' when interacting with hidden DOM, I fixed it by Wait until element is Visible .

I just used test Teardown at keyword level when using data-driven, so far so good.

Using slave is a good solution, I'll try to persuade our architect to adopt it.

Why I rolled back to the old version of RIDE, Selenium2Library and firefox? 
It's because I met some issue on ubuntu12.1(64bit)+jenkins+vncserver+RIDE2.8.1+Seleniym2Library1.4+selenium2.35+googlechrome30+ chromedriver2.3 or 2.4(64bit). The same test suites running well on old version googlechrome and chromedriver, but not well on new version ones. This issue is still existing. I'm trying to fix it. Could you please help me out?However, all the test suite pass under RIDE on ubuntu desktop. 

---

Started by user Guanhua Jing
Building in workspace /var/lib/jenkins/workspace/BTR_Regression_Test_On_Chrome
No emails were triggered.
Starting xvnc
[BTR_Regression_Test_On_Firefox] $ vncserver :53 -localhost -nolisten tcp

New 'X' desktop is yul-o-autoqa01:53

Starting applications specified in /var/lib/jenkins/.vnc/xstartup
Log file is /var/lib/jenkins/.vnc/yul-o-autoqa01:53.log

[BTR_Regression_Test_On_Firefox] $ /bin/sh -xe /tmp/hudson3045510853237596908.sh
- /var/lib/jenkins/jobs/run.sh
  ....
  UpdateAccountFail :: 1. Go to registration page                       [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.66)\n  (Driver info: chromedriver=2.4.226074,platform=Linux 3.8.0-29-generic x86_64)' 
  Second signal will force exit.

---

For now, I have to write down the following maintenance rules for our team to avoid some weird issue occur.

Avoid to auto-update anything
Turn off browser’s auto-update
Lock the stable version
Backup installation packages with stable version
Avoid to auto-lock screen on Ubuntu

Any suggestion and problem please feel free to let me know.

Many Many thanks!
Guanhua

**Comment by gjingqa** [comment]
Shell script called by Jenkins

---

run.sh
#!/bin/sh
export PATH="/opt/google/chrome/:/usr/bin:$PATH"
pybot --variable BROWSER:$BROWSER --variable URLBASE:$URLBASE --variable SCREENSHOTCOMP:$SCREENSHOTCOMP --variable DBNAME:$DBNAME --variable DBUSERNAME:$DBUSERNAME --outputdir ./logs /var/lib/jenkins/jobs/RegressionTest
exit 0

---

Started by user Guanhua Jing
Building in workspace /var/lib/jenkins/workspace/BTR_Regression_Test_On_Chrome
No emails were triggered.
Starting xvnc
[BTR_Regression_Test_On_Firefox] $ vncserver :72 -localhost -nolisten tcp

New 'X' desktop is yul-o-autoqa01:72

Starting applications specified in /var/lib/jenkins/.vnc/xstartup
Log file is /var/lib/jenkins/.vnc/yul-o-autoqa01:72.log

[BTR_Regression_Test_On_Firefox] $ /bin/sh -xe /tmp/hudson1415675133524884292.sh
- /var/lib/jenkins/jobs/run.sh

# 

RegressionTest :: BTR website automation test suite. Version 2.7 canadacomp...

# 

RegressionTest.Account :: A new customer doesn't yet has an account.\n Crea...

# 

RegressionTest.Account.AccountInformation :: After creating a new account, ...

# 

UpdateAccountFail :: 1. Go to registration page                       [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 
| FAIL |
Several failures occurred:

1) Text 'fakename' did not appear in 1 minute

2) WebDriverException: Message: u'unknown error: cannot get automation extension\nfrom chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 

3) WebDriverException: Message: u'unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 

4) WebDriverException: Message: u'unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 

5) WebDriverException: Message: u'unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)'

---

RegressionTest.Account.AccountInformation :: After creating a new ... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

# 

RegressionTest.Account.AutoRegister :: Register a user automatically(withou...

# 

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n  (Session info: chrome=30.0.1599.101)\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 
Register :: 1. Go to registration page                                | FAIL |
Parent suite setup failed:
WebDriverException: Message: u'unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)'

---

RegressionTest.Account.AutoRegister :: Register a user automatical... | FAIL |
Suite setup failed:
WebDriverException: Message: u'unknown error: Chrome failed to start: exited abnormally\n  (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)' 

1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed

**Comment by HelioGuilherme66** [comment]
Again my gut feelings about your problem:
- It is clearly stating that chrome is not being launched (not found). How about firefox, same happens?
- My suggestion is to run.sh locally as user jenkins. I see an extra / in PATH (don't know if problematic):
     export PATH="/opt/google/chrome/
- I did use a workaround for when calling webdriver, adding Sleep 30 seconds (jenkins might take longer to start things) 

(I am currently struggling to get wxPython running in my CentOS system, so can't help more for now)

**Comment by gjingqa** [comment]
Thanks.
Firefox can be found and launched, all the test suites pass (firefox v23, not latest).
So did I. I removed that "/" today and tried again, and run "which google-chrome" at command line, it can be found. But same happens.
Good idea! I'll try it tomorrow.

I installed wxPython on CentOS, Ubuntu and Mac.

CentOS
http://dl.fedoraproject.org/pub/epel/6/x86_64/wxPython-2.8.12.0-1.el6.x86_64.rpm
rpm -ivh wxPython-2.8.12.0-1.el6.x86_64.rpm
http://sourceforge.net/projects/wxpython/files/wxPython/2.8.12.1/wxPython-src-2.8.12.1.tar.bz2/download

Ubuntu
sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-doc wx2.8-examples wx2.8-headers wx2.8-i18n

Mac

Download wxPython2.8
When you install wxpython you maybe meet the following issue.
Issue: 64bit python causes run-time error.
ride.py
wxPython not found.
You need to install wxPython 2.8 or 2.9 toolkit with unicode support to run RIDE.
See http://wxpython.org for more information.

> > > import wx  
> > > Traceback (most recent call last):    File "<pyshell#0>", line 1, in <module>      import wx    File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/**init**.py", line 45, in <module>      from wx._core import \*    File "/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core.py", line 4, in <module>      import _core_  ImportError: dlopen(/usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core_.so, 2): no suitable image found.  Did find:     /usr/local/lib/wxPython-unicode-2.8.12.1/lib/python2.7/site-packages/wx-2.8-mac-unicode/wx/_core_.so: no matching architecture in universal wrapper
> > > <<<<
> > > Make sure you are using the correct version of wxPython. Not just the right Python version, but the right bit version two: 32bit
> > > $ python-32 
> > > import wx
> > > so, you must install python 64bit. Do Not install 64bit python.

**Comment by gjingqa** [comment]
As other user, I run run.sh manually at terminal under GUI desktop, chrome browser can be launched and test suites run well.
As jenkins user, I run run.sh manually at terminal under GUI desktop, chrome browser can be launched and test suites run well.
As jenkins user, under vncserver, jenkins call run.sh, firefox browser can be launched and test suites run well.
However, as jenkins user, under vncserver, jenkins call run.sh, chrome browser seems not to be launched....

UpdateAccountFail :: 1. Go to registration page [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n (Session info: chrome=30.0.1599.101)\n (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)'

**Comment by HelioGuilherme66** [comment]
You say:
As jenkins user, under vncserver, jenkins call run.sh, firefox browser can be launched and test suites run well.

## However, as jenkins user, under vncserver, jenkins call run.sh, chrome browser seems not to be launched....

Well, firefox webdriver is built-in Selenium2Library. Chrome and IE are external applications. Chrome is a 32bit application, and maybe jenkins is not looking in the right place. Have you ran chrome with jenkins user? Is everything OK with permissions? (can you start chrome-driver standalone? my experience with this is in Windows). Good luck.

**Comment by gjingqa** [comment]
Ubuntu 64bit.
Yes, I ran chrome with jenkins user, it's ok.
I can start chromedriver at command line.
That's why I feel so weird.
I'll try 32bit chromedirver to see if it works.

Thanks a lot!

**Comment by j1z0** [comment]
```
UpdateAccountFail :: 1. Go to registration page [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: WebDriverException: Message: u'chrome not reachable\n (Session info: chrome=30.0.1599.101)\n (Driver info: chromedriver=2.3,platform=Linux 3.8.0-29-generic x86_64)
```

This sounds very much like a PATH issue.  Keep in mind that when executing scripts from Jenkins you don't necessarily have the same PATH as you do when the Jenkins User logs in.  I would specifically set the path to chrome from inside jenkins just before you attempt to run your tests.

For the error:

```
Error: cannot open display: :94
```

this is likely a configuration issue with you vncserver.  I would suggest you goolge jenkins xvfb.  I have used it succesfully in the past to run firefox and chrome on Debian (should be the same as ubuntu), and there are jenkins plugins to help with the setup.

Good Luck.

Jeremy

**Comment by gjingqa** [comment]
Thanks so much! Jeremy!
Solve it.
PATH issue!
I changed the run.sh, moved the 'export PATH= .....' to jenkins 'Execute shell' section.

---

Execute shell
command 

export PATH="/opt/google/chrome:/usr/bin:$PATH"
/var/lib/jenkins/jobs/run.sh

---

How did you know that? lol

Have a nice day!
Guanhua
