### ISSUE TITLE
Facing issue when running multiple scripts on chrome

### ISSUE THREAD

**Issue by praduman** [robotframework/SeleniumLibrary#241]
Hi,
I am running approx 400 scripts on chrome through batch file or RIDE but it's getting crashed during execution.Half of the scripts are getting failed and when opening Report/log file then it's blank. It's happening every time and not able to find the issue.
I am using chrome 30 version and tried it on previous version also.
Please help me to resolve the issue asap.

**Comment by HelioGuilherme66** [comment]
I would split the scripts to smaller test suites (think of memory leaks, or consumption).
You can produce logs and reports and then use rebot to collect them in a final report.
Even from failed test suites, you can use rebot to produce the logs and report (from output.xml).
(take care when using updated browsers, not always the webdriver is supporting them)
Good luck.

**Comment by aaltat** [comment]
There has not been activity for this issue for few long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
