### ISSUE TITLE
Add option to start browser headless

### ISSUE THREAD

**Issue by IlfirinPL** [robotframework/SeleniumLibrary#242]
Add option to start browser headless or other way that will not be visible to user.
ex. start as hidden window

**Comment by mayask** [comment]
You could try HtmlUnit or PhantomJS browser emulators. They're trying to mimic the real browser behaviour programatically. See more here http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Open%20Browser

**Comment by IlfirinPL** [comment]
Its not solution I am looking for, I want to test using FF, and since test capture page screenshot i dont need to see browser itself, I think it should be easily done since for example jenkins add slave node of selenium as headless

**Comment by j1z0** [comment]
To run Firefox headless on Jenkins you use a virtual frame buffer like xvfb. 

You can also look at saucelabs and run against any browser in the cloud without you having to watch. Use SAUCE5 for the discount code if you decide to use sauce. 

Either option u choose will work with RF but they are not part of RF. 

Cheers,
Jeremy

**Comment by ombre42** [comment]
Jeremy has provided a sufficient answer.

**Comment by ponkar** [comment]
May i know what is the sufficient answer provided here ?

**Comment by jimpriest** [comment]
Would it be worth re-opening this given that both Firefox and Chrome both now natively support a headless mode?

**Comment by aaltat** [comment]
Yes it could be a good idea. There actually is a PR for the fix proposal in #1011

**Comment by aaltat** [comment]
After reading the issue, it is better to create a new issue, because this issue contains details which creates noise and that is not required.

**Comment by pekkaklarck** [comment]
Always a good idea to refer to the new issue as well. In this case #1014.
