### ISSUE TITLE
Execute Javascript documentation issue

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#244]
The documentation says "code may contain multiple lines of code but must contain a return statement (with the value to be returned) at the end."

This should be re-worded to reflect that the keyword has a return value of None unless you have a return statement at the end of the script. A return statement is not a "must".

**Comment by gjemp** [comment]
sry for commenting this  but I was really confused with returning value. 
was trying following: 
1) function a(){ var b = 1; return b;}  
2) function a(){ var b = 1; return b;}  return a();

were not working and then I tried this:
1) return b=1;
 and it worked. But in JS you can return something only in function so I was expecting that if functions returns something then that is it  :)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return

The return statement ends function execution and specifies a value to be returned to the function caller.

Example of returning anything should be shown as( this is working at the moment :D )  : Execute Javascript   return a=1+1

**Comment by ombre42** [comment]
Sounds like we need more clarification.
Add this text (from the Javadocs for Se): The script fragment provided will be executed as the body of an anonymous function.
Add an example with a return statement to _both_ execute keywords.

**Comment by ombre42** [comment]
@gjemp I updated per my comments above - see d993370207ecf5ed6feaa4024bd8bf4abd1d10e3.

FYI you can find more examples in [this Javadoc](http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/JavascriptExecutor.html)
