### ISSUE TITLE
Add keywords for Additional Waits 

### ISSUE THREAD

**Issue by EricZeff** [robotframework/SeleniumLibrary#246]
Having keywords listed below would make syncing with the application easier.

It seems when issue 174 https://github.com/rtomac/robotframework-selenium2library/issues/174 was closed and the proper issue was address but there should have been a new issue opened for the additional waits (see list below)
- [ ] Element Should Be Clickable
- [ ] Element Should Not Be Clickable
- [ ] Element Should Be Selected
- [ ] Element Should Not Be Selected
- [x] Element Should Not Contain #373 
- [ ] Element Text Should Not Be
- [ ] Wait Until Element Contains
- [ ] Wait Until Element Is Clickable
- [ ] Wait Until Element Is Not Clickable
- [ ] Wait Until Element Is Selected
- [ ] Wait Until Element Is Not Selected
- [x] Wait Until Element Is Visible
- [x] Wait Until Element Is Not Visible
- [ ] Wait Until Element Does not Contain
- [ ] Wait Until Page Does Not Contain
- [x] Wait Until Page Does Not Contain Element #375
- [ ] Wait Until Title Is
- [ ] Wait Until Title Is Not
- [ ] Wait Until Title Contains
- [ ] Wait Until Title Not Contains

**Comment by just-be-dev** [comment]
`Not Contains` is improper English. I recommend `Does Not Contain` as an alternative.

**Comment by aaltat** [comment]
There has not been activity for this issue for few long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by CaptainRatax** [comment]
Hi, sorry to bother, but the keyword "Wait Until Title Is" or " Wait Until Title Is Not" would be really helpful in some cases.
