### ISSUE TITLE
Keywords for network statistics and metrics

### ISSUE THREAD

**Issue by daluu** [robotframework/SeleniumLibrary#25]
In particular, performance timings of content/file downloads, uploads, etc. along with viewing HTTP headers sent/received in browser.

Selenium RC had a captureNetworkTraffic option on startup of browser session to enable such functionality, though the user of course had to manually parse the desired data (or look for third party Selenium tools that did that).

WebDriver unfortunately doesn't natively support this, so just opening up a tracking issue for discussion and consideration of adding such functionality perhaps with third party tools.

See following for references:

Matching SeleniumLibrary issue 206
http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=206

Request for such functionality at RF user group
http://groups.google.com/group/robotframework-users/browse_thread/thread/c44178c9edb4febe

Third party solutions to desired feature:
http://deanhume.com/Home/BlogPost/measuring-web-page-performance-with-selenium-2-and-the-web-timings-api/56
http://www.theautomatedtester.co.uk/blog/2010/selenium-webtimings-api.html
http://sevenseconds.wordpress.com/2011/06/28/velocity-conference-2011-workshop-on-automated-web-performance-testing/
http://www.supermind.org/blog/968/howto-collect-webdriver-http-request-and-response-headers

**Comment by emanlove** [comment]
daluu, Have you seen the [robotframework-httplibrary](https://github.com/peritus/robotframework-httplibrary) and it's various [forks](https://github.com/peritus/robotframework-httplibrary/network/members)?  Some of this functionality might already be present there or more appropriate for that library.

**Comment by daluu** [comment]
emanlove, yes, I've heard of that library, but didn't check out the forks. Nevertheless, it doesn't quite fit with the issue here. This issue is about doing testing with WebDriver and at the same time being able to query for the browser data such as HTTP headers and as a result of that also extrapolate timing statistics.

This was possible as part of Selenium RC via captureNetworkTraffic option. It isn't available to WebDriver and must be extended via third party tools unless it is somehow incorporated in future WebDriver releases.

But you are right that if I just wanted pure HTTP request/response testing, I could use the mentioned library or similar.

While the use case of this issue is not a widely requested or needed feature, it does have its uses. Same as how developers can check HTTP headers, cookies, and related data via browser extensions like Firebug, we would want same functionality exposed via Selenium to extract out with our tests for debugging or performance analysis, etc. rather than do it via separate tools in separate tests/scripts, etc.

**Comment by emanlove** [comment]
daluu,  thanks for helping me understand these issues better.  I've not yet had a need for this type of functionality so you have really helped me to see better how it fits into the robotframework-selenium2library, what your needs are, and what greater possibilities there are for me to use the framework for.

**Comment by lsjuanny** [comment]
There is a reason I think we need this feature:
On a webpage, a javascript execution trigger a http request. This happens typically when the webpage need send logging information to server. Such as following scenarios:
1. When user stay on one page for more than 3 seconds, it will send log to server
2. When user open a open a drop down menu and select a item, it will send log to server
And so on.

For this kind of scenarios, I can got two reason why robotframework-httplibrary is not suitable here.
1.  The thing we need test is the behavior of javascript execution.
2.  We need check if it works well in all kinds of browser.

**Comment by daluu** [comment]
It's may also be useful for testing/verifying AJAX web requests w/o simulating it w/ an external library/tool. But usually simulation is good enough though.

**Comment by ombre42** [comment]
Has anyone tried  to use [BrowserMobProxy](https://github.com/lightbody/browsermob-proxy)? That seems like it would help gather the information. It is not tied to Selenium and so should have its own library for Robot Framework.

**Comment by daluu** [comment]
That would be nice if there was a BrowserMobProxyLibrary to combine with Selenium2Library for testing in this area.

**Comment by SteveHarrison82** [comment]
I would like to share the following link: 
https://github.com/Work4Labs/selenium-simple-test/blob/72569ee775425273859b36c201508a973ce2db00/src/sst/actions.py. 

I came across browser mob some days back from this link and was not aware of its requirement at that time. From the glimpse, the snippet appears to use webdriver

**Comment by just-be-dev** [comment]
That would be a good reference for a BrowserMob Proxy library. They're using BrowserMob's restful api. Thanks for the resource @rama-bornfree, I might do something with this!

**Comment by SteveHarrison82** [comment]
Welcome, I will try to understand the snippet

**Comment by just-be-dev** [comment]
I'm working on a [BrowserMob Proxy library](https://github.com/zephraph/robotframework-browsermoblibrary) that would be more appropriate for this. As far as I'm concerned this is outside of the scope of S2L so I'm going to close it.
