### ISSUE TITLE
Better project introduction to PyPI

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#254]
The current introduction just says:

```
"""Selenium2Library is a web testing library for Robot Framework that leverages the Selenium 2 (WebDriver) libraries."""
```

It would be great to have some more information, including installation instructions there. A very easy and DRY solution is reading the current README.rst content to long_description in setup.py. We recently did that with StatusChecker project and it works great. The same information is visible in [BitBucket project pages](https://bitbucket.org/robotframework/statuschecker/src) (GitHub obviously shows READMEs same way) and on [PyPI pages](https://pypi.python.org/pypi/robotstatuschecker), and the [implementation](https://bitbucket.org/robotframework/statuschecker/src/master/setup.py) was pretty trivial.

**Comment by aaltat** [comment]
I think this is now done in: https://github.com/robotframework/SeleniumLibrary/commit/a10a421bf8012d6d3927e66571c89ecd5d2571c8
