### ISSUE TITLE
Remove unnecessary downloads

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#256]
There are six downloads related to 1.4 on [PyPI](https://pypi.python.org/pypi/robotframework-selenium2library/1.4.0). For a casual user knowing what to use is pretty hard, especially when the installation instructions only say `pip install ...`. In the future I would be ready to have only the `.tar.gz`. This would have various benefits:
- Easier to pick the right package.
- Easier to document the installation procedure (see also #255).
- Less work creating and uploading packages (running `python setup.py sdist register upload` is enough).

The reason I think we are fine with `.tar.gz` is that it is enough both for pip and for manual installation. Why the other packages aren't really giving anything but extra work is explained below:
- `.win32.exe` and `.win-amd64.exe`: These aren't enough to actually install the library. Some of the dependencies need to be installed using source distributions anyway, so it would probably be easier to just document the manual installation procedure to always use them (#255). Creating these packages also requires access to two separate Windows machines.
- `.zip`: Current Windows machines should be able to extract `.tar.gz` just fine so having two source distributions doesn't give much. Creating this package is possible also outside Windows so it's not too big a task.
- `-py2.6.egg` and `-py2.7.egg`: I don't know any use case for these.

If any of the above packages have valid use cases they obviously should be kept, but adding a note about the usage to installation instructions might be a good idea then. If all of the packages are valid, this issue should be closed as invalid instead.

**Comment by aaltat** [comment]
This should be done now days, closing.
