### ISSUE TITLE
Remove unnecessary `docutils` dependency

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#257]
This library currently has following dependencies:

```
decorator >= 3.3.2
selenium >= 2.32.0
robotframework >= 2.6.0
docutils >= 0.8.1
```

Three first are actually used by the library, but docutils is only used for compiling README.rest and other reStructuredText files to HTML by `doc/generate_readmes.py` and `doc/buildhtml.py`. This is just a developer/packager activity and thus users don't really need docutils for anything.

I would like to remove the docutils dependency to make it easier to document what dependencies are needed in manual installation (see #255). Avoiding an unnecessary download when using pip wouldn't obviously hurt either.

I'm not certain is compiling reST to HTML really needed in general. Users looking at source probably are fine with *.rst source files and in GitHub (and PyPI #254) these files are formatted automatically. If the compilation isn't needed anymore, then the need for docutils obviously goes away. If there is a use case for the compilation, I would still be more than willing to remove the docutils dependency from users. If we want to be helpful for the developer running the aforementioned compilation scripts, we can change them to import docutils like this:

```
try:
    import docutils
except ImportError:
    raise ImportError('Importing `docutils` failed. Install it with `pip install docutils`.')
```

**Comment by aaltat** [comment]
@pekkaklarck Would you time to look the pull request to fix this.
