### ISSUE TITLE
Reinstate SeleniumLibrary library import arguments and start/stop server keywords in the future

### ISSUE THREAD

**Issue by daluu** [robotframework/SeleniumLibrary#26]
Just a placeholder for tracking and discussion. If I get to it, may have pull request for this as well (if I add RemoteWebDriver functionality to this library).

While not all the SeleniumLibrary import stuff and certain keywords relating to  stop/start server may be relevant to Selenium 2, however some do apply.

For example server_host and server_port do apply when considering RemoteWebDriver and Selenium Grid2 deployment, and it also applies if we wanted to better support backward compatibility with SeleniumLibrary (less work to modify import statement in tests).

And jar_path for import along with keywords Start Selenium Server and Stop Selenium Server can apply for RemoteWebDriver case (maybe also Grid2, but not sure). For example: start up Selenium 2 server in standalone mode for use with RemoteWebDriver. Stop the server as needed (via WebDriver.close() on final/main browser window, or close all windows if more than one open to stop the server).

FYI, the Selenium 2 server is started in standalone mode (or RemoteWebDriver) as follows:

java -jar selenium-server-standalone-{VERSION}.jar

which uses default host and port of localhost, 4444.

To not break compatibility, these reinstated library import arguments would also be optional, in case user is not using RemoteWebDriver. For RF users who prefer backward compatibility in their tests that used to use SeleniumLibrary, they can run tests using this library via RemoteWebDriver + desired browser option rather than the native browser driver option. That way, not need to modify import statement. And they can switch back and forth between SeleniumLibrary and this library using same tests (in ideal world anyways). They would just need to manually start the server when using RemoteWebDriver is all, unless they use start/stop server keywords.

**Comment by j1z0** [comment]
Ok I went ahead and implemented the remoteWebDriver support.  Just checked it in.  it's all part of the open browser keyword now, where you can pass in the remote server and the desired capabilities.  I did not however add the start stop server keywords.  So feel free to do that if you have some time. :)

**Comment by just-be-dev** [comment]
This is an old discussion, I'm going to close this issue. 

If something related to this issue needs to be brought back up then let's do so in a new issue.
