### ISSUE TITLE
Document that jQuery is not provided by Selenium2Library

### ISSUE THREAD

**Issue by anianj** [robotframework/SeleniumLibrary#262]
If that so, please update the keyword document to remove the information about jquery & sizzle

**Comment by emanlove** [comment]
@nianjcn: As far as I know no changes were made in this area. Are you experiencing some sort of issue with the latest release?

**Comment by anianj** [comment]
Hi emanlove, when i use this keyword with jquery locator
Click Element    jquery=input[value=*'Start the storage pool configuration wizard']
i got
WebDriverException: Message: u'jQuery is not defined'

**Comment by ombre42** [comment]
The current implementation of jQuery support depends on the application under test providing jQuery. Selenium2Library accesses jQuery through the global object jQuery (same object as $). @nianjcn are you trying to use jQuery in a web app that does not use it? See the [discussion on the pull request](https://github.com/rtomac/robotframework-selenium2library/pull/161).

**Comment by ombre42** [comment]
The library documentation does not mention that jQuery selectors require jQuery to be provided by the AUT and referenced in the variable named jQuery. We need to document this as Jeremy's code to automatically provide jQuery was not merged.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by jensens** [comment]
I just stumbled over this one.

```
WebDriverException: Message: unknown error: jQuery is not defined
  (Session info: chrome=49.0.2623.75)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-24-generic x86_64)
```

So yes, some lines in the docs about this would help.

**Comment by aaltat** [comment]
Although this has been clear for me always, it seems that it news to someone and it would not hurt to add note, example in [Execute Javascript](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Execute%20Javascript) keyword. The error message is clear and I would not change that part.

**Comment by aaltat** [comment]
Created a pull request #613. If we all happy with the change, we can merge it to master and close the issue.

**Comment by emanlove** [comment]
I believe this was not an issue of "Execute Javascript" and not having jQuery it is a problem of using jQuery locators.

> when i use this keyword with jquery locator
> Click Element jquery=input[value=*'Start the storage pool configuration wizard']
> i got
> WebDriverException: Message: u'jQuery is not defined'

The documentation should be within the section on locators and not the 'Execute Javascript' keyword.

**Comment by emanlove** [comment]
[Forgot to ask...] @jensens where did you see this error? what were you doing at the time or what was the keyword/statement that caused the error?

**Comment by aaltat** [comment]
@emanlove Good point, I will make the change.
