### ISSUE TITLE
Keyword to add a Selenium driver to BrowserCache

### ISSUE THREAD

**Issue by GarethNixon** [robotframework/SeleniumLibrary#265]
Hello, 

Our team was having an issue trying to get a Selenium web driver created in a separate python library added to the Selenium2Library driver cache. We were able to accomplish this by adding a new keyword to the _browsermanagement class which took our driver as an argument though it's a hack so it's obviously not ideal.   

def add_to_cache(self,driver,alias):
        self._cache.register(driver, alias)

Would it be possible to add something like this to the library or is there a better way to do this already that we missed? Would be very helpful :).

Kind Regards

Gareth

**Comment by ombre42** [comment]
The new keyword [Create Webdriver](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Create%20Webdriver) in 1.5 should cover most use cases for creating a WebDriver instance and putting it into the cache. Please explain your scenario if that keyword is not helping you.

If you find it painful to create the right argument values to pass to _Create Webdriver_ in the RF syntax, you can call _Create Webdriver_ from Python.

```
from robot.libraries.BuiltIn import BuiltIn

def launch_my_special_browser():
    ... build up chrome_options ...
    BuiltIn().get_library_instance('Selenium2Library').create_webdriver('Chrome', chrome_options=my_chrome_options)
```

You could also invoke _Run Keyword_ from Python to call _Create Webdriver_, but with keyword arguments its a little tricky/long.

Prior to 1.5 there was no _Create Webdriver_ and you still did not need to modify Selenium2Library to manually put a WebDriver instance into the cache. See [this comment](https://github.com/rtomac/robotframework-selenium2library/issues/214#issuecomment-19837982) for an example of how to do that.

If you find that none of these answers address your problem satisfactorily, feel free to re-open this issue.

**Comment by GarethNixon** [comment]
Hey thanks for getting back to me so quickly.

I'm not 100% sure the Keyword does what we need it to, we've attempted using it as a keyword and in Python. The issue is that the Python SDK for an application we're using takes a webdriver as an argument when creating an instance. We've attempted to use Selenium for this but we can't seem to get just a driver object returned to use when creating the application instance. Is there anyway to do that with the Create Webdriver keyword that we missed? 

When we did try to capture the returned instance Robot threw a wall of error text.

Thanks again.

**Comment by ombre42** [comment]
I hope I am understanding you right. Open Browser and Create Webdriver return indicies, not WebDriver instances. After calling either of these keywords, you can do this to get the WebDriver instance that was just created:

```
${s2l}=    Get Library Instance    Selenium2Library
${web_driver}=    Call Method    ${s2l}    _current_browser
```

or in Python

```
s2l = BuiltIn().get_library_instance('Selenium2Library')
web_driver = s2l._current_browser()
```

Then you can pass the WebDriver instance to the Python SDK that will create an instance of the application.

**Comment by GarethNixon** [comment]
Yes you understood perfectly,

Added that to the Python and it worked without issue. Thanks again for the help!

**Comment by ombre42** [comment]
Glad to be of help. The information to do what I mentioned should be documented somewhere, for sure.

**Comment by appalaprathyusha** [comment]
> I hope I am understanding you right. Open Browser and Create Webdriver return indicies, not WebDriver instances. After calling either of these keywords, you can do this to get the WebDriver instance that was just created:
> 
> ```
> ${s2l}=    Get Library Instance    Selenium2Library
> ${web_driver}=    Call Method    ${s2l}    _current_browser
> ```
> 
> or in Python
> 
> ```
> s2l = BuiltIn().get_library_instance('Selenium2Library')
> web_driver = s2l._current_browser()
> ```
> 
> Then you can pass the WebDriver instance to the Python SDK that will create an instance of the application.

Hi, I am getting the following error when I use 'SeleniumLibrary'.
Object '<SeleniumLibrary.SeleniumLibrary object at 0x000001DB5E6648B0>' does not have method '_current_browser'.

**Code:**
Open Browser    https://www.softwaretestinghelp.com/css-selector-selenium-locator-selenium-tutorial-6/   chrome
   ${driver}=    Get Library Instance    SeleniumLibrary
   ${web_driver}=    Call Method    ${driver}    _current_browser

Kindly help me how to do using 'seleniumLibrary'.

**Comment by aaltat** [comment]
Use:
```
sl = BuiltIn().get_library_instance('SeleniumLibrary')
driver = sl.driver
```

**Comment by appalaprathyusha** [comment]
ok thanks.
