### ISSUE TITLE
Check if option in list is selected can take unnecessarily long time

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#271]
Using the 'List Selection Should Be' keyword to check if certain item(s) are selected can take longer then necessary, especially for a single select list with many options. An example where performance is poor is checking the single country of residence in selection list of 250+ countries. The current code finds all elements with tag option within the select element and checks each and every one's is_selected status before comparing against the expected selection. This problem also affects 'Get Selected List Label' and 'Get Selected List Value' but not as severe as these return only the first found selected option.

**Comment by ombre42** [comment]
@emanlove Do you have any ideas on how to speed it up? I do not see how we could without reducing information in the failure message or sidestepping the API and using JavaScript. Maybe I am just missing something.

**Comment by emanlove** [comment]
@ombre42 I was thinking of additional keywords like 'Is List Option Selected' or 'Check List Option Selected' with possible some specific 'Check List Option By Value Selected' or 'Check List Option By Label Selected' - I haven't worked out any good keyword names for these  ('get option selected attribute by value'... ). Essentially what I'm thinking is that with a single select list one should be able to query a specific option (by value, label, or possibly index) on a list and get it's selected attribute. One could also check specific options on a multiselect list but I suspect with multiple option lists one would want to know if the other options are not selected, i.e. mutually exclusive selection.

I wouldn't be surprised if there is a better where to check this that I haven't thought of yet...

**Comment by emanlove** [comment]
... a better way like simply checking the selected attribute of the option. Adding to the internal tests, [acceptance\keywords\lists.txt](https://github.com/rtomac/robotframework-selenium2library/blob/master/test/acceptance/keywords/lists.txt), for example

```
Get Selected Attribute
    # Expect the default selection of the preferred channel to be telephone ...
    ${is_selected}=  Get Element Attribute  //select[@name="preferred_channel"]/option[@value="phone"]@selected
    Should Be Equal  ${is_selected}  true
    # ...and the Email and Direct Mail options to be not selected.
    ${is_selected}=  Get Element Attribute  //select[@name="preferred_channel"]/option[@value="email"]@selected
    Should Be Equal  ${is_selected}  ${None}
    ${is_selected}=  Get Element Attribute  //select[@name="preferred_channel"]/option[@value="directmail"]@selected
    Should Be Equal  ${is_selected}  ${None}
```

**Comment by aaltat** [comment]
Closing because method now days uses Selenium API to get the list selection and the performance does not anymore depend on the SeleniumLibary.
