### ISSUE TITLE
Press Key does not support non-ASCII, non-typeable characters such as ARROW_RIGHT

### ISSUE THREAD

**Issue by pandabat** [robotframework/SeleniumLibrary#275]
Current implementation of Press Key does not seem to support sending an ARROW_RIGHT press to the webdriver.

Example, web app that allows navigation via up-down-left-right keys.

Registered keycode in app for right arrow is "39" but this is not the ASCII code 39 ('). Sending "Press Key <ELEMEND_ID> \39" just results in a ' being typed. Can't find any constant table to reference for code for arrow key nor does there seem to be any "native key" command or any other code set (apart from ASCII) with which to enter an arrow key.

Cannot test normal keyboard navigation of web app.

Using Selenium2Library with robotframework on Fedora Linux. Tried to get this going under Firefox & Chrome but now don't think that it's possible.

**Comment by pandabat** [comment]
Ok, so first I tried Execute Javascript to do an arrow key press like follows but these failed:

```
Execute Javascript  var kp = document.createEvent("KeyboardEvent"); kp.initKeyEvent("keypress",true,true,null,false,false,false,false,39,0); window.dispatchEvent(kp);

Execute Javascript  var kp = document.createEvent("KeyboardEvent"); kp.initKeyEvent("keypress",true,true,null,false,false,false,false,39,0); document.dispatchEvent(kp);

Execute Javascript  var kp = document.createEvent("KeyboardEvent"); kp.initKeyEvent("keypress",true,true,null,false,false,false,false,39,0); var x = document.getElementById('home-menu'); x.dispatchEvent(kp);
```

**Comment by pandabat** [comment]
Tried a few other things before finally deciding to try extending the existing library.

I'm using Fedora and I edited 

/usr/lib/python2.7/site-packages/Selenium2Library/keywords/_element.py

(could be different on Windows/Mac/Other Linux) 

and made a modification to check for a double-double-escaped (or quadruple-escaped) code (e.g \\\\ARROW_RIGHT). ASCII codes remain double-escaped only (e.g. \\65 = 'A'). When a '\\\\' is detected preceeding a code, the press_key method/function now maps the following code to the selenium.webdriver.common.keys as outlined on the page: http://selenium.googlecode.com/git/docs/api/py/webdriver/selenium.webdriver.common.keys.html

The modification is at bottom of post.

This now means that you now can use 'Press Key' to press these keys such as ARROW_UP, ARROW_DOWN, ARROW_LEFT, ARROW_RIGHT, HOME, META, PAGE_UP, TAB and so on.

Examples of usage:

Press Key    <some_element>   \\\\ARROW_RIGHT # press ARROW_RIGHT (right arrow/cursor)
Press Key    <other_element>    \\\\PAGE_UP          # press PAGE_UP button
Press Key    <fifth_element>       \\65                        # press ascii code 65 or 'A' 

Simple solution in the end - no idea why something like this isn't already integrated but maybe there are complications that I'm not aware of in its general use. Still might get some of you out of a hole until a fix is implemented in source

```
 def press_key(self, locator, key):
        """Simulates user pressing key on element identified by `locator`.

        `key` is either a single character, or a numerical ASCII code of the key
        lead by '\\'.

        Examples:
        | Press Key | text_field   | q |
        | Press Key | login_button | \\13 | # ASCII code for enter key |
        | Press Key | nav_console | \\\\ARROW_UP | # selenium.webdriver.common.keys ARROW_UP KEY
        """
        if key.startswith('\\\\') and len(key) > 1:
            key = getattr(Keys,key[2:])
        elif key.startswith('\\') and len(key) > 1:
            key = self._map_ascii_key_code_to_key(int(key[1:]))
        #if len(key) > 1:
        #    raise ValueError("Key value '%s' is invalid.", key)
        element = self._element_find(locator, True, True)
        #select it
        element.send_keys(key)
```

**Comment by HelioGuilherme66** [comment]
This is very useful.

How can we get this in next release?

**Comment by pandabat** [comment]
I have no idea :)

I'm glad that someone found it useful though and I was very surprised that it hadn't been done before (that I could find online) and that it wasn't part of standard release as it seems so straightforward.

It's the first bit of Python that I ever coded! :)

**Comment by emanlove** [comment]
@pandabat: Thank you for contributing this code. Sorry for the very long delay in responding.

I'm not sure why we can't simply allow one to use the selenium key variable, like

Press Key    ARROW_DOWN

If press key expects a single character with the idea that one can really only press a single key then if it is not a single character then it must be something else. No need to have a special syntax. This could be expanded to allow for many different representations of characters so all the following would be allowed

```
# a single character
H, e, L, L, o, !, @, #, $

# an escape code
\t, \n, \v

# an ascii code
\\0, \\8, \\43

# a selenium named key
ARROW_DOWN, F1, COMMAND

# and possibly ...

# unicode hex
&#x2318, &#x238B

# unicode decimal
&#8997, &#9099

# ... etc ... 
???
```

I need to test out the underlying selenium to see what hapens when some of these are passed to see what we might need to map and which ones gets "automatically" mapped by selenium.

**Comment by pandabat** [comment]
At the time I was just happy to find something that works but I don't know
what the best solution here is. I suppose the case where someone actually
wants the chars "ARROW_RIGHT" output by Press Key must also be considered.
i.e. How would the difference between the character sequence and the
selenium key variable be detected. I suspect many people (myself included
most likely) will use Press Key's current functionality of inputting a
string of characters which people won't want broken overnight if it can be
avoided.

**Comment by emanlove** [comment]
@pandabat: Keeping backwards compatability is important here. Currently this keyword does allow someone to "Press" or enter several keys at once which at one point it was prevented in doing so.  It looks like that change allowing more than one key to be pressed was inadvertently introduced back around version1.0.0 or early 2012 timeframe. The underlying code runs the same webdriver command as the 'Input Text' keyword except for the additional step of pre-clearing the text which 'Input Text' does.

[Thinking]. Well one could if they currently use press key use input text instead although I could see someone wanting to add text without clearing. We could add an additional optional flag to input text for ignoring the clear text command. They could modify by adding additional single character 'Press Key' keywords. Some options... @ombre42, @j1z0  any thoughts?

**Comment by ombre42** [comment]
We use Press Key to input text without clearing in some spots where clearing a field makes the AUT angry, so I agree with @pandabat about the breakage.
We still lack a solution for performing chords, like Ctrl+C and for pressing keys without specifying an element/locator (hmalphettes/robotframework-selenium2library-extensions provides both).

I think if you match the key against the key codes in the Keys class in a case-_sensitive_ manner, the amount of breakage will be very small. If done this way, I think it would only be fair to add an optional `clear` argument to `Input Text` contemporaneously.

**Comment by HelioGuilherme66** [comment]
Hi,

This is a reminder that I am working in a Press Keys keyword that allows to
send Ctrl-C or even Ctrl-Shift-Home.
I have already some acceptance tests working.

https://github.com/HelioGuilherme66/robotframework-selenium2library/tree/expand_press_key

Can you take a lock at it?

(The behavior in IEDriver is really slow.)

Thanks,
Hélio

**Comment by emanlove** [comment]
Hélio, yes I am looking at your implementation too.
