### ISSUE TITLE
firefox is lunched,then it is not responding when selenium2library work on windows7 32bit  with windows domain account

### ISSUE THREAD

**Issue by bluezhaocai** [robotframework/SeleniumLibrary#282]
execute keyword: "Open Browser  www.baidu.com"
firefox is lunched,then it is not responding when selenium2library work on windows7 32bit  with windows domain account.
but when I login in windows with administrator account, selenium2library works well. firefox can be lunched and open web site.

**Comment by aaltat** [comment]
Closing due inactivity. If this is still a problem, please report back.
