### ISSUE TITLE
"Confirm Action" function returns error message "There were no alerts"

### ISSUE THREAD

**Issue by yulogs** [robotframework/SeleniumLibrary#284]
Sorry, Can you help me?

I already update version:
robotframework==2.8.4
robotframework-ride==1.3
robotframework-selenium2library==1.5.0
selenium==2.40.0

thank you!!

**Comment by emanlove** [comment]
The best place to look for help with how to use certain keywords or with problems you are experiencing is the [robotframework-users group](http://groups.google.com/group/robotframework-users). Please post your question there.
