### ISSUE TITLE
Table lookup stratergies documentation incorrect

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#287]
The Selenium2Library documentation when describing the look-up strategies states
"More complex table look-up strategies are also supported:

<table border="1">
<tbody><tr>
<td><b>Strategy</b></td>
<td><b>Example</b></td>
<td><b>Description</b></td>
</tr>
<tr>
<td>css</td>
<td>Table Should Contain <span class="name">|</span> css=table.my_class <span class="name">|</span> text</td>
<td>Matches by @id or @name attribute</td>
</tr>
<tr>
<td>xpath</td>
<td>Table Should Contain <span class="name">|</span> xpath=//table/[@name="my_table"] <span class="name">|</span> text</td>
<td>Matches by @id or @name attribute</td>
</tr>
</tbody></table>

To me it looks as if the **Description** column is incorrect. Looking at the **Strategy** and the **Example** as well as the description for the element look-up strategies. I suspect that the CSS strategy should have a description of "Matches by CSS selector" and xpath - "Matches with an arbitrary XPath expression".

**Comment by emanlove** [comment]
In addition the description of the default table locator is vague in regards to what is the current used, css selector. The documentation states

> Table related keywords, such as Table Should Contain, work differently. **_By default, when a table locator value is provided, it will search for a table with the specified id attribute._** For example:
> 
>  Table Should Contain my_table text" [my emphasis]

This makes it sound like it searches by id as we do with the element locator (i.e. driver.find_element_by_id) when in fact it searches by css selector using the id (i.e. driver.find_element_by_css_selector) or css=table#_id_locator_.

**Comment by ombre42** [comment]
Also jQuery/sizzle support has been added for table locators but do not appear in this table.

**Comment by pekkaklarck** [comment]
This has been fixed as part of #924. Hopefully we get rid of differences between table locators and other locators in general as part of #923.
