### ISSUE TITLE
Add a keyword which highlights elements

### ISSUE THREAD

**Issue by anilreddy** [robotframework/SeleniumLibrary#289]
add keywords which highlights text and elements like success messages, etc

**Highlight Element**
**Highlight Text**

and also for every selenium command when executing like 

**Set Element Highlight**

**Comment by just-be-dev** [comment]
So, I'm not really sure what you're trying to do here. 

Do you want some text element selected? Are you trying to change the styling of something?

Until I know more I'm going to close this issue. There's probably a method build in that can do whatever it is you want to do.
