### ISSUE TITLE
pip reference in readme

### ISSUE THREAD

**Issue by gunthercox** [robotframework/SeleniumLibrary#290]
In the readme there is a line that says

```
pin install robotframework-selenium2library==1.4.1
```

`pin` should be `pip`
This isn't a major issue, but it might cause a bit of confusion.

**Comment by emanlove** [comment]
On 04/21/2014 06:56 AM, Gunther Cox wrote:

> In the readme there is a line that says
> 
> |pin install robotframework-selenium2library==1.4.1
> |
> 
> |pin| should be |pip|
> This isn't a major issue, but it might cause a bit of confusion.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/rtomac/robotframework-selenium2library/issues/290.

Fixed. Thanks Gunther!

Ed
