### ISSUE TITLE
Input Text bleeds into other text fields

### ISSUE THREAD

**Issue by Tallisado** [robotframework/SeleniumLibrary#291]
When targeting Sencha textfields with text, it will bleed into completely different fields.

The following code to reproduce:

```
*** Settings ***
Suite Setup
Suite Teardown    Close Browser
Library           Selenium2Library
Library           Collections

*** Variables ***

*** Test Cases ***
Login
    Open Browser    http://dev.sencha.com/deploy/ext-4.0.0/examples/writer/writer.html    browser=chrome

Set Profile Settings
    Input Text    name=email    ${EMPTY}
    Input Text    name=email    (613) 123-4567  
    Input Text    name=first    ${EMPTY}
    Input Text    name=first    (613) 123-9999
    Textfield Should Contain    name=email    (613) 123-4567
    Textfield Should Contain    name=first    (613) 123-9999
    Sleep    5
```

Attaching screenshot
![image](https://cloud.githubusercontent.com/assets/5503681/2907316/da86442a-d61a-11e3-84ca-22dc6f264d23.png)

**Comment by HelioGuilherme66** [comment]
Hi,

I have just run your test (exact copy) and passed OK.
Tested in Fedora 19 x64 and:
robotframework==2.8.4
robotframework-ride==1.3
robotframework-selenium2library==1.5.0
robotframework-sshlibrary==2.0.2
selenium==2.41.0

$ google-chrome --version
Google Chrome 34.0.1847.132

Hélio

**Comment by Tallisado** [comment]
Thanks for testing, 

I've verified that im on all the same versions. (Debian 7.4)

Note that the test didnt have any validation on the fields, It was just a visual validation - so the test would have passed regardless. I'm going to update the test code with the following validation to be sure:

```
    Textfield Should Contain    name=email    (613) 123-4567
    Textfield Should Contain    name=first    (613) 123-9999
```

**Comment by HelioGuilherme66** [comment]
Tested with:
Validate Profile Settings
    Textfield Should Contain    name=email    6131234567
    Textfield Should Contain    name=first      6131239999
    Capture Page Screenshot

Well, test fails but your problem (text bleeding) does not occur.

Validate Profile
Settings                                                       | FAIL |
Text field 'name=email' should have contained text '6131234567' but it
contained '613123-4567'

(you had 1111234567 to validate)

In my system I do not use chrome, but firefox as main browser. Maybe you
should try to clear the browser cache before starting the test.

**Comment by j1z0** [comment]
You might also try adding some explicit waits to ensure fields are completely rendered prior to calling set text. 

Cheers,
Jeremy

**Comment by Tallisado** [comment]
Thanks for the suggestions! Unfortunately clearing the cache and explicit waiting did not address the issue.

Firefox did execute this test correctly, it seems that this is an issue with Chrome. The test is failing in both the following versions:
-  Chromium 34.0.1847.132 Built on Debian 7.5, running on Debian 7.4
-  Google Chrome 34.0.1847.116

**Comment by ombre42** [comment]
I was unable to reproduce the bleeding issue using Chrome 37.0.2062.124 m and Chromedriver v2.8.241075 on Windows 7. I am confident this is an issue outside of this project. Please report this to the Selenium issue tracker for resolution if this is still an issue for you.
