### ISSUE TITLE
Add ability to type into a prompt

### ISSUE THREAD

**Issue by boakley** [robotframework/SeleniumLibrary#292]
Right now it is not possible to type into a javascript prompt -- the only options are to confirm or cancel an alert.

I would like support for a keyword like "Insert into prompt" that would type into a prompt. 

I did a quick prototype on my mac, and it seemed pretty easy to implement:

<pre>
    def insert_into_prompt(self, text):
        alert = None
        try:
            alert = self._current_browser().switch_to_alert()
            alert.send_keys(text)

        except WebDriverException:
            raise RuntimeError('There were no alerts')
</pre>

**Comment by emanlove** [comment]
Sounds like a good suggestion.

**Comment by pekkaklarck** [comment]
Should probably be named like "Input Text Into Prompt" to be consistent with "Input Text".

**Comment by Kristina001** [comment]
Hey guys..
Will it helps me for my probleM?

My problem is the following:
I have an upload form, and when I do upload file and click a button - my web-application automatically send me a new file for downloading. I can't handle this firefox downloading window  :(

Im fighting with this for like a several days ...

**Comment by ombre42** [comment]
@Kristina001 I do not think this will help for your situation unfortunately. This is for the JS method Window [prompt](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt).

**Comment by SerhiiAksiutin** [comment]
When I do something like 
`Go to  https://username:password@mytestwebsite.com`
`Input Text Into Prompt  ${url_username}`

(Or you can just open Privet window) I get this. Does it look like an alert? If so then "Input Text Into Prompt" keyword doesn't work for Safari Technology Preview Release 33 (Safari 11.0, WebKit 12604.1.25.0.2)

<img width="1280" alt="screen shot 2017-06-18 at 10 40 08 am" src="https://user-images.githubusercontent.com/27512156/27262880-ac86f6a2-5414-11e7-8275-411de02b7b33.png">

**Comment by aaltat** [comment]
Please open a new issue or send mail to the Robot Framework user group.

**Comment by ShAnsari** [comment]
Is this issue solved?

**Comment by aaltat** [comment]
See https://github.com/robotframework/SeleniumLibrary/issues/827

**Comment by antho03** [comment]
It's ok for type in first username textfield but how can i input on password field ?

**Comment by aaltat** [comment]
Please ask the question in the Robot Framework user group or open a new issue. First one is preferred.

**Comment by Ballalokesh** [comment]
hi above issue got solved?? please let me know i am also facing same issue now

![image](https://user-images.githubusercontent.com/45655492/49576007-1f31b100-f96a-11e8-8aa5-ae6a5f4f5ed7.png)

**Comment by Ballalokesh** [comment]
Hi above issue got solved?? please let me know i also facing similar kind of problem.

**Comment by satymaju** [comment]
Hi,
How to input text into alert when there are two fields ?
Anyone figured out how to input text in the alert second input field(for example: password field) ?

Thanks, 
Satya

**Comment by satymaju** [comment]
> When I do something like
> `Go to https://username:password@mytestwebsite.com`
> `Input Text Into Prompt ${url_username}`
> 
> (Or you can just open Privet window) I get this. Does it look like an alert? If so then "Input Text Into Prompt" keyword doesn't work for Safari Technology Preview Release 33 (Safari 11.0, WebKit 12604.1.25.0.2)
> 
> <img alt="screen shot 2017-06-18 at 10 40 08 am" width="1280" src="https://user-images.githubusercontent.com/27512156/27262880-ac86f6a2-5414-11e7-8275-411de02b7b33.png">

Yes , I am getting the same problem it is not an alert. 
Have you been able to find how to input text there, without the url technique(https://username:password@mytestwebsite.com`) ?

**Comment by aaltat** [comment]
See https://github.com/robotframework/SeleniumLibrary/issues/292#issuecomment-310044552 and for support read https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
