### ISSUE TITLE
S2L and Selenium 3 protocol?

### ISSUE THREAD

**Issue by skipkent** [robotframework/SeleniumLibrary#299]
We have a large existing codebase using Appium 0.18.2 along with Robot Framework and the Selenium2Library. The testing centers around an Android wrapped application, and works great with the Appium 0.18.2 server.

This breaks, however, when upgrading to Appium 1.x.  In this case, the switch to webview fails because doing so now requires the use of driver.contexts, which is not currently available with S2L.  The 'migrating to 1.0' page on the appium site explains it better than I can:

(See 'Hybrid support through context, not window')
https://github.com/appium/appium/blob/master/docs/en/migrating-to-1-0.md

I raised an issue with the Appium dev and he suggested the following:

"I think Robot Framework probably needs to be updated so that it can work with the selenium 3 protocol. Maybe someone can make an Appium extension to Robot Framework.

The only workaround I can suggest right now is patching the driver object you get with Robot Framework to include the context commands. You can take a look at the appium-client code to see how that's done."

That's way beyond my current coding capabilities, unfortunately.  Is support for the Selenium 3 protocol something you might be addressing yourself in the future?

**Comment by skipkent** [comment]
It would be great to get some input on this.  Is there any other information I can offer to clarify my question?

**Comment by pekkaklarck** [comment]
I know nothing about Selenium 3 nor Appium, but apparently someone has already implemented a library for it:
https://pypi.python.org/pypi/robotframework-appiumlibrary/1.0.13

**Comment by skipkent** [comment]
We're pretty closely tied to the current Selenium2Library, but that looks very promising.  Thanks for sending it along!

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
