### ISSUE TITLE
Test for Choose File expects full path but returned value is only the filename 

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#305]
To have Travis build green, it would require the decision to change the test to expect only the filename. The returned value from the browser in not under our control.

Test with firefox:
Value of text field 'file_to_upload' should have been '/home/helio/robotframework-selenium2library/test/acceptance/keywords/temp.txt' but was 'temp.txt'

Test with PhantomJS and Google Chrome:
Value of text field 'file_to_upload' should have been '/home/helio/robotframework-selenium2library/test/acceptance/keywords/temp.txt' but was 'C:\fakepath\temp.txt'

(Tested under Fedora Core 19 x86_64, Firefox 31, PhantomJS 1.9.7 and Google Chrome 36.0.1985.125)

**Comment by HelioGuilherme66** [comment]
This is fixed by https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/532295cbce3c27d83d003ea07aaf5130ea685cfe and https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/cddb4fca0094be83c59ed5fde097bccebe12ffe9 .

**Comment by HelioGuilherme66** [comment]
Choose File fails in IE because its result may contain capitalized letters, and there is an exact comparison in the text box.
This https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/ae494a863eec9b2b227d767554e3ca7219965f6d fixed Choose File test by adding a casesense option (True by default) to TextField Value Should Be.

**Comment by just-be-dev** [comment]
It looks like this issue was resolved.
