### ISSUE TITLE
Firefox becomes unresponsive

### ISSUE THREAD

**Issue by know1nos** [robotframework/SeleniumLibrary#307]
Some of our testers have been seeing their Firefox test cases/ keywords cause the browser to become unresponsive in multiple suites that had been running fine for months.  The same keywords are used for internet explorer and chrome and still work fine.  Has anyone else experienced this issue/ know what is causing it or how to resolve it?

**Comment by xiongjiaji** [comment]
I also came across this problem.

**Comment by just-be-dev** [comment]
I don't really have a whole lot to go on here so I'm going to close this issue. If you're still having these issues and can narrow down the problem let me know and I'll reopen his issue.
