### ISSUE TITLE
Rename acceptance tests to use `.robot` extension instead of `.txt`

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#312]
This makes it easier to distinguish between test case files and possible normal text files. In practice that means that many RF editor plugins will recognize them automatically, and also GitHub will syntax highlight them.

This change was recently done for Robot Framework itself (robotframework/robotframework#1766). That required more work because we also wanted to convert remaining HTML files to plain text format and clean-up test data in general. For an example file that is now syntax highlighted see https://github.com/robotframework/robotframework/blob/master/atest/testdata/standard_libraries/xml/add_and_remove_elements.robot

**Comment by HelioGuilherme66** [comment]
I have renamed tests in this commit: https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/c264f5fa5af1bec21d7a66f3f4999acd499f3d52 (this commit also changed travis.yml to pass tests).

You could use only the shell script in the end of the commit.

**Comment by just-be-dev** [comment]
I'm very much in favor of this. I'll try to target this after the 1.7 release.
