### ISSUE TITLE
Browsers HTMLUNIT and HTMLUNITWITHJS fail to start (Desired Capabilities can't be None)

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#314]
Please forgive me if they are no longer supported, if so documentation must be updated.

Here are my experiments outputs:
$ pybot -v BROWSER:phantomjs simple_test.robot

= =============================================================================
Simple Test  
= =============================================================================
## browser_test                                                          | PASS |

Simple Test                                                           | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
= =============================================================================
Output:  /home/helio/robotframework-selenium2library/test/output.xml
Log:     /home/helio/robotframework-selenium2library/test/log.html
Report:  /home/helio/robotframework-selenium2library/test/report.html
pybot -v BROWSER:htmlunit simple_test.robot

= =============================================================================
Simple Test  
= =============================================================================
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
browser_test                                                          | FAIL |
## WebDriverException: Message: "Desired Capabilities can't be None"

Simple Test                                                           | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
= =============================================================================
Output:  /home/helio/robotframework-selenium2library/test/output.xml
Log:     /home/helio/robotframework-selenium2library/test/log.html
Report:  /home/helio/robotframework-selenium2library/test/report.html

pybot -v BROWSER:htmlunitwithjs simple_test.robot
= =============================================================================
Simple Test  
= =============================================================================
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
browser_test                                                          | FAIL |
## WebDriverException: Message: "Desired Capabilities can't be None"

Simple Test                                                           | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
= =============================================================================
Output:  /home/helio/robotframework-selenium2library/test/output.xml
Log:     /home/helio/robotframework-selenium2library/test/log.html
Report:  /home/helio/robotframework-selenium2library/test/report.html
[helio@localhost test]$ cat simple_test.robot 
**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
browser_test
    Open Browser    http://www.google.com/    ${BROWSER}
    Capture Page Screenshot
    Close Browser

**Comment by ombre42** [comment]
HTMLUnit and HTMLUnitWithJS are remote-only WebDrivers. `Open Browser` will not work without passing in a value for `remote_url`. The Python bindings cannot start the browser and  driver server. This has to be performed prior to `Open Browser` using `Process.Start Process` or similar.
