### ISSUE TITLE
needed a Get Weblement(s) keyword

### ISSUE THREAD

**Issue by KD1102** [robotframework/SeleniumLibrary#315]
Hello,

I was working on a test for selecting a date from datePicker. By mentioning simply the xpath of the webelement from the calendar, but to requirement is to select (Now+2d) add 2 days to the current day.
Right now, i have to hard code the table cells (tr and td) to select the date.
But to create a dyanmic xpath, i need to work on webelements, which is missing right in current version of Selenium2Library. For example, code implemented in Java- Webdriver,

/*DatePicker is a table.So navigate to each cell  
         \* If a particular cell matches value 13 then select it  
         */  
        WebElement dateWidget = driver.findElement(By.xpath("//table[@class='ui-datepicker-calendar']"));  
        List<WebElement> columns=dateWidget.findElements(By.tagName("td"));  

```
    for (WebElement cell: columns){  
        //Select 13th Date   
        if (cell.getText().equals("13")){  
            cell.findElement(By.linkText("13")).click();  
            break;  
        }  
    }  
```

I want to re-do this code in Robotframework.

Kindly help.

Regard,
Kuldeep

**Comment by ombre42** [comment]
@emanlove has proposed doing this in the [forums](https://groups.google.com/d/msg/robotframework-devel/MbYs1y_1WkQ/EX0B9yoW7xAJ) so this functionality will probably be coming somewhat soon. In the mean time, you should be able to construct an XPath selector that will select the correct element, something similar to `//table[@class='ui-datepicker-calendar']//td[.='13']/a`. For help on that please post the [Robot Framework user group](https://groups.google.com/forum/#!forum/robotframework-users).

**Comment by ombre42** [comment]
One option that may be worth considering is to add an argument first_only, which would control whether Get Webelements returns a single WebElement or a list of them. For example,
`${elem}=    Get Webelements    xpath=//*    True` returns a single WebElement, but `${elems}=    Get Webelements    xpath=//*` returns a list of WebElements (possibly a list of one WebElement).
This would help avoid keyword pollution by avoiding the need for a separate Get Webelement keyword.
Just a thought...

**Comment by pekkaklarck** [comment]
More generic `index` could be even better.

**Comment by emanlove** [comment]
[Here is my implementation](https://github.com/emanlove/robotframework-selenium2library/compare/webdriver-element), as it currently stands from about a month ago. I like @pekkaklarck's idea of 'index'. Listening to your suggestion @ombre42 I was thinking we had several of these dual perform action on one and perform action on many keyword pairs. So I was thinking why not. But reviewing the keyword list I see actually very few; just _Get Selected List Label_/_Get Selected List Labels_ and _Get Selected List Value_/_Get Selected List Values_. Looking at just the documentation I can't see the difference between the singular vs multiple keywords. So I see your point and agree that having only _Get WebElements_ with possibly some sort of index/first/last filter is better.

**Comment by ombre42** [comment]
I agree @pekkaklarck 's idea is good. The difference being that with first_only (or a separate Get Webelement), returning None if no elements were found is the behavior I was thinking. With an index, it would make more sense to have the keyword fail. With XPath, one could do `Wait Until Page Contains Element    xpath=(//div[@name='foo'])[3]` to wait for at least 3 matches before trying to fetch the 3rd element with Get Elements, so I think this is okay. Any thoughts on this?

Even though Get Element is more consistent with the other keywords, it conflicts with the XML library, so I like the idea of Get Webelements more. WebElement is what the class is actually called and the term used in the Selenium world anyways.

**Comment by ombre42** [comment]
Hmmm...after @pekkaklarck comments elsewhere I'm having some doubts about whether Get Webelements is better then Get Elements....
- _Get Element Text_ already conflicts with a keyword in XML
- Get Element is more generic, in line with how Selenium is being used outside of HTML and HTML-based applications (e.g. native apps with Appium)
- As noted before, _Get Elements_ is more consistent with existing keywords in this library

**Comment by pekkaklarck** [comment]
It's a good point that there are already conflicts with XML library and that also other keywords talk about _Element_. In this case the benefit of _WebElement_ would be that it makes it more clear the keyword deals with exactly those Selenium objects. That can easily be explained in the documentation, though, and talking about _Web_ would definitely be weird outside HTML context.

**Comment by ponkar** [comment]
Hello ,

This is something I was looking to iterate accross few elements to check their attributes. What is the status of this implementation. Is it pushed to the repo ?

**Comment by ombre42** [comment]
@ponkar have not heard from Ed. His last commit was at the end of August.
As a temporary workaround, you can use Execute Javascript to return elements or invoke _element_find.

**Comment by ponkar** [comment]
Ok Can any one comment if it is in development plan that anyone is working on it

**Comment by emanlove** [comment]
@ponkar, @ombre42: I have [added some initial documentation changes](https://github.com/emanlove/robotframework-selenium2library/commit/41982661996877ebd014bda042b2ba14f6f59db6) to the Selenium2Library Introduction and section about locators. I am still working out formating and wording so any suggestions are welcome.

**Comment by ombre42** [comment]
Still analyzing, but wanted to suggest changing Get Element Attribute to support using a webelement as a locator. It would be easy to do in a backwards compatible way by adding a `name` argument that supersedes parsing `attribute_locator` for an attribute name.

**Comment by just-be-dev** [comment]
Resolved with #365

**Comment by aliasgerkw** [comment]
Sorry for the commenting on closed thread, can we have a keyword wrapped around Get Web Elements which will do operations on the list return by this? For example, If in an application I filtered a column and want to verify if the results are there in each row I can simply do below:
@{elList} =                                         Get webelements                                     ${OR_CELL_TO_CHECK}
    :FOR    ${item}     IN      @{elList}
      ${textOfAcc}=       Get Text                ${item}
      Should Be Equal     ${textOfAcc}            ${SHOULD_CONTAINS}
    END

We can have multiple keywords using this like:
Get elements and verify the text
Get elements and verify attribute
Get elements and verify does not contains text

Please advise. Thanks!

**Comment by aaltat** [comment]
Well, you can get, at least almost, similar result by using [Page Should Contain Element](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Page%20Should%20Contain%20Element) keyword `limit` argument and using xpath. See the keyword documentation how limit argument works and [example](https://stackoverflow.com/questions/2994198/xpath-to-return-only-elements-containing-the-text-and-not-its-parents) how xpath can be used to locate text from element. If this does not solve your problem, please open a new issue and lets move discussion in there.

**Comment by aliasgerkw** [comment]
Thanks @aaltat 
Let me try this otherwise will open a new issue.
