### ISSUE TITLE
Add captureNetworkTraffic in Selenium2Library

### ISSUE THREAD

**Issue by sachin6757** [robotframework/SeleniumLibrary#319]
Selenium has option to capture network traffic. It would be great to have this supported in the Selenium2Library

**Comment by ombre42** [comment]
That functionality was present in the older, pre-WebDriver Selenium a.k.a. Selenium 1 and it was not fully developed either from what I gather.

There are tools such as [BrowserMobProxy](https://github.com/lightbody/browsermob-proxy) and [Fiddler Core](http://www.telerik.com/fiddler/fiddlercore) you can use to capture the traffic. Selenium2Library provides the capability to pass in proxy information to use these tools (not necessarily easy).

It does not make sense to integrate a proxy server directly into Selenium2Library, as this functionality would be useful for other testing tools utilizing HTTP. I hope someone makes a BrowserMobProxy library as I think there is demand for it.
