### ISSUE TITLE
'Capture Page Screenshot' should create directories as needed

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#324]
If the output directory has a directory named _foo_,
`Capture Page Screenshot    foo/bar.png`
will work.

If the directory _foo_ does not exist in the output directory, the screenshot will not be saved (quietly so due to #322).
This is a bit of a gotcha that could easily be solved with `os.makedirs`.

**Comment by just-be-dev** [comment]
This issue is being addressed in #381 and is slated for release in 1.7.0.
