### ISSUE TITLE
Clarify differences in keyword documentation

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#325]
There are a couple of similar keywords _Get Selected List Label_/_Get Selected List Labels_ and _Get Selected List Value_/_Get Selected List Values_ for which one can not easily tell the difference between the pairs. It would be helpful to clarrify the difference and possible make reference to the other.

**Comment by aaltat** [comment]
The documentation was enhanced in SeleniumLibrary 3.0 and none has raised this as a problem. Therefore closing the issue.
