### ISSUE TITLE
Waiting untill element is not in the page. 

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#327]
Sometimes, example waiting for ajax calls that filters a table, it would nice to poll the page that the element is not in the page. I know that I can already do this by for loop, "page should not contain" and "run keyword if" keywords but it would be really nice if S2L would come out of the box with "Wait Until Page Does Not Contain Element" keyword

**Comment by winko** [comment]
I can confirm that the "Wait Until Page Does Not Contain Element" keyword is a very useful and required one!

**Comment by klemmster** [comment]
it's one of the waiting keywords referenced in  #246

**Comment by just-be-dev** [comment]
Since this kinda duplicates the #246 request I'm going to close this in favor of that.
