### ISSUE TITLE
Selenium2Library is not in PyPI

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#33]
The biggest problem this causes is that, for example, `pip install Selenium2Library` does not work.

Adding the library into PyPI is easy. If you only want to submit the package metadata, all you need to do is running `python setup.py register`.

For more information see:
http://pypi.python.org
http://wiki.python.org/moin/CheeseShopTutorial

**Comment by j1z0** [comment]
Pekka,

I will get this done next week.  I'm just slammed right now due to a
deadline at work.  But next week we are going to have a new . release of
S2L and I'll get it up on PyPI as well.

Cheers,
Jeremy

On Wed, Feb 1, 2012 at 5:24 AM, Pekka Klrck <
reply@reply.github.com

**Comment by pekkaklarck** [comment]
Great to hear there's going to be a new version next week! By then RF 2.7 alpha 2 ought to be available and also pip installable.

**Comment by pekkaklarck** [comment]
Any news about the new release? I would like to recommend Se2Lib over SeLib for people in general but the current release contains too old bundled Selenium version to be usable. If I've understood it correctly, future releases won't have bundled Selenium anymore so it will be easy to update it separately.

**Comment by j1z0** [comment]
We are just trying to fix a few remaining bugs,  the release should come soon. 

Cheers,
Jeremy

**Comment by rtomac** [comment]
Version 1.0.0 has been released and is now on PyPI, closing this issue.
