### ISSUE TITLE
Key Click Element keyword not found in _element.py

### ISSUE THREAD

**Issue by gobblygeek** [robotframework/SeleniumLibrary#330]
According to https://github.com/rtomac/robotframework-selenium2library/commit/15721d1eed063bdeda5818a0c02842a7aadab023, a keyword called Key Click Element was added to robotframework-selenium2library

I did a pip install of robotframework-selenium2library in April, and this keyword is not found in the file referenced. I tried to do an update using pip install --upgrade robotframework-selenium2library, and it's still nowhere to be seen. Is it only available in beta, or is there something wrong with my pip command?

Please advise.

**Comment by ombre42** [comment]
That commit belongs to #249, which is a pull request that has not been merged, so this code is not a part of this project (yet). Installing from the source would not make this feature available in other words.

**Comment by gobblygeek** [comment]
Thanks.
