### ISSUE TITLE
jquery,sizzle,dom locator strategies do not honor implicit wait setting

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#337]
This issue is not affecting me, but I noticed this inconsistency.
Since these strategies use `execute_script` instead of selenium's built-in methods to locate elements, the implicit wait code in Selenium is not used. This could be handled on the client side by adding a polling/timeout mechanism.

Fails immediately instead of after 20 seconds:

```
    Set Selenium Implicit Wait    20 seconds
    Page Should Contain Element    jquery=#bad_id
```

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
