### ISSUE TITLE
Open Context Menu not working with phantomjs

### ISSUE THREAD

**Issue by hellmanj** [robotframework/SeleniumLibrary#346]
This appears to be a phantomjs issue (see https://github.com/ariya/phantomjs/issues/11429) but it doesn't seem to be getting fixed.  There is a javascript-based workaround in the issue comments which does seem to work.  Is it appropriate to alter `Open Context Menu` with special logic for phantomjs that uses this workaround?

**Comment by just-be-dev** [comment]
I believe this may have already been (resolved)[https://github.com/n1k0/casperjs/commit/8e83c265ac895cfca58b8e02eeefa655c94ec0fa]. If this issue comes back up when we migrate over to saucelabs I'll investigate it more.
