### ISSUE TITLE
Add argument [index_or_alias] to the  Keyword "Close browser"

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#347]
Hi,

It would be great to add argument [index_or_alias] to the  Keyword "Close browser" as already is in keyword Switch Browser.

**Comment by Gaurang033** [comment]
@chevi I could write this. however, would like to know what is the exact use case of it. Most of the time, if you are doing some action and a new browser opens you can switch to that browser, do some action or not (depends on your test case) and then close the browser.

**Comment by chevi** [comment]
@Gaurang033 

Case was when you operate with several users in different browsers in the one test. So in teardown I need to Close browser of user2, but leave browser of user1. I already resolve this issue with robot framework keyword. I think there is no need to implement with the library.

**Comment by aaltat** [comment]
It seems that issue was resolved and therefore closing the issue. If you feel that issue should be left open, please send a message and we will re-open the issue.
