### ISSUE TITLE
Add help on docs about common tools how to find correct xpath

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#350]
Most/many of the new users questions are related to validating the selector that they have used. It would ease the pain of new users if we would list some of the default tools that would ease the pain of creating selectors in the web world. Like Firebug and firepath for ff and developer tools for chrome.

**Comment by just-be-dev** [comment]
Hey @aaltat, thanks for your input!

Right now we're going to hold off on this issue. While I agree there could be more information about selectors and how to use selectors, I don't necessarily agree that the docs for this library is the best place for that kind of tutorial. 

With that being said, if you see a place where you think more documentation would be appropriate, feel free to submit a PR and I'll review it for you.
