### ISSUE TITLE
Add a keyword to check focus

### ISSUE THREAD

**Issue by email2vimalraj** [robotframework/SeleniumLibrary#351]
Add a keyword to assert the focus of the element. Currently we have a keyword 'Focus' to focus on the given locator, but missing the assertion for the same.

**Comment by just-be-dev** [comment]
@email2vimalraj What do you mean specifically? Like `Element Should Be Focused`?

**Comment by email2vimalraj** [comment]
@zephraph, really sorry for replying you late.

Yes I'm expecting a keyword like `Element Should Be Focused`.

**Comment by just-be-dev** [comment]
Okay, I'll take a look.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by pekkaklarck** [comment]
This is nowadays implemented. See #851.
