### ISSUE TITLE
On IE9, "click element" does not work after switch from other window

### ISSUE THREAD

**Issue by cyllouis** [robotframework/SeleniumLibrary#353]
On IE9, opened 2 windows (A, B). Try to switch window from B to A, use command: Select window | title=A;
And then try to click on one element in A to logout, cmd: click element | css=a.layer-picture-link[title="Sign out"]
it does not work.
While, it works well with Firefox, but when turn to IE9, it does not work.
There is not error reported in this step, but the "click" operation did not work, the page was remained no change.
And if I use cmd "click element" twice, it works.

**Comment by cyllouis** [comment]
Sorry, seems it has been fixed in 1.6.0

**Comment by emanlove** [comment]
If this issue reappears open a new ticket.
