### ISSUE TITLE
Add keyword "Wait Until Page Title Contains"

### ISSUE THREAD

**Issue by alexhaller** [robotframework/SeleniumLibrary#354]
Hi,

I miss the given keyword in the heading. I want to wait till a page is loaded but I don´t want to check if there´s a certain element on the site. I need the page title.

It would be great if you can add this keyword.

Thx a lot!

Best regards,
Alex

**Comment by just-be-dev** [comment]
This is already listed under #246. I'm closing it as a duplicate.
