### ISSUE TITLE
'Get List Items' keyword documentation should reference 'labels'

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#357]
The 'Get List Items' keyword documentation states "Returns the values in the select list " when it really should read "Return the labels" and not "values". For example if the page contains the following 

``` html
    <select name="preferred_channel">
        <option value="email">Email</option>
        <option value="phone" selected>Telephone</option>
        <option value="directmail">Direct mail</option>
    </select>
```

then a call to 'Get List Items' would return Email Telephone and Direct Mail not email, phone, and directmail. Or it would return the option text and not "value" attribute.

**Comment by aaltat** [comment]
This is fixed in #721 It was made configurable that does the keyword return labels or values.
