### ISSUE TITLE
Add Location Strategy Keyword

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#364]
The first selenium library had the `Add Location Strategy` keyword. It essentially allowed for instances like [this](https://github.com/MarkusBernhardt/robotframework-selenium2library-java/blob/master/src/test/robotframework/testsuites/UnitTests/ExtJS.txt) which is exactly what I happen to need at the moment. 

Is there a particular reason why it isn't present? I found the [java implementation](https://github.com/MarkusBernhardt/robotframework-selenium2library-java/blob/master/src/main/java/com/github/markusbernhardt/selenium2library/locators/ElementFinder.java#L237) of this keyword.

**Comment by emanlove** [comment]
We were actually having a discussion within #333 about allowing user specified locator strategies. Just curious what type of element are you trying to locate that is already satisfied by the current strategies?

**Comment by just-be-dev** [comment]
I want to locate using ExtJs' component query (see the _this_ link above. What I have in mind is basically a javascript locator. Already working on a PR. 

It's pretty much exactly what's implemented in the Java version I linked to.

**Comment by emanlove** [comment]
Looking at that [example](https://github.com/rtomac/robotframework-selenium2library/issues/333) what I see is this is a javascript locator. Just wandering if there is other locator type that we can implement with a very similar keyword/argument syntax that is not javascript based. The reason I ask is to see if we need to add an argument that states which method the locator code implements. Something like

```
Open Page
  # 'Add Location Strategy'  | strategy name | strategy method |  stategy implementation "code" 
  Add Location Strategy extJs  javascript return window.document.getElementById((Ext.ComponentQuery.query(arguments[0])[0]).getId());
```

Better to add it now then trying to patch in later.

**Comment by just-be-dev** [comment]
Well, I suppose that's entirely possible. You could just provide it with a python function to run. It wouldn't be all doable from within RF, but I feel like this is somewhat of a special case anyway so I think that'd be acceptable. 

Edit: After thinking about it a bit I've got a pretty good idea of how we can implement general, reusable solution. I'll get back to you when I have a basic implementation done.

**Comment by just-be-dev** [comment]
See #365 for progress on this issue.
