### ISSUE TITLE
Choose File does not fail on invalid file path

### ISSUE THREAD

**Issue by stevejefferiesIDBS** [robotframework/SeleniumLibrary#372]
Currently "Choose File" checks for the files existence (os.path.isfile) and will log an info statement if the file does not exist, but does not fail the keyword. This causes issues when the browser is interacting with a native select file dialog, such as the IEDriver does. In the case of IE the test then hangs since the native dialog cannot be closed.

**Comment by just-be-dev** [comment]
@stevejefferiesIDBS I'll take a look at this for you.

**Comment by just-be-dev** [comment]
@stevejefferiesIDBS Assuming there are no objections you can expect to see this in the coming 1.7.0 release.
