### ISSUE TITLE
Get window titles failing for FF, py 2.6

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#374]
A lot of PRs have failures on travis because `Get Window Titles` failed on python 2.6. It's possible this is because of a change in the selenium 2 dependency that dropped some 2.6 support.

**Comment by just-be-dev** [comment]
I've marked this as a known issue on #379. This should probably still be investigated though.

**Comment by sbrugman** [comment]
Got the same problem. The `Get Window Titles` cannot be used now to check whether for instance a window is open or selected.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closing due inactivity

**Comment by deepakaravind** [comment]
I am encountering the same issue with all the browsers.  Get Window Titles keyword worked perfectly fine with Selenium2Library - but does not work after we upgraded to SeleniumLibrary.  Fails with the following error : "UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)"

**Comment by aaltat** [comment]
I am pretty sure that your issue is not the same as this one. Please open a new issue because Python 2.6 is not been supported for ages.

Could you open a new issue and tell what Selenium, driver and browser version you are using. Also could you provide the full stack trace of the error, by running test with `--loglevel trace` set from command line.

**Comment by deepakaravind** [comment]
Sure thanks @aaltat Will create a new issue and add those details.
