### ISSUE TITLE
Choose file sends file as application/octet-stream, but needs text/csv

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#378]
Hi,

I want to test functionality where user uploads csv file. And on server there is verification of the uploaded file type:

```
file_content_type != 'text/csv' && file_content_type != 'application/vnd.ms-excel'
```

When I make "Choose file" with Selenium2Library and submit, I get error from server that file type is incorrect. Basically it was sent as **application/octet-stream** type, but when I do the same manually, browser sends **text/csv** type.

Is it possible to add additional parameter to the keyword "Choose file", where will be possible to specify file type?
Example:

| Keyword | locator | path | file type |
| --- | --- | --- | --- |
| Choose file | file | test.csv | text/csv |

**Comment by just-be-dev** [comment]
I'll take a look at this.

**Comment by just-be-dev** [comment]
Okay, so I haven't messed with form uploads in a while and I was reading up on this.

I assume when you did this manually you pulled up the file browser dialog and selected the file that way. When the RF-S2L selects a file it simply types the file name into the upload dialog box. My hypothesis is that your browser then doesn't specify what the mime type for whatever reason and just falls back to _application/octet-stream_. The bad news here is, there's no way (that I have found) to set the mime type. 

So technically as per your suggestion this doesn't seem to be possible. There may be a work around to fix your particular issue, but that'll require some more investigation. What browser are you testing this against?

**Comment by chevi** [comment]
Thanks for you response

After you commented, I've checked with other browsers that I have and results are:

Works on: 
- Firefox 37.0.1

Doesn't work on: 
- Chromium 41.0.2272.76 (webdriver 2.15)
- google-chrome-stable 42.0.2311.135-1 (webdriver 2.15)

OS environment:
Ubuntu 14.04

**Comment by just-be-dev** [comment]
Thanks for getting me that info @chevi! 

After doing some more investigation into this it seems it's a issue with the chrome webdriver. This issue has also been reported on their ticket tracker [here](https://code.google.com/p/chromedriver/issues/detail?id=915&#makechanges). I've mentioned that you're having an issue with it as well, but you're more than free to make a comment on that issue. 

There's nothing really I can do on my side. Hopefully they'll fix that issue soon.
