### ISSUE TITLE
Support user created action chains

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#386]
Selenium has a concept of [action chains](http://selenium-python.readthedocs.org/en/latest/api.html#module-selenium.webdriver.common.action_chains) which supports complex user interactions.  If we could somehow facilitate the creation of action chains we could give the ability to accomplish things like #249 without modifying the base library. 

My initial thoughts go something along this line

``` robotframework
${action chain}=   Create Action Chain
Chain  ${action chain}  key down  shift
Chain  ${action chain}  click  id=my_button
Chain  ${action chain}  key up  shift
Perform  ${action chain}
```

Here there are three keywords: 
- `Create Action Chain` which initializes the action chain object
- `Chain` which chains together a new action on the specified action chain
- `Peform` which executes the given action chain. 

The arguments of chain would be the icky part. They could just be strings that are interpolated into the corresponding function and arguments. Anyway, it would still be interesting functionality. 

Thoughts?

**Comment by pekkaklarck** [comment]
What benefits this would have compared to creating a user keyword with same functionality?

If this is considered a useful feature, I'd still like keyword names to be a bit more explicit. `Create Action Chain` is good, but would change `Chain` to `Add to Action Chain` and `Perform` to `Perform Action Chain` or `Execute Action Chain`.

**Comment by ombre42** [comment]
@zephraph Have you looked at [robotframework-selenium2library-extensions](https://github.com/hmalphettes/robotframework-selenium2library-extensions)?
I'm not implying anything here. I just wanted to make sure you were aware of that project.

**Comment by just-be-dev** [comment]
@ombre42, good call. I hadn't seen that. That hasn't really been touched in a while though, so it's still something we could look at doing. 

@pekkaklarck, there may be no benefit to it. Creating keywords may be the way to go. That's why I've labeled this as an investigation. 

The reason I created this ticket to begin with is #249 was essentially wanting to add a keyword that I thought should be composable. Why should there be a `Shift Click` keyword when there could be a `Key Down`, `Click` and `Key Up`. 

What I don't know is if there's any functional difference between a connected and disconnected action chain. For example, if I have key down on one chain but I don't do key up until another chain does the key down event get repeated multiple times (like it would if the key was actually held down)? That's one of the questions I'd like to answer in the investigation.

**Comment by pekkaklarck** [comment]
Yes, it's definitely worth investigating is there difference between running `key down`, `click` and `key up` separately and as an action chain. If there is, it would be great to be able to chain normal keywords somehow, but that is probably quite a bit harder than just registering and executing lower level Selenium commands.

**Comment by just-be-dev** [comment]
This probably isn't necessary anymore with the work we're doing on `Press Key` and `Press Keys`. In the other cases we can probably just implement specific keywords.
