### ISSUE TITLE
Set Window Position test failing on Ubuntu 15.04 / Latest FF 40.0a2

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#398]
When attempting to set the Y position on a FF window that opens "snapped" to the top menu bar and full length (not full screen) the window will not be moved.

**Comment by just-be-dev** [comment]
Upon further investigation I found that both `Set Window Size` and `Set Window Position` aren't given enough time to properly execute. When adding a delay, `Set Window Size` fails on  my Ubuntu setup because the window can't be sized above the maximum screen height if the window is snapped. I fixed this by simply reducing the overall resize height. 

The issue I reported above is fixed by resizing the window before trying to set the window position. 

@emanlove, @pekkaklarck, any ideas on addressing these timing issues? Should I just document that the action may not occur until some point after the keyword executes? I would add a timeout and just watch for the correct changes but `Set Window Size` lies and says it's the right size until the actual update occurs in which case it gives the correct values.

**Comment by pekkaklarck** [comment]
Is it possible to poll and wait until windows is resized/moved? If not, then documenting this behavior ought to be fine.

**Comment by just-be-dev** [comment]
It does seem possible for the move, but the resize immediately reports the correct size but gets updated again after the resize occurs. I don't know what's up with the inconsistent behavior, it's just something on the webdiver's side.

**Comment by HelioGuilherme66** [comment]
I also got tests failing with Firefox (34.5) and Chrome (44.0.2403.155)  in Fedora 19 (but not in Windows 7).
Firefox:
`Get and Set Window Size :: Get and Set Window Size                    | FAIL |
846 != 800`
`Get and Set Window Position :: Get and Set Window Position            | FAIL |
100 != 0`

Chrome:
`Get and Set Window Position :: Get and Set Window Position            | FAIL |
100 != 102`

**Comment by manycoding** [comment]
Here is another example of snapping in Fedora 22.
I noticed no matter what page height do you choose, after setting the position it can't be more than screen height - bar size - y position.
For example, if I resize with 860 and any height more than 1006, and set position to 1060 20 - the height after position is changed will be 1006 (=1080-54-20).

```
KEYWORD Selenium2Library . Set Window Size @{WINDOW_SIZE}
Documentation: Sets the `width` and `height` of the current window to the specified values.
Start / End / Elapsed:  20151118 13:59:38.947 / 20151118 13:59:38.977 / 00:00:00.030
13:59:38.947    TRACE   Arguments: [ '860' | '1006' ]   
13:59:38.948    DEBUG   POST http://127.0.0.1:56204/hub/session/f6e8321f-371e-4288-9a99-e8ce4334827a/window/current/size {"width": 860, "windowHandle": "current", "sessionId": "f6e8321f-371e-4288-9a99-e8ce4334827a", "height": 1006}     
13:59:38.977    DEBUG   Finished Request    
13:59:38.977    TRACE   Return: None    

00:00:00.010 KEYWORD ${width}, ${height} = Selenium2Library . Get Window Size
Documentation:  Returns current window size as `width` then `height`.
Start / End / Elapsed:  20151118 13:59:38.978 / 20151118 13:59:38.988 / 00:00:00.010
13:59:38.978    TRACE   Arguments: [  ]     
13:59:38.978    DEBUG   GET http://127.0.0.1:56204/hub/session/f6e8321f-371e-4288-9a99-e8ce4334827a/window/current/size {"windowHandle": "current", "sessionId": "f6e8321f-371e-4288-9a99-e8ce4334827a"}    
13:59:38.987    DEBUG   Finished Request    
13:59:38.988    TRACE   Return: (860, 1006)     
13:59:38.988    INFO    ${width} = 860  
13:59:38.988    INFO    ${height} = 1006    

00:00:00.008 KEYWORD Selenium2Library . Set Window Position @{POSITION}
Documentation:  Sets the position `x` and `y` of the current window to the specified values.
Start / End / Elapsed:  20151118 13:59:38.989 / 20151118 13:59:38.997 / 00:00:00.008
13:59:38.990    TRACE   Arguments: [ '1060' | '20' ]    
13:59:38.991    DEBUG   POST http://127.0.0.1:56204/hub/session/f6e8321f-371e-4288-9a99-e8ce4334827a/window/current/position {"y": 20, "x": 1060, "windowHandle": "current", "sessionId": "f6e8321f-371e-4288-9a99-e8ce4334827a"}   
13:59:38.996    DEBUG   Finished Request    
13:59:38.996    TRACE   Return: None    

00:00:00.007 KEYWORD ${x}, ${y} = Selenium2Library . Get Window Position
Documentation:  Returns current window position as `x` then `y`.
Start / End / Elapsed:  20151118 13:59:38.997 / 20151118 13:59:39.004 / 00:00:00.007
13:59:38.997    TRACE   Arguments: [  ]     
13:59:38.998    DEBUG   GET http://127.0.0.1:56204/hub/session/f6e8321f-371e-4288-9a99-e8ce4334827a/window/current/position {"windowHandle": "current", "sessionId": "f6e8321f-371e-4288-9a99-e8ce4334827a"}    
13:59:39.003    DEBUG   Finished Request    
13:59:39.003    TRACE   Return: (1060, 20)  
13:59:39.004    INFO    ${x} = 1060     
13:59:39.004    INFO    ${y} = 20   

00:00:00.009 KEYWORD ${width}, ${height} = Selenium2Library . Get Window Size
Documentation:  Returns current window size as `width` then `height`.
Start / End / Elapsed:  20151118 13:59:39.005 / 20151118 13:59:39.014 / 00:00:00.009
13:59:39.006    TRACE   Arguments: [  ]     
13:59:39.006    DEBUG   GET http://127.0.0.1:56204/hub/session/f6e8321f-371e-4288-9a99-e8ce4334827a/window/current/size {"windowHandle": "current", "sessionId": "f6e8321f-371e-4288-9a99-e8ce4334827a"}    
13:59:39.013    DEBUG   Finished Request    
13:59:39.013    TRACE   Return: (860, 1006)     
13:59:39.014    INFO    ${width} = 860  
13:59:39.014    INFO    ${height} = 1006
```

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
