### ISSUE TITLE
Press Enter Key doesn't work

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#4]
Hi there, 

I have downloaded the latest lib, and trying in my system. I have trouble click an area, so I am trying to focus on the area first and then press an ENTER key. I am using PRESS KEY | myid | \13. However, I got following error: valueError: ("Key value '%s' is invalid.", u'13')

Thanks! 

Adam

**Comment by adwu73** [comment]
The issue is solved, I should use  "Press Key | login_button | \13". One more slash, the python code gives the correct example. However, the F5 keyword gives the wrong example. Should this be fixed?

**Comment by hali4ka** [comment]
I had the same problem using Firefox 8 and I found that it should be used key 10 instead of 13.

**Comment by daluu** [comment]
Worthwhile to document for library/wiki if no code fix needed.

**Comment by hbmartin** [comment]
Perhaps there can be an ${enter} variable that inserts the appropriate character value?

**Comment by aminK1** [comment]
you would need to escape first backslash in RF.
This should solve your issue..

"Press Key    login_button    \13"

**Comment by bulletforyou** [comment]
The answer above that all of you said are wrong,
the correct answer is 
Press Key| login_button |\13

There are two Backslashes instead of  one's  before 13
