### ISSUE TITLE
Document that WebElements can be used as locators

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#404]
As [suggested by](https://github.com/rtomac/robotframework-selenium2library/issues/315#issuecomment-58188151) @ombre42,

> Still analyzing, but wanted to suggest changing Get Element Attribute to support using a webelement as a locator. It would be easy to do in a backwards compatible way by adding a name argument that supersedes parsing attribute_locator for an attribute name.

**Comment by just-be-dev** [comment]
Should be implemented as of 1.7 release.

**Comment by peterstory** [comment]
Has the documentation been updated to reflect this? The doc for 1.7.4
http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Get%20Element%20Attribute

still shows the following for Get Element Attribute

```
Get Element Attribute   attribute_locator   
Return value of element attribute.
attribute_locator consists of element locator followed by an @ sign and attribute name, for example "element_id@class".
```

which seems to imply that WebElements cannot be passed.

**Comment by aaltat** [comment]
By a quick read of the code, the WebElements can be used (Did not test it, just reading) also with this keyword. Although it's briefly mentioned in the documentation that WebElements can be used, the documentation could be better. Could you write an issue about it and perhaps even send pull request.

**Comment by peterstory** [comment]
I'm wondering how the syntax works. Suppose you get a WebElement, and then you want to determine its class: 

```
${button} =  Get Webelement  id=fancy-button
Get Element Attribute        ${button}
```

Where does the `@class` go?

**Comment by just-be-dev** [comment]
If you want to get the class you can just do this

``` robotframework
${button}=  Get WebElement  fancy-button
LOG  ${button.get_attribute('class')}
```

You should be able to access any of the [WebElement API](http://selenium-python.readthedocs.org/en/latest/api.html#module-selenium.webdriver.remote.webelement) that way.

**Comment by peterstory** [comment]
The only problem is trying to do that from RobotFramework using Restructured Text. I'm currently using the `.get_attribute()` method in a custom Python library I wrote (with code for the keywords `Element Should Have Class` and `Element Should Not Have Class`). But using Python is less than ideal, since I'm trying to design a suite of tests for users unfamiliar with Python.

edit: Ah, I see what you're doing. So would this work? 

```
${button}=  Get WebElement  fancy-button
${the_classes}=  ${button.getattribute('class')}
```

I take it that @emanlove's original suggestion (having an optional 2nd argument, for the attribute being selected) wasn't implemented?

**Comment by just-be-dev** [comment]
Right. We could add it, but it after discussing it we decided to hold off. If you think it's needed create a new issue.

**Comment by just-be-dev** [comment]
Actually, I take that back. We probably should just reopen this issue. This would be a good candidate for refactor in 1.8.

**Comment by aksenov007** [comment]
Any progress? Still only the way to do this as described [here](https://github.com/robotframework/Selenium2Library/issues/404#issuecomment-138910370)?

**Comment by aaltat** [comment]
No progress. No-one has seen the change important enough to submit PR.

**Comment by aksenov007** [comment]
I've created the pull request #730 to close this issue. Can anyone link it to this issue, please?

**Comment by aaltat** [comment]
This is done in https://github.com/robotframework/Selenium2Library/commit/dbbc8a9d698713dda60ffd61821cbe894165fe4c

**Comment by pekkaklarck** [comment]
Related docs have been heavily enhanced by #924.
