### ISSUE TITLE
Allow custom locators to define a default criteria

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#406]
In [elementfinder](https://github.com/rtomac/robotframework-selenium2library/blob/ea384de3885b905a306c12de50d788c5a2a14ae1/src/Selenium2Library/locators/elementfinder.py#L125) we have functionality to have certain criteria to automatically use a default locator if met. Our current implementation allows the specification of `//` to automatically use an xpath locator. It would be good if custom locators could define this functionality. 

The limitation of this is that it must not match any of the locator names. I.E. if a locator `list` is defined, `li` couldn't be used as a default locator criteria.

**Comment by divfor** [comment]
today I found related states in pages:
http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#location-strategies
http://www.seleniumhq.org/docs/06_test_design_considerations.jsp#ui-mapping

**Comment by just-be-dev** [comment]
Could you clarify what these resources are supposed to help address? I looked through the links, but I feel like I'm missing something.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
