### ISSUE TITLE
Document network capture options and examples on the wiki

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#411]
~~Selenium has the ability to capture network traffic for whatever site it runs against. If the library can currently accomplish this (I'm assuming it can),~~ Investigate writing a test to detect any 500 errors on a given site. After determining how the test should be written, document the test case on the wiki.

**Comment by ombre42** [comment]
The ability to capture network traffic using Selenium alone was lost when moving from RC to WebDriver A.K.A. Selenium 2. Was this feature added back and I just am not looking in the right places?
See #25

**Comment by just-be-dev** [comment]
It seems you may be right about. I'd at least like to figure out possible solutions and document it on the wiki. I need this for work, so it's pretty important to me.

**Comment by just-be-dev** [comment]
I've renamed the issue and changed its scope to reflect your feedback @ombre42. I also found #319, which is related.
