### ISSUE TITLE
How to know which keyword triggers run on failure?

### ISSUE THREAD

**Issue by datakurre** [robotframework/SeleniumLibrary#413]
"Register keyword to run on failure" almost helps debugging difficult test errors by allowing to add an "automatic break point" where the errors happens. For example, by using "Debug" keyword from robotframework-debuglibrary or just custom keyword triggering PDB.

Except that when that break point happens, one has no idea, what has failed. (That can only be seen from the test log.)

Any idea, how one could determine the current test position, failed keyword and the failing reason from the keyword run by "run on failure" keyword?

**Comment by datakurre** [comment]
Run on failure -behavior is implemented here https://github.com/rtomac/robotframework-selenium2library/blob/master/src/Selenium2Library/keywords/keywordgroup.py

**Comment by just-be-dev** [comment]
Have you investigated listeners? That would probably best help you in this situation.

**Comment by datakurre** [comment]
@zephraph I was hoping something simpler, but listeners would definitely work. Yet, they would require saving state into threadlocal variable into some module to access that state information from a keyword.

Another known alternative would be to use inspect and step back some frames, because "run on failure" code knew which keyword was being called.

**Comment by pekkaklarck** [comment]
@datakurre Library listeners ought to avoid storing global state:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-libraries-as-listeners

That's a new feature in RF 2.8.5. In RF 2.9 we are going to support multiple listeners per library:
https://github.com/robotframework/robotframework/issues/1970

**Comment by just-be-dev** [comment]
@pekkaklarck, do you have any other ideas for this? I'm not too sure what to suggest, because I haven't had to do this before.

**Comment by pekkaklarck** [comment]
I haven't done this earlier either. Just wanted to comment that if listeners work in this context, it's probably a good idea to use the newish library listener functionality. Otherwise communication between the library and the listener is much more complex.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
