### ISSUE TITLE
Push 1.7 Update

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#416]
We've got some major new functionality and several new keywords that are waiting to be pushed out. 

@ombre42, @emanlove, @pekkaklarck is there anything any of you think should be added for the next release? Do we need to do anything (more stringent testing, etc) before the release?

I'm still new to this project so I didn't want to do something like a version push without getting your consensus.

**Comment by pekkaklarck** [comment]
I have never been that actively involved with this particular project so cannot help much with releasing. Great work with 1.7 so far @zephraph!!

**Comment by just-be-dev** [comment]
I still like to include you because I feel you have a good working knowledge of the whole infrastructure and may see things that we miss. Thanks! I'm doing my best. Always room for improvement though, heh.

**Comment by just-be-dev** [comment]
I've given this a few days and I haven't heard anything back, so I'm going to move forward with plans to release 1.7. 

If there are any objections, please say so ASAP.

**Comment by just-be-dev** [comment]
Update progress
- [x] Publish package to pipy
- [x] Publish release to github
- [x] Update documentation

**Comment by just-be-dev** [comment]
Welcome to 1.7?!
