### ISSUE TITLE
Confused row/column definition in table keywords

### ISSUE THREAD

**Issue by divfor** [robotframework/SeleniumLibrary#418]
Table Cell Should Contain: row/column start from 1 counting thead, tbody and tfoot
Table Row Should Contain: row starts from 1 but only counting tbody

actually, tfoot may be either before tbody or after tbody in the html document order, but in web UI  table footer is always present after table body. so it make sense that these keywords should only take count of tbody into table row number.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
