### ISSUE TITLE
wrong xpath suffixes for last-col

### ISSUE THREAD

**Issue by divfor** [robotframework/SeleniumLibrary#419]
in tableelementfinder.py, there is _locator_suffixes defined. 
for ('xpath', 'last-col'): [' //tbody/tr/td[position()=last()-(%s-1)]', ' //tbody/tr/td[position()=last()-(%s-1)]']
it has two identical tr/td suffixes. should they be tr/td and tr/th?
('xpath', 'last-col'): [' //tbody/tr/td[position()=last()-(%s-1)]', ' //tbody/tr/th[position()=last()-(%s-1)]']

see css part, it is:
('css', 'last-col'): [' tr td:nth-last-child(%s)', ' tr th:nth-last-child(%s)'],

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by pekkaklarck** [comment]
@divfor was right, there shouldn't be `//tbody/tr/td[position()=last()-(%s-1)]` twice. I guess the original idea has been to use `th` instead `td` in one of them. That wouldn't have worked correctly with rows containing both `th` and `td` elements.

This problem caused bug that `Table Column Should Not Contain` doesn't work with `th` cells when using negative indexes. That's now reported as part of #990.
