### ISSUE TITLE
How to handle proxy authentication in Robot ride.

### ISSUE THREAD

**Issue by preshri** [robotframework/SeleniumLibrary#42]
We execute scripts through a corporate network. How do we handle proxy authentication.
Currently when we try to open a browser in FF, ride throws an error 

WebDriverException: Message: '<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD>\n<BODY>\n<FONT face="Helvetica">\n<big><strong></strong></big><BR>\n</FONT>\n<blockquote>\n<TABLE border=0 cellPadding=1 width="80%">\n<TR><TD>\n<FONT face="Helvetica">\n<big>Access Denied (authentication_failed)</big>\n<BR>\n<BR>\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica">\nYour credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica">\nThis is typically caused by an incorrect username and/or password, but could also be caused by network problems.\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica" SIZE=2>\n<BR>\nFor assistance, contact your network support team.\n</FONT>\n</TD></TR>\n</TABLE>\n</blockquote>\n</FONT>\n</BODY></HTML>\n'

**Comment by ombre42** [comment]
You may have to disable proxying of local webdriver traffic, as it is proxied by default even though it may be local to the machine. Search existing issues or post to the user group. Closing as this is environment related and there are workarounds posted on this issue tracker and elsewhere.
