### ISSUE TITLE
Drag and Drop not working

### ISSUE THREAD

**Issue by jjwipf** [robotframework/SeleniumLibrary#423]
I'm need to simulate a drag and drop and am not seeing the expected result in s2l
## If I run the following code

**\* Settings ***
Library    Selenium2Library    run_on_failure=Nothing
Library    HttpLibrary.HTTP

**\* Test Cases ***
Google Image Drag Check
    Open Browser    https://www.google.com    gc
    sleep  .2
    #Drag And Drop    id=hplogo    id=sb_ifc0
    Mouse Down On Image    hplogo
##     Mouse Up    sb_ifc0

I am expecting that the code will open a browser to google.com using chrome (43) and drag the google image into the search box. I chose that because the google homepage is universal and I wanted a visual representation with the search field updating visually. Any help/knowledge appreciated.

(I did notice an issue from 2012 about drag and drop and iframes, I don't believe the google homepage is using iframes and my non-example webpage is definitely not using iframes)

**Comment by just-be-dev** [comment]
What version of RF, SL2, Chrome?

**Comment by just-be-dev** [comment]
I'll take a look at this sometime tomorrow.

**Comment by jjwipf** [comment]
Apologies for the late response, I'm using:
RF 2.8.7
S2L 1.6.0
Chrome 43.0.2357.81
Thanks for looking into this!

Edit: Thinking about it this morning I wasn't sure if the google example was the best since the logo isn't explicitly draggable (as my eventual item to test will be). I wrote this up to test for that:

W3S Image Drag Check
    [Tags]    w3s
    Open Browser    http://www.w3schools.com/html/html5_draganddrop.asp    gc
    sleep  .2
    #Drag And Drop    id=drag1    id=div2
    Mouse Down On Image    id=drag1    #img_w3slogo.gif
    Mouse Up    id=div2

The end result for me is still that the image isn't in the drop region.

**Comment by jjwipf** [comment]
I just wanted to give you an update.

I found a div only draggable object and ended up with this:

Div Based DnD Example

```
[Tags]   elated

Open Browser    http://www.elated.com/res/File/articles/development/javascript/jquery/drag-and-drop-with-jquery-your-essential-guide/droppable.html    gc

sleep  .2

Drag And Drop    id=makeMeDraggable    id=makeMeDroppable

#Mouse Down    id=makeMeDraggable

#Mouse Up    id=makeMeDroppable
```

Which behaves as expected in chrome with the red box moving into the outlined box. (both drag and drop as well as mouse down and mouse up)

So drag and drop appears to be behaving as expected. (assuming that draggable is explicitly required)

This does however raise the question of what are the constraints on mouse up and mouse down. Are they also required to be draggable? If so they are not nearly as robust as the documentation lead me to believe. The documentation only mentions a locator which must be id or name which fits all of these tests. I did dig around in the mouse down and mouse up portions of the S2L code which lead me to robotframework-selenium2library/src/selenium2library/keywords/_element.py specifically to line 412. This lead me to the selenium webdriver action chains documentation which ended up losing me since it seems like that would do exactly what I expect.

Additionally I re-attempted to use FF with my google example which failed initially. One issue was that the mouse was required to be in the fire fox window. A second issue was that the mouse had to be in the search frame for it to properly drop the item (I actually switched from the image to the gmail icon since that is a div). However I could not simulate this behavior in ie or gc regardless of mouse position. Unfortunately I need to simulate a mouse down+up/drag and drop across gc/ie/safari/ff (of which GC is our currently supported browser). Also I'm not sure how drag and drop is working in the google example with ff if the mouse is hovered over the search; if drag and drop does indeed require draggable.

Overall I think I'm going to play around with creating a miniature library around drag and drop and mouse down/up. I'll keep checking here for updates and I'll update on anything I find.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by jjwipf** [comment]
I haven't had a chance to investigate further since then. I did rerun these example tests and it does appear to still behave in the same way. The team ended up putting our drag and drop portion on hold so I've had little expose after the initial try. I can play around some more but I think it will take a more experienced eye than mine to trace through the code.

**Comment by philsalman** [comment]
Im experiencing the same problem. Currently i'm trying to drag and drop multiple elements from the source location to target location but it does not even drag the specified source elements to the destination nor does it report any errors about not being able to drag the specified element. It just runs my test file saying all keywords passed, but nothing has been dragged and drop. Unfortunately i can't provide my issue as an example because the code Im trying to run my tests on, is not open source. But tonight Im going to create a similar example that will hopefully expose this.

**Comment by yeminib** [comment]
@philsalman i am currently facing the same problem, No test errors no drag and drop events occured !

**Comment by VaishinaviRajaraman** [comment]
Has anyone found a solution to this? I am facing the same issue too. My tests pass, but the element hasn't dragged and/or dropped

**Comment by howtoautomateinth** [comment]
I'm facing the same issue too. here my code

```
${a_url}	http://html5demos.com/drag
${elem_source}	xpath=(//ul//li//a)
${elem_target}	css=div#bin
${browser}	chrome

A Based DnD Example
	Open Browser	${a_url}	${browser}
	Maximize Browser Window
	${elems}=	Get Webelements	${elem_source}
	${size}=	Get Length	${elems}
	:FOR	${index}	IN RANGE	${size}
	\	Drag And Drop	${elem_source}[${index}+1]	${elem_target}
```

**Test pass but nothing move.** 

Don't sure it because "draggable" attribute or not.

Test on:

- Google Chrome 56
- Window 7
- robotframework 3.0.1
- robotframework-selenium2library 1.8.0

## **Update**
I think this is a root cause why it can't drag and drop
http://stackoverflow.com/questions/29381233/how-to-simulate-html5-drag-and-drop-in-selenium-webdriver
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3604

HTML5 "drag&drop" is not currently supported by Selenium

there have some workaround in the thread

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by el-nuru** [comment]
Experiencing the same issue with
```
Drag And Drop    ${rich_text}    ${screen_canvas}
Mouse Down    ${screen_canvas}
Mouse Up    ${screen_canvas}
```
elements are draggable, RF doesn't report any error, adding `Mouse Down` and `Mouse Up` had no effect, I'm on the latest RF
