### ISSUE TITLE
Keyword capture_page_screenshot fails when using Remote WebDriver

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#43]
When using a Remote WebDriver, call keyword Capture Page Screenshot.  Result:
FAIL    AttributeError: 'WebDriver' object has no attribute 'save_screenshot'

The remote driver in the Selenium Python bindings defines a method called get_screenshot_as_file instead of save_screenshot, but they perform the same action and have the same signature.

A simple workaround for this:
on Line 27 of keywords/_screenshot.py,
replace:
        self._current_browser().save_screenshot(path)
with:
        if hasattr(self._current_browser(), 'get_screenshot_as_file'):
            self._current_browser().get_screenshot_as_file(path)
        else:
            self._current_browser().save_screenshot(path)

**Comment by ombre42** [comment]
fixed in korda's fork- https://github.com/korda/robotframework-selenium2library/commit/0c52e076c335f6804899fee9ea7d1b2a7904773f
thank you and sorry I didn't use GFM markup

**Comment by adwu73** [comment]
I have reproduced the issue, and tested the fix. It works. can someone help to merge this into the fork? It seems this fix is not in 1.0.1 yet?

**Comment by hbmartin** [comment]
I am also curious about the status of this fix, especially since it seems like rtomac hasn't been active in over a month.

**Comment by peritus** [comment]
I can confirm that @ombre42's patch fixes the issue (and i get screenshots in reports)

**Comment by peritus** [comment]
Created a pull request that includes @korda's patch for easy merging:

https://github.com/rtomac/robotframework-selenium2library/pull/80

**Comment by emanlove** [comment]
Merged with #80. This fix will be in the Selenium2Library 1.1 release.
