### ISSUE TITLE
Note version added to recently added keywords.

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#435]
It might be worth wild to add a note on the keyword documentation noting under what versions recently added keywords were added. For example,

```
'Wait Until Element Is Not Visible' was added in version 1.7.
```

**Comment by just-be-dev** [comment]
Agreed.

**Comment by aaltat** [comment]
I agree, added to 2.0 release so that we remember to update the documentation.

**Comment by aaltat** [comment]
Will not added to old keywords, but must be added to new keywords. Also update the contributing instructions.

**Comment by aaltat** [comment]
Note is added for the new keywords in release 3.0.0. There CONTRIBUTING instructions needs to be updated, but there are few others things which needs to changed in the CONTRIBUTING instructions, so there is a separate issue for that. Closing this one.
