### ISSUE TITLE
Click element and safari

### ISSUE THREAD

**Issue by jjwipf** [robotframework/SeleniumLibrary#437]
I'm noticing that if I use the following code

`*** Settings ***`
`Library    Selenium2Library    run_on_failure=Nothing`
`Library    HttpLibrary.HTTP`
`Library  String`

`*** Test Cases ***`
`Safari Button Tied To Alert Check`
`[Tags]    safari`
`Open Browser    http://www.javascriptkit.com/javatutors/alert2.shtml    safari`
`sleep  2`
`Assign Id To Element  //*[@id="contentcolumn"]/form/p/input  tryit`
`Click Element  tryit`
`Alert Should Be Present  My name is George. Welcome!`

I end up with the error:
`UnexpectedAlertPresentException: Alert Text: None`
`<super: <class 'WebDriverException'>, <UnexpectedAlertPresentException object>>`

If I swap out safari for gc/ff/ie I'm not getting this error; the alert should be present properly picks it up instead. From what I can tell it's like the click element action is registering the alert and wants to handle it with safari. I didn't see a keyword to preemptively say that an alert is coming but it isn't currently onscreen.

(Being done on Windows Server 2012 R2, safari 5.1.7)

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by jjwipf** [comment]
The team moved away from Safari as a requirement and I haven't had a chance to look further into the issue. I'm unsure of how to close it, but that seems fine with me.

Edit: Just kidding I tried the close and comment and that appears to be the way.
