### ISSUE TITLE
Alert Should Be Present and PhantomJS

### ISSUE THREAD

**Issue by jjwipf** [robotframework/SeleniumLibrary#441]
I'm having issues with the keyword `Alert Should Be Present` and PhantomJS. I am running the same test against chrome/firefox/internet explorer/safari with no complaints but PhantomJS returns:

`Fail There were no alerts`

It's like phantom isn't sensing javascript popups

Looking into it more, here (Ivan De Marino's message specifically):
https://groups.google.com/forum/#!topic/phantomjs/w_rKkFJ0g8w

Seems to suggest that the alert will never be present but rather registered into a file. My question would be is this interaction expected in S2l? If so we'll do a different behavior around phantomjs. Just wanted to check to see if the keyword (Alert Should Be Present) should "play well" with phantomjs. Thanks for your time!

**Comment by just-be-dev** [comment]
I think phantomjs is a special case. It really doesn't handle alerts all that well. 

I'm not entirely sure if there's actually a javascript representation of the alert built out or if it only triggers the `onAlert` event. In any case, I would use [onAlert](http://phantomjs.org/api/webpage/handler/on-alert.html) like Ivan stated. 

Perhaps you could create a hidden div with the class alert or something from that event and check for it from S2L that way?

**Comment by jjwipf** [comment]
After communicating with the team more I have learned that the approach will eventually take out these types of popups. (They were put in place for expediency more than anything) For the moment I have thrown the keyword in another keyword that calls it through run keyword and continue on failure. The test fails yes, but it should be failing as that is not expected behavior so it's properly failing.

I do think the `There were no alerts` text is a tad confusing at first (purely in the phantom case), but after further inspection I would assume most people would get to the general conclusion that it is a phantom issue.

**Comment by just-be-dev** [comment]
I'll try to see if I can make the handling a little more graceful.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by peterstory** [comment]
I think this is still a problem: using Chrome, when my test triggers an alert, I dismiss it with `Confirm Action`. But if I try the same test using PhantomJS, `Confirm Action` gives this error: `There were no alerts`. Is there a workaround available?

**Comment by peterstory** [comment]
For future reference, a workaround is to override the confirmation dialog box to always return true. For example: 

`Execute Javascript  window.confirm = function(confirmationText) { return true; };`

**Comment by aaltat** [comment]
Because this seems to be a problem, I did open the issue.

**Comment by xanadiu** [comment]
This behavior also affects our work as a non-working handling of JavaScript alerts by phantomjs does not allow us to use phantomjs for automated tests. Which is sad as phantomjs seems to be more stable in contrast to constantly updating browsers and their corresponding web drivers.

**Comment by aaltat** [comment]
I have disabled the browser automatic updates from the CI infrastructure. Which helps a lot. There is a fix in the master  m p: https://github.com/robotframework/Selenium2Library/commit/dcc7ff9e7c2a27fb234678cec388a52de1f0e5ba

**Comment by aaltat** [comment]
I recall many fixes on chrome driver side and in the library it self to make the alert more stable. Also due inactivity, I am closing the issue.
