### ISSUE TITLE
remote file upload

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#445]
thank you so much for this great library. Very helpful!

I want to use the Webdriver mechanism to upload files remotely (since version 2.8). The junit fraction does it like this:

``` java
driver.setFileDetector(new LocalFileDetector())
```

Would that be possible in selenium2library, too. Did anybody look into that already?
The python bindings (file_detector.py) already implements this:

``` python
class LocalFileDetector(FileDetector):
    """
    Detects files on the local disk.
    """
```

Details here:
http://stackoverflow.com/questions/16205299/create-and-upload-a-file-on-selenium-grid

**Comment by just-be-dev** [comment]
I'll look into it, thanks for the suggestion.

**Comment by just-be-dev** [comment]
Have you tried just selecting the upload element and using `send_keys` (`Input Text`) with the path to the local file? It seems like the python api has some magic to facilitate that. 

https://github.com/SeleniumHQ/selenium/blob/f5b4f1c693f9598050e6f507eb1441a0b77c2943/py/selenium/webdriver/remote/webelement.py#L283-L285

**Comment by ghost** [comment]
I guess I trusted your documentation on that "Choose File ... The file specified with file_path must be available on the same host where the Selenium Server is running." I just tried and like you said it magically works. That is great news! Thanks for pointing that out. I suggest that you update the documentation.

**Comment by just-be-dev** [comment]
This project has a long history with a lot of people involved. Things like this fall through the cracks from time to time.  

Thanks for testing it out though! I'll make an issue to update the documentation.

**Comment by just-be-dev** [comment]
Also, did you just try it with `choose file`? I forgot that that keyword even exists, it should essentially do the same thing.

**Comment by ghost** [comment]
yes, I used `choose file` and it worked perfectly.
Again thank you for your support!

**Comment by just-be-dev** [comment]
Cool. Sorry again about the documentation! I'm working on it.
