### ISSUE TITLE
Handling "Leave Page" popup created by defining window.onbeforeunload function

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#448]
There is a popup on page when user trying to leave page
![c9ip2](https://cloud.githubusercontent.com/assets/1729590/8749741/2abc3a42-2cac-11e5-82ad-b2bc7c27f000.png)

Existing keyword in Selenium2Library **Choose Ok On Next Confirmation** doesn't handle this alert. 
The keyword **Confirm Action** just hide alert, but I need to accept it and leave the page.

There is a resolved issue in [webdriver issues](https://code.google.com/p/selenium/issues/detail?id=4496)

**Comment by just-be-dev** [comment]
It looks like it should work properly. Can you show me that part of your test?

**Comment by chevi** [comment]
This is my test:

```
go to   ${HOST}/layouts/12/edit 
Reload Page     
Choose Ok On Next Confirmation      
Input Text  custom_object_layout_name   test text
```

And log file from chrome

![screenshot at 19-12-24](https://cloud.githubusercontent.com/assets/1729590/8751765/eb861a6c-2cb7-11e5-8ff4-b9f57a94564e.jpg)

**Comment by just-be-dev** [comment]
Try this

``` robotframework
go to   ${HOST}/layouts/12/edit 
Reload Page     
Choose Ok On Next Confirmation     
Confirm Action 
Input Text  custom_object_layout_name   test text
```

**Comment by chevi** [comment]
Fantastic! Thanks, zephraph
