### ISSUE TITLE
Update documentation on Choose File to show that it supports remote uploading

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#449]
The documentation for `Choose File` states that the filepath must be available on the same host where the Selenium Server is running. #445 revealed that this statement is false. 

Selenium is setup to send files remotely to a server, but the files must be located on the system from which the test is running.

**Comment by aaltat** [comment]
Selenium does this magically behind the scenes: https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py#L733 and https://github.com/SeleniumHQ/selenium/blob/e74164e117e23e9588170613d7201e4d74245578/py/selenium/webdriver/remote/webelement.py#L505
