### ISSUE TITLE
Firefox opens but does not load any page

### ISSUE THREAD

**Issue by hasmukh** [robotframework/SeleniumLibrary#451]
Hello Everyone,
I am running Robot Framework RIDE in testing machine.
Automatic testing was going smoothly with Firefox 31
Recently my firefox gets updated automatically and all my test cases are getting failed.
By reverting to Firefox 31 it works.
I don't know what really happened after updating firefox. 
It looks like there is a problem in patching with selenium library and firefox.

Could  someone please tell how to resolve this problem ?
Where to get information about Selenium & Firefox Patch management?

Any help will be greatly appreciated.

Thank you
Hasmukh Maniya

**Comment by emanlove** [comment]
There is usually a lag in between the time Firefox is released and when selenium supports that version. Most people I know tend to turn off auto-updates so this breakage doesn't occur. To see what version is supported I view the [CHANGES log](https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES#L17).  Note sometimes there is a [further lag for native actions](https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES#L27) (see [[old] documentation](https://code.google.com/p/selenium/wiki/AdvancedUserInteractions#Native_events_versus_synthetic_events) about native events). So be aware of what each selenium version provides and doesn't provide.

**Comment by hasmukh** [comment]
Thank you @emanlove 
Actually I wanted to know whether is there any specification mentioned patches with the versions of Selenium and Firefox browser ?

**Comment by just-be-dev** [comment]
@hasmukh, what version of firefox are you running now?

**Comment by hasmukh** [comment]
@zephraph @emanlove 
I am using FireFox 31 on one machine and Firefox 31 ESR on second machine.
http://stackoverflow.com/questions/31645783/ride-selenium-patch-management-with-firefox
Where can I see the versions of Selenium2Library and supportable Firefox version ?

Regards as soon as possible.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
