### ISSUE TITLE
Review add cookie keyword

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#454]
Some points were brought up in #286 that all arguments may not be used for `add cookie`. We should investigate that keyword and ensure it's properly implemented. 

If anything is lacking in the documentation that should also be updated.

**Comment by aaltat** [comment]
This was fixed in: https://github.com/robotframework/SeleniumLibrary/commit/87b3bae99ce8737aa238d808cb284288476e150d
