### ISSUE TITLE
Capture Page Screenshot is displaying HTML with RF 2.9rc1

### ISSUE THREAD

**Issue by markwinspear** [robotframework/SeleniumLibrary#458]
Hi
Running Selenium2Library v1.7.1 and Selenium 2.46.0 with Robot Framework 2.9rc1 and Capture Page Screenshot is outputting the HTML source in my report file, rather than the screenshot

Unfortunately I can't downgrade to verify if this is related to RF 2.9rc1 or not at the moment, but wanted to get this one on the radar quickly

**Comment by just-be-dev** [comment]
That's a new one... Try upgrading to 1.7.2.

**Comment by markwinspear** [comment]
Thanks. I've just tried that and get the same result...
![screenshot](https://cloud.githubusercontent.com/assets/6747519/8853083/91345f3e-3148-11e5-8258-dfdfa2d7c51a.png)

**Comment by just-be-dev** [comment]
What browser/version are you using?

**Comment by markwinspear** [comment]
To view the robot framework report, I've tried chrome 43, ie11 and Firefox on Win 8.1 with the same results

**Comment by just-be-dev** [comment]
Could you rerun the test and pass in the arguments `--test your_test_name --loglevel DEBUG` and post the log file somewhere I can look at it?

You can also email it to me if you'd like. I just don't have enough information on what's going on.

**Comment by markwinspear** [comment]
Hi - I've just sent the log file by email. Let me know if I can do anything else

**Comment by just-be-dev** [comment]
Thanks, I'll take a look.

**Comment by just-be-dev** [comment]
I just ran across this issue at work. I'm not sure what's going on, but this is now at the top of my list.

**Comment by just-be-dev** [comment]
Upon second glance, it actually does capture the screenshot. If you expand the capture page screenshot step, the screenshot is inside there. 

Why it dumps out all the page though is beyond me. It'll require a bit more investigation, but this seems pretty nasty to me.

**Comment by markwinspear** [comment]
Indeed. I mean, if you want the page source, the Selenium2Library has a keyword for that - "Get Source". Thanks for the update

**Comment by ombre42** [comment]
In your screenshot, you have not expanded the keyword Capture Screenshot. The HTML you are seeing is output from keyword `Page Should Contain`. I ran a similar test and see similar output with RF 2.8.3 & S2L 1.2.
You can see in the code (keywords/_element.py) that the source is logged before raising an exception.

``````
        if not self._page_contains(text):
            self.log_source(loglevel)
            raise AssertionError("Page should have contained text '%s' "
                                 "but did not" % text)```
``````

**Comment by ombre42** [comment]
@markwinspear If you do not want to capture the HTML in the log, use the loglevel argument:

```
Page Should Contain Element    ${error_message}    loglevel=NONE
```

The behavior of logging the HTML is as designed and is documented in the keyword documentation.
If you still want to change the logging of the source on failure during the keywords like Page Should Contain, it would probably be best to create a new issue and close this one to avoid confusion.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
