### ISSUE TITLE
RemoteDriver won't work with selenium 2.21.2

### ISSUE THREAD

**Issue by korda** [robotframework/SeleniumLibrary#46]
I fixed this in my fork by changing

webdriver.Remote(desired_capabilities=desired_cap , command_executor=str(remote_url), browser_profile=profile)

to

webdriver.Remote(str(remote_url), capabilities_type)

in _browsermanagment.py

however it won't work with profiles or capabilities other that browser type, I don't know how to do it since I couldn't find selenium2 python bindings documentation that is up to date. Only useful thing I found was here http://seleniumhq.org/docs/04_webdriver_advanced.html#remotewebdriver, it provides basic working example.

**Comment by emanlove** [comment]
This appears to be an issue with a particular selenium version and not selenium2library. If you feel I am mistaken please reopen this issue.
