### ISSUE TITLE
Temporary directory for WebDriver not removed after run

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#462]
After several (many) rounds of testing with Selenium2Library 1.7.0 my machine complains about /tmp getting full.
There are a lot of /tmp/tmpXXX-directories which are obviously created by the WebDriver. They never get removed.
I googled a bit and found out that if one would call driver.quit() instead of driver.close(), this temporary directory would be removed.
What does the Selenium2Library call?

**Comment by just-be-dev** [comment]
I'm not sure, but that's a very valid concern. I want to say yes, that is included, but let me double check.

**Comment by just-be-dev** [comment]
It seems that we do indeed do this. Check [browserchache](https://github.com/rtomac/robotframework-selenium2library/blob/master/src/Selenium2Library/utils/browsercache.py#L23). 

You just need to ensure that after you've finished your test you call `Close All Browsers`. I'm not sure that that's called automatically.

**Comment by aaltat** [comment]
Is this still a problem?

**Comment by aaltat** [comment]
Yes, it is. I am seeing the same problem also in my CI.

**Comment by aaltat** [comment]
But I can reproduce the problem with Selenium code also and therefore this is a Selenium bug. Please raise an issue to the Selenium issue tracker.
