### ISSUE TITLE
Need "Table Should Not Contain" keyword

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#463]
There are a bunch of "Should Contain" keywords for tables (Table Should Contain, Table Should Not Contain, ....) For all of them also a "Should Not Contain" version should exist.

(Of course you can use a workaround, e.g.
Run Keyword And Expect Error    Table identified by 'xpath=.//table[@id='credentialList:dataTable']' should have contained text 'HTTP Access'.  selLib.Table Should Contain xpath=.//table[@id='credentialList:dataTable']  HTTP Access loglevel=NONE

But this is obviously very ugly)

**Comment by just-be-dev** [comment]
Easy enough, I'll add it to the todo list.

**Comment by Gaurang033** [comment]
Hi @zephraph 
I am willing to work on it, if you haven't started it yet.

**Comment by tarand** [comment]
Hi Shah,

thanks!

No, I did not start work on it until now (except that I have a private robot keyword for that…) But I guess the solution will be done on python side?

Ciao
                Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com

**Comment by Gaurang033** [comment]
Hi @tarand 

I am aware of the solution and I can implement that easily. however I don't want to start working on it without assigning a ticket to myself. 

just wanted to confirm with @zephraph  as well, if he hasn't started working on it and if he can assign the ticket to me, I can start working on it right away.

**Comment by aaltat** [comment]
I haven't heard that anyone would be working on the request. Nor I haven't seen pull request.

The Feature Request label doesn't mean that someone would be working on the matter. It means, more or less, that idea behind the request is OK and if the code in the pull request is good, it can be merged to the master. This way it will go to the next release.

I think that now one from the core team has worked on the matter. So if you want to send it, please feel free to do so.

**Comment by eL-Prova** [comment]
@aaltat @Gaurang033 
https://github.com/robotframework/Selenium2Library/pull/767

**Comment by jimpriest** [comment]
Will this ever be integrated?

**Comment by aaltat** [comment]
No-one has seen the feature important enough to implement it. If you need it, please send a PR.

**Comment by eL-Prova** [comment]
I have implemented long time ago (see my pull). Because of renaming not found but link is:
https://github.com/robotframework/SeleniumLibrary/pull/767

Pull again submitted

**Comment by aaltat** [comment]
Closing due inactivity. If there is an interest to me this happen please open new issue and preferably create also a PR

**Comment by RH-sdavey** [comment]
So, 
the issue was opened in 2015...
a PR was submitted in 2017...
which was ignored until 2018...
resubmitted in 2018...
and then closed (wrongly) because of "inactivity" in 2019...

And now Im looking for the same thing in 2022.

**Comment by emanlove** [comment]
Looking at [the pull request](https://github.com/robotframework/SeleniumLibrary/pull/724) there were many requested changes that were not completed. I believe that was why it was closed out.
