### ISSUE TITLE
Table Should Contain keyword doesn't throw proper error if the selected table (via xpath) cannot be found

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#464]
I'm using "table should contain" with the following syntax:
Table Should Contain    xpath=.//table[@id='credentialList:dataTable']  HTTP Access

If (by mistake) I pass a non-existent id, I get the same error as if the id is correct but the text is not contained:
Table identified by 'xpath=.//table[@id='credentialList:dataTabe']' should have contained text 'HTTP Access'.

What is needed is an error message indicating that the table is not there. 

For example, if I use the "Get WebElements" keyword, I get 
ValueError: Element locator '//table[@id='credentialList:dataTabe']' did not match any elements.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by tarand** [comment]
The only reason why I did not further comply is why my test cases now have a valid xpath-specification so that I do not run into this error.

But if the lib didn’t change here, the issue is still there and should be corrected…

Ciao,
                Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com
