### ISSUE TITLE
Consider adding more automated test coverage to the Travis builds

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#467]
To prevent issues like [this](https://github.com/rtomac/robotframework-selenium2library/commit/e43e782a5a0173a4dce2d60ce5f46e6ce3b78f78) from occurring, we really need greater test coverage. 

This includes determining what versions of RF that we will support and running the tests for each of those versions. 

We also need better browser coverage. I mentioned using SauceLabs in #383, and I still think we should investigate that option. It seems there a run limit before you hit a paywall though, so maybe investigating other options would be good too.

**Comment by pekkaklarck** [comment]
Sauce is promotinc RF and S2L via blog posts and video tutorials. I'm fairly sure they'd give us free credits if asked.

**Comment by just-be-dev** [comment]
Hmmm... I may have been wrong about that. 

I have an account, but it turns out it wasn't for their open source program? I feel like they've transitioned to a new payment scheme recently. Regardless, I'll keep that in #383.
