### ISSUE TITLE
Documentation error for desription of "Using webelement"

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#469]
The keyword documentation has:
Starting with version 1.7 of the Selenium2Library, one can pass an argument that contains a WebElement instead of a string locator. To get a WebElement, use the new Get WebElements keyword. For example:
${elem} =   Get WebElements     id=my_element
Click Element   ${elem}     

This can obviously not work, as Get WebElements returns a list. I think it should be
${elements} =   Get WebElements     id=my_element
Click Element   ${elements}.first()
Or similar

**Comment by just-be-dev** [comment]
Ugh, yeah, you're right. We'd planned on adding a `Get WebElement` keyword that just returned a single item. That slipped through the cracks though.

I'll look at rewording the documentation and possibly introducing that keyword.

**Comment by just-be-dev** [comment]
Should I add `Get WebElement`or just suggest people use `Get WebElements` combined with `@{list}[0]`?

**Comment by just-be-dev** [comment]
@pekkaklarck, is there any precedence for this? Having two keywords, one that returns a list of items and the other that returns just the first.

**Comment by pekkaklarck** [comment]
I think it would be convenient to have `Get WebElement` separately.

For example, XML library has both `Get Elements` and `Get Element` keywords. The former returns a list of elements and the list can be empty. The latter fails if there is not exactly one element. Would that make sense in S2L context?

**Comment by tarand** [comment]
I would say, yes.

Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023
thomas.arand@nokia.commailto:thomas.arand@nsn.com

Nokia Solutions and Networks Deutschland GmbH

**Comment by just-be-dev** [comment]
I thought it was needed originally, and I still think it'd be nice to have.

**Comment by just-be-dev** [comment]
Fixed in 1.7.3
