### ISSUE TITLE
Please change heading formatting in "Locating or specifying elements" section

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#470]
Within this section there are sub-sections. (e.g. "Using 'locator'", "Using 'webelement'", ...)
These cannot be distinguished by normal paragraph text, and it is thus confusing to read this section. This can be seen best at:

This can be fixed by changing the locator to:

Click Link    default=page?a=b

Using 'webelement'

Starting with version 1.7 of the Selenium2Library, one can pass an argument that contains a WebElement instead of a string locator. To get a WebElement, use the new Get WebElements keyword. For example:

Here You cannot see that "Using webelement" starts a new subsection, and you must read it twice or more to recognise that.

**Comment by just-be-dev** [comment]
It's a little better as of the 1.7.3 release. 

We'll try to continue to improve it in the future. 

Feel free to submit a PR.

Thanks.
