### ISSUE TITLE
Passing window id as an argument to python script

### ISSUE THREAD

**Issue by mamathanag** [robotframework/SeleniumLibrary#48]
I am trying to implement the page object design where , the page is the class and the services offered by the page are methods/functions within that class... I am stuck with partial execution in Robot and method/function calls in python

My Code: 
**\* Settings ***
Library           Selenium2Library
Library           xlrd
Library           ReadExcel

**\* Variables ***
${Test_test_URL}    http://stage.Test.com
${Browser}        googlechrome
@{Valid Email IDs}
${ExcelFileName}    C:\Users\user\Documents\Test\Login\Test_login_email.xls
${ExcelSheetName}    DataSet
${EveryEmail}     ${EMPTY}

**\* Test Cases ***
request an invitation
    open browser    ${Test_test_URL}    ${Browser}
    @{Valid Email IDs}    read values    ${ExcelFileName}    ${ExcelSheetName}
    : FOR    ${EveryEmail}    IN    @{Valid Email IDs}
    \    send an invite    ${EveryEmail}

**\* Keywords ***
send an invite
    [Arguments]    ${arg1}
    Input Text    email    ${arg1}
    click button    SEND
    Wait until page contains    Thank you - we will contact you!    30

---

I intent to replace the piece of logic in "Send an Invite" code
(Input Text    email    ${arg1}
    click button    SEND) 
as a call to a python script with valid email address as the argument. However, How do I pass the browser handle to the python script and how do I receive the browser handle within the python script so I can call functions like driver.find_element_by_id("email")

we would typically do : driver = webdriver.Firefox(); but this would open a new instance... I want the script to work on the existing instance of the browser...

Please help!

**Comment by emanlove** [comment]
On 04/27/2012 05:46 AM, mamathanag wrote:

> I am trying to implement the page object design where , the page is the class and the services offered by the page are methods/functions within that class... I am stuck with partial execution in Robot and method/function calls in python
> 
> My Code:
> **\* Settings ***
> Library           Selenium2Library
> Library           xlrd
> Library           ReadExcel
> 
> **\* Variables ***
> ${Test_test_URL}    http://stage.Test.com
> ${Browser}        googlechrome
> @{Valid Email IDs}
> ${ExcelFileName}    C:\Users\user\Documents\Test\Login\Test_login_email.xls
> ${ExcelSheetName}    DataSet
> ${EveryEmail}     ${EMPTY}
> 
> **\* Test Cases ***
> request an invitation
>      open browser    ${Test_test_URL}    ${Browser}
>      @{Valid Email IDs}    read values    ${ExcelFileName}    ${ExcelSheetName}
>      : FOR    ${EveryEmail}    IN    @{Valid Email IDs}
>      \    send an invite    ${EveryEmail}
> 
> **\* Keywords ***
> send an invite
>      [Arguments]    ${arg1}
>      Input Text    email    ${arg1}
>      click button    SEND
>      Wait until page contains    Thank you - we will contact you!    30
> 
> ---
> 
> I intent to replace the piece of logic in "Send an Invite" code
> (Input Text    email    ${arg1}
>      click button    SEND)
> as a call to a python script with valid email address as the argument. However, How do I pass the browser handle to the python script and how do I receive the browser handle within the python script so I can call functions like driver.find_element_by_id("email")
> 
> we would typically do : driver = webdriver.Firefox(); but this would open a new instance... I want the script to work on the existing instance of the browser...
> 
> Please help!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rtomac/robotframework-selenium2library/issues/48

Mamatha,

You should look within the selenium2library code, in particular the 
src/Selenium2Library/keywords/_browsermanagement.py file and possible 
the robotframework/src/robot/utils/connectioncache.py file. Here is 
where the handle to the particular webdriver field exists.  I don't see 
any keywords within selenium2libary which passes this handle along; most 
of the implemenation is hiddened behind the various browser keywords. 
You could try adding a keyword to add this functionality.

The other alternative to using python code to implement the page object 
paradigm is to simply use user keywords, and resource and variable 
files. In other words use the architect of robot framework to create 
page objects.  I'm currently working on a significant sized open source 
project for which I was going to try a similar method of creating page 
objects using just keywords, resource files and variable files.

Ed

**Comment by j1z0** [comment]
Further on Ed's comment for one of my currenengagments we are extending S2L is a customer specific was so we create a RobotFramework Library (lets call it CustLib) and CustLib just inherits from S2L.  That we from cost lib we have access to _browsermanagement all all the other cool functionally that S2L provides.

**Comment by mamathanag** [comment]
@Ed - Thanks for your suggestion. A question on the alternative of using keywords. Isn't  that the way I have implemented currently or are you suggesting something else that I may have missed?

**Comment by mamathanag** [comment]
@j1z0 : Appreciate your response. Sounds interesting. I will try it out however I am not confident of implementing this myself...will sure try.

**Comment by j1z0** [comment]
Let me know if u need some help and I could put some code samples together for u. 

Cheers,
Jeremy

**Comment by mamathanag** [comment]
@Jeremy .... Wow.....that would really help..... I am feeling lucky....

Cheers,
Mamatha

**Comment by emanlove** [comment]
On 04/28/2012 12:25 AM, mamathanag wrote:

> @Ed - Thanks for your suggestion. A question on the alternative of using keywords. Isn't  that the way I have implemented currently or are you suggesting something else that I may have missed?

@Mamatha, What I was suggesting was that you could use test resources as 
a page object and thus do your page objects within the plain text test 
resources files instead of using variable files which are python code.  
Tony Sweets provides an example of this in his blog post "Using the Page 
Object Pattern with Robot Framework" http://www.beer30.org/?p=54.

**Comment by SeleniumTester** [comment]
I am writing test script using robot framework to read data from Excel.
Does anyone know how to access different sheet in Excel?

I am using Excel library to read data from Excel but I don't see any method in this to refer different sheet.

I also tried xlrd library 
but when I try to use sheet by name or sheet by index method, it always say "keyword not found" although I have xlrd library added.

Please let me know if someone know any method to refer different sheet in Excel.
