### ISSUE TITLE
Write up a collaborators guideline

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#485]
As our team has recently expanded, it would be good to have a goto list of guidelines for collaborators. 

Here's a few things I think it should have
- Never commit directly to master
- Never merge a PR that fails CI
- Never merge a PR that adds functionality but doesn't properly test it
- Ensure the changelog is updated if any notable change is made
- Try to get others to review changes before merging

This is just a start and I would love to hear suggestions and improvements.

@pekkaklarck It would also be beneficial to know how RF handles this.

**Comment by pekkaklarck** [comment]
First of all, we just recently got contributing guidelines written for Robot Framework itself. One of the goals was that other project could refer to them from their guidelines and just list things they do differently. All kind of comments and enhancement ideas related to them are highly appreciated. You can find them here:
https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst

Robot's guidelines don't talk too much about the items listed above. They look pretty good to me in general, and something like that could be added to Robot's guidelines too. I wouldn't ban committing directly to master, though. @jussimalinen and I do it with Robot, but with all more complicated code we use pair programming or at least review the code face-to-face.

**Comment by just-be-dev** [comment]
That's absolutely a great resource, but I was gearing this to be directly for our team members who have write access to the repository. I feel like this should be a separate document from the contributors guidelines, though not necessarily mutually exclusive.

To be honest, I've committed to master a few times on this project as well. Generally though, those commits have only been one or two lines and usually only fix typos or documentation. I'm generally okay with those types of things getting committed directly to master, but it can be hard to classify what's OK to be committed directly to master and what needs to be in a PR. 

For a smaller team I don't think there's any issue with occasionally committing to master, but I feel it should be avoided in larger teams. It's more of a better safe than sorry approach, but I'm certainly open to opposing opinions on this.

**Comment by aaltat** [comment]
I am huge fan of code reviews, they help spot many kind of issues (where the author is usually blind). Also it helps share the knowledge of the product within the team and may lead to different/better implementation.

The other items in @zephraph list are good too.

**Comment by pekkaklarck** [comment]
I would include process documentation for the team members in `CONTRIBUTING.(rst|md)` along with other such guidelines. It's easy to have separate sections and a table of contents. I'd only have building/releasing instructions separately in `BUILD.(rst|md)`. Also, S2L having a policy that nothing is committed to master directly is just fine.

**Comment by aaltat** [comment]
Initial version in #509, only copy/pasted from [RF CONTRIBUTING.rst](https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst) and modified relevant sections. All the good ideas what @zephraph has in mind where not done.

**Comment by aaltat** [comment]
The #509 was merged to the master, therefore closing the issue
