### ISSUE TITLE
Investigate using AWS S3 to serve result files

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#486]
Currently in our travis setup there's no way to see the log/result files that are generated by RF from our CI tests. I would like to configure our travis setup to store log/result files on an AWS S3 instance.

My envisioned setup:
- Travis is configured to store log/result files in an S3 bucket. (Read [here](http://docs.travis-ci.com/user/uploading-artifacts/)).
- Add a static landing page that uses JS to pull up all the results (using js) and show them in a list
- Have the S3 bucket instance automatically delete results > 1 week old

**Comment by aaltat** [comment]
I like the idea, no idea how to do it though. But if someone does it, I gladly accept

**Comment by just-be-dev** [comment]
I plan on being the one to implement it. Heh, I'll have to pay for the S3 service anyway.

**Comment by aaltat** [comment]
This is only possible if we use Travis cron feature. For regular PR this is not possible and therefore I don't think we are going to use this. Closing.
