### ISSUE TITLE
Raise minimum RF version to 2.8

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#488]
Supporting all the way back to 2.6 is a bit challenging, and I'm not even sure we actually do support versions that old. 

In the next major release we're going to set the minimum supported version of RF to 2.8.

**Comment by emanlove** [comment]
What do you mean by "support"? What breaks with with versions prior to 2.8? I am extremely hesitant to bump dependency version (under setup.py) without understanding the consequences, which in this case could blindly force people to upgrade or were allowing a prior version that doesn't work with the current library.

We've bumped a required version in the past with the [most recent example](https://github.com/rtomac/robotframework-selenium2library/commit/860f753cfc74c9e49d7949c0afccb22cc412bae7) of when we added support for the WebDriver Select class. Here there was a minimum version for which Selenium contained that class code.

I would suggest we investigate and run the library under 2.6 and 2.7 and see what breaks. Although setting the minimum version to 2.8 sounds reasonable if the Selenium2Library still works with 2.6/2.7 than I would leave it be. We also need to be careful as we move forward that we either provide plenty of notice to updating minimum version and make sure we are not adding code that makes large jumps to the most recent version of the dependencies.

**Comment by just-be-dev** [comment]
Agreed. We really need to be more careful with changes in general (and I say this for me more than anyone else).

**Comment by pekkaklarck** [comment]
I don't have anything against supporting older Robot versions, but I doubt there are that many users that run e.g. RF 2.6 with the latest S2L.

If a version is declared to be supported, it should also be tested. In practice there should be CI jobs for all supported versions. To limit this a bit, S2L could declare that it supports the latest three (or even two) RF major versions.

**Comment by aaltat** [comment]
Removed 1.8 scope because of lack of time

**Comment by aaltat** [comment]
We are doing this and we did create a new issue about it. Closing this one because it is so down on the list
