### ISSUE TITLE
Does current selenium2lib support selenium grid 2?

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#49]
Any one has tried this?

Thanks!

Adam

**Comment by j1z0** [comment]
I haven tried but selenium 2 library does support the remote web driver protocol so that should get you at least some Of the way there. 

Cheers,
Jeremy

**Comment by adwu73** [comment]
Thanks I will give a try and post the result

**Comment by adwu73** [comment]
I finally got time to set up this and give a try. The result is promising, I can use s2l with selenium grid 2 successfully (there is only one capture screen shot issue listed in issue 43). What you need to do is to set up grid 2 hub & node as documented, and use the name open browser capability in release 1.0.1

Open Browser | <dest url> | IE | |  <hub url>

**Comment by j1z0** [comment]
Nice. :). One feature I was thinking about adding / bringing back us the start server keyword. Which you could use to programmatically start up the grid or any remote server for that matter. Is that something you would use?  Or do you have other ways to manage startup of the grid?

**Comment by adwu73** [comment]
when you start the grid, you have to start the grid server as well as the grid node(is this techically possible?). I don't think this process should be a part of the test case. For now, I think I will manage the grid start up seperately.

**Comment by jollychang** [comment]
@adwu73 is my setting correct?  

### hub

```
java -jar /home/jollychang/selenium-server-standalone-2.25.0.jar -role hub  
```

### node

```
java -jar /home/jollychang/selenium-server-standalone-2.25.0.r  -role webdriver -port 5556 -hub http://localhost:4444/grid/register  
```

### robotframework-selenium2library

```
Open Browser  ${HOST}  ${BROWSER}  None  http://127.0.0.1:4444/wd/hub  
```

> WebDriverException: Message: u"Modal dialog present\nBuild info: version: '2.25.0', revision: '17482', time: '2012-07-18 21:08:56'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.34-gentoo-r12', java.version: '1.6.0_24'\nDriver info: driver.version: EventFiringWebDriver\nSession ID: 20947b2d-1ec0-4464-bb68-e09fb7850650" ; Stacktrace: Method newInstance0 threw an error in NativeConstructorAccessorImpl.java 

### Grid2 logs

> 14:52:19.530 WARN - Exception thrown  
> org.openqa.selenium.UnhandledAlertException: Modal dialog present
> Build info: version: '2.25.0', revision: '17482', time: '2012-07-18 21:08:56'
> System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.34-gentoo-r12', java.version: '1.6.0_24'
> Driver info: driver.version: EventFiringWebDriver
> Session ID: f1bd7b8d-1d00-4d00-a4ba-d816c0ed9a95
>         at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
>         at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:188)
>         at org.openqa.selenium.remote.ErrorHandler.createUnhandledAlertException(ErrorHandler.java:169)
>         at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:141)
>         at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:498)
>         at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:242)
>         at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:616)
>         at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
>         at $Proxy1.get(Unknown Source)
>         at org.openqa.selenium.support.events.EventFiringWebDriver.get(EventFiringWebDriver.java:155)
>         at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:38)
>         at org.openqa.selenium.remote.server.handler.ChangeUrl.call(ChangeUrl.java:1)
>         at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:166)
>         at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:150)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>         at java.lang.Thread.run(Thread.java:679)
> 14:52:19.531 WARN - Exception: Modal dialog present

**Comment by adwu73** [comment]
I start node like this
 java -jar selenium-server-standalone-2.24.1.jar -role node -hub http://<hubname>:4444/grid/register

it seems that you have been hit by another issue, not related to grid2

Modal dialog present

**Comment by jollychang** [comment]
I post a blog for this  
http://testlog.jollychang.com/robotframework-selenium2library-for-grid2

**Comment by mithundinil** [comment]
s

**Comment by mithundinil** [comment]
How to control robot java class on remote machine (selenium-grid). Please advice to resolve this issue.
