### ISSUE TITLE
Add keywords for checking whether element or page has scrollbars

### ISSUE THREAD

**Issue by daluu** [robotframework/SeleniumLibrary#51]
Copying over request from SeleniumLibrary:

http://code.google.com/p/robotframework-seleniumlibrary/issues/detail?id=209

**Comment by emanlove** [comment]
Pushing to 1.2 release...

**Comment by aaltat** [comment]
There has not been activity for this issue for few years and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closed because of inactivity. If someone encounters similar or same problem please open a new issue.
