### ISSUE TITLE
Improve remote_url example in Open Browser keyword

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#510]
The documentation for the "Open Browser" keyword says:
"Optional 'remote_url' is the url for a remote selenium server for example http://127.0.0.1/wd/hub."

With that, connection to the selenium server is not successful, as the port number is missing. I would suggest to change this to 
"Optional 'remote_url' is the url for a remote selenium server for example http://127.0.0.1:4444/wd/hub."

**Comment by aaltat** [comment]
Good catch, would you mind making a pull request and fix the doc too?

**Comment by tarand** [comment]
Hi;

what do you mean with “making a pull request”?

Ciao,
                thomas

**Comment by aaltat** [comment]
Pull request is explained in the GitHub documentation: https://help.github.com/articles/using-pull-requests/

**Comment by aaltat** [comment]
The #518 offers fix for this minor issue.

**Comment by aaltat** [comment]
Closed because #518 was merged to master

**Comment by tarand** [comment]
Thank you!

Thomas
