### ISSUE TITLE
Is "Open Browser" working correctly if an alias is given?

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#511]
According to the documentation, I would expect that I can pass any value a argument for "Open Browser", e.g.

Open Browser | ${url} |alias=abc

However, if I do that I get "alias=abc is not a supported browser"

Is that an expected behavior?

**Comment by pekkaklarck** [comment]
`alias=abc` definitely should work. Which RF version do you use?

**Comment by tarand** [comment]
RF 2.9
Selenium2: 1.7.2

**Comment by pekkaklarck** [comment]
Tested this and everything worked OK.

**Comment by tarand** [comment]
Hi Peke,

you are right, it works when using the Open Browser keyword directly.

For some reasons we need to call it via a wrapper keyword. All of those named args should be passed as a list – that works well in another example. But as in this case these optional args have to be given in the following way:
                alias=abc

I guess that robot makes a directory variable (map) out of it. However, I would need a real list in this way.

Any ideas how to get this?

BTW: if I’m right, this would be a backward incompatible change in robot 2.9…

Ciao,
                Thomas

**Comment by tarand** [comment]
Hi Peke,

I got it! I must specify the “optional named parameters” in my wrapper keyword with the directory-variable syntax, e.g. &{additionalPars}

With that it works.

Thanks for your support!

BTW: there is a bug in robotide_1.4. It seems to be not possible to enter that ‘&’ in the parameter field of a keyword.

Ciao,
                Thomas

you are right, it works when using the Open Browser keyword directly.

For some reasons we need to call it via a wrapper keyword. All of those named args should be passed as a list – that works well in another example. But as in this case these optional args have to be given in the following way:
                alias=abc

I guess that robot makes a directory variable (map) out of it. However, I would need a real list in this way.

Any ideas how to get this?

BTW: if I’m right, this would be a backward incompatible change in robot 2.9…

Ciao,
                Thomas

**Comment by pekkaklarck** [comment]
1. Yes, you can use `&{dict}` variable to accept unlimited number of free named arguments. This is a new feature in RF 2.9.
2. Alternatively you could just have `${alias}=${None}` in arguments and later use `Open Browser` with `alias=${alias}`.
3. RIDE 1.4 doesn't support new features in RF 2.9. RIDE 1.5 does.
