### ISSUE TITLE
'Get List Items' ValueError Message

### ISSUE THREAD

**Issue by Tset-Noitamotua** [robotframework/SeleniumLibrary#513]
I tried to use the 'Get List Items' keyword on such element `xpath=//li[@class="foobar"]` which I thought is just another ordinary list. This element is definitly on the tested page but I got this error:

``` log
ValueError: Element locator 'xpath=//li[@class="endcustomer-search__result"]' did not match any elements.
```

Maybe the error message should better be something like `This ist not a valid list`(?)

**Comment by emanlove** [comment]
I could see some better error reporting when filtering by either tag or constraints. In this case as you've noted the Get List Items is for select elements and not list elements. It might be hard to give smart response like "This is a list element when what is expeccted is a select element" but a simple "<This keyword> was expecting an element with tag select/constaint xxxx " or even simplier "Element locator did not find any elements with <tag/constraint>".

**Comment by Tset-Noitamotua** [comment]
Another quick solution would be to note in keyword documentation that this (and some other related keywords) are not intended to work with `<li> ... </>` elements although the keyword's semantic suggests that.

**Comment by aaltat** [comment]
This might be fixed with the current code in the master. @Tset-Noitamotua would you give it try and see if you are happy with the results?

**Comment by pekkaklarck** [comment]
I don't think this has changed. List related keywords only work with select elements.

**Comment by aaltat** [comment]
Closing due inactivity.
