### ISSUE TITLE
using screenshot_root_directory in constructor does not work

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#517]
I need to have a different location for the failure-screenshots. According to the doc, I should be able to use screenshot_root_directory=dir when initializing the Selenium2Library. But that does not work.
I also tried run_on_failure=nothing, but also this parameter is obviously being ignored.

However, when calling set_screenshot_directory explicitly, it works as expected.

Any ideas what could cause this failure? Note: I also use the Selenium2Library in other files (such as keyword files), where I do not specify the screenshot_root_directory parameter. Could that be a reason?

**Comment by just-be-dev** [comment]
S2L is a global library. That means it's only initialized once, afterwards each suite pulls in the existing instance. In this case, passing in the `screenshot_root_directory` will only work on your first import of S2L and will be used for the rest of the test execution. If you only want to set it in certain tests you need to explicitly use `set_screenshot_directory`. Same goes for the `run_on_failure` argument.

**Comment by tarand** [comment]
Hi,

thanks for the answer!

Yes, this is what I would also have expected. Note: I did not manage to get it to work (constructor call). Can it be the reason that we a using jython 2.7 as a start for robot.

As I have some test suites within the same directory (being execution within the same robot call), and each of them should use a different screenshot_root_directory, I need to use the set_screenshot_directory keyword.

Thomas

**Comment by kathor15** [comment]
Hello,
Is there any more information on this issue?  I've installed new version of Selenium2Library and the screenshot on failure of the test still doesn't show in directory that I defined with screenshot_root_directory. Could you let me know if you did any further investigation on that?

**Comment by emanlove** [comment]
One method of debugging is to place the following line of code,

``` python
 import pdb,sys; pdb.Pdb(stdout=sys.__stdout__).set_trace()
```

into the source code which on windows is usually found C:\Python2x\lib\site-packages\Selenium2Library...

This will allow you to run the [Python pdb debugger](https://docs.python.org/2/library/pdb.html) at the command prompt.

**Comment by ombre42** [comment]
Although Selenium2Library is global, if you import it in different places with different arguments, the library should be re-loaded to make the arguments effective. See the [note in the part on global in Test library scope in the user guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-library-scope).
My guess is that you are importing Selenium2Library in multiple places. There is not an easy way to debug this. If you are using RF > 2.9, you could write a simple listener to print to the console when Selenium2Library is being imported (where from and with what arguments). I advocate importing libraries through resource files. In that style, you would have to call Set Screenshot Directory in a suite setup.

If I run RF pointing to a folder containing the following two test suites (all executing in the same RF instance), the screenshot stored in the folders specified.

Test1.robot:

```
*** Settings ***
Test Teardown     Close All Browsers
Library           Selenium2Library    screenshot_root_directory=c:/screenshots1

*** Test Cases ***
Failing Test Case
    Open Browser    http://www.google.com    gc
    Page Should Contain Element    id=not_here
```

Test2.robot:

```
*** Settings ***
Test Teardown     Close All Browsers
Library           Selenium2Library    screenshot_root_directory=c:/screenshots2

*** Test Cases ***
Another Failing Test Case
    Open Browser    http://www.google.com    gc
    Page Should Contain Element    id=not_here
```

**Comment by just-be-dev** [comment]
Ah, I see. Didn't realize. Regardless, I wasn't clear earlier but the `Set Screenshot Directory` Keyword will accomplish the same thing.

**Comment by ombre42** [comment]
@zephraph The reason the note is in the user guide is because [I asked it to be added](https://code.google.com/p/robotframework/issues/detail?id=1508). It is a bit of a gotcha I bet a lot of people do not know about. I probably got tripped up by the behavior at some point.

**Comment by kathor15** [comment]
I agree about the addition to the documentation. But if I understand you correctly if I initialize the Selenium2Library with the screenshot_root_directory=c:/screenshots1 the second test (Test2.robot:) will store screenshots there if I don't add the screenshot_root_directory argument, because the instance was already initialized. So the initialization is done only in the first run of the test suite?

**Comment by ombre42** [comment]
Not quite. If in the second suite file you do not specify screenshot_root_directory, Robot Framework will see that you used different arguments than the last time the library was imported. In this case Robot Framework will create a new instance of Selenium2Library. Since it is a new instance, the library will use the default path (where the test log is written to). Every time you import a library, Robot Framework remembers what arguments where used to import the library. If the arguments where the same, then the global library instance is re-used. Otherwise a new instance is created with the new parameters.

**Comment by just-be-dev** [comment]
Heh, I learned something today. That totally runs counter to how I thought it worked. Interesting.

**Comment by aaltat** [comment]
Because this issue seems resolved I am closing the issues.
