### ISSUE TITLE
Current Frame Contains keyword should be renamed

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#520]
The naming of this keyword is against the conventions that are used in Selenium2Library. Consequently it should be "Current Frame Should Contain".
Note: this was the case in the original SeleniumLibrary.
(However, for a smooth migration you must first implement a copy of this keyword before you can delete this keyword later)

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by tarand** [comment]
I still think you should rename this keyword. It is totally against the naming conventions of other selenium keywords.

Ciao,
                Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com

**Comment by pekkaklarck** [comment]
Good news, this keyword has already been renamed! See #920.
