### ISSUE TITLE
Load FF extension

### ISSUE THREAD

**Issue by rarajabs** [robotframework/SeleniumLibrary#522]
Hi, do this possible to load FF extension?

such as Open browser    ff    ff_profile_dir=profile.default    ff_extension=extension.xpi ?

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
