### ISSUE TITLE
Cannot use webelement with Table keywords

### ISSUE THREAD

**Issue by manycoding** [robotframework/SeleniumLibrary#524]
I have many 1-row tables at a page.
I want to check if all of them have identical values at the specified column.

@{tables}=    Get Webelements    //div[contains(@id, "table_grid_TreeGrid")]//table[@class = "gridxRowTable"]

 :FOR  ${row}  IN  @{tables}
    \  Table Column Should Contain    ${row}    1    Value

It throws:
AttributeError: 'WebElement' object has no attribute 'startswith'

**Comment by emanlove** [comment]
The Table keywords don't work with WebElements. If you want to use the Table Keyword you have to use either a css, jquery/sizzle, or xpath locator strategy or if no strategy used it assumes css. You might be better off just using the webelements and using something like Get Text.

**Comment by manycoding** [comment]
Surely there's a way to work around it.

Although, since WebElement is introduced, don't you think it'd be appropriate to make it work with as many keywords as possible?

**Comment by emanlove** [comment]
Agreed, thus #525.

**Comment by aaltat** [comment]
As a side comment you should be able to this with pure xpath and you should not need the for loop.

But tables are always complex and perhaps it would be better to return the row, column or whole table from keyword and then iterate over list(s).

**Comment by aaltat** [comment]
Closing due inactivity
