### ISSUE TITLE
Click Element has no effect unless preceded by Capture Page Screenshot

### ISSUE THREAD

**Issue by janihur** [robotframework/SeleniumLibrary#534]
I'm trialing Selenium WebDrive and Robot Framework with a Javascript web application that runs in an iframe on top of an existing website. I have run into very peculiar behavior that for me looks like a bug - I'm unable to "click" a link in an iframe unless I `Capture Page Screenshot` before `Click Element`. `Click Element` doesn't report an error but the app state is not changing and thus the following `Wait Until Element Is Visible` fails.

The following is the full test case that demonstrates the issue. Just comment and uncomment `Capture Page Screenshot` to reproduce the issue. The SUT is publicly available in http://test.hoogleit.com.

```
* Settings *
| Documentation | Log-in tests
| Library | Selenium2Library

* Variables *
| ${PRICE_CHAT_BUTTON} | xpath=/html/body/div[4]/div/div[2]/div/div[3]/table/tbody/tr[@class='product-row']/td[div/div[@itemprop='name' and text()='Castelgarden XC53 BSW4']]/div[@class='hoogleButton']
| ${EMAIL_LOGIN_BUTTON} | xpath=//a[@class='hgl-btn email']

* Test Cases *
| Login failure
| | Open Browser | http://test.hoogleit.com/category-garden-equipment
| | Wait Until Page Contains Element | ${PRICE_CHAT_BUTTON} | timeout=60
| | Click Element | ${PRICE_CHAT_BUTTON}
| | Wait Until Page Contains Element | id=iframe_hoogle
| | Select Frame | id=iframe_hoogle
| | Wait Until Page Contains Element | ${EMAIL_LOGIN_BUTTON} | timeout=30
| | Element Text Should Be | ${EMAIL_LOGIN_BUTTON} | LOG IN WITH EMAIL
# WTF: Screenshot required to the Click Element take effect ?
#| | Capture Page Screenshot
| | Click Element | ${EMAIL_LOGIN_BUTTON}
# If I press the button myself the rest of the test case executes correctly including Click Button:
| | Wait Until Page Contains Element | id=Email | timeout=30
| | Wait Until Element Is Visible    | id=Email | timeout=30
| | Input Text                       | id=Email | my_account
| | Wait Until Element Is Visible    | id=Password | timeout=30
| | Input Password                   | id=Password | my_password
| | Click Button                     | id=aspnet-login-button
| | Wait Until Page Contains Element | xpath=//article[@class='hgl-system-message error'] | timeout=30
| | Wait Until Element Is Visible    | xpath=//article[@class='hgl-system-message error'] | timeout=30
| | Page Should Contain Element      | xpath=//article[@class='hgl-system-message error']
| | Page Should Contain Element      | xpath=/html/body/div[@id='hoogle_window']/section[@id='hgl-orb-contents']/main/section[@id='system-message-container']/article[@class='hgl-system-message error']
```

I'm running Robot in a fresh Vagrant box with:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
$ python --version
Python 2.7.6
$ pybot --version
Robot Framework 2.9.2 (Python 2.7.6 on linux2)
$ pip show robotframework-selenium2library

---
Name: robotframework-selenium2library
Version: 1.7.4
Location: /usr/local/lib/python2.7/dist-packages
Requires: decorator, selenium, robotframework, docutils
$ dpkg -s firefox|grep Version:
Version: 42.0+build2-0ubuntu0.14.04.1
```

I have attached files from two test runs.

Working test run:
- [debug-20151115-210923.txt](https://github.com/robotframework/Selenium2Library/files/34982/debug-20151115-210923.txt)
- [output-20151115-210923.txt](https://github.com/robotframework/Selenium2Library/files/34986/output-20151115-210923.txt)
- [log-20151115-211015.txt](https://github.com/robotframework/Selenium2Library/files/34984/log-20151115-211015.txt)
- [report-20151115-211015.txt](https://github.com/robotframework/Selenium2Library/files/34988/report-20151115-211015.txt)

Failing test run:
- [debug-20151115-211259.txt](https://github.com/robotframework/Selenium2Library/files/34983/debug-20151115-211259.txt)
- [output-20151115-211259.txt](https://github.com/robotframework/Selenium2Library/files/34987/output-20151115-211259.txt)
- [log-20151115-211339.txt](https://github.com/robotframework/Selenium2Library/files/34985/log-20151115-211339.txt)
- [report-20151115-211339.txt](https://github.com/robotframework/Selenium2Library/files/34989/report-20151115-211339.txt)

**Comment by HelioGuilherme66** [comment]
Yes, I can confirm that strange behavior.

I did have success when replaced Capture Screenshot with "Sleep    1
second".

Some how it needs a delay before actually clicking the button (and that was
what Capture Screeshot was doing).

**Comment by aaltat** [comment]
This is quite typically problem with web applications which use JavaScript. The element is there but the JavaScript running in the background is not ready. Therefore the interaction with the element does not work.

For me, usually, there are other indicators in the page which can tell is the JavaScript running or not. Sometimes I will have to wait some other element or an attribute of am element (same or other) and then perform the desired action. If there are not obvious indicators, I go and discuss with the developer about the problem and usually we can find a suitable solution for the problem in hand. For the small amount of problems, I am forced to use sleep, Wait Until Keyword Succeeds or both. Example like this:

```
| Click Login Button |
| | Wait Until Keyword Succeeds | 10 | 2 | Helper Click |

| Helper Click |
| | Clock Element | xpath=//button/xpath/here |
| | Wait Until Page Contains Element | xpath=//next/page/xpath/here | 1s |
```

Note: The above code is untested and written out of my memory, so it may contain errors.. 

Also these kinds of ugly helpers should be last tool in your arsenal and not the first one. Because perhaps it's a real bug and there might be better solution to your problem.

But as bottom line, this looks like it is not a Selenium2Library issue, instead it looks your web application problem. At least for me it strongly looks that way, but I can't not be sure. If you disagree, more details from your problem is needed.

**Comment by janihur** [comment]
Thanks for your comprehensive comment ! I'll consider your advice and think the suggested workarounds.

**Comment by aaltat** [comment]
As a followup, it would be really nice if you could share what what was the solution that did help you. Or if you didn't find a solution and went for a totally different automation solution.

**Comment by janihur** [comment]
I run into similar (Javascript) issues also with another web application (3rd party, not under my control) where I was not running Robot but Selenium Webdriver directly from Python. I'm not a front-end guy but based on my sample size of 2 it looks like a modern front-end convention is to heavily modify DOM in the browser instead of reloading the DOM from the server ([single-page application](https://en.wikipedia.org/wiki/Single-page_application)). So instead of checking an element existence one should check element visibility. In Selenium2Library this means using [Wait Until Element Is Visible](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Wait%20Until%20Element%20Is%20Visible) and with Webdriver the corresponding [expected condition](http://selenium-python.readthedocs.org/en/latest/api.html#module-selenium.webdriver.support.expected_conditions).

In my original issue I had to rely on `Sleep`. My best guess at the moment is the problem is related to CSS transition that takes place when the haggle button is pressed. Below you'll find a full example of my current test case that works correctly. The key is `Patient Click Element`-keyword that is having an extra `Sleep` that resolves the issue.

```
* Settings *
| Documentation | Log-in tests
| Library | Selenium2Library
| Variables | variables.py

* Variables *
| ${EMAIL_LOGIN_BUTTON} | xpath=//a[@class='hgl-btn email']

* Keywords *
| Open Hoogle UI
| | [Arguments] | ${category} | ${product_name}
| | ${category_url} = | Set Variable | http://test.hoogleit.com/category-${category}
| | ${haggle_button_locator} = | Set Variable | xpath=/html/body/div[4]/div/div[2]/div/div[3]/table/tbody/tr[@class='product-row']/td[div/div[@itemprop='name' and text()='${product_name}']]/div[@class='hoogleButton']
| | Open Browser                     | ${category_url}
| | Wait Until Page Contains Element | ${haggle_button_locator} | timeout=60
| | Click Element                    | ${haggle_button_locator}
| | Wait Until Page Contains Element | id=iframe_hoogle
| | Select Frame                     | id=iframe_hoogle
| | Wait Until Element Is Visible    | xpath=//div[@id='main-login'] | timeout=30

| Patient Click Element
| | [Arguments] | ${locator} | ${wait}=1 second
| | [Documentation] | A workaround to mysterious no-effect Click Element (maybe because CSS transition)
| | Sleep | ${wait}
| | Wait Until Element Is Visible | ${locator} | timeout=30
| | Click Element | ${locator}

* Test Cases *
| Failed email login
| | Open Hoogle UI | garden-equipment | Castelgarden XC53 BSW4
| | Patient Click Element         | ${EMAIL_LOGIN_BUTTON}
| | Wait Until Element Is Visible | id=Email | timeout=30
| | Input Text                    | id=Email | my_account
| | Wait Until Element Is Visible | id=Password | timeout=30
| | Input Password                | id=Password | my_password
| | Click Button                  | id=aspnet-login-button
| | Wait Until Element Is Visible | xpath=//article[@class='hgl-system-message error'] | timeout=30

| Successful email login
| | Open Hoogle UI | garden-equipment | Castelgarden XC53 BSW4
| | Patient Click Element         | ${EMAIL_LOGIN_BUTTON}
| | Wait Until Element Is Visible | id=Email | timeout=30
| | Input Text                    | id=Email | ${HOOG_USERNAME}
| | Wait Until Element Is Visible | id=Password | timeout=30
| | Input Password                | id=Password | ${HOOG_PASSWORD}
| | Click Button                  | id=aspnet-login-button
```
