### ISSUE TITLE
Allowing rebot to process Report and Log for acceptance tests when using --dryrun

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#536]
See PR #535

In a more global PR for robotframework, I plan to use the `--dryrun` option in rebot to be accepted and give relevant results.

For now this allows running the acceptance tests with the `--dryrun` option and obtain the Report and Log files.

In this PR, it is also changed to `include_root_package_name = True` in run_unit_tests.py which is critical for me in my Linux machine (and harmless in Windows).

**Comment by aaltat** [comment]
PR did broke the Travis integration, so at least that should be fixed.

But could you explain why you need the dryrun option available in the S2L acceptance test runner?

I don't recall what the `include_root_package_name` actually does. Does someone remember what it does and why we have it?

**Comment by HelioGuilherme66** [comment]
My only explanation for the Travis build fail, is the Python versions
(being too picky with try/exception).
Now that I am writing this, I think I have also to catch ValueError.
Travis is using Python 2.6 and 2.7.6. My system has 2.7.10.

I have plans to expand `--dryrun` to obtain a list of test files,
resources, libraries, test cases names, and most important; all tag names.
This PR was done because rebot errors when using `--dryrun`, and does
not produce Report and Log. Log is helpful to see all the info I mentioned.

The `include_root_package_name` translates like a Namespace (I think),
and there are some tests found that would construct the correct path if
False.

(I am writing this by memory, later I will see if I fix the build, ~~and show
error message~~ see below the error)

On Tue, Nov 17, 2015 at 3:57 PM, Tatu Aalto notifications@github.com
wrote:

> PR did broke the Travis integration, so at least that should be fixed.
> 
> But could you explain why you need the dryrun option available in the S2L
> acceptance test runner?
> 
> I don't recall what the include_root_package_name actually does. Does
> someone remember what it does and why we have it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robotframework/Selenium2Library/issues/536#issuecomment-157412659
> .

EDIT: This is the output when `include_root_package_name` set to False

```
[helio@localhost test]$ python run_tests.py python firefox
Running unit tests
Traceback (most recent call last):
  File "run_tests.py", line 110, in <module>
    unit_failures = _run_unit_tests()
  File "run_tests.py", line 99, in _run_unit_tests
    failures = run_unit_tests()
  File "/home/helio/robotframework-selenium2library/test/run_unit_tests.py", line 8, in run_unit_tests
    env.UNIT_TEST_DIR, include_root_package_name = False, pattern="test*.py")
  File "/home/helio/robotframework-selenium2library/test/../src/Selenium2Library/utils/__init__.py", line 43, in import_modules_under
    for module_name in module_names ]
ImportError: No module named test_browsercache
```

**Comment by pekkaklarck** [comment]
How should `--dryrun` work with Rebot?

**Comment by HelioGuilherme66** [comment]
Right now it would just be fine if ignores the option and proceed with Report and Log.
Future improvements, would represent a complete table with all tags found in tests (possibly using color styling), some tree of the test suites (file paths), etc. Info that we usually don't need or want in a Log, but we need to prepare a test run.
(In this S2L case, I would like to know which Test Suites are to avoid in Jython, for example)

**Comment by pekkaklarck** [comment]
Discussing about possible RF enhancements in S2L tracker is off-topic, but quick comments anyway:
- I don't think it is a good idea to ignore invalid options.
- Showing information based on output.xml on the console sounds like an OK idea, but that should probably be a task for a separate tool.
- Even if Rebot would be enhanced to show info on the console, using `--dryrun` option to enable that would be weird.

**Comment by aaltat** [comment]
What we should do with this pull request?

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
