### ISSUE TITLE
New keyword Highlight

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#537]
In this commit: https://github.com/HelioGuilherme66/robotframework-selenium2library/commit/49574dd1be6df2eccae8b56656ab5ea53813753d

A new Highlight keyword that changes the background and border of elements.

I do not take credit for the original code.

Comments are welcome.

**Comment by aaltat** [comment]
Are still interested to making this or can we close the issue?

**Comment by aaltat** [comment]
Closing due inactivity.
