### ISSUE TITLE
Select From List RegExp

### ISSUE THREAD

**Issue by roebuck69** [robotframework/SeleniumLibrary#54]
The app I'm currently testing contains a number of select controls that contain dynamic values. As the 'select from list' keyword does not allow for regular expressions, I need a new library keyword to allow selection bases on a regexp pattern. I've had a quick stab at this myself, and added the following code to my _selectelement.py. However, I don't know Python and I'm sure someone who does could do a much more elegant job. 

import re

def select_from_list_regexp(self, locator, regexp):

```
    select, options = self._get_select_list_options(locator)
    option_labels = self._get_labels_for_options(options)

    i = -1
    option_index = None
    found = False
    for label in option_labels:
        i+=1
        if re.search(regexp, label):
            option_index = i
            self._info("Match for regexp '%s': label='%s'; index=%s" % (regexp, label, i))
            found = True
            break

    if not found:
           self._info("Failed to find a match for regular expression '%s' in list %s." % (regexp, locator))

    self._select_option_from_single_select_list(select, options, option_index) 
```

This code seems to work ok, but it doesn't allow for multiple items or for the selection of the nth match of an expression. Perhaps this could be implemented in the next release of the library?

Cheers,

Rob

**Comment by hbmartin** [comment]
Look at the latest commit in my branch and let me know what you think

**Comment by ombre42** [comment]
I do not think that this would be needed enough to justify creating a new keyword for it.
If this keyword is worth than doing, than why not:
Option List Should Have Option Matching Regexp
Title Should Match Regexp
Element Text Should Match Regexp
Location Should Match Regexp
Select Window Matching Regexp
etc....
This problem should be solved by combining existing keywords in this and other libraries and/or perhaps using some glue code in Python.
@emanlove Please weigh in here
@roebuck69 I do not mean to sound unsympathetic here, but looking to stay on track as resources are limited and more is not always better

**Comment by pekkaklarck** [comment]
FWIW, I totally agree with @ombre42. Adding regexp versions of all Should keywords is too much work and would add would explode the number of kws. Adding only some regexp kws would be inconsistent.

Has anyone tested is this easy to implement as a user keyword? BuiltIn and String library kws ought to make it pretty easy.

**Comment by roebuck69** [comment]
No worries.

**Comment by zmlpjuran** [comment]
Moreover, you can specify element locators more precisely with regexp (matches()). see http://stackoverflow.com/questions/1398705/how-to-use-regex-in-selenium-locators .

**Comment by uvelayut** [comment]
Do we have a fix for this now ? How do I select a value from list via passing a regular expression (to select single or multiple items)

**Comment by aaltat** [comment]
It's not fixed. There is a limitation from the Selenium side and Selenium does not support regex for list method.
