### ISSUE TITLE
Remove README

### ISSUE THREAD

**Issue by just-be-dev** [robotframework/SeleniumLibrary#540]
The bare readme was added in commit e241153. We should see if it's actually needed still and remove it if it's not.

**Comment by aaltat** [comment]
For me it looks that it would best just to delete the README file and use the README.rst

**Comment by just-be-dev** [comment]
Make sure to read the message in the linked commit before doing so.

**Comment by aaltat** [comment]
Ah, darn. It might be dependency to setuptools, need to be tested before can be deleted.

**Comment by pekkaklarck** [comment]
FWIW, Robot Framework itself only has `README.rst`. It's included into the distribution in `MANIFEST.in`.

**Comment by aaltat** [comment]
Done in e3b4fd091433b9c4635a9665dc2ad3b435a56fb7
