### ISSUE TITLE
Get Cookie Value not working on Windows, but works on Linux 

### ISSUE THREAD

**Issue by maratkalibek** [robotframework/SeleniumLibrary#541]
Windows - Windows 7, FF 42.0, RobotFramework - 2.8.7
Linux - Ubuntu 14.04, FF 42.0, RobotFramework - 2.8.6 

When running this code in Linux, it works fine. Reading cookie value is ok. But it is problem reading cookie on Windows.

**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
Cookie
    Open Browser    http://google.com
    Sleep    10
    ${cookies}    Get Cookies
    ${cookie}    Get Cookie Value    NID
    Close Browser

**Comment by HelioGuilherme66** [comment]
It worked fine in Windows 7 with:
Robot Framework version 3.0.dev20151119
python version 2.7.10
Firefox 38.4.0 ESR
Example:

```
${cookie} =
67=NBLIcdh9REvQhMAA8Yv0fTaYKpr5PaO4Xsk5xeoM4gq3iWTiMflabINtuwW4O7-6pHIKLh8UffTsaI0VjeHHcIT3TZ6udBD_ofUZ5qWVqcbKV_O3meO96XV1VsX_6OyFKZMo9WDD(...)
```

Also worked with:
Robot Framework version 2.8.7

```
${cookie} =
67=LaMethMWpkxIIoBW7VE4bt33jAfQweKUKqpdCuQNn-KHvShaQOzX4aolAlEiiim3fh3K0c3el8ss3x5LAVX1zMM54hJFK_2mzPvtx2iiYQlHiSECX1itvMHP9(...)
```

In my test environment I had to pass to `Open Browser`, the browser=ff
and
ff_profile_dir=C:${/}Users${/}Username${/}AppData${/}Roaming${/}Mozilla${/}Firefox${/}Profiles${/}1sgzovb5.default

**Comment by aaltat** [comment]
The problem could be that the FF, by default profile in Selenium2Library don't allow reading cookies. Or this could be FF version specific issue.

Could you try with different FF version and modifying the profile, like in issue #177.

**Comment by maratkalibek** [comment]
Thank you for replies!
solved by applying custom firefox preferences as suggested in #177
