### ISSUE TITLE
browser proxy not taken in Selenium2library

### ISSUE THREAD

**Issue by peacechan** [robotframework/SeleniumLibrary#544]
I have web proxy setup in Firefox but when I try to run my test from ride.py (using robot framework with Selenium2lib) test runs successfully but very slow and when I check the proxy settings on that browser (run by the selenium), there is no proxy on it. 
When I try to open the same test in non proxy setup environment the test is quite fast.
The test code has very simple code to login to the browser:
**\* Settings ***
Library           Selenium2Library

**\* Variables ***
${Username}       peacechan@xxx.com
${Password}       145dXdk1d
${Browser}        Firefox
${SiteUrl}        https://github-xxx.com
${DashboardTitle}    GitHub
${Delay}          5s

**\* Test Cases ***
LoginTest
    Open Browser to the Login Page
    Enter User Name
    Enter Password
    Click Login
    sleep    ${Delay}
    Assert Dashboard Title

**\* Keywords ***
Open Browser to the Login Page
    open browser    ${SiteUrl}    ${Browser}
    Maximize Browser Window

Enter User Name
    Input Text    login_field    ${Username}

Enter Password
    Input Text    password    ${Password}

Click Login
    Click button    commit

Assert Dashboard Title
    Title Should be    ${DashboardTitle}

Please help me if I need to make any changes anywhere. @divfor

**Comment by aaltat** [comment]
The Selenium2Library don't use your Firefox profile to run test. Instead it uses a default profile, from [library source](https://github.com/robotframework/Selenium2Library/tree/master/src/Selenium2Library/resources/firefoxprofile). But you can change the default profile to be anything you want, see the [Open Browser](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Open%20Browser) keyword ff_profile_dir argument.

**Comment by peacechan** [comment]
I tried by creating profile and added the code as below but I got the following error:
LoginTest                                                                                                                                                       | FAIL |
ValueError: Firefox ff_profile_dir=C:UserspahariAppDataRoamingMozillaFirefoxProfilesff_profile is not a supported browser.

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open

**\* Settings ***
Library           Selenium2Library

**\* Variables ***
${Username}       peacechan@xxx.com
${Password}       12dr9Bk3#
${Browser}        Firefox
${SiteUrl}        https://github-xxx.com
${DashboardTitle}    GitHub
${Delay}          0s
${FF_PROFILE}     C:\Users\pahari\AppData\Roaming\Mozilla\Firefox\Profiles\ff_profile

**\* Test Cases ***
LoginTest
    Open Browser to the Login Page
    Enter User Name
    Enter Password
    Click Login
    sleep    ${Delay}
    Assert Dashboard Title
    Click Next

**\* Keywords ***
Open Browser to the Login Page
    open browser    ${SiteUrl}    ${Browser} ff_profile_dir=${FF_PROFILE}
    Maximize Browser Window

Enter User Name
    Input Text    login_field    ${Username}

Enter Password
    Input Text    password    ${Password}

Click Login
    Click button    commit

Assert Dashboard Title
    Title Should be    ${DashboardTitle}

**Comment by ombre42** [comment]
You need to have at least two spaces between arguments. Add a space after ${Browser}.

**Comment by aaltat** [comment]
Ugh

\ character is a escape character in Robot Framework. To write literal \,
write \.

-Tatu
Send from my mobile

**Comment by peacechan** [comment]
@aaltat Thank you so much! The problem was with \ character. 
It worked with double \: 
${FF_PROFILE}     C:\Users\pahari\AppData\Roaming\Mozilla\Firefox\Profiles\ff_profile

@ombre42 , I do have two spaces everywhere, spaces are not shown after copying the code.

**Comment by aaltat** [comment]
Because it seems that issue was solved, I am closing the issue.
