### ISSUE TITLE
Misleading error when element not found in text field content assertions

### ISSUE THREAD

**Issue by ombre42** [robotframework/SeleniumLibrary#547]
If an element is not found (or filtered out), `Textfield Should Contain` and `Textfield Value Should Be` fail with misleading errors.
`Textfield Value Should Be` fails with an error similar to:
Value of text field 'name=email' should have been 'selenium@xxx.yyy' but was 'None'
`Textfield Should Contain` fails with an error similar to:
TypeError: argument of type 'NoneType' is not iterable

These errors are misleading. It would be better if the failure was similar to other keywords, like:
ValueError: Element locator 'name=email' did not match any elements.

This is being entered as a result of this: http://stackoverflow.com/questions/34169390/how-to-find-value-of-email-field-using-selenium2library

**Comment by ombre42** [comment]
I started work on fixing this. I noticed that `Get Value` does not fail if no element is found, yet `Get Element Attribute` and `Get Text` do fail. I want to change that. Passing and returning None does not seem right, but there is always a risk in a change like that. Thoughts?

**Comment by pekkaklarck** [comment]
Sounds good to me. Must be done in a major release and mentioned in release notes, thoigh. With RF itself we use `bwic` label with issues introducing backwards incompatible changes to make sure we remember to add them to the notes.

**Comment by ombre42** [comment]
Thanks for the input. I will create a separate issue for it then.

**Comment by aaltat** [comment]
I did read the code and different error is raised if the element is not found. I am closing this issue, because it's not anymore correct.
