### ISSUE TITLE
Set Window Position documentation incorrect

### ISSUE THREAD

**Issue by GLMeece** [robotframework/SeleniumLibrary#548]
The entry for the **Set Window Position** documentation is incorrect. It looks like it is copypasta from **Set Window Size**. [Here is the reference](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Set%20Window%20Position).

Currently:

```
Set Window Position  x, y  Sets the position x and y of the current window to the specified values.
                           Example:
                           | Set Window Size | ${1000} | ${0}                |
                           | ${x}            | ${y}=   | Get Window Position |
                           | Should Be Equal | ${x}    | ${1000}             |
                           | Should Be Equal | ${y}    | ${0}                |
```

Should be:

```
Set Window Position  x, y  Sets the position x and y of the current window (relative to the left and top of the screen) to the specified values.
                           Example:
                           | Set Window Position | ${8}    | ${10}               |
                           | ${x}                | ${y}=   | Get Window Position |
                           | Should Be Equal     | ${x}    | ${8}                |
                           | Should Be Equal     | ${y}    | ${10}               |
```

**Comment by aaltat** [comment]
Your version of the documentation is better, would you like to create pull request to fix it?

**Comment by GLMeece** [comment]
Hey, @aaltat - I wasn't sure where the actual content of the documentation lived. If you can point me to the part of the repo, I will create a branch and make the changes. Then I'll submit a pull request.

Thanks!

**Comment by ombre42** [comment]
`Get Window Position` should also have a clause about relativity added if its appropriate for `Set Window Position`.
`Set Window Position` documentation is here: https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_browsermanagement.py#L272

**Comment by aaltat** [comment]
I did post a comment in to the commit.

**Comment by aaltat** [comment]
Was this already fixed?

**Comment by GLMeece** [comment]
@aaltat - looks like [it was merged with this pull request](https://github.com/robotframework/Selenium2Library/commit/ef659fe8ab29faa5ba37dcbfff2d59c185abb956).
