### ISSUE TITLE
Create a Indows installer including all dependancies

### ISSUE THREAD

**Issue by GerhardHeil** [robotframework/SeleniumLibrary#55]
Selenium2Library is installed (on Windows) using pip or easy_install. But these tools do not work on computers behind a proxy. Installing manually falls from one missing component into the next missing component.

Please provide a Windows installer for Selenium2Library that includes installing all dependancies. I would need it for Windows XP and Windows 7. 

Thanks and best regards
Gerhard

**Comment by emanlove** [comment]
On 05/21/2012 05:37 AM, GerhardHeil wrote:

> Selenium2Library is installed (on Windows) using pip or easy_install. But these tools do not work on computers behind a proxy. Installing manually falls from one missing component into the next missing component.
> 
> Please provide a Windows installer for Selenium2Library that includes installing all dependancies. I would need it for Windows XP and Windows 7.
> 
> Thanks and best regards
> Gerhard
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rtomac/robotframework-selenium2library/issues/55

We should possibly make two installers; one with just selenium2library 
and one with everything you need to get started (what we in the Plone 
community call a unified installer that contains the core "product" as 
well as dependencies).  Any thoughts?

Ed

**Comment by GerhardHeil** [comment]
Hello Ed,

one or two installers, that is ok. I also would accept a sequence of installers, if
you would provide a separate installer for each dependancy. That would be a bit more
laborious, but if you provide the (working!) installers, together with a list of
required installers (and an install description if necessary) on the S2L GitHub
page, that would be manageable.

In the current state I got errors in install execution, I don´t know how to correct
them, I don´t know which and how many dependancies will yet be missing, once the
current error would be solved. I am working on this topic since more than one week,
and it is not going to be finished.

Best regards
Gerhard

## 

Optimized Networks GmbH
Increasing Network Profitability
Ebenweg 7, 83122 Samerberg, Germany

## Gerhard.Heil@optimized-networks.net

Legal information: Optimized Networks GmbH
HRB 16526 Amtsgericht Traunstein
Sitz der Gesellschaft: Grainbach
Geschäftsführer: Dr. Toni Göller

**Comment by emanlove** [comment]
Gerhard,

The dependencies include

'decorator >= 3.3.2',
'selenium >= 2.8.1',
'robotframework >= 2.7.1',
'docutils >= 0.7'

To install the dependencies you will need easy_install. You can install easy_install by downloading http://peak.telecommunity.com/dist/ez_setup.py and then running it. Then at the prompt type the following to install the dependencies

c:\easy_install selenium
c:\easy_install decorator

We have a [bug ticket](https://github.com/rtomac/robotframework-selenium2library/issues/40) to better explain the Windows installation process. Sorry about this issue and thank you for your feedback.

Ed

**Comment by GerhardHeil** [comment]
```
<rtomac/robotframework-selenium2library/issues/55/5863362@github.com>
```

In-Reply-To: 
     <rtomac/robotframework-selenium2library/issues/55/5863362@github.com>
X-Greylist: Sender IP whitelisted, not delayed by milter-greylist-4.0.1 (mail.mincom.de [192.168.77.210]); Wed, 23 May 2012 10:51:11 +0200 (CEST)

Hello,

now the module webdriver is not found. It has been available once, maybe I find out
myself what is missing now for webdriver. Last week I had installed several
dependancies (in long discussion with Jeremy Johnson), and mostly easy_install did
not work, as my PC is behind a proxy. The missing component in the last step of that
sequence (after installing selenium, decorator and docutls) was simplejson. I am not
sure from where to download or how to install it. I found a simplejson.2.0.7.tar.gz,
including a setup.py; when I call the setup, it requires some more parameters.

Meanwhile I have tried out downloading and installing so many tools, got errors and
saw that I had installed a wrong one, that meanwhile some of my problems are caused
by installing the wrong tool. Can you now give me a complete description from
scratch for a Windows XP machine, and another for a Windows 7 machine? What
components are to be removed? What are to be installed? And what steps are to be
executed? For some of the dependanies Google finds several alternatives with the
same name, so I have to guess what to take and to try. If I have to handle the
downloads and setups myself, at least a description, that says from where to
download which file and what to call then, would be rather helpful.

I assume that Robot Framework is used in companies rather than at private PCs, and
companies usually have proxies. Therefore I cannot believe that I am the only one
running into problems with easy_install.

Do you want to drive this discussion with every new user who wants to install S2L on
a Windows PC within a company (behind a proxy)? I am in discussion about this
project with Jeremy since 10th of May and I do not see how long we will need to
finish. I hoped I would get a complete installer that does the work.

Maybe I have to wait for that for some weeks; that would be ok, as I can use old
SeleniumLibrary and switch to S2L once it is installed. That would be much better
than this search and install marathon.

Best regards
Gerhard

## 

Optimized Networks GmbH
Increasing Network Profitability
Ebenweg 7, 83122 Samerberg, Germany

## Gerhard.Heil@optimized-networks.net

Legal information: Optimized Networks GmbH
HRB 16526 Amtsgericht Traunstein
Sitz der Gesellschaft: Grainbach
Geschäftsführer: Dr. Toni Göller

**Comment by GerhardHeil** [comment]
Hi Gerhard,

About easy_install (and pip) and proxy.

In windows things usually work if system proxy settings are correct.
At least pip (which uses urllib2) will sniff the proxy settings correctly.

You can also manually set "set http_proxy=[i think you also know this  
in our case]"

some of the links might be https so you should also set:

set https_proxy=[i think you also know this in our case]

In linux:

export http_proxy=[i think you also know this in our case]
export https_proxy=[i think you also know this in our case]

or as a super user:
sudo env http_proxy [i think you also know this in our case] pip install ..

Kind Regards,
Mikkko Korpela

Quoting "ext Gerhard Heil" gerhard.heil@optimized-networks.net:

**Comment by GerhardHeil** [comment]
2012/5/23 ext Mikko Korpela mikko.korpela@reaktor.fi:

> About easy_install (and pip) and proxy.
> 
> In windows things usually work if system proxy settings are correct.
> At least pip (which uses urllib2) will sniff the proxy settings correctly.

I think easy_install doesn't read system proxy settings. I would
otherwise recommend pip, but at the moment installing Se2Lib with it
does not work.

> You can also manually set "set http_proxy=[i think you also know this in our
> case]"
> 
> some of the links might be https so you should also set:
> 
> set https_proxy=[i think you also know this in our case]

Yes, after setting http_proxy and https_proxy environment variables,
easy_install should work just fine.

Cheers,

##     .peke

Agile Tester/Developer/Consultant :: http://eliga.fi
Lead Developer of Robot Framework :: http://robotframework.org

**Comment by tenwit** [comment]
Is this issue still in contention for resolution?  Everyone where I work would vote for it, if there was a vote button :)  We need a robust way to get Selenium2Library working quickly for everyone, or else management won't allow us to drop SeleniumLibrary.

**Comment by GerhardHeil** [comment]
Yes, I still vote for it. I will have to install this tool on Windowss testbeds which do not have internet access. If there is a Windows installer exe, I can download it from my workstation, transfer it to the testbed and install there locally.

Best regards
Gerhard

**Comment by HelioGuilherme66** [comment]
This all-in-one Windows installation package is very much needed for offline installations.

I did not find information on this problem in the main project page. (only today I found that the dependencies were not installed with the current installer).

Thanks,
Hélio

**Comment by WillDev10** [comment]
Fyi, the company I work for just decided not to use RobotFramework because of this issue. Everyone loved the RIDE IDE, but when there was no real install file (that worked) they started to lose enthusiasm. When the only way to actually install it was via the command line, they lost a lot more enthusiasm. I was able to get it to install on win7 with pip, but on winxp pip wouldn't work at all behind it couldn't get past the corporate proxy (despite me putting in the proxy config, which worked for some things but not others).

When the only way to get it installed was to take their laptop home and do it over their home network, something about it being a "good tool for hackers, but not for testers" was mentioned.

Is it really to much to have a simple windows installer that doesn't require using the command line to install, and that works even through a corporate proxy?

**Comment by just-be-dev** [comment]
This issue hasn't garnered any attention in a while, but I'd like to address this issue soon. This is more of a robotframework specific task though, so I'm going to close this and open an issue on the main repository.

**Comment by pekkaklarck** [comment]
How is this Robot Framework specific? Are you planning to create an installer that also contains Robot itself? I would be fine with that, but such installer should anyway be a separate project if it bundles various other projects.

Personally I see the need for separate Windows installers pretty small in general nowadays when Python 2.7.9 contains pip bundled in.

**Comment by just-be-dev** [comment]
Yeah, that's more or less what I meant. A standalone installer with a few of the commonly used RF packages bundled in for ease of use. The primary use for this is installing in locations without an external network connection (like a lot of corporate testing environments).

**Comment by pekkaklarck** [comment]
OK. It would be useful, but there are several non-trivial problems:
- How to select what are the most commonly used libs and tools.
- How to handle binary dependencies (pycrypto w/ SSHLibrary, browser drivers with Se2Lib, etc.)
- Installer needs to be updated every time new version of any package or package dependency is released.
- All users may not want to have latest versions of all packages.
- 32bit vs 64bit Windows.

Also, most of my clients actually have Linux running on their testing environments that aren't connected to the Internet. It would thus be even more useful to have a platform independent installer. If you are fine with using pip as the actual installer, you could get quite far by collecting all needed source distributions together and using pip to install them locally. Not sure do you know, but `pip install robotframework.tar.gz` works just fine, and with requirement files it ought to be easy to install a bunch of packages in one go.
