### ISSUE TITLE
Allow Open Browser keyword to pass capabilities also for local browsers

### ISSUE THREAD

**Issue by drobota** [robotframework/SeleniumLibrary#550]
Sometimes it could be useful to allow capabilities be passed also to local browsers. The current implementation of the `Open Browser` only passes the capabilities  to the Selenium side only when `remote_url` argument is used.

**Comment by ombre42** [comment]
I do not think there is a real reason other than no one has submitted a fix for it and there is a workaround.
@aaltat identified a workaround in #139. See also #342.
Here is the historical reason:
The ability to pass in capabilities to the `__init__` of local webdrivers was not originally part of Selenium 2. For example, IE did not [get this feature](https://github.com/SeleniumHQ/selenium/commit/4d121811a75a90d859f6c3a34fee73ff586958c7) until Mar 4, 2013.

**Comment by ombre42** [comment]
Considering the frequency of users being confused by this quirk and posting to SO or the user group, I think this should be fixed.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by drobota** [comment]
@aaltat  I provided a pr I would like to be merged, however issue can be closed.

**Comment by aaltat** [comment]
Is it #552? We like to keep the issues open until the PR is merged to the master. This helps us to track things better. Let's keep this issue open and hopefully we can find time to review the pull request.

**Comment by drobota** [comment]
Yes it is #552

**Comment by aaltat** [comment]
Ok, thanks. We will try to find time to look at the PR.
