### ISSUE TITLE
Running Robot Scripts using Jenkins

### ISSUE THREAD

**Issue by ilamezhil** [robotframework/SeleniumLibrary#554]
Getting following error when try to run simple robot script to open browser. I can run the script in slave machine with out any errors.
# F:\JENKINS-SLAVE\workspace\XDQ0\XDQ0_DFR_Automation>C:\Python27\Scripts\pybot --variable browserName:"internet explorer" --name Functional F:\JENKINS-SLAVE\workspace\XDQ0\XDQ0_DFR_Automation\Tescases\Jenkins.txt  
# Functional                                                                    

Jenkins Config Test :: Validate Jenkins Config                        [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
## WebDriverException: Message: Failed to navigate to http://www.google.com. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed.

Functional                                                            | FAIL |
1 critical test, 0 passed, 1 failed
#1 test total, 0 passed, 1 failed

Output:  F:\JENKINS-SLAVE\workspace\XDQ0\XDQ0_DFR_Automation\output.xml
Log:     F:\JENKINS-SLAVE\workspace\XDQ0\XDQ0_DFR_Automation\log.html
Report:  F:\JENKINS-SLAVE\workspace\XDQ0\XDQ0_DFR_Automation\report.html
Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information
Build step 'Execute Windows batch command' marked build as failure
Sending e-mails to: ezhilgnanam.ilanthiraiyan@rbccm.com
Warning: this build has no associated authentication, so build permissions may be lacking, and downstream projects which cannot even be seen by an anonymous user will be silently skipped
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

Please advice.

**Comment by ombre42** [comment]
How are you connecting the slave to master? In any recent version of Windows, Selenium will not work if the slave agent is running as a Windows service. The slaves I setup auto-login to Windows and launch the slave agent from a shortcut in the startup folder using Java web start.
See [this post](http://stackoverflow.com/questions/19441324/how-to-run-gui-tests-on-a-jenkins-windows-slave-without-remote-desktop-connectio)

**Comment by aaltat** [comment]
Because this seems to be a problem in how the library is used and not in library it self, I was planning to close the issue. But before issue is closed, do you have an update that would provide evidence that this is an issue in the Selenium2Library and the issue should remain open?

**Comment by aaltat** [comment]
Closing because this is not Selenium2Library issue
