### ISSUE TITLE
[Choose file] Not working for uploading with hidden input=file.

### ISSUE THREAD

**Issue by guit2** [robotframework/SeleniumLibrary#560]
After I used choose file keyword to upload jpg file, I expect thumbnail with this image should be displayed. 
Selenium nor python throws no errors, so I don't really know what is the problem.
Tested od chrome  47.0.2526.106 m.

**Comment by aaltat** [comment]
The underlying selenium library doesn't not allow interaction with hidden elements. Selenium tries to mimic what the real user can do and real users don't have a way to interact with hidden elements. But you are correct that there should be an error, which makes me believe that your selector is not unique and your event is fired for some other element. Could you double check your code, example by using Firebug and Firepath.

If you think your part is correct, would it be possible to demonstrate the problem with example which we can use and debug.

**Comment by guit2** [comment]
Really thanks for your suggestion with constructed improperly selector (not
unique). Now everything works perfectly.

2015-12-31 12:40 GMT+01:00 Tatu Aalto notifications@github.com:

> The underlying selenium library doesn't not allow interaction with hidden
> elements. Selenium tries to mimic what the real user can do and real users
> don't have a way to interact with hidden elements. But you are correct that
> there should be an error, which makes me believe that your selector is not
> unique and your event is fired for some other element. Could you double
> check your code, example by using Firebug and Firepath.
> 
> If you think your part is correct, would it be possible to demonstrate the
> problem with example which we can use and debug.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robotframework/Selenium2Library/issues/560#issuecomment-168179938
> .

## 

Zbyszek
One Second Photography
1sphoto.com
http://www.facebook.com/onesecondphoto

**Comment by aaltat** [comment]
Happy to help.

I am assuming that issue is fixed and therefore closing the issue. If that is not the case, feel free to open the issue or submitting a new one.
