### ISSUE TITLE
Can't add Selenium2Libray in Ride

### ISSUE THREAD

**Issue by ggoubb** [robotframework/SeleniumLibrary#565]
I have installed Selenium2 library with Robot framework and Ride and have configured corresponding Path variables.
When import Selenium2Libray, the library name was red, 
Got below log messages from Ride log. Could anybody let me what's wrong? Thank you!
20160107 10:41:15.430 [INFO]: Found Robot Framework version 2.8.5 from 'C:\Python27\lib\site-packages\robot'.

20160107 10:41:15.431 [INFO]: Started RIDE 1.5 using python version 2.7.11 with wx version 2.8.12.1 in win32.

20160107 10:41:41.542 [WARN]: Importing test library "Selenium2Libray" failed

Traceback (most recent call last):
Importing test library 'Selenium2Libray' failed: ImportError: No module named Selenium2Libray
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 143, in _import
    return __import__(name, fromlist=fromlist)
PYTHONPATH:
  C:\Python27\lib\site-packages\robot\libraries
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode
  C:\Python27\Scripts
  C:\Python27\lib\site-packages\decorator-4.0.6-py2.7.egg
  C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg
  C:\Python27\lib\site-packages\robotframework_selenium2library-1.7.4-py2.7.egg
  C:\windows\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages\robotide\spec
  .
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\Python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = robotapi.TestLibrary(path, args)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 46, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 67, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robotide\lib\robot\utils\importer.py", line 103, in _raise_import_failed
    raise DataError('\n'.join(msg))

**Comment by aaltat** [comment]
1) How did you install Selenium2Library? Was there any errors during the installation process?
2) Does `C:\Python27\Lib\site-packages\Selenium2Library` folder exist?
3) If above folder exist, could you run a following command from a command line and send the output:
`python -c "import Selenium2Library`
4) If the above command succeeds without errors, could you also run the following commands from the command line and send the output:
- `python`
- `x = Selenium2Library.Selenium2Library()`
- `x.open_browser("https://github.com/robotframework/Selenium2Library/issues/565")`

**Comment by boakley** [comment]
You misspelled the library name. Look closely at this part of the
stacktrace:

```
Importing test library 'Selenium2Libray' failed: ImportError: No module
```

named Selenium2Libray

Notice that it says "Selenium2Libray", not "Selenium2LIbrary"

**Comment by ggoubb** [comment]
1)  I download the .exe file and run it.
2) The Selenium2Library exists at C:\Python27\Lib\site-packages\Selenium2Library
3) Send comman python -c "import Selenium2Library", didn't get any output
4) Run command
-python
-x = Selenium2Library.Selenium2Library()

C:\Python27\Lib\site-packages\Selenium2Library>python -c "import Selenium2Librar
y"

C:\Python27\Lib\site-packages\Selenium2Library>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

> > > x=Selenium2Library.Selenium2Library()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > NameError: name 'Selenium2Library' is not defined
> > > 
> > > Thank you!

**Comment by aaltat** [comment]
Ah @boakley is correct, you did misspelled the library name. Try with the correct name.

**Comment by ggoubb** [comment]
@aaltat @boakley Thank so much for your help! Can't believe such a stupid mistake cost me whole day!

**Comment by aaltat** [comment]
It is quite familiar feeling, so do not worry. But closed issue because it is error in spelling and not in library.

**Comment by hariprasadv-eng** [comment]
facing the same kind of errors while installing json library

**Comment by aaltat** [comment]
It would be best to check the spelling and remember that in library imports case does matter.

If that doesn't not help, then please report the issue to the Json library issue tracker. This is Selenium2Library repository and we don't support Json library.

**Comment by hariprasadv-eng** [comment]
Thanks @aaltat

**Comment by anilrawat1984** [comment]
Hi.
I am not able to import seleniumlibrary in ride. 

I have installed following:
python=2.7
pypubsub==3.3.0
robotframework==3.1.1
robotframework-ride==1.7.3
robotframework-seleniumlibrary==3.3.1
selenium==4.0.0a1
urllib3==1.25.3

Now tell me what name i should enter in ride library window. Till now i have used: "SeleniumLibrary" & ""robotframework-seleniumlibrar" and "selenium"

Nothing is working.

I have installed the selenium from its packages using python setup.py install command. I was not able to install it through pip because of company imposed instructions. Please help me here.

**Comment by aaltat** [comment]
SelenuimLibrary 3.3 has a bug which prevents using Selenium 4.0.0 alpha version (or any Selenium version, which has non numerical values in the version string) and therefore the import fails. There is at least two ways to solve the problem: 1) Downgrade Selenium to 3.X 2) Install SeleniumLibrary from the GitHub repository, the bug has been already fixed but not yet released.

**Comment by anilrawat1984** [comment]
Hi, I have downloaded the selenium from github only. https://github.com/robotframework/SeleniumLibrary/

Can u suggest any link from which i can download the selenium and install it manually. I cannt use pip to install because of company restrictions. 
Can i download selenium2library and rename its folder to SeleniumLibrary. I think it should work.

**Comment by anilrawat1984** [comment]
Installing the selenium2library worked. Also i didnt renamed it to SeleniumLibrary. By default it was named like that in python path and was successfully imported in ride.

**Comment by aaltat** [comment]
Ugh

Downloads are available from pypi
https://pypi.org/project/selenium/3.141.0/#files

Please note that Selenium2Library (Python) is deprecated and is not anymore
developed. All new development, for Python, will happen in SeleniumLibrary.

-Tatu
Send from my mobile

**Comment by anilrawat1984** [comment]
Hi,

WHen i am installing selenium library using the link provided by you, I am getting selenium-3.141.0-py2.7.egg folder on python path. Why i am not getting SeleniumLibrary name folder?

Can i rename it to SeleniumLibrary so that it can be imported on ride

**Comment by aaltat** [comment]
This is turning to a support issue and how to get support please see the [README](https://github.com/robotframework/SeleniumLibrary#support). You will most likely get better and faster answer.

**Comment by karelf** [comment]
Hi all.
I have installed Selenium2 library with Robot framework and Ride and have configured corresponding Path variables.
When import Selenium2Libray, the library name was red,
and send command:

PS C:\Python27\lib\site-packages\Selenium2Library> python -c "import Selenium2Library"
PS C:\Python27\lib\site-packages\Selenium2Library> python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>  x = Selenium2Library.Selenium2Library()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Selenium2Library' is not defined

I can't find the mistake, please advise

**Comment by humbienri** [comment]
Hello @karelf,

Is there a reason you are posting to a Closed ticket? You might be better off creating a new ticket. However, must you use Selenium2Library and must it be Pythong 2.7? I'd advise against using both of those. They are old!
