### ISSUE TITLE
add keyword "Get Browser Version"

### ISSUE THREAD

**Issue by jerry57** [robotframework/SeleniumLibrary#569]
Would be helpful to be able to retrieve the browser version to record when running testcases.  Knowing the browser version is very important to submitting "bugs/issues" normally.

This page had examples of how that might be accomplished:
http://stackoverflow.com/questions/12556163/get-browser-version-using-selenium-webdriver

Usage of the keyword could be something like:
${output}    Get Browser Version
Log    ${output}

**Comment by HelioGuilherme66** [comment]
We have PR #482 that would solve your question. It was the need to know the Browser Version that drove me to create the PR.

**Comment by jerry57** [comment]
Excellent, I am looking forward to it being merged and released soon.  THANKS!

**Comment by aaltat** [comment]
Getting all the capabilities is better idea than having separate keywords to return only one value. Closing due #980.
