### ISSUE TITLE
PIP installation issue on Windows

### ISSUE THREAD

**Issue by Seanogie** [robotframework/SeleniumLibrary#57]
Using windows, Python 2.7 and PIP, I have tried to install robotframework-selenium2library.  However the pop up window when install PIP is too quick to read and it does not seem to install correctly.

Under the PIP/build folder I see the dependence I have downloaded
'decorator >= 3.3.2',
'selenium >= 2.8.1',
'robotframework >= 2.7.1',
'docutils >= 0.7'

When I run "pip install upgrade robotframework-selenium2library" the screen is too fast to see if it was successful.  However as the folder is not created I assume it was not successful. The same for "selenium2library".

So, how can I keep the window open to see the issue? 

And am I doing something wrong?

**Comment by j1z0** [comment]
I assume u are running pip through the run menu?  Can u open cmd prompt first and then run pip?

**Comment by Seanogie** [comment]
Hi j1z0, no I ran this through the cmd prompt.

**Comment by j1z0** [comment]
So what window are u talking about keeping open?  Pip should just output everything to the command prompt.

**Comment by emanlove** [comment]
@Seanogie If you are still experiencing this problem please reopen the issue and provide an updated status or error message.

**Comment by mcteo** [comment]
I have also experienced this problem, when pip.exe is ran, from a command prompt, it opens a new command prompt, prints it output to this new window, and closes it again.

A workaround is to use the pip-2.7-script.py directly.
