### ISSUE TITLE
Using a @list variable in an Execute Javascript call doesn't work

### ISSUE THREAD

**Issue by dflock** [robotframework/SeleniumLibrary#572]
Using a scalar variable in `Execute Javascript` code works fine, but list variables break. For example this code:

```
@{USERS}              ADMIN                TEST

Execute Javascript    $('#users .multiselect').multiselect('select', '@USERS')
```

produces this error:

```
Executing JavaScript:
$('#users .multiselect').multiselect('select', '[u'ADMIN', u'TEST']')
```

This is because the Python list is getting converted into a string - by python - and it's including the `u` unicode indicators - which means that Javascript doesn't recognise this as a list.

Doing something like this instead works ok:

```
${USERS}    '["ADMIN","TEST"]'

Execute Javascript    $('#users .multiselect').multiselect('select', '$USERS')
```

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.
