### ISSUE TITLE
Having difficulty installing Selenium2Library for use with robotframework

### ISSUE THREAD

**Issue by TonyStarch** [robotframework/SeleniumLibrary#573]
I'm attempting to learn more about robotframework, and the documentation mentioned using Selenium2Library if one wishes to interact with a web browser. So I tried pip installing this to my virtualenv, but it looks like something went wrong:

```
(robotenv)btweed@btweed:[~/virtualenvs/robotenv/PlayArea]>pip install robotframework-selenium2library
Collecting robotframework-selenium2library
  Using cached robotframework-selenium2library-1.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w6/rjdtmsb96ks4nv4xfm2p8v400000gp/T/pip-build-__rwphnc/robotframework-selenium2library/setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "/private/var/folders/w6/rjdtmsb96ks4nv4xfm2p8v400000gp/T/pip-build-__rwphnc/robotframework-selenium2library/src/ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w6/rjdtmsb96ks4nv4xfm2p8v400000gp/T/pip-build-__rwphnc/robotframework-selenium2library
```

I'm using pip 8.0.2 to install this package to a Python 3.4.3 virtualenv for use with Robot Framework 3.0. Is there a different package that I should try installing? Also, is there a standardized way that robotframework users install and work with Selenium2Library?

**Comment by HelioGuilherme66** [comment]
Selenium2Library is not compatible with Python 3 (yet). See PR #564.
If you are willing to try a Beta package, you may install like:

```
pip install -U https://github.com/HelioGuilherme66/robotframework-selenium2library/archive/v1.8.0b1.tar.gz
```

Or download from [Releases](https://github.com/HelioGuilherme66/robotframework-selenium2library/releases/tag/v1.8.0b1)

**Comment by tisto** [comment]
@HelioGuilherme66 thanks for your work! Where would be the right place to report bugs for your release/fork?

**Comment by HelioGuilherme66** [comment]
The right place to report bugs is at [My fork tracker](https://github.com/HelioGuilherme66/robotframework-selenium2library/issues)

But the goal is to have only the official branch merged.

**Comment by Thish25** [comment]
Hi,

I'm new to Python and Robotframework.  I use the python version 3.4.  Is it good idea to use beta or should I download python 2.9? and use the selenium2library?

**Comment by aaltat** [comment]
Selenium2Library is not compatible with Python 3, but we are working on the support. If you want to use the official release then you must use Python 2.7. The next major release should bring support for Python. If you need to Python 3 support now, then best option is to use Selenium2Library fork which provides the support.

**Comment by tisto** [comment]
@Thish25 I'm using @HelioGuilherme66 fork with Python 3 since quite a while and it works well for me.

**Comment by pskpg86** [comment]
@HelioGuilherme66, I have tried to use your fork in python 3.4.3 but am not able to install the selenium2library.  I get following error: 

 Traceback (most recent call last):
      File "c:\python34\lib\site-packages\ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Pankaj\AppData\Local\Temp\pip-2jognamh-build\setup.py", line 8, in <module>
        use_setuptools()
      File "c:\python34\lib\site-packages\ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "c:\python34\lib\site-packages\ez_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "c:\python34\lib\site-packages\ez_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    OSError: Could not build the egg.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Pankaj\AppData\Local\Temp\pip-2jognamh-build\

Will you be able to check this.

**Comment by HelioGuilherme66** [comment]
@pskpg86 
> Will you be able to check this.

**No!** Sorry but this is a issue tracker for main project. This issue is Closed, for my fork you should open an Issue there. Or you can see try to merge some PRs we are making here to get it fixed.
(you don't seem to be using pip to install, try to download the package and install from it with `pip`)
