### ISSUE TITLE
Add function to capture console logs from selenium browser.

### ISSUE THREAD

**Issue by binyata** [robotframework/SeleniumLibrary#574]
I was wondering if you could add this function to your _browsermanagement.py file? This will enable the selenium tests to pull information straight from the developer console. This feature will give a better picture of what is going on with the back end when running these kind of tests within a frame buffer like XVFB.

def printMyLogs(self):
        sampleLogsArray = []
        for entry in self._current_browser().get_log('browser'):
            print entry
            sampleLogsArray.append(entry)

```
    return sampleLogsArray
```

**Comment by shanmusa** [comment]
hi, I am trying to capture console.log using java selenium. can you give me above equivalent code in java?

**Comment by aaltat** [comment]
I don't live in Java world, so.no idea.

**Comment by aaltat** [comment]
This is now implemented in #863

**Comment by pekkaklarck** [comment]
I'll rename the keyword from `Get Log` to `Get Selenium Log`.

**Comment by pekkaklarck** [comment]
I looked the implementation of this keyword a bit more closely and noticed several problems:

1. `Get Log` is a very generic name. The keyword should be renamed to `Get Selenium Log`.

2. Return value, at least when getting `browser` logs, is a list of dictionaries. This kind of format is not at all clear in Robot's logs and it's also inconvenient to use in Robot's data. A better solution would be formatting the log into a string that can be nicely logged in Robot logs, but that would be even harder to use in the data. The best solution would be implementing a custom object that makes it easy to use the data but also has clear string representation. This is something we need to discuss.

3. Return format is not at all documented. This is a huge problem. Nobody can use this keyword!

4. Only one of the documented log types is actually tested. This test is also in `javascript.robot' file which contains totally unrelated tests otherwise. This functionality should probably get its own test suite.

Because there are so many problems, I'm going to remove the current implementation altogether. The functionality itself is useful and I hope we can include it later.

**Comment by accesslubos** [comment]
@pekkaklarck When will this be released please?

**Comment by pekkaklarck** [comment]
I don't know when this will be released. It requires someone who needs it to implement it so that the functionality is easy to use, well documented and adequately tested.

**Comment by aaltat** [comment]
Perhaps we should look at the use cases point of view. For me the most interesting use case is not to get the Selenium logs, but to display the logs when error happens. I don't want to perform any checks on the log, instead I want to read the Selenium logs from the log.html when an error happens in the SeleniumLibrary keyword. Example I would like to do something like this:
```
| My SL Run On Failure Keyword |
| | Get Selenium Log               | all |
| | Maximize Browser             | |
| | Capture Page Screenshot | |
```
And then the `Get Selenium Log` keyword would get all the  possible Selenium logs and log then in some reasonable manner in the log.html file.

I can imagine that someone wants to make assertion based on the received data. But for that we need to agree how that data is formatted and returned to the Robot Framework test data side. Any good ideas?

**Comment by ybian19** [comment]
is there any plan for this issue? I think it's really helpful if we have a keyword for getting the log about console errors when load a page.

**Comment by aaltat** [comment]
Yes it's useful feature. To implement this in better way we would need information about your use case. My use case is that I only want to put the all logs provided by the keyword in to the log.html report in info level. But I just want to log the Selenium logs and I don't want perform any checks against the Selenium logs. Is your use the same or is it different? If it's different, could you describe what your use case actually is?

**Comment by ybian19** [comment]
In my use case, I need check if there any js errors or warnings in browser console when I load the page, and I think another keyword for logging the Selenium logs in log.html is also very helpful

**Comment by aaltat** [comment]
So you want to get the console log content from browser and make checks against the contract. In practice, do you want something like this:
```
| ${log} = | Get Selenium Log | console |
| Should Not Match | error | ${log} |
| Should Not Match | warning | ${log} |
```

**Comment by chevi** [comment]
For me this case is useful too. For example keyword with this code can be run with **Run Keyword If Test Failed** 

```
| ${log} = | Get Selenium Log | console |
| Log | ${log} |
```

When analyze Fail of the test within Log file I can see, were there any errors in console or not

**Comment by pekkaklarck** [comment]
Are all logs returned by Selenium as lists of dictionaries? Do these dictionaries contain information about each logged message like the level and the actual message? Do they always have same information?

Assuming the answer to the above questions is yes, I would propose implementing this as follows:

1. Implement a custom class like `LogMessage` that can be populated based on information in the returned dictionaries. Information should be stored to attributes to make it easily accessible in Robot's data like `${message.level}`.

2. Implement separate class like `SeleniumLog` that store `LogMessage` objects. It should be list-like to allow handling messages as lists. Either it could extend the standard `list` or implement `collections.Sequence` abstract  base class.

3. `LogMessage` should have a custom `__str__` to return the message nicely formatted. `SeleniumLog` should also have a custom `__str__` to return messages joined together. 

4. Very importantly, `SeleniumLog` should have custom `__contains__` and `count` to allow using it with `Should (Not) Contain (X Times)`:

       ${messages} =    Get Selenium Log    type=browser
       Should Not Contain    ${messages}    ERROR      # Validate there are no errors
       Should Contain    ${messages}    Some message   # Validate message exists
       Should Contain    ${messages}    INFO: Message  # Validate message with level exists

5. Consider adding support to getting only messages with certain level:

       ${errors} =    Get Selenium Log    filter=ERROR
       Should Be Empty    ${errors}

6. Should also decided how to handle logging the logs. Alternatives are `Get Selenium Log` always logging messages, it having `loglevel=INFO` or `loglevel=NONE` argument to control should they be logged, and adding separate `Log Selenium Log` keyword that gets and logs messages.

**Comment by aaltat** [comment]
I could not find details about the different logs. I would assume that logs are returned as Json, but each browser driver may return different things. I think the only sure way is to test with different browsers and see what is returned.

**Comment by aaltat** [comment]
I did perform some testing and it looks like the content is list of dictionaries. 

```
from selenium import webdriver


driver = webdriver.Chrome()
driver.get('https://github.com/robotframework/SeleniumLibrary')
driver.execute_script("console.error('test message 1')")
driver.execute_script("console.error('test message 2')")
driver.execute_script("console.error('test message 3')")
log = driver.get_log('browser')
print log
log = driver.get_log('driver')
print log
driver.quit()
```

**Comment by pekkaklarck** [comment]
Tested the above and noticed that the actually logged messages look somewhat strange. Also noticed that this doesn't work at all with Firefox. Supporting this in generic manner requires a bit more thinking. Those just interested to get the logs in the current format could use the following keyword compatible with SL 3.0 RC 1:

```python
from robot.libraries.BuiltIn import BuiltIn


def get_selenium_browser_log():
    selib = BuiltIn().get_library_instance('SeleniumLibrary')
    return selib.driver.get_log('browser')
```

**Comment by rklama1992** [comment]
This is how you can do it in C#, and print the result in Extent Reports if you want. 
public void Test_DetectErrorLoadingWebpage()
        {
            try
            {
                test = extent.CreateTest("Test_DetectErrorLoadingWebpage");
                test.Log(Status.Info, "Tests to detect missing Css/js files required to load the webpage.");
                List<LogEntry> logs = driver.Manage().Logs.GetLog(LogType.Browser).ToList();
                foreach (LogEntry log in logs)
                {
                    while(logs.Count > 0)
                    {
                        String logInfo = log.ToString();//logInfo is used in printing error message in actual report.
                        if (log.Message.Contains("Failed to load resource: the server responded with a status of 404 (Not Found)"))
                        {
                            Assert.Fail();
                        }
                        else
                        {
                            Assert.Pass();
                        }
                    }
                }
            }
            catch (NoSuchElementException e)
            {
                test.Fail(e.StackTrace);
            }
        }

**Comment by rklama1992** [comment]
Good luck

**Comment by lucagiove** [comment]
I did some test with chorme but I'm not getting any logs execpt the one I directly generate from seleinum javascript execution.
Someone have been able to get logs from the real website with selenium python library?

**Comment by aaltat** [comment]
It seems that Selenium has changed and logging must be enabled by desired capabilities. Example for Chrome, this should work: 
```
{'browserName': 'chrome', 'version': '', 'platform': 'ANY', 'loggingPrefs': {'browser': 'ALL'}}
```

**Comment by torybenya** [comment]
You may all already be aware, but I sort of stumbled on this discussion while working on the same issue (independent of the Robot framework). Implementation might be a little different depending on the browser, it seems. Firefox (geckodriver) does not appear to have yet implemented the same interface, though it still seems potentially doable (at least as of FF 65). See: https://github.com/mozilla/geckodriver/issues/284 - hope that helps.

**Comment by aaltat** [comment]
Thanks for the input. I think we are not going to do this until this gets defined in the WebDriver specification and at least two browsers work in similar fashion.

**Comment by aaltat** [comment]
The [SeleniumTestability](https://github.com/rasjani/robotframework-seleniumtestability) plugin has this keyword and it supports more browsers then is supported by the Selenium. Therefore closing this issue. 

If there is a new need, we can consider implementing this feature in SeleniumLibrary too.

**Comment by arsen-t** [comment]
Can I see browser console messages inside robotframework log if I 'Open Browser' or 'Create Webdriver' passing desired capabilities?
