### ISSUE TITLE
Support argument passing to webdrivers

### ISSUE THREAD

**Issue by do3cc** [robotframework/SeleniumLibrary#575]
Hi,

the phantomjs webdriver accepts the argument service_args. It would be nice if there was a way for Selenium2Library to pass this argument on to the webdriver. This would allow one to tell phantomjs to open the remote debugger port (WebDriver(...service_args='--remote-debugger-port=9999')

**Comment by molsky** [comment]
It should be possible with `Create Webdriver` keyword (use that instead of Open Browser).
http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Create%20Webdriver

**Comment by aaltat** [comment]
Is this issue still open or can we close it?

**Comment by do3cc** [comment]
It is a possible solution. What I loose this way, that I can just use

```
open browser
```

and control which browser to use via env variables.

**Comment by aaltat** [comment]
The Open Browser is not intended to handle all the possibilities which can be used to create the driver instance from selenium. It is intended to be a simple and easy way to create the default driver.

Creating the driver is actually quite complex scenario and there is lots of different options for different browsers. Although the Create Webdriver is powerful, it cannot handle all the options, fine example is in #532.

If one has special needs, which is not supported by the Open Browser keyword, then the next option is to go with the Create Webdriver keyword.  If it comes to complex to handle in RF data or need cannot be fulfilled by the Create Webdriver keyword, one can always extend the S2L and create a new keyword to open the browser.

The point is that you have lot of options to choose from, you just need to decide which one is best suited for your needs.

**Comment by do3cc** [comment]
I get your points, thank you for your detailed reasoning.
