### ISSUE TITLE
How to test tab-key pressing

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#577]
I have a dialog with several input fields, and I want to test the correct behavior of pressing the tab-key. Typically, pressing this key moves the focus to the next field where the user can type the next input.

I would like to a) enter  a value in the currently focussed field and b) press the tab-key
in a loop. At the end I would like to verify that the correct values are present in the correct fields.

Before, in SeleniumLibrary version 1, there was a keyword "press key native" which I could use for that purpose. This keyword is gone, and I only have "Press Key" which expects a fieldId as parameter. However, this can hardly be used for these kinds of tests, as I do not know (resp. I do not WANT to know) the fieldId where the dialog is in after pressing the tab-key.

Any ideas what can be done?

**Comment by jjwipf** [comment]
It's possible to use press key to tab and enter the desired inputs. It might work as a temporary work around if no better solution exists.

Use the Press Key keyword with `Value0\tValue1\tValue2\tValue3` `\t` will tab through to next input. This does force the values into a chain however. You can use a for loop to construct the majority of the tab+value structure if you want to do this semi-dynamically based on existing list-like structures.

**Comment by tarand** [comment]
Hi,

thanks for that answer. Well, a workaround. Not nice.

But a deeper analyzis of the existing test cases (which I have to migrate from SeleniumLibrary version 1 to Selenium2Library) shows that the problem is more complicated. It simulates the pressing of the F6-Key (which selects the Address-Bar of the Browser) without knowing which element has the focus. From there it simulate pressing the tab-key several times (which must select the elements of a certain dialog window).

How to do that with Selenium2 ???

Thanks,

Thomas

---

Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023  / (Soft) 8041034
thomas.arand@nokia.commailto:thomas.arand@nokia.com

**Comment by tarand** [comment]
I found a better workaround. You can get the focussed element with
   ${result}= | selLib.execute javascript | return window.document.activeElement.id
You can then use ${result} for the "Press Key" keyword.

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by aaltat** [comment]
Closed because of inactivity
