### ISSUE TITLE
select window doesn't work for model dialog on Selenium2Lib 1.0.0

### ISSUE THREAD

**Issue by qitaos** [robotframework/SeleniumLibrary#58]
for version 0.5.2, it works well. But I updated it to 1.0.0, it doesn't work.

I use the script following:
Wait until keyword succeeds 1min 5sec Select window windowname

**Comment by j1z0** [comment]
@qitaos,

Is it possible you can provide a test that reproduces the problem?

**Comment by adwu73** [comment]
I have tested today. For my newly installed s2l 1.0.1, the issue live in here: https://github.com/adwu73/robotframework-selenium2library/commit/66564fa6d834869de6a6923240f7dcd648553059#src/Selenium2Library/webdrivermonkeypatches.py after I modifed this, I can work with modal dialog again. 

Can some one review this fix and merge this to the trunk? You can find more info about this error in issue 10, tks

**Comment by ombre42** [comment]
Modal dialog boxes are mostly the domain of IE web apps, although FF does support them to some extent. In Selenium2Library 1.1, which has the patch adwu73 mentioned, the window related keywords seem to be working in IE when they did not in 1.0. I think we can close this unless someone is still having problems.

**Comment by emanlove** [comment]
Fixed under Selenium2Library version 1.1
