### ISSUE TITLE
Internet Explorer 11 : i think ignoreProtectedModeSettings is not working when loading a javascript library

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#581]
## Expected Behavior -

Setting ignoreProtectedModeSettings TRUE, , Unable to get browser ( http://stackoverflow.com/questions/12694001/selenium-server-error-unable-to-get-browser ) should not be raised loading a javascript file
## Actual Behavior -

NoSuchWindowException: Message: Unable to get browser is raised
## Steps to reproduce -

**\* test cases ***
test capabilites
       Open Browser    www.google.com  ie
       Execute Javascript  ${CURDIR}/jquery-1.12.0.min.js

you got the exception.

then manually set protected mode for every zones and launch again the test : no exception raised 

so restore the default protected mode and try to set ignoreProtectedModeSettings : no exception should be raised .... 

test capabilites
    ${dc}   Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.INTERNETEXPLORER  sys, selenium.webdriver
    Set To Dictionary       ${dc}       ignoreProtectedModeSettings     ${True}
    Open Browser    www.google.com  ie
    Execute Javascript  ${CURDIR}/jquery-1.12.0.min.js

but exception raised.

**Comment by aaltat** [comment]
Is this still a problem or can we close the issue?

**Comment by aaltat** [comment]
Closing due inactivity
