### ISSUE TITLE
Input Text with specific text and run with Selenium Server will failed

### ISSUE THREAD

**Issue by frank007love** [robotframework/SeleniumLibrary#582]
I narrow down the problem and 
use the Input Text like:
![rf_test_testcases](https://cloud.githubusercontent.com/assets/6027226/13451003/dcc0aa98-e075-11e5-90ed-7ae3bec4e6fd.png)
and the browser will show:
![rf_input_text_with_1_bug](https://cloud.githubusercontent.com/assets/6027226/13451017/f6d55050-e075-11e5-8490-f0c80e288880.png)

The text value is C:\Users\ADMINI~1\AppData\Local\Temp\1\38cd2359-abf5-4e39-8ece-6abf58046aec\upload8851560835147769565file\1.

1:
[1.txt](https://github.com/robotframework/Selenium2Library/files/154137/1.txt)

selenium server console:
[output.txt](https://github.com/robotframework/Selenium2Library/files/154136/output.txt)

Version info:
Robotframework 3.0
Selenium2Library 1.74
selenium 2.52.0

**Comment by aaltat** [comment]
Closing due inactivity. If this is still a problem, please send an update and we can consider should the issue be opened.
