### ISSUE TITLE
mac how to use other browser like chrome,safari and so on

### ISSUE THREAD

**Issue by testj** [robotframework/SeleniumLibrary#589]

**Comment by aaltat** [comment]
Have you looked at [Open Browser](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Open%20Browser) keyword documentation?

**Comment by testj** [comment]
I have read it,but it tell me need to use chrome driver,then i download it,but in this keyword have't any parameter to suport this,i found this keyword code,also can't find support this.

**Comment by aaltat** [comment]
If you did follow the [Getting Started](https://sites.google.com/a/chromium.org/chromedriver/getting-started) instructions for ChromeDriver the only thing you need to configure in the Selenium2Library side is `browser` argument in the Open Browser keyword.

**Comment by testj** [comment]
Now I found `Create Webdriver` this keyword can use `executable_path` this param to specified chrom path,but when I run robot,the ride has no log.Before is my chromedriver is not in the PATH,so it always reminder me can't find it!

**Comment by aaltat** [comment]
I am sorry but I don't understand your problem description. 

1) Could you clarify what you are trying to do, what is your goal?
2) What you have tried? Examples of Robot Framework tests are really useful and what kind of error message you received when you run the examples.

**Comment by aaltat** [comment]
Do you still have a problem or can we close the issue?

**Comment by testj** [comment]
sorry,I fogot it,thank you

**Comment by aaltat** [comment]
No problem
