### ISSUE TITLE
Make "Drag and Drop" work when having a second scroll inside the window?

### ISSUE THREAD

**Issue by idgserpro** [robotframework/SeleniumLibrary#591]
We're using Plone, a CMS system, in version 4.3.x. We have the following situation in our web test:

![selecao_151](https://cloud.githubusercontent.com/assets/8203476/14331068/090855c8-fc1a-11e5-8a5f-e9dfd57dfb9e.png)

As you can see, there's a scroll inside this box, and I want to drag and drop an item that you have to scroll to drag it.

![selecao_152](https://cloud.githubusercontent.com/assets/8203476/14331091/27d12f66-fc1a-11e5-8b94-389457d3a91c.png)

When testing it, using "Drag And Drop" keyword, the scroll even moves  like the second example above, but the item isn't "dragged".

So:
- Is this a bug?
- Is there a different keyword (scroll, something) that I need to use to acomplish the drag and drop when having a second scroll in my page?

**Comment by aaltat** [comment]
There has not been activity for this issue for long time and we are planning to close the old issues if they are not anymore valid ones. If you feel that this is still valid issue, could you send an update. If update is not received in a month, we will assume that this is not anymore an issues and we will close this issue.

**Comment by idgserpro** [comment]
We did a workaround for this issue in this commit https://github.com/plonegovbr/brasil.gov.tiles/commit/0fea8c22e0f57c1f8a2b64433bb6e1fad05970c7, we'll test if it's still valid.

**Comment by idgserpro** [comment]
This is the broken build to show the "Drag and Drop" problem: https://travis-ci.org/plonegovbr/brasil.gov.tiles/jobs/171142485

This is the robots file: https://github.com/plonegovbr/brasil.gov.tiles/blob/d2d404285fba268dd14e30b23ce7618cd672b92e/src/brasil/gov/tiles/tests/test_mediacarousel_tile.robot#L134 the problem happens in the line

``` robots
Drag And Drop  xpath=${my_news_folder_selector}  css=${tile_selector}
```

The "workaround" is to make robots insert a string into "filter items" (as you can see in [the screenshot](https://cloud.githubusercontent.com/assets/8203476/14331091/27d12f66-fc1a-11e5-8b94-389457d3a91c.png)) so the item 'my-news-folder' is outside the scroll, and a `Sleep` to be sure that the Drag And Drop only occurs after the scroll is gone. So, before the "Drag And Drop", we add:

``` robots
Input Text  id=${filter_items}  ${my_news_folder}
Sleep  1s
Drag And Drop  xpath=${my_news_folder_selector}  css=${tile_selector}
```

You can see the file with the workaround here https://github.com/plonegovbr/brasil.gov.tiles/blob/0fea8c22e0f57c1f8a2b64433bb6e1fad05970c7/src/brasil/gov/tiles/tests/test_mediacarousel_tile.robot#L139

Probably you're not into Plone, but to simulate the error you need to do:

``` bash
git clone https://github.com/plonegovbr/brasil.gov.tiles/
git co selenium2library_issue_591
python bootstrap.py
# Expect a long time until it downloads all dependencies
bin/buildout
bin/test -t test_mediacarousel_tile.robot
```

And then you get the error:

``` log
==============================================================================
Test Mediacarousel Tile                                                       
==============================================================================
Test Mediacarousel Tile                                               | FAIL |
Text 'my-nitf-with-image' did not appear in 30 seconds
------------------------------------------------------------------------------
Test Mediacarousel Tile                                               | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/user/Desktop/brasil.gov.tiles/parts/test/test_mediacarousel_tile/Test_Mediacarousel_Tile/output.xml



Failure in test Test Mediacarousel Tile (test_mediacarousel_tile.robot)
Traceback (most recent call last):
  File "/home/user/.buildout/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/user/.buildout/eggs/robotsuite-1.7.0-py2.7.egg/robotsuite/__init__.py", line 461, in runTest
    assert last_status == 'PASS', last_message
AssertionError: Text 'my-nitf-with-image' did not appear in 30 seconds
```

`Text 'my-nitf-with-image' did not appear in 30 seconds` is incorrect: the item _is there_, but "hidden" in a second scroll.

**Comment by aaltat** [comment]
Thank you from the detailed analysis. We will have to take a look and see can it be resolved in the Selenium2Library side or is this a problem in the selenium side.

**Comment by idgserpro** [comment]
The pinned versions are at https://github.com/plonegovbr/brasil.gov.tiles/blob/d2d404285fba268dd14e30b23ce7618cd672b92e/buildout.cfg#L52

Feel free to ask anything about this package since it's in brazilian portuguese.

**Comment by aaltat** [comment]
Seeing the config reminds me few things. Do you always use the same browser (and version) or have you tried to test with multiple different browsers? Have you tried with newer selenium version? Have you tried newer browser driver, example Chrome driver, version?

**Comment by idgserpro** [comment]
We're using the Travis infrastructure, with Firefox. We're testing the last version of selenium 2.x branch since 3.x givers other errors.

```
firefox -v
Mozilla Firefox 31.0
Installed Firefox version
firefox 31.0esr
```

**Comment by aaltat** [comment]
Is this still a problem or can the issue be closed?

**Comment by aaltat** [comment]
Closing due inactivity.
