### ISSUE TITLE
Get Table Cell fails to give correct element if there are nested tables

### ISSUE THREAD

**Issue by clarklsteven** [robotframework/SeleniumLibrary#596]
If you have a table that has rows that contain nested tables within them, and these nested tables have table header elements, it turns out that these "th" elements from the nested table are treated as the first elements in the outer table row.

The offending line is in _tableelement.py at about line 38 and looks like:

columns = rows[row_index].find_elements_by_tag_name('th')

The problem seems to be that the find_elements_by_tag_name being used here will dig deep into anything found in the indexed for (nested or otherwise) and put any "th" elements at the start of the constructed array of column values. It shouldn't do this. It should only pick up "th" rows if they are elements of the row in question.

**Comment by aaltat** [comment]
There has not been activity on the issue for long time and we are doing some cleaning with the issues. Is this a valid problem? If it is a valid problem, could you provide a example test which we all could run?

If there is not response to the issue, I am assuming that this is not anymore valid issue and will close the issue.

**Comment by aaltat** [comment]
Closing due inactivity.
