### ISSUE TITLE
Delete unused (stale) branches

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#598]
following branches are unused (stale) and/or merged and can be removed:
v1.0-source-only Updated 4 years ago by j1z0
iframe Updated 4 years ago by j1z0
select-window Updated 4 years ago by Ed Manlove
fix-webelement-header Updated 9 months ago by zephraph

**Comment by aaltat** [comment]
@zephraph Do you have need for the https://github.com/robotframework/Selenium2Library/tree/sauce-labs ?

**Comment by aaltat** [comment]
@emanlove Can we remove the https://github.com/robotframework/Selenium2Library/tree/sauce-labs

@j1z0 Can we remove the https://github.com/robotframework/Selenium2Library/tree/iframe and https://github.com/robotframework/Selenium2Library/tree/v1.0-source-only

Also pressed delete for some obvious ones.

**Comment by j1z0** [comment]
hey Tatu,

Yeah you can nuke em.

Cheers,
Jeremy

**Comment by just-be-dev** [comment]
@aaltat, I haven't worked on that branch in a while and I won't be able to get to it anytime soon, if ever. I think it's safe to nuke it.

**Comment by aaltat** [comment]
@zephraph I can not deleted it, because of some access rights stuff, could you do it?

**Comment by just-be-dev** [comment]
Done

**Comment by aaltat** [comment]
Thanks

**Comment by ghost** [comment]
This issue can be closed.because (most of the) stale branches are deleted.
