### ISSUE TITLE
"Drag and Drop" function not supported in selenium2library ?

### ISSUE THREAD

**Issue by mamathanag** [robotframework/SeleniumLibrary#60]
Guys,

  I have a requirement to automate Dragging one element from source and dropping it into a target element. I see that drag and drop is not supported in selenium2library. Any alternatives? I am thinking of copying the same from Selenium1. 

-Mamatha

**Comment by emanlove** [comment]
This functionality is supported under Selenium 2 / WebDriver (using [action_chains](http://code.google.com/p/selenium/source/browse/trunk/py/selenium/webdriver/common/action_chains.py)). It's easy enough to create a keyword for it with the only question should we keep the function call the same as the [old selenium library](http://code.google.com/p/robotframework-seleniumlibrary/source/browse/src/SeleniumLibrary/element.py),

<code>drag_and_drop(self, locator, <strong>movement=None</strong>, target=None)<code>

or should it directly correspond with selenium call, such as

<code>drag_and_drop(self, <strong>source</strong>, <strong>target</strong>)</code> *

which I think is cleaner but might break what people are used to. We could leave the drag and drop call as is and add functions like

<code>drag_and_drop_on_target(self, source, target)</code>
<code>drag_and_drop_by_offset(self, source, xoffset, yoffset)</code>

for which the new selenium2library keyword, 'Drag and Drop', could call depending on the movement/target parameters or could be called directly.

\* where <code><strong>source</strong></code> is the same as <code>locator</code>

**Comment by j1z0** [comment]
Yeah I think copying from selenium 1 library wound be the best way to go. However im not sure if the action chains API is the same between selenium 1 and webdriver. 

Cheers,
Jeremy

**Comment by mamathanag** [comment]
@emanlove @j1z0,

Just to bring this issue to closure, documenting what we have implemented in our project and works fine.

Edited element.py and added the following keyword(function) 

def drag_and_drop(self, source, target):
        """Drags element identified with `locator` by `movement`

```
    `movement is a string in format "+70 -300" interpreted as pixels in
    relation to elements current position.
    """
    actionChains = ActionChains(self)
    element = self._element_find(source,True,True)
    target =  self._element_find(target,True,True)
    ActionChains(self._current_browser()).drag_and_drop(element, target).perform()
```

**Comment by j1z0** [comment]
I believe we should just follow what is in webdriver, which is different from what was in selenium.  In web driver it is:

```
drag_and_drop(self, source, target)
drag_and_drop_by_offset(self, source, xoffset, yoffset)
```

in such a way it would break for existing selenium users that were using offsets, but it keep things in line with web driver and will be easier for new users coming from web driver.

**Comment by dkoudrin** [comment]
Drag and Drop in Selenium2Library is NOT working for me... It used to work fine in SeleniumLibrary.

**Comment by daluu** [comment]
FYI, for issues with drag & drop, it would help if one indicates which browser. There are some browser specific issues with WebDriver drag & drop, and SafariDriver has no support for it natively (one would have to use javascript fallback).

**Comment by dkoudrin** [comment]
Hi, sorry, firefox 21 is the browser.

**Comment by daluu** [comment]
Also forgot to mention, any specific public site (or custom HTML file(s)) for testing the issue against? Or is it generally reproducible for any given site using the library and FF 21? It would help to provide the test site or files to reproduce the issue against.

And also, if one is able to use Selenium 2 / WebDriver directly outside of Robot Framework, it also helps to see if issue reproduces there as well to narrow down the problem of whether it is with this library or Selenium itself (or the Python bindings to it). If it is the latter than the former, you'd then have to raise the issue with the Selenium team itself (submit Selenium issue or post to their Google discussion groups).

**Comment by dkoudrin** [comment]
Nah sorry, it is an internal only website, cannot provide it outside the company :(

I use selenium2library in a robot test (run through RIDE). All I've changed is upgraded from importing seleniumlibrary to selenium2library. Now drag and drop fails (and A LOT of other keywords but I am slowly fixing those up).

**Comment by ahitrin** [comment]
@dkoudrin try to run your tests with older version of Firefox (19 or 20). The problem is that Firefox 21 currently is not fully supported by Selenium (see https://code.google.com/p/selenium/source/browse/py/CHANGES for more info).

**Comment by dkoudrin** [comment]
Oh really? Well that's bad news, the whole point of me upgrading to selenium2 was so I could run tests on the latest firefox.

**Comment by ahitrin** [comment]
@dkoudrin You can use the _almost_ latest version, so the news are no so bad :)

**Comment by dkoudrin** [comment]
Yes, but 'almost' doesn't satisfy my boss's requirements...
