### ISSUE TITLE
How to inject msg into the log.html without Keywords

### ISSUE THREAD

**Issue by lucyking** [robotframework/SeleniumLibrary#600]
-  We have generated the gif in the output dir.
-  then we need inject the gif into the log.html at the test_end.
  if calling the **Inject_Gif_To_Log** Keyword that modified from **self.capture_page_screenshot()**, of course robot will inject this Keyword && gif into the log.But the user need call _Inject_Gif_To_Log_ every time.It seems redundant.  
- my question is that,if we can inject the msg/gif directly into log.html in the util.listenerlibrary,etc ,without calling KW in test case?  

Any suggestion is appreciate : )

<br><br>

> calling the KW to inject gif

![ride](https://raw.githubusercontent.com/lucyking/pic/master/call.png)

> the log:

![log_content](https://raw.githubusercontent.com/lucyking/pic/master/log_content.gif)

**Comment by pekkaklarck** [comment]
This isn't really related to Se2Lib but to RF itself. In general messages belong to keywords and you cannot inject a message to log without having a keyword. One keyword can have multiple messages, though. Additionally listeners can call keywords automatically, and version 3 listeners can also modify results (e.g. add keywords and messages) dynamically if needed. See User Guide for more information and ask more help on robotframework-users mailing list or other support forums if needed.

**Comment by lucyking** [comment]
@pekkaklarck  
Many thanks for you patient answer in detail.
Now we're wondering where to set the listener,
in the _robot\output\logger.py_ or _Selenium2Library\utils\librarylistener.py_?
On my opinion,may in the robot's logger is better.Due to RF holds the workflow as well as the log msg.But I'm not sure.May you give us some good advice?
