### ISSUE TITLE
Input Text is very very slow

### ISSUE THREAD

**Issue by digimon83** [robotframework/SeleniumLibrary#604]
My code in RF:
    Open Browser    https://www.baidu.com/    ie
    Input Text    Xpath = //*[@id="kw"]    111

This case run on Win7_64bit OS with IE 11, it will cost me 22 seconds. Anyone know how to speed it up on my machine?

**Comment by HelioGuilherme66** [comment]
Yes, use the 32 bit version of IE Driver.

**Comment by HelioGuilherme66** [comment]
Sorry,

I should not have answered to your question. Ask in other places, this is
Issue tracker.

Please close this Issue.

**Comment by digimon83** [comment]
Using 32bit driver can speed it up. thx for your solution.

发自我的 iPhone

> 在 2016年5月16日，下午4:14，Hélio Guilherme notifications@github.com 写道：
> 
> Sorry,
> 
> I should not have answered to your question. Ask in other places, this is
> Issue tracker.
> 
> Please close this Issue.
> 
> On Mon, May 16, 2016 at 9:09 AM, Hélio Guilherme helio.guilherme@iol.pt
> wrote:
> 
> > Yes, use the 32 bit version of IE Driver.
> >
