### ISSUE TITLE
Scroll Element into View

### ISSUE THREAD

**Issue by MithuraJ** [robotframework/SeleniumLibrary#605]
Error scrolling into view. Using Selenium2Library for robot framework. 

1    Click Element    ${Button}
2    Wait until Page Contains Element    id=title    30
3    Click Element    id=room
4    Wait until Page Contains Element    ${Kitchen}    30
5    Wait until Page Contains   Kitchen    30
6    Current Frame Contains    ${Kitchen}
7    Click Element    ${Kitchen}

4 and 5 pass, the element and text is found but it fails on step 6 and 7 because the element is not in the frame.  The exact error is `ElementNotVisibleException: Message: element not visible`.

If however I add a sleep before 6 and 7, then it finds the element, scrolls it into view and it works.

**Comment by HelioGuilherme66** [comment]
Do you have a public URL where we can see the behavior?
Are you sure the element is visible and in a frame, and that frame is selected?
Have you tried with different browsers?
What is the version of Selenium?

**Comment by aaltat** [comment]
This is quite typical problem with web pages, you are trying to click element before the page has made the element visible. When page contains a element, it doesn't mean that element is visible for the user and could be clicked. Please note that this is not the only possible explanation for your problems and with modern dynamic web apps, there are plenty of other reason too. But as quick try, have you looked at [Wait Until Element Is Visible](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Wait%20Until%20Element%20Is%20Visible) keyword.

But with this information, I am thinking that the library is working as it should be and this is not a bug. Of course we will try our best to support you to solve the problem, but without getting the details that @HelioGuilherme66 requested we can only guess what might go wrong and what would be the best way to solve it.

**Comment by MithuraJ** [comment]
**Do you have a public URL where we can see the behavior?**
No

**Are you sure the element is visible and in a frame, and that frame is selected?**
Maybe, it works when the browser is not full screen because everything is visible however when it is full screen then you have to scroll and not everything is visible 

**Have you tried with different browsers?**
Yes, Chrome & Firefox

**What s the version of Selenium?**
1.7.4

`Wait until Element is Visible`worked, what is the difference between this and `Wait until Page Contains Element`.

Thank you very much!

**Comment by HelioGuilherme66** [comment]
Thank you for the Info.
However, the version of Selenium2Library is 1.7.4 but we still don't know the version of Selenium (the Webdriver core). See below an example:

```
C:\>pip show selenium
---
Metadata-Version: 2.0
Name: selenium
Version: 2.53.2
Summary: Python bindings for Selenium
Home-page: https://github.com/SeleniumHQ/selenium/
Author: UNKNOWN
Author-email: UNKNOWN
Installer: pip
License: UNKNOWN
Location: c:\python27\lib\site-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  License :: OSI Approved :: Apache Software License
  Operating System :: POSIX
  Operating System :: Microsoft :: Windows
  Operating System :: MacOS :: MacOS X
  Topic :: Software Development :: Testing
  Topic :: Software Development :: Libraries
  Programming Language :: Python
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3.2
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
```

`Wait until Element is Visible` == The element exists and the visibility attributes are enabled, and it is not hidden behind other elements. In other words, a User can really see it or interact with it.
`Wait until Page Contains Element` == The element exists in the HTML code in that moment.

Please close this issue, thanks.

**Comment by MithuraJ** [comment]
**Do you have a public URL where we can see the behavior?**
No

**Are you sure the element is visible and in a frame, and that frame is selected?**
Maybe, it works when the browser is not full screen because everything is visible however when it is full screen then you have to scroll and not everything is visible 

**Have you tried with different browsers?**
Yes, Chrome & Firefox

**What s the version of Selenium?**
1.7.4

`Wait until Element is Visible `worked, what is the difference between this and Wait until Page Contains Element.

Thank you very much!

**Comment by aaltat** [comment]
To get a wider audience to your problem and more answers it would be best to post your question to the Robot Framework user group: https://groups.google.com/forum/m/#!forum/robotframework-users
