### ISSUE TITLE
Add Keyword : Delete Browser Cache

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#607]
I need to delete browser cache in order to test some page functionality.

now, to obtain the same result, i tried to
- Open Browser
- Close All Browser (by documentation is the only keyword that delete caches)
- Open Browser

i'm not sure that this is working , because my webpage calculate an ID based on browser cache by if-none-match header (https://en.wikipedia.org/wiki/HTTP_ETag) and sometime the ID doesn't change, so browser cache is not changed.

**Comment by aaltat** [comment]
Instead of creating a new keywords, could you try to demonstrate the original problem? Examples which can be run by anyone to show the problem are really useful.

**Comment by aaltat** [comment]
Would you have an update on the matter?

**Comment by andreabisello** [comment]
@aaltat sorry but my daughter was born some days after this thread and i returned ad work now, then firefox stop working and i must handle the issue 614

i will give a demostration asap

**Comment by aaltat** [comment]
Good luck with new comer and hope all goes well. Take your time on the issue.

**Comment by aaltat** [comment]
Is this still a problem for you or did you get the problem resolved in some way?

Hope that all is going well with the new comer too.

**Comment by andreabisello** [comment]
@aaltat i need something that permits me to say "the cache is not deleted" and give you a test page but in order to obtain this i need some work from my co-worker that developed the library around if-none-match . My daugher is developing hard all the new drivers needed , for example the webcam drivers =D

**Comment by andreabisello** [comment]
@aaltat i don't want to keep the issue opened for month, if you want feel free to close it. i will return when i have an answer.
