### ISSUE TITLE
Add a new keyword for uploading multple files

### ISSUE THREAD

**Issue by VitoAlbano** [robotframework/SeleniumLibrary#609]
At the moment the input element with "multple" attribute cannot be tested with the keyword "Choose File".

I've created a custom keyword which takes in input a list of files and works on Chrome ( needs to be test on Firefox).

**Comment by aaltat** [comment]
I haven't encountered this type of element before. Would you have some example webpage somewhere which we could try out? 

How would the keyword work then? Any usage ideas, keyword name and so on?

**Comment by VitoAlbano** [comment]
Here it is an example page where you can try the element : http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_multiple

The keyword could be as easy as choose multiple files where you can pass the locator, maybe a base path ( to avoid to put the absolute path for all the files) and a list of file names.

There is a known issue opened : SeleniumHQ/selenium-google-code-issue-archive#2239 which talks about it, and searching around it seems that actually there is only a way to do this.

i'll paste here my code (it sure can be improved but it actually works :) ) : 

```
def choose_multiple_files(self, locator, basePath="",  *files):
    fileList = []
    for file in files:
        path_to_image = os.path.join(basePath, file)
        if not os.path.isfile(path_to_image):
            raise AssertionError("File '%s' does not exist on the local file system" % path_to_image)
        fileList.append(path_to_image)
    selenium2Lib = BuiltIn().get_library_instance('Selenium2Library')
    selenium2Lib._element_find(locator, True, True).send_keys("\n".join(fileList))
```

**Comment by aaltat** [comment]
Closing due inactivity

**Comment by lovelytxm** [comment]
Thank you so much for sharing.
