### ISSUE TITLE
Alert Should Be Present&close browser cause memory crash.

### ISSUE THREAD

**Issue by nbbull** [robotframework/SeleniumLibrary#61]
using windows,IE8,I use "Alert Should Be Present ",then call 'close browser' Immediately.
This will frequently  lead to python.exe crash,like"memory can't be read" error.
I add "sleep 1s" after  "Alert Should Be Present ",then it works ok.

**Comment by ombre42** [comment]
I have seen similar problems with java.exe crashing when using Selenium2Library and Selenium Grid. It must be an uncatchable exception happening in native code (C++) that is part of Selenium. I do not see how this is a Selenium2Library issue and not a Selenium issue instead.

**Comment by emanlove** [comment]
@nbbull If you are still experiencing this issue please reopen this ticket.  As @ombre42 suggests this might be an upstream issue with selenium.  The latest [Selenium2Library Developer's Documentation has a tutorial section](https://github.com/rtomac/robotframework-selenium2library/blob/master/BUILD.rst#testing-third-party-packages) on how to discern selenium issues from Selenium2Library issues as well as documentation on how to easily test for bugs within selenium only.
