### ISSUE TITLE
Error trying to run a robot test on safari

### ISSUE THREAD

**Issue by VitoAlbano** [robotframework/SeleniumLibrary#615]
I was trying to run some tests that are already working on other browsers on Safari.
I got this error :  

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
1.Login Page Should Have User and Password Required                   | FAIL |
Parent suite setup failed:
No executable path given, please add one to Environment Variable                 'SELENIUM_SERVER_JAR'

Reading on some forums it seems that this it should be something already fixed, i've also added the extension of Selenium on Safari (9.1.1)

Actually i'm using : 

robotframework (3.0)
robotframework-selenium2library (1.7.4)
selenium (2.53.5)

What am i missing?

Thanks

**Comment by HelioGuilherme66** [comment]
I think you need to use the java-selenium-standalone.jar (this is not the exact name), and define the shell variable  'SELENIUM_SERVER_JAR' to its path.

**Comment by VitoAlbano** [comment]
Yes, this is what i thought , but reading this : https://github.com/SeleniumHQ/selenium/wiki/SafariDriver and then this https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5352 i thought that maybe the safari support was already added to selenium (and selenium2Library) ,that's why i'm asking :)

I've also found this :https://github.com/robotframework/Selenium2Library/pull/247 that seems to be merged

**Comment by aaltat** [comment]
Are you running your test from a Mac or from other OS?

**Comment by VitoAlbano** [comment]
MAC Os 10.11.5

**Comment by aaltat** [comment]
Have you setup the safari driver: https://github.com/SeleniumHQ/selenium/wiki/SafariDriver

**Comment by VitoAlbano** [comment]
Yes i've followed the getting started part where they ask to install on Safari the selenium plugin (SafariDriver.safariextz ) .
For the class example i haven't done anything 'cause i'm using robot so i expect i need only to change the configuration for the browser used.
The only thing which left me surprised is that only until version 2.48 there is this driver for Safari, for newer version there is no Safari exec. Maybe this could be the problem?

**Comment by aaltat** [comment]
I don't own a Mac, so I haven't encountered your problem before. But looking the code and the selenium API, the S2L is creating the driver object as instructed in the SafariDriver pages. Therefore I would assume that one must set the SELENIUM_SERVER_JAR in the $PATH.

**Comment by VitoAlbano** [comment]
Ok it seems that even if the issue is closed on Selenium repo(SeleniumHQ/selenium-google-code-issue-archive#5352) there is no way to use the Safari webdriver without adding the SELENIUM_SERVER_JAR variable.

Thanks :)

**Comment by aaltat** [comment]
It might be good idea to open a new issue in the selenium side

**Comment by VitoAlbano** [comment]
Re opened and get the answer : https://github.com/SeleniumHQ/selenium/issues/2436 :)

**Comment by aaltat** [comment]
Good to know, thank you from input.
