### ISSUE TITLE
"wait until page contains element" doesn't find elements located in iframe

### ISSUE THREAD

**Issue by PavloSI** [robotframework/SeleniumLibrary#62]
quell code:

<pre>
*** Variables ***
${userFieldLocator}         xpath=//*[@id="username"]
...

*** Test Cases ***
ExampleTestCase
         wait until page contains element         ${userFieldLocator}
...
</code>
</pre>

error:

<pre>
<code>
ValueError: Element locator 'xpath=//*[@id="username"]' did not match any elements.
</code>
</pre>

Element '${userFieldLocator}' is located in iframe

This simple example works with 'SeleniumLibrary'

**Comment by j1z0** [comment]
This is correct and as per the design. Frames and iframes consist of a separate HTML page than the 'main page' containing them. Thus u would have to select and switch to the frame first as then wait for the element. 

I'm not saying this is how it should be. I'm just saying this is how it's always been designed....

In addition there is a related issue about the iframe support not really working at all.  Which has been resolved in the iframe branch but there are design reasons why we haven't merged the iframe branch yet. So if u really need the support straight away u can get the iframe branch and it will work for you assuming u follow the steps outline in the first paragraph. 

Cheers,
Jeremy

**Comment by r-chris** [comment]
I thought it may be helpful for anyone else stumbling onto this to add that you can select an `iframe` like this:

```
Select Frame    xpath=//iframe
```

This works if you only have a single `iframe`, but if you are looking to select a specific iframe you would have to expand the `xpath` appropriately.
