### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#620]
Python 2.6 hasn't been officially supported since October 2013 and Robot Framework is going to drop support for in the next major release. There's no need for Selenium2Library to spent development and CI resources to support it anymore in its major release either.

For more details and reasoning see robotframework/robotframework#2276.

**Comment by pekkaklarck** [comment]
In practice this change would mean that we don't include Python 2.6 in our forthcoming CI system and stop testing it in general. I don't think we need to explicitly check is someone using Python 2.6 or try to go through the code to check for places where we could use Python 2.6 features. This issue is here mainly to act as note to be added to the release notes.

**Comment by aaltat** [comment]
The only thing left from this is to documentation and fixing the`setup.py`

**Comment by aaltat** [comment]
Also check `ÌNSTALL.rst` doc

**Comment by aaltat** [comment]
Done in many commits.
