### ISSUE TITLE
Extend existing ci configuration

### ISSUE THREAD

**Issue by drobota** [robotframework/SeleniumLibrary#621]
The task consists of the next:
- Add python 3 config 
- Add chrome and phantomjs 
- Add support for sauce labs to cover safari, ie, edge etc.

Existing issues:
- https://github.com/robotframework/Selenium2Library/issues/467
- https://github.com/robotframework/Selenium2Library/issues/383
- https://github.com/robotframework/Selenium2Library/issues/497

PRs:
- https://github.com/robotframework/Selenium2Library/pull/468
- https://github.com/robotframework/Selenium2Library/pull/557

**Comment by drobota** [comment]
Short status is next:
-  Firefox, Chrome and IE are added 
-  Currently is only python 2.7 used

Current issues:
- all tests are run on sauce lab( need to run firefox on local)
- chrome and IE tests look very bad
- sauce tunnel started for all tests even local browser
- there is no way how to control browser version on saucelabs

What needs to be done
- add browser specific capabilities 
- run firefox tests locally
- need to review tests ( fix/update tests, update test data)

Nice to add:
- python 3+ build 
- split unit tests and acceptance tests 
- more platforms (but we are limited by 5 concurrent jobs on sauce labs)

cc @aaltat, @HelioGuilherme66, @wingyplus

**Comment by pekkaklarck** [comment]
Awesome! Is the problem with 5 concurrent jobs urgent? Is it a permanent problem or a problem because we have a free plan? In the latter case we could try contacting them and asking for a better plan. They promote S2L too, so they ought to be interested it getting good test coverage.

**Comment by drobota** [comment]
Yes, it is a limitation for a free plan. In my view 5 is quite enough. I mentioned it because we only need to select configurations wisely.

**Comment by aaltat** [comment]
Would it make the CI more easier to use/configure/maintain if we could lift some of the free plan restrictions? Or should we gather some experience and then review?

But in any case, great work.

**Comment by HelioGuilherme66** [comment]
For now, to have a basic CI validating our Python 3 development, I created #657.
We'll come back to this task later.

**Comment by aaltat** [comment]
Did looked that runner logic and module import code and it looks like it needs some refactoring. That [__init__.py in utils](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/utils/__init__.py) looks like we have to find better way to import the modules for testing.

**Comment by aaltat** [comment]
This is done in #678
