### ISSUE TITLE
Firefox does not launch on Alpine Linux when desired_capabilities defines firefox_profile

### ISSUE THREAD

**Issue by matthewvalimaki** [robotframework/SeleniumLibrary#624]
When Selenium node is on headless Alpine Linux Firefox would refuse to start up because of how Selenium2Library set firefox_profile. Selenium2Library always sets firefox_profile without giving me the option to not to set it. Likewise `marionette: false` was being set again giving me no way to remove it altogether. Yes, I could do `marionette: true` but that is not what I'm looking for, I want complete removal of the value.

This is what I had in a robot file:

```
Simple Google Browser Test
    Open Browser    https://www.google.com/
    ... browser=firefox
    ... remote_url=http://hub:4444/wd/hub
    Close Browser
```

Here's a snippet of the node log:

```
16:06:26.992 INFO - Creating a new session for Capabilities [{browserName=firefox, javascriptEnabled=true, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIAHehC0evRGoQpQMAA...}]
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error relocating /tmp/anonymous444229514335126196webdriver-profile//org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so: XFree: symbol not found
Error relocating /tmp/anonymous444229514335126196webdriver-profile//org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so: XRefreshKeyboardMapping: symbol not found
Error relocating /tmp/anonymous444229514335126196webdriver-profile//org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so: XSetInputFocus: symbol not found
Error relocating /tmp/anonymous444229514335126196webdriver-profile//org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so: XGetAtomName: symbol not found
Error relocating /tmp/anonymous444229514335126196webdriver-profile//org/openqa/selenium/firefox/amd64/x_ignore_nofocus.so: XQueryTree: symbol not found

        at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:112)
        at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:271)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:119)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:218)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:211)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.callConstructor(FirefoxDriverProvider.java:91)
        at org.openqa.selenium.remote.server.FirefoxDriverProvider.newInstance(FirefoxDriverProvider.java:68)
        at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:60)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:222)
        at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
16:07:12.259 WARN - Exception thrown
```

This is what Selenium2Library sends over to hub:

```
Capabilities [{marionette=false, browserName=firefox, javascriptEnabled=true, version=, platform=ANY, firefox_profile=UEsDBBQAAAAIAHehC0evRGoQpQMAA...}]
```

In comparison same request with [webdriverio](https://github.com/webdriverio/webdriverio):

```
Capabilities [{rotatable=true, locationContextEnabled=true, loggingPrefs=org.openqa.selenium.logging.LoggingPreferences@274f5eeb, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, requestOrigins={name=webdriverio, version=4.2.1, url=http://webdriver.io}}]
```

While I do not know why Firefox does not start I do disagree with forcing default arguments that cannot be overwritten. I've created PR #623 to make everything optional.

**Comment by aaltat** [comment]
The [Open Browser](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Open%20Browser) keyword is not meant to handle all possible scenarios which on can perform when the WebDriver is created. It is meant to handle the most common situations and therefore the keyword is not suitable for all situations.

There might be few other ways to solve the problem. 
1. Have you tried to define the desired_capabilities argument, it is possible with the remote_url parameter?  
2. There is also [Create Webdriver](http://robotframework.org/Selenium2Library/doc/Selenium2Library.html#Create%20Webdriver) keyword, which allows more flexibility on creating the WebDriver.

**Comment by matthewvalimaki** [comment]
> It is meant to handle the most common situations and therefore the keyword is not suitable for all situations.

Understood. I find it just strange that Firefox is a special case where profile is forced including other capability options. I would argue not to do any defaults at all. But the PR I provided leaves that functionality as is giving option to remove them - which is not possible right now.

> Have you tried to define the desired_capabilities argument, it is possible with the remote_url parameter?

Sorry, I do not understand this question. Above I mentioned what I have in the robot file, including `remote_url`. I did try `firefox_profile` as well there but it had no effect as it seems to be set elsewhere.

> There is also Create Webdriver keyword, which allows more flexibility on creating the WebDriver.

No, I have not looked at that yet.

**Comment by aaltat** [comment]
If the `ff_profile_dir` evaluates Python False, then the library will set the `ff_profile_dir` to a default one. By looking the code, if you point the `ff_profile_dir` to a empty directory, that should be enough clear the default profile.

When the `remote_url` is defined, one can also define the `desired_capabilities` argument. It allows to set the desired capabilities in the way one wants.

**Comment by matthewvalimaki** [comment]
Problem is that if I do `ff_profile_dir=""` or anything like that - something that doesn't exist - I get an error saying no such directory. So either I have to have a profile or I do not run.

`desired_capabilities=firefox_profile:1234` has no effect. See line [613](https://github.com/robotframework/Selenium2Library/blob/ec3c897935866b62a64c311bc3218c2538ba1278/src/Selenium2Library/keywords/_browsermanagement.py#L613) which defines profile (which contains the `firefox_profile`).

**Comment by aaltat** [comment]
Sorry for long delay. There is always profile for Firefox, if not given by the user, then selenium will copy one from it's [defaults](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L51). I don't recall why we set the default profile to be different from the selenium profile, perhaps it originates from the SeleniumLibrary. 

But in any case, if you want more control over how the driver instance is created then the [Create Webdriver](http://robotframework.org/Selenium2Library/Selenium2Library.html#Create%20Webdriver) is the direction where to go. Also it is possible to create the driver as by one pleases and register the driver object back to S2L with [register](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/keywords/_browsermanagement.py#L120) function.

**Comment by aaltat** [comment]
Is this still a problem?

**Comment by aaltat** [comment]
Closing due inactivity.
