### ISSUE TITLE
Create issue template to improve bug report quality

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#632]
I think it would improve bug report quality if we take issue template in use, example: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Template should instruct people to add:
- Used browser and version
- Selenium version
- Robot Framework and Python version
- Stack trace of the problem, if feasible
- Robot Framework example if possible

**Comment by HelioGuilherme66** [comment]
See if you want to use my template for issues:  [robotframework-selenium2library/ISSUE_TEMPLATE.md ](https://github.com/HelioGuilherme66/robotframework-selenium2library/blob/code_futurized/ISSUE_TEMPLATE.md)

There is also one for Pull Requests at: [ robotframework-selenium2library/PULL_REQUEST_TEMPLATE.md ](https://github.com/HelioGuilherme66/robotframework-selenium2library/blob/code_futurized/PULL_REQUEST_TEMPLATE.md)

**Comment by aaltat** [comment]
Thanks from the update, it gives good pointers.

**Comment by aaltat** [comment]
The Markdown links did not work in the template and make it look confusing. Strip the formatting away.

**Comment by aaltat** [comment]
Done in #1230
