### ISSUE TITLE
Decide should the documentation be Markdown (md) or reStructuredText (rst/reST)

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#633]
I did create the [CONTRIBUTING.md](https://github.com/robotframework/Selenium2Library/blob/master/CONTRIBUTING.md) by using md but the rest of the documentation is using reST. Decide for the format and use the format in all places.

**Comment by pekkaklarck** [comment]
Markdown pros:
- Used extensively on GitHub (e.g. in these comments)
- Somewhat simpler for simple needs
- More well known by potential contributors

reStructredText pros:
- Supports advanced features like table of contents
- Supported also by PyPI (could use `README.rst` contents as the project long description in `setup.py`)
- Used extensively by Robot Framework core project

**Comment by aaltat** [comment]
One can have table of contents of MD but it must be done manually, therefore I am starting to favor the reStructredText format.

**Comment by just-be-dev** [comment]
I originally pushed for it because it's easier to read (to me) and more widely used on github. I'm in favor of just using rst though, to be standard with the rest of the project.

**Comment by emanlove** [comment]
Funny, I was starting to think, why not, switch over to md for these smaller inner-project documents that are mostly read through Github. [Laughing - @zephraph and I seem to always go in opposite directions]. I would say that for larger more in-depth documentation (generally put into a /doc directory off of root) I would definitely stick to reStructuredText as this is the Python standard and mostly widely used in the Python community.

Really for now the deciding factor would be a debate of maintenance/current effort and forward drive. The forward drive would favor md while the effort to convert over something that is currently doing the job would say leave it be and focus on development. And as you want to get out a release I don't see a compelling and significant reason to spend the time switching over and doing editorial checking.

But I will re-say it (even though I am hesitant too) I'm ok with switching these smaller inner-project documents to md.

**Comment by Tset-Noitamotua** [comment]
+1 for MarkDown

I would not be very suprised if Python will switch to MD in some years. It's becoming more and more mainstream and there are really great (web)editors which make it fun to work with - same as working on Github is a pleasure compared to everything else we use at work.

**Comment by pekkaklarck** [comment]
All docs seem to be reST nowadays. I guess this issue can be considered done.
