### ISSUE TITLE
Cleanup build instructions and scripts

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#634]
The Python build and release has changed since the original Selenium2Library build instructions and scripts has been written. Cleanup the scripts to support modern ways.

Included tasks:
- [x] Better build docs
- [x] Clean up `setup.py`
- [x] Remove `ez_setup` (done as separate issue #646)
- [x] Clean up `MANIFEST.in`
- [x] ~Clean up~ Remove `setup.cfg`
- [x] Better build scripts (probably based on Invoke like with RF itself)
- [x] Remove references to already deleted `doc` directory
- [x] Remove references to already deleted `demo` directory

**Comment by pekkaklarck** [comment]
_Edited by @zephraph to move checklist to the ticket description for more visibility_

**Comment by just-be-dev** [comment]
Hey @pekkaklarck, I moved your checklist up to the description that way it can be seen from the issues list.

**Comment by emanlove** [comment]
I would recommend we also upgrade the test runner (which could be another ticket).

**Comment by pekkaklarck** [comment]
Agreed. I would assume Python 3 adds some new requirements for test runners too. This is also something where we can look for inspiration (or steal code) from RF. If there are lot of very similar needs, we may want to extract some build and test scripts to a separate shared project. Anyway, enhancing test runners definitely needs a separate task.

**Comment by pekkaklarck** [comment]
All checkboxes in the description checked.
