### ISSUE TITLE
Make 1.8.0 relase

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#637]
Make release:
- [x] Verify changes from commits
- [x] Write changes to doc
- [x] Tag version
- [x] Get PyPI account
- [x] Run release command (`python setup.py sdist register upload`)
- [x] Send mail to user group
- [x] Enjoy suitable beverage

**Comment by aaltat** [comment]
More actions:
- [ ] Get Pypi account
- [ ] Tag version

**Comment by pekkaklarck** [comment]
@aaltat: I moved actions from your comment to the description to have all actions in same place.

**Comment by wcainboundary** [comment]
+1 this would be fantastic

**Comment by JetTheHawk** [comment]
+1 This would be really great!

**Comment by aaltat** [comment]
I did put beverage in cold and did promise not to drink it before the release is done. So soon...

**Comment by aaltat** [comment]
This is done, now to the cold one...

**Comment by JetTheHawk** [comment]
Well deserved! Thanks!!

**Comment by wcainboundary** [comment]
🍻

**Comment by wcainboundary** [comment]
@aaltat It looks like the binaries did not upload to pypi.

For example, there is a `Downloads ↓` button in [1.7.4](https://pypi.python.org/pypi/robotframework-selenium2library/1.7.4#downloads) with this content in the downloads section:

```
File    Type    Py Version  Uploaded on Size
robotframework-selenium2library-1.7.4.tar.gz (md5)  Source      2015-08-26  229KB
robotframework-selenium2library-1.7.4.win-amd64.exe (md5)   MS Windows installer    any 2015-08-26  386KB
robotframework-selenium2library-1.7.4.win32.exe (md5)   MS Windows installer    any 2015-08-26  359KB
robotframework-selenium2library-1.7.4.zip (md5) Source      2015-08-26  249KB
robotframework_selenium2library-1.7.4-py2.6.egg (md5)   Python Egg  2.6 2015-08-26  116KB
robotframework_selenium2library-1.7.4-py2.7.egg (md5)   Python Egg  2.7 2015-08-26  117KB
```

vs. No `Downloads ↓` button in [1.8.0](https://pypi.python.org/pypi/robotframework-selenium2library/1.8.0#downloads) and no downloads section.

So far we have been unsuccessful installing 1.8.0 with pip:

```
Could not find a version that satisfies the requirement robotframework-selenium2library==1.8.0
...
No matching distribution found for robotframework-selenium2library==1.8.0
```

...whereas no problem with 1.7.4.

Any ideas? Thank you!

**Comment by HelioGuilherme66** [comment]
@wcainboundary Thank you for the Report. We already noticed that and @aaltat is going to fix it when he can.

**Comment by aaltat** [comment]
And it's fixed

**Comment by wcainboundary** [comment]
Thank you! 🙇🏽 🙇🏽 🙇🏽
