### ISSUE TITLE
Capture (not all the page) Screenshot

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#638]
with http://robotframework.org/Selenium2Library/Selenium2Library.html#Capture%20Page%20Screenshot we can take screenshot of the full webpage.

i need to take a screenshot of a part of the webpage, for example, a css selector.

how to obtain this?

thanks

**Comment by aaltat** [comment]
S2L does not have the functionality but getting screen shot from element is possible by using selenium: http://selenium-python.readthedocs.io/api.html?highlight=screen%20shot#selenium.webdriver.remote.webelement.WebElement.screenshot

It could be useful to have this functionality also in the S2L. Would you be interested to make a pull request?

**Comment by emanlove** [comment]
I would recommend the [robotframework-selenium2screenshots library](https://github.com/datakurre/robotframework-selenium2screenshots), which you seemed to have found and has this capability already.

Before installing the selenium2screenshots library you should first install [Pillow](https://pillow.readthedocs.io/en/3.3.x/) (which is the current maintained, pip-installable version of [PIL or Python Imaging Library](https://pypi.python.org/pypi/PIL)). To install Pillow try

```
pip install pillow
```

Then install robotframework-selenium2screenshots with

```
pip install robotframework-selenium2screenshots
```

**Comment by emanlove** [comment]
@aaltat I would recommend we leave this functionality out of the core Selenium2Library and instead use and expand/contribute to the [robotframework-selenium2screenshots library](https://robotframework-selenium2screenshots.readthedocs.io/en/latest/).

**Comment by aaltat** [comment]
Didn't recall that library, I agree with @emanlove

**Comment by pekkaklarck** [comment]
Should the sceenshot lib and other possible companion libraries be mentioned in the README or elsewhere?

**Comment by aaltat** [comment]
At least somewhere, perhaps readme is a good place.

**Comment by vasudeoparab** [comment]
Hello,

How to take whole page screenshot with out scrolling bar in robot framework

**Comment by jonny64** [comment]
What about current SeleniumLibrary v3 ?
 - I can't use selenium2screenshots 
 - SeleniumLibrary v3  fails to Capture Page Screenshot due to  js alert open, out app full of this

**Comment by aaltat** [comment]
It looks like you have different problem than what is stated in the original description and therefore posting to unrelated issue is not a good idea. Also it looks like you are seeking a support: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
