### ISSUE TITLE
Assertion failing on Internet Explorer

### ISSUE THREAD

**Issue by vishaltelangre** [robotframework/SeleniumLibrary#640]
I have following keyword:

``` robot
Element Should Contain  css=#flash  ×\nHello there...
```

And here's the HTML (from a page) it is tested upon:

``` html
<div id="flash">
  <button type="button" class="close" data-dismiss="alert">×</button>Hello there...
</div>
```

It works on Firefox and Chrome browsers (webdrivers) but fails on Internet Explorer with following expectation:

```
×Hello there...
```

Notice the newline is getting ignored while performing assertion on IE.

How to fix such cases? Is there any way through we can instruct Robot or Selenium to do it the same way alike Firefox and Chrome WebDrivers?

**Comment by drobota** [comment]
It might be a InternetExplorer driver issue. I suggest you to test this example in python.
Easy fix is use partial text `Element Should Contain  css=#flash  Hello there`

**Comment by aaltat** [comment]
The `Element Should Contain` keyword does exact match and the text does not contain *-character or a new line in the example. If the text is different in different browsers, which is common between IE and other browsers, the best option would be to change the text to be same in all browsers. The seconds best option is to use xpath with [contains](https://www.w3.org/TR/xpath/#function-contains) or [starts-with](https://www.w3.org/TR/xpath/#function-starts-with) functions.

**Comment by aaltat** [comment]
Is this still a problem for you or can we close the issue?

**Comment by vishaltelangre** [comment]
I have overridden the `element_should_contain` method to make it work across all browsers. 
Thanks everyone for suggestions.
