### ISSUE TITLE
Canvas Automation Support

### ISSUE THREAD

**Issue by vinaybond** [robotframework/SeleniumLibrary#645]
Is there any plan to automate HTML5 <canvas> . If yes, when it is likely to happen?

**Comment by aaltat** [comment]
As far I know we do support HTML5. Could you be more specific on your request: Examples and error messages from failures are useful. Specially if those examples are based on webpages which are available for all of us. Also explaining what problem you are trying to solve is useful.

**Comment by aaltat** [comment]
Would you have an update to the matter?

**Comment by vinaybond** [comment]
Sorry @aaltat I should I have shared details in my first post. Its about supporting the new components 

<canvas>: Right now we cannot detect and interact with the object inside HTML5 canvas. If I want to get some text from the box inside canvas, i cant.

<Video> : As far as I know, there is no way I can play/pause video, change the volume with selenium Web API. 

There may be some more objects as well. But these are the two that I can think of. Canvas I have seen is widely being used and we have to rely on image processing libraries which comes with its limitations.

**Comment by aaltat** [comment]
If you want to find ways to interact stuff inside of the canvas element, you need to find some other way/library. This library relies on selenium and as far I know what you seek is not directly supported by selenium. Therefore it's not supported by us either.

By Googleling you can find some solutions how to interact with stuff inside of canvas with selenium. But those solution are purely application specific. I haven't tested anything with canvas and therefore cannot give a good answer, perhaps it would best to ask the same question from Robot Framework user group. In this way you get a wider audience for your problem and find someone that has encountered a same type of problem. This person might be able help you better.

**Comment by aaltat** [comment]
Are you having more questions about the topic or can we close the issue.
