### ISSUE TITLE
unify print() usage

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#648]
printing new line was used with `print('')` and with `print()`. Use only print()

**Comment by pekkaklarck** [comment]
First of all, wouldn't it be better to have this as a sub-task in Python 3 support? Secondly, `print()` and `print('')` are not identical in Python 2. Should use `from __future__ import print_function` in all production code.

**Comment by HelioGuilherme66** [comment]
Shouldn't we use double quotes instead of single quotes?

**Comment by aaltat** [comment]
Closed in f168c358
