### ISSUE TITLE
Handling alerts sometimes fails with Chrome

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#652]
With Chrome  53.0.2785.92, chromedriver 2.23.409687 and selenium 2.53.6 the alert acceptance test seems be failing, again. 

There seems to be timing issue with chrome which causes `WebDriverException: Message: unknown error: unhandled inspector error` on random but frequent places. Fix the error or at least perform few times a re-try.

**Comment by lionlamb** [comment]
I am still encountering this issue in Chrome but not Firefox.
I am using the latest SeleniumLibrary, curious if there is workaround on it? I pasted the error below:
```

Login To Page                                                  [7092:19556:0716/174928.983:ERROR:install_util.cc(597)] Unable to read registry value HKLM\SOFTWARE\Policies\Google\Chrome\MachineLevelUserCloudPolicyEnrollmentToken for writing result=2

DevTools listening on ws://127.0.0.1:57742/devtools/browser/e862df1c-13e1-464f-b426-6b650734699a
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : This is demo pop up.}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.16299 x86_64)

```

**Comment by aaltat** [comment]
I am pretty that your problem is not same as this because it's over two years old. If you think that there is a problem in the library, please open new issue. If you are seeking support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
