### ISSUE TITLE
Fix _alert.py documentation to use reStructuredText

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#665]
- [ ] Format documentation to use reStructuredText
- [ ] Follow pep8

**Comment by pekkaklarck** [comment]
Wouldn't it be better to have one issue about moving to reST and not separate issues for each module? Didn't know that was decided already, but don't have anything against it. Should also decide do we follow Sphinx style or something else to document arguments. That may then require changes on Libdoc side to format them nicely.

**Comment by aaltat** [comment]
True, if separate issue are created for each module, it will come a maintenance burden.
