### ISSUE TITLE
Need functionally to allow for key arrows to be sent to browser 

### ISSUE THREAD

**Issue by jono-allen** [robotframework/SeleniumLibrary#667]
The Current mapping table in keywords/_element.py does not have the keys arrows mapped. Require this functionality to drive a dropdown menu that is dynamically generated.

**Comment by Gaurang033** [comment]
I can take that up, the only problem is Arrow keys are not represented by single ASCII code. So not sure what to use in key map? any suggestions?

**Comment by aaltat** [comment]
PR #666 is for this but it lacks the test.

**Comment by aaltat** [comment]
Closing this on favor of #498
