### ISSUE TITLE
Cannot operate on the invisible element?

### ISSUE THREAD

**Issue by EileenLi** [robotframework/SeleniumLibrary#67]
<p>
<input id="test-io_name" class="checkbox io-select-field" type="checkbox" forfield="io_name" name="test-io_name">
<label for="test-io_name"></label>
</p>

Above is the html for a "Checkbox", the checkbox is covered by the label, and the checkbox is invisible. 
The user can click the label to select the checkbox, but the automation cannot. It throws below error
"ElementNotVisibleException: Message: u'Element is not currently visible and so may not be interacted with'".

Seems Selenium2Library doesn't support the invisible element? How to solve this problem?

**Comment by j1z0** [comment]
Sorry but what selector are u using to get the element. Are u calling click on the label or the checkbox?  If its invisible selenium won't click it unless you modify selenium itself.  But if it's really invisible I would
Be surprised that a browser would click the element either.  Is there some JavaScript involved?  Can h just call the JavaScript directly?

**Comment by EileenLi** [comment]
Thank you for the feedback. Yes, I want to modify selenium itself, to select the invisible Checkbox forcelly. How could I do that?

**Comment by EileenLi** [comment]
Problem solved by "Click Element" on the label. https://github.com/rtomac/robotframework-selenium2library/issues/67/close

**Comment by manojthennarasu** [comment]
Hi  EileenLi, am facing exactly the same here... Can you please provide me the details how you resolved it. It would help me..

**Comment by Leoooob** [comment]
Instead of clicking on the locator you are currently using, change the locator to point to the container or the inner element
