### ISSUE TITLE
Element locator could not find the element by XPath

### ISSUE THREAD

**Issue by ghost** [robotframework/SeleniumLibrary#670]
Hello,
I try to use xpath to locate the element which contains some text, but selenium2library reports below error:

> ValueError: Element locator 'xpath=//td[text()[contains(.,'PRODUCT')]]' did not match any elements.

I do validate the XPath  `//td[text()[contains(.,'PRODUCT')]]` directly in python+selenium, it works fine.

Does selenium2library support such xpath? Or is there some magic trick for make it working?

Thanks,

**Comment by aaltat** [comment]
Xpath is supported. If you use assertion type of keyword, like Click Element or Get Element Text, the keyword doesn't perform polling. This means that the element must be present at the page when keyword gets executed. But with modern web applications, which usually are quite dynamic, it's best practice to poll the element before test performs the interaction with the element. For polling library offers many different Wait\* type of keywords. If you use those keywords, will it solve your problem?

**Comment by ghost** [comment]
Oops, It seems that I used incorrect type for the element.
The issue has gone after use 'Click Element' instead of 'Click Button'.

Thanks a million for your reply.

**Comment by aaltat** [comment]
Good that you got it sorted out.
