### ISSUE TITLE
Get Child object of a given element

### ISSUE THREAD

**Issue by mzbedat** [robotframework/SeleniumLibrary#672]
Hi,
When using the Get WebElements keyword am getting a list of elements that fits my locator.
Each element contains a child object, how can I get the child one?

example:

``` html
<a class="yt-uix-sessionlink spf-link " data-sessionlink="itct=CGEQlDUYAyITCOeh4-OEvM8CFQKkHAodw6QFfSiOHjIGZy1oaWdoWg9GRXdoYXRfdG9fd2F0Y2g" href="/watch?v=5i-94at2SDA" aria-hidden="true">
<div class="yt-thumb video-thumb">
<span class="yt-thumb-simple">
<img height="110" width="196" data-ytimg="1" alt="" src="https://i.ytimg.com/vi/5i-94at2SDA/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=YqxUUk-Z6HgOYPKBVVuMA9o1iaU" onload=";__ytRIL(this)">
</span>
</div>
<span class="**video-time**" aria-hidden="true">**3:34**</span>
/a>
```

I want to get the "video-time" inside a random a> element, is it possible?

**Comment by aaltat** [comment]
Is there a reason why this does not work:

```
| ${text} = | Get Element Text | xpath=//*[@class="**video-time**"] |
```

**Comment by mzbedat** [comment]
Yes.
I have many "video-time" elements in the page (YouTube Home Page for example) and I want to randomize one element and pick it up only if it's duration is less than a threshold...

for now I used:
`${duration_text}=      Selenium2Library.Get Text   xpath=.//ol[@class='item-section']/li/div/div[1]/div[2]/ul/li[${**random**}]/div/div/div/div[1]/a/span`

But I know that in robotframework-uiautomator library there is a Get Child keyword, so maybe it can be added to Selenium library as well.

**Comment by emanlove** [comment]
The idea of a "Get Child" keyword is interesting. Working with the AngularJS Library and the underlying Protractor/WebDriverJS I see a lot of this (pseudo-code here)

```
child = parent.find_by_('locator')
...
grandchild = child.find_by('another_locator')
```

I have thought about adding an optional parameter to the Get Web Elements keyword passing it a root element from where to search from. I struggled with how we could do this with just a locator. Some sort of "Get Child" keyword might be a valid solution...

**Comment by aaltat** [comment]
Because you need to get the time, would the problem be easier to solve if there would be a keyword which would return text from all elements that would match to the selector. Example like:

```
| @{texts} = | Get Elements Text | xpath=//*[@class="**video-time**"] |
```

Then you could iterate through the list of times and make decisions based on the time.

**Comment by aaltat** [comment]
The finding element child is an interesting idea and also a one which I have sometimes used. Also in a similar situation which @mzbedat described. I do not anymore have the code available, but if recall correctly I did add the element in the S2L by using `_cache.register` and `_cache.close` methods. Then it worked quite nicely. I did call the keyword `Set Context` and `Clear Context`keywords.

**Comment by aksenov007** [comment]
As @aaltat [requested](https://github.com/robotframework/SeleniumLibrary/pull/702#issuecomment-352174529), here is a possible acceptance test for this issue.

Because this functional can be a little bit tricky to understand and implement, I think it makes sense to make acceptance tests for any type of locator. Also, may be it makes sense to create a separate file for these tests, what do you think about it? 

```
Get Child Web Element Passing Parent And Child As Locator
    ${child}=    Get Child WebElement    //div[@id="first_div"]    css:#foo
    ${expected_child}=    Get WebElement    id:foo
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Parent And Child As Locator
    [Setup]    Go To Page "nested_divs.html"
    @{childs}=    Get Child WebElements    //div[@id="d"]    tag:a
    @{expected_childs}=    Get WebElements    //div[@id="d"]//a
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Child As Element Should Fail
    ${parent}=    Get WebElement    //div[@id="first_div"]
    ${child}=    Get WebElement    //div[@id="first_div"]/a
    Run Keyword And Expect Error    Get Child WebElement does not support `WebElement` as a `child_locator` parameter value    Get Child Webelement   ${parent}    ${child}

Get Child Web Elements Passing Child As Element Should Fail
    [Documentation]  Get Child WebElements should fail if "child locator" is a web element
    ${parent}=    Get WebElement    //div[@id="first_div"]
    ${child}=    Get WebElement    //div[@id="first_div"]/a
    Run Keyword And Expect Error    Get Child WebElements does not support `WebElement` as a `child_locator` parameter value    Get Child Webelements   ${parent}    ${child}

Get Child Web Element Passing Implicit Child Locator With Id
    [Setup]    Go To Page "nested_divs.html"
    ${parent}=    Get WebElement    id:d
    ${child}=    Get Child WebElement    ${parent}    needleD2
    ${expected_child}=    Get WebElement    id:needleD2
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Implicit Child Locator With Id
    [Setup]    Go To Page "nested_divs.html"
    ${parent}=    Get WebElement    id:d
    @{childs}=    Get Child WebElements    ${parent}    needleD2
    @{expected_childs}=    Get WebElements   id:needleD2
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Implicit Child Locator With Name
    ${child}=    Get Child WebElement    tag:body    div_name
    ${expected_child}=    Get WebElement    (//*[@name='div_name'])[1]
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Implicit Child Locator With Name
    @{childs}=    Get Child WebElements    tag:body    div_name
    @{expected_childs}=    Get WebElements   name:div_name
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Explicit Child Locator With Id
    [Setup]    Go To Page "nested_divs.html"
    ${parent}=    Get WebElement    id:d
    ${child}=    Get Child WebElement    ${parent}    id:needleD2
    ${expected_child}=    Get WebElement    id:needleD2
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Explicit Child Locator With Id
    [Setup]    Go To Page "nested_divs.html"
    ${parent}=    Get WebElement    id:d
    @{childs}=    Get Child WebElements    ${parent}    id:needleD2
    @{expected_childs}=    Get WebElements   id:needleD2
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Explicit Child Locator With Name
    ${child}=    Get Child WebElement    tag:body    name:div_name
    ${expected_child}=    Get WebElement    (//*[@name='div_name'])[1]
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Explicit Child Locator With Name
    @{childs}=    Get Child WebElements    tag:body    name:div_name
    @{expected_childs}=    Get WebElements   name:div_name
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Explicit Child Locator With Identifier
    ${child}=    Get Child WebElement    tag:body    identifier:div_name
    ${expected_child}=    Get WebElement    (//*[@name='div_name'])[1]
    Should Be Equal    ${child}    ${expected_child}
    ${child}=    Get Child WebElement    tag:body    identifier:div_id
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Explicit Child Locator With Identifier
    @{childs}=    Get Child WebElements    tag:body    identifier:div_name
    @{expected_childs}=    Get WebElements   name:div_name
    Lists Should Be Equal    ${childs}    ${expected_childs}
    @{childs}=    Get Child WebElements    tag:body    identifier:div_id
    @{expected_childs}=    Get WebElements   id:div_id
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Explicit Child Locator With Class
    ${child}=    Get Child WebElement    tag:body    class:Second class
    ${expected_child}=    Get WebElement    class:Second class
    Should Be Equal    ${child}    ${expected_child}

Get Child Web Elements Passing Explicit Child Locator With Class
    @{childs}=    Get Child WebElements    tag:body    class:Second class
    @{expected_childs}=    Get WebElements   class:Second class
    Lists Should Be Equal    ${childs}    ${expected_childs}

Get Child Web Element Passing Explicit Child Locator With Tag
    [Setup]    Go To Page "nested_divs.html"
    ${child}=    Get Child WebElement    id:d2    tag:a
    ${expected_child}=    Get WebElement    id:needleD2
    Should Be Equal    ${child}    ${expected_child}
```

etc. for xpath, css, dom, link, partial link; I think the current snippet explains the idea clearly already. If no, I can write the rest tests in this issue as well tomorrow.

**Comment by aaltat** [comment]
I think creating a new keyword for getting the child element is not good idea. Instead we could enhance the `Get WebElement` and `Get WebElements` keywords to support child element. The keyword could look like this:
```
| ${child_element} = | Get WebElement | locator | parent |
```
The keyword would first search the element with `parent` argument locator and then it would use the parent element to find the child element by using the `locator` argument locator. 

Some noteworthy things to decide. Using a parent to search child element is not supported by all locator strategies that the SeleniumLibrary supports. Example using parent to find child can't not be done locator strategy which use JavaScript to find element, because JavaScript is always executed by using the `driver` and JavaScript can't be executed by using a element. In practice child element can be found by using the strategies which are directly supported by the Selenium [1]. Perhaps it would be best to raise an error if finding a child is not supported by the locator strategy used with the keyword. Also we need to document and test the above well.

[1] http://selenium-python.readthedocs.io/locating-elements.html

**Comment by aksenov007** [comment]
@aaltat Thanks for the answer!

> I think creating a new keyword for getting the child element is not good idea. Instead we could enhance the `Get WebElement` and `Get WebElements` keywords to support child element.

I am agree with you absolutely. Our team use the same overload approach in our wrappers over Selenium methods.

> Example using parent to find child can't not be done locator strategy which use JavaScript to find element, because JavaScript is always executed by using the driver and JavaScript can't be executed by using a element. In practice child element can be found by using the strategies which are directly supported by the Selenium [1].

If so, then according to the table of supported explicit locator strategies from [SeleniumLibrary documentation](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Locating%20elements) if there are two arguments are passed (`locator` and `parent` both) the `child` locator should be explicit (is implicit possible too, because that strategy uses "id" or "name" which are supported by Selenium directly? I will check it this week) and the stategy should be one of the following: `id`, `name`, `identifier` (?), `class`, `tag`, `xpath`, `css`, `link`, `partial link`.

> Perhaps it would be best to raise an error if finding a child is not supported by the locator strategy used with the keyword. Also we need to document and test the above well.

The error message could look like: "Impossible `locator` strategy: < requested locator strategy >. If `child` parameter is provided, `locator` should use one of the following strategies: `id`, `name`, `identifier` (?), `class`, `tag`, `xpath`, `css`, `link`, `partial link`". The second sentence of the error message could be put in the documentation of both keywords.

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by zed0** [comment]
If anyone is still looking for this I've been using the following:
```robot
Get child webelement
    [Arguments]    ${parent}    ${child_selector}
    ${parent_element}=    Get webelement    ${parent}
    ${selector_parts}=    Get regexp matches    ${child_selector}    ^(\\w+)[:=](.*)$    1    2
    ${selector_scheme}=    Set variable    ${selector_parts[0][0]}
    ${selector_query}=    Set variable    ${selector_parts[0][1]}
    ${child_element}=    Call method    ${parent_element}    find_element    ${selector_scheme}    ${selector_query}
    [return]    ${child_element}
```

**Comment by albert-schilling** [comment]
I would like to reopen this issue in a more general context.
We just came across a similar issue, where we wanted to make sure a `DOM element` exists or does not exist inside another `container DOM element`. It would be great if `Get WebElement(s)` and the `Element *` keywords could be enhanced with an optional context, which would just be another context. I guess, the implementation should not be that hard. 

If the locators are in xPath => provide document.evaluate with the `container DOM Element` as context. 
https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate
e.g. in: `document.evaluate(.elementXPath, contextDOMNode, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue`
... and if the locators are css selectors, use querySelector not on the document object but on the `container DOM Element`.
e.g. `contextDOMNode.querySelector(elementCSSSelector)`

**Comment by aaltat** [comment]
Yes, this gets asked now and then. Also it's technically possible to implement this in many ways. But unfortunately no one has seen this important enough to implement. Currently my development time is used to help https://github.com/MarketSquare/robotframework-browser

**Comment by praveendvd** [comment]
> Yes, this gets asked now and then. Also it's technically possible to implement this in many ways. But unfortunately no one has seen this important enough to implement. Currently my development time is used to help https://github.com/MarketSquare/robotframework-browser


There is direct message, you can use execute script to create a varaible.

so i created a keyword 

      Validate child element exists

it takes two argument parent(Webelement) and child(Xpath) to search for child inside the parent.

      Validate child element exists    ${parent}    ./h3

Assuming parent xpath to as : `//ul[@id="top_menu"]` , the above code will search for equalent xpath `//ul[@id="top_menu"]/./h3` note taht context is parent and not root

so this will be equalent to xpath 







    *** Test Cases ***
    Google Search
        [Tags]    you    probably    do    not    have    this    many    tags    in    real    life
        Wait Until Element Is Visible  CSS=[id="introduction-container"]
        ${parent}=    Get webelement    xpath=//*[@id="introduction-container"]
    	${result}=    Validate child element exists    ${parent}    ./h3   
        Should Be True     ${result}
    
    	
    *** Keywords ***
    Validate child element exists 
        [Arguments]    ${parent}   ${child} 
        ${child}=    Execute Javascript    return window.document.evaluate( arguments[1], arguments[0], null, XPathResult.FIRST_ORDERED_NODE_TYPE, null ).singleNodeValue;     ARGUMENTS    ${parent}    ${child}
        [Return]    ${child}

**Comment by lukasgebhard** [comment]
For SeleniumLibrary versions 5.0 and above, you can use [chained locators](https://github.com/robotframework/SeleniumLibrary/issues/1512).
