### ISSUE TITLE
Support locating elements using element class

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#673]
Decide should selenium find_by_class exposed as selector strategy. Based on discussion on user group: https://groups.google.com/forum/m/#!topic/robotframework-users/2gzzmGAhofY

**Comment by emanlove** [comment]
I vote yes. In my mind the most basic concept for the Selenium2Library is it exposes and mirrors the functionality of the underlying Selenium Python WebDriver. As this is one of the base find_by method it makes sense that it should be within the core locator strategies.

**Comment by aaltat** [comment]
I am thinking to the same direction. Also it is something which is not that hard to do.

**Comment by Gaurang033** [comment]
if no one has started working on it, i can take this up.

**Comment by aaltat** [comment]
Feel free to make a pull request. Remember to write tests and update the library keyword documentation on the locator strategies.

**Comment by Gaurang033** [comment]
Created the pull request #584. Please check.

**Comment by aaltat** [comment]
Please make a separate pull request to resolve this issue.

**Comment by Gaurang033** [comment]
created a separate pull request as suggested.  #674

**Comment by aaltat** [comment]
Thank you for the update.

**Comment by aaltat** [comment]
Done in https://github.com/robotframework/Selenium2Library/pull/674
