### ISSUE TITLE
Maximize Browser Window with Chrome doesn't work as expected on OSX

### ISSUE THREAD

**Issue by molsky** [robotframework/SeleniumLibrary#677]
`Maximize Browser Window` keyword only maximizes browser window height or doesn't even do that at all (looks like Chrome opens by default with max height). When setting window size with `Set Window Size` keyword  browser's width and height changes correctly. So it looks like `Maximize Browser Window` is partially or completely broken with Chrome on OSX.

OS: macOS Sierra
Chrome 53 & chromedriver 2.24

robotframework==3.0
robotframework-selenium2library==1.8.0
selenium==2.53.6 (tested also with 3.0.1)

**Comment by aaltat** [comment]
I don't have Mac available but the bug may be on selenium side. If you execute the following code l:

```

from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
driver.get("http://www.python.org")
driver.maximize_window()
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.clear()
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

is the browser then maximised correctly? If it's then there is a bug in the Selenium2Library side. If it's not then the bug is on the selenium and we cannot fix it.

**Comment by drobota** [comment]
I noticed this issue as well. I believe that is known bug and it is related specifically to chromedriver implementation. 
Here I found this bug 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=985

**Comment by kormbrek-rally** [comment]
The root problem appears to be that maximize in Chromium is not maximize.
https://bugs.chromium.org/p/chromium/issues/detail?id=14185
So even starting Chrome with `--start-maximized` doesn't help.
If `Set Window Size` is not an alternative for you, here is a workaround that runs Chrome full screen:

```
    ${options}  Evaluate  sys.modules['selenium.webdriver'].ChromeOptions()  sys
    Call Method  ${options}  add_argument  --start-fullscreen
    Create WebDriver  Chrome  chrome_options=${options}
    Go To  https://stackoverflow.com
```

**Comment by aaltat** [comment]
@molsky Because this seems to be problem with selenium and not problem with Selenium2Library I am going to close the issue. If need more information/help or disagree on the matter, we can always reopen the issues and see if we could do something.

**Comment by ngoyalx** [comment]
I was facing the same issue specifically for mac. Following worked fine for me.

JavascriptExecutor jse = (JavascriptExecutor)driver;
        String screenWidth = jse.executeScript("return screen.availWidth").toString();
        String screenHeight = jse.executeScript("return screen.availHeight").toString();
        int intScreenWidth = Integer.parseInt(screenWidth);
        int intScreenHeight = Integer.parseInt(screenHeight);
	Dimension d = new Dimension(intScreenWidth, intScreenHeight);        
	driver.manage.window.setSize(d);

**Comment by ksmanoj** [comment]
@ngoyalx Thumbs up

**Comment by imardari** [comment]
Thanks @kormbrek-rally
Do you know by any chance how to achieve the same result but with Safari on Mac?
When I use 
`maximize browser window`
It just ignores that line(because it does not maximize it)
I'm using:
Python(PyCharm IDE)
robotframework==3.0.3.dev20170213
selenium==3.4.3

Thanks and Cheers!

**Comment by kormbrek-rally** [comment]
sorry @imardari only working with Chrome in a Docker image lately.
[Set Windows Size](http://robotframework.org/Selenium2Library/Selenium2Library.html#Set%20Window%20Size) should help the testing to be consistent rather than relying on the desktop dimensions anyways.
