### ISSUE TITLE
Two elements with same id, xpath and class.

### ISSUE THREAD

**Issue by Bouqui** [robotframework/SeleniumLibrary#679]
Hello All,

I am currently having an issue running a test. There are two elements sharing using same id, xpath and class and so the test fails everytime I try to click a specific element.

Can someone please help with this as I need to complete the test script ASAP

Thanks

**Comment by pekkaklarck** [comment]
Isn't two elements on a same page having same id a real bug?

**Comment by aaltat** [comment]
There could be many ways to solve the problem. One of them being a unique id to the element and the most easiest way from your point of view.

To be able to help you better, could share the relevant parts of the DOM and explain what element you actually want to click.

**Comment by Bouqui** [comment]
@aaltat The issue here is that 2 different elements share same id, xpath and class. Below is part of the DOM and a screenshot of the page

**\* Settings ***
Library           Selenium2Library

**\* Test Cases ***
Log in
    Open Browser    "url of application under test"  Chrome
    Maximize Browser window
    Title should be    Cheap Flights, Vacation Packages, Affordable Holidays
    Element Text should be    id=dropdownMenu1    Account
    Click Element    id=dropdownMenu1
    Click Element    /html/body/div[3]/div/div/div/div[1]/div[4]/div[4]/ul/li[1]/a
    Page should contain    Sign in to your account
    Input Text    id=txtUserName    user@gmail.com
    Input Text    id=txtPassword    password
    Select Checkbox    id=chkTermCondition
    Click button    css=btn.bold.btn-warning.orange-btn

These are the links to the screenshots of the element I am trying to click http://take.ms/74GQg  and http://take.ms/buz52. Account and Support are using same id, xpath and class. I intend clicking on Account but Support was clicked instead when I run the test.

**Comment by HelioGuilherme66** [comment]
I don't see a bug here. When selenium is locating your element, it probably stays focused on the last occurrence (the Support).

I think you should be able to clearly identify your element by incorporating the text value in the xpath expression (i.e. contains('Accept')).
Other possibility is to use `Get Web Elements` and iterate with them (or refine search like I mentioned before).

**Comment by drobota** [comment]
I see only one issue here you don't know how to use xpath, css selector etc. 
I would recommend you to have a look into these tutorials 
http://www.w3schools.com/cssref/css_selectors.asp
http://www.w3schools.com/xml/xpath_intro.asp

**Comment by Bouqui** [comment]
@HelioGuilherme66  Could you pls give the right xpath to use? i.e how to incorporate text value in the xpath.

Thanks

**Comment by drobota** [comment]
`//button[., "expected_button_text"]`

**Comment by aaltat** [comment]
@Bouqui do you still have a problem or can we close the issue.

**Comment by Bouqui** [comment]
@aaltat Still couldn't find my way around it. :(

**Comment by Bouqui** [comment]
I finally found a solution to it by using //*[@id="dropdownMenu1"][contains(string(),'Account')]

Thanks everyone.
