### ISSUE TITLE
How to switch to the new tab with the same title of the original tab?

### ISSUE THREAD

**Issue by lamcee** [robotframework/SeleniumLibrary#685]
For example, new tab opened by clicking a `a` tag:

```html
<a target="_blank" class="btn btn_add btn_primary r btn_new" href="/inedx.php?t=media/blog_edit&amp;action=edit&amp;isNew=1&amp;type=10&amp;token=690587089"> new blog  </a>
```

The title of the new tab is the same with the original, I was wondering how to switch to it?

**Comment by lamcee** [comment]
I find an ugly way to make it

``` javascript
    ${url}=       Execute Javascript    return $('.btn_new').attr("href")
    ${url}=      Evaluate    "https://blog.mytest.com"+('${url}')
    go to    url=${url}
```

But I don't know if it was the best solution.

**Comment by HelioGuilherme66** [comment]
First of all, this is an Issue tracker. We have different channels for helping with questions, like the [Google Group](https://groups.google.com/group/robotframework-users) or [Slack](http://robotframework.org/#support-contact).

A browser Tab is a Window, so you have to see the [Select Window](http://robotframework.org/Selenium2Library/Selenium2Library.html#Select%20Window) and other Windows keywords like [Get Window Identifiers](http://robotframework.org/Selenium2Library/Selenium2Library.html#Get%20Window%20Identifiers).
