### ISSUE TITLE
"No Browser is open" - new Issue

### ISSUE THREAD

**Issue by mzbedat** [robotframework/SeleniumLibrary#686]
Hi,
I had selenium2Library (version 1.8) working from my robotframework tests, but suddenly I start getting the following when trying to open browser:

**Chrome**:

> [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
WebDriverException: Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"2192.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.71)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64)

To resolve it I downloaded the latest version of chrome driver.

**Firefox**:

> [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

I downloaded the geckodriver and then I got another error:

> WebDriverException: Message: Unsupported Marionette protocol version 2, required 3

My question is, what happened suddenly? what was changed?
It was working before perfectly!

Regards.

**Comment by aaltat** [comment]
#Chrome
Update to the latest Chrome driver

#Firefox
See https://github.com/robotframework/Selenium2Library/issues/676

**Comment by mzbedat** [comment]
Hi,
I was trying before getting your response and it worked for me with 
pip install selenium=2.53.6 (last one before 3.0.xx)

Thanks

**Comment by aaltat** [comment]
Is the problem solved and we can close the issue?

**Comment by mzbedat** [comment]
It's confusing... in order to make it all working you need a specific version of:
- selenium
- selenium2library
- FireFox (we are using FF43 and disabling auto upgrade)

is it a matter of time till we have Selenium 3 working with most updated version of firefox?
Need to maintain working environments all the time, a little change and its stop working...

**Comment by aaltat** [comment]
As said in the #676 there is nothing that we can do in the S2L side to solve the problem. We need to wait for the selenium and Mozilla to sort their stuff first.

As a side note, controlling the test environment us actually very good idea. And nailing down the version feels natural at least for me.

**Comment by lifeislearning** [comment]
Hi, I also got the same issue.

My version is Robot Framework 3.0.4 (Python 3.6.5 on win32).
I had set environment variable in my WIN 10 and downloaded the chromedriver to my google folder, but it's still not work. Please help me to resolve it.

**Comment by aaltat** [comment]
This is more than one year old issue and world has changed a lot in that long time. Therefore it would be best to open a new issue.
