### ISSUE TITLE
Selenium2Library fail to SELECT pop-up window

### ISSUE THREAD

**Issue by waikchiu5** [robotframework/SeleniumLibrary#687]
OS: Windows 7
Selenium Version:   2.47 and 2.53.1
Browser:   Internet Explorer
Browser Version:  11

I am using Selenium2Library to control the Browser(IE)
There is one button on the webpage. The ID is "confirm"
When the button is clicked, 3 stuff will show at the same time:
1. Alert with OK button
2. Pop-up window
3. Download bar (After closed the Alert)
![capture](https://cloud.githubusercontent.com/assets/15870347/20129286/922cdae4-a689-11e6-9453-44851935c9b9.PNG)

`Click Button          id=confirm`
`Sleep              2s`
`Alert Should Be Present                alert message`
`Sleep                            10s #the pop-up window will load some content`
`Select Window                        title=Reports`
`Sleep                                2s`
`Close Window                       #close the pop-up`

However, the robot will waiting on Select Window. Maybe still searching the target pop-up?
My pop-up will load around 15s at least. So it won't have title of pop-up window.
I cannot get the log.html. The robot won't stop.

FYI:
I found that all the Windows Keyword will disabled or cannot use after 3 stuff shown up.
Eg. Log Window Titles...../Get window Titles....

**Comment by HelioGuilherme66** [comment]
That looks like a browser specific dialog, which we can't handle with webdriver and Selenium2Library. I would not consider a valid defect in this Issue tracker.
What defect are you reporting?
Does it happen with other browsers?

If you are just asking for help, we have more appropriate channels for helping with questions, like the [Google Group](https://groups.google.com/group/robotframework-users) or [Slack](http://robotframework.org/#support-contact).

**Comment by waikchiu5** [comment]
@HelioGuilherme66 
Thanks for your reply. I figuring the root issue. 
When i clicked the button, it will show pop-up window, alert and prompt download bar
Before accept the Alert. I tried to use 
Get Window Identifiers
Get Window Names
Get Window Titles
Log Window Identifiers
Log Window Names
Log Window Titles
These keywords can work.

After 3 stuff show up.
These keywords seem enter the infinite loop. Finding the window instances ? 
I think that the download bar maybe the cause.

**Comment by aaltat** [comment]
It's because that Windows operating system dialogue blocks the interaction with the browser. That dialogue can not controlled from selenium and therefore it can not be controlled from the Selenium2Library.

If you need download the file, use cURL (or similar) for downloading or configure the browser to automatically download files and not to display the dialogue.

**Comment by aaltat** [comment]
Did you get the problem solved or do you still have a problem?

**Comment by aaltat** [comment]
Because Selenium2Library is working as it should and the problem seems to be resolved, I am closing the issue.

**Comment by waikchiu5** [comment]
@aaltat 
Sorry for my late comment. This case still cannot resolve. When i face the Download dialog, it will stop the interaction with the browser. I cannot take screenshot or log to console or pass test case.
Due to the some limit, i cannot use cURL and modify the configure of browser.

I tried some possible solution. It still stuck on it.
Such as:
Set the timeout of Test case [Timeout]
->exceeded the timeout. the Selenium2Library still waiting(It means the robot will enter infinite loop)

**Comment by aaltat** [comment]
If you can not use other tool to download the file or can not modify browser configuration then you can not download the file.

Because Selenium2Library is working as it should I am keeping the issue closed.

**Comment by waikchiu5** [comment]
Maybe i explain not clear. My test case is aim to test "Download file dialog" part but not real download. Assume the pass case is "download dialog" will show after click the download link. Then, the Selenium2Library will take a screenshot and pass the case. However, after show up the dialog. Selenium2Library will enter infinite loop.

Thank you for your comments

**Comment by aaltat** [comment]
It's because that operating system dialogue blocks the interaction with the browser. That dialogue can not controlled from selenium and therefore it can not be controlled from the Selenium2Library.

Then you need to find other libraries, to find the OS dialogue, take the screen shot and cancel the dialogue. If you live in Windows, autoIT might be good solution to control the dialogue and screenshot library to take the screen shot.

**Comment by waikchiu5** [comment]
@aaltat 
Thanks for your kindly reply.
I tested again. When i manually close the download dialogue. The robot still stopped. 
I need to manually close the browser. The test case will pass and generate the log.html

I believe that this is cannot controlled from the Selenium2Library. Do you know which parts has limit for solving this problem.
IE limited? or IEDriverServer limited? Selenium limited?

**Comment by aaltat** [comment]
I don't use IE that much and I don't have tested this scenario. But generally speaking selenium should be able to run normally after the blocking dialogue has been removed.

This feature is coming from selenium but it also could come from the browser too. I have never bothered to dig any deeper than selenium.
