### ISSUE TITLE
How can i get the value or attribute from the text box

### ISSUE THREAD

**Issue by aalwinkarthi** [robotframework/SeleniumLibrary#688]
*** Settings ***
Library           Selenium2Library
Library           OperatingSystem

*** Variables ***
${VoiceMail_Preferences_Add_Notification_SMS_Notification_SMS}    id=sms

  Log    ${VoiceMail_Preferences_Add_Notification_SMS_Notification_SMS}

It prints "id=sms"

How can i get the value or attribute of the text box

**Comment by aaltat** [comment]
By using this: http://robotframework.org/Selenium2Library/Selenium2Library.html#Get%20Element%20Attribute you get the attribute
