### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bolerap** [robotframework/SeleniumLibrary#689]
Hi Author.
I've try to install with this command `pip install robotframework-selenium2library` and tried manual install but it issue error `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n_h4_km0/robotframework-selenium2library/
`

Does it support python 3? all command above i run from virtualenv of python 3
Thanks

**Comment by aaltat** [comment]
Python 3 is not yet supported. Closing because this is duplicate of #479
