### ISSUE TITLE
CSS selector not working in Chrome

### ISSUE THREAD

**Issue by hirsivaja** [robotframework/SeleniumLibrary#691]
The following is not working in Chrome:
`Click Element    css=input[value='Sign In']`
The error produced is:

>  	POST http://127.0.0.1:58525/session/ead77b5ecc5eff116c9fb3567231f177/elements {"using": "css selector", "sessionId": "ead77b5ecc5eff116c9fb3567231f177", "value": "input[value='Sign In']"} 

> InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified (Session info: chrome=54.0.2840.99) (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.1.7601 SP1 x86_64)

The test case is working fine in Firefox and Internet Explorer.

Has the Chrome API changed in some way that the Selenium2Library is not anymore compatible?

**Comment by HelioGuilherme66** [comment]
Can you retest with an updated chromedriver? 2.25?

**Comment by hirsivaja** [comment]
> InvalidSelectorException: Message: invalid selector: An invalid or illegal selector was specified
>   (Session info: chrome=54.0.2840.99)
>   (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.1.7601 SP1 x86_64)

**Comment by aaltat** [comment]
Your selector looks like a valid one, but I don't use css that much and therefore I am not 100% sure.  If the selector works fine with some external validator or with some other browser then it would be best to raise the issue to the Google Chromedriver issue tracker.

As a workaround xpath should work fine: `xpath=//input[@value='Sign In']`

**Comment by aaltat** [comment]
Did you get the problem sorted out or do you still have a problem?

**Comment by hirsivaja** [comment]
Unfortunately I was not able to resolve the issue. With the xpath I get the following:

```
11:40:04.414 	INFO 	Clicking element 'xpath=//input[@value='Sign In']'.
11:40:04.850 	FAIL 	WebDriverException: Message: unknown error: Right-hand side of 'instanceof' is not callable
  (Session info: chrome=54.0.2840.99)
  (Driver info: chromedriver=2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf),platform=Windows NT 6.1.7601 SP1 x86_64)
	
11:40:04.851 	DEBUG 	Traceback (most recent call last):
  File "<decorator-gen-54>", line 2, in click_element
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\Selenium2Library\keywords\_element.py", line 354, in click_element
    self._element_find(locator, True, True).click()
```

**Comment by aaltat** [comment]
Please try with the latest Chrome driver.

**Comment by hirsivaja** [comment]
The result is the same with chromedriver 2.25.426923

**Comment by HelioGuilherme66** [comment]
Sometimes we need little adjustments to the XPATH expressions. Try to use a xpath validator from dev tools in your browser. I use Firepath from Firebug on Firefox.
Possible variants for your case:
`xpath=.//input[@value='Sign In']`
`xpath=.//input[.='Sign In']`
There are more, but you need to be sure your locator is working.

**Comment by hirsivaja** [comment]
The locator that Tatu gave works in the dev tools of both Chrome and FF. The test case is only working with FF. I tried those two that you suggested as well, the first one is working in dev tools but neither in the test case with Chrome

**Comment by aaltat** [comment]
The xpath is a valid one, but the error might be related to an unresolved issue in the chrome driver https://bugs.chromium.org/p/chromedriver/issues/detail?id=1388

Can you reproduce the problem with a other browser. If you can't then it would be best to report the problem Chrome driver issue tracker.

**Comment by hirsivaja** [comment]
This doesn't seem to be an issue with the Selenium2Library, but rather with the ChromeDriver. So this issue can be closed. Thanks for the help!
