### ISSUE TITLE
Get parent webelement keyword

### ISSUE THREAD

**Issue by tx3stn** [robotframework/SeleniumLibrary#699]
I have an update that I have made locally to get an element's parent that I thought I'd see if anyone had any thoughts or objects before raising a PR.

```python
    def get_parent_webelement(self, locator):
        if isinstance(locator, WebElement):
            locator_element = locator
        else:
            locator_element = self.get_webelement(locator)
        return locator_element.find_element(by="xpath", value="parent::*")
```

I'm currently using this for pages with table like data with numerous input fields, not actually in a table, and I need to be sure the fields being updated are the correct ones, which I can do by getting the parent element (which in this case is the container for the whole row), and then looking for the child fields I need in the parent. 

Happy to raise the PR with tests for this if theres no objections / anyone else will find it useful.

**Comment by aaltat** [comment]
Yes there has been and yes it could be useful. Example in #672. 

Because this is a duplicate, closing this issue.

**Comment by aaltat** [comment]
Reopened because #702 discussion

**Comment by aksenov007** [comment]
As @aaltat [requested](https://github.com/robotframework/SeleniumLibrary/pull/702#issuecomment-352174529), here is a possible acceptance test for this issue. It's the same as in the #702 and I think it is enough to describe how this keyword should work.

```
Get Parent Web Element Passing Element
    [Documentation]  Get parent web element of the element passed
    ${expected_parent}=     Get WebElement  //div[@id="div_id"]
    ${element}=    Get WebElement    //div[@id="div_id"]/a
    ${parent}=  Get Parent WebElement   ${element}
    Should be equal     ${parent}   ${expected_parent}

Get Parent Web Element Passing Locator
    [Documentation]  Get parent web element of the locator passed
    ${expected_parent}=     Get WebElement  //div[@id="div_id"]
    ${parent}=  Get Parent WebElement   //div[@id="div_id"]/a
    Should be equal     ${parent}   ${expected_parent}
```
The only case is worrying me: get parent of the `<html>` web element... Should I write a separate acceptance test for that case or not?

**Comment by aaltat** [comment]
Closing due inactivity.
