### ISSUE TITLE
Combining `Open Browser`and `Create Webdriver`keywords 

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#701]
* Take KW args in use
    * `Open Browser` is made in are where kwargs where not available from Robot Framework. The kwargs could allow creating the browser in more generic way
    * could pass the `desired_capabilities` in dictionary. Also should support other configuration options from 
 * One keyword only to handle the opening the browser
It should be possible to move many things from Create Webdriver` keyword to `Open Browser` keyword. Then we should create pubic API to register the browser/driver to S2L side, so that user could create the browser/driver in the python code as they want. 
 * See what selenium API supports
The might be some difficult scenarios with selenium API, which can not be handled with vargars and kwargs. But documenting and creating public API for registering these should be enough. 
 * Think should Open Browser keyword open always keyword or should it reuse existing browser
There is use case where the `Open Browser` keyword could do the same thing as `Go To` keyword if the browser is already open. Think how to do it. 

To better support what `Create WebDriver` keywords enables to do, it might the argument signature of the `Open Keyword` should be changed, or perhaps `Open Browser 2` keywords should be created.
Now the argument signature is:
```
| Open Browser | url | browser=firefox | alias=None | remote_url=False | desired_capabilities=None | |ff_profile_dir=None |
```
But it might better to have: 
```
| Open Browser | url | browser=chrome | alias=None | remote_url=False | desired_capabilities=None | options=None |  service_log_path=None | ff_profile_dir=None |
```

**Comment by accesslubos** [comment]
Hello! Question.
I was just experimenting with headless Chrome. Currently I add that as an argument and then I call the Create Webdriver keyword directly:
```
Call Method    ${chromeOptions}    add_argument    --headless
Create Webdriver    ${global_browserName}    chrome_options=${chromeOptions}
```
Now I noticed there is an easy option to pass in "headlesschrome" as a browser name to the Open Browser keyword which is not available with the Create Webdriver keyword. Would it be possible to combine those two/is this in scope of this ticket?
The only reason why I want to use Create Webdriver instead of Open Browser is specifying download directory and client language setup.

Let me know if I can help!

**Comment by aaltat** [comment]
The plan is to combine the keywords in such manner that `Open Browser` keyword allows more flexibility for the driver creation. More detailed information is not yet available because we haven't given any more thought for the matter. Perhaps good starting point would be to ask from the community, how they currently use the `Create Webdriver` keyword and see what possibilities the current Selenium API offers. This also might require raising the minimum required Selenium version to above 3.8.

**Comment by aaltat** [comment]
This is split into to multiple different issues and therefore I am closings this issue.
