### ISSUE TITLE
Increase the required selenium version to latest selenium 2 version

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#704]
Supporting old selenium version would require more work than we can do at the moment. 

We would actually need to run test with all those versions and decide which we support. But in the other hand we should not make changes that would break the compatibility. 

Document and announce to user group

**Comment by emanlove** [comment]
@aaltat Why force an upgrade if there is no issue nor complaints? I don't see the dependency version listed in setup.py as a statement of support but more as a minimum required version for current functionality. This was last bumped when we changed select list to use the newly added Select class and thus required a certain version.

That said looking back at the selenium 2.32 I see it was released back in April 2013. So... I could see someone saying well that really old and we should bump it up. But the problem I have with saying and actually changing to the very latest release, in this case 2.53.0, then it forces everyone to go to the very latest when some require for reason unknown to us 2.51.1 or some other "recent" release.

I am not saying no we shouldn't bump this number but I think it shouldn't be as restrictive as the very latest 2.x release (as compared to the last release 1.5 years ago), that we should pre warn the community giving plenty of notice and taking any feedback as a possibility to reverse that decision. Just saying changes like these have a lot of affect on people in many ways we don't know so they just need to be planned out.

**Comment by aaltat** [comment]
I don't like the idea, to make promise that we will guarantee that the Selenium2Library is compatible with the selenium 2.32 or greater. Specially because we do not test it. 

In the other hand, I do not want to force to use the selenium 2.53.0 or any specific version. Perhaps we should document that we test with this X.X.X (whatever that version might be) version of selenium. Also we could document that users can freely install whatever version that they want with pip, but we can not guarantee that it works. And the compatibility actually depends on the changes in the selenium API.

**Comment by pekkaklarck** [comment]
IMHO we should set version requirement to whatever we test. Users can upgrade S2L w/o upgrading dependencies if they want to.

Is there any good reason to use older se versions?

**Comment by aaltat** [comment]
There might be some reasons to get some specific browser version to work, but can not recall any such example. The reason why we usually do not it, is to allow people to setup their environments as they please and not to force the update.

**Comment by aaltat** [comment]
The Travis is setup to run acceptance test with selenium 2.53.6 and 3.0.2. I think it's good to let the community to know what was used to test the release. Also if possible avoid making changes that would break the comparability.

Things to do next:
Update the requirements.txt to install selenium 2.53.6 or greater.

Update release process to include the versions in the changes file. And in the announcement letter too.

**Comment by aaltat** [comment]
Done in #819
