### ISSUE TITLE
Remove the WebDriverMonkeyPatches

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#706]
It looks like the [WebDriverMonkeyPatches](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/webdrivermonkeypatches.py) was done to ease to conversion from SeleniumLibrary to Selenium2Library. Most likely we do not needed at all and we could use the methods from the selenium directly.

**Comment by ombre42** [comment]
I think this is a good idea. But I am pretty sure some people out there are using these methods on `_current_browser()`. So it should be clearly communicated that `get_current_window_info`, etc. is going away.

**Comment by aaltat** [comment]
I think some of the methods will stay, in some form or other, but not in there. At least the ones that will have direct counterpart in selenium side will disappear.

**Comment by emanlove** [comment]
Is there a list of what we will still have and what we will lose by removing it?

**Comment by aaltat** [comment]
Not yet, but we definitely need a one. The #708 changes the monkeypatched methods to their selenium/webdirver counter parts: 
 * get_window_handles() -> window_handles
 * get_current_url() -> current_url
 * get_page_source() -> page_source
 * get_title() -> title

Those where the easy ones. Most likely the rest will in stay in some form or other but it needs some thinking.  But before that thinking I need some sleep.

**Comment by aaltat** [comment]
Done in #708
