### ISSUE TITLE
[warn] [Capture Page Screenshot] WebDriverException: Message: docEl is null

### ISSUE THREAD

**Issue by akvilla** [robotframework/SeleniumLibrary#709]
I've wrote tests for check of PDF reports.
When I use "Wait Until Keyword Succeeds" +"Element Should Contain" the tests could fails, because the reports sometimes couldn't be completely downloaded at first try. 
Robot try to capture screenshot and in log I see warnings "WebDriverException: Message: docEl is null".

Traceback (most recent call last):
File "<decorator-gen-147>", line 2, in capture_page_screenshot
File "C:\Python27\lib\site-packages\Selenium2Library\keywords\keywordgroup.py",
               line 15, in _run_on_failure_decorator return method(*args, **kwargs)
File "C:\Python27\lib\site-packages\Selenium2Library\keywords\_screenshot.py",
               line 91, in capture_page_screenshot if not self._current_browser().get_screenshot_as_file(path):
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py",
               line 798, in get_screenshot_as_file png = self.get_screenshot_as_png()
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py",
               line 817, in get_screenshot_as_png return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py",
               line 827, in get_screenshot_as_base64 return self.execute(Command.SCREENSHOT)['value']
File "C:\Python27\lib\site-packages\Selenium2Library\webdrivermonkeypatches.py",
               line 11, in execute result = self._base_execute(driver_command, params)
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py",
               line 236, in execute self.error_handler.check_response(response)
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py",
               line 192, in check_response raise exception_class(message, screen, stacktrace)

![Screenshot](https://cloud.githubusercontent.com/assets/22197402/21004518/7d87be08-bd39-11e6-9ba2-636f00ce16e4.png)

**Comment by aaltat** [comment]
Would the `Wait Until Page Contains Element` keyword solve your problem? If not could you describe your problem better, because I don't understand what problem you are trying to solve?

**Comment by akvilla** [comment]
> Would the Wait Until Page Contains Element keyword solve your problem?

I've used this keyword and it's work fine. In this case I can refactor my tests and use the other keywords with "wait ...".

> I don't understand what problem you are trying to solve?

This issue was opened, because I couldn't find any references to the warning "WebDriverException: Message: docEl is null".
Is it expected that warning appears when I use "Wait Until Keyword Succeeds" +"Element Should Contain"?

**Comment by aaltat** [comment]
You have two errors. First one is coming from the `Page Should Contain Element` and raised ValueError. The second one coming from `Capture Page Screenshot` and raised WebdriverException.

The first on, ValueError, is normal because in that moment page doesn't contain the element you expect. The first error can be avoided by using `Wait Until Page Contains Element` and then you don't need to use `Wait Until Keyword Succeeds`.

The second error is not common and I don't have any idea why it happens. The second error tells that something went wrong with taking the screen shot from the browser. But the second problem should go away if you use the `Wait Until Page Contains Element` keyword.

**Comment by akvilla** [comment]
thanks for clarifying

**Comment by aaltat** [comment]
If you think that problem is solved, could we close the issue?

**Comment by akvilla** [comment]
Yes, thanks.
