### ISSUE TITLE
Unable to select nested iframe in an iframe

### ISSUE THREAD

**Issue by pe2mbs** [robotframework/SeleniumLibrary#711]
Current we are string a application that heavily uses iframes to get to the right elements we need to select an iframe and than select the second iframe. See the example below.
  
`<iframe id="A">`
`       ....`
`       <iframe id="B">`
`             ....`
`             <div id="C">   `
`             ....`
`       </iframe>`
`  </iframe>`

When we do 
`  Select Frame      //*[@id="A"]`
`  Select Frame      //*[@id="B"]       # Here the element cannot be found.`
`  Element Should Contain            //*[@id="C"]         Some text`

The second Select Frame fails due it cannot be found.

Possible solution: add keyword for selecting a frame from with a frame

`   Select Frame      //*[@id="A"] `
`   Select Frame from Frame      //*[@id="A"]      //*[@id="B"]`

The select frame from frame keyword should accept multiple frame ids to get the correct iframe.

**Comment by aaltat** [comment]
Could you tell which browser and selenium version you are using? Also have you tried with the different browser? Also could you tell the library version you are using? Also could you send the full stack trace from the error, use `--loglevel trace` from command line. Also if it's possible to send an example which we could also run, would be big plus.

I haven't used nested frames,  so have to some reading from the selenium API documentation.

**Comment by pe2mbs** [comment]
Here the trace of the failing second select frame:
[trace.txt](https://github.com/robotframework/Selenium2Library/files/651142/trace.txt)

Browser google chrome Version 54.0.2840.99 m
ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)

Sending a full example is problematic due our integrated test environment, The application is a Business Process Model (BPM) Flow and is based on the IBM Couch framework.

**Comment by aaltat** [comment]
That trace file does not look like trace file from Robot Framework. In the previous post, I was meaning this: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setting-log-level

**Comment by pe2mbs** [comment]
What you got is trace file with -b option from Robot Framework. And that contains the same information as the HTML version.

**Comment by aaltat** [comment]
Thank is the whole point of using the use `--loglevel trace` from command line. It increases the loglevel and displays better error message.

**Comment by aaltat** [comment]
It this still a problem or can we close the issue?

**Comment by pe2mbs** [comment]
We will not continue testing the IBM BPM application for now, so just close it. If we want to continue testing that application we will create a new issue. and create new logs.
