### ISSUE TITLE
Support returning int from `Get Matching Xpath Count`

### ISSUE THREAD

**Issue by GLMeece** [robotframework/SeleniumLibrary#715]
This "feature" has been present AFAIK since about the first check-in. I tripped up over this when attempting to add a value to the return and got a type error.

Two suggested approaches:

1. Change the documentation, per [this pull request](https://github.com/robotframework/Selenium2Library/pull/714).
2. As an optional keyword argument, allow for an `int` return (default would remain `str`). I have not included a code example/pull for that.

**Comment by aaltat** [comment]
I am happy in both ways, which way you want to go?

**Comment by GLMeece** [comment]
See my most recent [pull request](https://github.com/robotframework/Selenium2Library/pull/717). I have not added any tests for this.

**Comment by pekkaklarck** [comment]
This is included in SL 3.0, right? Notice also that we have decided to deprecate `Get Matching XPath Count` in favor of more generic `Get Matching Locator Count` (#949) and the plan is that the new keyword will always return an integer.
