### ISSUE TITLE
Consider string `False` to be false similarly as Robot Framework

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#719]
RF convenience methods for handling booleans, example 
```
| Some Keyword | False |
```
Is evaluated as False in Robot Framework standard libraries, although the argument is string and according Python it should evaluate as True. Changing the S2L to behave in similar fashion as the Robot Framework standard libraries could be useful.

More details in http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Boolean%20arguments and some discussion in #717

**Comment by aaltat** [comment]
This is done is #845

**Comment by aaltat** [comment]
The doc update is missing, reopening.

**Comment by pekkaklarck** [comment]
Here's an example from a similar docs from XML library:
http://robotframework.org/robotframework/latest/libraries/XML.html#Boolean%20arguments

The main differences in S2L compared to XML are that also string `NONE` is considered false (this will change in RF/XML too) and that same logic applies also to `None` argument, not only to booleans.

**Comment by pekkaklarck** [comment]
I don't see any reasonable use case where this could cause backwards incompatibility problems.
