### ISSUE TITLE
Enhance `Get List Items` to support returning values or labels

### ISSUE THREAD

**Issue by qitaos** [robotframework/SeleniumLibrary#722]
@aaltat 
I have a demo website http://demo.robotframework.cn/.
There is a select list, it's html code is:
![snipaste20161228_091150](https://cloud.githubusercontent.com/assets/1754412/21511671/8fd21018-ccde-11e6-824e-e383228ef2c4.png)

my case is:
![snipaste20161228_091354](https://cloud.githubusercontent.com/assets/1754412/21511673/8fd5ac3c-ccde-11e6-8c28-1973f8989809.png)

The keyword get_list_items docstring wrote it will return the values in the select list. But the result is:
![snipaste20161228_091336](https://cloud.githubusercontent.com/assets/1754412/21511672/8fd532c0-ccde-11e6-9fa1-e3fa84bf81d9.png)

I want to get the option value for "item1","item2","item3", but it returns the labels "first","second","third".
So I checked the keyword get_list_items source code: 
`

    def get_list_items(self, locator):
        """Returns the values in the select list identified by `locator`.

        Select list keywords work on both lists and combo boxes. Key attributes for
        select lists are `id` and `name`. See `introduction` for details about
        locating elements.
        """
        select, options = self._get_select_list_options(locator)
        return self._get_labels_for_options(options)
`

It wrote 'returns the values', but it return self._get_labels_for_options(options).

I change the docstring to "Returns the labels", then add a keyword for get_list_values:
`

    def get_list_values(self, locator):
        """Returns the values in the select list identified by `locator`.

        Select list keywords work on both lists and combo boxes. Key attributes for
        select lists are `id` and `name`. See `introduction` for details about
        locating elements.
        """
        select, options = self._get_select_list_options(locator)
        return self._get_values_for_options(options)

`

So this is the issue for the pr #721

**Comment by aaltat** [comment]
Ah, now I understand, thank you from the explanation.

Your need is a valid one. The only thing that I am wondering do we need a new keyword for this or would it be better to have one keyword and decide based on argument what to return. Example:
```
| ${labels1} = | Get List Items | xpath=//h1 |
| ${labels2} = | Get List Items | xpath=//h1 | label=${True} |
| ${values} = | Get List Items | xpath=//h1 | label=${False} |
| Should Be Equal | ${labels1} | ${labels2} |
```
There are quite many keywords and I don't like to raise the keyword amount. But I don't feel strongly on the matter, what do you think, or others?

Also the new functionality must be backed up with tests.

**Comment by qitaos** [comment]
I think add argument is fine too.

**Comment by qitaos** [comment]
@aaltat I made a new commit for add argument and test cases.

**Comment by aaltat** [comment]
Thank you. I am busy other stuff for few days, but next year there should be time to take a look.

**Comment by aaltat** [comment]
It was decided to make configurable to keyword return values or labels based on a new `value` argument. The keyword default functionality is backwards compatible.

**Comment by aaltat** [comment]
Done in #721

**Comment by pekkaklarck** [comment]
I think `values` is better name for the optional argument than `value`. I'll change it while doing cleanup to list related keywords and their docs in general. I'll also add a note that this argument is new in SL 3.0.
