### ISSUE TITLE
Can't locate elements which with blank suffix  in content-desc

### ISSUE THREAD

**Issue by lucyking** [robotframework/SeleniumLibrary#725]
[criteria = locator_parts[2].strip()](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/locators/elementfinder.py#L227]) will wipe space bar off at the string end, that
lead to can't locate the special element which **with blank suffix in content-desc**. 
eg:

| Keywords  | Locator |
| ------------- | ------------- |
Mobile_Click_Element  |   accessibility_id= _some_desc_\<space bar\> |

after [strip()](https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/locators/elementfinder.py#L227])'s process: 

| Keywords  | Locator |
| ------------- | ------------- |
Mobile_Click_Element  |   accessibility_id= _some_desc_ |

I've submit a PR #583 to solve this problem.
This patch using ```"``` to wrap the criteria.
If criteria has ```"``` itself, we can use accessibility_id=""value "" to deliver it's value.
Because the [[1:-1]](https://github.com/robotframework/Selenium2Library/pull/583/files#diff-b91175814577caa11b43b4be06319f57R226)  operation just strip first couple of ```"``` .

**Comment by aaltat** [comment]
I understand your problem, but the PR maybe backwards incompatible. I also like the `strip()` for locator parsing, because it eases the selector writing. 

I think a better solution would be make the strip() as configurable and by default use `strip()`. This is more work  because it it needs changing the keywords signature.

The other solution is to use xpath: ```xpath=//*[@accessibility_id= "some_desc "]```

**Comment by lucyking** [comment]
Yes,I agree with that making the strip() configurable.

**Comment by aaltat** [comment]
This is actually fixed in the 3.0.0 release: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/locators/elementfinder.py#L263
