### ISSUE TITLE
support of Python35

### ISSUE THREAD

**Issue by narenatgit** [robotframework/SeleniumLibrary#726]
Hi, 

Is selenium2Library now supported by python35? I have downloaded latest version -1.8.0 from pypi. But still I am getting the below error. If the support hasnt been extended to Python35 yet, when can we expect it? Kindly share the details. 

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from ez_setup import use_setuptools
  File "src\ez_setup.py", line 106
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax

**Comment by aaltat** [comment]
No, we don't yet support Python 3. But the next release should provide the support for Python 3. There is a fork that supports Python 3. If I recall correctly, it was this one: https://github.com/HelioGuilherme66/robotframework-selenium2library 

Because this is know issue, closing.
