### ISSUE TITLE
Add keyword "Wait Until Table Contains"

### ISSUE THREAD

**Issue by rseif** [robotframework/SeleniumLibrary#729]
I am currently using the Wait Until Page Contains without problems, but seems more appropriate to have this new keyword. Might even be faster.

**Comment by aaltat** [comment]
I don't understand what you are requesting. Could you describe the problem and solution you are proposing.

**Comment by Gaurang033** [comment]
@rseif I think you can use **Wait Until Keyword Succeeds** keyword with **Table Should Contain** keyword to achieve this.

**Comment by aaltat** [comment]
Yes one can but it's really ugly way do it.

**Comment by rseif** [comment]
@aaltat I want to be able to use Wait Until Table Contains to wait until a certain table gets updated with the value I am looking for and it should not look for that value in any other place in the page.

**Comment by rseif** [comment]
@Gaurang033 Thanks for opening my eyes to that keyword that I haven't messed with yet

**Comment by aaltat** [comment]
@rseif The request sounds reasonable. If you want it please make a pull request to fulfill the need.

**Comment by rseif** [comment]
Thanks! @aaltat I definitely see many instances where I would use it. I appreciate your help. Not too familiar with pull request, n00b here.

**Comment by aaltat** [comment]
Started reading from here: https://github.com/robotframework/Selenium2Library/blob/master/CONTRIBUTING.md

**Comment by drobota** [comment]
I'll take it

**Comment by humbienri** [comment]
Hello,
Couldn't you just determine whether the element of interest is in a table (or not) depending on the XPath/CSS selector you employ?

**Comment by aaltat** [comment]
Closing due inactivity.
