### ISSUE TITLE
Add Keyword "Element Value Should Be"

### ISSUE THREAD

**Issue by rseif** [robotframework/SeleniumLibrary#732]
Trying to assert that a certain element has a specific value (attribute). Element Should Contain does not do this. It would be bad-ass to have this keyword instead of using two or more keywords to achieve this.

**Comment by aaltat** [comment]
In practice you are looking something like this:
```
| Element Attribute Value Should Be | xpath=//div | attribute=id | value=foobar |
```
Was my assumption correct?

I usually want to read the attribute value and then use it to something totally different, like query database. Therefore I don't see the use case for the keyword. Would you be able to describe a use case when this keyword would be useful?

**Comment by rseif** [comment]
Hi @aaltat!
` |Element Attribute Value Should Be | locator=foobar_id | expected value=test | `

Something like this would suffice, I believe. The use case is to verify the value is correct on a certain element. In a particular case the html is

`<input id="foobar_id" value="test">`

**Comment by drobota** [comment]
This is implemented in pr https://github.com/robotframework/Selenium2Library/pull/570. I'll fix merge conflicts

**Comment by rseif** [comment]
@drobota Nice, Thanks!

**Comment by aaltat** [comment]
When thinking this little bit more, it might be good idea to use kwargs to verify the attribute value. Example like this:
```
|Element Attribute Value Should Be | xpath | value=test |
```
Then we would not need that many arguments and could check multiple attributes with the same keyword. Like
```
| Element Attribute Value Should Be | xpath | value=test | id=foobar_id |
```

**Comment by rseif** [comment]
Yeah it would be good to have locator instead of having it strictly xpath... Also I do not normally verify the ids because they are not attributes that change

**Comment by aaltat** [comment]
Xpath is a locator as like id or something else. Also it's more powerful than id or css, but unfortunately xpath is wery write once language.
