### ISSUE TITLE
There are random failures with acceptance test when running in  CI + Chrome

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#734]
In half of the test runs in CI, there is a failure. Most of the failures seems to be related on opening new window. The problem can not be reproduced when running tests on a local PC.

Think how to resolve the problem and take corrective actions.

**Comment by HelioGuilherme66** [comment]
We are using the default timeout of 5 seconds. Our computers are fast machines, but when on Travis (or other CI's) this may take some seconds more. I propose, we experiment, gradually increment by 1 second our Library default and test on Travis until we find a good value.

**Comment by aaltat** [comment]
I think it is because Travis has smallish delay to open a new browser and because test do not poll is the new window actually open or not. Test seem to click link to open new window and immediately check is the new window open. But the click doesn't not know that click is opening new window and it should wait such event before returning from the method.

I can now and then reproduce the problem, when I run test in a virtual machine. Next time it happens, I can preserve the logs and we can investigate the problem more better.

**Comment by aaltat** [comment]
Or perhaps #750 could solve the problem?

**Comment by aaltat** [comment]
In #756 added bunch of WUKS to wait that new window is opened and it should resolve most of the failures with problem related when opening new window in tests. There is one other problem related to the [locators](https://github.com/robotframework/Selenium2Library/tree/master/test/acceptance/locators) suite setup which is not yet resolved. For some unknown reason the acceptance test in Travis hangs on that suite setup. Fixing that needs little bit more thinking.

**Comment by pekkaklarck** [comment]
Library's own tests needing WUKS to work reliably is an indication that the library could itself get a new `Wait ...` keyword (e.g.  `Wait Until Window Opens` in this case). Even better if related keywords could be enhanced to handle waiting automatically, but that doesn't seem to be possible in this case.

**Comment by aaltat** [comment]
I agree that we should have Wait* keywords for window selection. Perhaps the best solution would enhance the current keyword to perform polling and separate Wait Until Window Is Found keyword.
