### ISSUE TITLE
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by zeing** [robotframework/SeleniumLibrary#736]
i use MacOS
my installing have 
Python 2.7.10
pip 9.0.1 from /Library/Python/2.7/site-packages (python 2.7)
robotframework (3.0.1)
robotframework-selenium2library (1.8.0)
selenium (3.0.2)

and i use example test from bitbucket 
![image](https://cloud.githubusercontent.com/assets/20161393/22214853/ce310538-e1cb-11e6-92df-ee8ab2ccbe43.png)

what's wrong for this ? 
thank you

**Comment by drobota** [comment]
Please read the following docs https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette
and https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by aaltat** [comment]
Because this is not a Selenium2Library problem, closing the issue. If you thin that this is an Selenium2Library issue, please send an update.
