### ISSUE TITLE
Click Element At Coordinates

### ISSUE THREAD

**Issue by celian-garcia** [robotframework/SeleniumLibrary#739]
Hello, 
Is the keyword **Click Element At Coordinates** really tested ? 
Because I'm facing problems using it. 

### Try # 1
When I use that
`click element at coordinates  |  css=<my_selector>  |  0  |  0`
with this code inside the keyword (default code in release and master branch)
```
# ActionChains(self._current_browser()).move_to_element_with_offset(element, xoffset, yoffset).click().perform()
ActionChains(self._current_browser()).move_to_element(element).move_by_offset(xoffset, yoffset).click().perform()
```
**It does not perform the click** (It should perform click at the middle)

### Try # 2
But when I use the same keyword with this code inside
```
ActionChains(self._current_browser()).move_to_element_with_offset(element, xoffset, yoffset).click().perform()
# ActionChains(self._current_browser()).move_to_element(element).move_by_offset(xoffset, yoffset).click().perform()
```
**It performs well the click** at the top left of the element. (As it should)

### Try # 3
Moreover, when I run this
`click element  |  css=<my_selector>`
**It's ok the click is performed at the middle** (As it should)

Thank you

**Comment by aaltat** [comment]
See here: https://github.com/robotframework/Selenium2Library/blob/master/test/acceptance/keywords/click_element_at_coordinates.robot

**Comment by celian-garcia** [comment]
Thank you for you quick answer.
I ran and passed the acceptance tests.

It is somehow related to my element...

How could I run some custom webdriver action chains from python ?  Using the driver instance from selenium2library instance.

**Comment by aaltat** [comment]
Here is small example for replacement for Open Browser keyword: https://gist.github.com/aaltat/fb8a99a28953965fe37eae77519fdd23

And there are more details in the user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-active-library-instance-from-robot-framework

**Comment by celian-garcia** [comment]
Ok I see, it means I need to instantiate myself the driver in order to access it. Am I right ?

**Comment by celian-garcia** [comment]
I found a workaround which change less things in my code and work pretty well.
```
# coding: utf8
from __future__ import unicode_literals
from robot.libraries.BuiltIn import BuiltIn
from selenium.webdriver.common.action_chains import ActionChains


class S2LExtension():
    def __init__(self):
        BuiltIn().set_library_search_order("S2LExtension")

    @staticmethod
    def click_element_at_coordinates(locator, xoffset, yoffset):
        selenium_lib = BuiltIn().get_library_instance("Selenium2Library")
        element = selenium_lib.get_webelement(locator)
        ActionChains(selenium_lib._current_browser()).move_to_element_with_offset(element, xoffset, yoffset).click().perform()
```
Does it seem acceptable for you ?

**Comment by aaltat** [comment]
I can't decide what is good for you. If it works for you, go for it. From Python point of view, it looks ok.

It could be that we need to take closer look how that action chains with coordinates work. To get it working with better with other browsers too. But this is also an application specific problem and might be difficult problem to solve.

But for now if you have a working solution, can we close this issue?

**Comment by aaltat** [comment]
Darn GitHub those Close and Comment buttons are too close. Re-opened the issue.

**Comment by celian-garcia** [comment]
Ok thank you again. Yeah let's close !
