### ISSUE TITLE
Option to provide path to webdriver and browser binaries

### ISSUE THREAD

**Issue by mohanraj-r** [robotframework/SeleniumLibrary#74]
By default, the webdriver binaries are expected to be in the system path and the browser binaries in their default locations. 

But this is not always possible. I need the flexibility to specify the path to the webdriver binaries and browser binaries. I currently do this for my selenium2 tests. I am trying to migrate them to rf-selenium2library and unable to run the tests. 

I see couple of ways to do this:

. modify rf-selenium2library itself in place (I can do it, but don't favour doing it unless the authors are ready to accept it as a fix).
. extend rf-selenium2library and over ride the open_browser keyword (being new to RF - not sure how to do this - can you help please).

Are there any other ways to have the framework accept webdriver and browser binary paths?

**Comment by ImmoWetzel** [comment]
Good Point I just struggled on this. My ChromeBrowser is not available for good reasons inside the path. Therefore 
the modify rf-selenium2library would be my favorite

**Comment by ombre42** [comment]
New in 1.5, the [Create Webdriver](http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Create%20Webdriver) keyword allows you to pass parameters to the WebDriver __init__s, which allow you to specify the path to the browser executable. If you need help in using this, post to the [Robot Framework user group](https://groups.google.com/forum/#!forum/robotframework-users).
