### ISSUE TITLE
Get Matching XPath

### ISSUE THREAD

**Issue by gvarun112** [robotframework/SeleniumLibrary#741]
Hi,

I would like to find how to get a matching XPath from the page. I mean I want to pull out all the elements on the page which doesn't have the same xpath but they have a similarity.

Example:
![image](https://cloud.githubusercontent.com/assets/17029191/22341630/8a34d418-e3bf-11e6-9c87-8745d454c787.png)

I would like to get all those into a list without hard coding them in my code. So, is there a regex match that I can use here?

**Comment by gvarun112** [comment]
@ombre42 Can you please have a look at this?

**Comment by ombre42** [comment]
You can use regular expressions in XPath 2.0, but Selenium only supports XPath 1.0. But there is `starts-with`. Try:
```
@{elems}    Get Webelements    //*[starts-with(@id, 'combobox-')]
```

**Comment by gvarun112** [comment]
Works like a charm! Thank you so much.

**Comment by gvarun112** [comment]
It returns elements like this:

@{GetAllDropdowns} = [ <selenium.webdriver.remote.webelement.WebElement (session="fc79046d5827e39be37b3b5468eaa033", element="0.4665817713304947-2")> | <selenium.webdriver.remote.webelement.WebElement (session="fc79046d58...

Am I doing something wrong here?

**Comment by gvarun112** [comment]
@aaltat  Can you please re-open this for me?

**Comment by aaltat** [comment]
Those are selenium web elements: http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.remote.webelement and keyword is working correctly.

Could you explain what you want to do and then perhaps we can help you better.

**Comment by gvarun112** [comment]
Thank you @aaltat for re-opening this issue for me.

All I am trying here to do is, get all the Dropdown elements from the website and click them one by one. All the Dropdowns have the XPATH like `//*[@id="combobox-1037"]` as I mentioned in my issue.

The number 1037 changes for every Dropdown.

**Comment by aaltat** [comment]
Please see http://robotframework.org/Selenium2Library/Selenium2Library.html#Select%20From%20List and it variants

**Comment by gvarun112** [comment]
Select From List is a little different than what I am looking for here. Is there anyway I can actually get all the XPATH's on a webpage that match a format? Like a regex or something that could help here?

This is the snippet I am trying here.

```
@{GetAllDropdowns}    get webelements  //*[starts-with(@id, 'ext-gen')]
    : FOR  ${item}  in  ${GetAllDropdowns}
    \   select from list  ${item}
    \   click element  ${item}
    \   wait until element is visible  //*[@id="boundlist-1113-listEl"]/ul/li[1]    ${DELAY}
    \   click element  //*[@id="boundlist-1113-listEl"]/ul/li[1]
```
![image](https://cloud.githubusercontent.com/assets/17029191/22347300/78635500-e3d5-11e6-9d59-c2fb0b206f36.png)

**Comment by ombre42** [comment]
In for loops, you need to tell robot to expand sequences (lists). Use @
```
    : FOR  ${item}  in  @{GetAllDropdowns}
```

**Comment by ombre42** [comment]
If you are uncomfortable working with WebElements, then you could fetch the `id`s and use that. This is what I would do if aiming to avoid writing in Python:
```
@{GetAllDropdowns}    get webelements  //*[starts-with(@id, 'ext-gen')]
@{ids}    Evaluate    [elem.get_attribute('id') for elem in $GetAllDropdowns]
```

If performance is a concern, then you could use `Execute Javascript` to grab all of the `id`s and return an array back to Robot.

**Comment by gvarun112** [comment]
Thank you @ombre42 ! This helps a lot to me.. I am working on an ExtJS Application and this is the reason I have such issues. I will try implementing `Execute Javascript`.

**Comment by gvarun112** [comment]
Hi @ombre42 & @aaltat ,

This is what I have done here:

```
`execute javascript  document.querySelectorAll('[id^=combobox] [id$=inputEl]')[0].click();
    
capture page screenshot
    
sleep  4s
    
execute javascript  document.querySelectorAll('[id^=boundlist] [id$=listEl]')[2].click();`
```

The first Execute Javascript command will click on the Dropdown (this is working fine)
The second Javascript command in the above code is to click the 2nd element from the dropdown 

The XPATH for the dropdown elements are as follows:
`(XPATH - //*[@id="boundlist-1068-listEl"]/ul/li[2])`

The number (1068) in the XPATH changes for every session. That is the reason I am using starts with (id^) and ends with ($=) here. I am unable to figure out how to append the \ul\li[2] to the Javascript command.

I have also tried something like this: (which did not work)

`execute javascript  document.querySelectorAll('[id^=boundlist] [id$=listEl]\ul\li')[2].click();`

Is there a way for us to get this done?

**Comment by aaltat** [comment]
I don't understand what you want to do. I see that you have some sort of solution in mind but that doesn't explain what you want to do.

**Comment by gvarun112** [comment]
Hey @aaltat , I just updated my previous comment if that makes more sense?

**Comment by aaltat** [comment]
No, not really, because you are explaining a solution. Explain what is the problem you want to solve.

**Comment by gvarun112** [comment]
All I want to do here is, click on the drop-down and then click on one of the drop-down elements and check if the data changes on the page.

**Comment by aaltat** [comment]
And what prevents you to use: http://robotframework.org/Selenium2Library/Selenium2Library.html#Select%20From%20List and http://robotframework.org/Selenium2Library/Selenium2Library.html#Wait%20Until%20Page%20Contains keywords?

**Comment by gvarun112** [comment]
The Web application that I am testing here is an ExtJS framework. Select from list won't work on it because, the drop-downs in ExtJS are not Select elements. It's a separate div element which appears like this:

![image](https://cloud.githubusercontent.com/assets/17029191/22429504/d6530d3a-e6d8-11e6-99c7-28cdd14e45ea.png)

**Comment by gvarun112** [comment]
I'm looking for a dynamic xpath to use as described here: http://stackoverflow.com/questions/39319847/java-selenium-find-element-with-xpath

But, I am looking for that in Robot.

**Comment by aaltat** [comment]
Is there a reason why you can't click on the element that opens the dropdown and then wait + click on a element based on it's text in the dropdown list?

**Comment by gvarun112** [comment]
The text is not going to be constant across all the drop-down's in the application. I will have to go by the index number to test this in an effective manner.

**Comment by drobota** [comment]
What do you mean under different text? Do you need test under different localizations ? Or you need to select different items so than you can rely on text and create custom keyword f.e.
```
Select From Menu 
    [Arguments]    ${item}  // item is element test 
    Click Element    xpath=//div[@id='boundless-1068-listE1']
    Wait Until Element Is Visible    xpath=//li[@role='option' and .='${item}']   10
    Click Element   xpath=//li[@role='option' and .='${item}']
```
Usage  
```
Select From Menu   item1 
Select From Menu   another item  
```

**Comment by gvarun112** [comment]
@drobota , the problem here is the number which comes in the selector id is not constant. It changes for every session and hence cannot be hard coded to the code.

boundlist-1068-listEl  -- 1068 here is for this session. It changes the next session.

Please have a look at this:
http://stackoverflow.com/questions/31864953/extjs-test-automation-using-selenium-webdriver

**Comment by aaltat** [comment]
That it not a problem and is actually quite typical problem. But @drobota is in right track. Can you tell what is constant and could identify the element correctly? it can be also something in above or below in the DOM? Is the class attributes example always the same?

**Comment by drobota** [comment]
This is only about correct locator which will work every time. If you have an issue with that you may suggest for your developers to add specific data attributes which will help you to locate correct elements on the page if usual classes or ids are dynamic.

**Comment by gvarun112** [comment]
@drobota @aaltat Thank you so much for all the help!

So in this application, all the XPATH or ID attributes have a number associated to them which are dynamic. That was the reason I was looking for something like 

`querySelectorAll('[id^=boundlist] [id$=listEl]')`

Because, this will eliminate the need of recognizing the numbers in the identifiers.

Now, the problem here is, after I get the elements from the above querySelector command, I need to append an /ul/li[something] to navigate thru the list of elements in the drop-down.

**Comment by drobota** [comment]
I see here 2 solutions:
1) Use javascript to locate element and set uniq data attribute/class/id  to it and then use it in locator.
2) `'[id^=boundlist] [id$=listEl]'` is common css selector but you can convert into xpath and use it 
'[id^=boundlist] [id$=listEl]' is  `xpath=//*[contains(@id, 'boundlist')//*[contains(@id, 'listEl')]`

f.e. code will look like 
```
Select From Menu 
    [Arguments]    ${item}  // item is element text 
    ${menu_locator}=   Set Variable  xpath=//*[contains(@id, 'boundlist')//*[contains(@id, 'listEl')]
    ${item_locator}=   Set Variable    ${menu_locator}//li[@role='option' and .='${item}']
    Click Element       ${menu_locator}
    Wait Until Element Is Visible    ${item_locator}   10
    Click Element   ${item_locator}
```

**Comment by gvarun112** [comment]
@drobota Thank you for this. I will give it a try and let you know how it goes. Looks like a potential solution to me! 👍

**Comment by aaltat** [comment]
Did you get the problem solved?

**Comment by gvarun112** [comment]
Not yet. @aaltat .. I'm working on something higher in priority. I will post it here and let you know how it goes when I do it.

**Comment by aaltat** [comment]
Ah, sorry. I thought yeah meant that issue is solved.

**Comment by aaltat** [comment]
Did you get the problem solved?

**Comment by aaltat** [comment]
Closing due inactivity

**Comment by thamizh1407** [comment]
is there any npm package or git repository to get the relative xpath in which we can get the xpath in chrome dev tool ?
