### ISSUE TITLE
How to check attribute value should be in element

### ISSUE THREAD

**Issue by zeing** [robotframework/SeleniumLibrary#755]
i want to check value of attribute in any element 

**Example** 
i want to check attribute "tittle" that should be equal "Point"  

`<img src="/coin_pre-01.png" title="Point" style="width:20px; height:20px; float:left; margin:-2px 5px;">
`

i try to get value(Point) from title

`${text} =  Get element attribute xpath=//div[@id='divGridpromotion']/div[1]//div[@class='caption']/span[4]/div[2]/img@title
`

${text} will be "Point"

but i can't check  by using "Element Text Should Be " because it require argument ( location , expect)

How to compare value of attribute in element with expect value ?
thank you

**Comment by aaltat** [comment]
Use http://robotframework.org/Selenium2Library/Selenium2Library.html#Get%20Element%20Attribute to get the attribute value and then use one of the BuiltIn library `Should Be Equal*` keywords to verify that the value is correct.

**Comment by zeing** [comment]
i get it ,thank you very much.
