### ISSUE TITLE
Keyword to wait that windows is open

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#757]
Many cases, like #756, the selecting of a window may fail because the windows is not yet open. Then a common solution is to do this: 
```
| Wait Until Keyword Succeeds | 5 | 1 | Select Window | window_title |
```
It would be better to create keyword that allow to wait a window is opened, example:
```
| Wait Until Window Is Open | window_title | timeout |
| Select Window | window_title |
```
Other option would be to enhance the `Select Window` to perform polling and add a timeout 
```
| Select Window | window_title | timeout |
```

**Comment by pekkaklarck** [comment]
I initially thought we should add `Wait Until Window Is Open`, but having just one keyword for waiting and selecting the window actually sounds even better. Adding optional timeout to `Select Window` might thus be a good idea. I guess it should work so that if no timeout is given there's no polling either. Would similar timeout functionality be useful also with other keywords?

**Comment by aaltat** [comment]
For me also wait and select window sounds more realistic use case.

Having similar functionality could be useful in other keywords too. At least I usually build my UI facing libraries in such way that they poll and assert. Also if time out is zero it only performs assert, but I rarely use that because polling is usually the best option to build stable test.

There is at least one down side, if one is writing test by using `Page Should *` keywords, then test are not that readable than `Wait Until *` keywords. I actually used, with my poll and assert keywords, a `Verify *` prefix. For me it made understanding what the keyword does easier and it made writing the test more fluent.

**Comment by pekkaklarck** [comment]
I agree. I actually think that `Should` keywords should rather get `Wait` counterparts than have an optional timeout. Like we already have `Page Should Contain` and `Wait Until Page Contains`. Having a timeout would be more useful in keywords that do something like `Click Button    example    timeout=2s`.
