### ISSUE TITLE
Code loaded by Execute Javascript file.js doesn't works, but loaded in a webpage as a normal script, it works

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#758]
i have a index.js file (attached).
this index.js file works normally if loaded as script hosted on a webserver.
like this.

<!DOCTYPE html>
<html>
    <head>
        <script src="index.js"></script>
    </head>
    <body>
    </body>
</html>

due this javascript creates some instances of javascript "classes", i can access the object .

![image](https://cloud.githubusercontent.com/assets/2149815/22779956/0992d6d0-eebd-11e6-9e52-dc76f7058ab8.png)

i used Execute Javascript with other javascript file, without problem.

the attached javascript has something strange, but if used on a normal browser with a normal web server, it works.

if you use

![image](https://cloud.githubusercontent.com/assets/2149815/22780353/b913a0a2-eebe-11e6-964e-045af69da451.png)

in robot framework,

there is no javascript error in console,

javascript looks loaded,

but instances are not created.

![image](https://cloud.githubusercontent.com/assets/2149815/22780314/9d631cf2-eebe-11e6-8000-0989e2a76383.png)

this is my test environment : 

windows 7
python 2.7.11
selenium 3.0.2
robotframework-selenium2library 1.8.0
robotframework 3.0.1

so i think there is something strange with Execute Javascript.

[index.zip](https://github.com/robotframework/Selenium2Library/files/763398/index.zip)

**Comment by aaltat** [comment]
If you execute the JavaScript from the console, does it work then properly?

**Comment by andreabisello** [comment]
@aaltat 

from the same browser and the same console,

if i open chrome and with chrome i open a webpage that include the <script> yes,

if i open chrome with robot framework opening a blank webpage and Execute Javascript index.js, no.

i tried to put an

alert("hello") at the end of the javascript,

robot framework raise the hello ,

so the javascript is really included,

but i don't understand why there are two different behaviour if included as a script or included by robotframework.

i hope to have answered your question.

**Comment by aaltat** [comment]
Because those two things are not, always, the same thing. Execute JavaScript is a same thing as you would open the browser console and copy/paste the js file content to the console. If you do the above, do you get the results you did expected? If the results are not what you did except, then the problem is not with the Execute JavaScript keyword

**Comment by andreabisello** [comment]
@aaltat 

copy-pasting the js in the browser opened by robot framework,

the code works.

![image](https://cloud.githubusercontent.com/assets/2149815/22818976/342e938a-ef70-11e6-97f7-452e24a57d57.png)

**Comment by aaltat** [comment]
The keyword reads the code from the file and then executes the JavaScript by using the selenium API:  http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.execute_script.

Keyword should log the file content during the execution time, could you check that the code is still the same as in the file?

If it's same then next logical option would be try the same with selenium only. Are you able to try that one out?

**Comment by andreabisello** [comment]
@aaltat sure, i will try monday. The code is on my office pc.
thanks.,

**Comment by andreabisello** [comment]
@aaltat the log (attached) contains the javascript.

if i copy paste the javascript from log.html in the browser console, it works.

but for the browser, it doen't works.

i will try using selenium .

[log.zip](https://github.com/robotframework/Selenium2Library/files/770870/log.zip)

**Comment by aaltat** [comment]
Reading the file was a long shot but was good to check out.

**Comment by andreabisello** [comment]
@aaltat reading http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.execute_script and http://stackoverflow.com/questions/23228247/selenium-webdriver-execute-script-cant-execute-custom-methods-and-external-jav it looks like driver.execute_javascript cannot load external .js file.

taking a look at selenium2library code, here, https://github.com/robotframework/Selenium2Library/blob/931f2fde47b0ead97956bb593b66ad74d3bc89e0/src/Selenium2Library/keywords/javascript.py , i understand that robot framework will read the javascript from the file and then execute as it was a string.

so i made a minimal version of the read file

![image](https://cloud.githubusercontent.com/assets/2149815/22934888/ecb8ff54-f2d0-11e6-895e-02848d519861.png)

with test.js that contains only a simply var.

![image](https://cloud.githubusercontent.com/assets/2149815/22934906/ff790788-f2d0-11e6-9549-0772c9bf727b.png)

the execution of the selenium works,

but i obtain a similar problem of the original issue : 

![image](https://cloud.githubusercontent.com/assets/2149815/22934932/19080d48-f2d1-11e6-8f17-6f9f6f1f2865.png)


so i tried to use execute_javascript , but i think i'm not able to use it, due this example doesn't work again.

![image](https://cloud.githubusercontent.com/assets/2149815/22935069/9395889c-f2d1-11e6-904c-5cee14ed7769.png)

**Comment by aaltat** [comment]
Did you happen to try http://selenium-python.readthedocs.io/api.html?highlight=javascript#selenium.webdriver.remote.webdriver.WebDriver.execute_async_script ?

The example show that problem is a limitation on the selenium side and not on the Selenium2Library side. And therefore there is nothing that we could do in the S2L to help you to overcome the problem. If you want you could raise a similar issue to the selenium[1] side and see if they can provide help on your problem.

[1] https://github.com/SeleniumHQ/selenium

**Comment by aaltat** [comment]
But because this is not a problem with Selenium2Library and is a limitation or a bug in the selenium side, I am closing the issue.

If you feel differently, send an update.

**Comment by andreabisello** [comment]
You are right.

Thanks aatu:)

Il 15 Feb 2017 17:31, "Tatu Aalto" <notifications@github.com> ha scritto:
