### ISSUE TITLE
Change link in help `Get Alert Message` to `Dismiss Alert`

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#759]
Current help for `Get Alert Message` includes a link to itself. This should be changed to other Alert closing keyword, like for example, [Dismiss Alert](http://robotframework.org/Selenium2Library/Selenium2Library.html#Dismiss%20Alert).

> **Get Alert Message**    dismiss=True	
Returns the text of current JavaScript alert.
By default the current JavaScript alert will be dismissed. This keyword will fail if no alert is present. Note that following keywords will fail unless the alert is dismissed by this keyword or another like [Get Alert Message](http://robotframework.org/Selenium2Library/Selenium2Library.html#Get%20Alert%20Message).

**Comment by aaltat** [comment]
True, would you mind sending a PR to fix this.
