### ISSUE TITLE
Support Call Selenium API and SeleniumLibrary/RC support

### ISSUE THREAD

**Issue by daluu** [robotframework/SeleniumLibrary#76]
I haven't been following this project lately but recall that (initially at least) not all the keywords from SeleniumLibrary are supported.

It just occurred to me that we can better provide support for them now, and it's worth consideration for users to migrate over from SeleniumLibrary to Selenium2Library w/o having to make considerable changes to their tests, at least initially (for migration).

This issue is for the Call Selenium API keyword to be supported in this library as well as any other applicable unsupported SeleniumLibrary keywords.

Here's some options for supporting them:

Using the new server-side WebDriverBackedSelenium feature that should supposedly be available to Python.

http://seleniumhq.wordpress.com/2012/02/08/announcing-selenium-2-19-the-prancing-unicorn-release/

Another alternative option if that doesn't work out too well is to emulate/implement WebDriverBackedSelenium ourselves to replicate the needed functionality. I did some work on that for PHP already, before the server-side WebDriverBackedSelenium was made available. It could be adapted here for Python. And with this approach call to SeleniumLibrary keyword that's not available in Selenium2Library would go to these new emulated keyword methods, and Call Selenium API keyword could internally call these as well.

https://github.com/daluu/php-webdriver-bindings/blob/master/phpwebdriver/WebDriverBackedSelenium.php

And also regarding Call Selenium API keyword, if a native WebDriver approach (or Selenium2Library keyword) is available, then the keyword should call that, else fall back to using WebDriverBackedSelenium approach.

**Comment by emanlove** [comment]
@daluu I don't see us implementing this.  If there is a specific Selenium functionality or set of functionality we don't currently implement we can focus on those.
