### ISSUE TITLE
No browser is open and WebDriverException

### ISSUE THREAD

**Issue by imdanielalves** [robotframework/SeleniumLibrary#766]
Hi,

I can not solve this problem:

ommand: python.exe -m robot.run -P C:\Users\Daniel Bezerra\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Selenium2Library --listener C:\Users\DANIEL~1\AppData\Local\Temp\RobotTempDir1406197233307818880\TestRunnerAgent.py:57876:False -s RobotTest.Robotframework.Acceptance.Test_Case_1 C:\Users\Daniel Bezerra\workspace\RobotTest
Suite Executor: null
==============================================================================
RobotTest                                                                     
==============================================================================
RobotTest.Robotframework                                                      
==============================================================================
RobotTest.Robotframework.Acceptance                                           
==============================================================================
RobotTest.Robotframework.Acceptance.Test Case 1 :: A resource file containi...
==============================================================================
Check out google dot com                                              C:\Users\Daniel Bezerra\AppData\Local\Programs\Python\Python36-32\lib\runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
------------------------------------------------------------------------------
RobotTest.Robotframework.Acceptance.Test Case 1 :: A resource file... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest.Robotframework.Acceptance                                   | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest.Robotframework                                              | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest                                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\Daniel Bezerra\workspace\RobotTest\output.xml
Log:     C:\Users\Daniel Bezerra\workspace\RobotTest\log.html
Report:  C:\Users\Daniel Bezerra\workspace\RobotTest\report.html
Exception ignored in: <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x03CD5C10>>
Traceback (most recent call last):
  File "C:\Users\Daniel Bezerra\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 173, in __del__
    self.stop()
  File "C:\Users\Daniel Bezerra\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\common\service.py", line 145, in stop
    if self.process is None:
AttributeError: 'Service' object has no attribute 'process'

Can someone help me?

**Comment by aaltat** [comment]
I think you have several issues

1) Selenium2Library doesn't yet support Python 3, only Python 2 is supported. Release 2.0 will support Python 3.
2) It seems that you are using Firefox to launch your test. Unfortunately selenium support for Firefox is limited and it would be better to use other browser, example Chrome.
3) It looks like you are using RIDE to launch your test, could you next time run the test from command line.

**Comment by imdanielalves** [comment]
Hello, I'm using RED in eclipse.
I changed the version of Python from 3.0.2 to version 2.7.13.

I also switched to the gc browser. But I still can not open the browser. The error now is as follows;

Command: C:\Python27\python.exe -m robot.run -P C:\Users\Daniel Bezerra\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Selenium2Library --listener C:\Users\DANIEL~1\AppData\Local\Temp\RobotTempDir1849057714206127568\TestRunnerAgent.py:50127:False C:\Users\Daniel Bezerra\workspace\RobotTest
Suite Executor: Robot Framework 3.0.2 (Python 2.7.13 on win32)
==============================================================================
RobotTest                                                                     
==============================================================================
RobotTest.Robotframework                                                      
==============================================================================
RobotTest.Robotframework.Acceptance                                           
==============================================================================
RobotTest.Robotframework.Acceptance.Test Case 1 :: A resource file containi...
==============================================================================
Check out google dot com                                              [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
------------------------------------------------------------------------------
RobotTest.Robotframework.Acceptance.Test Case 1 :: A resource file... | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest.Robotframework.Acceptance                                   | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest.Robotframework                                              | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
RobotTest                                                             | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\Daniel Bezerra\workspace\RobotTest\output.xml
Log:     C:\Users\Daniel Bezerra\workspace\RobotTest\log.html
Report:  C:\Users\Daniel Bezerra\workspace\RobotTest\report.html
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x033B1E30>> ignored

**Comment by HelioGuilherme66** [comment]
Well, you should really have used the command line to better see the errors.
This is your problem:
`WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

I am closing this, since it is not Selenium2Library issue.
