### ISSUE TITLE
How i can get text in p tag of html

### ISSUE THREAD

**Issue by zeing** [robotframework/SeleniumLibrary#768]
i can't get text in p tag by getText of selenium2library

`<p id="pProductinfo" class="productdetail">NEW BALANCE WR996GW US6</p>`

i want to get

>  NEW BALANCE WR996GW US6

i use  `${PRODUCT INFO}=  Get Text   //*[@id="pProductinfo"]`

but i can't get it 

can you help me ? 

thank you

**Comment by aaltat** [comment]
The most common reason for this type of error is that the selector is not unique. Please check the selector, example like this: http://stackoverflow.com/questions/5665307/how-to-search-dom-elements-using-xpath-or-css-selectors-in-chrome-developer-tool

**Comment by zeing** [comment]
i think it is unique . i try many ways 
and i think in one page it has id  only one e.x. id pProductinfo 
i try by selector by id , xpath  thoroughly

**Comment by zeing** [comment]
okay i will try again

**Comment by zeing** [comment]
i try in dev chrome 
![image](https://cloud.githubusercontent.com/assets/20161393/23338636/d6a3f720-fc42-11e6-96e2-ab94235121b5.png)
it  get value

**Comment by aaltat** [comment]
Other common reason is that the element is not visible. In that case selenium will always return empty string, even the element contains a text.

Other common reason is that you have a dynamic web application and you read the element text before the text is in the page. Or it could be other issues related to dynamic web applications.

But could you better describe what actually happens in your test case, example write small example of the part that fails. Even better if someone else could run the example too.

**Comment by aaltat** [comment]
Do you still think this is a problem in the Selenium2Library or can we close the issue?

**Comment by zeing** [comment]
okay you can set to close state. thank you
On Mar 3, 2560 BE, at 2:21 PM, Tatu Aalto <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you still think this is a problem in the Selenium2Library or can we close the issue?
