### ISSUE TITLE
Print locator of invisible element in the error

### ISSUE THREAD

**Issue by php-coder** [robotframework/SeleniumLibrary#769]
I'm running RobotFramework test in the Travis CI and it fails:
```
Catalog price should reject invalid values :: Verify that fields w... | FAIL |
Several failures occurred:
1) You may only interact with visible elements
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'testing-gce-221b369a-a72a-4586-b314-3521d80c3cb3', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-103-generic', java.version: '1.8.0_111'
Driver info: driver.version: unknown
2) You may only interact with visible elements
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'testing-gce-221b369a-a72a-4586-b314-3521d80c3cb3', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-103-generic', java.version: '1.8.0_111'
Driver info: driver.version: unknown
```
As you can see, there is not so much useful information because I don't see which exactly element is  invisible.

If it's possible, could you include also element's location in the error message?

**Comment by aaltat** [comment]
That error message comes directly from selenium and Selenium2Library cannot control the error message. You could run the test with ```--loglevel trace``` set from command line and you should see more details in the log.html

**Comment by php-coder** [comment]
In Java it is`ElementNotVisibleException` that could be caught and additional message printed. Does Python library has such exception?

Or if it doesn't have type or it's not an exception, we could test the error message for a specific pattern and print more information. WDYT?

**Comment by php-coder** [comment]
>You could run the test with --loglevel trace set from command line and you should see more details in the log.html

I don't have access to `log.html` because build happens on CI system. That's why I'd like to have a more detailed error message.

**Comment by aaltat** [comment]
Then you should get better access to the CI system. Without the log.html it's really hard to know which keyword did fail and without of the ```--loglevel trace``` set, it's impossible to know where in the source code error did happen. If you don't have access to those details, debugging the reason of the failure is really difficult.

**Comment by php-coder** [comment]
In this particular case, element locator would be enough to me for debugging.

**Comment by aaltat** [comment]
What you see in the error message is what you get in Python. When exception is raised, it's up to the raiser decide what information is included in the error message. There might be way to configure the error message from the selenium side, when the driver instance is created, but I don't know does that actually exist. Please read the selenium documentation for more details: https://seleniumhq.github.io/selenium/docs/api/py/api.html

**Comment by aaltat** [comment]
Element locator is visible in the log.html file when ```--loglevel trace``` set.

**Comment by aaltat** [comment]
Do you still think that this is a problem in the Selenium2Library or can we close the issue?

**Comment by php-coder** [comment]
Yes, I still think that UX for the such cases could be improved.

**Comment by aaltat** [comment]
In which way you would like to improve the what we log in the console?

**Comment by php-coder** [comment]
Element locator could be injected into the message itelf
```
1) You may only interact with visible elements (Keyword: Get Text Arguments: id=my-element)
```
or showed later:
```
1) You may only interact with visible elements
Keyword: Get Text
Arguments: id=my-element
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'testing-gce-221b369a-a72a-4586-b314-3521d80c3cb3', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-103-generic', java.version: '1.8.0_111'
Driver info: driver.version: unknown
```

**Comment by aaltat** [comment]
Because the error message comes directly from selenium side, it would be better to request the change from the selenium side: https://github.com/SeleniumHQ/selenium

I know that it would be possible also the make the change in our code base, but that would require putting lot of try/expect and overwriting error message from the selenium side. And that is not a good idea. Also the information is already in the log.html message. Therefore decided to not to fix this issue.

**Comment by php-coder** [comment]
Could you look at this once again? We had [a conversation in the upstream](https://github.com/SeleniumHQ/selenium/issues/3917#issuecomment-307068567) and it turned out that it's mostly impossible to put data about element to an error message on so deep level because they have only an element and don't have information about which locator was used to find it.

**Comment by aaltat** [comment]
I think the this information is best kept in the log file. But could you describe me a use case where having the xpath in the error message is useful in way where one does not need a access to the log file.

**Comment by php-coder** [comment]
Even if we have a log, in the trivial cases I wouldn't need to inspect it if error message have all relevant information.

In other situations, when we don't have access to the log it will be super helpful.

**Comment by aaltat** [comment]
I haven't found a such trivial case where seeing a locator could pin point a reason for the failure. At least I have to see what keyword did fail, in which context keyword did fail (same locator and​/or keyword may be used many times in the same test) and I need to investigate the SUT state too. All this information is available in the `log.html`. Also one should always have access to the Robot Framework results, having such a thing is quite big limitation.

That being said, there are other ways to get the information you want to the console. You could use Robot Framework listener API, version 2, `end_keyword` method [1] to listen Selenium2Library keywords. If keyword fails you could log the locator argument where ever you want. In this way you don't have depend on Selenium2Library to make the change and you will get universal solution. Would this suite for your needs?

[1] http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-version-2

**Comment by aaltat** [comment]
Closing due inactivity. If you think this is a problem, please provide details and we can consider opening the issue.
