### ISSUE TITLE
Add copyrights back to the repository

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#772]
The S2L is based on the work of the original SeleniumLibrary and it it seems that the copyrights where removed at some point. Add the copyrights back.

**Comment by pekkaklarck** [comment]
Should also include copyrights of the original S2L team and decide what copyrights we want to have for the future work. For the latter I propose Robot Framework Foundation, for the former we probably need to consult the orig team directly.

**Comment by pekkaklarck** [comment]
I noticed there still was COPYRIGHT.txt in the project root and created PR #828 to update it. The most important change was updating copyright holders to this list:

```
Copyright 2008-2011 Nokia Networks
Copyright 2011-2016 Ryan Topac, Ed Manlove and contributors
Copyright 2016-     Robot Framework Foundation
```

As you can see, I explicitly mentioned only the original S2L developers @rtomac and @emanlove. Should we also include @zephraph? Any other comments from others? Let us know at least if you don't want yourself to be listed!

Once we agree what's the correct listing, we still need to add this copyright notice back to all source files.

**Comment by pekkaklarck** [comment]
Just noticed that Jeremy Johnson i.e. @j1z0 is also listed as author in setup.py. Should he be listed also in copyrights in the future?

**Comment by just-be-dev** [comment]
You can include me if you want, but it's up to you really.
