### ISSUE TITLE
Select two deferent elements on the Browser.

### ISSUE THREAD

**Issue by Nightlord851108** [robotframework/SeleniumLibrary#773]
I want to test an event that while I select two deferent element, some buttons on the page should be disable. 
However, I don't know how to click two elements at same time...
Could I hold Control key and click the second element?

**Comment by aaltat** [comment]
I don't quite understand what you want. Could you explain what is the user scenario you are trying to test. Perhaps show some screenshots or written some pseudo code is useful in your case.

**Comment by aaltat** [comment]
I am closing this due inactivity. If you are still having a problem, please provide more details and we will consider opening the issue.
