### ISSUE TITLE
Expose selenium WebElement.value_of_css_property() to Selenium2Library

### ISSUE THREAD

**Issue by AlexanderWhitestone** [robotframework/SeleniumLibrary#774]
This method isn't used in any keywords in Selenium2Library right now.

There are good keywords for checking CSS values written here:
https://github.com/axon-id/Selenium2LibraryExtension/blob/master/src/Selenium2LibraryExtension/keywords/__init__.py

**Comment by aaltat** [comment]
Closing due inactivity. If there is an interest to me this happen please open new issue and preferably create also a PR
