### ISSUE TITLE
Is Set Suite variable going away in Selenium2? 

### ISSUE THREAD

**Issue by hemakannan** [robotframework/SeleniumLibrary#78]
I didnot see this keyword in the Selenium2 documentation. please advice.

Thank You
hema

**Comment by stevejefferies** [comment]
"Set Suite Variable is a BuiltIn library keyword not a Selenium2Library keyword - it is documented here - http://robotframework.googlecode.com/hg/doc/libraries/BuiltIn.html?r=2.7.3#Set%20Suite%20Variable

**Comment by hemakannan** [comment]
oops sorry was looking in the wrong place. Thank you Steve.

Hema
