### ISSUE TITLE
Python package install does not install latest selenium2library that supports gecko

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/SeleniumLibrary#785]
Python Package install does not download latest version using -U upgrade option.
pip installation does not install latest version of robotframework-selenium2library that supports selenium 3.3 and hence geckodriver latest that supports webdriver specification is not working with selenium2library

**Comment by aaltat** [comment]
The latest Selenium2Library release is in PyPi, which is 1.8.0. If you are having problems PyPi or pip, I would suggest consulting PyPi or pip documentation.

One workaround is to specify the in the pip command:
`pip install robotframework-selenium2library==1.8.0`

**Comment by aaltat** [comment]
Because pip or PyPi problems are not Selenium2Library problems, closing issue.
