### ISSUE TITLE
Robotframework 3.0.2 hangs when opening a Microsoft Edge browser instance

### ISSUE THREAD

**Issue by neospin** [robotframework/SeleniumLibrary#789]
Using RF 3.0.2 and Microsoft webdriver 10586. I can call it through python calling selenium and it works (assuming they do not use selenium2library). But in RF "Open Browser" would hang. And if I change it to "Create Webdriver" then "GoTo", the first instruction "Create Webdriver" would hang. 

In both cases Edge window shows up with default home page. And nothing happens.

**Comment by aaltat** [comment]
Would you check that the EdgeDriver you are using, is compatible with the Edge version you are using. More details in here: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by neospin** [comment]
Edge version is 13.10586, Microsoft webdriver was downloaded from the url you have, and it is version 10586

**Comment by aaltat** [comment]
Would you be able to create a simple example, which demonstrates the problem and also we are able to execute? Also could you run the simple example with `--loglevel trace` and `--debugfile debug.log` and share the `log.html` and `debug.log` with us?

Also could you tell the selenium and Selenium2Library version you are using. Also if the selenium is not the latest released version, could you try with the latest selenium version and see does the problem disappears.

**Comment by neospin** [comment]
Ok I updated the start page of Edge and now it worked. Must be a microsoft thing

**Comment by aaltat** [comment]
Could be, at least IE is really picky on it's settings. But it might be good idea to raise an issue to the Microsoft issue tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues

Also it looks like you got the issue solved, can we close the issue?

**Comment by neospin** [comment]
Yes please close the issue. Thanks
