### ISSUE TITLE
Cannot add keywords

### ISSUE THREAD

**Issue by hbmartin** [robotframework/SeleniumLibrary#79]
I am trying to add a create_cookie keyword in keywords/_cookie.py, but Robot Framework doesn't recognize the new keyword. What do I need to do to get new keywords working?

**Comment by hbmartin** [comment]
In particular, I added the following lines to _cookie.py:
    def create_cookie(self):
        """Creates a demo cookie."""
        self._current_browser().create_cookie("test=iWorked", "path=/")

**Comment by j1z0** [comment]
That is correct.  But to be clear you need to add that function to the _CookieKeywords class right.  once you have done that you should be good to go.

Cheers,
Jeremy

**Comment by hbmartin** [comment]
Yes, I added it to the _CookieKeywords class but it still is not available as a keyword in RF.
Perhaps I need to recompile or relink something?

**Comment by hbmartin** [comment]
RF is now recognizing the keyword (at least, it's successfully pulling the doc string), but it is saying that there is no create_cookie method. This doesn't make sense to me, since my new keyword is using the same object as all of the other cookie keywords.

KEYWORD: Selenium2Library.Create Cookie Expand All
Documentation:  Creates a demo cookie.
Start / End / Elapsed:  20120719 15:33:16.357 / 20120719 15:33:21.058 / 00:00:04.701
FAIL    AttributeError: 'WebDriver' object has no attribute 'create_cookie'

**Comment by hbmartin** [comment]
I'm an idiot... should be using the add_cookie method.
