### ISSUE TITLE
Cannot switch windows on browsers which don't support javascript

### ISSUE THREAD

**Issue by davidshepherd7** [robotframework/SeleniumLibrary#790]
When using a web browser that doesn't support javascript  (such as [QtWebDriver](https://github.com/cisco-open-source/qtwebdriver)) using the `Select Window` keyword results in an error:
```
WebDriverException: Message: Script execution failed. Script: return [ window.id, window.name, document.title, document.URL ];;
 Current view doesnt support this command.
```
even though this operation can be done through the web driver API.

Selenium2Library and QtWebDriver are checked out from their respective git development branches, Robot Framework version 3.0.2, Selenium version 3.3.1.

Pull request #788 fixes this issue.

**Comment by aaltat** [comment]
Done is #788
