### ISSUE TITLE
Extend xpath detection to support xpath starting with (//

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#794]
Selenium2Library locators support xpath's that are not prefixed if the xpath starts with `//`. It would also good to support xpath starting with `(//` because it is quite common situation to access index of the xpath. 

Now one has to write
```
| Page Should Contain Element | xpath=(//div)[1] |
```
But it would be nice if this would work:
```
| Page Should Contain Element | (//div)[1] |
```

**Comment by pekkaklarck** [comment]
In my opinion automatic support for `//` is a bit confusing and would prefer always prefixing locators when not using ids. I don't think removing this support is a good idea, though, and supporting `(//` too sounds logical.

**Comment by aaltat** [comment]
The other option is to deprecate the support for `//` in next major release. Then have a really long deprecation period and perhaps remove the support in some future release. Because I also like to be explicit, rather than implisit.

**Comment by pekkaklarck** [comment]
I don't think deprecation is worth the effort.

**Comment by emanlove** [comment]
We use ```//``` a fair amount (and maybe embarrassed to say). I don't have a strong opinion on ```(//``` but do think we should support ```:)``` which should make all the tests pass and the rain go away.

**Comment by aaltat** [comment]
There is a fix for this as part of #811

**Comment by aaltat** [comment]
Code is merged but needs documentation update to the keyword doc, in Locating or specifying elements chapter.

**Comment by aaltat** [comment]
Also add/modify acceptance test

**Comment by aaltat** [comment]
The #818 provides update for the documentation

**Comment by aaltat** [comment]
This is done in #811 and #818, closing.
