### ISSUE TITLE
Can't run Chrome with some prefs

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#795]
Hi

In Chrome (since version 57) there is changes of PDF viewer plugin. I want to turn off preview and download PDF. I used [this answer](http://stackoverflow.com/a/42927095) and tried to implement in a such way:
`${chrome options}= |   Evaluate  |  sys.modules['selenium.webdriver'].ChromeOptions()  |  sys, selenium.webdriver`
` ${prefs}=  |   Create Dictionary  |  download.default_directory=${download directory}   | plugins.always_open_pdf_externally=true`
`Call Method  |  ${chrome options}  |  add_experimental_option |   prefs  |  ${prefs}`
`Create Webdriver   | Chrome  |  chrome_options=${chrome options}`

Result:
download.default_directory - set correctly
plugins.always_open_pdf_externally - doesn't set

Might it relates to Selenium2Library issues?!

I have installed:
- robotframework-3.0.2 
- robotframework-selenium2library-1.8.0 
- selenium-3.3.3

**Comment by aaltat** [comment]
I do not have any idea, how you should set those Chrome options. It would be best to ask from user group mailing list: http://groups.google.com/group/robotframework-users

**Comment by chevi** [comment]
I resolved my issue by setting Chrome options throw python library [https://groups.google.com/forum/#!topic/robotframework-users/Jo1lzODNhXw](url)
