### ISSUE TITLE
Mouse right click

### ISSUE THREAD

**Issue by x64joxer** [robotframework/SeleniumLibrary#796]
It looks like Selenium supports right click mouse on element.
Selenium library in Robot Framework supports only left mouse click or context menu.
But sometimes (like on webpage tested by me) it is necessary to right click on element.
As a result of this new element appear and this is not context menu.
Is it possible to add this functionality?

**Comment by aaltat** [comment]
I think we already have this, have you looked at: http://robotframework.org/Selenium2Library/Selenium2Library.html#Open%20Context%20Menu

**Comment by x64joxer** [comment]
@aaltat 
When I am using Open Context Menu on my locator default Firefox context menu opens.
But when I am clicking manually new element appear.
When I right clicking manually with left key Shift key pressed default Firefox context menu opens (same as using Open Context Menu).

**Comment by aaltat** [comment]
In practice the keyword does this:
```
ActionChains(self._current_browser()).context_click(element).perform()
```
Is there some other selenium API which could be also used?

**Comment by x64joxer** [comment]
@aaltat You're right. Sorry for my mistake!
