### ISSUE TITLE
Selenium2library doesnt open new ie instance

### ISSUE THREAD

**Issue by Dhanabal** [robotframework/SeleniumLibrary#8]
I am planning to upgrade the test cases developed using selenium RC with robot framework to Selenium2Library. I just tried the below code using Selenium2Library in robot framework

open browser    www.google.co.uk    ie

No IE browser instance is opened bubt the test result is saying pass

The samething if i Try

open browser    www.google.co.uk    firfeox

new firefox instance is opened but no proxy setting is set in th opened browser. Please help me out

**Comment by adwu73** [comment]
I noticed this issue on one of my machine yesterday. Can you let us know the details about your env? IE version? FF version? Windows version? etc

**Comment by ktrajesha-yfni** [comment]
Environment details were below

IE version - IE9
FF Version- 5.0
Windows 7

**Comment by j1z0** [comment]
proxy settings for firefox can be set using a firefox profile.  for internet explore they can be set by using remoting which is now supported.  an explanation is here:

http://seleniumhq.org/docs/04_webdriver_advanced.html
