### ISSUE TITLE
Test failed on CLOSE ALL BROWSERS

### ISSUE THREAD

**Issue by b4oshany** [robotframework/SeleniumLibrary#800]
![image](https://cloud.githubusercontent.com/assets/1830494/25633387/852109c4-2f3c-11e7-94d4-3b0b52addc95.png)

**Comment by aaltat** [comment]
Could you create a simplified version of your test, which we all can see and perhaps use. Also could you run the with ```--loglevel trace``` option set from command line and send the stack trace to us. 

Also could you tell the selenium version you are using. Also tell the browser version and the driver version you are using

**Comment by b4oshany** [comment]
NVM, apparently, I had two keywords colliding, meaning, I was redefining a keyword that uses the ***Close All Browsers*** in my resources.robot file.

**Comment by aaltat** [comment]
Good that you sorted the problem out.
