### ISSUE TITLE
Robot Framework/Jenkins: chromedriver executable needs to be in PATH error

### ISSUE THREAD

**Issue by sandeepvaidya** [robotframework/SeleniumLibrary#801]
I am running Robot Framework/Selenium2Library tests on a linux VM. 

I am able to open browser with  the following Robot Framework test from the command line:

   
    Open Browser  https://xxxxxxxxxx/xx     chrome

The Chromedriver is in my home directory and the PATH is correctly set.

However, now I want to run the project in jenkins. Jenkins is running on the same linux VM as above. 
So, I copied the Chromedriver to JUNKINS_HOME (/var/lib/jenkins). Set the PATH to include this directory.

Changed RF test to:

 
	Set Environment Variable  webdriver.chrome.driver  /var/lib/jenkins/chromedriver  
    Open Browser  https://xxxxxxxxxx/xx     chrome

I am not able to et over this error mesg:

Onboard The Customers                                                
 [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
Test Start Time: 20170504 12:22:42.512
Test End Time: 20170504 12:22:42.541
WebDriverException: Message: 'chromedriver' executable needs to be in PATH.

**Comment by aaltat** [comment]
I am pretty sure that operating system is correct and the ChromeDriver is not in the PATH. 

With Jenkins, I usually put the ChromeDriver to `/apps/chrome_driver` folder. Then in the Jenkins job, I add that folder to the PATH, so that I don't have to modify the test depending where the test is run.

**Comment by sandeepvaidya** [comment]
Thanks!!  I had not set the path in Jenkins!!
Now I have something similar to this

On Jenkins:
Name  PATH
Value $PATH:/app/chrome_driver
So, now the driver is recognized. However, i have to now figure out the headless browser mode with phantomJS:

WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 3.10.0-514.6.2.el7.x86_64 x86_64)

**Comment by aaltat** [comment]
If you run chrome in normal operation mode, it needs a display. For me, easiest way to add display, in Linux, is to use xvfb.

Chrome also has a new feature, that support headless operation mode: http://www.thefriendlytester.co.uk/2017/04/new-headless-chrome-with-selenium.html?m=1

But I am not using that feature, so I don't know how to help you with headless chrome setup.

Please also note that PhantomJS​ development did end, when the headless chrome was released.

**Comment by sandeepvaidya** [comment]
Thanks a million for your responses. I have been able to set up the Xvfb virtual buffer and the tests are now running ok.

**Comment by aaltat** [comment]
It seems that issue is resolved and we can close the issue.

**Comment by sandeepvaidya** [comment]
yes!

**Comment by saudiatepace** [comment]
Hello @sandeepvaidya may I know how did you configure the PATH for chromedriver in Jenkins? Need some help. :)

**Comment by sandeepvaidya** [comment]
On Jenkins:
Name PATH
Value $PATH:/app/chrome_driver



________________________________

**Comment by mithunsureshqa** [comment]
@sandeepvaidya , i tried setting up environment variable on jenkin configure. build failed to identify python. 
below is my shell script command 
"python -m robot.run /Users/<name>/PycharmProjects/learn/Test"
On removing the env variable from configure in jenkin, i get webdriver not found error. "WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please"

**Comment by sandeepvaidya** [comment]
Make sure the chromedriver location   is in $PATH


________________________________

**Comment by mithunsureshqa** [comment]
i have placed the chrome driver on same path. now works fine.

**Comment by udhayaganesh** [comment]
can someone help me on windows OS?
I am running robot framework on web application with instrucion shown on https://github.com/robotframework/WebDemo

I get "WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home".

Chromedriver is on path. but still get same error.

**Comment by aaltat** [comment]
With this information it's not possible to help you, because there are many ways to set up the PATH in windows. Also this is more of an support requests and how to get support is explained in here: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
