### ISSUE TITLE
Selenium2Library Keyword Page errors when using www

### ISSUE THREAD

**Issue by vairamsvsjdo** [robotframework/SeleniumLibrary#806]
Documentation Issue: 
Works: http://robotframework.org/Selenium2Library/Selenium2Library.html
Does not work: http://www.robotframework.org/Selenium2Library/Selenium2Library.html

**Comment by HelioGuilherme66** [comment]
It is working for me.
Browser, removes automatically the www so it goes for the first link.
Tried with Firefox, Chrome, IE11 and Edge on Windows 10.

**Comment by aaltat** [comment]
Both of them works from mobile and from desktop.

**Comment by aaltat** [comment]
Is this still a valid problem or can we close the issue?

**Comment by aaltat** [comment]
Closing due inactivity
