### ISSUE TITLE
Wait Event keyword

### ISSUE THREAD

**Issue by jvanz** [robotframework/SeleniumLibrary#824]
I believe it would be nice the the Selenium2Library offer a keyword to allow the test wait for a specific event. For instance,

`Wait Event    hidden.bs.modal    jquery=div.modal`

Hence, it would be easier wait for a transaction effects, like a bootstrap modal close, finish.

**Comment by aaltat** [comment]
Is there a reason why http://robotframework.org/Selenium2Library/Selenium2Library.html#Wait%20For%20Condition doesn't work for you in this case?

**Comment by aaltat** [comment]
Is this still a problem?

**Comment by jvanz** [comment]
I do not think so. Your hint helped. Thank you @aaltat
