### ISSUE TITLE
Can't install it with python 3.6.1

### ISSUE THREAD

**Issue by StyleTJy** [robotframework/SeleniumLibrary#825]
I installed python 3.6.1 and pip 9.0.1. When I tried to run the recommended command
 `pip install robotframework-selenium2library` 
I got error

> Collecting robotframework-selenium2library
>   Using cached robotframework-selenium2library-1.8.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\J_~1\AppData\Local\Temp\pip-build-rt44bo4z\robotframework-selenium2library\setup.py", line 7, in <module>
>         from ez_setup import use_setuptools
>       File "C:\Users\J_~1\AppData\Local\Temp\pip-build-rt44bo4z\robotframework-selenium2library\src\ez_setup.py", line 106
>         except pkg_resources.VersionConflict, e:
>                                             ^
>     SyntaxError: invalid syntax
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\J_~1\AppData\Local\Temp\pip-build-rt44bo4z\robotframework-selenium2library\

so i doubt that if the scripts of the installation are too old for python 3 and don't know if there any body had the same problem with me.

**Comment by aaltat** [comment]
The Python 3 support is not yet released, although the project docs have been updated. Could you perform the installation from the source and then it should work with Python 3.

**Comment by aaltat** [comment]
Do yo still have a problem, or can we close the issue?

**Comment by StyleTJy** [comment]
@aaltat sorry for being late to reply your comments. actually, I tried to download the source package which was modified by 2016-08-23. so did I download the old version?

**Comment by aaltat** [comment]
Yes you did, you need install from the repository master branch directly If you are using pip, please see here for more details: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by StyleTJy** [comment]
OK, that helps a lot. thanks for your useful suggestions.
