### ISSUE TITLE
Type into a prompt is not working for Safari Technology Preview

### ISSUE THREAD

**Issue by SerhiiAksiutin** [robotframework/SeleniumLibrary#827]
When user does something like this in test.robot file

`Create Webdriver  Safari  executable_path=${technology_preview}`
`Go to  https://username:password@mytestwebsite.com`
`Input Text Into Prompt  ${url_username}`

Expected:
Text should be populated in the alert

Actual:
Nothing is happening. No error in the output
<img width="1280" alt="screen shot 2017-06-18 at 10 40 08 am" src="https://user-images.githubusercontent.com/27512156/27262880-ac86f6a2-5414-11e7-8275-411de02b7b33.png">

Notes:
Safari Technology Preview Release 33 (Safari 11.0, WebKit 12604.1.25.0.2)

CC: @aaltat

**Comment by aaltat** [comment]
Does it work with other browsers, example Chrome?

**Comment by SerhiiAksiutin** [comment]
It is not working for Chrome as well

Steps:
`Create Webdriver  Chrome  --ignore-certificate-errors`
`Go to  ${https}${url}`
`Input Text Into Prompt  ${url_username}`

Actual:
`[ INFO    ] There were no alerts`
<img width="957" alt="screen shot 2017-06-19 at 9 51 52 am" src="https://user-images.githubusercontent.com/27512156/27296325-41f1dd18-54d5-11e7-994d-68e5a84b1a41.png">

**Comment by aaltat** [comment]
Would you mind running the test with `--loglevel trace` set from command line? I would like to see the full stack trace from the error.

**Comment by SerhiiAksiutin** [comment]
```
[ TRACE   ] Finished Request
[ TRACE   ] Return: None
.[ TRACE   ] Arguments: [ b'storefront' ]
[ TRACE   ] GET http://127.0.0.1:51246/session/9a10592a9075fd42c5c59b0bbc5b678b/alert_text {"sessionId": "9a10592a9075fd42c5c59b0bbc5b678b"}
[ TRACE   ] Finished Request
[ TRACE   ] GET http://127.0.0.1:51246/session/9a10592a9075fd42c5c59b0bbc5b678b/alert_text {"sessionId": "9a10592a9075fd42c5c59b0bbc5b678b"}
[ TRACE   ] Finished Request
[ TRACE   ] Arguments: [  ]
[ TRACE   ] GET http://127.0.0.1:51246/session/9a10592a9075fd42c5c59b0bbc5b678b/screenshot {"sessionId": "9a10592a9075fd42c5c59b0bbc5b678b"}
[ TRACE   ] Finished Request
[ TRACE   ] </td></tr><tr><td colspan="3"><a href="selenium-screenshot-1.png"><img src="selenium-screenshot-1.png" width="800px"></a>
[ TRACE   ] Return: '/Users/saksiutin/.virtualenvs/cherobot/robot-framework/results/selenium-screenshot-1.png'
[ TRACE   ] There were no alerts
[ TRACE   ] Traceback (most recent call last):
  File "<decorator-gen-162>", line 2, in input_text_into_prompt
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/_alert.py", line 21, in input_text_into_prompt
    raise RuntimeError('There were no alerts')
Positive: Open landing page :: User will open a browser and go to ... | FAIL |
There were no alerts
------------------------------------------------------------------------------
```

**Comment by aaltat** [comment]
The code polls the alert, but only for a one second. If the alert is not present then an exception is raised. 

If you do:
```
| Wait Until Keyword Succeeds | 30s | 5s | Input Text Into Prompt | ${url_username} | 
```
Does it then work ok for you?

**Comment by SerhiiAksiutin** [comment]
@aaltat it never succeeds for 30 seconds while the alert is clearly populated
```
[ TRACE   ] There were no alerts
[ TRACE   ] Traceback (most recent call last):
  File "<decorator-gen-162>", line 2, in input_text_into_prompt
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/_alert.py", line 21, in input_text_into_prompt
    raise RuntimeError('There were no alerts')
[ TRACE   ] Arguments: [ b'storefront' ]
[ TRACE   ] GET http://127.0.0.1:50310/session/0d7ecb59f96add102faf54911522ccac/alert_text {"sessionId": "0d7ecb59f96add102faf54911522ccac"}
[ TRACE   ] Finished Request
[ TRACE   ] GET http://127.0.0.1:50310/session/0d7ecb59f96add102faf54911522ccac/alert_text {"sessionId": "0d7ecb59f96add102faf54911522ccac"}
[ TRACE   ] Finished Request
[ TRACE   ] Arguments: [  ]
[ TRACE   ] GET http://127.0.0.1:50310/session/0d7ecb59f96add102faf54911522ccac/screenshot {"sessionId": "0d7ecb59f96add102faf54911522ccac"}
[ TRACE   ] Finished Request
[ TRACE   ] </td></tr><tr><td colspan="3"><a href="selenium-screenshot-6.png"><img src="selenium-screenshot-6.png" width="800px"></a>
[ TRACE   ] Return: '/Users/saksiutin/.virtualenvs/cherobot/robot-framework/results/selenium-screenshot-6.png'
[ TRACE   ] There were no alerts
[ TRACE   ] Traceback (most recent call last):
  File "<decorator-gen-162>", line 2, in input_text_into_prompt
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "/Users/saksiutin/.virtualenvs/cherobot/robot-framework/tmp/rf/lib/python2.7/site-packages/robotframework_selenium2library-1.8.0-py2.7.egg/Selenium2Library/keywords/_alert.py", line 21, in input_text_into_prompt
    raise RuntimeError('There were no alerts')
[ TRACE   ] Keyword 'Input Text Into Prompt' failed after retrying for 30 seconds. The last error was: There were no alerts
```

**Comment by aaltat** [comment]
Ah but that is a basic authentication dialog, right? Unfortunately selenium does not support handling basic authentication dialog. Because of this we can not do anything on the Selenium2Library side. Your best option to google around see how you can bypass the basic authentication in Safari. Here is working example for Chrome: https://stackoverflow.com/questions/9888323/how-to-override-basic-authentication-in-selenium2-with-java-using-chrome-driver

**Comment by SerhiiAksiutin** [comment]
In this case, It's not an alert as I thought. Although `http://username:password@mytestsite.com` works for Chrome and FF very well. 
And for Safari I have already opened an issue report [Unable to bypass auth if credentials sent via url e.g. https://username:password@mytestsite.com](https://bugreport.apple.com/web/?problemID=32839932)

**Comment by aaltat** [comment]
As a side note, chrome has dropped support for URL basic authentication in release 59: https://www.chromestatus.com/feature/5669008342777856

**Comment by SerhiiAksiutin** [comment]
> As a side note, chrome has dropped support for URL basic authentication in release 59: https://www.chromestatus.com/feature/5669008342777856

@aaltat That's the only workaround. Don't you think Selenium2Library could do anything about it?  I could keep the issue open?

**Comment by aaltat** [comment]
There is rumours that Webdriver specification next release would bring support for basic authentication, but that is only rumor. Unless Selenium provides the support, don't think we are going to provide direct support.

In my humble opinion, it would be best if the whole basic authentication would die away. There are better and easier ways to do the user authentication.
