### ISSUE TITLE
Capture Page Screenshot + Should Be Equal in Documentation

### ISSUE THREAD

**Issue by chanwooh** [robotframework/SeleniumLibrary#834]
For the keyword "Capture Page Screenshot"'s documentation, it uses the keyword "Should Be Equal" to imply that certain files should be equal. However, the keyword cannot actually be used to compare images or screenshots (it simply uses the arguments as strings in these cases and fails). 

I think the documentation should be clarified by noting that "Should Be Equal" in this case would not work, or remove the keyword from the example altogether.

**Comment by aaltat** [comment]
I don't quite understand what you are trying to explain. Could you clarify the problem?

**Comment by chanwooh** [comment]
![screen shot 2017-06-21 at 13 20 26](https://user-images.githubusercontent.com/14134553/27404862-719d82dc-5684-11e7-98cb-1fadb579fc43.png)

In Example 1 (shown above), "Should Be Equal" seems to be testing if screenshot ${file1} and screenshot ${${OUTPUTDIR}${/}selenium-screenshot-1.png} are equivalent as _images_. This is misleading since the keyword actually compares the _names_ of the screenshots for equality. That's why I think there should be a note that "Should Be Equal" cannot be used to compare the contents of ${file1} and ${${OUTPUTDIR}${/}selenium-screenshot-1.png}.

**Comment by aaltat** [comment]
Now I understand what you are trying to say. I also understand why you might have come to this assumption. 

Would you have ideas how to improve the keyword documentation? Also perhaps in a pull request?

**Comment by chanwooh** [comment]
I think just a clear note before the examples will suffice, since there isn't an easy "built-in" way to compare screenshots. I'll submit a pull request, thanks!

**Comment by aaltat** [comment]
Issue should not be closed before we decide what to with the PR.

**Comment by aaltat** [comment]
Closing
