### ISSUE TITLE
Remove unused expiry argument from `Add Cookie` keyword

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#847]
The `Add Cookie` keyword has arguments `name, value, path, domain, secure and expiry` but the `expiry` argument is not used in anywhere. Removing the unused argument.

**Comment by aaltat** [comment]
Done in #846

**Comment by pekkaklarck** [comment]
Issue #891 is about adding expiry back so that it actually works. If that gets done, then this issue should be removed from SL 3.0 scope.

**Comment by pekkaklarck** [comment]
Expiry nowadays works.
