### ISSUE TITLE
Double Click Element does not work for firefox

### ISSUE THREAD

**Issue by juncsun** [robotframework/SeleniumLibrary#852]
Hi,
  In my test webpage, there is one element on doubling clicking which there will be one new dialog displayed, or on clicking right mouse button there will be one context menu displayed, but while I am using Double Click Element or Open Context Menu by firefox browser, neither works.
However, while I am using chrome browser, the Double Click Element works(I did not have a try for Open Context Memu).

 Would you pls help to tell me whether there is something error in my env?  Thanks so much

Firefox 52.1.0 (64-bit) and 52.1.0 (64-bit) v0.17.0 on linux el7,
Robot Framework  3.0.2
Selenium2Library:  1.8.0

**Comment by aaltat** [comment]
The Firefox support for Selenium is at best on beta stage, because of the Firefox moving to use the geckodriver. Unfortunately there is not anything that we could help on the Selenium2Library side. If the latest geckodriver and Selenium version doesn't help, please raise an issue to the Selenium issue tracker.

**Comment by juncsun** [comment]
Got you. Thanks for your information. I will try again with firefox beta version

**Comment by aaltat** [comment]
I did mean that Firefox support for Selenium is not fully ready. Therefore the problem, most likely, is in Selenium or somewhere in the browser specific implementation. 

If the latest Firefox, geckodriver or Selenium doesn't solve the problem, please raise an issue to the Selenium or geckodriver side.

**Comment by juncsun** [comment]
Really Thank you aaltat. I will try again with latest Firefox/geckodriver/Selenium. And follow your suggestion if that still does not work.

**Comment by aaltat** [comment]
Was your problem solved or did you report the problem to selenium/FF? If you did can we close the problem?

**Comment by juncsun** [comment]
Hi,tatu,Sorry that I don't realize that I can close it.Will do that soon.


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： Tatu Aalto <notifications@github.com> 日期: 2017/8/9  03:07  (GMT+08:00) 收件人： robotframework/Selenium2Library <Selenium2Library@noreply.github.com> 抄送： juncsun <aofei_2000@163.com>, Author <author@noreply.github.com> 主题： Re: [robotframework/Selenium2Library] Double Click Element does not
  work for firefox (#852) 
Was your problem solved or did you report the problem to selenium/FF? If you did can we close the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/robotframework/Selenium2Library","title":"robotframework/Selenium2Library","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/robotframework/Selenium2Library"}},"updates":{"snippets":[{"icon":"PERSON","message":"@aaltat in #852: Was your problem solved or did you report the problem to selenium/FF? If you did can we close the problem?"}],"action":{"name":"View Issue","url":"https://github.com/robotframework/Selenium2Library/issues/852#issuecomment-321052016"}}}
