### ISSUE TITLE
"Textfield Value Should Be" applied on a textarea gives wrong error message

### ISSUE THREAD

**Issue by tuxayo** [robotframework/SeleniumLibrary#853]
> Value of text field 'MY_LOCATOR' should have been 'EXPECTED' but was 'None'

The error message says something wrong about the value when it should complain about not finding the element or the element being of the wrong type.

Is the above correct?

Versions:
```
$ pip2 freeze | grep -E '(robot|selen)'
robotframework==3.0.2
robotframework-archivelibrary==0.4.0
robotframework-requests==0.4.7
robotframework-selenium2library==1.8.0
robotframework-selenium2screenshots==0.7.2
selenium==2.53.6
```

**Comment by aaltat** [comment]
There would be different error if the element would not be found, it would raise ValueError if element is not found. Now it raises AssertionError because the text is not expected.

When text field does not contain text, Selenium returns Python `None`. Based on the error message I would assume that your text field is empty, locator is pointing to the wrong element or there is a timing issue.

**Comment by aaltat** [comment]
Because Selenium2Library working as expected l, I am closing the issue. If you feel differently, please state why you feel so and we can reconsider opening the issue.

**Comment by tuxayo** [comment]
Thanks for your answers, I hope to have the time in the next few days to respond.

But for now I'm found another problem that might be related.

While trying to debug a test that I'm writing, I ended up using a bogus css selector and a bogus locator.
And here the messages that I got:

```
Keyword 'Textfield Value Should Be' failed after retrying for 7 seconds. The last error was: Value of text field 'css=SELECTOR_THAT_DONT_EXIST' should have been '123456' but was 'None'

Keyword 'Textfield Value Should Be' failed after retrying for 7 seconds. The last error was: Value of text field 'SELECTOR_THAT_DONT_EXIST' should have been '123456;' but was 'None'
```
