### ISSUE TITLE
doc: "Textfield Value Should Be" should mention that it doesn't work on hidden fields

### ISSUE THREAD

**Issue by tuxayo** [robotframework/SeleniumLibrary#854]
Where `type="hidden"`

Is that behavior that I just found correct?

I guess it also applies to "Textfield Should Contain" ?

For anyone else trying to the same thing, here is a solution:
```
${actual_value} =  Get Value  MY_LOCATOR@MY_ATTRIBUTE
Should Be Equal  MY_EXPECTED_VALUE  ${actual_value}
```

**Comment by aaltat** [comment]
Yes, if element is hidden, underlying Selenium will always return `None`. This is because Selenium mimics what real users can do and real users can not not see or interact with hidden elements. 

To solve your problem, you could try the `Get Element Attribute` keyword.

**Comment by aaltat** [comment]
And to answer to your question, yes documentation can always be enhanced. Would you like to make a pull request?

**Comment by aaltat** [comment]
Closing due inactivity.
