### ISSUE TITLE
Could not close browser with Selenium3

### ISSUE THREAD

**Issue by justcby** [robotframework/SeleniumLibrary#856]
Hi,
In my test webpage, use keyword "Close Browser" to close current browser , it meet error and failed message is only "quit"
But before upgrade firefox and selenium version , it's fine for my scripts.
Would you pls help to tell me whether there is something error in my env? Thanks so much

Firefox 52.2.1 (32-bit)  on windows,
Robot Framework 2.8.7
Selenium2Library: 1.8.0
Selenium: 3.4.3

**Comment by justcby** [comment]
WebDriverException: Message: quit

**Comment by HelioGuilherme66** [comment]
Did you download and place in a PATH location, the "geckodriver" executable?

**Comment by justcby** [comment]
yes. seem use geckodriver latest version v0.18.0 have this problem. but use oldest geckodriver version, after it close browser , it will alert that"Firefox has stopped working"  ...
due to firefox version ?

**Comment by aaltat** [comment]
I did read the code and basically `Close Browser` keyword it does this: 
```
driver.quit()
```
Which is the standard way to close the browser.  

But perhaps this was a problem with the Firefox because I can not reproduce the problem with 54 or 55 versions. Could you update your FF, try again and report back how it go.

**Comment by justcby** [comment]
@aaltat I update FF to 54 , it is work now.. Thanks
