### ISSUE TITLE
Unable to install Robot framework. Getting error "except pkg_resources.VersionConflict, e:"

### ISSUE THREAD

**Issue by Zabi-Py** [robotframework/SeleniumLibrary#857]
Im trying to install robotframework and i got the following error, Environment - Windows 10, Python 3.6.2, Selenium 3.4.3

C:\Users\Zabihullah>pip install robotframework-selenium2library
Collecting robotframework-selenium2library
  Using cached robotframework-selenium2library-1.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ZABIHU~1\AppData\Local\Temp\pip-build-c_s2tg4s\robotframework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\ZABIHU~1\AppData\Local\Temp\pip-build-c_s2tg4s\robotframework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ZABIHU~1\AppData\Local\Temp\pip-build-c_s2tg4s\robotframework-selenium2library\

Kindly help me resolve this issue asap.
![robotinstall](https://user-images.githubusercontent.com/30861354/29119625-821577ca-7d24-11e7-8e58-de5b22803a70.png)

**Comment by aaltat** [comment]
The Python 3 is not supported by the 1.8.0 release. The good news is that the Python 3 support is available but not yet released. You can install with pip from GitHub repository, see more details in pip documentation: https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

But because this is known issue and workaround exist, I am closing the issue.

**Comment by Zabi-Py** [comment]
Kindly release Python3 support for Robot framework asap.

**Comment by Zabi-Py** [comment]
Also can you please give the command here to install using vcs. Im still facing issues. May be im doing it wrong

**Comment by aaltat** [comment]
See example here: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch
