### ISSUE TITLE
Get Text in Sel2Lib not working

### ISSUE THREAD

**Issue by nikhilrajgarhia** [robotframework/SeleniumLibrary#865]
Hi,

I am not able to get the text from element. Even though I added wait like 'Wait Until Page Contains Element', it didn't fetch the element text. I have used this statement just above the line where I am fetching the text.
Eg:
Wait Until Page Contains Element ${elementsInList} timeout=120
${textValue} Get Text ${elementsInList}

**Comment by aaltat** [comment]
The Selenium returns Python `None` if the element is not visible or if the element does not contain any text. To be able to help you better, could you provide example which we all can run?

**Comment by nikhilrajgarhia** [comment]
Yes, its returning None. 
I am running the scripts on my application, So, it wouldn't be available for everyone to test. But, for an overview, I will provide with a piece of code and the screenshot.

'${ctcElements}  Get Webelements    xpath=//div[@colid='full_inc']/gt-grid-currency-cell
${ctcElemLength}    Get Length    ${ctcElements}    
#Log To Console    ${ctcElemLength}
Sleep  10s    

${ctcList}  Create List
    : FOR    ${iRNo}  IN RANGE  0  ${ctcElemLength}
    \  ${elementsInList}  Collections.Get From List    ${ctcElements}    ${iRNo}
    \  ${ctcValue}    Get Text    ${elementsInList}
    \  Log To Console    ${iRNo}
    \  Log To Console    ${ctcValue}
    \  Insert Into List    ${ctcList}    ${iRNo}    ${ctcValue}
    Log    ${ctcList}'

Output:-
0
1,850,000
1
`-`
2
5,200,000
3
600,000
4
5,000,000
5
1,850,000
6
`None`
7
`None`

Screenshot attched.

![pic1](https://user-images.githubusercontent.com/13416016/29505719-7c491f28-8665-11e7-83ee-99abeb733a04.jpg)
![pic2](https://user-images.githubusercontent.com/13416016/29505747-aa08116c-8665-11e7-8dc1-e54b2dab2d3f.jpg)

**Comment by aaltat** [comment]
Because I don't see the application I am flying blind, to be able to help you better, could you provide example which we all can run?

**Comment by nikhilrajgarhia** [comment]
No, It wont work out of the Network.

**Comment by aaltat** [comment]
Well, could you create an example by using that is publicly available?

**Comment by nikhilrajgarhia** [comment]
Sure, will create one and share.

**Comment by aaltat** [comment]
Is this still a problem or can we close the issue?

**Comment by nikhilrajgarhia** [comment]
Yes, I am still facing the issue. Let me provide you an example.

**Comment by aaltat** [comment]
How is that example going on?

**Comment by nikhilrajgarhia** [comment]
Sorry for the late response. Here are few observations.

1) The issue is faced when I am trying to extract the text from the table which has scroll down/up feature. Even though the elements are available on the UI, but, I am not able to get the text.
1) It works fine when we have a table without scrolls.

Unable to provide the example since I didn't get any demo site online for which I can write the scripts.

**Comment by aaltat** [comment]
If the element is hidden, example you need to scroll to see the element, then Selenium will return `None`, because real users can not see the text which is hidden. This is way the Selenium works and the SeleniumLibrary can not change it.

But because this turning more a support issue than a bug report or a feature request, I am closing the issue. For seeking support, please see: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

There are ways to solve the problem, but the way depends on what your requirements are.
