### ISSUE TITLE
Open browser with profile name as argument

### ISSUE THREAD

**Issue by Yoganand0708** [robotframework/SeleniumLibrary#868]
I am using Selenium2Library on one of my Linux machine and 

I am launching different firefox sessions manually at the same time by using profiles concept.

Below is the command which I use in case of linux.

firefox -no-remote -P "<Profile_Name>"

So the same i wanted to try from Selenium using "**Open Browser**" which takes _<Profile_name>_ as an argument.

Could you please help me if it is possible.

Regards,
Yoganand

**Comment by aaltat** [comment]
It's not possible to use the profile name, but it's possible to use a path to the profile which you want to use. Please see the `Open Browser` keyword documentation for more details.

**Comment by Yoganand0708** [comment]
Hi aalat,

Yeah, I can use the Profile path but my issue here is, I can't launch more than one firefox session in case of linux, 

So to launch multiple firefox sessions, I was using profiles concept incase of linux.

Could you please help me with below info:-

1) Does using the path and launch using different profiles is one and the same?
(I see this as this value as this would overwrite the current default path)

My scenario is to launch nearly 20-25 firefox sessions simultaneously. 

Below is the error which I see when launching more than one.


![firefox_error](https://user-images.githubusercontent.com/31201489/29518224-1ed024c8-8696-11e7-831a-9ac429e6c145.JPG)


Regards,
Yoganand

**Comment by aaltat** [comment]
Firefox should automatically create a new profile for each browser when used from selenium. If that does not work, then it is bug in selenium (not in Selenium2Library) or in Firefox side. The only limiting factor for how many browser you can have open should be the resources on your PC, not the amount of profiles for your Firefox. 

Please open a new issue to the selenium or/and Firefox issue tracker if the latest Firefox, geckodirver and selenium version does not remove your problem. 

As a workaround, 
1) You could use chrome
2) See if the using the different FF profiles remove the problem

**Comment by aaltat** [comment]
Is this a still a problem or can we close the issue?

**Comment by aaltat** [comment]
Closing due inactivity.
