### ISSUE TITLE
Unable to work on firefox remote browser with gecko browser 0.15, 0.16, 0.17 and 0.18

### ISSUE THREAD

**Issue by anupamdas24** [robotframework/SeleniumLibrary#869]
Unable to launch the Firefox remote branch with the gecko driver.

**Comment by aaltat** [comment]
Please read this: https://github.com/robotframework/Selenium2Library/blob/master/CONTRIBUTING.md#submitting-issues and fill the missing details. 

As a side note, cross posting on several issues is not good practice.

**Comment by aaltat** [comment]
Closing doe inactivity
