### ISSUE TITLE
Document that Jython and PyPy are supported but IronPython is not

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#879]
Now that SL 3 is getting ready, it's a good idea to test how it works with alternate Python interpreter versions. This issue is mainly a reminder to check the overall status and update README accordingly.

If non-trivial fixes are needed to support alternate interpreters, that must wait for later releases. Separate issues can be submitted about different interpreters like we already have #410 about Jython compatibility.

**Comment by pekkaklarck** [comment]
Results from testing:

- PyPy 2 and PyPy 3 both work fine. Only tested on Linux where PyPy is much better supported than on Windows, though.
- Jython 2.7 works fine. Tested both on Linux and Windows.
- IronPython doesn't work at all. Couldn't get even a [simple Selenium example](http://selenium-python.readthedocs.io/getting-started.html#simple-usage) to work either. If IronPython doesn't support Selenium at all, there's nothing we can do to support about it.

**Comment by pekkaklarck** [comment]
PR #902 documents the current Jython/PyPy/IronPython support. In practice we support Jython and PyPy but not IronPython.

To make sure we don't accidentally break Jython or PyPy support, we needed to add CI tasks to run tests on them automatically. Should separate issue(s) be submitted about that?

**Comment by aaltat** [comment]
Separate issues would be better.

**Comment by pekkaklarck** [comment]
Decided to change the issue from task to enhancement to get the now official Jython and PyPy support listed also on release notes.
