### ISSUE TITLE
Externally useful attributes should be declared public and documented.

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#882]
Old Selenium2Library has several attributes that are useful externally from custom libraries and extensions:

```
_run_on_failure_keyword
_speed_in_secs
_timeout_in_secs
_implicit_wait_in_secs
_current_browser()
```

We should indicate that using these externally is OK by removing the leading underscore. The current WebDriver instance should also be accessible as a normal attribute (i.e. without calling a method like `current_browser()`) and we should name the attribute `webdriver` to make it explicit what it actually is. I would also remove unnecessary `_in_secs` postfixes. In other words, I would like to have these attributes instead:

```
run_on_failure_keyword
speed
timeout
implicit_wait
webdriver
```

Renaming these attributes is obviously a backwards incompatible change. We should thus add propertys that enable the old functionality but emit deprecation warnings. These propertys can then be removed in 3.1 or later.

---

*UPDATES:*

1. We used `browser` attribute instead of `webdriver` until 3.0 RC 1.

2. In 3.0 RC 1 we added also methods `find_element` and `find_elements` directly to the library itself. These methods form the recommended public API to find elements for external tools.

**Comment by pekkaklarck** [comment]
This is mostly fixed if #884 is merged. The remaining decisions to make are:

- Should deprecated attributes be unit tested somehow? Shouldn't be too hard, but adding tests for features that are going to be removed pretty soon feels a bit like waste.

- What do to with `_browsers`?

**Comment by aaltat** [comment]
1) I think that it is waste too, lets not do unit test for those. 
2) Is the cache for drivers. There already are public API to register driver, get the current driver and switch between drivers and close driver. With those API it might be better to leave it private.

**Comment by pekkaklarck** [comment]
If we aren't going to add more tests and we'll keep `_browsers` as-is, isn't this issue done?

**Comment by aaltat** [comment]
Yes it's. Closing

**Comment by pekkaklarck** [comment]
We decided to change `browser` to `webdriver' still. We'll deprecate `browser` in 3.0 rc 1 so that early adopters aren't punished, but we'll remove it still before the final release.

**Comment by aaltat** [comment]
I think it would be better to use `driver` instead of `webdriver`. `webdriver` is module in selenium, which might confuse people, which we are referring to. Also all example in selenium uses word `driver` when the refer to `selenium.webdriver.Chrome`

It would be good idea to change also `BrowserCache` to `DriverCache`

**Comment by pekkaklarck** [comment]
I actually prefer `webdriver` instead of `driver`. The former makes it explicit that this is a `WebDriver` object, not some other driver. I don't thing anyone would confuse `SL.webdriver` attribute with the `webdriver` module.

My guess is that Selenium examples use `driver` because in their context `WebDriver` can be assumed. Also, in their examples `webdriver` could actually clash with the `webdriver` module.

**Comment by boakley** [comment]
I agree with @aaltat - driver and browser both seem better than webdriver. I would prefer you stick with browser since the code is already in release candidate status and public interfaces shouldn‘t be changing.

**Comment by pekkaklarck** [comment]
We aren't in RC yet. In earlier versions this attribute was `_browser` and thus it wasn't really public. The reason I'd call it `webdriver` is that it is an instance of `WebDriver` and tbe idea is that external users can use its functionality as needed. That name would make the situation explicit even without much documentation.

**Comment by boakley** [comment]
Well, even in beta these types of changes shouldn’t be happening. 

--bryan

**Comment by aaltat** [comment]
Adding sphinx style definitions helps users of the methods and IDE's to provide auto completions for arguments and return values. 

- [x] Change ContextAware class `param` to `param` and `type`to better support Sublime Anaconda plugin
- [x] Add [find_elements](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L407) to contain similar type of definitions as [find_element](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L392)

**Comment by aaltat** [comment]
I prefer using `driver`, because that is defacto way of referring to the `WebDriver` instance. 

I agree that making changes this late in release pipeline is causing problems for the end users who have extended SL with their own libraries. I am one of those users, too. But I also agree that the old public API, or lack of it, is also a big problem. I hope that we can now implement a better public API which allows extending the library in more easier and cleaner way.

**Comment by aaltat** [comment]
Did forget to say that the plan is to keep some of the old non public API interface in place, to ease the transition from S2L 1.8.0 to SL 3.0.0. If I recall correctly, @boakley requirements for the old API are pretty much the same as mine. But I know that if users have used `ElementFinder`, `TableElementFinder` or some other internal functionality, the code is not anymore backwards compatible.

**Comment by aaltat** [comment]
Document public properties and `find_elements` with sphinx documentation. At least document the types and if method document return types.

**Comment by aaltat** [comment]
The sphinx documentation is done in #994
