### ISSUE TITLE
How to extend SeleniumLibrary?

### ISSUE THREAD

**Issue by youarelev** [robotframework/SeleniumLibrary#889]
How to do something like this - https://github.com/rickypc/robotframework-extendedselenium2library/blob/master/src/ExtendedSelenium2Library/__init__.py ?

I have extended Selenium2Library (<3.0 version) like in example above, because I need to override some default keywords. After update to 3.0.0b1 S2L my my tests tell me that there are no any keywords found in my S2L extended library. P.S, I have hundred of tests already. How can I fix it or how to install latest 2.* version of S2L using pip (found 3.0.0b1 version in pip repo only)?

**Comment by pekkaklarck** [comment]
How to extend the new SeleniumLibrary depends on what you actually want to do. If you just want to access attributes provided by the library, they should still be avaialble although some are deprecated. If you want to add new keywords, then you need to use extension mechanism provided by the [PythonLibCore](https://github.com/robotframework/PythonLibCore) that SL nowadays uses internally. Unfortunately that library isn't yet adequately documented, and I doubt we can finish them before SL 3.0 final. Here are very quick instructions that ought to get you started:

- Implement you keywords in library components similarly as SL nowadays does. Decorate keywords with the `@keyword` decorator.
- Add custom libraries by calling the `add_library_components()` method provided by the PythonLibCore.

How to install the latest legacy Selenium2Library version is explained by both SL and S2L installation instructions:
https://github.com/robotframework/SeleniumLibrary#installation
https://github.com/robotframework/Selenium2Library#installation

**Comment by aaltat** [comment]
Starting from 3.0.0 Alpha release the architecture of the [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst) has changed. The [Selenium2Library](https://github.com/robotframework/Selenium2Library) was renamed as SeleniumLibrary and currently Selenium2Library is only wrapper on top of the SeleniumLibrary. Many things has changed and it is possible that libraries extending SeleniumLibrary needs some changes.

Now there are many ways to solve the problem, but there is not a single solution that would fit for all. Could you share a simple example that demonstrates the problem? With some example code and test data that demonstrates the problem? And seeing the error message would be a good start. 

Please note that old releases are not deleted from the PyPI and the [1.8.0](https://pypi.python.org/pypi/robotframework-selenium2library/1.8.0) is the last release using the old architecture. Doing `pip install robotframework-selenium2library==1.8.0` is install you the correct version.

**Comment by youarelev** [comment]
S2L 1.8.0 was uploaded on 2016-08-25. But I saw S2L 2.9.2 few moths ago. Also I can install it using pip install robotframework-seleniumlibrary==2.9.2. Why it is not the latest version?

Small code example:
<><><>
from SeleniumLibrary import SeleniumLibrary

class Selenium2LibraryExtended(SeleniumLibrary):
def __init__(self, ...):
SeleniumLibrary.__init__(self, timeout=timeout, implicit_wait=implicit_wait, **kwargs)

override keyword
def open_browser(self, ...):
I have about 100 lines of code here and:
super(Selenium2LibraryExtended, self).open_browser(...)
at the end

custom method
def custom_method(self, ...):
DO IT

...
<><><>

And in *.robot file I do:
Library  Selenium2LibraryExtended
instead of:
Library  SeleniumLibrary

That was cool object oriented solution. If I use that code right now, my tests do not see any custom or overwritten keywords. Can you explain my why?

**Comment by aaltat** [comment]
As Pekka stated, the library has moved to use the Dynamic API and the PythonLibCore. If you follow his instructions you should be able to extend your libraries. If you can not, could you provide more details where you are having problems, example by providing a simple and runable example will help a lot. 

There are SeleniumLibrary and Selenium2Library. The history of two libraries are explained in the user [README.rst:](https://github.com/robotframework/SeleniumLibrary#versions)

**Comment by youarelev** [comment]
Thanks for explanation and links. Closing this issue.
