### ISSUE TITLE
Improve Documentation of Select Frame and Select Window

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/SeleniumLibrary#892]
When selecting a child frame (for example inside a `frameset`), we must go back to the main frame. There is no keyword for this, except `Select Window` without arguments. I propose to add text to `Select Window` to explain this, and to `Select Frame` to have reference to `Select Window`.
Add a note that frame or iframe are the same :)

Alternatively, modify `Select Frame` to accept `locator=None` and behave like `Select Window`.

**Comment by aaltat** [comment]
There is `Unselect Frame` which should return to the main, if I recall the code correctly. If using the unselect keyword is not clear from the ` Select Frame` keyword, the documentation could be enhanced.

**Comment by aaltat** [comment]
Done in #919

**Comment by pekkaklarck** [comment]
Enhancing documentation in general is covered by #925. I'll mark this as its duplicate.
