### ISSUE TITLE
Not able to Run Protractor Test on Firefox browser

### ISSUE THREAD

**Issue by makwanaparth94** [robotframework/SeleniumLibrary#893]
Failed: 
[INFO]     Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:54:15.039Z'
[INFO]     System info: host: 'MC0XSZYC', ip: '10.87.197.153', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
[INFO]     Driver info: driver.version:

Eclipse raised these issue while running test on firefox

![image](https://user-images.githubusercontent.com/28529639/30109798-4d7a966e-9325-11e7-8c9b-aaf4cca31f31.png)

**Comment by aaltat** [comment]
This is [Robot Framework](http://robotframework.org/) library/extension and I think you are reporting this issue to wrong issue tracker. This project does not support Protactor and therefore issue is closed.
