### ISSUE TITLE
proxy support is still missing in 1.0.1

### ISSUE THREAD

**Issue by adwu73** [robotframework/SeleniumLibrary#90]
I have tested 1.0.1 s2l, the proxy support is still missing. To use the proxy, you have to set the proxy in the desired capability to a dictionary of valye including httpProxy,proxyMode, etc. You can not do this using current Open Browser keyword, the current API doesn't handle recrusive setting like this:
proxy:{httpProxy:localhost:8580,proxyMode:MANUAL}

**Comment by SergiuTudos** [comment]
Is that you are not able to use the proxy at all, or recursively only as per your example?
I use 
 Open Browser  ${site}  ${browser}  None  True  "httpProxy:"0.0.0.0:8080"  None

And I have 
ValueError: too many values to unpack

**Comment by adwu73** [comment]
I got ValueError: too many values to unpack as well, this is because you got 2 : in the string "httpProxy:"0.0.0.0:8080"

**Comment by ombre42** [comment]
this is likely fixed by [Allow desired_capabilities= to be a dictionary](https://github.com/rtomac/robotframework-selenium2library/pull/165)

**Comment by emanlove** [comment]
Fixed in #252.
