### ISSUE TITLE
def _handle_alert has hard coded 5 seconds of wait, but must use selenium timeout value

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#917]
Hi

There is hard corded 5 seconds waiting time in keywords for browser alerts.
For example keyword **Confirm action**, if there is no alert will take 5 second until will be failed. The same for **Alert should be present**, etc. The main problem: it slows down tests. 

What I suggest:
this keywords must use **Selenium Timeout** which is defined within importing library or by **Set Selenium Timeout** keyword.

Example of code from keywords/alert.py
![alertpy](https://user-images.githubusercontent.com/1729590/30808621-8792329e-a207-11e7-832f-8cb99865d8ac.png)

**Comment by aaltat** [comment]
This is true and good suggestion. Would you like to make PR to fix it?

**Comment by pekkaklarck** [comment]
Closing this in favor of #942.
