### ISSUE TITLE
Get Alert Message |  dismiss=False --- doesn't work

### ISSUE THREAD

**Issue by chevi** [robotframework/SeleniumLibrary#927]
**Run test:**
```
Execute Javascript | confirm('Are you sure?')
Get Alert Message | dismiss=False
Capture Page Screenshot
```
**Result:**
With legacy Selenium2Library 1.8.0 - works fine, test passes
with 3.0.0b - fails, because dismiss=False doesn't work

**Comment by pekkaklarck** [comment]
The reason for the behavior change is that when you use `dismiss=False`, you end up passing `False` as a string to the keyword and in S2L 1.8 its implementation is this:

```python
    def get_alert_message(self, dismiss=True):
        if dismiss:
            return self._close_alert()
        else:
            return self._read_alert()
```

String `False` is considered true in Python, so `self._close_alert()` is executed.

In S(2)L 3.0 the library considers string `False` to be false (#719), so nowadays the `else` branch is executed instead.

We've actually just yesterday noticed that alert related keywords are a mess in general. Our current plan is to leave them as-is in 3.0 and pretty much rewrite them in 3.1, but this kind of issues make me think should we look at them a bit more closely already now.

**Comment by aaltat** [comment]
As Pekka did explain, the library functionality has changed how Boolean arguments are handled. This is also explained in the keyword documentation: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Boolean%20arguments

I also agree that we should take a closed look with `Alert ...` keywords in near future.

**Comment by pekkaklarck** [comment]
I added #933 about cleaning up alerts and have been looking at the current and v1.8 code related to them. It seems we have broken `Dismiss Alert` at some point, but `Get Alert Message` works like earlier except that string `False` is now handled differently. That part is covered by #719 which is already marked as backwards incompatible. I think this issue can be closed.
