### ISSUE TITLE
Check and fix `Get ... s` keyword not to fail if return value is empty

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#929]
Check keywords:
- [x] Get Cookies
- [x] Get List Items
- [x] Get Locations
- [x] Get Selected List Labels
- [x] Get Selected List Values
- [x] Get Window Identifiers 
- [x] Get Window Names
- [x] Get Window Titles

**Comment by aaltat** [comment]
Only `get_selected_list_values` and `get_selected_list_labels` fails if list is empty. Write new issue about fixing  those keywords.

**Comment by pekkaklarck** [comment]
New issue is #977.
