### ISSUE TITLE
"Open Browser" keyword crashes without error

### ISSUE THREAD

**Issue by eweseong** [robotframework/SeleniumLibrary#931]
I've been getting intermittent error when running a robot script, the intermittent error happens during the "Open Browser" keyword. From the VNC, the browser seems to be opened but the URL wasn't inserted into the browser. Below is the robot log and output.xml. Do note that it is intermittent error.
[log.zip](https://github.com/robotframework/SeleniumLibrary/files/1339679/log.zip)

Environment Info
operating system: Red Hat 7.2
python: 2.7
robotframework: 3.0.2
robotframework-selenium2library: 1.8.0
selenium: 3.5.0
geckodriver: 0.19.0
firefox: 55.0.3

It would also help if there's option to turn on the geckodriver log, from the documentation i couldn't see a valid ways to change the geckodriver log level. I've tried passing as desired capabilities and using the "Create Webdriver" keyword to pass in the log level. Both to no avail. Could you point me to the right direction in enabling the geckodriver log through selenium in robot framework?

**Comment by aaltat** [comment]
The geckodriver log options are not changed in the selenium side, but if I recall correctly, the log goes to the folder where test execution starts.

Perhaps most easiest way to debug the problem is to write a small Python script which does the same thing as `Open Browser`. Example this could work nicely
```
from selenium import webdriver

driver = webdriver.Firefox()
driver.get("http://www.python.org")
assert "Python" in driver.title
driver.close()
```
Save it to a file and run it from the Linux. If you experience with same kind of problem, then the problem is in the Selenium side and we in the SeleniumLibrary can not fix it. In this case, please raise an issue to the Selenium issue tracker.

**Comment by eweseong** [comment]
So currently there's no options to modify the log level from selenium side?

**Comment by aaltat** [comment]
Here is the Selenium API: http://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.firefox.webdriver

Only thing that directly relates to the geckodriver is setting the log file name.

**Comment by eweseong** [comment]
Is using the **firefox_options** argument with https://seleniumhq.github.io/selenium/docs/api/py/webdriver_firefox/selenium.webdriver.firefox.options.html#module-selenium.webdriver.firefox.options a viable option?

**Comment by aaltat** [comment]
I haven't looking into that direction for a long time,  because I don't actively test with Firefox in my day work. Reading the documents and trying out different options will give you better understanding than I have. Sorry that I can not help on this problem more.

**Comment by eweseong** [comment]
no worries, thanks for the comment and advice, i will try to identify the root of the issue between selenium v selenium-robot first

**Comment by eweseong** [comment]
In case anybody wishes to change the geckodriver log level, the following steps managed to do it for me:

`${options}=   Evaluate   sys.modules['selenium.webdriver.firefox.options'].Options()    sys, selenium.webdriver`
`Call Method   ${options}    add_argument    "log": {"level": "trace"}`
`Create Webdriver    Firefox   firefox_options=${options}`
`Go To   http://www.python.org`

**Comment by aaltat** [comment]
Nice to see that it's possible. If this turns to be a Selenium bug or something else related to underlying tools, would it be possible to get reference to the other project issue.

**Comment by eweseong** [comment]
it is a bug related to marionette, detail description of the issue can be found at [issue #979](https://github.com/mozilla/geckodriver/issues/979)
