### ISSUE TITLE
Add keyword to get all cookie information

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/SeleniumLibrary#932]
We currently have `Get Cookie Value` but it only returns the value, not other information such as expiry. We have few possibilities how this could be implemented:

1. Enhance the existing `Get Cookie Value` to allow returning other info too. For backwards compatibility reasons its default behavior cannot change, but it could get a new optional argument like `info='value'` that could be used like this:

        ${value} =    Get Cookie Value    name
        Log    ${value}
        ${expiry} =    Get Cookie Value    name    info=expiry
        Log    ${expiry}

2. Add separate new keyword like `Get Cookie` or `Get Cookie Information` that returns a custom object containing all cookie information in its attributes. This info could then be used in the data easily:

        ${cookie} =    Get Cookie    name
        Log    ${cookie.value}
        Log    ${cookie.expiry}

3. Enhance the existing `Get Cookie Value` to return an object with all the cookie information.

My favorite is option 2. If we decide to do that, then we could consider deprecating the existing `Get Cookie Value`. We should also think what to do with the current `Get Cookies` which returns a string in format `cookie1=value1; cookie2=value2`. It should rather return a list of cookie objects, but that change would be backwards incompatible. I have an idea how it could be deprecated pretty gracefully, though.

**Comment by pekkaklarck** [comment]
I add this into SL 3.0 rc 1 scope because some kind of a way to get the expiry value would be needed by #891. If adding a new object and deprecations it would require is too much work, we can in SL 3.0 simply enhance the existing `Get Cookie Value`.

**Comment by aaltat** [comment]
I think that option 2 would be best but it might be challenging to do in the 3.0 scope. Then doing the option 1 would be nice.

**Comment by pekkaklarck** [comment]
One thing to decide, regardless how we decide to return the information, is how to represent the expiry time. Apparently browsers store them in seconds (since EPOCH?) except for Safari that uses milliseconds. We should always use the same format, regardless the browser, and I don't think a plain integer (or float) is the best representation.

Probably the best idea would be using Python's standard [datetime object](https://docs.python.org/2/library/datetime.html#datetime-objects). They have useful attributes that can be accessed in data like `${expiry.year}` and they are fully supported also by Robot's own [DateTime library](http://robotframework.org/robotframework/latest/libraries/DateTime.html). Regardless the format we use, the same format should be accepted as an input when setting the expiry time (#891).

**Comment by aaltat** [comment]
I don't have knowledge how the expiry date of the cookie is stored. Is it possible that other formats than epoch is supported? By quickly googling it looks like that: https://stackoverflow.com/questions/6556930/python-persistent-cookie-generate-expires-field and 
https://en.m.wikipedia.org/wiki/HTTP_cookie

**Comment by aaltat** [comment]
Done in #930

**Comment by pekkaklarck** [comment]
Attributes provided by the returned object should be documented. Using a table for attributes and adding some usage examples similarly as with [Process library's Result object](http://robotframework.org/robotframework/latest/libraries/Process.html#Result%20object) ought to work well.

Should also add a note that this keyword was added in SL 3.0.
