### ISSUE TITLE
Keyword definition and Variable definition not found error

### ISSUE THREAD

**Issue by Zabi-Py** [robotframework/SeleniumLibrary#937]
1. Keyword definition not found error is being raised for SeleniumLibrary keywords. 
2. Autocomplete is also not working. 
3. Variable definition not found error is raised even after importing resource file.
Can you please resolve this issue.

 RobotFramework = 3.0.2  robotframework-seleniumlibrary = 3.0.0.b3

**Comment by aaltat** [comment]
Is this a problem in some editor or plugin you are using? And this is not related when test are run?

**Comment by Zabi-Py** [comment]
Not sure. Some keywords like "sleep,log, should be equal as strings,set global variable, run keyword if" are recognized while some other keywords like "click element,get text,page should contain element" throw Keyword defi

**Comment by Zabi-Py** [comment]
*throw keyword definition not found error.  Some tests ran fine, while some failed. Just fyi these test cases ran fine in older versions of SeleniumLibrary

**Comment by aaltat** [comment]
If this is a plugin related problem, then please raise an issue to the plugin developer issue tracker.

There has been lot of changes since release 1.8.0 and therefore it's possible that you have found a real problem in the library itself. For further assist we would example need a simple example, which I can run, that demonstrates the problem.

**Comment by Zabi-Py** [comment]
I have raised an issue there as well. I couldn't figure where could be the issue (Library or plugin). I just rolled back to Selenium2library 1.8.0 and things are working fine now.

Have attached the script i'm using.
[Robots.zip](https://github.com/robotframework/SeleniumLibrary/files/1349107/Robots.zip)

**Comment by aaltat** [comment]
The report looks like all test did succeed, so it does not look like a problem with the SeleniumLibrary.

SeleniumLibrary internal architecture has been changed a lot and example Robot Framework Library API has been changed to [Dynamic Library](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#different-test-library-apis) API. I have heard that many plugin or editors do not support the Dynamic library. Therefore raise an issue to your plugin developer issue tracker.

**Comment by Zabi-Py** [comment]
Aaltat that test report belongs to Selenium2library 1.8.0.

**Comment by aaltat** [comment]
Is there something that you need from us, more details perhaps? Or is there some other reason why you did reopen the issue?

**Comment by Zabi-Py** [comment]
Please read my previous comment. It seems to be an issue with the library as well I guess.

**Comment by pekkaklarck** [comment]
I read the comments and didn't find anything indicating this would be an issue in SeleniumLibrary. Notice also that libraries aren't in general responsible on locating keywords or variables.

I close this issue again. Please reopen it *only* if you have concrete information that indicates that the problem would be in SeleniumLibrary.

**Comment by aaltat** [comment]
I am sorry but I am not able to understand what is your problem. Could you explain the problem more clearly? Example provide the stack trace of the error you are getting when you execute the test. Also example which we can also run and demonstrates the problem are really useful too.
