### ISSUE TITLE
[Documentation] - Add how to use xpath to click text

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#938]
based on https://github.com/robotframework/SeleniumLibrary/issues/533 ,
i suggest to add this example that permits to Click Element where text contains

Click Element By Text
	[Arguments]			${text}
	Click Element 		xpath=//*[contains(text(),'${text}')]

**Comment by aaltat** [comment]
Would you like to provide a PR to fix the issue?

**Comment by andreabisello** [comment]
@aaltat sure. i would to do this, but i don't know what i should to edit because https://github.com/robotframework/SeleniumLibrary/blob/master/docs/SeleniumLibrary.html is autogenerated. How i can learn how to improve documentation? You make a big work, and i want to help too, but i don't know how to do. Can you help me? thanks.

**Comment by aaltat** [comment]
The keyword documentation is generated from the source code and from the methods which implements the keywords. Example `Click Element` is here: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L423

If you edit the method doc string, it will also update the keyword documentation in the next release.

**Comment by andreabisello** [comment]
@aaltat very good.

**Comment by aaltat** [comment]
The keyword documentation currently uses different mixture of styles, unfortunately. If you need to take an example, please see the library [__init__.py](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py) and more details can be found from the User Guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#documenting-libraries

**Comment by andreabisello** [comment]
@aaltat in fact i'm editing __ init __.py

**Comment by andreabisello** [comment]
@aaltat not sure if this is correct, but i created a pull request https://github.com/robotframework/SeleniumLibrary/pull/940

**Comment by pekkaklarck** [comment]
This has been fixed by 4724be0.
