### ISSUE TITLE
Get Text in Sel2Lib please

### ISSUE THREAD

**Issue by hemakannan** [robotframework/SeleniumLibrary#94]
Can we pls bring back this function/keyword.. Its a total awesome keyword that definitely should be a part of Sel2Lib.

**Comment by emanlove** [comment]
On 08/22/2012 11:08 PM, hemakannan wrote:

> Can we pls bring back this function/keyword.. Its a total awesome 
> keyword that definitely should be a part of Sel2Lib.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/rtomac/robotframework-selenium2library/issues/94.

This change has been commited and will be in the next release.  If you 
require this change sooner you can either grab the main branch or cherry 
pick out the commit.

Ed

**Comment by hemakannan** [comment]
Yay ! Thank you so much....
I hope the add location strategy is also brought back into sel2lib. Jeremy said he was going to look at it (https://github.com/rtomac/robotframework-selenium2library/issues/77). If that also is brought in, there is nothing holding us back to port over to Sel2Lib. Crossing my fingers.
Thank you so much guys for supporting this awesome framework !

**Comment by hemakannan** [comment]
Oh BTW when will the next release be. I can wait until then.

**Comment by emanlove** [comment]
On 08/22/2012 11:29 PM, hemakannan wrote:

> Oh BTW when will the next release be. I can wait until then.
> 
> ---
> 
> Reply to this email directly or view it on GitHub 
> https://github.com/rtomac/robotframework-selenium2library/issues/94#issuecomment-7959063. 

Hopefully in the next couple of weeks.  There was an issue with Selenium 
2.25.0 which was causing the internal tests to fail.  That has been 
taken care of but I did notice one more issue with a drag and drop 
test.  So I need to look into that when I get some time.

**Comment by hemakannan** [comment]
ok, great. Thanks so much. I will close this ticket.

**Comment by PriyaAn** [comment]
Is selenium2library with "getText" keyword released??

**Comment by emanlove** [comment]
> Is selenium2library with "getText" keyword released??
> 
> It is within the main branch but has not yet been released.  We are 
> trying and I would like to see us cut a release by Friday, Sept 28, 
> 2012. In the mean time you can grab the source from 
> https://github.com/rtomac/robotframework-selenium2library

   git clone git://github.com/rtomac/robotframework-selenium2library.git 
rf-s2l

**Comment by PriyaAn** [comment]
Thank You So Much...

**Comment by PriyaAn** [comment]
Is it released on 28th September?

**Comment by emanlove** [comment]
No its has not yet been released.  We will announce the release on robotframework mailing list.

**Comment by ombre42** [comment]
not sure if anyone notice issue #115. get text does not throw exception if element is not found

**Comment by emanlove** [comment]
Looking into this now. One issues I am seeing is that we are inconsistent with our error reporting when an element is not located.  We have

```
raise ValueError("Element '%s' not found." % (locator))

raise AssertionError("ERROR: Element %s not found." % (locator))

raise ValueError("Element locator '" + locator + "' did not match any elements.")
```

I think the last is the best solution as it captures most instances of unlocatable elements. Also this issues also effects 'Element Should Contain' for which looking at the code will present a similar issue if an element is not found.

**Comment by emanlove** [comment]
'Get Text' and 'Element Should Contain' now throws exception if element is not found. See #127.

**Comment by shrutishrivastava** [comment]
Is there any update regarding getText functionality?
Is it possible to create our own keyword for getText?
If yes, Please share the procedure.

**Comment by Arpitha10** [comment]
Just came across this thread while searching solution for my issue. I'm using Get Text in Robot. I can say behaviour is different of Selenium2Library. I get my text in SeleniumLibrary but not in Selenium2Library. Any input on this.

**Comment by aaltat** [comment]
The underlying functionality of selenium RC, which SeleniumLibrary is using and selenium webdriver, which Selenium2Library is using may be different. 

Because this issue was requested for a new keyword and it seems that you are having difficulty to get the text with the keyword. They are different things and therefore would it be possible to open a new issue and explain your problem with better details.

**Comment by Arpitha10** [comment]
Sure. Please find it here . 

https://github.com/robotframework/Selenium2Library/issues/588
