### ISSUE TITLE
Change self.browser to self.webdriver

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#946]
Because ElementFinder supports finding elements also with WebElement it would be good to refactor `browser` to `webdriver` or `driver` in code side.

Deprecate the `browser` in next release candidate and remove it in release after that.

**Comment by pekkaklarck** [comment]
Public API is covered by #882. I reopened it with a comment that we are going to rename `browser` to `webdriver`. This issue can now be closed as its duplicate.
