### ISSUE TITLE
Enhancements to getting and validating element counts

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#949]
- Deprecate `Locator Should Match X Times`, `Xpath Should Match X Times` and `Get Matching Xpath Count`. 
- Instead `Locator Should Match X Times` and `Xpath Should Match X Times` users should use: `Page Should Contain Element` keyword with `limit` argument. 
- Instead of `Get Matching Xpath Count` create `Get Matching Locator Count`.

**Comment by pekkaklarck** [comment]
As discussed in comments of PR #950, the plan is that `Get Matching Locator Count` returns an integer, not string. This is different to `Get Matching Xpath Count`.

**Comment by aaltat** [comment]
Discussed with Pekka and we did decide the following: 
- Rename `Get Matching Locator Count` to  `Get Element Count` 
- Deprecate silently also `Locator Should Match X Times` and enhance `Page Should Contain Element` to take in optional `count` argument
- When `Page Should Contain Element` keyword `count is None` it should match to one or more elements. Just like the current keyword works
- When `count` is number it should fail if number elements does not match.
- Optional, `count` could be also a range, defined like `x..y`. Where x < y. Keyword should pass if `x <= element count <= y`

**Comment by aaltat** [comment]
Decided not to do `x..y` support in this issue. It is useful feature but, it is more important to get 3.0 rc1 out.

**Comment by pekkaklarck** [comment]
The original issue description is outdated and needs to be updated. The title isn't ideal either as it doesn't mention the newly added `Get Element Count` nor enhancements to `Page Should Contain Element`. Perhaps the title should be something generic like `Enhancements to getting and validating element counts`. I reopen this issue until we get at least the misleading description fixed.

**Comment by aaltat** [comment]
Fixed title and initial description. Closing issue.
