### ISSUE TITLE
Capture Page Screenshot can't capture window

### ISSUE THREAD

**Issue by wingking** [robotframework/SeleniumLibrary#95]
when login web with  a wrong password, it pop a window.
if you do something,it will fail, and auto avoke .Capture Page Screenshot.
but it can not capture the message window, and will disappear the window, so i can use take screenshot (robot framework library) to capture it either.

robotframework 2.7.3
s2l: 1.0.0
win xp sp3

**Comment by emanlove** [comment]
@wingking If you are still experiencing this issue please reopen this issue report or, even better, post a question to the robotframework-users mailing list, http://groups.google.com/group/robotframework-users.
