### ISSUE TITLE
All silently deprecated keyword in 3.0 should be deprecated with warning.

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#963]
In 3.0 release there was lot of keyword which where silently deprecated. In 3.1 they must be deprecated with proper warning to the users.

**Comment by rubygeek** [comment]
by "silently deprecated" do you mean those keywords that have deprecated message in the doc string like here? https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/element.py#L166

**Comment by pekkaklarck** [comment]
Yes. It's easy to turn these into "loud warnings":
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#deprecating-keywords
