### ISSUE TITLE
Update 'Library  Selenium2Library' keyword documentation and examples

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#97]
The documentation examples for the Selenium2Library are invalid and wrong.  We added another parameter, implicit_wait, to the library initialization but I forgot to update the documentation string.

**Comment by emanlove** [comment]
We should also update the main library documentation section ["Timeouts"](http://rtomac.github.com/robotframework-selenium2library/doc/Selenium2Library.html#introduction) with information about the new implicit_wait functionality and a link to the [selenium documentation](http://seleniumhq.org/docs/04_webdriver_advanced.html#explicit-and-implicit-waits) on the topic.

**Comment by emanlove** [comment]
The documentation examples have been updated but the ["Timeouts" ](http://rtomac.github.com/robotframework-selenium2library/doc/Selenium2Library.html#introduction) section could be improved with information about implicit_wait. Could also add note in "Timeouts" section about why there is, in general, no need for a 'Wait For Page To Load' keyword (See #107). Push completing this issue to 1.2 release.

**Comment by emanlove** [comment]
Should also add a sentence or two about not setting both timeout and implicit wait to a non-zero value at the same time. See [this discussion](https://groups.google.com/forum/?fromgroups=#!topic/selenium-users/C71oDod5Vvg) as to why not.

**Comment by aaltat** [comment]
Ed, do you feel that this is still valid issue?

**Comment by emanlove** [comment]
Yes, let's keep this one open. Scheduled for 1.8 release.

**Comment by aaltat** [comment]
Removed 1,8 milestone because of lack of time.

**Comment by pekkaklarck** [comment]
These docs have been highly enhanced as part of #924 and enhancements will be part of SL 3.0 rc 1. The latest version of the docs are here at http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html.
