### ISSUE TITLE
win 10 ie 11 webdriver 3.6 Capture Page Screenshot doesn't capture what the browser is rendering

### ISSUE THREAD

**Issue by andreabisello** [robotframework/SeleniumLibrary#973]
This is what the browser is rendering

![image](https://user-images.githubusercontent.com/2149815/32062641-5ecccaf0-ba75-11e7-8727-4ade6e02e216.png)

this is the Captured image

![image](https://user-images.githubusercontent.com/2149815/32062804-da8c37a2-ba75-11e7-928b-9b2a0926d828.png)

Whare are the left and right colum gone?

this is a my customer web application, so i cannot share a test page.

any suggestion for a debugging purpose?

thanks

**Comment by aaltat** [comment]
It could be timing issue, if you put a sleep before the screen capture, does is the image then correct?

**Comment by andreabisello** [comment]
I already wait a lot of seconds before creating the screenshot on a interface that needs no more than 2-3 seconds to be loaded.

Baseline Creation
	[Arguments]				${WHAT}
	Sleep					10s
	Log To Console 			Creando ${WHAT}
	Sleep					15s
	Capture Page Screenshot			img${/}${BROWSER}${/}${WHAT}
	Sleep					5s
    Reload Sikuli Image

i also wait 5 seconds after the screenshot creation to avoid write on disk time issue

**Comment by aaltat** [comment]
I see, then it's not a timing issue. The`Capture Page Screenshot` is really thin wrapper on top of the Selenium and I would suspect that is, again, problem in the IEDriver. Would you happen to be able to create an example which we all can execute. Then it would be easy to see where the problem is and most likely to push on the Selenium issue tracker.

**Comment by andreabisello** [comment]
@aaltat yes. i'll make a test on a public website searching for somewhere the issue can be reproduced

**Comment by andreabisello** [comment]
https://github.com/SeleniumHQ/selenium/issues/4973
