### ISSUE TITLE
Wait until element is focused

### ISSUE THREAD

**Issue by jsevern55** [robotframework/SeleniumLibrary#975]
I created 'Wait until element is focused' in waiting.py. It works well, and I was hoping it could be added to the SeleniumLibrary

```
    @keyword
    def wait_until_element_is_focused(self, locator, timeout=None, error=None):
        """Waits until element specified with 'locator' is focused
        
        Key attributes for arbitrary elements are `id` and `name`. See
        `introduction` for details about locating elements.

        New in SeleniumLibrary 2.0.1.
        """
        def check_focus():
            element = self.find_element(locator)
            try:
                focused = self.browser.execute_script('return document.activeElement;')
            except (IOError, RuntimeError) as err:
                raise AssertionError("Internal Error: '%s'" % (err))
            if not element == focused:
                return error or "ERROR: Element '%s' is not with focus after %s." % (locator, self._format_timeout(timeout))
        self._wait_until_no_error(timeout, check_focus)
```

Is it possible to have this added?

**Comment by aaltat** [comment]
Your needs is a valid one and sounds like a good idea to have. Next you have to choose from few options.
1) You will create a pull request to contribute.
2) Wait someone else to create the pull request.
3) Pay someone to create the pull request.

If you want to go with option one, then next step is explained in here: https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst#code-contributions and after that it's good to read this one too: https://github.com/robotframework/SeleniumLibrary/blob/master/test/README.rst

If you want to go with option 2, then you you don't have to do anything,  except wait that someone else has a similar need and implements the your request. But it could be a long wait if no-one has a similar need.

Or if you want to go with option 3, then you will need to find the funding and rest of the stuff.

**Comment by pekkaklarck** [comment]
Could this be implemented somehow using Javascript so that the existing `Wait For Condition` could be used instead? Or could we add waiting support to the existing focus keywords? I don't have anything against adding this keyword, but I'm a bit concerned how many `Wait ...` keywords should we add to the library.

**Comment by aaltat** [comment]
There is actually Selenium method which returns the currently active element: [switch_to.active_element](http://selenium-python.readthedocs.io/api.html?highlight=switch_to.active_element#selenium.webdriver.remote.webdriver.WebDriver.switch_to). Although it seems work little bit [differently in FF than in Chrome](https://github.com/SeleniumHQ/selenium/issues/4983) I would still prefer using the Selenium method. But I think we could enhance the existing `Element Should Be Focused` keyword with timeout and custom error message.  

If the change with FF is permanent, then we could consider changing the `Element Should Be Focused` keyword to something like this: 

```
    @keyword
    def element_should_be_focused(self, locator):
        """Verifies that element identified with ``locator`` is focused.

        See the `Locating elements` section for details about the locator
        syntax.

        New in SeleniumLibrary 3.0.
        """
        element = self.find_element(locator)
        focused = self.browser.switch_to.active_element
        if self.browser.capabilities['browserName'] == "firefox":
            focused = focused.get('value')
        if element != focused:
            raise AssertionError("Element '%s' does not have focus." % locator)
```

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by humbienri** [comment]
Hmn, sorry to hear there's been not much traction on this.  I don't usually sit and browse over github issues for SeleniumLibrary but I noticed that the `Wait For Condition` is referenced back in Fall of 2017!  Didn't realize it was that old...yet doesn't get much usage? Guess no way to really tell until people start complaining or commenting about it.

I most definitely like the idea of adding a timeout to the `Should` keywords so as to avoid have to lead those `Should` keywords with `Wait` keywords and in the case of failures, then it's the `Wait` keywords that fail, not the `Should`.  Just seems to me that it leads to code bloat?
