### ISSUE TITLE
Table keywords should not log source if they fail

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#991]
Currently table related keywords logs the page source and user can define the level on which the logging happens. But the logging the source and defining logging level are not useful features. It would be better to remove the source logging and logging level definition. Instead it might be useful to allow user to define custom error message, if they want, if the table related keywords fails. 

Example `Table Cell Should Contain` keyword signature should have arguments: `locator`, `row`, `column`, `expected` and `message` and here is an example:
```
| Table Cell Should Contain | xpath: //table | row=1 | column=2 | expected=foo | message=User defined error message | 
````

**Comment by pekkaklarck** [comment]
Should in general go through which keywords log the source, see does it make sense with them, and also see if some other keyword should get that functionality. In addition to that, should check how `message` functionality is used in general. Perhaps we should add it to all `Should` keywords?

**Comment by aaltat** [comment]
Generally I feel that logging the source is useless, although there might be some rare cases where it could be useful. I have to say that my run on failure keyword, maximize the browser, take screenshot and logs the source, but I usually never actually look at the source dump. Therefore I feel that we should remove the source logging from all keywords. Also unifying the `message` argument is a good idea.

It would be good idea to ask also other users opinion on the matter after the 3.0 release.

**Comment by aaltat** [comment]
It looks like all table keywords use `loglevel` only to control the logging when failure happens. It would be backwards incompatible just to remove the argument, because it is likely that it will make lot of test to fail. Instead I see two choices: 

1. Change the `loglevel=INFO` to `loglevel=TRACE`. In this way the default Robot Framework logging level, `INFO`, does not log the page source. 

1. Deprecate the argument. First silently, by setting the value to `loglevel=None` and only log if the level is actually defined (in SL 3.3.0 release): Then in the SL 3.4.0 release display warning and finally in SL 3.5.0 remove the argument.

**Comment by pekkaklarck** [comment]
I think both `loglevel=None` (i.e. not logging anything by default) and using `loglevel=TRACE` are fine. In both cases I'd leave the `loglevel` argument to avoid the extra work required by deprecation and to allow logging the source if it's actually needed.

**Comment by aaltat** [comment]
Closing this issue because this is replaced by #1259
