### ISSUE TITLE
Element Should Be Focused keyword should use driver.switch_to.active_element also with Firefox

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#998]
With selenium 3.6.0 (or smaller) and when using Firefox (with geckodriver) this `driver.switch_to.active_element` returns a dictionary which contains the a `WebElement`. Starting from Selenium 3.7.0 this is fixed and `driver.switch_to.active_element` returns directly a `WebElement`. Change the SeleniumLibrary: 
1. Use `driver.switch_to.active_element` always 
2. Support both Selenium 3.6.0 and 3.7.0

**Comment by pekkaklarck** [comment]
Element Should Be Focused was a new keyword added in 3.0 (#851). Fixes to it don't really belong to 3.0 release notes.
